### PR TITLE
[Feature] Reusable contact info

### LINKED ISSUE #5174: Per page contact information block
# Story

As an editor, I would like to reference a unit in my organization that has contact information and display it on the page similar to hr.uiowa.edu (v2)

# Additional notes

This is a requested feature from UIHC lab sites and Pentacrest Museums (https://wiki.uiowa.edu/display/drupaldev/Customer+Feature+Requests)

HR would also benefit from this in moving to V3.

# Proposed solution

- [ ] Bring HR's "Unit" taxonomy, page reference field and contact block to default and make available in the default template/more.

### LINKED ISSUE #8078: Reusable Contact Info
# Story

As a Registrar site owner, I would like to be able to place unit contact info on pages and have that info maintained in a single place so that we don't have to update multiple pages every time unit contact info changes.

# Additional Info

The current live site has a "Registrar Contacts" taxonomy, which is rabbit holed, where they maintain the contact information. They can then reference this taxonomy on "Pages" so it can be displayed on multiple pages and maintained in one place.

They also have a display of all "Registrar Contacts" on the contact page. https://registrar.uiowa.edu/contact.

"Registrar Contacts" have the following fields:

- Name
- Location - Address components
- Phone - multiple
- Fax
- Email - required
- Description - text area - filtered html
- Map link - not needed

They want something similar but would be ok with placing a layout builder block which would output the contact information for the unit chosen.

Display all contact information if added. No need to go to the entity.

# Question

Is this something that we should be adding for the service and not just Registrar?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/8078. 
Resolves https://github.com/uiowa/uiowa/issues/5174. 

Review https://github.com/uiowa/uids/pull/939. 

# How to test
- Code review
  - Is `uiowa_core` the best place for the contact specific code?
  - Review the `uiowa_core_clean_address_fields` helper function for the address used by lawinrc and the contact feature.

```
ddev blt ds --site=default  && ddev drush @default.local config-split:activate contact -y && ddev drush @default.local uli  /node/add/contact  
```

**Optional devel_generate option:**

```
 ddev blt ds --site=default  && ddev drush @default.local config-split:activate contact -y && ddev drush @default.local en devel_generate && ddev drush @default.local devel-generate:content 40 --bundles contact && ddev drush @default.local uli    /node/add/page
```

- Create a contact node.
- Try to add the node to a page through the featured content block. 
- Review for content type best practices: https://docs.prod.drupal.uiowa.edu/development-workflow/content-type-best-practices.   Some were previously set for now.uiowa.edu but we can adjust. 
- Test adding a contact node and verify that address country doesn't render.

## now.uiowa.edu

```
ddev blt ds --site=now.uiowa.edu  && ddev drush @now.local uli /admin/content
```

- Check existing contact nodes for new fields and/or data loss
- Check existing points of contact https://now.uiowa.ddev.site/news/2024/09/ui-seeks-iowa-board-regents-approval-3-facilities-projects

- [x] Attach uids merged hash from https://github.com/uiowa/uids/pull/939

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Opinions on whether this should also close out https://github.com/uiowa/uiowa/issues/5174?

**Comment by joewhitsitt** [comment]
Pulling down to start testing

**Comment by joewhitsitt** [comment]
>Is uiowa_core the best place for the contact specific code? Review the uiowa_core_clean_address_fields helper function for the address used by lawinrc and the contact feature.

I'd say it is fine. We also have similar code in sitenow_events, sitenow_people and admissions_core. Is now a good time to see about consolidating those as well?

**Comment by bspeare** [comment]
> I'd say it is fine. We also have similar code in sitenow_events, sitenow_people and admissions_core. Is now a good time to see about consolidating those as well?

I can update those here.  I don't see it in admissions_core - do you know where that is?

**Comment by joewhitsitt** [comment]
Oops. you are right. Something different for field_person_hometown and admissions_core_preprocess_field on Admissions. I was just doing a search for `country_code`

**Comment by joewhitsitt** [comment]
Screenshot 2024-10-03 at 8 50 58 AM

Wonder if we can get away with just `Phone` similar to `Email` and `Fax`. Also, these are currently comma-separated but then split out on separate lines.

When I do a config-split:export contact on the default site when the feature is enabled, I get a bunch more patched config related to articles and the field being present there. Should that be captured?

**Comment by bspeare** [comment]
> When I do a config-split:export contact on the default site when the feature is enabled, I get a bunch more patched config related to articles and the field being present there. Should that be captured?

Good question.  What do we do with all of that extra config?

**Comment by joewhitsitt** [comment]
From what I am seeing, the article/patch ones are expected and should be captured to ensure field visibility/weight, etc. are consistent each deployment.

Something ain't right with the split, causing a full export of config/features/contact/field.field.block_content.featured_content.field_featured_content_item.yml when there is a partial already.

config/features/contact/field.field.node.article.field_contact_reference.yml and config/features/contact/field.storage.node.field_contact_reference.yml are unique to the feature and should be complete items.

**Comment by joewhitsitt** [comment]
Locally, I am having better luck with

```diff
diff --git a/config/default/config_split.config_split.contact.yml b/config/default/config_split.config_split.contact.yml
index f6ca44386..958a04ba3 100644
--- a/config/default/config_split.config_split.contact.yml
+++ b/config/default/config_split.config_split.contact.yml
@@ -15,13 +15,16 @@ complete_list:
   - core.base_field_override.node.contact.promote
   - metatag.metatag_defaults.node__contact
   - node.type.contact
-  - pathauto.pattern.contact
   - simple_sitemap.bundle_settings.default.node.contact
+  - pathauto.pattern.contact
   - 'core.entity_form_display.node.contact.*'
   - 'core.entity_view_display.node.contact.*'
   - 'field.storage.node.field_contact_*'
+  - 'core.entity_view_display.node.article.default'
 partial_list:
-  - metatag.settings
   - field.field.block_content.featured_content.field_featured_content_item
+  - metatag.settings
   - workflows.workflow.editorial
   - 'user.role.*'
+  - 'core.entity_form_display.node.article.*'
+  - 'core.entity_view_display.node.article.*'
```

But there still seems to be issues with the featured content block. It might need a cex on the default first.

Whatever is changed in the default related to featured content and articles, will then need to cascade and update the contact feature, and so on to the now site split.

The ideal is that when we run a cex or config-split:export, it should come back clean

**Comment by bspeare** [comment]
@joewhitsitt the articles and reference stuff was coming from `- 'field.storage.node.field_contact_*'` and I removed that in https://github.com/uiowa/uiowa/pull/8115/commits/8eb2f38220005ddb357526856b41750bf2efb67a.

**Comment by joewhitsitt** [comment]
To me, that sounds incomplete then. If this field exists on the default article content type, the article content type's config changes and should be accounted for in the split.

Just like https://github.com/uiowa/uiowa/tree/main/config/features/grad_person_extended or https://github.com/uiowa/uiowa/tree/main/config/features/periodical, extra fields, modify the content type, we account for it in the split.

**Comment by joewhitsitt** [comment]
Ben explained that the article reference field is not in-scope for this slice. Nevermind

**Comment by joewhitsitt** [comment]
So then, do we need a post-deploy task to clean up the now split? Aka remove `config/sites/now.uiowa.edu/node.type.contact.yml` etc.?

**Review by joewhitsitt — APPROVED** [review]
Looks good. Sorry for the confusion earlier.

**Comment by bspeare** [comment]
> So then, do we need a post-deploy task to clean up the now split? Aka remove `config/sites/now.uiowa.edu/node.type.contact.yml` etc.?

Good question.  I thought I had deleted it but I just removed it in https://github.com/uiowa/uiowa/pull/8115/commits/6529a8edb98f94d87c7cbdd58f7b0ca6c1f645ef.   Can you sync this one more time with now.uiowa.edu?

**Comment by joewhitsitt** [comment]
I think that worked. Thanks for the change

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
