### PR TITLE
Replace medium image style with square 384 in sitenow_events.

### PR DESCRIPTION
**Pull request by richardbporter**
Otherwise the non-existent medium causes a whitescreen.

### CODE REVIEW

**Review by pyrello — APPROVED** [review]
Reviewed, not tested. Probably in the long run we should think about making this responsive.

**Comment by richardbporter** [comment]
If its as simple as using that machine name, I can change it now. What is it?

**Comment by pyrello** [comment]
It's not that simple. It is a different array structure, I think.

**Comment by joewhitsitt** [comment]
it isn't that simple. you are hardcoding a render array and i think it expects a single image style here not a responsive collection

**Pull request merged**
