### PR TITLE
[ITS] Support article updates

### LINKED ISSUE #7462: ITS Support Article Feedback
- They would like the category reference field to be a select list or radios rather than an autocomplete.
- They don't want the ability for folks creating support articles to set a custom url alias.
- They would like the url pattern to be `services/[service]/[support article title]`
- They would like the breadcrumb to output `Home / Services / [Service] / [support article title]`
- They would like to display the support article number and last udated date at the bottom of a support article rather than the sidebar. The service and category do not need displayed since the service will be available in breadcrumb and category link doesn't add value.
- Probably need to rabbit hole the category terms?

# Proposed Solution
```[tasklist]
### Tasks
- [x] Convert category reference field to use radios
- [x] Hide URL alias field group for non-admins
- [x] Update URL alias pattern to `/services/[service-title]/[article-title]`
- [x] Ensure that breadcrumbs display as `Home / Services / [Service Title] / [Article Title]`
- [x] Remove Category and Service from full node display
- [x] Move article number and last updated to the bottom of the page
- [x] Rabbit hole category vocab
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
Tracks https://github.com/uiowa/uiowa/issues/7462

## To test:

1. `ddev blt ds --site=its.uiowa.edu && ddev drush @its.local uli`
2. Look at the [checklist here.](https://github.com/uiowa/uiowa/issues/7462)
4. Go through each item, and ensure that each item is resolved.
5. Are there things that I missed?

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Based on @cory-skeers 's [comment here](https://github.com/uiowa/uiowa/issues/7462#issuecomment-2007574086), I think we have met the conditions of done for this issue. I will make some testing instructions.

**Comment by joewhitsitt** [comment]
I think I am confused by the original IS and the [comment](https://github.com/uiowa/uiowa/issues/7462#issuecomment-1992507789) from the recent meeting:

>url patterns
>not completely sure that the URL patterns are set in stone. Adrian said that she felt like the current pattern is correct, but it is a big change so they want Tracy to sign off on it. Big agreement on the pattern, but want leadership signoff.
>Support article number

So should it be node:title or nid for the URL path?

**Comment by pyrello** [comment]
> I think I am confused by the original IS and the [comment](https://github.com/uiowa/uiowa/issues/7462#issuecomment-1992507789) from the recent meeting:
> 
> > url patterns
> > not completely sure that the URL patterns are set in stone. Adrian said that she felt like the current pattern is correct, but it is a big change so they want Tracy to sign off on it. Big agreement on the pattern, but want leadership signoff.
> > Support article number
> 
> So should it be node:title or nid for the URL path?

Unless its changed since I last knew, I thought it was supposed to be `/services/[service-title]/[article-title]`. They would still use `/node/[nid]` internally.

**Comment by GaryRidgway** [comment]
> > I think I am confused by the original IS and the [comment](https://github.com/uiowa/uiowa/issues/7462#issuecomment-1992507789) from the recent meeting:
> > > url patterns
> > > not completely sure that the URL patterns are set in stone. Adrian said that she felt like the current pattern is correct, but it is a big change so they want Tracy to sign off on it. Big agreement on the pattern, but want leadership signoff.
> > > Support article number
> > 
> > 
> > So should it be node:title or nid for the URL path?
> 
> Unless its changed since I last knew, I thought it was supposed to be `/services/[service-title]/[article-title]`. They would still use `/node/[nid]` internally.

I think I have this configured correctly then, correct me if I am wrong?

**Comment by pyrello** [comment]
> I think I have this configured correctly then, correct me if I am wrong?

It looked right, or close to right when I looked at the code changes.

**Comment by e-marie-w** [comment]
Just to double-check, we do want the category to be multiselect checkboxes, instead of radios as listed in the issue checklist?

Also, nearly everything is removed from the edit form sidebar, not just the URL alias section, is that the desired outcome?

Lastly, just noting that if they plan to keep the already created support articles we'll need to resave them for the new URL pattern and breadcrumbs to take effect.

**Review by e-marie-w — APPROVED** [review]
Confirmed in Slack that the differences I noticed were intentional. Updated alias and breadcrumb patterns are showing as intended, and the URL alias is hidden for non-admins. Category is now multiselect instead of autocomplete, and it and the service do not display on the full node anymore. Article number and last updated date now display at bottom of the article. Lastly, the category taxonomy rabbit hole is working.

Great job!!

**Comment by GaryRidgway** [comment]
> Lastly, just noting that if they plan to keep the already created support articles we'll need to resave them for the new URL pattern and breadcrumbs to take effect.

Should we do an update hook for this or is it fine to do it manually?

**Comment by briand44** [comment]
We are going to migrate support articles so any support articles that exist now are just for testing purposes, I wouldn't invest in an update hook.

**Pull request merged**
