### PR TITLE
I2351 events card options

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #2351

Long, round about way of adding card style options to events blocks in v3. This is a forked branch of https://github.com/uiowa/uiowa/pull/2730 which removes the changes made to articles/people blocks until we can figure out the best path forward as it relates to views paging.

# To Test

## HR
This PR should not affect HR's website. Events listings should look the same as it is sub-themed off uiowa_bootstrap.

## v2 Websites (e.g. hawkeyemarchingband, diversity, law, brand)

Check list/grid/masonry style options for events. Should look the same.
## v3 Websites (e.g. sandbox, uiowa, admissions, grad, international)

Existing events blocks should be set with PROD defaults and look similar (left-aligned content, left-aligned small circle image with border)

New events blocks should have the following defaults with the option labels showing (default) appended. White background, left-aligned content, left-aligned small circle image with border

Changes between widescreen image and square/circle should change the image view mode and clear necessary caches.

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling this down to test.

**Comment by bspeare** [comment]
Tested on `v2` HMB.  Looks like we need one override on the list style to remove the extra margin that has been added for left and right positioning. 


Screen Shot 2021-01-08 at 10 22 28 AM

**Comment by bspeare** [comment]
@joewhitsitt I've tested this on HMB and Admissions and I'd be happy to approve it once https://github.com/uiowa/uiowa/pull/2811#issuecomment-756853758 is resolved.

**Comment by joewhitsitt** [comment]
@bspeare sorry if I didn't understand correctly. 10f891b i get lost in uids_base.

**Comment by bspeare** [comment]
@joewhitsitt You got it right.  It looks like we may need to adjust it to:

```
  &.card--media-left,
      &.card--media-right {
        .paragraph--type--section:not([class*="bg-"]) & {
          margin-bottom: 0;
        }
      }
```

Let me know if you'd like me to add that.

**Comment by joewhitsitt** [comment]
Screen Shot 2021-01-08 at 3 51 01 PM
Screen Shot 2021-01-08 at 3 51 42 PM

**Review by bspeare — APPROVED** [review]
Looks good!  I have tested on HMB, Admissions, and Sandbox for the card events styles.

**Comment by joewhitsitt** [comment]
Thanks for your attention to detail through this and the previous PR @bspeare!

**Pull request merged**
