### PR TITLE
Block Grid Layout Overflow

### LINKED ISSUE #5946: Blocks in grid layouts overflow layout columns at smaller column widths
# Problem
As you can see with the four-column grid on https://csd.uiowa.edu/research, at smaller breakpoints the grid is no longer equal-width. 

Screen Shot 2022-11-14 at 1 59 03 PM

# Proposed solution
Items within grid layouts need a min-width to maintain the grid: https://css-tricks.com/preventing-a-grid-blowout/. 

- Add `min-width: 0` to https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L54. 

Once that is set, the grid widths are maintained but the cards will still overflow.  See details for more information:

<details>

Screen Shot 2022-11-14 at 2 01 49 PM

This line is causing the overflow: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L16.   Removing this line will cause words to break:

Screen Shot 2022-11-14 at 2 04 37 PM

Some options to fix that:
- Investigate implementing https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
- We could adjust this to use CSS clamp and container queries to adjust the sizing of these headings at these smaller widths to maintain 
- Break the grid into three columns earlier to maintain a certain width. 
- 
</details>

# Follow up tasks
- [x] https://github.com/uiowa/uiowa/issues/4678

### PR DESCRIPTION
**Pull request by makurj**
Resolves #5946 

### How to Test:
1. `blt ds` csd.uiowa.edu and default.
2. `yarn workspace uids_base build`
3. Check https://csd.uiowa.ddev.site/research at smaller breakpoints to make sure the grid (cards) is equal-width.
4. On default, create a four-column section with cards and see that the grid stays equal width.
5. If the text is overflowing, don't worry about it. That will be worked on in a [follow-up issue](https://github.com/uiowa/uiowa/issues/4678).

### CODE REVIEW

**Comment by makurj** [comment]
After 816ffe8 commit:

Chrome:
image

Safari:
image

**Comment by bspeare** [comment]
@makurj I updated the code.  The code line link that I had provided in the proposed solution had changed since the issue was created.

**Comment by bspeare** [comment]
Tested this with the code below and this fix still appears to work. 
```// This chooses the proper container for rendered content vs building in layout builder.
.fragment .layout__region,
.node__content .layout__region,
.layout-builder .layout-builder-block {
  container-type: inline-size;
  container-name: column;
}

```

**Review by bspeare — APPROVED** [review]
This looks good! Thanks @makurj!  I removed the line of code that was from the bad link in the proposed solution.

**Pull request merged**
