### PR TITLE
Person Additions

### PR DESCRIPTION
**Pull request by joewhitsitt**
- position, credentials, biography, image, short bio (teaser) fields
- credential field renders as a subtitle on node full by utilizing a new variable in an overridden block template.
- reduce extends in article and person CSS
- content type specific teaser labels
- start standardizing teaser markup

This is work towards feature parity.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Apparently there are some decisions on campus that would affect all of this. Waiting for more info.

**Comment by joewhitsitt** [comment]
Moving forward with local people until APR or whatever else comes down the pipeline.

**Comment by joewhitsitt** [comment]
I think this is ready to review. It would be nice to get another set of eyes on this.

**Comment by richardbporter** [comment]
A few things:

- The WYSIWYG is missing the padding we added in #232. Maybe we should scope that differently.
- Why is the image field in the collapsible?
- Why is the content description in the collapsible?
  - Also, is summary not a thing anymore?

The image was gigantic on the full content display until I compiled SASS locally. Gulp.

**Comment by joewhitsitt** [comment]
The image and the teaser are in the collapsible for consistency. Articles (now) and basic page (soon) have the same setup.

The decision to use field_teaser instead of a body summary was a long time ago, but I feel the language is different depending on the content. Article Summary, Short Biography, Content Description

**Comment by richardbporter** [comment]
03bfafb exports the credential field to be hidden on the minimal entity form display.

**Comment by richardbporter** [comment]
I can't review because I have not been requested but 👍

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
