### PR TITLE
Inline basic criticial CSS for uids_base theme.

### LINKED ISSUE #1368: Investigate adding critical_css module
# Problem

We have a 2s page rendering block on uiowa.edu that slows down the page load on mobile. 

# Proposed solution

Add https://github.com/addyosmani/critical to our gulp process so that we have the `critical.css` file ready to use with https://www.drupal.org/project/critical_css when the time comes.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1368 

Until SiteNow adopts uids_base (#371) this will need to target a remote URL but the default local site would be ideal.

I had trouble getting the Gulp example to work so this is only running post-build. If someone wants Gulp integration, feel free to give it a shot.

There is some discussion in #1368 about the rendering FOUC this causes. I tried to force include `.uiowa-bar .page__container` to fix the margin jank but no luck. Additional selectors can be added with more `--include .selector` options in the postbuild NPM script in uids_base/package.json.

### Testing
- Check out this branch locally.
- `vagrant provision`
- `blt sync --site uiowa.edu`
- `blt frontend`

You can then run `yarn workspace uids_base run postbuild` to build the critical CSS repeatedly. For example, after changing the script args/options in uids_base/package.json.

Note that caching/aggregation is disabled locally so jank is pretty bad. FireFox seems to have a hard time with this locally as well as on dev. Chrome seems to render it fine except on a hard refresh which disables caching.

### CODE REVIEW

**Comment by bspeare** [comment]
I got this error during `blt frontend`: 

```
Error: Failed to launch chrome!
/var/www/uiowa/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory
```

**Comment by richardbporter** [comment]
Sorry - you need to run `vagrant provision` to install Selenium. Added that to the testing steps.

**Comment by bspeare** [comment]
@richardbporter I've found the missing styles that are causing the jank.  What's the best way to add these in?

**Comment by richardbporter** [comment]
I thought thats what the `--css` option was for but I'm not entirely sure what the it does. The docs don't really specify. Adding another `--include` option with the selector might do it.

**Comment by bspeare** [comment]
It seems be ignoring some classes when I specify something.  Maybe it is struggling to grab the styles from the separate css components that aren't cached?  Here are the styles needed to make this work on top of the ones already generated:

```
@media (min-width: 84.375em) {
  .layout-container,
  .page__container,
  .page__container--mixed {
    max-width: 81.875em;
    margin: 0 auto;
  }
}
@media (min-width: 84.375em) {
  .header--primary .search-wrapper {
    -webkit-box-align: unset;
    -ms-flex-align: unset;
    align-items: unset;
  }
}

.header--primary .search-wrapper {
  -webkit-box-align: end;
  -ms-flex-align: end;
  align-items: flex-end;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -ms-flex-direction: column;
  flex-direction: column;
}
@media (min-width: 84.375em) {
  .search-wrapper {
    margin-right: calc(50% - 50vw);
  }
}
@media (min-width: 855px) {
  .search-wrapper {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;
  }
}

.search-wrapper {
  position: relative;
}
@media (min-width: 84.375em) {
  .search-button {
    right: 167px;
  }
}
@media (min-width: 84.375em) {
  .logo-icon--tab {
    margin-left: -16px;
    width: 180px;
    height: auto;
    padding: 5px 15px 25px 20px;
  }
}
@media (min-width: 84.375em) {
  .header--primary .logo-icon--secondary .logo-icon,
  .header--secondary .logo-icon--secondary .logo-icon {
    margin-top: 13px;
  }
}
@media (min-width: 84.375em) {
  .uiowa-bar .page__container {
    -webkit-box-pack: unset;
    -ms-flex-pack: unset;
    justify-content: unset;
  }
}
@media (min-width: 84.375em) {
  .o-canvas__group {
    position: absolute;
    top: 0;
    right: 0;
  }
}
```

**Comment by richardbporter** [comment]
What CSS files are those in?

**Comment by bspeare** [comment]
```
@media (min-width: 84.375em) {
  .uiowa-bar .page__container {
    -webkit-box-pack: unset;
    -ms-flex-pack: unset;
    justify-content: unset;
  }
}
```

In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/header/header.css which is in https://uiowa.stage.drupal.uiowa.edu/sites/uiowa.edu/files/css/css_dKyUEvcGJVUJVfrbx5LmECIeDTqAYAWCMNOEbPOrbUw.css



```
@media (min-width: 84.375em) {
  .o-canvas__group {
    position: absolute;
    top: 0;
    right: 0;
  }
}

```

In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/menus/off-canvas/off-canvas.css

```
@media (min-width: 84.375em) {
  .header--primary .search-wrapper {
    -webkit-box-align: unset;
    -ms-flex-align: unset;
    align-items: unset;
  }
}

.header--primary .search-wrapper {
  -webkit-box-align: end;
  -ms-flex-align: end;
  align-items: flex-end;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -ms-flex-direction: column;
  flex-direction: column;
}
@media (min-width: 84.375em) {
  .search-wrapper {
    margin-right: calc(50% - 50vw);
  }
}
@media (min-width: 855px) {
  .search-wrapper {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-flex: 1;
    -ms-flex: 1;
    flex: 1;
    -webkit-box-pack: justify;
    -ms-flex-pack: justify;
    justify-content: space-between;
  }
}

.search-wrapper {
  position: relative;
}
@media (min-width: 84.375em) {
  .search-button {
    right: 167px;
  }
}
```

In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/search-toggle/search-toggle.css



```
@media (min-width: 84.375em) {
  .logo-icon--tab {
    margin-left: -16px;
    width: 180px;
    height: auto;
    padding: 5px 15px 25px 20px;
  }
}
@media (min-width: 84.375em) {
  .header--primary .logo-icon--secondary .logo-icon,
  .header--secondary .logo-icon--secondary .logo-icon {
    margin-top: 13px;
  }
}
```
In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/logo/logo.css


```
@media (min-width: 84.375em) {
  .layout-container,
  .page__container,
  .page__container--mixed {
    max-width: 81.875em;
    margin: 0 auto;
  }
}
```

In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/templates/page-layouts/page-layouts.css which is in
https://uiowa.stage.drupal.uiowa.edu/sites/uiowa.edu/files/css/css_dKyUEvcGJVUJVfrbx5LmECIeDTqAYAWCMNOEbPOrbUw.css

**Comment by richardbporter** [comment]
Yea, its a bit of mystery how the library is generating the styles. Kind-of a rabbit hole. Maybe I can try the other library mentioned in the module docs: https://github.com/filamentgroup/criticalCSS

**Comment by bspeare** [comment]
Yeah, we could also just manually create the file.   There might be some style overrides necessary to reduce the jank and we might be able to manually reduce/remove some of the selectors that it is grabbing.  I'm open to trying the other library too.

**Comment by richardbporter** [comment]
No luck getting the other library to even run. 

As a quick test, I combined the styles you posted with what critical was giving us. It definitely solves the bar jank. It seems like it might be easier to manually maintain this or import the required styles into the critical partial (header, bar, etc.)

**Comment by bspeare** [comment]
I think the manual setup will work better especially if we want this to work on all sites and header variations.   Maybe we can also exclude those libraries from being loaded by the theme so we aren't loading duplicate files.

**Comment by bspeare** [comment]
I can try to make a list of the css partial files that we would need to include.

**Comment by bspeare** [comment]
This is probably a good starter list that would be huge:

- https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/global.css
- https://uiowa.local.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/menus/superfish/superfish.css
-  https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/header/header.css 
- https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/menus/off-canvas/off-canvas.css
- https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/search-toggle/search-toggle.css
- In https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/global/logo/logo.css
-  https://uiowa.stage.drupal.uiowa.edu/themes/custom/uids_base/assets/css/components/templates/page-layouts/page-layouts.css 

To reduce the size, it might be worth just working with a custom file that we manually curate.

**Comment by richardbporter** [comment]
I have to switch gears for a bit if you want to take a shot at that. I think just editing the scss/critical/default-critical.scss file would work, right?

**Comment by bspeare** [comment]
I think so.   I'll add the local css that I had working previously.

**Comment by bspeare** [comment]
After working on this some more it seems like there are more issues.   Try going to https://uiowa.dev.drupal.uiowa.edu/ and clicking on one of the news stories on the home page and then navigate back to the home page using the back button.  There is major FOUC happening which makes me wonder if this is worth it.

**Comment by richardbporter** [comment]
Yea I noticed that when you are scrolled down a page and the browser keeps you there, the FOUC is pretty bad. We'd have to increase the viewport height to include more styles or almost inline everything.

I'm fine with closing this if we think that its not worth it. After all, the issue was titled "Investigate". :)

**Comment by bspeare** [comment]
Let's bring it up in Parking Lot on Monday.   I added a card there so we don't forget.

**Comment by richardbporter** [comment]
We determined that this probably a better fit for SPA's that aren't doing full page loads on navigation. If we have any future sites like that, they can implement this themselves.

**Pull request closed without merging**
