### PR TITLE
P2LB protected node revision updates

### LINKED ISSUE #6859: Revisit p2lb protected node revision to ensure proper cleanup
# Problem

With the current protected revision, there is a potential for v2 draft revisions to exist that are "newer" (high id increment). We are currently targeting the protected node revision id and anything _less than_ which leaves these newer revisions around and prevents complete clean up of v2 content.

>Do we want to delete all revisions except for the "current" one? I've run into an issue on brand where things get messy and there are v2 revisions newer than the protected revision. This results in the orphan purger not cleaning things up because the current code only deletes the protected revision and anything that is "less than"

Screenshot 2023-09-06 at 2 46 11 PM

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/6830#issuecomment-1708993147_

# Proposed Solution
- [ ] Look for a ways to make sure the protected revision is the newest revision before conversion or change our criteria for cleaning up v2 content after conversion is complete.

# Workaround
- Manually delete those leftover revisions and trigger the `delete orphans` entity_reference_revisions functionality an additional three times to handle paragraph nesting.

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves #6859 

# How to test

```
ddev blt sync --site hawkeyemarchingband.uiowa.edu && ddev drush @hawkeyemarchingband.local uli admin/content?type=page
```
- Create a draft version of one or two pages without publishing so that the draft is the newest version of the page. It is easier to test this if your draft includes an edit that makes it immediately visually clear so you can see the change when you visit the converted page.
- Activate the split
```
ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y 
```
- Visit https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter
- Convert the pages which you modified.
- Confirm that the converted pages have the changes you made to the drafts.
- View the revisions and confirm that the draft(s) exist still.

## Cleanup

- Visit https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter again.
- Convert the remaining pages in bulk.
- Visit https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter/converted?moderation_state=editorial-draft.
- Bulk publish all pages.
```
ddev drush @hawkeyemarchingband.local sitenow_p2lb:cleanup
```
- Ensure the process completes.

# Bonus
- Test the whole process on Brand!
```
ddev blt sync --site brand.uiowa.edu && ddev drush @brand.local config-split:activate p2lb -y && ddev drush @brand.local uli admin/content/sitenow-converter
```
- https://brand.uiowa.ddev.site/admin/content/sitenow-converter/converted?moderation_state=editorial-draft
```
ddev drush @brand.local sitenow_p2lb:cleanup
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Does my [highly-scientific calculation of running it three times](https://github.com/uiowa/uiowa/pull/6830#issuecomment-1707262909) (section > component > item) still stand with this patch in play? https://github.com/uiowa/uiowa/pull/7025/commits/52a94da68641b52ff219b1d56b16285a50938374

**Comment by pyrello** [comment]
> Does my [highly-scientific calculation of running it three times](https://github.com/uiowa/uiowa/pull/6830#issuecomment-1707262909) (section > component > item) still stand with this patch in play? [52a94da](https://github.com/uiowa/uiowa/commit/52a94da68641b52ff219b1d56b16285a50938374)

It seems to.

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
tested on HMB, brand, gis.sites. seems to work as designed. so that would close that other issue https://github.com/uiowa/uiowa/issues/6861 

hope that patch gets some more traction though.

**Comment by pyrello** [comment]
> hope that patch gets some more traction though.

Since the patch only affects a drush command, it seems relatively safe to adopt it since it is not committing us to schema or object structures that might change in a future iteration.

**Pull request merged**
