### PR TITLE
i3247 - lb styles

### LINKED ISSUE #3247: As an Admissions site owner, I can see a styled version of the "find your major" section on the admissions site
# Story

As an Admissions site owner, I can see a styled version of the "find your major" section on the admissions site.

# Proposed solution

- [x] Add new layout builder style Icon pattern background with class `bg--white--pattern--community`.
- [ ] Adjust styles for `block-uiowa-area-of-study-search` to remove background color, border, padding to match screenshot below. 
- [x] Add placeholder text for area of study search form and visually hide form label. 

Screen Shot 2021-03-15 at 10 55 24 AM

## Blocked until 
- [x] Create new background in UIDS: https://github.com/uiowa/uids/issues/492.

### PR DESCRIPTION
**Pull request by dnkemper**
# How to test

Closes #3247 

**Update UIDS**
- `blt frontend` 
or:
- `rm -rf ./node_modules`
- `yarn cache clean`
- `yarn install`
- `yarn workspace uids_base gulp --development`

**Test Admissions home page:**
- `blt ds --site=admissions.uiowa.edu`
- `yarn workspace admissions_core build`
- `drush @admissions.local cr`
- Go to http://admissions.local.drupal.uiowa.edu/ and edit the "Find your Major" section and add a new background pattern for "White - Community pattern".

**Test Sandbox**
- `blt ds --site=sandbox.uiowa.edu`
- `drush @sandbox.local cr`
-  Add and run through new section background options listed below on http://sandbox.local.drupal.uiowa.edu/kitchen-sink and verify that color contrast on the elements there looks correct. 

```
Black – Brain pattern
Black – Community pattern
Black – Particle pattern
Black
Gold – Brain pattern
Gold – Community pattern
Gold – Particle pattern
Gold
Gray – Brain pattern
Gray – Community pattern
Gray – Particle pattern
Gray
White
White – Brain pattern
White – Community pattern
White – Particle pattern
```

Still todo:
- Attach new UIDS release (blocked until brand team approves new backgrounds).

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Taking a look

**Comment by joewhitsitt** [comment]
I like these backgrounds! Really adds versatility and the names make more sense. A few contrast issues I spotted.
 
Screen Shot 2021-03-23 at 11 20 28 AM
Screen Shot 2021-03-23 at 11 20 48 AM
Screen Shot 2021-03-23 at 11 21 17 AM
Screen Shot 2021-03-23 at 11 21 30 AM
Screen Shot 2021-03-23 at 11 22 46 AM
Screen Shot 2021-03-23 at 11 25 48 AM

**Comment by bspeare** [comment]
> I like these backgrounds! Really adds versatility and the names make more sense. A few contrast issues I spotted.
> 
> Screen Shot 2021-03-23 at 11 20 28 AM
> 
> Screen Shot 2021-03-23 at 11 20 48 AM
> 
> Screen Shot 2021-03-23 at 11 21 17 AM
> 
> Screen Shot 2021-03-23 at 11 21 30 AM
> 
> Screen Shot 2021-03-23 at 11 22 46 AM
> 
> Screen Shot 2021-03-23 at 11 25 48 AM

@joewhitsitt Are those on the published kitchen sink page or the lb editor preview?

**Comment by joewhitsitt** [comment]
layout builder preview for sure. i will quickly go back through those and check.

**Comment by bspeare** [comment]
@joewhitsitt I think it is just the preview.  I will fix.

**Comment by bspeare** [comment]
@joewhitsitt Those editor styles should be fixed now if you could review it again.

**Comment by joewhitsitt** [comment]
sorry, gotta hold on this until https://status.acquia.com/ clears up. i don't have a sandbox site to test against.

**Comment by joewhitsitt** [comment]
Checked this morning. Looks good. Is there are reason this is still in draft and blocked?

**Comment by bspeare** [comment]
@joewhitsitt Thanks! I'm going to create a UIDS release now.  I didn't want this to be merged in without it if you want to approve.

**Review by joewhitsitt — APPROVED** [review]
Tested everything but the route check. Reviewed that. Looks correct.

**Pull request merged**
