### PR TITLE
Feature: page title template refactor

### LINKED ISSUE #2674: As a developer, I can create a new content type without having to add a field template file for the page title
# Story

As a developer, I can create a new content type without having to add a field template file for the page title.

# Proposed solution

- Create one page title template: `docroot/themes/custom/uids_base/templates/field/field--node--title.html.twig`

- Remove these templates:
```
docroot/themes/custom/uids_base/templates/field/field--node--title--area-of-study--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--page--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--person--default.html.twig
docroot/themes/custom/uids_base/templates/field/field--node--title--student-profile--default.html.twig
docroot/themes/custom/uids_base/templates/field/paragraphs/field--node--title--article--default.html.twig
```
- Remove `<h1>` from https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/content/page-title.html.twig#L17
- Run a search for other templates used outside of `uids_base`

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/2674. 

This pr removes all the duplicate page title templates that I could find and sets a page_title_alter function to set a custom page template for node titles.   

# How to test

`blt ds --site=sandbox.uiowa.edu (enable topic_collection, enable event split, enable areas of study split)`

Run `drush @sandbox.local cim` and test the article, page, topic collection, event, and areas of study content types.  Verify that the page title for each is using `field--node--title.html.twig` and that there are not empty/duplicate `<h1>` tags. 

`blt ds --site=grad.uiowa.edu`
- Test on custom grad content types mentor, thesis defense, scholar and verify that there are not empty/duplicate `<h1>` tags. 

`blt ds --site=admissions.uiowa.edu`
- Test on custom taxonomy pages and view pages like https://admissions.local.drupal.uiowa.edu/colleges/college-dentistry and https://admissions.local.drupal.uiowa.edu/areas-of-study and verify that the page title is using the `page-title.html.twig` template.   

`blt ds --site=hawkeyemarchingband.uiowa.edu`
- Test on v2 pages and verify that there are no issue with page titles. 

## User story

As a developer, I can create a new content type without having to add a field template file for the page title

### CODE REVIEW

**Comment by richardbporter** [comment]
Mostly for my own understanding:

Fellowships (scholarships) on grad.uiowa.edu is using uids_base/templates/field/field--node--title.html.twig.

image

What is the difference between that and uids_base/templates/content/page-title--node.html.twig?

**Comment by richardbporter** [comment]
Does site name count as a duplicate h1?

**Comment by bspeare** [comment]
`uids_base/templates/field/field--node--title.html.twig` - is mostly used by layout builder pages
`uids_base/templates/content/page-title.html.twig` - is used by taxonomy term pages and views for page titles
`uids_base/templates/content/page-title--node.html.twig` - is used by nodes not using layout builder for page titles so we can include `field--node--title.html.twig` in that template and utilize the markup in that field template.

**Comment by bspeare** [comment]
@richardbporter no, I was seeing some empty `<h1>` around the page title markup during the refactoring and I just wanted to make sure you didn't notice that happening.   The site name is a completely different issue we might want to address in the future.

**Comment by richardbporter** [comment]
Thanks!

Event seems to be using field--node--title--event--default:
image

**Comment by richardbporter** [comment]
OIC https://github.com/uiowa/uiowa/pull/4110/files#diff-75ae3c0da087cf86fa5c0e17c64b7e2edbdc834b177c463bd5fbae165adae918

**Review by richardbporter — APPROVED** [review]
Looks good to me. 👍🏻

**Comment by bspeare** [comment]
@richardbporter thanks!

**Pull request merged**
