### PR TITLE
[Bug] People list block website field

### LINKED ISSUE #5905: As a SiteNow editor, I can display the website field in my people list block
# Story

As a SiteNow editor, I can display the website field in my people list block so that I can display custom links related to the user profile. 

As a part of the content review for https://uc.prod.drupal.uiowa.edu/our-organization we found that they created their own custom profile teaser displays within a text area because they wanted to display the websites of each profile.   If there were an option to display the "Website" field within the list block they might have been able to accomplish a similar layout. 

Screen Shot 2022-11-01 at 2 46 25 PM

# Proposed solution
- Add website field as an option for the people list block?

Possibly related https://github.com/uiowa/uiowa/issues/5722.

### LINKED ISSUE #7203: [Bug] People list block hidden fields regression
# Problem
`Content: website` and `Content: Link directly to website` are now options in the People list block. 
Screenshot 2023-12-12 at 11 28 53 AM

# Steps to reproduce
Configure a people list block on https://sandbox.prod.drupal.uiowa.edu/node/51/layout. 

# Proposed solution
- Add the website as an option to the teaser and set an update hook to keep it hidden.  

## Considerations
- Doing this will make the website field appear on /people but it seems like we need to make the People view configurable: https://github.com/uiowa/uiowa/issues/7101
- The featured content card will also display the website field without an ability to hide (you can't hide the email or the phone number fields either).

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7203
Resolves https://github.com/uiowa/uiowa/issues/5905

# How to test
```
ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /debug-one-people-list-block
```
- Code review
- Test https://github.com/uiowa/uiowa/issues/7203#issuecomment-1852702948 and confirm that no update hook is needed
- Do we need to do anything about https://github.com/uiowa/uiowa/issues/7203#issuecomment-1852721124?
- Edit the block and uncheck the website field and confirm that the website field is visible on save. 
- Confirm website is showing on https://sandbox.prod.drupal.uiowa.edu/leadership-team and https://sandbox.prod.drupal.uiowa.edu/featured-content-0

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>Do we need to do anything about https://github.com/uiowa/uiowa/issues/7203#issuecomment-1852721124?

Short of reversing the logic, I think we just need to be mindful going forward. "New field on an existing content type that has a listblock..."

**Comment by joewhitsitt** [comment]
Pulling to test

**Review by joewhitsitt — APPROVED** [review]
These changes look good. Curious if we want to limit the teaser to display only one website?

Screenshot 2023-12-22 at 4 00 45 PM

**Comment by joewhitsitt** [comment]
Also glanced to see if anyone was completely splitting on teaser but I think it is all partial which should accept this change. Tested immuno.grad

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I'm fine with multiple as it could help out scenarios like the screenshot on https://github.com/uiowa/uiowa/issues/5905.

**Comment by joewhitsitt** [comment]
Haha, got you on record. We will revisit when someone goes wild with like 10+ website links and thinks it is okay.

**Pull request merged**
