### PR TITLE
Add right margin to card list media.

### LINKED ISSUE #2227: Fix padding around images for card lists in uids_base
# Problem 

#2076 may have created some padding regressions with card lists where media images are right up against the border on v3. 

94057836-cbde5c00-fda5-11ea-8c5b-2a30053bb228

# Proposed Solution

Adjust card list padding to create space for media images.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2227 

### Testing
- On a v3 site, create a page with events, people and article lists. 
- See that card--list media does not edge up against the right side of the container.
- Shrink viewport to small breakpoint to see media has no margin.

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling this down to test.

**Comment by bspeare** [comment]
I added a rule to only add the margin if a background class is applied.  I tested this locally and it works on all list displays mentioned.

**Review by bspeare — APPROVED** [review]
I tested this locally and it works on all list displays mentioned.

**Comment by richardbporter** [comment]
Thanks

**Pull request merged**
