### PR TITLE
ListBlock Updates

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/4158

Created draft PR from Makur's branch

## To Test

- Interact with existing views blocks. Check for visual regressions from that of PROD (e.g. filters being revealed that weren't previously revealed).
- Create new people list blocks in v3 and make sure the settings provided are what are rendered.

### CODE REVIEW

**Comment by pyrello** [comment]
Taking a look.

**Comment by pyrello** [comment]
I did some refactoring with an eye towards making it easier to compare the `ListBlock` class and its new parent. Also made some changes to align with expected changes when we adopt a patch to allow exposing filters.

Also ended up creating a helper function for running update hooks to update a batch of blocks of a certain plugin id, but didn't end up needing it yet. I left it in because I think it will be helpful in the future.

@joewhitsitt Might be good for you to re-check this to make sure I didn't break anything. Everything looked good to me when I tested your code.

**Comment by pyrello** [comment]
I'm giving preliminary approval of this based on the checking I did. Once @joewhitsitt has satisfied himself about how it works, then I'll give actual approval.

**Comment by joewhitsitt** [comment]
So, it seems that https://github.com/uiowa/uiowa/pull/4198/files#diff-80bddf0efcb844ce671e57c638bfaa246f2fa0d0c37b1689cfcdc03657b3e565R975 will be a config update for all views blocks (article block, etc.), but one that doesn't need to happen before deployment? Is that correct @pyrello ?

**Comment by pyrello** [comment]
It seems like views don't update their config definition until they are re-saved. At least, after adding that option, none of the other views were updated. I think that not having that item in there will cause them to continue to function they way they currently do. If we wanted to be as thorough as possible though, we would re-save every block and then re-export. Or if it seemed like something that could be handled via file comparison and copy/paste that would probably do the trick as well.

**Comment by joewhitsitt** [comment]
from my tests, other view blocks were not affected beyond the new config but that the new config didn't prevent the new/existing blocks to work.

**Review by dnkemper — APPROVED** [review]
Nervous to approve this but tested it following the testing instructions and everything seems to work as expected

**Comment by joewhitsitt** [comment]
Based on:

>I'm giving preliminary approval of this based on the checking I did. Once @joewhitsitt has satisfied himself about how it works, then I'll give actual approval.

>Nervous to approve this but tested it following the testing instructions and everything seems to work as expected

and my own testing, I am going to merge this.

**Comment by pyrello** [comment]
Woo-hoo! Thanks for taking this on, @joewhitsitt. I think this work will make the future work in #3804 easier.

**Pull request merged**
