### PR TITLE
Clean up old media revisions

### LINKED ISSUE #4811: Clean up media revisions
Epic #4338 

# Story

When a media entity is deleted from the website, as a site editor I expect the underlying file to be removed from the server so it no longer shows up in search results.

# Proposed Solution

Update hook to remove non-current media revisions and set the related files' status to 0 so that garbage collection can remove them.

- [x] query the media table for all `mid/vid`. Then in media_revision get all `mid/vid` that don't intersect and safely delete using `\Drupal::service('entity_type.manager')->getStorage('media')->deleteRevision({vid});` OR look into comparing `changed` values to identify older candidates.
- [x] Test to see if file_usage table counts are updated with this alone, otherwise look into other ways to trigger an update without the usual add/edit/delete operations.
- [ ] Confirm that existing "latest" media is not wiped out and that cron doesn't remove them in subsequent runs.
- [ ] Run off-hours

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #4811 

Previous work in #4641 prevents new media revisions from being created when media entities are edited and saved, including when new files are attached. Media entities made prior to that PR's deployment may have multiple revisions, including revisions using different files as in the case of file overrides.

This PR cleans up any old revisions if they exist for all media entities. Part of this process should also mark any files which were previously only associated with old revisions as no longer in use (tracked in the `file_usage` table). These files should be marked status = 0 as part of this update, which would allow cron processes to clean them up at a later time as no longer used by the site.

# How to test

- Sync a site, check that the update hook runs without issue
- Check that the media entities count does not change (number of rows in the `media` table) following the update hook
- Check that the number of rows in the `media_revision` table equals the number of rows in the `media` table (it may have been larger prior to the update hook)
- Check if the number of rows in the `file_usage` table has changed
  - If it has changed, check that the difference is equal to the number of files in `file_managed` which have a status of '0'
  - Of the files in `file_managed` which have a status of 0, check that they are associated to media entities which have new files associated with their most current revisions

### CODE REVIEW

**Comment by cory-skeers** [comment]
Looking at the media and media_revision tables, update hook appears to be getting the job done. (Sandbox counts go from 132 to 121, which equals the media table counts).

Looking at the file_usage table, the counts change from 133 to 128 in the sandbox site, so something is being updated there. Need to look more into it yet to understand if enough is being updated, and where the count differences come from.

**Comment by cory-skeers** [comment]
> Looking at the file_usage table, the counts change from 133 to 128 in the sandbox site, so something is being updated there. Need to look more into it yet to understand if enough is being updated, and where the count differences come from.

File usage counts for some rows decreased, and some rows were dropped completely after the hook.

5 entities in the file_managed table went from a status of 1 to 0 from the hook on sandbox, which would match the 5 dropped rows from the file_usage table. This seems to make sense if these files were replaced and only appeared in revisions. The other 5 revisions dropped should correspond, then, to instances where the same file is still used in the media, but for some other change in revision, and should see a corresponding change in file_usage count.

```
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+------------+----------+--------+------------+------------+
| fid | uuid                                 | langcode | uid  | filename                    | uri                                          | filemime   | filesize | status | created    | changed    |
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+------------+----------+--------+------------+------------+
| 411 | 6ab44959-c121-45f3-91c7-c76be3ba262f | en       |   71 | carl-spackler-square.jpeg   | public://2021-09/carl-spackler-square.jpeg   | image/jpeg |   174923 |      0 | 1631800786 | 1646669339 |
| 566 | 8522ffd4-25d8-4126-884b-69c36759eaf8 | en       |   71 | instagram-square-brands.png | public://2021-12/instagram-square-brands.png | image/png  |     3740 |      0 | 1639496997 | 1646669339 |
| 576 | 805de74d-3b86-4a8a-95db-e3fb21d81f49 | en       |   71 | pinterest-square-brands.png | public://2021-12/pinterest-square-brands.png | image/png  |     3665 |      0 | 1639497043 | 1646669339 |
| 581 | b260332b-742e-4d2b-b537-a857960a9938 | en       |   71 | snapchat-square-brands.png  | public://2021-12/snapchat-square-brands.png  | image/png  |     2951 |      0 | 1639497070 | 1646669339 |
| 586 | 7e0adb07-c07d-4b3e-a91a-46f67575a15f | en       |   71 | youtube-square-brands.png   | public://2021-12/youtube-square-brands.png   | image/png  |     2743 |      0 | 1639497093 | 1646669339 |
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+------------+----------+--------+------------+------------+
```

**Comment by joewhitsitt** [comment]
Hmm. Those icons shouldn't be marked as status 0 because there should still be a media entity that "counts." Those are being used in Concept3D's footer.

**Comment by cory-skeers** [comment]
> Hmm. Those icons shouldn't be marked as status 0 because there should still be a media entity that "counts." Those are being used in Concept3D's footer.

It looks like there are non-square versions of the files that still have a status 1 (eg "instagram-brands.png" along with "instagram-square-brands.png"). As far as I can tell, it looks like the "square" version was originally used in the media entity, but was replaced by the non-square, and so the "square" only exists as being used in media revisions.

If that's the case, then this should be working as expected, and it should be part of the expected file cleanup. If not, there's something not good going on...

```
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+-----------+----------+--------+------------+------------+
| fid | uuid                                 | langcode | uid  | filename                    | uri                                          | filemime  | filesize | status | created    | changed    |
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+-----------+----------+--------+------------+------------+
| 556 | 624215d4-1b71-496b-8399-8d20076bd09d | en       |   71 | facebook-square-brands.png  | public://2021-12/facebook-square-brands.png  | image/png |     2341 |      1 | 1639496939 | 1639496960 |
| 661 | d93586b3-7eca-4069-b80c-0b0366ceb863 | en       |   71 | instagram-brands.png        | public://2022-01/instagram-brands.png        | image/png |     3874 |      1 | 1642717577 | 1642717577 |
| 566 | 8522ffd4-25d8-4126-884b-69c36759eaf8 | en       |   71 | instagram-square-brands.png | public://2021-12/instagram-square-brands.png | image/png |     3740 |      0 | 1639496997 | 1646669339 |
| 571 | d65ca7fd-98ff-4dfd-a20d-44a36a334b83 | en       |   71 | linkedin-brands.png         | public://2021-12/linkedin-brands.png         | image/png |     2534 |      1 | 1639497020 | 1639497028 |
| 676 | b55702b2-5ab1-48c9-8b51-c158e291051a | en       |   71 | pinterest-brands.png        | public://2022-01/pinterest-brands.png        | image/png |     4505 |      1 | 1642717658 | 1642717658 |
| 576 | 805de74d-3b86-4a8a-95db-e3fb21d81f49 | en       |   71 | pinterest-square-brands.png | public://2021-12/pinterest-square-brands.png | image/png |     3665 |      0 | 1639497043 | 1646669339 |
| 671 | 98e68af8-ad88-46f0-b34b-35ee1420bce7 | en       |   71 | snapchat-brands.png         | public://2022-01/snapchat-brands.png         | image/png |     3641 |      1 | 1642717634 | 1642717634 |
| 581 | b260332b-742e-4d2b-b537-a857960a9938 | en       |   71 | snapchat-square-brands.png  | public://2021-12/snapchat-square-brands.png  | image/png |     2951 |      0 | 1639497070 | 1646669339 |
| 681 | 00401c36-c4e2-429e-ab48-3e05607c9815 | en       |   71 | tiktok-brands.png           | public://2022-01/tiktok-brands.png           | image/png |     3402 |      1 | 1642718489 | 1642718504 |
| 561 | 2b0b24f2-e158-4bc3-8465-5b4076100ec4 | en       |   71 | twitter-square-brands.png   | public://2021-12/twitter-square-brands.png   | image/png |     2974 |      1 | 1639496975 | 1639496983 |
| 666 | fb2718d0-4a61-4ebe-a4c7-679dd68e37bf | en       |   71 | youtube-brands.png          | public://2022-01/youtube-brands.png          | image/png |     2515 |      1 | 1642717600 | 1642717600 |
| 586 | 7e0adb07-c07d-4b3e-a91a-46f67575a15f | en       |   71 | youtube-square-brands.png   | public://2021-12/youtube-square-brands.png   | image/png |     2743 |      0 | 1639497093 | 1646669339 |
+-----+--------------------------------------+----------+------+-----------------------------+----------------------------------------------+-----------+----------+--------+------------+------------+
```

**Comment by joewhitsitt** [comment]
Ah yes! Nice catch. Brand team noticed I didn't mimic the homepage and had me change them using the replace functionality

**Comment by cory-skeers** [comment]
Testing the update hook on brand.uiowa.edu sync:
media counts stay constant at 677
media_revision counts go from 1366 to 677
file_usage counts go from 1352 to 822
file_managed table goes from 0 files with status 0 to 530 files with status of 0.

From looking at the numbers alone, this appears to be working as expected and include the desired updates to the file usage, where the drop in file_usage matches the number of files switched to status 0, and there is an equal or larger drop in media_revision counts than file_usage (as each additional media revision of the current may involve an additional file upload/usage or not).

Edit:
Spot checking files that were updated to status=0 in file_managed, every instance checked could be matched to a media entity which has had its associated file replaced (ie the file is used only in old media revisions, and not current). Was far from extensive to the full 530 files marked as status=0, but roughly 20-30 files checked.

**Comment by cory-skeers** [comment]
> Ah yes! Nice catch. Brand team noticed I didn't mimic the homepage and had me change them using the replace functionality

Awesome. Thanks for the added clarity there!

**Comment by cory-skeers** [comment]
Tested the update hook for admissions.uiowa.edu.
media counts stay constant at 714.
media revision counts go from 812 to 714.
file usage counts go from 728 to 727.

One record in file_managed after running where status=0.
```
+-----+--------------------------------------+----------+------+---------------------------------------------------------+--------------------------------------------------------------------------+------------+----------+--------+------------+------------+
| fid | uuid                                 | langcode | uid  | filename                                                | uri                                                                      | filemime   | filesize | status | created    | changed    |
+-----+--------------------------------------+----------+------+---------------------------------------------------------+--------------------------------------------------------------------------+------------+----------+--------+------------+------------+
| 971 | 9be970ca-47ab-4558-8ced-562ae7af0973 | en       |   21 | 2019_10_08-Iowa River Drone Shoot II jatorner -0009.jpg | public://2021-02/2019_10_08-Iowa River Drone Shoot II jatorner -0009.jpg | image/jpeg |  3670875 |      0 | 1613160405 | 1646688106 |
+-----+--------------------------------------+----------+------+---------------------------------------------------------+--------------------------------------------------------------------------+------------+----------+--------+------------+------------+
```
Checking in media, the media entity this file previously was associated with is now using the file "2021_02_05-Hancher - National Wear Red Day 2021 jatorner -0014.jpg," so it fits that this is now listed as status=0.

Spot checking other media entities that had revisions removed, didn't find any others that changed which file was associated, so the only one change makes sense.

**Comment by cory-skeers** [comment]
Leaving this in draft so it doesn't get merged in yet, but I think this could use some other eyes/testing.

**Comment by joewhitsitt** [comment]
pulling to test on a couple sites

**Comment by joewhitsitt** [comment]
So far it is looking promising but I want to do more testing. Tried it on Brand after syncing files locally. In batches of 100 after I adjusted the changed timestamp to speed up the six hour hold in place, cron cleared up over 1.25 GB (530 files). Spot checking the site, I am not noticing broken images or missing file downloads. Knowing that cron doesn't try to do this all at once makes me feel better.

HR - 197 files marked as 0. A lot of them are the icons they switched out for images when they adopted uids_base.

Transportation - 26 files marked as 0. Looks like parking lot maps were updated.

I ran a big DSA on some custom and standard sites (my multisites list) and I am not noticing big counts besides brand/hr. The ones I am seeing are a lot of 2020 versions or ...report_v1_5.pdf types of content which will still be beneficial as it relates to our common support issue.

**Comment by joewhitsitt** [comment]
This has my 👍. Since the update hook doesn't cause any immediate operations, maybe this can just go out normally but alone with no other update hooks

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
