### PR TITLE
People list block link fix

### LINKED ISSUE #5666: Clickable people profile images
# Story
As a user, I would like to be able to click the profile image on a people listing to view their profile.

- Making the People images not clickable breaks with breaks with how the cards, events, and articles are used.
- The default people directory listing has the images clickable.

examples:
https://sandbox.prod.drupal.uiowa.edu/sandbox-people
https://sandbox.prod.drupal.uiowa.edu/people-examples

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5666. 

# How to test

- `ddev blt ds --site=sandbox.uiowa.edu`
- Go to https://sandbox.prod.drupal.uiowa.edu/people-examples and verify that images are clickable. 
- Edit the list block and make sure that the "Hide fields" option does not contain a "Content: link to content" option. 
- Verify that is OK to remove https://github.com/uiowa/uiowa/pull/5710/commits/5d0de989c4f1c47b4eee7526df4f54e613c0d3c3.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>Verify that is OK to remove https://github.com/uiowa/uiowa/commit/5d0de989c4f1c47b4eee7526df4f54e613c0d3c3.

It is being used to construct the title/credential [link](https://github.com/uiowa/uiowa/blob/5d0de989c4f1c47b4eee7526df4f54e613c0d3c3/config/default/views.view.people_list_block.yml#L117). I believe it is [restricted for users to toggle](https://github.com/uiowa/uiowa/blob/5d0de989c4f1c47b4eee7526df4f54e613c0d3c3/config/default/views.view.people_list_block.yml#L983)

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I'll remove that `{{ node/{{ nid }}` if we are comfortable with moving forward with this bug fix that uses a `view_node` field instead.

**Comment by joewhitsitt** [comment]
Okay. I wasn't sure what the overall solution would be. `nid` from restricted fields would be removed too.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and works great!

Also with the way this is linked, I think we are good to remove the `nid` from the view. 👍

**Comment by bspeare** [comment]
Thanks @cory-skeers!

**Pull request merged**
