### PR TITLE
Adopt DrupalVM.

### LINKED ISSUE #919: Install NVM when vagrant provision runs
Just like yarn: https://github.com/uiowa/uiowa01/blob/master/box/config.yml#L137

### LINKED ISSUE #933: Move sitenow demo site out of default directory
I'm not sure if the default site should be a sitenow site. With multiple profiles now supported, it might make more sense to just run a standard Drupal install that isn't really used. 

We do need a site there to bootstrap for Cloud Hooks to work properly.

### LINKED ISSUE #942: Sitenow provision/deprovision commits failing.
Its a bit excessive and makes history hard to read. We typically don't need to revert individual files from a prov/deprov operation.

### LINKED ISSUE #976: Use DrupalVM for all local development
I started this on https://github.com/uiowa/uiowa/compare/master...vm but we have new sites that need the updates run against them.

### PR DESCRIPTION
**Pull request by richardbporter**
# Description
Resolves #976  
Resolves #942 
Resolves #933 
Resolves #919 

# Testing
1. Install VirtualBox 6.0.16
  - https://www.virtualbox.org/wiki/Download_Old_Builds_6_0
2. Install Vagrant 2.2.6
  - https://www.vagrantup.com/downloads.html
3. Comment out any `multisites` local overrides in `blt/local.blt.yml` file.
4. Remove all local setting files with `rm -f docroot/sites/*/settings/local.settings.php docroot/sites/*/local.drush.yml`.
5. Regenerate local settings with `blt blt:init:settings` or `blt bis` or short.
6. Initialize the VM with `blt vm`. Follow any on-screen instructions. There may be warnings/errors but you should get a green message at the end mentioning the dashboard: http://dashboard.local.drupal.uiowa.edu. Visit that URL.
7. Uncomment any `multisites` overrides in `blt/local.blt.yml` file.
8. SSH into the VM with `vagrant ssh` on a new terminal tab.
9. Delete the node_modules directory in the application root.
10. Sync local sites with `blt drupal:sync:all-sites` or `blt dsa` for short. 

Creating a site will require running `vagrant provision` from the host, i.e. your machine. This will create a new VHOST for the domain and it will be listed in the dashboard.

Be sure to scrub any sensitive info, users, pws, server paths, etc. from comments posted here.

### CODE REVIEW

**Comment by richardbporter** [comment]
You can login to a local site using the new local alias from your host, e.g. `drush @mysite.local uli`. The site has to bootstrap obviously.

**Comment by pyrello** [comment]
When I run `drush @theming.local si collegiate`, I get the following error:

```
Warning: Identity file /home/vagrant/.vagrant.d/insecure_private_key not accessible: No such file or directory.
```

**Comment by pyrello** [comment]
I think that in the drush/sites/*.site.yml files, we are going to want the *.uri values to have "https://" at the beginning of them. Otherwise, all the URLs generated by `drush uli` will use http.

I'm writing an update for this.

**Comment by pyrello** [comment]
I run into the following error when I run `blt dsa`:

```
> source:build:frontend
> source:build:frontend-reqs
Executing frontend-reqs target hook...
[ExecStack] . $NVM_DIR/nvm.sh && nvm install && yarn install
[ExecStack] Running . $NVM_DIR/nvm.sh &&
 nvm install &&
 yarn install in /var/www/uiowa/docroot
sh: 1: .: Can't open /nvm.sh
[ExecStack]  Exit code 2  Time 0.004s
[error]  Executing target-hook frontend-reqs failed.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `source:build:frontend-reqs ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `source:build:frontend ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

**Comment by dnkemper** [comment]
1. Installed the vm - everything seems to be working correctly
2. blt dsa worked
3. Blt ds —site=* worked on the sites I tested
4. When I logged in, I got a https warning
Screen Shot 2020-01-27 at 9 18 19 AM

**Comment by richardbporter** [comment]
Thanks! The cert warning is expected since it is a self-signed cert for local development only. You can proceed to the site using the advanced button.

**Comment by joewhitsitt** [comment]
still testing, but just FYI, it seemed to overwrite my local.blt.yml file. which is fine, but i forgot which multisites i had (commented out)

**Comment by pyrello** [comment]
@joewhitsitt Do you know at what point your local.blt.yml was overwritten? I didn't experience that when testing.

**Comment by richardbporter** [comment]
I was able to run `drush @theming.local si collegiate` without error.

**Comment by pyrello** [comment]
@richardbporter I should have said warning, not error. It did not prevent the successful execution of the command and I don't think it was specifically related to the command.

**Comment by joewhitsitt** [comment]
Uh, it mentioned:
> ...uiowa/blt/local.blt.yml was modified.

Right before it said it configured for PHP 7.2

the contents were just:

```
vm:
  enable: true
```

Without reading each line of output, I don't know where it exactly might have happened.

**Comment by pyrello** [comment]
Okay. Got it. I didn't run the `blt vm` command, but it sounds like that is the step where it happens and that is what I meant by my question :)

**Comment by joewhitsitt** [comment]
i was able to perform all of the setup steps without breaking issues. logged into a site and setup stage_file_proxy, etc. slower than drush rs but not unusable like lando without the excludes.

ran `drush @theming.local si collegiate` went fine, but trying to `uli` i got:

```
Warning: Identity file /home/vagrant/.vagrant.d/insecure_private_key not accessible: No such file or directory.                                                        
                                                                                                                                                                         
  In FilesystemLoader.php line 106:                                                                                                                                      
                                                                                                                                                                         
    The "themes/custom/collegiate_theme/hds/components/03 - global/site-name" d                                                                                          
    irectory does not exist ("/var/www/uiowa/docroot/themes/custom/collegiate_t                                                                                          
    heme/hds/components/03 - global/site-name").
```

`blt frontend` did not run during `dsa` and when run manually I ran into the NVM error.

**Comment by pyrello** [comment]
@joewhitsitt Did you confirm that it overwrote your local.blt.yml file? It looks like it should just insert `vm.enable = true`.

**Comment by joewhitsitt** [comment]
Yeah, something definitely overwrote it. i had all the example commented out stuff as well as my multisites declarations commented out. when the vm was built and i was supposed to uncomment my multisites, all that was in the file was the vm enable true.

Again, not a big deal.

**Comment by richardbporter** [comment]
The quickest way to solve the NVM issue may be to abandon it and keep Pipelines + VM in sync manually. I added another step to the process: `9. Delete the node_modules directory in the application root.` Otherwise, `blt frontend` fails with a permissions issue. 

I think `blt dsa` should complete now.

**Comment by joewhitsitt** [comment]
Thanks. i was able to frontend and uli into collegiate theming

**Comment by joewhitsitt** [comment]
i was not able to get xdebug to trigger in phpstorm with the following: http://docs.drupalvm.com/en/latest/extras/xdebug/

In PHPStorm I registered the CLI interpreter using the vagrant option. Alot of this auto filled but debugger says not installed compared to my old php setup:

Screen Shot 2020-01-27 at 11 27 28 AM

**Comment by richardbporter** [comment]
When syncing the demo site, I noticed the sync commands were not correct. @pyrello Are you ok with setting the sync commands for every site in the top-level blt.yml file? This only affects `blt dsa` and `blt sync`.

**Comment by pyrello** [comment]
@richardbporter I'm not sure what the ramifications of this are - off the top of my head - in terms of how we work with our existing sites, but I think that should be okay

**Comment by richardbporter** [comment]
If you weren't running `dsa` or `sync` before, then it shouldn't change anything. If you start using that to quickly get local sites in the same state as prod, then its important to export any configuration locally beforehand. Otherwise, you risk losing configuration when `drupal:update` runs: it executes `drush updb` and `drush config:import`.

**Comment by richardbporter** [comment]
Regarding the alias warning, the local aliases are configured to run from your host, not on the Vagrant box. That is what BLT ships with by default so I set it up that way. They still work on the VM but you'll see that warning because the key does exist there.

So on your machine, you can run `drush @hr.local uli` and it will open your browser for you. On the VM, it will print that warning but still work only without the browser opening automatically.

**Review by pyrello — APPROVED** [review]

**Comment by richardbporter** [comment]
I've got xDebug working with VSCode and PHPStorm with the latest config change. It does not require a cookie be set via command line or browser extension. It does require path mappings bet set up.

**Comment by pyrello** [comment]
For those who are new to Drupal VM, anytime there is a change to the box/config.yml file, it is necessary to exit the VM and run `vagrant provision` from the root of the project. This will ensure that any changes get incorporated.

**Review by joewhitsitt — APPROVED** [review]
xdebug working in PHPStorm. I don't have the path mappings setup correctly in VSCode, but that is my fault.

Everything else seems to be working alright

**Pull request merged**
