### PR TITLE
Admissions kiosk work

### LINKED ISSUE #3841: Admissions print kiosk
Admissions would like a print kiosk so people who come in can choose to print the pdf's for whatever Areas of Study they are interested in rather than Admissions pre-printing lots of these.

# Additional Info
Some Intro text
List of Areas of Study with checkboxes to select one or more
Big print button
when click print, it just prints - no additional dialogues, can print multiple at once
not indexed
~possibly authenticate & go directly to page to select what to print~
Scott shared https://printjs.crabbly.com/ as a possibility to look at.

Hardware - will use CLAS kiosks - Microsoft Surface
Printer hardwired

Isaac P in ClAS is contact related to hardware

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3841 

# How to test

- `composer install`
- `blt ds --site=admissions.uiowa.edu`
- `drush @admissions.local cim`
- `yarn workspace admissions_core build`
- `drush @admissions.local cr`
- Go to https://admissions.local.drupal.uiowa.edu/kiosk as anonymous user in Chrome and verify that you can print multiple PDFs
- Verify that page refreshes and resets checkboxes after closing print dialog
- Verify that print button only appears if aos checkboxes are checked
- Verify reset button appears when applying a filter (switch on academic interest)
- Verify that multiple page pdfs are clearly separated on separate pages
- Verify page is set to noindex in metatag settings

### CODE REVIEW

**Comment by bspeare** [comment]
I think I got the page break patch working.  Try pulling this down and running:

- `composer require drupal/entity_print:^2.3`
- `yarn workspace admissions_core build`
- `drush @admissions.local cr`
- Trying selecting multiple items on https://admissions.local.drupal.uiowa.edu/areas-of-study/kiosk.

**Comment by cory-skeers** [comment]
I can take a look at this

**Comment by dnkemper** [comment]
thank you, @cory-skeers 🥳

**Comment by cory-skeers** [comment]
Interacting with the filters (either the search box or the academic interest toggles) clears any currently selected checkboxes.

Search field scenario:

- Search for one AoS (e.g. comp sci) and check it
- Search for a second (or more) AoS (e.g. data science) and check it
- Only the AoS(s) selected after the last search/filter interaction will print

Toggles scenario:

- Choose one area of interest
- Select an item from that area
- Toggle on another area of interest
- The previously selected item will remain in the list, but no longer be checked

**Comment by GaryRidgway** [comment]
@cory-skeers I will try and figure out a solution for this!

**Comment by GaryRidgway** [comment]
@cory-skeers you should now be able to do what you have described. Also, I added support for printing checked options that are no longer on the screen after a filter is checked. For example, If you check something, choose a filter, and then choose something else, it will still track that you checked something that is not available in the current filter and add that to the print document.

**Comment by cory-skeers** [comment]
@GaryRidgway Awesome--pulling down the changes and will continue testing!

**Review by cory-skeers — APPROVED** [review]
This looks great, and everything's working as expected.

Good work team!

**Comment by dnkemper** [comment]
thank you so much, @cory-skeers 🥳

**Comment by pyrello** [comment]
Hey. I'm going to make a few very small changes that don't affect functionality.

**Comment by GaryRidgway** [comment]
I think I want to do a comment pass before we ship if that's okay?

**Comment by pyrello** [comment]
I'm done.

**Comment by dnkemper** [comment]
thank you, @pyrello 👍

**Comment by dnkemper** [comment]
@GaryRidgway may I merge or still wait?

**Comment by GaryRidgway** [comment]
@dnkemper I am almost done, just doing the comments

**Comment by GaryRidgway** [comment]
@dnkemper now you are good to go!

**Comment by dnkemper** [comment]
@GaryRidgway I did it 🤓

**Pull request merged**
