### PR TITLE
Added sidebar menu configuration for businessmanager.fo.uiowa.edu

### PR DESCRIPTION
**Pull request by dnkemper**
Apparently you have to hardcode changes in blocks. Darn. Added Sidebar menu to display all of their links like they requested.

### CODE REVIEW

**Review by briand44 — COMMENTED** [review]
I would like Joe and/or Rick to weigh in on this. My thought is we should be config ignoring this so all customers have this ability. You mentioned they didn't have permissions to do this as well. I think that would be another service wide config change.

**Comment by briand44** [comment]
I don't think we want to be going custom with this site. We want to investigate if we can add this functionality to the entire SiteNow v2 service.

**Comment by dnkemper** [comment]
@briand44 if we remove the config split file, it will affect SiteNow sites

**Comment by richardbporter** [comment]
Yea, we probably should not be config-splitting standard SiteNow sites. If the behavior is desired for all sites, then adding it to the sitenow sync directory would be fine. However, I think @briand44 tested this and was unable to get working on another site.

**Comment by joewhitsitt** [comment]
Without testing this, I don't know what it changes exactly. Is there an issue that describes the change? All I can say is that the current configuration was decided by Adam and I based on the offerings available in the D8 version (not as good as D7). It is supposed to show the first level of children for the current page. https://sitenow.uiowa.edu/documentation/media with the breadcrumb or top-nav being used as the "backtrack"

I don't care if it changes for the service. I would resist changing it for this one site. I think blocks are ignored, so an update hook is probably necessary to update existing sites.

**Comment by richardbporter** [comment]
Let's close this and potentially follow up with other issues that describe what the problems are.

**Pull request closed without merging**
