### PR TITLE
Extend Linkit to other link fields

### LINKED ISSUE #4235: Add link context to structure menu link search
# Story

As an editor, I would like to be able to link content on block types as well as the menu management interface using the autocomplete functionality found in the WYSIWYG.

# Problem
Within a Structure > menu page, when you use the search to choose where to link the page to, it does not provide context on whether it is a page, article, or person.

Screen Shot 2021-09-30 at 1 21 33 PM

# Steps to reproduce
Go into  Structure > Menus and edit/add a page and use the search menu to choose a link destination.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/4235

Menu link content support:

258191224-a9b8c6aa-5b25-4f63-8856-c1caa200abdf

Layout builder block and paragraphs support:

Screenshot 2023-08-04 at 2 00 45 PM

# To Test

As an editor, I can get autocomplete content context (linkit) as I start typing for menu links administered through /admin/structure/menu as well as all of the default sitenow v3 block content types (e.g. card, banner, cta) and their nested paragraphs (e.g. timeline item) similar to when using the WYSIWYG.

The following link fields are supported as part of this PR:

menu_link_content link

field_collection_more_path (ui events)
field_uiowa_banner_link
field_uiowa_button_link
field_uiowa_card_link
field_uiowa_cta_link
field_uiowa_event_link
field_uiowa_image_link
field_uiowa_quote_citation (blockquote)
field_timeline_link
field_uiowa_slide_link

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Styling could be better, but the functionality is there. Looks like `#drupal-off-canvas` is overriding the styles in a bad way.

Screenshot 2023-08-03 at 12 21 09 PM
Screenshot 2023-08-03 at 12 20 43 PM

**Comment by bspeare** [comment]
This gets it looking a little better if you can figure out the header part:

```
#drupal-off-canvas .ui-autocomplete.linkit-ui-autocomplete span:first-child {
  display: block;
  font-weight: bold;
}

#drupal-off-canvas .ui-autocomplete.linkit-ui-autocomplete {
  width: 85%!important;
}
```

**Comment by joewhitsitt** [comment]
>This gets it looking a little better if you can figure out the header part

Thanks @bspeare, I'll try to take a look at this a bit later.

**Comment by bspeare** [comment]
This looks good.  Should we try a `:focus` and `:hover` fix here too?  Do you think that gray passes validation?

**Review by bspeare — APPROVED** [review]
Tested on all of the fields.  I added a background color contrast fix for the hover/focus states of off-canvas and claro forms.

**Pull request merged**
