### PR TITLE
Media Tagging Support

### LINKED ISSUE #137: Investigate organizing media library solutions.
Feedback stated it would be nice to organize the media library using an arbitrary user structure.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/137

This satisfies the first step towards something more https://github.com/uiowa/uiowa/issues/3453. Site editors can tag media and find media by tag. Tagged media _do not_ show on taxonomy term pages but _are_ visible in the usage tab. This PR is affected by... you guessed it... https://github.com/uiowa/uiowa/issues/3204

# Story

As a site editor, I can tag new and existing media entities for organizational purposes and then filter by tag on the media overview and media library/browser displays.

# To Test

- sync admissions, v2, v3 sites.
- When adding or editing media (all default types), you can add tags to the media entity
- You can filter by those tags within the media overview page or when adding media via wysiwyg
- When you view a taxonomy term page, the referenced media entities should not display similar to tagged content (page, article, person) but can be seen within the usage tab of the taxonomy term.
- Admissions does not have any config import issues.

### CODE REVIEW

**Comment by richardbporter** [comment]
Is this expected? On the default (V3) site.
Screen Shot 2021-09-15 at 10 10 02 AM

**Comment by joewhitsitt** [comment]
Oops. pull, cim, check?

**Comment by richardbporter** [comment]
That fixed it.

I'm getting duplicate results when using two tags in filter. I think this is also happening with content so maybe doesn't need to be addressed here.

Screen Shot 2021-09-15 at 10 18 24 AM

To reproduce:
- tag one item with foo
- tag another item with bar
- tag another item foo and bar
- filter by foo and bar

**Comment by richardbporter** [comment]
I don't see the tag filter on the media library modal when editing a basic page on the default site:

Screen Shot 2021-09-15 at 10 22 48 AM

**Comment by joewhitsitt** [comment]
> I don't see the tag filter on the media library modal

I will take a look at this. Thought I had this setup.

**Comment by richardbporter** [comment]
> > I don't see the tag filter on the media library modal
> 
> I will take a look at this. Thought I had this setup.

Also not seeing it on V2 site.

**Comment by richardbporter** [comment]
That did the trick. I'm kinda thinking we should look into the duplicate results in this PR because it might confuse people:

Screen Shot 2021-09-15 at 11 16 45 AM

Sorry if this is just user error on my part. :)

**Comment by joewhitsitt** [comment]
that is valid. i can turn on "reduce duplicates" for all of these and go back to content overview tags filter and do the same there.

**Comment by richardbporter** [comment]
No more dupes.

>When you view a taxonomy term page, the referenced media entities should not display similar to tagged content (page, article, person)

Media does not show, tagged content does display on the term pages though. Content is supposed to right? Am I just reading this wrong?

**Comment by joewhitsitt** [comment]
Correct. tagged "content" should be listed. tagged "media" should not. both "content" and "media" should show in usage as content/media is saved (we didn't bulk update existing usage when we fixed it)

**Review by richardbporter — APPROVED** [review]
Ok, I'm not seeing anything else. NOICE!

**Pull request merged**
