### PR TITLE
Feature: brand site adjustments 

### PR DESCRIPTION
**Pull request by bspeare**
This PR contains work for https://github.com/uiowa/uiowa/issues/1557. 

# How to test

`blt sync --site brand.uiowa.edu`
`blt frontend`

# Removed top padding from first paragraph item on each page. 

- Test on https://brand.local.drupal.uiowa.edu/logo that first paragraph section has top padding removed.    

Screen Shot 2020-05-19 at 2 27 26 PM

# Spacing below page title on pages not using layout builder or paragraphs https://github.com/uiowa/uiowa/issues/1534

- Add a person to https://brand.local.drupal.uiowa.edu/ or a new content type and verify that there is `1.5rem` margin added to the page title block. 

Screen Shot 2020-05-19 at 2 30 56 PM

# Image alignment https://github.com/uiowa/uiowa/issues/1411

- Add an image inline to a page/section with body text and check the alignment/padding at small breakpoints.   I am removing the right/left alignment for mobile.  Let me know if you agree with this and whether the image and caption padding are working at wider breakpoints. 

Screen Shot 2020-05-19 at 2 33 46 PM

# Lockup preview https://github.com/uiowa/uiowa/issues/1590

- Go to Create a lockup page and verify that preview text has changed but is still accessible. 

Screen Shot 2020-05-19 at 2 43 29 PM

# Background color changes https://github.com/uiowa/uiowa/issues/1591

- Change the background color on a section and on a text block in `uids_base` and `uiowa_bootstrap` and verify that the `Black Background` option works and that the `Dark Background` in `uids_base` has changed to a cool gray color. 

Screen Shot 2020-05-19 at 2 46 24 PM

Screen Shot 2020-05-19 at 2 45 02 PM

Screen Shot 2020-05-19 at 2 46 42 PM

# UIDS Mobile Header updates

- Change the header settings in `uids_base` and verify that mobile experiences is consistent and the search works. 

Screen Shot 2020-05-19 at 2 50 10 PM

Screen Shot 2020-05-19 at 2 51 39 PM

### CODE REVIEW

**Review by joewhitsitt — APPROVED** [review]
Thanks for these updates!

Works as expected but a few notes that might not have been in scope for this PR. I can create issues for these if we want to get this one out.

- Center aligned wysiwyg images didn't work for me in uids_base. Don't know if that was in scope of #1411.

- In relation to the background colors, follow up is needed to account for conflicting link styles (alerts, paragraphs with their own bg options, wysiwyg blockquote), etc. with foreground elements. Not sure black is covered completely in uiowa_boostrap/uids_base and dark in uids_base. 

Screen Shot 2020-05-20 at 8 49 40 AM
Screen Shot 2020-05-20 at 8 50 35 AM

**Comment by bspeare** [comment]
@joewhitsitt Thanks for testing these!  I would like to verify that those can be fixed before closing this.

**Comment by bspeare** [comment]
@joewhitsitt can you explain what site/content type you tried to center images on?  I am not seeing the issue with centering yet.

**Comment by joewhitsitt** [comment]
I believe it was brand site with uids_base, basic page > section > text area wysiwyg drupal-entity large view mode with caption. the wysiwyg centers it, but the render is left aligned.
Screen Shot 2020-05-20 at 10 29 47 AM

**Comment by joewhitsitt** [comment]
@bspeare do you want me to focus on some of the background layering issues?

**Comment by bspeare** [comment]
@joewhitsitt That would be great if you could take a look at those.  I'll continue on the alignment fix.

**Comment by joewhitsitt** [comment]
@bspeare so this is the kitchen sink problem with all of the paragraph options (aka problems). I am going to attach this here because it will be easier to work on other issues as they come up (webform). I think I captured most of the "supported" possibilities

i will start working on this

brand local drupal uiowa edu_kitchen-sink
[kitchen-sink.txt](https://github.com/uiowa/uiowa/files/4658757/kitchen-sink.txt)

**Comment by joewhitsitt** [comment]
I think uiowa_bootstrap and hr now covered for the new black option.

Still much to do in uids_base for other paragraph bundles (e.g. articles) when it comes to section background colors. Articles for example is using the .card class which has a white background.

**Comment by bspeare** [comment]
@joewhitsitt Thanks for your help with this.  Are you ok with merging this and handling the rest of the paragraph bundles in future work?

**Comment by joewhitsitt** [comment]
Yeah, I created a follow-up issue #1654

**Pull request merged**
