### PR TITLE
Tippie - Split robots.txt

### PR DESCRIPTION
**Pull request by joewhitsitt**
Has the robots.txt adjustment from https://github.com/uiowa/uiowa/issues/6835

Screenshot 2023-10-23 at 5 10 59 PM

Unfortunately this can't be partially split as it is all one line. We will have to update with the d10 updates once this is merged https://github.com/uiowa/uiowa/pull/6994/commits/b57ac7aa5603a416260ebea32f7d94ff35f691b5

### CODE REVIEW

**Comment by pyrello** [comment]
I wondering about, instead of doing this for Tippie, should we just make this the default for the platform? Opt out of being crawled by AI crawlers (that observe the directive) until we can better understand it and/or someone asks for their content to be available to be crawled?

**Comment by joewhitsitt** [comment]
So you suggest disallow / for the user agent GPTBot for all sites? Tippie is only doing the /advisor path currently.

>The rest of the Tippie we[b] properties can certainly be open to generative app crawlers. For The Advisor, I’ll continue to look for every way I can find to block generative app crawlers.

**Comment by cory-skeers** [comment]
> I wondering about, instead of doing this for Tippie, should we just make this the default for the platform? Opt out of being crawled by AI crawlers (that observe the directive) until we can better understand it and/or someone asks for their content to be available to be crawled?

As silly as it may be, I worry that ChatGPT and its ilk may be used (or be used in the future) for things like prospective students looking for information on UI, admissions, etc. The tool absolutely should not be expected to be accurate in that realm, but the use of digital tools often doesn't match up with "should" (thinking of people using Instagram search features over Google's). And in that case, even if it's a tiny niche of the billions of parameters that get slightly tuned toward accuracy by crawling our actual content, I would lean toward allowing the tools that are going to be used to crawl (the majority) of our sites.

I think we absolutely need to keep the conversation going, but in the interim, I'd be in favor of an opt-out approach like this until we come up with a policy on what we block and how we determine what gets blocked (block any for-profit tools? any generative tools regardless of for-profit or non-profit, etc).

**Comment by pyrello** [comment]
After a conversation about this in Daily Scrum, I see there is more complexity to this and differing opinions that will require more time and information to sort out. As such I think we should proceed with this change for now.

**Review by pyrello — APPROVED** [review]
Reviewed, not tested.

**Pull request merged**
