### PR TITLE
Remove collegiate profile and related clean-up

### LINKED ISSUE #1247: Move sitenow configuration to default directory
It would be nice if we could move sitenow config to the default directory as outlined in the BLT docs: https://docs.acquia.com/blt/developer/config-split/#default-configuration

Multiple profiles running disparate config syncs works but isn't really supported by BLT. Advantages of this approach:

- Refer to platform configuration as default and not any one profile, i.e. sitenow
- Potentially setup profile splits, although more granular feature splits might be preferable
- Config lives outside docroot
- Potentially use hook_install() in profile(s)
- One less site/database as the default could be used for a demo site.

### LINKED ISSUE #1248: Remove global settings sync dir check
This seems like a complicated global setting to run on every site. The default BLT behavior should probably be enabled and individual sites or profile-specific settings can override this if desired.

### LINKED ISSUE #1477: Post Collegiate clean-up
- [x] Remove `docroot/profiles/custom/collegiate`.
- [x] Remove `docroot/themes/custom/collegiate_theme`.
- [x] Remove `collegiate_theme` entry from package.json workspaces.
- [x] Remove `Uiowa\Blt\Plugin\Commands\ReplaceCommand::replaceSetup` (https://github.com/uiowa/uiowa/blob/fc7fe6af7c60024677380f0da72e9b74257c6fac/blt/src/Blt/Plugin/Commands/ReplaceCommands.php#L74) to remove looping through profiles.
- [x] Compare collegiate.info.yml with composer.json to see if any dependencies can be removed.
- [ ] Archive https://github.com/uiowa/hds
- [x] Remove profile argument from `uiowa:multisite:create`.
- [x] Remove uiowa.profiles custom configuration from blt.yml. Move requester config up for new and existing sites.
- [x] Set cm.core.install_from_config to true in blt.yml.
- [x] Remove default profile configuration from site creation process.
- [x] Update all existing site blt.yml files to remove profile specific config.
- [x] Move sitenow.settings.php to global.settings.php and remove profile specific include chain.
- [x] #1248 
- [x] #1247

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #1477 
Resolves #1247 
Resolves #1248 

# To test
* No build issues
* `blt ds` any site (since they're all SiteNow sites!)
* `drush uli` to look at the site locally

### CODE REVIEW

**Review by richardbporter — APPROVED** [review]
This looks ok to me but would like to get @mark-bennett-uiowa to look at it as well.

**Comment by richardbporter** [comment]
I'm going to jump in here and some additional tasks from #1477.

**Comment by mark-bennett-uiowa** [comment]
Tested this after @richardbporter committed [7f5946f](https://github.com/uiowa/uiowa/pull/1603/commits/7f5946f47fc9ba3f9ec1a5cbe6a5bd27c69f33c6) and was able to ds and uli into the local claspolicy site. Did have to perform a `drush @claspolicy.local cr` before that would work however.

**Review by richardbporter — APPROVED** [review]
Probably don't want to wait too long on this one considering it moves all config. I synced sites locally and didn't notice any issues but testing sites locally would be good.

**Comment by pyrello** [comment]
I tested against a sampling a sites using `blt dsa`. I think with that plus a passing build, it should be good to go.

**Pull request merged**
