### PR TITLE
Update drupal core to 10.1.8

### LINKED ISSUE #7175: CSS/JS aggregation issues since 10.1 update
# Problem

The issue was first reported by Denny Crall related to sites that use the Directory Profiles integration. On the directory profiles page, the page was failing to load. Eventually we discovered that turning off JS aggregation in production works as a temporary workaround. I was able to reproduce locally by turning on JS aggregation in `local.settings.php` for the site I was debugging (Education)

## Related information
- CSS/JS aggregation change introduced in 10.1.0: https://www.drupal.org/node/3301716
- Bug identified and fixed with the above change: https://www.drupal.org/project/drupal/issues/3370828
- Fix applied in 10.1.2 (as of this writing we are on 10.1.6): https://www.drupal.org/project/drupal/releases/10.1.2

# Steps to reproduce
```
ddev blt ds --site eductation.uiowa.edu
```
- Change `FALSE` to `TRUE` in `docroot/sites/education.uiowa.edu/settings/local.settings.php` on line `63`.
- Visit https://education.uiowa.ddev.site/directory

# Proposed solution

- https://github.com/uiowa/uiowa/issues/7175#issuecomment-1883661252

### PR DESCRIPTION
**Pull request by joewhitsitt**
- drupal/core-composer-scaffold (10.1.6 => 10.1.8)
  - drupal/core-project-message (10.1.6 => 10.1.8)
  - symfony/yaml (v6.3.7 => v6.3.8)
  - symfony/string (v6.3.5 => v6.3.11)
  - symfony/console (v6.3.4 => v6.3.11)
  - symfony/filesystem (v6.3.1 => v6.4.0)
  - symfony/process (v6.3.4 => v6.3.11)
  - symfony/finder (v6.3.5 => v6.4.0)
  - guzzlehttp/promises (2.0.1 => 2.0.2)
  - symfony/var-dumper (v6.3.6 => v6.3.11)
  - symfony/event-dispatcher (v6.3.2 => v6.3.11)
  - nikic/php-parser (v4.17.1 => v4.18.0)
  - symfony/validator (v6.3.7 => v6.3.11)
  - symfony/serializer (v6.3.7 => v6.3.11)
  - symfony/routing (v6.3.5 => v6.3.11)
  - symfony/http-foundation (v6.3.7 => v6.3.11)
  - symfony/http-kernel (v6.3.7 => v6.3.11)
  - symfony/var-exporter (v6.3.6 => v6.3.11)
  - symfony/dependency-injection (v6.3.5 => v6.3.11)
  - pear/pear-core-minimal (v1.10.13 => v1.10.14)
  - drupal/core (10.1.6 => 10.1.8)
  - symfony/dom-crawler (v6.3.4 => v6.4.0)
  - symfony/css-selector (v6.3.2 => v6.4.0)
  - symfony/browser-kit (v6.3.2 => v6.4.0)
  - theseer/tokenizer (1.2.1 => 1.2.2)
  - sebastian/lines-of-code (1.0.3 => 1.0.4)
  - sebastian/complexity (2.0.2 => 2.0.3)
  - phpunit/php-code-coverage (9.2.29 => 9.2.30)
  - phpunit/phpunit (9.6.13 => 9.6.15)
  - phpstan/phpdoc-parser (1.24.2 => 1.25.0)
  - phpdocumentor/type-resolver (1.7.3 => 1.8.0)
  - phpspec/prophecy (v1.17.0 => v1.18.0)
  - react/promise (v3.0.0 => v3.1.0)
  - behat/mink (v1.10.0 => v1.11.0)
  - behat/mink-browserkit-driver (v2.1.0 => v2.2.0)
  - drupal/core-recommended (10.1.6 => 10.1.8)
  - symfony/cache-contracts (v3.3.0 => v3.4.0)
  - symfony/mailer (v6.3.5 => v6.4.2)

# Test

- Passing build, inspect changes.
- Run site install, site sync. Login and poke for issues.
- No database updates
- Resolves https://github.com/uiowa/uiowa/issues/7175
  - `ddev blt ds --site=education.uiowa.edu` make sure the local.settings.php file is set to true for css/js aggregation and go to https://education.uiowa.ddev.site/directory/

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Running an site install and spot checking a site sync.

**Comment by joewhitsitt** [comment]
As an aside in my brief testing of turning on aggregation locally for education and trying to go to https://education.uiowa.ddev.site/directory, the update in 10.1.7 doesn't seem to be related. still need the `preprocess: false`. Relates to https://github.com/uiowa/uiowa/issues/7175

Update: fixed with https://github.com/uiowa/uiowa/pull/7273/commits/0d5fd6f056d30bbb68a1b611d392db45c4f565eb

**Review by bspeare — APPROVED** [review]
Education profiles worked, didn't notice anything particular in poking around.

**Comment by pyrello** [comment]
> Update: fixed with https://github.com/uiowa/uiowa/commit/0d5fd6f056d30bbb68a1b611d392db45c4f565eb

Is there a link to a change record or other documentation you referenced to come up with this fix?

**Comment by joewhitsitt** [comment]
I was about to pass this issue to Denny when I realized one of our javascript files was possibly involved. While looking at the library definition to find the js file, the IDE was flagging it as an issue. Seemed weird in a yaml file. Searched for other instances of an MIT license. https://github.com/uiowa/uiowa/issues/7175#issuecomment-1897160671

**Pull request merged**
