### PR TITLE
Tippie pardot2

### LINKED ISSUE #3811: As a MarTech person, I want our CRM module enabled in Tippie so that we can use it for recruitment
# Story

TIPPIE - As a MarTech person, I want our CRM module enabled in Tippie so that we can use it for recruitment.

Pardot module: copy/edit/create https://www.drupal.org/project/pardot
https://git.drupalcode.org/project/pardot/-/blob/8.x-1.x/pardot.info.yml
https://www.drupal.org/project/pardot/issues/3176074
https://help.salesforce.com/s/articleView?id=000312312&type=1

An anonymous cookie is dropped via GTM when a user visits Tippie. Their browsing history is captured in that. Then once they submit a Drupal webform, the Pardot module takes their anonymous browsing history and attaches it to their known ID (which is coming from the webform). So basically pre-webform-submission browsing history and post-webform-submission browsing history are attached to a known ID that is then passed to Pardot.

From user: "The Pardot cookie basically allows Pardot to take their “anonymous cookie” – the one they got the moment they visited a Tippie web property – and tie it to their “known cookie”, the one that contains their name and email. This is how we can see someone’s browsing history once they’ve converted… not just the pages they visit AFTER filling out the conversion form/RFI… but everything they did before conversion on our site."

# Proposed Solution
Using test accounts that Makur and Joe have try to send data to Pardot using one of the following making sure that the GTM pardot code is included in the DOM:

- [x] ~~Re-visit https://www.drupal.org/project/pardot and try the 2.x dev branch - _installed_~~
  - [x] ~~Try the webform integration patch https://www.drupal.org/project/pardot/issues/2878909~~
  - [x] ~~Generally see how the module development is going and see if it is worth waiting or put effort in there.~~
  - [x] ~~Reach out to EduDu Slack group and see if they have made progress with Pardot for D8/9~~
- [x] ~~In a tippie_core module try something similar to the D7 versions where they make a client side request using a faux object: https://github.com/uiowa/uiowa/issues/3811#issuecomment-1009381466, https://github.com/uiowa/uiowa/issues/3811#issuecomment-1022319225~~
- [x] Remove previous iframe related code from tippie_core
- [x] Referencing https://github.com/uiowa/uiowa/issues/3811#issuecomment-1055931872, create a JS script that is loaded into webform (form_alter) if remote post and a certain hidden visitor_id field is set by the form editor. Get the visitor_id cookie and make it the value of that hidden input.
- [ ] Have customer test in DEV
- [ ] Before merge to main, make sure environment based check on google tag manager in uiowa_core is set

### PR DESCRIPTION
**Pull request by makurj**
Resolves #3811

Assumes "page" confirmation method is set.

# To Test
- Customer is checking the integration with Pardot.
- Technical review of the code.
- Sync tippie down and as a webmaster ensure that you can add the handler without error and have settings saved (included/excluded values)
- Create a hidden field "visitorid" on a webform. See if that field has a submission value.

# ToDo

- [x] Customer approval from testing in DEV
- [x] Uncomment environment restriction [docroot/modules/custom/uiowa_core/uiowa_core.module]

### CODE REVIEW

**Comment by makurj** [comment]
Next steps:

1. Add config to add per handler endpoint URL
2. Investigate dynamically adding webform values
3. Investigate alternative confirmation options (for example, URL) before the iframe gets inserted

**Comment by joewhitsitt** [comment]
This has been deployed to DEV again for customer review

**Comment by richardbporter** [comment]
Setting an additional FQDN under `tippie.uiowa.edu` for ddev got the cookies working locally. I was able to see and debug the `visitor_id` cookie in PHP. I changed the PR to attach a form validator instead of JS which saves the visitor ID to the hidden form field on submission. 

The next step would be to test this in dev by adding the hidden form field to the remote post handler. I merged this into develop and pushed.

I don't think we want to commit the ddev FQDN changes without further discussion so I just have those stashed locally.

**Comment by makurj** [comment]
As we hardcoded the machine name for the hidden field, should we change "pardot_visitor_id" to "visitorid" as that's what Lydia is planning to use on all the forms?

**Comment by makurj** [comment]
Heard back from user, this is good to be deployed to prod.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
