### PR TITLE
Sprint 207 Facilities work

### LINKED ISSUE #7540: Facilities sorting issues
> That all looks good, thanks!  I noticed on the project info page if you click on the  “building” and “number” headers it doesn’t sort in alphabetical order. The project title does.
> On Featured project and Capital project pages, the project title and number headings sort in order, but the building header does not.
> Is that fixable?

In my testing I am only seeing issues with sorting by building on all three of these pages.

# Proposed Solution

- Fix building sort on featured, capital and project information pages
- Verify number and title columns are sorting correctly

### LINKED ISSUE #7543: Facilities Alert questions/issues
> - Previously there was a user role called  “construction managers” for Alerts. I believe it restricted them from making any changes to the rest of the website. I don’t see that user role on the new site. Is there a role already there that would give us the same control or does it need be created?

We have the collaborator role that construction managers should be assigned to correct?

> - I got an error on the traffic control link in the email when I created a test alert and uploaded a traffic control plan .pdf. It looks like the link doesn't have "prod.drupal" in the name so that might be the issue, which should correct itself when the site is live? Also, the old site has very specific naming restrictions for .pdfs or else the system would throw an error when it was clicked on in the alert email/site. For this site, can we use any naming convention or are their restrictions like no spaces, or something else?

> - The active Engie alert uses an image file for the traffic control plan and we couldn't upload it to the new system. Can we allow image files in this field please?

> - See the screenshots below for how my test alerts are displaying in Lauren’s email. For fields that are linked (the building and traffic control plan) her browser email is displaying the link information in brackets instead of making them hyperlinks. If she clicks "View message in browser" it fixes the issue and it doesn't seem to be happening on her desktop app version of Outlook. These links appear correctly in my email alerts; however, again the building and traffic control links don’t work (maybe b/c in prod?)
```[tasklist]
### Proposed Solution
- [x] Let Facilities know the Collaborator role should be used for Construction Managers
- [ ] Let Facilities know if there are any naming restrictions for traffic control file uploads (no spaces, etc.)
- [x] Make sure links to traffic control plan files work
- [x] Allow images to be uploaded to traffic control plan
- [x] Make sure building link works in alert emails
```

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #7540
Resolves https://github.com/uiowa/uiowa/issues/7543

# To Test
```
ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli
```
## Project views sorting

- Go to https://facilities.uiowa.ddev.site/project-information  and see that the column label is still "Building", that the buildings are properly linked and that the column can be sorted by building name. See that you can still filter by project building and search for building alternates in the input (e.g. "Hawkeye Parking Ramp")
- Go to https://facilities.uiowa.ddev.site/project-information/featured-projects and see that the column label is still "Project building," that the buildings are properly linked and that the column can be sorted by building name.
- Go to https://facilities.uiowa.ddev.site/projects/project-information/capital-projects and see that the column label is still "Project building," that the buildings are properly linked and that the column can be sorted by building name.
- Go to https://facilities.uiowa.ddev.site/building/0042 and see that the items are sorted by project number.

## Alerts

- Go to https://facilities.uiowa.ddev.site/alert/5951 and confirm that building and traffic control plan both render as absolute urls.  Inspect the source to confirm. 
- Edit the alert and confirm that you can upload an image into the traffic control plan and that the image also renders as an absolute url. 
- Inspect placeholder values on https://facilities.uiowa.ddev.site/node/5951/dispatch and confirm both render as absolute urls.

### CODE REVIEW

**Comment by bspeare** [comment]
I have tested @joewhitsitt's changes and can confirm that are working as described.

**Comment by bspeare** [comment]
The alerts part of this pr is ready for review.  I have previously reviewed the project views sorting https://github.com/uiowa/uiowa/pull/7544#issuecomment-2040632470.

**Comment by e-marie-w** [comment]
I can test the alerts part of this

**Review by e-marie-w — APPROVED** [review]
I tested alerts part, building and traffic control plan are now rendering as absolute URLs on the alert view and in the dispatch part. An uploaded image to the traffic control plan also correctly renders as an absolute URL. 

Approving based on my alerts testing and Ben's previous testing of the projects part.

**Comment by joewhitsitt** [comment]
@bspeare sorry i just noticed this. i have had my head down in migrations. is there a reason you are creating the links this way?

```
Link::fromTextAndUrl('My Link', Url::fromUri('https://example.com')),
```

Not sure the benefits but there would be more consistency across our platform

**Comment by bspeare** [comment]
Thanks @joewhitsitt.  No reason! I appreciate the suggestion.  Is https://github.com/uiowa/uiowa/pull/7544/commits/b9587020ae4034a0f12d0dcd4cecf6b844d52ccf what you meant?

**Comment by joewhitsitt** [comment]
@bspeare yes. If this works. Untested. We've also used `->toString();` instead of `toRenderable`

**Comment by joewhitsitt** [comment]
Just pulled and confirmed the links are outputting as expected. Thanks for making the change. 👍

**Pull request merged**
