### PR TITLE
[Find Text] Update version, remove SiteNow Find Text

### LINKED ISSUE #5383: Clean up sitenow_find_text from the codebase, finish transition to find_text
Blocked by #5363 (needs to be in a later deployment)

sitenow_find_text has moved to https://www.drupal.org/project/find_text. Because of order of operations in the build and deployment process, previous work disabled sitenow_find_text and enabled find_text, but sitenow_find_text still exists in the codebase.

# Proposed solution
Remove sitenow_find_text
Update gh sitenow_find_text label to find_text
Check that any issues in our repo are represented on the project issues, and that any issues in the project repo have a tracker issue here

### LINKED ISSUE #6552: Find text can run out of memory and error out
# Problem
SiteNow Find Text can run out of memory.

# Steps to reproduce
https://onenr.io/0BQrxp4ynRZ

# Proposed solution
~Update the `searchButton` callback to exit early if the `needle` is less than 3 characters. The form validate function can be left in place to add the actual error, but this will prevent the processing from (wrongly) occurring.~
Update is in place in https://git.drupalcode.org/project/find_text/-/commit/781ad170f30860c1e22c8515299ddfdb88251219

Next steps--create a release for Find Text, then update composer to pull in the newly updated version.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #6552 (first steps--we should create a followup for further protection through paging or other solutions)
Resolves #5383 

# How to test

`composer install`
Sync a site, use the Find Text tool
Try searching for an empty string and/or a string of fewer than 3 characters
See that not only do you get the error message, but also it doesn't bring up results (or attempt to bring up results and crash the page)
When searching a string, try hitting Enter while the search text field is in focus, and see that it successfully submits the form - Huzzah!

### CODE REVIEW

**Comment by cory-skeers** [comment]
Build failing, Travis looking for the previous `sitenow_find_text` tests:
```
Test directory "/home/travis/build/uiowa/uiowa/./docroot/modules/custom/sitenow_find_text/tests/" not found
 [Acquia\Blt\Robo\Tasks\PhpUnitTask]  Exit code 2  Time 0.389s
 [info] Killing running google-chrome processes...
 [info] Killing all processes on port '9222'...
 [info] Killing running chromedriver processes...
 [info] Killing all processes on port '9515'...
 [error]  PHPUnit tests failed.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
```

**Comment by cory-skeers** [comment]
Setting back to draft, as there are likely some more updates to Find Text coming soon.

**Comment by cory-skeers** [comment]
May be more changes coming down the pipeline, but all in-progress updates are now in. Ready for review again.

**Review by e-marie-w — APPROVED** [review]
This is working great! I'm really excited I can hit Enter to search now. Empty strings and less than 3 char searches now properly error instead of crashing. I tested on default and sandbox. Thanks for updating this @cory-skeers!

**Pull request merged**
