### PR TITLE
Webform d10 from 6.1.3 to 6.2.0-beta6

### PR DESCRIPTION
**Pull request by bspeare**
Patch from https://github.com/uiowa/uiowa/pull/6698 has been removed and file seems to be uploading locally. 

# How to test

**Fresh install**
```
ddev drush @default.local si sitenow && ddev drush @default.local uli
```
**Run all multisites**

```
ddev blt ume sql:drop && ddev blt dsa
```
**Sandbox only**
```
ddev composer install && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /admin/structure/webform
```

## Update hooks being run

```
  webform      8637                             hook_update_n   8637 - Issue #3249092: Disable 'Allow users to post submissions from a dedicated URL' for all webforms.    
  webform      ckeditor                         post-update     Move from custom CKEditor to hidden 'webform_default' text format.                                         
  webform      ckeditor01                       post-update     Issue #3351348: '#multiple__no_items_message' added to every field.                                        
  webform      confirmation_page_noindex        post-update     #3335924: Allow the confirmation page to include robots noindex meta tag.                                  
  webform      deprecate_jquery_ui_datepicker   post-update     #3254570: Move jQuery UI datepicker support into dedicated deprecated module.                              
  webform      deprecate_location_places        post-update     Issue #3247475: Location field Algolia Places sunsetting May 31, 2022.                                     
  webform      multiple_categories              post-update     Issue #3339769: Improve Webform categorization to support assigning multiple categories and default        
                                                                categories.       
```

## New config

```
	config/default/editor.editor.webform_default.yml
	config/default/filter.format.webform_default.yml
```

### CODE REVIEW

**Comment by bspeare** [comment]
After syncing uiowa.edu, I'm getting this error message:  
`In SqlCommands.php line 199:`                                                                                                                                                 `Query failed. Rerun with --debug to see any error message. ERROR 1114 (HY000) at line 14167: The table ``'webform_submission_data' is full`

Update: I synced again after clearing up space in Docker and I am no longer getting this error.

**Comment by bspeare** [comment]
I have run `ddev blt dsa` on 37 sites with no install errors and tested out sandbox forms and uiowa.edu forms.  Do other team members want to try and test this?  It seems like webform is so big that there's a lot to test.

**Comment by joewhitsitt** [comment]
when there are db updates with this module i usually go through the webform settings and re-save all of the config through the UI and then export. also, tippie and maybe more are using the advanced_webform split for the remote post functionality

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Comment by bspeare** [comment]
I see `advanced_webform` listed as inactive on tippie and pharmacy - are they still using those?

**Comment by bspeare** [comment]
Found the remote post handler option available on tippie and it appears to still be set with webmaster access.

**Comment by joewhitsitt** [comment]
I guess they haven't adopted it yet, but that was the eventual plan. https://github.com/uiowa/uiowa/pull/5395 uip.pharmacy has it

**Comment by bspeare** [comment]
Tippie is setting the handler through their site split: https://github.com/uiowa/uiowa/blob/main/config/sites/tippie.uiowa.edu/config_split.patch.webform.settings.yml.  Do we need to move them to use the `advanced_webform` feature or should they continue with the site split that is only setting this custom value?

**Comment by joewhitsitt** [comment]
>Do we need to move them to use the advanced_webform feature or should they continue with the site split that is only setting this custom value?

I think the idea was to wait till we touch the Tippie split again and that there was no rush to move them over.

**Comment by bspeare** [comment]
I think this is ready for review.   I've tested the `advanced_webform` feature on uip and have run `ddev drush @default.local si sitenow` and resaved and exported the webform config.

**Comment by joewhitsitt** [comment]
going to pull this one down to test

**Comment by joewhitsitt** [comment]
I got a few config diffs after, re-saving all of the configuration pages and running the "repair config" tool under advanced. should i commit?

```
diff --git a/config/default/webform.settings.yml b/config/default/webform.settings.yml
index c592e15ef..675ded731 100644
--- a/config/default/webform.settings.yml
+++ b/config/default/webform.settings.yml
@@ -246,9 +246,15 @@ export:
   header_prefix: true
   header_prefix_key_delimiter: __
   header_prefix_label_delimiter: ': '
+  entity_reference_items:
+    - id
+    - title
+    - url
   options_single_format: compact
   options_multiple_format: compact
   options_item_format: label
+  likert_answers_format: label
+  signature_format: status
   composite_element_item_format: label
   excluded_exporters:
     yaml: yaml
@@ -360,9 +366,6 @@ ui:
   toolbar_item: false
 libraries:
   excluded_libraries:
-    - algolia.places
-    - ckeditor.codemirror
-    - ckeditor.image
     - jquery.chosen
     - jquery.rateit
     - signature_pad
 
```

**Comment by bspeare** [comment]
@joewhitsitt sounds good.  I had not run the "Repair" option.

**Comment by bspeare** [comment]
@joewhitsitt just noticed this unchecked on a sandbox install.   Are you seeing this?

Screenshot 2023-10-06 at 10 36 17 AM

**Comment by joewhitsitt** [comment]
Sorry, had to step away for a bit. Yes, I see this. It is new compared to PROD. I think we will want to mark that as checked.

Screenshot 2023-10-06 at 12 23 28 PM
Screenshot 2023-10-06 at 12 25 36 PM

**Review by joewhitsitt — APPROVED** [review]
a bit of run-around with config but looks good.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
