### PR TITLE
Remove duplicate profiles `<title>` element.

### PR DESCRIPTION
**Pull request by richardbporter**
# How to test

- Go to https://education.dev.drupal.uiowa.edu/directory and inspect meta tags like title, description, canonical and schema as you navigate between profiles and back to the directory listing.
- Compare the source code, not inspector, of the following URLs:
  - https://education.uiowa.edu/directory/john-achrazoglou
    - Notice the duplicate, empty `<title>` element.
  - https://education.dev.drupal.uiowa.edu/directory/john-achrazoglou
    - Confirm that the dev URL shows the correct meta tags: one title, description, canonical and schema while viewing source.
- Also, you can run some dev profile URLs through https://tamethebots.com/tools/fetch-render?utm_source=pocket_mylist and confirm those metatags are seen by bots. You need to uncheck "Honour robots.txt" and "Flatten DOM".

### CODE REVIEW

**Comment by cory-skeers** [comment]
Taking a peek at this.

**Comment by cory-skeers** [comment]
Going to take a look at some tamethebots test runs, but all manual testing/inspection is looking good.

**Comment by cory-skeers** [comment]
Ran several through the tamethebots test, and can confirm the metatags were seen by the bots.
https://education.dev.drupal.uiowa.edu/directory/gerta-bardhoshi
https://education.dev.drupal.uiowa.edu/directory/nick-colangelo
https://education.dev.drupal.uiowa.edu/directory/kari-vogelgesang

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested 💯

**Comment by mjoneill** [comment]
all metas are visible when viewing in chrome with JS off.  

Only one set of <title> tags.

This is looking good.

**Comment by richardbporter** [comment]
Thanks!

**Pull request merged**
