### PR TITLE
Refactor automatic site installs out of code deploy cloud hooks.

### LINKED ISSUE #1032: Automatic site installs taking too long in cloud hooks.
This was nice to get sites up and running quickly but its taking too long for cloud hooks to complete. It also affects sites that may need a cache rebuild quickly by delaying that with long running installs.

I think we should find another option here. Cron might work but we'd have to run it more often on dev/stage and add notifications for failures.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1032 

This PR creates a command that can be run manually or scheduled in desired environments. It changes the install process to use the BLT `drupal:install` command which handles some things we were doing manually with Drush.

### CODE REVIEW

**Comment by richardbporter** [comment]
Anyone have thoughts/questions on this?

**Review by joewhitsitt — APPROVED** [review]
Rick explained this to me and I approve

**Comment by richardbporter** [comment]
Copied slack notification functionality from AcHooksCommand in BLT.

**Review by pyrello — APPROVED** [review]
Reviewed, not tested.

**Pull request merged**
