### PR TITLE
Events pager

### LINKED ISSUE #5189: Add a pager option to the events block
# Story

As a site editor I want to display events with pager so that long lists of events don't disrupt my other page content

This is less of an issue at the moment, but if/when the events block options open further to allow for larger date ranges of events to be pulled in, a potentially large amount of content needs to be accounted for.

# Proposed solution

- Add a pager option to the events block form
  - Options may be a num results per page, or have each page cover a duration of time (week, month, etc.)
- Update events block rendering logic to include a pager

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/5189

Announced a change to the API:
https://iowaweb.slack.com/archives/C0KMREKNU/p1658435749631079

**For this to merge, a deployment of `content_hub_api_total_results` on uiowa702 needs to happen first.**

# To Test

- Sync down a v2 site, no config errors.
- Sync down a v3 site, no config errors.
- `drush cset sitenow_events.settings base_endpoint https://content.dev.drupal.uiowa.edu/api/v1/` on each site you are testing.
- See that you are able to interact (no errors) with events block the same and that you get the correct number of results based on a basic filter (audience: everyone, number of items: 3)
- Edit existing events block, create new events block, see the show pager checkbox. interact with it as it relates to the number of results field.
- If pager is on, the number of results is the number of items per page. Test the pager to make sure the items change and match the same order that would occur if you turned the pager off and increased the number of items.
- Past events option should also work.
- Anonymous users should get cached queries after initial paging. Cache times are the same as before.

Interesting tidbit: I think we have events from 2009 to 2025 in the system now

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Since it is still hardcoded +/- 365 days and easier to reach now with the paging, help text and documentation are probably warranted until we up the limit (2038?) or implement the date range.

Alternatively, we could take this moment to change the limits to 01/01/1970 and 01/19/2038 (UNIX time)

I just tried some big range queries on content hub and I am not getting back what I expected. Going to dig a bit.

**Comment by makurj** [comment]
Pulling down to test.

**Comment by briand44** [comment]
>Alternatively, we could take this moment to change the limits to 01/01/1970 and 01/19/2038 (UNIX time)

I think I am leaning towards going this route unless we have any concerns about performance, etc.

**Comment by makurj** [comment]
On HawkeyeMarchingBand V2 site, I am able to add the events block and narrow it down by audience and number of events. Once I save the layout, the block does not render. It's not even showing up in the DOM. Tried sql:drop, cr, and still the same behavior.

image
image
image

**Comment by makurj** [comment]
V3: students.tippie.uiowa.edu. 
1. Creating a new events block filtered by audience and 3 events - Works as expected.
2. Edit existing events block, create new events block, see the show pager checkbox. interact with it as it relates to the number of results field - Works as expected.
3. If pager is on, the number of results is the number of items per page - Works as expected.
4. Test the pager to make sure the items change and match the same order that would occur if you turned the pager off and increased the number of items - Works as expected.
5. Past events option should also work - Works as expected
6. Anonymous users should get cached queries after initial paging. Cache times are the same as before. - Works as expected, newer pages slower than the cached ones.

**Comment by joewhitsitt** [comment]
@makurj the screenshot you included for adding events to a v2 website shows the layout builder interface. v2 editors don't have access to layout builder and certain blocks won't work. Instead v2 users edit the page where nested Paragraphs are located and there is a paragraphs specific bundle for events.

Screen Shot 2022-07-20 at 1 03 57 PM

**Comment by makurj** [comment]
> @makurj the screenshot you included for adding events to a v2 website shows the layout builder interface. v2 editors don't have access to layout builder and certain blocks won't work. Instead v2 users edit the page where nested Paragraphs are located and there is a paragraphs specific bundle for events.

Oh yeah! I'll try that and test.

**Comment by makurj** [comment]
V2 working as expected, except I don't see a pager option. Otherwise, I'd say it's great.

**Comment by joewhitsitt** [comment]
>V2 working as expected, except I don't see a pager option

Sorry, I didn't carry this over from the issue. This PR does not add pagers to v2 events. #worksasdesigned

**Comment by makurj** [comment]
Travis failed, but I can still approve, if you want...?

**Comment by briand44** [comment]
We should probably address https://github.com/uiowa/uiowa/pull/5462#issuecomment-1189192372 before merging.

**Comment by joewhitsitt** [comment]
I made the change to the date ranges.

Sometimes though (no filtering) it doesn't fetch all (I would expect this to go back to 2018 something):
Screen Shot 2022-07-20 at 3 22 48 PM

Other times when filtering, it almost gets everything, but I am not seeing something I expect:
https://content.uiowa.edu/node/8201/edit
Screen Shot 2022-07-20 at 4 50 34 PM
Screen Shot 2022-07-20 at 4 50 14 PM

**Comment by joewhitsitt** [comment]
i'd like to understand these queries more before merge

~~update: i am going to create some dummy events on content.dev to work with~~

**Comment by joewhitsitt** [comment]
I think I found the problem. createPager is expecting the total number of items, not the total number of pages. We can either do fuzzy math on the fly or see about adding a count to the query result to target.

**Comment by joewhitsitt** [comment]
Proposing a one line change to docroot/sites/content.uiowa.edu/modules/custom/content_hub_core/inc/content_hub_core.data_feeds.inc that includes the total_results (defined earlier on to compute total pages)

```
    $output = (object) ['events' => $new_output, 'page' => array('current' => $current_page, 'size' => (int) $items_per_page, 'total' => ceil($total_pages), 'total_results' => (int) $total_results)];
```

uiowa702 branch is `content_hub_api_total_results`

**Review by e-marie-w — APPROVED** [review]
Pager working as expected, only see set number of results per page. Number of total events (to 50) and events themselves match between blocks with pager and blocks without, for future events and past events. And I can see past events going back to 2007, so the extended date range is working too. Awesome job Joe!

**Comment by joewhitsitt** [comment]
Thanks for the review @e-marie-w. Based on that, I am going to merge and deploy the content hub change, notify the events calendar slack and then this can be merged in.

**Comment by joewhitsitt** [comment]
702 with the change for content hub has been deployed

**Comment by joewhitsitt** [comment]
Just did another test without setting the dev endpoint. Looks good to me.

**Pull request merged**
