### PR TITLE
Update drupal/core to 8.9.6 with dependencies.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves security update CI failures. See ca3559eed4ba0681432247c6e830700ca6a30067 for version output.

### Testing
- `composer install`
- ??
- Profit.

https://git.drupalcode.org/project/drupal/-/compare/8.9.3...8.9.6

https://www.drupal.org/project/drupal/releases/8.9.4
https://www.drupal.org/project/drupal/releases/8.9.5
https://www.drupal.org/project/drupal/releases/8.9.6

### CODE REVIEW

**Review by joewhitsitt — APPROVED** [review]
reviewed, not tested beyond my own attempt

**Comment by richardbporter** [comment]
>Paragraphs modal dialogs may not show due to a CSS change in core

Are we worried about that?

**Comment by joewhitsitt** [comment]
i can't think of a paragraph modal dialog beyond a media/entity embed dialog inside of a paragraph...

**Comment by richardbporter** [comment]
That seems to work fine.

**Comment by joewhitsitt** [comment]
Tested paragraphs on v2 default and all seems okay.
blt frontend ran fine too

**Pull request merged**
