### PR TITLE
update entity_usage, remove media deletion restriction

### LINKED ISSUE #7644: Probe - Entity usage seems to still be holding on to media usage
# Problem
Three know situations now where after cleaning up referenced revisions, the media still shows usage to the node(s).

- Setting up ned.uiowa.edu behind authentication and deleting default files
- Education (single file two pages)
- Rhetoric (multiple files one page)

# Steps to reproduce
Try delete files as described by our documentation (https://sitenow.uiowa.edu/documentation/media#delete-media)

# Workaround

I've been pulling the site down locally, finding the corresponding `fid` for each media entity id using the `file_usage` and `file_managed` tables.

Locally, I try using `drush entity:delete media {comma-separated media ids}` and then expecting the files in `file_managed` to make sure their status is set to `0`

# More info

It doesn't seem to show up in find text but I have had some results in finding the media in various tables `paragraph__field_collection_body` like `media/123` but then it is kind of a pain to track back from there.

# Proposed solution

- [ ] Look for upstream issues with entity_usage, linkit_media_library or Drupal 10.2 as this wasn't an issue when we released https://github.com/uiowa/uiowa/pull/7389
- [ ] ?

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/7644

# How to test

- Note that there is no update hook associated with the module upgrade.
- Until #8318 is merged, use sequel ace, or one of the other methods [listed here](https://ddev.readthedocs.io/en/stable/users/usage/database-management/) to monitor the database locally.
- `ddev blt ds --site=sandbox.uiowa.edu`
- Open your database UI and pull up file_usage and file_managed tables.
- Try the media replace functionality (uncheck overwrite original) and take note of the original filename.
- Delete the media item even if it has usage.
- the fid/mid in file_usage associated with the filename in file_managed should disappear and the row in file_managed should change to status = 0. the modified timestamp should update.
- Do your worst to the the node/layout/media/revision workflow. Try creating orphan block entities with media usage. Go to a page with a card image. Change the image on the block. Save the page. Delete all previous revisions of the page. The media usage should still point out a old revision related to block content. Delete the media item despite the warning. 
- the fid/mid in file_usage associated with the filename in file_managed should disappear and the row in file_managed should change to status = 0. the modified timestamp should update.

# Follow-up

Drafted a new version of the docs: https://sitenow.uiowa.edu/node/171/latest. Publish on deployment.

### CODE REVIEW

**Comment by e-marie-w** [comment]
The media replace functionality is not working on images for me. I get the `The image file is invalid or the image type is not allowed. Allowed types: gif, jfif, jpe, jpeg, jpg, png, webp` error message when I try to save. So far I've tried jpeg and png with no success. I can replace files and remote videos just fine. The file_usage and file_managed tables are updating correctly for the pdf files. I will try the images next just without it being replaced.

**Comment by joewhitsitt** [comment]
Hmm. Seems unrelated to the work in this PR, but I am curious if you can provide an example of the media you are replacing and with what you are trying to replace it with.

I have seen the issue with overwrite existing checked, that it is very particular with what you are replacing with. For example, .jpg replacing a .jpeg with overwrite existing has been rejected for me.

**Comment by e-marie-w** [comment]
So I unchecked the 'overwrite original file' as mentioned in the instructions and first tried replacing a .jpg with another .jpg and then a .png. Then I tried the same thing (.jpg and .png replacements) for a .png image and a .jpeg. I might checkout main and play around to see if the same thing happens again. But first I'll approve this since it seems unrelated to the work of this PR and everything else works fine.

**Review by e-marie-w — APPROVED** [review]
Followed instructions, I can now delete media even if usage is listed or if the media remains even after all usage instances of it have been deleted. The file_managed and file_usage tables update as expected. Awesome work!

**Comment by joewhitsitt** [comment]
Alternatively, if you want to try to reproduce the replace issue in PROD we can further confirm it is not an issue with this PR.

**Comment by e-marie-w** [comment]
Okay, I actually can't replicate it in prod, I can replace the files fine there.

**Comment by joewhitsitt** [comment]
I am going to pull down and compare the replace file functionality between this branch and main

**Comment by joewhitsitt** [comment]
I haven't been able to reproduce. Here is what I did.

`git checkout main`
`ddev composer install`
`ddev drush @default.local sql-drop -y && ddev drush @default.local cr && ddev blt ds --site=default && ddev drush @default.local uli`
Added the following file: 
png1
Edited the media entity and selected this other file to replace it with overwrite existing checked:
png2
The image styles/thumbnail were incorrect but that is a known issue. The file when loaded in the preview generated the new styles.
Unchecked overwrite existing and selected this file (jpg):
9bbxiq

I then repeated the same steps with `entity_usage_update`

**Comment by e-marie-w** [comment]
Following those instructions it does actually save when overwrite existing is unchecked. When checked it does save but it doesn't update anywhere - not even when visiting a page using the media item and re-saving/re-adding it, but I'm guessing that's part of the known issue or something funky with my local setup if it works fine for you.

**Comment by joewhitsitt** [comment]
>When checked it does save but it doesn't update anywhere - not even when visiting a page using the media item and re-saving/re-adding it, but I'm guessing that's part of the known issue or something funky with my local setup if it works fine for you.

Well yeah, the caching of meta data is an known issue for overwrite existing and we are waiting for core to provide some kind of refresh metadata in order to properly clear this stuff. https://github.com/uiowa/uiowa/issues/6817

>I get the The image file is invalid or the image type is not allowed. Allowed types: gif, jfif, jpe, jpeg, jpg, png, webp error message when I try to save.

I thought you were continuing to run into this issue.

**Comment by joewhitsitt** [comment]
I went ahead and published the changes to https://sitenow.uiowa.edu/documentation/media since this has been merged and is going to be heading out soon.

**Pull request merged**
