### PR TITLE
i3010 - Drawer menu getting cut off on shorter screen height

### LINKED ISSUE #3010: Drawer menu getting cut off on shorter screen height
# Problem
This issue was reported on the Graduate College site:

Drop Down Menu

As can be seen in the image, the links at the bottom are cut off and inaccessible despite being scrolled all the way down.

# Steps to reproduce
Visit https://grad.uiowa.edu and resize window to similar dimensions as shown in the image above. Click the menu button to open the drawer menu. Click the "Info for" link. Attempt to scroll to and click on "Alumni & Friends."

# Proposed solution
TBD

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3010 

# How to test

1. blt ds --site=grad.uiowa.edu
2. blt frontend
3. Open the menu and expand one of the expandable sections. Then scale the window down as small as possible and make sure you can scroll up and down and that all menu links are visible. Expand children as well to double check.
4. Test in chrome and firefox

### CODE REVIEW

**Comment by dnkemper** [comment]
Thank you so much for all of your help, @bspeare 🥇

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by pyrello** [comment]
I should have mentioned. I just tested this and there were still issues when I was logged out.

**Comment by joewhitsitt** [comment]
issues on uiowa.edu
Screen Shot 2021-02-16 at 3 25 06 PM

**Comment by dnkemper** [comment]
I'm a little confused how scss styling can be applied when logged in but not when logged out. Not sure how to go about fixing this?

**Comment by joewhitsitt** [comment]
might have been a cache issue. i think my uiowa.edu local is working now

uiowa.edu
Screen Shot 2021-02-16 at 3 29 16 PM


grad.uiowa.edu
Screen Shot 2021-02-16 at 3 35 06 PM

**Review by joewhitsitt — APPROVED** [review]
cache rebuild worked for me. @pyrello can you confirm?

**Comment by dnkemper** [comment]
🤞 Thank you so much, @joewhitsitt

**Comment by pyrello** [comment]
I'm still having this issue. `drush cr` does not resolve it for me.

**Review by pyrello — CHANGES_REQUESTED** [review]
I'm still experiencing the issue.

**Comment by bspeare** [comment]
@pyrello can you add a screenshot?

**Comment by dnkemper** [comment]
I've tried and haven't been able to reproduce what @pyrello is seeing. For some reason it still works for me when I'm logged out. Going to wipe out db and triple check just in case.

**Comment by bspeare** [comment]
I was able to reproduce @pyrello's issue using Browserstack using Chrome/Mojave combo.   I'll do some further browser testing.

**Comment by dnkemper** [comment]
OH! Chrome/Catalina. Interesting.

**Comment by pyrello** [comment]
This appears to be working now.

The amount of space at the bottom is different when logged out vs. logged in:

**Logged out**
Screen Shot 2021-02-17 at 8 48 17 AM

**Logged in**
Screen Shot 2021-02-17 at 8 47 37 AM

**Review by pyrello — APPROVED** [review]
Working.

**Pull request merged**
