### PR TITLE
I1922 hide si widget

### LINKED ISSUE #1922: Hide Site Improve widget when editing a layout builder page.
When editing a Layout builder page and pulling in blocks from a side menu, the Site improve widget is by default open and blocks some of your view. This should be collapsed by default when editing a layout page.

### PR DESCRIPTION
**Pull request by GaryRidgway**
This resolves #1922 and should collapse the Site Improve widget when editing the layout of a layout builder page.

To test:
1. Pull down branch and set up a Layout builder site.
2. Go to any layout builder page and edit its layout.
3. Check to make sure the SI widget is collapsed, and that a double click opens it.

### CODE REVIEW

**Comment by richardbporter** [comment]
Found the offending PHPCS line by running `blt phpcs` locally.

One question I have here is if this SI overlay is needed period. I find it annoying on other pages too.

**Comment by richardbporter** [comment]
Ah, I see what it does now. However, I don't see any per-page information when editing a layout. It doesn't seem to know what page it is like it does when just editing a node.

**Comment by joewhitsitt** [comment]
So just to understand the problem, I went to the PROD homepage site. By default, yeah it sticks out, but you can click or drag it close and it remembers with a browser cookie it looks like, so I don't know if additional code is needed here.

Screen Shot 2020-07-17 at 12 18 34 PM

**Comment by richardbporter** [comment]
@bspeare I think you added this to #1778 - any thoughts here? I guess I could go either way. This works as advertised.

**Comment by bspeare** [comment]
I like the idea of having it collapsed because it helps reduce the visual clutter and does not require every editor to know that it will disappear if set on other pages.   If you guys think we should avoid the additional code, I can see it go that way too.  I just want to reduce the visual noise on the layout edit screen.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
