### PR TITLE
Bumped up uids version to 3.1.2

### PR DESCRIPTION
**Pull request by dnkemper**

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Isn't this the same issue we had earlier? https://github.com/uiowa/uiowa/pull/2626/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR938

Did the solution get documented?

**Comment by dnkemper** [comment]
Neat. Yes, it is! The reasoning behind the fail in October was because a release was deleted?

**Comment by dnkemper** [comment]
I'll fix it :)

**Comment by pyrello** [comment]
To be clear, this is my bad. I created a new release for UIDS without following the full release process because I was testing out the fix to the build system. It should be resolved now.

**Review by joewhitsitt — APPROVED** [review]

**Comment by dnkemper** [comment]
Thank you, @joewhitsitt!

**Pull request merged**
