### PR TITLE
update smart_date to 4.1.3

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/7711

# To Test

- It has database updates (expanding db for 2038 problem), but there are no config changes.
- `ddev blt ds --site=its.uiowa.edu`
- Test that `its_core_alert_email_build`, aka a single ITS alert email still outputs the date as expected.
- `ddev mailpit`
- `ddev blt ds --site=grad.uiowa.edu`
- `ddev blt ds --site=now.uiowa.edu`
- Check field_original_publication_date on now.uiowa.edu article and field_thesis_defense_date on grad thesis defense. End dates should be hidden for both through different methods.

## Test bug fix
```
ddev composer install && ddev blt ds --site=its.uiowa.edu && ddev drush @its.local uli /node/add/alert
```
1. Confirm that end date does not display for "Ongoing" on initial page load.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Looks like the latest version caused a bit of a regression from the [last update](https://github.com/uiowa/uiowa/pull/7078#issuecomment-2018532564). @pyrello is this still okay you think or do we need to take steps to address this again?

Screenshot 2024-05-29 at 10 45 06 AM

**Comment by pyrello** [comment]
> Looks like the latest version caused a bit of a regression from the [last update](https://github.com/uiowa/uiowa/pull/7078#issuecomment-2018532564). @pyrello is this still okay you think or do we need to take steps to address this again?
> 
> Screenshot 2024-05-29 at 10 45 06 AM

Since this isn't end-user facing and is more of a bizarre UI for site editors, I think its okay to not worry about this.

**Comment by bspeare** [comment]
Pulling to test

**Comment by bspeare** [comment]
When creating a new alert it looks like we are going from:

Screenshot 2024-06-04 at 1 41 32 PM

to:

Screenshot 2024-06-04 at 1 41 49 PM

This looks like the same thing pointed out in https://github.com/uiowa/uiowa/pull/7731#issuecomment-2137735582.

**Comment by bspeare** [comment]
I've created a bug issue at https://www.drupal.org/project/smart_date/issues/3452796 with a proposed solution that I believe would fix the issue in https://github.com/uiowa/uiowa/pull/7731#issuecomment-2148180020.

**Comment by joewhitsitt** [comment]
Thanks for noticing that and filing that upstream issue. Did you mean to set it back to Active (work to do)?

**Comment by bspeare** [comment]
@joewhitsitt I did not mean to do that.  Changed it back to "needs review" - good eyes!

**Comment by joewhitsitt** [comment]
If you tested it, it could be switched to Reviewed and Tested by the Community

**Comment by joewhitsitt** [comment]
Can confirm the patch in https://github.com/uiowa/uiowa/pull/7731/commits/6aa5a0646b239e6d64ac07e9dc858e25228066d1 gets things back to expected for ITS and Grad

Screenshot 2024-06-06 at 2 36 13 PM
Screenshot 2024-06-06 at 2 38 29 PM

**Review by bspeare — APPROVED** [review]
Approving based on @joewhitsitt and my own testing.

**Pull request merged**
