### PR TITLE
[Card] Added linkit to card field link

### LINKED ISSUE #7228: P2LB link conversions for cards fail to convert WYSIWYG link into a usable field_link
# Problem
In converting https://brand.uiowa.edu/template-library, brand has found that their media links are not being converted into a usable link like `/sites/brand.uiowa.edu/files/2023-05/IOWA-StylizedWordDocument-2023.zip`.  Instead they are getting `/media/121`. 

# Steps to reproduce
Try converting https://brand.uiowa.edu/template-library locally with P2LB. 

# Proposed solution
@pyrello mentioned that https://www.drupal.org/project/linkit/issues/2712951#comment-14961979 can now be used.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7228./

# How to test
- Test with P2LB
```
ddev blt ds --site=brand.uiowa.edu && ddev drush @brand.local uli /node/761/revisions
```

- Revert to the pre-V3 page
- Edit a card paragraph
   - Add an image 
   - Add a title
   - Remove image from WYSIWYG
- Convert the page to V3
  - Verify that the `/media/` url is converted into the card

## Test overall card functionality
```
ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /cards
```
Test out card link functionality with Linkit
Test with `<nolink>`, `<front>`, and any others you can think of

### Styling
- Do we need extra styling here from https://github.com/uiowa/uiowa/pull/6742
### Circle button
- Circle button logic needs to be reworked

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I am curious why we aren't re-surfacing the old PR so that there is more consistency across blocks even if you want to avoid the menu_link_content portion of the PR. Also, is the issue of existing stored values still a concern?

**Comment by bspeare** [comment]
@joewhitsitt I think we still can, I just wanted to see if I could get this working with cards and P2LB.

**Comment by bspeare** [comment]
@joewhitsitt in terms of data loss or existing stored values are you talking about `<nolink> <front> ` usage?

**Comment by joewhitsitt** [comment]
Again, fuzzy on the results last time, but this comment stands out:

> might need to be an update hook with this as linkit modifies the value stored in the db. `<front>` to `\` and `<nolink>` to `route:<nolink>`

The hope is that `nolink` is not used much if at all outside of the menu link content area, but I know that `<front>` is documented in the help text and has been used a lot of demos and folks may have taken note for use in their own sites.

>Enter `<front>` to link to the front page. Enter `<nolink>` to display link text only. Enter `<button>` to display keyboard-accessible link text only.

An audit here as well could help determine if any further action is necessary.

**Comment by bspeare** [comment]
I looked into this a little further and it looks like we can't use Linkit with our cards unless we want to process the url from the "Separate link text and url" formatter so that the url outputs the `/media/1` path as a public file path.

**Comment by bspeare** [comment]
I'll add observations and screenshots here in a details element.

**Comment by bspeare** [comment]
I don't see an immediate path forward for this so I am going to close this pull request.

**Pull request closed without merging**
