### PR TITLE
i924 - SiteNow Training Registration Form

### PR DESCRIPTION
**Pull request by dnkemper**
# Description
SiteNow Training Registration Form

### CODE REVIEW

**Comment by briand44** [comment]
shorten title. Add more text - Please submit form below to ... Inline labels? smaller field sizes? Require all fields or we shouldn't be asking for that info. Change confirmation message to use #926 minus 1 sentence. Additonal text in warning ~once filled form will close, contact us to let us know of interest, automatically close after 16 submissions, site url help text say SiteNow V2 site.

**Comment by joewhitsitt** [comment]
Looks fine to me. Fixed an upper to lowercase typo.

**Comment by briand44** [comment]
A couple more comments on this: I don't want to hold this up but it would be nice if the help text for url field let customers know to include "https://". Also, I didn't notice any text for once the form has reached 16 submissions. I think there should be some text saying that all of the spaces have been filled and if there is interest in additional trainings to contact us (link to contact form).

**Comment by dnkemper** [comment]
@briand44 Since you wanted it to be inserted in a page, I added the page it will be implemented on in slack (https://sitenow.uiowa.edu/sitenow-training) it's currently unpublished where it would mention the occupancy and whatnot.

**Comment by briand44** [comment]
Ok, I think we may want some text that appears once the form has reached 16 submissions. Maybe is just says "All seats have been filled for this training session. The form is now closed." There is configuration for this.

**Comment by briand44** [comment]
Also noticed the confirmation text doesn't appear to be outputting html? Not a deal breaker just an fyi.

**Review by briand44 — APPROVED** [review]

**Pull request merged**
