### PR TITLE
Emergency website cache control

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/8336

# How to test

Using [https://emergency.dev.drupal.uiowa.edu/](https://emergency.dev.drupal.uiowa.edu/api/active) and [https://signage-stage.uiowa.edu/city-iowa-city/downtown-interchange-stop-0001](https://signage-stage.uiowa.edu/city-iowa-city/downtown-interchange-stop-0001) create hawk alerts and observe the behavior. Ideally alerts and replacement alerts should show up in less than or a little over a minute based on the various timers between the two systems. After an alert is marked as complete, it should fall off the sign in an hour. I've made no change to how signage fetches/displays these.

Then you `curl -I` the different endpoints (DEV/PROD), you should see a big difference in varnish cache age.

The hope is that cutting Varnish times lower will prevent signs from fetching stale information.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
So far, compared to PROD, this is limiting the max-age of the endpoint. Because Drupal-Cache is still a HIT, I think I will remove the attempt at gutting of those. If the node_list does trigger, it should clear this under the 30 sec max-age.

https://emergency.dev.drupal.uiowa.edu/api/active

**Comment by joewhitsitt** [comment]
DEV:
```
age: 0
via: varnish
x-cache: MISS
```

PROD:
```
age: 96571
via: varnish
x-cache: HIT
```

**Comment by joewhitsitt** [comment]
signage-stage hawk alert endpoint config has been switched to emergency.dev.drupal.uiowa.edu

Testing:

I opened a sign in an anonymous chrome-based browser and didn't touch it.
Created an alert on emergency.dev.drupal.uiowa.edu and set it to published. Less than a minute later It popped up on the sign without any interaction with the window.
I then went into the alert and marked it complete. This removes it from the endpoint, but I am still seeing the alert on the sign. A new alert created will replace it (less than or around a minute), but completing both alerts will keep the latest one showing for an hour. I _think_ this is working as it was originally designed. I don't love it though.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested with similar results. Let's get it up to prod.

**Pull request merged**
