### PR TITLE
[Facilities] Added coordinators view

### LINKED ISSUE #7361: Theme building coordinator info on building pages
# Story

As a Facilities website owner, I would like the building coordinators that appear on building pages to look similar to the mockup created.

# Additional Info

Mockup - https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup-final-wbanner-image
Existing example - https://www.facilities.uiowa.edu/building/0003

# Proposed solution

- Contact Information headline
- Primary Building Coordinator label
- Output primary building coordinator name as a mailto link.
- Secondary Building Coordinators label
- Output secondary building coordinators names as mailto links
- Don't show if there aren't any

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7361

# How to test

```
ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local fm-buildings && ddev drush @facilities.local uli node/1731/edit
```
- Look through buildings like https://facilities.uiowa.ddev.site/building/0001 and confirm primary and secondary coordinators are listed. 
  - Review other buildings with multiple secondary coordinators. 
- Empty view headers are still showing like on https://facilities.uiowa.ddev.site/building/0005
  - Review the no results settings and see if you can figure out why the view block is still rendering when empty?  https://github.com/uiowa/uiowa/issues/7368#issuecomment-1957044809

### CODE REVIEW

**Comment by GaryRidgway** [comment]
I will pull this to test

**Comment by GaryRidgway** [comment]
>   * Review other buildings with multiple secondary coordinators.
> * Empty view headers are still showing like on https://facilities.uiowa.ddev.site/building/0005

I am seeing a bunch of empty `<div><p></p></div>` pairs that correspond to the displayed fields of the view. 

I thought it could be that there was a space or something added in to the coordinators fields, but when I add a string to the rewrite section of the view it renders, so it is not that.

I am trying to strip things down until i get one of those fields to not render, then build it back up.

**Comment by GaryRidgway** [comment]
We were able to refactor to this because there should never be any alternative coordinators if there is no main coordinator.

**Comment by joewhitsitt** [comment]
We were also reminded that twig_debug locally produces empty divs sometimes

**Review by GaryRidgway — APPROVED** [review]

**Pull request merged**
