### PR TITLE
Card background options, template updates

### LINKED ISSUE #2425: Implement and test card template refactor for event, events, aggregator, articles, people
# Issue

Now that the card option updates from UIDS have been implemented in https://github.com/uiowa/uiowa/issues/2306, additional work is necessary to implement and test these updates with the `v2` and `v3` custom blocks, paragraphs, feeds, and content types that use the card template for their displays. 

## Template updates

- [x] Update event template to implement updated card template.
- [x] Update events template to implement updated card template.
- [x] Update aggregator template to implement updated card template.
- [x] Update people teaser template 
- [x] Update paragraphs card template
- [x] Update articles teaser template

### LINKED ISSUE #2426: Implement card background color options and test card template refactor for a11y
# Issue

We are moving the events and aggregator template to use the updated card template and this issue will need to be completed so that each event and aggregator item on the Admissions website will render without a fixed white background. 

Add color background options for white, black, gray, and gold for the card component and test them with various background combinations. 
- [x] Adjust LBS block background color options for `white`, `black`, `gray`, and `gold` to appear as options within the card component. 
- [x] Update LBS block background color class names, `white` with `bg--light` might be missing: https://github.com/uiowa/uids/blob/i309-event-card-variant/src/components/background/_background-mixins.scss. 
- [x] Add background.css component to `uids.base.libraries.yml`
- [x] Remove specific background color rules from `card.scss` (https://github.com/uiowa/uiowa/blob/feature_card_option_updates/docroot/themes/custom/uids_base/scss/components/card.scss#L105-L123) and `admin.scss`(https://github.com/uiowa/uiowa/blob/feature_card_option_updates/docroot/themes/custom/uids_base/scss/admin.scss#L278-L289). 
- [x] Find/Replace search for class names listed `background-mixins.scss` in `uids_base` to adjust for new background color names. 
- [x] Update hook to set `bg--white` as background color for existing cards?

## Accessibility testing for v3 sites

Once https://github.com/uiowa/uids/issues/400 is ready, proceed with the testing listed below. 

Now that the card no longer has a standard white background color.   We must test all color contrast variations with the card and related templates listed above to make sure they have accessible color contrast. 

### Gold section background

- [x] Gold section background with Black card background
- [x] Gold section background with white card background
- [x] Gold section background with gold card background
- [x] Gold section background with gray card background

### Black section background

- [x] Black section background with Black card background
- [x] Black section background with white card background
- [x] Black section background with gold card background
- [x] Black section background with gray card background

### Gray section background

- [x] Gray section background with Black card background
- [x] Gray section background with white card background
- [x] Gray section background with gold card background
- [x] Gray section background with gray card background

### White section background

- [x] White section background with Black card background
- [x] White section background with white card background
- [x] White section background with gold card background
- [x] White section background with gray card background

### Brain pattern section background

- [x] Brain pattern section background with Black card background
- [x] Brain pattern section background with White card background
- [x] Brain pattern section background with Gray card background
- [x] Brain pattern section background with Gold card background

### Brain pattern gold section background

- [x] Brain pattern gold section background with Black card background
- [x] Brain pattern gold section background with White card background
- [x] Brain pattern gold section background with Gray card background
- [x] Brain pattern gold section background with Gold card background

### Brain pattern black section background

- [x] Brain pattern black section background with Black card background
- [x] Brain pattern black section background with White card background
- [x] Brain pattern black section background with Gray card background
- [x] Brain pattern black section background with Gold card background

### No card background

- [x] Brain pattern black section background with no set card background
- [x] Brain pattern section background with no set card background
- [x] Brain pattern gold section background with no set card background
- [x] Gold section background with no set card background
- [x] Gray section background with no set card background
- [x] White section background with no set card background
- [x] Black section background with no set card background

## Accessibility testing for v2 sites

We might want to continue to keep a sold white background for cards in `v2`.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2425
Resolves #2426 

Adds new bg color options to cards.

# How to test

## Testing the update hook

Sync site and/or import config `drush @site.env cim` or `blt ds --site=sandbox.uiowa.edu`

Existing cards on sites need to be tested that they receive the new defaults. After running the update hook:
- If the existing card had no background set (the standard white background), it should now have `White (default)` set as its background style
- If the existing card had a gray background, it should now have `Gray` set as its background style

## Testing color options for v3

```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
```
Sync site and/or import config `drush @site.env cim` or `blt ds --site=sandbox.uiowa.edu`

```
drush @sandbox.local cr
```
- Test that newly created cards begin with `White (default)` as their bg style option
- Test that upon saving, bg options including `White (default)` and others properly apply and appear upon editing the card
- Test event (v3), events (v3) and aggregator (v3) styles are all correct and use the card template (`card` classes) instead of the old event template (`events-card` classes).

## Testing sandbox pages for v3

- https://sandbox.prod.drupal.uiowa.edu/card-and-event-background-testing
- https://sandbox.prod.drupal.uiowa.edu/cards 
  - In each background color section, adjust the card background color to be `none` `white` `gray` `gold` `black`
  - Verify that color changes in layout builder preview mode and once page is saved. 
- https://sandbox.prod.drupal.uiowa.edu/articles
- https://sandbox.prod.drupal.uiowa.edu/people-directory
- https://sandbox.prod.drupal.uiowa.edu/events-listing
- https://sandbox.prod.drupal.uiowa.edu/event-combinations
- https://sandbox.prod.drupal.uiowa.edu/aggregator-0
- https://sandbox.prod.drupal.uiowa.edu/kitchen-sink
  - Review kitchen sink page color contrast
  - Add `gray` background to each text area section
  - Add `white` background option to each text area

## Testing color options for v2:
- `blt ds --site=hawkeyemarchingband.uiowa.edu`
- Add featured content, articles, events, people paragraph sections. 
  - Test with list, grid, masonry 
  - Test with pager and more button
  - Test with gray, gold, dark, and black background colors.

### CODE REVIEW

**Comment by bspeare** [comment]
@cory-skeers I've looked through this and I'm wondering:

- Can we set an update hook to set all existing cards to have the `White` background option if it hasn't been set to `Gray`?
- Add `White` as the default option for the card background color when creating a new card block?

**Comment by cory-skeers** [comment]
@bspeare That sounds like a good plan to me. Both can be fairly straightforward additions. I can start on those two parts shortly.

**Comment by bspeare** [comment]
## Starting a checklist 
- [ ] `bttn` border fixes on certain backgrounds
- [ ] uiowa.edu event blocks padding/size
- [ ] funky black background text coloring for `event`
Screen Shot 2020-11-05 at 10 04 43 AM
- [ ] Headlines on dark backgrounded sections are not easily visible and/or practically invisible.
Screen Shot 2020-11-05 at 10 06 28 AM
- [ ] Text color on dark background colors are not readable
Screen Shot 2020-11-05 at 10 09 28 AM
- [ ] Brain pattern black has no readable text
Screen Shot 2020-11-05 at 10 32 25 AM

**Comment by GaryRidgway** [comment]
V2 color issues list here 

EVENTS
- [x] All circle borders are Grey, and therefore not correct on:
    ~~- Dark~~
    ~~- Black~~
    ~~- Gold~~
- [x] Text color on Grid is always black, and doesn't match on:
    ~~- Dark~~
    ~~- Black~~
    ~~- Gold~~
- [x] Text color on Masonry is always black, and doesn't match on:
    ~~- Dark~~
    ~~- Black~~
    ~~- Gold~~

ARTICLES
- [x] Link color is always black, and doesn't match on:
    ~~- Dark~~
    ~~- Black~~

PEOPLE
- [x] Link color is always black, and doesn't match on:
    ~~- Dark~~
    ~~- Black~~
- [x] Text color is white on white background for Grid on:
    - Dark
    - Black
- [x] Text color is white on white background for Masonry on:
    - Dark
    - Black

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by GaryRidgway** [comment]
I will test as well, I have some kitchen sink pages ive been using locally

**Review by GaryRidgway — APPROVED** [review]
Ben and I have gone back and forth testing and fixing these a few times for the v2 implementations, and I am happy to say all boxes have been checked!

**Comment by joewhitsitt** [comment]
Disregard that deleted comment. forgot to `cr`

Approved

Tested on sandbox and law

**Comment by joewhitsitt** [comment]
Needs UIDS release before merge

**Pull request merged**
