### PR TITLE
Writing University Serif font additions

### LINKED ISSUE #2807: Switch Writing University website to use serif font by default
# Story

As a Writing University website visitor I want to see pages using a serif font by default because that is my expectation based on my experience with other literary websites.

# Proposed solution

- [x] Add Lora fonts to UIDS.
- [x] Add a theme setting to UIDS Base to allow switching between sans serif and serif fonts defaulted to sans serif.
- [x] Limit access to theme setting to only sites matching site path of `sites/writinguniversity.org`.
- [x] Add logic to `uids_base_preprocess_html` or `uids_base_preprocess_page` to add a `text--serif` class to the `<body>` element.
- [x] Add style definitions to appropriate stylesheets to override font-family for the following elements:
     * Body field
     * Bio field?
     * Text area blocks
- [ ] Test extensively using the Writing University site and the sandbox site.

### PR DESCRIPTION
**Pull request by GaryRidgway**
PR for work on https://github.com/uiowa/uiowa/issues/2807

# To Test
1. Pull this Branch
2. blt frontend
3. Sync either sandbox.uiowa.edu site or writinguniversity.org. I recommend sandbox.uiowa.edu as it has people.
4. You should observe that an update hook ran.
5. uli in to the site and navigate to Appearance > Settings > uids_base
6. In the Font family dropdown, select Serif(Zilla Slab)
7. Observe that there is Zilla Slab font in these Places:
    1. Articles Page Body field and WYSIWYG 
    2. People Page Biography and WYSIWYG
    3. Events Page Description
    4. Page body Field and WYSIWYG
    5. Layout builder text area and WYSIWYG

### CODE REVIEW

**Comment by GaryRidgway** [comment]
I am leaving this in draft state but putting it in review because it is a review needed to make sure that no more functionality is required. If there is some, then it will need to continue development.

**Comment by pyrello** [comment]
Testing this.

**Comment by bspeare** [comment]
@GaryRidgway could you post screenshots of how these changes look in the items described in number 7 of your testing instructions?

**Comment by pyrello** [comment]
@GaryRidgway Nice work on this so far!

@bspeare and I took a look at this and here is our feedback:
* We should exclude cards from the font changes.
* We should include lists.
* It looks like the serif font is going to need to be bumped up in size a little bit so that it doesn't look smaller than the sans-serif font.
* In the theme settings, I think we need to make it more clear how the scope of the change is limited. Right now someone is likely to think that it is going to change all the text on their site.

**Review by pyrello — CHANGES_REQUESTED** [review]
Please see comments just posted.

**Comment by GaryRidgway** [comment]
Awesome comments, thanks guys! I'll get on it!

**Review by GaryRidgway — COMMENTED** [review]
The requested change should be added

**Comment by joewhitsitt** [comment]
taking a look see

**Comment by GaryRidgway** [comment]
My apologies, the instructions are outdated. updating the instructions now

**Comment by joewhitsitt** [comment]
- Even though HR doesn't have uids_base the update hook ran and didn't affect anything.
- Ran correctly for writing university and other sites.
- Is this something webmaster (on writing university) should control?
- Are WYSIWYG headings, lead not in-scope? That will probably lead to a lot of manual class markup overrides.
- I think it is fine for now, but I am worried about the scalability of the limited instances stuff. One more thing to do if we add another content type (e.g. local events), or allow on a custom site later. SiteNow Articles/People header content text areas are not covered by this.

- Lists don't seem to be covered in WYSIWYG. This is probably the biggest issue I see. Sans-serif in WYSIWYG and serif on output (page body).

I think the foundation is good and can be shipped out as-is and is flexible for changes later. 👍

**Comment by pyrello** [comment]
List are definitely intended to be included. I'm not sure about lead text. When @bspeare has a moment to review your comments, I'd like to get his thoughts.

**Comment by bspeare** [comment]
It looks like a few of them are messed up:

Screen Shot 2021-02-24 at 8 30 01 AM

I'd probably keep them styled as they are defined since they are custom styles:

Screen Shot 2021-02-24 at 8 35 12 AM

**Comment by pyrello** [comment]
@bspeare In your last image above, I think the "Light intro" text should be using Zilla.

**Comment by bspeare** [comment]
I think it makes more sense to leave them since they are all custom classes that have to be added to the WYSIWYG.  Also, if we change `lead` to be Zilla, then there's no need to adjust these.

**Comment by bspeare** [comment]
@pyrello Maybe we just add `element--light-intro-serif` so that it can be used for everyone?

**Comment by GaryRidgway** [comment]
I have added styles for `.lead` and added cases to not target the WYSIWYG headings with the serif scss. I have also pre-prepped the SCSS to handle a new custom WYSIWYG heading class, `.element--light-intro-serif`. I do not think this PR needs to have that to ship, but it would be nice. I was unable to complete that today, but seeing as that is not required to merge, i do not think this PR should be held up by it.

**Comment by bspeare** [comment]
Pulling down to test.

**Comment by bspeare** [comment]
Tested all the criteria out locally on Sandbox site and it all works.

**Review by bspeare — APPROVED** [review]
Nice job!

**Review by pyrello — APPROVED** [review]
Approving based on other approvers.

**Pull request merged**
