### PR TITLE
Admissions - Add fields to Areas of Study

### LINKED ISSUE #2741: As a site owner, I can create an Area of Study page that has all of the defined fields
# Story

As a site owner, I can create an Area of Study page that has all of the defined fields

# Proposed solution

- [x] Subtitle - Text (formatted, long, with summary)
- [x] Intro - Text (formatted, long, with summary)
- [x] Why Iowa - Text (formatted, long, with summary)
- [x] Admission Requirements - Text (formatted, long, with summary)
- [x] Create Admission Requirements content type (Title Field and Body - Text (formatted, long, with summary))
- [x] Admission Requirements - reference field to "Admissions Requirements" content type (limit to 3)
- [x] Careers and Outcomes - Text (formatted, long, with summary)
- [x] Student Opportunities - Text (formatted, long, with summary)
- [x] Stories - Multi-value paragraph field with an image field that also accepts remote video: https://github.com/uiowa/uiowa/issues/2724
  - Use same fields and formats as card block 
- [x] Related Links - multi-value link field?
- [x] Program types

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/2741

## To Test

- First sync the default site and enable the Areas of Study feature split. https://default.local.drupal.uiowa.edu/admin/config/development/configuration/config-split
- `drush @default.local cim` to import the AoS config changes.
- The area of study feature should now be tracked in the sitemap and have the revisions limit set to 10.
- Next sync admissions. The AoS should already be turned on and the changes to the default AoS feature split as well as the fields listed in #2741 should all be present but un-styled (exception being the intro field which is using the body field instead but is also un-styled).
- Why Iowa should have a question mark on render but not on the form.
- Admissions' Student profile and admissions requirement content types should also have the sitemap and revisions tweaks.
- Admissions' student profile short blurb field should now be restricted to minimal/plain text.
- For the stories, you should see a card component template be used and a video or image can be added.

### CODE REVIEW

**Comment by richardbporter** [comment]
> The area of study feature should now be tracked in the sitemap and have the revisions limit set to 10.

I'm not seeing it in the sitemap.xml file. Am I missing something?

**Comment by richardbporter** [comment]
Oh duh. Cron. NM.

**Comment by joewhitsitt** [comment]
you took it too literally. i meant, check the content type edit form to see that there were settings set.

**Comment by richardbporter** [comment]
> Why Iowa should have a question mark on render but not on the form.

Should the colon be removed? Or does that fall under unstyled?

image

**Comment by joewhitsitt** [comment]
unstyled

**Comment by joewhitsitt** [comment]
Example of what it will look like: https://admissions.prod.drupal.uiowa.edu/academics/accounting

**Review by richardbporter — APPROVED** [review]
Works as advertised but I've been disconnected from this story for awhile so I'm unsure what kind of ramifications this might have going forward. Oh well: update hooks.

**Comment by joewhitsitt** [comment]
> I've been disconnected from this story for awhile so I'm unsure what kind of ramifications this might have going forward. Oh well: update hooks.

Maybe I should look for more qualified approvals before merging..

**Comment by pyrello** [comment]
When we left off on this previously, I was not 100% sure about the approach to listing degree objectives. That would be my only concern. Otherwise, I think the list that Ben put together for the fields should be good. We may end up making some tweaks to it, but if this meets that list, it is probably good to go for now.

**Comment by joewhitsitt** [comment]
> Works as advertised

>but if this meets that list, it is probably good to go for now

#works4me

**Pull request merged**
