### PR TITLE
Feature: Housing filter fixes

### PR DESCRIPTION
**Pull request by bspeare**
Added no results text, sorting by title, and reducing duplicates for furnishings. 

# How to test

- `ddev blt ds --site=housing.uiowa.edu`
- Go to https://housing.uiowa.ddev.site/residence-halls and verify halls are displayed alphabetically. 
- Verify that you can see no results text and that the view header still displays if there are no results. 
- Try the combinations below and verify that there are not duplicate entries listed in the results. 
- Try to create duplicates with any other searches... 

Screen Shot 2022-07-14 at 9 18 37 AM
Screen Shot 2022-07-14 at 9 47 08 AM

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
In what this PR addresses, it checks out. 

As a user though, I am confused. Looks like the amenities are treated as ORs which is the same as their current site. Air conditioning and market place bring up Parklawn making me think Parklawn has a market place. At the same rate, I could be closer to Hancher and still have a marketplace on site?

**Comment by bspeare** [comment]
Thanks @joewhitsitt.  Should we make some changes based on your feedback?

**Comment by mkyoder** [comment]
All 11 residence hall have air condition, which is accurate. When I did a reset and checked market place for Parklawn, it is not displaying for me. Which is accurate since it does not have a market place in it.
Screen Shot 2022-07-18 at 2 05 31 PM

**Comment by mkyoder** [comment]
But when I did one that had multiple filters checked, it seemed strange.
Screen Shot 2022-07-18 at 2 08 01 PM

**Comment by mkyoder** [comment]
Technically only Burge should fit all of the criteria selected. Mayflower and Parklawn should drop off since they do not have market places. Let me make sure I didn't put market place taxonomy on those pages by accident...

**Comment by mkyoder** [comment]
I checked and didn't place the market place taxonomy on those specific res hall pages...strange.

**Comment by mkyoder** [comment]
I tried one more set with the east side residence halls and market places. There should only be two halls that fit all the criteria selected, Burge and Catlett. The others should drop off since they also do not have market places.
Screen Shot 2022-07-18 at 2 13 13 PM

**Comment by joewhitsitt** [comment]
Based on @mkyoder's experimentation, sounds like ANDs would be a preferred UX for this. @bspeare would you like help with these changes?

Additional context: https://iowaweb.slack.com/archives/C0164FNN1PV/p1658170437294439

**Comment by bspeare** [comment]
@joewhitsitt I can adjust it!

**Comment by joewhitsitt** [comment]
pulling down and taking a look

**Review by joewhitsitt — APPROVED** [review]
Thanks for making these quick adjustments. Noticed east/west work better now too and that I am still getting no result messages and no duplicates.

**Pull request merged**
