### PR TITLE
Prepare codebase for multiple profiles and applications.

### LINKED ISSUE #852: Preparing for combining uiowa and uiowa01 repos
Related PR: #862 

Here is a diff between this project's`blt/blt.yml` file and the one from uiowa/uiowa01:
```diff
diff --git a/blt/blt.yml b/blt/blt.yml
index c1130f28..008df72a 100644
--- a/blt/blt.yml
+++ b/blt/blt.yml
@@ -1,64 +1,55 @@
 project:
-  prefix: uiowa
-  human_name: 'The sitenow platform on the uiowa application.'
+  prefix: UIowa01
+  human_name: 'UIowa 01'
   profile:
-    name: sitenow
-  local:
-    uri: 'localhost:8888'
-cm:
-  core:
-    dirs:
-      sync:
-        path: 'profiles/custom/sitenow/config/sync'
+    name: collegiate
+  local: {  }
 git:
   default_branch: master
   remotes:
-    - 'git@github.com:uiowa/uiowa.git'
+    - 'git@github.com:uiowa/uiowa01.git'
   hooks:
     commit-msg: false
+    pre-commit: false
 deploy:
   tag_source: true
+drupal:
+  db:
+    username: drupal
+    password: drupal
+    host: localhost
 drush:
   aliases:
     ci: self
-  default_alias: self
+  default_alias: '${drush.aliases.local}'
+modules:
+  local:
+    enable: [dblog, devel, seckit, views_ui]
+    uninstall: [acquia_connector, shield]
+  ci:
+    enable: {  }
+    uninstall: [acquia_connector, shield]
+  dev:
+    enable: [acquia_connector, shield]
+    uninstall: {  }
+  test:
+    enable: [acquia_connector, shield]
+    uninstall: [devel, views_ui]
+  prod:
+    enable: [acquia_connector, shield]
+    uninstall: [devel, views_ui]
 disable-targets:
-  drupal:
-    toggle:
-      modules: true
   tests:
+    yaml: { lint: { files: true } }
     behat:
       run: true
     drupal:
       run: true
-    frontend:
-      run: true
-tests:
-  phpunit:
-    - config: '${repo.root}'
 validate:
-  deprecation:
-    modules: true
-    themes: true
+  twig:
+    functions:
+      - drupal_image
+    filters:
+      - image_style
 cloud:
-  appId: 6bcc006f-9a0e-425e-aba0-198585dd2b56
-drupal:
-  db:
-    host: localhost
-    database: null
-    username: root
-    password: null
-sync:
-  commands:
-    - blt:init:settings
-    - drupal:sync:db
-    - drupal:update
-    - sitenow:multisite:noop
-    - sitenow:multisite:noop
-command-hooks:
-  frontend-reqs:
-    dir: ${docroot}
-    command: '. $NVM_DIR/nvm.sh && nvm install && yarn install'
-  frontend-assets:
-    dir: ${docroot}
-    command: '. $NVM_DIR/nvm.sh && nvm use && yarn workspaces run gulp'
+  appId: 21a2a0ab-b4ed-4ecf-8bd4-9266c70f5ef1
```

The most immediately concerning thing that I see is the `cloud.appId` setting. With a hard-coded appId at the root of the project, commands run automatically against a particular AC application. We would need to figure out how to set this as a variable unique to each site. I'm not sure how to do that off the top of my head.

I'm going to work on seeing about which of these values I can sync up in our project so that when I copy the code over it should go more smoothly.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #852.

### CODE REVIEW

**Comment by richardbporter** [comment]
Doesn't look like code pushes (such as this) are triggering Pipelines builds on the uihealthcare01 application.

**Comment by pyrello** [comment]
@richardbporter Would it trigger a build if its just a draft PR?

**Comment by pyrello** [comment]
Also, would it be possible to add me to the application in AC so I can see what you are doing?

**Comment by pyrello** [comment]
I added Drupal VM and settings as well as our test site (so I could see if everything was working). I believe that it is possible for us to allow both Drupal VM and bare machine development using local.blt.yml. When you locally run `blt recipes:drupalvm:init`, one of the things that it does is add an entry to that file:
```
vm:
  enable: true
```

So, the setting is enabled at each local machine anyways. It seems we could just adjust any settings that we needed to for local development to work with the VM in that file, at least until your team was ready to move towards using that as a solution.

**Comment by richardbporter** [comment]
Cool. I think ideally our group would ditch the bare metal approach and just use what Acquia/blt recommends. It was always more of a stop-gap solution since we had trouble with multiple local environment setups. I will give DrupalVM a try soon.

**Comment by richardbporter** [comment]
I think we're waiting for one more provision on master that I will manually update.

**Comment by pyrello** [comment]
Sounds good. Nice work on this!

**Comment by richardbporter** [comment]
Obviously, there are a lot of changes here so I'll try to summarize.

- Removed sitenow-specific root BLT configuration and moved to sites blt.yml files.
- Refactored global.settings.php to only include the minimum code needed for every site, regardless of profile.
- Added includes.settings.php for every sitenow site which in turns includes the sitenow.settings.php file.
- Updated every site to hard-code the database include statement _before_ the BLT include, as outlined in the BLT docs.
- Reorganized BLT commands into a shared 'Uiowa' namespace and cleaned up some Multisite helper methods.
- Created a `uiowa:update` command which is a pared-down version of `blt:update`. This is useful for making dynamic file changes to every site.
- Refactored `sitenow:multisite:create` to allow for the cloud application to be selected.
- Moved sitenow-specific docs to the profile readme.
- Updated filesystem tests to check for new structure.

I tested a `blt dsa` on quite a few sites and all seemed normal. Would love feedback and additional testing. This will require additional testing on dev.

**Comment by pyrello** [comment]
I have tested the `blt dsa` command after setting my local.blt.yml multisites to include default and careers.uiowa.edu. I'm running this via Drupal VM, so I had to adjust some database settings for it to work with the default settings that I have set up for Drupal VM, but it worked for both of those sites.

What are some additional steps I could take to help test this?

**Comment by joewhitsitt** [comment]
> What are some additional steps I could take to help test this?

I'd be interested in knowing if one of our custom sites synced correctly/imported config correctly as it relates to Drupal VM, but that might not be related. `blt ds --site='sitenow.uiowa.edu'`

I am going to try this branch in a bit.

**Comment by pyrello** [comment]
@joewhitsitt To run the above command, do I need to add sitenow.uiowa.edu to my multisites setting?

**Comment by joewhitsitt** [comment]
No, the dsa references the multisites definitions, but a ds can run on any site that exists by passing it with the site argument. the quotes only seem to be needed with the word "site" at the beginning, but that could be an old habit. for example, `blt ds --site=gis.sites.uiowa.edu` should work without quotes.

**Comment by pyrello** [comment]
@joewhitsitt Both versions worked for me (with and without quotes)

**Comment by richardbporter** [comment]
Thanks. I just want to get that ICRU site in this PR and test it on dev. I can handle that.

**Comment by richardbporter** [comment]
Waiting for #913

**Comment by richardbporter** [comment]
In terms of "preparing the codebase", I think this is ready. I deployed the artifact to dev and tested a few sites. There are some quickly needed follow-up tasks though, mostly related to BLT commands and the usage of multiple apps. I can outline those issues.

**Review by pyrello — APPROVED** [review]

**Pull request merged**
