### PR TITLE
Feature: Default icons for person list and pages 

### LINKED ISSUE #3701: As a content editor, I can have a default anonymous image for Person nodes
# Story

As a content editor, I can have a default anonymous image for Person nodes if one is not added.

# Proposed solution

Can we include a default, anonymous, non-identifying, image to use for Person nodes if an editor does not upload one for the node?

I added one temporarily for Computer Science and Physics faculty members, but would prefer to have an automatic default if one is not uploaded and attached to the Person node:

Screen Shot 2021-06-22 at 1 27 37 PM
anonymous_silhouette

### LINKED ISSUE #3726: People list cards are missing `click-target` on card links
# Problem
The entire card for the people list view is missing the `click-target` class because the link is being created through views. 

# Steps to reproduce
Try clicking on the entire people list card https://cs.local.drupal.uiowa.edu/people/adjunct-faculty. 

# Proposed solution
Update view to add `click-target` class.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3726 and resolves https://github.com/uiowa/uiowa/issues/3701. 

- Contains a fix for missing click-target class
- Updates all person lists and full node view to use a default image if no image is selected

# How to test
`yarn workspace uids_base gulp --development`
- As a V2 or V3 site editor I can add a person content type without an image and expect a default icon based image to be used on the node view, people block list view, and the sitenow people page view.   
- As a site editor, I can adjust the image crop and size using the People list block and see the default icon image respond to each setting. 
- As a site editor, I can click on the entire person list card when viewing a page built using the person list block.
- Images should match the screenshots listed on https://github.com/uiowa/uiowa/issues/3701#issuecomment-871722653.

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
Pulling for testing.

**Comment by mark-bennett-uiowa** [comment]
@bspeare This looks good. Click effect seems to work properly on the entire card in both the Sitenow People list and the manually created People view blocks (e.g. Faculty). Default image shows up "properly" on lists and individual profiles. You mentioned the styling issue, so it sounds like you are aware of it. Great work as always, thanks so much!!
Screen Shot 2021-06-30 at 10 12 35 AM
Screen Shot 2021-06-30 at 10 12 43 AM

**Comment by mark-bennett-uiowa** [comment]
Pulling down for testing.

**Review by mark-bennett-uiowa — APPROVED** [review]
Tested with all sizes and shapes of images in People lists. Didn't notice any issues at all. This looks great. Approved.

**Comment by mjoneill** [comment]
From planning discussion:

Comms plan for site owners foreshadowing the fact that suddenly images are going to start appearing on people that might currently NOT have them.

Sitenow announcements list/campaign/population.  

For partners that are trying to intentionally NOT use images in their lists, there's a list block option to "remove photos".

**Comment by joewhitsitt** [comment]
We can add this to the monthly article to send out in the same email. https://github.com/uiowa/uiowa/issues/3608

**Review by mark-bennett-uiowa — APPROVED** [review]
New changes work properly from the testing I was able to do. I do have some concern with how low in the circle the image is though. See the difference in the three shapes:
Screen Shot 2021-07-08 at 9 39 02 AM
Screen Shot 2021-07-08 at 9 42 01 AM
Screen Shot 2021-07-08 at 9 42 17 AM

The square and rectangle look perfect, but the circle just looks too low. My two cents.

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
functionally works as expected. test on v2/v3 sites. i am satisfied with the image/placement but if there are concerns, I think further design review could be follow-up work. Might be hard to satisfy based on all of the different view mode options.

**Comment by joewhitsitt** [comment]
no longer blocked. communication about the change was sent out

**Comment by bspeare** [comment]
@mark-bennett-uiowa I imagine as we get more eyes on this within the platform and with https://profiles-test.uiowa.edu/ there will be future design tweaks.

**Pull request merged**
