### PR TITLE
Feature: views margin and local tasks menu adjustments

### LINKED ISSUE #2706: Change or re-scope default margins for views-element-container
# Problem
We are setting a global top margin for all views with the class `views-element-container` that is causing issues when using views within layout builder layouts. 

# Steps to reproduce
The extra space can be seen between the a-z links and page title on https://uiowa.edu/a-z. 

# Proposed solution

- Adjust scope of rule to only apply if body contains `layout-builder-disabled` class. 
- Use and expand the `block-margin` class https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L239-L257.

### LINKED ISSUE #4121: Local tasks underline renders on pages without edit tabs
# Problem 

Local tasks underline renders on pages without edit tabs

Screen Shot 2021-09-14 at 10 00 37 AM

# Proposed Solution

Adjust border to just appear on `.tabs li` so that the edit tab underline will not appear on pages without edit tabs. 

**Before**

Screen Shot 2021-09-14 at 10 02 19 AM

**After**

Screen Shot 2021-09-14 at 10 02 51 AM

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/2706.
Resolves https://github.com/uiowa/uiowa/issues/4121. 

When we first built https://uiowa.edu/a-z, we added some top margin for the view via https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/global.scss#L433-L446.   As a result, we had to override that margin for a lot of views.   This pr adds the margin class that we use for layout builder to views that need extra spacing at the top of each view.    For taxonomy, people, and articles views this margin has been added in through the existing component css file for each. 

# How to test

## Views updates

Review views code updates and verify that a `block-margin__top--extra` class has been added to these views:

```
config/default/views.view.aggregator_sources.yml
config/features/thesis_defense/views.view.thesis_defenses.yml
config/sites/admissions.uiowa.edu/views.view.areas_of_study.yml 
config/sites/admissions.uiowa.edu/views.view.events.yml
config/sites/brand.uiowa.edu/views.view.lockups.yml
config/sites/grad.uiowa.edu/views.view.srop_mentors.yml
config/sites/grad.uiowa.edu/views.view.srop_scholars.yml 
config/sites/policy.clas.uiowa.edu/views.view.book_a_z_list.yml 
config/sites/sppa.uiowa.edu/views.view.opportunities.yml 
config/sites/uiowa.edu/views.view.a_z_list.yml
```

Possibly scan https://github.com/uiowa/uiowa/find/main for views I may have missed. 

- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/icsa.uiowa.edu/views.view.reports.yml (/reports)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/icsa.uiowa.edu/views.view.projects.yml (/projects)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_toc.yml (/table-of-contents)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/ighn.international.uiowa.edu/views.view.ighn_person_view.yml (/ighn-person)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/immuno.grad.uiowa.edu/views.view.person_custom.yml (/people/faculty)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/genetics.grad.uiowa.edu/views.view.person_custom.yml (/people/faculty)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_search.yml (/search)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/admissions.uiowa.edu/views.view.student_profiles.yml (/student-profiles)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/immuno.grad.uiowa.edu/views.view.research_areas.yml (/people/research)
- [x] https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_whats_new.yml (/whats-new)

## Local tasks bug

```
blt ds --site=grad.uiowa.edu
yarn workspace uids_base build
```

Verify that when logged in, view pages do not have an underline under the page title like on https://grad.local.drupal.uiowa.edu/dei/srop/mentors.  
Verify that pages with local task buttons do have a solid gray underline under the buttons: https://grad.local.drupal.uiowa.edu/programs/graduate-certificates
Verify that there is extra space around the local tasks edit menu on pages not using layout builder: https://grad.local.drupal.uiowa.edu/academics/thesis-defenses/2021-11-10/larissa-jordan
See https://github.com/uiowa/uiowa/issues/4121 for screenshots.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
What about:
- https://github.com/uiowa/uiowa/blob/main/config/sites/icsa.uiowa.edu/views.view.reports.yml (/reports)
- https://github.com/uiowa/uiowa/blob/main/config/sites/icsa.uiowa.edu/views.view.projects.yml (/projects)
- https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_toc.yml (/table-of-contents)
- https://github.com/uiowa/uiowa/blob/main/config/sites/ighn.international.uiowa.edu/views.view.ighn_person_view.yml (/ighn-person)
- https://github.com/uiowa/uiowa/blob/main/config/sites/immuno.grad.uiowa.edu/views.view.person_custom.yml (/people/faculty)
- https://github.com/uiowa/uiowa/blob/main/config/sites/genetics.grad.uiowa.edu/views.view.person_custom.yml (/people/faculty)
- https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_search.yml (/search)
- https://github.com/uiowa/uiowa/blob/main/config/sites/admissions.uiowa.edu/views.view.student_profiles.yml (/student-profiles)
- https://github.com/uiowa/uiowa/blob/main/config/sites/immuno.grad.uiowa.edu/views.view.research_areas.yml (/people/research)
- https://github.com/uiowa/uiowa/blob/main/config/sites/policy.clas.uiowa.edu/views.view.book_whats_new.yml (/whats-new)

Also would the term views on admissions (academic groups, colleges be in-scope?)

Otherwise, the changes so far in this PR look good.

**Comment by bspeare** [comment]
@joewhitsitt I'll double check those.   I did check half of those so thank you for bringing the additional ones to my attention.   Admissions term pages are covered.

**Comment by bspeare** [comment]
@joewhitsitt I checked that list and pushed up the missing ones if you can glance at this one more time.

**Review by joewhitsitt — APPROVED** [review]

**Comment by bspeare** [comment]
Thanks! @joewhitsitt

**Pull request merged**
