### PR TITLE
i3348 APR style adjustments

### LINKED ISSUE #3348: Adjust APR styles
> Increase the font size of the Rank/Title displayed under the photo
> List each website on a separate line. They currently run together in some cases. (https://pharmacy.prod.drupal.uiowa.edu/people/guohua-an)
> List the office phone number below the Primary Office and with a heading of “Phone”. In some cases the phone number is listed with the address. (https://pharmacy.prod.drupal.uiowa.edu/people/vern-k-duba)
>  
> Also, I noticed on the main directory page https://pharmacy.prod.drupal.uiowa.edu/people, the rank/title isn’t always listed below the name.  Is there a way to ensure it gets listed below the name?

### PR DESCRIPTION
**Pull request by GaryRidgway**
Resolves #3348 

- [x] Increase the font size of the Rank/Title displayed under the photo
- [x] List each website on a separate line. They currently run together in some cases. (https://pharmacy.prod.drupal.uiowa.edu/people/guohua-an)
- [x] List the office phone number below the Primary Office and with a heading of “Phone”. In some cases the phone number is listed with the address. (https://pharmacy.prod.drupal.uiowa.edu/people/vern-k-duba)
- [x] Also, I noticed on the main directory page https://pharmacy.prod.drupal.uiowa.edu/people, the rank/title isn’t always listed below the name. Is there a way to ensure it gets listed below the name?
- [x] Remove back button, as it does not function as intended

# How to test
____
1. Sync `pharmacy.uiowa.edu`.
1. Check that the title under the profile picture matches the size of the other headings underneath it.
2. All websites for a user should be on a separate line. (https://pharmacy.local.drupal.uiowa.edu/people/guohua-an)
3. Phone numbers should now have the title "Phone". (https://pharmacy.local.drupal.uiowa.edu/people/vern-k-duba)
4. The title of a person should now always be underneath their name in the listing view. (https://pharmacy.local.drupal.uiowa.edu/people)
5. The back button should no longer show on individual person pages.

### CODE REVIEW

**Comment by richardbporter** [comment]
This is looking good. I noticed one profile where the phone doesn't look quite right though:
image

I'm not sure what the deal is with that profile. Are you seeing that?

**Comment by GaryRidgway** [comment]
Ah good catch, i think there is something wrong with the way the address or the phone container is styled. I'll take a look

**Comment by GaryRidgway** [comment]
@richardbporter this should be fixed now

**Review by richardbporter — APPROVED** [review]
Yes, that did it. Thanks.

**Pull request merged**
