### PR TITLE
Untangling Events and Admissions config

### PR DESCRIPTION
**Pull request by pyrello**
This is hopefully the first step in undoing some of the fragmentation that had occurred between the Admissions site split and the event feature.

1. Removes the full split of `views.view.events` from admissions.
2. Removes layout split from admissions.
3. Auto-submit is turned on for the default /events view.
4. The subevents view on the full node page has the "No results" removed so that nothing will appear if there are no subevents. 
5. The /events/calendar view is disabled for the feature split but turned on for admissions only. 
6. The local tasks css was moved to a separate library and is loaded separate for the local tasks block so that it can be used for the "Tabs" that are unstyled at https://admissions.uiowa.edu/events. 

# How to test

`ddev blt frontend`

```
ddev blt ds && ddev drush @default.local config-split:activate event -y && ddev drush @default.local cim -y && ddev drush @default.local uli events
```
- Check default + event feature
```
ddev blt ds --site admissions.uiowa.edu && ddev drush @admissions.local uli events
```
- Check Admissions and compare local /events page with prod /events page. 
```
ddev blt ds --site iowasummerwritingfestival.uiowa.edu && ddev drush @iowasummerwritingfestival.local uli events
```
- Check ISWF and compare local /events page with prod /events page. 
```
ddev blt ds --site oniowa.uiowa.edu && ddev drush @oniowa.local uli events
```
- Check OnIowa! and compare local /events page with prod /events page. 

### Check Admissions
```
ddev blt ds --site admissions.uiowa.edu && ddev drush @admissions.local uli areas-of-study
```

- Test desktop/mobile breakpoints
- Test search and reset buttons
- Compare https://admissions.uiowa.ddev.site/areas-of-study against https://admissions.uiowa.edu/areas-of-study
- Compare https://admissions.uiowa.ddev.site/events against https://admissions.uiowa.edu/events (Upcoming and Calendar tabs are now styled for anonymous users)

### Check Housing
```
ddev blt ds --site housing.uiowa.edu && ddev drush @housing.local uli residence-halls
```
- Test desktop/mobile breakpoints
- Test search and reset buttons
- Compare https://housing.uiowa.ddev.site/residence-halls against https://housing.uiowa.edu/residence-halls

### CODE REVIEW

**Comment by pyrello** [comment]
As discussed in Slack, the current state of this is that it adds a "Search" box to the Admissions `/events` page in addition to the event category drop-down field. Not sure if this would be an acceptable interim update or not, but it will probably need to be styled to be on two separate lines instead of one.

Probably we want to check in with Admissions about this before we do the work to style the fields.

**Comment by bspeare** [comment]
If you run `blt frontend` this is what the updated page looks like:

Screenshot 2023-06-08 at 12 19 46 PM

**Comment by bspeare** [comment]
I reached out to Scott and he said he was ok with adding the search field to https://github.com/uiowa/uiowa/pull/6502#issuecomment-1583056629.

**Comment by cory-skeers** [comment]
A couple notes on differences; not sure that I have a preference on whether what is currently on prod remains or these slight changes take place, but wanted to note them:

The collapse to single column on https://admissions.uiowa.ddev.site/areas-of-study (and /events) happens sooner (@ 980 vs @ 768), and the submit buttons are black instead of prod's gold.

For housing, the collapse to single column is the same difference as admissions.
The search/reset buttons are same line and differ in color rather than stacked and same color (I prefer this change, especially the color difference).

**Comment by bspeare** [comment]
Thanks for the notes @cory-skeers, I've update the breakpoints so they remain the same.   For the button colors, I think removing the customization that we did there will make our buttons more consistent and easier to manage.

**Comment by cory-skeers** [comment]
@bspeare I pulled the latest change, and I'm not sure it's working quite right. At the full container size, the grid gap is still at 1.5 (I think it should be 3 at that point), and the collapse to stacked is still happening at the 980.

I wouldn't put it past my local having something weird.

**Comment by bspeare** [comment]
I was able to get these errors to disappear after running xdebug on ViewsHandlerManager.php:82 which led me to the sort options in the admissions config patch.   I have updated the sort options in https://github.com/uiowa/uiowa/pull/6502/commits/7a8fed7d5f20a2d27d327a35123870e20c9d7d75 and the errors are gone. 

```
 [warning] Undefined array key "id" DisplayPluginBase.php:863
 [warning] Undefined array key "table" ViewsHandlerManager.php:82
 [warning] Undefined array key "field" ViewsHandlerManager.php:83
 [warning] Undefined array key "id" DisplayPluginBase.php:863
 [warning] Undefined array key "table" ViewsHandlerManager.php:82
 [warning] Undefined array key "field" ViewsHandlerManager.php:83
 [warning] Undefined array key "id" DisplayPluginBase.php:863
 [warning] Undefined array key "table" ViewsHandlerManager.php:82
 [warning] Undefined array key "field" ViewsHandlerManager.php:83
```

**Comment by bspeare** [comment]
@cory-skeers thanks for double checking that, now it should be fixed!

**Review by cory-skeers — APPROVED** [review]
Latest updates look good--thanks @bspeare!

With that and the previous testing, I think this is good to go.

**Comment by pyrello** [comment]
Thanks for testing, @cory-skeers!

**Pull request merged**
