### PR TITLE
LB Collections improvements.

### LINKED ISSUE #2104: LB Collection enhancements
# Problem
After the recent update to require at least one collection item, the collection now shows the add collection item form for the first item by default. This is a little confusing because it seems like the fields are related to the whole collection rather than the first item.
Screen Shot 2020-08-28 at 12 57 57 PM

# Proposed solution
Add some kind of label, outline, or other indicator to let the user know that the form items are for a nested item. This could be similar to how the collection items display after they are created:
Screen Shot 2020-08-28 at 1 12 08 PM

Additionally, I think a little bit of tweaking might be in order for the post-save view of the collection items.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2104 

UX improvements/updates for collections and slider.

### Existing content
Either sync a site with existing collections and sliders, or sync on main, create collections and sliders, and then checkout this branch, pull, `composer install`, and `drush @sitealias cim`
`blt frontend`

Check that the labels are updated correctly ("Collection Items" in the form is now "Items", and "Collection Body" simply "Body.")
Check that, when editing a current collection or after saving a collection item, the form displays the item headline and (truncated) body in the "Items" field list.
Check that, when adding a new collection, it is clear the "headline" and "body" field are for a new accordion/list item, and not the collection itself.
Try adding, removing, rearranging, and editing/collapsing sliders and collections, and check that the functionality works and is clear.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I can reproduce the SQL error.

Steps to reproduce:

- Checkout main and pull a v3 or collegiate site down
- Create a collection on the site.
- Checkout this branch and `cim cr`
- Edit the existing collection. Update block and then try to save Layout.

```Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'langcode' cannot be null: UPDATE {paragraphs_item} SET revision_id=:db_update_placeholder_0, type=:db_update_placeholder_1, uuid=:db_update_placeholder_2, langcode=:db_update_placeholder_3 WHERE id = :db_condition_placeholder_0; Array ( [:db_update_placeholder_0] => [:db_update_placeholder_1] => uiowa_collection_item [:db_update_placeholder_2] => 6faba44b-f889-4cbe-80a6-e5beff010291 [:db_update_placeholder_3] => [:db_condition_placeholder_0] => 1 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 846 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
Drupal\Core\Database\Statement->execute(Array, Array) (Line: 634)
Drupal\Core\Database\Connection->query('UPDATE {paragraphs_item} SET revision_id=:db_update_placeholder_0, type=:db_update_placeholder_1, uuid=:db_update_placeholder_2, langcode=:db_update_placeholder_3
WHERE id = :db_condition_placeholder_0', Array, Array) (Line: 357)
Drupal\Core\Database\Driver\mysql\Connection->query('UPDATE {paragraphs_item} SET revision_id=:db_update_placeholder_0, type=:db_update_placeholder_1, uuid=:db_update_placeholder_2, langcode=:db_update_placeholder_3
WHERE id = :db_condition_placeholder_0', Array, Array) (Line: 148)
Drupal\Core\Database\Query\Update->execute() (Line: 941)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->doSaveFieldItems(Object) (Line: 665)
Drupal\Core\Entity\ContentEntityStorageBase->doSave('1', Object) (Line: 457)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 837)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object) (Line: 395)
Drupal\Core\Entity\EntityBase->save() (Line: 303)
Drupal\entity_reference_revisions\Plugin\Field\FieldType\EntityReferenceRevisionsItem->preSave() (Line: 233)
Drupal\Core\Field\FieldItemList->delegateMethod('preSave') (Line: 191)
Drupal\Core\Field\FieldItemList->preSave() (Line: 881)
Drupal\Core\Entity\ContentEntityStorageBase->invokeFieldMethod('preSave', Object) (Line: 831)
Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('presave', Object) (Line: 500)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 700)
Drupal\Core\Entity\ContentEntityStorageBase->doPreSave(Object) (Line: 454)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 837)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object) (Line: 395)
Drupal\Core\Entity\EntityBase->save() (Line: 294)
Drupal\layout_builder\Plugin\Block\InlineBlock->saveBlockContent(1, ) (Line: 277)
Drupal\layout_builder\InlineBlockEntityOperations->saveInlineBlockComponent(Object, Object, 1, ) (Line: 193)
Drupal\layout_builder\InlineBlockEntityOperations->handlePreSave(Object) (Line: 206)
layout_builder_entity_presave(Object)
call_user_func_array('layout_builder_entity_presave', Array) (Line: 403)
Drupal\Core\Extension\ModuleHandler->invokeAll('entity_presave', Array) (Line: 206)
Drupal\Core\Entity\EntityStorageBase->invokeHook('presave', Object) (Line: 843)
Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('presave', Object) (Line: 500)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 700)
Drupal\Core\Entity\ContentEntityStorageBase->doPreSave(Object) (Line: 454)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 837)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object) (Line: 395)
Drupal\Core\Entity\EntityBase->save() (Line: 328)
Drupal\Core\Entity\EntityForm->save(Array, Object) (Line: 177)
Drupal\layout_builder\Form\OverridesEntityForm->save(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 592)
Drupal\Core\Form\FormBuilder->processForm('node_page_layout_builder_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object) (Line: 39)
Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
The website encountered an unexpected error. Please try again later.```

**Comment by cory-skeers** [comment]
Dang--I'll take a look.

Thanks @dnkemper and @joewhitsitt!

**Comment by joewhitsitt** [comment]
Whew, Danielle and I weren't crazy: https://github.com/uiowa/uiowa/pull/2112/commits/585f2fd7ac936ed899af0d17f9937e881c185fce

**Comment by cory-skeers** [comment]
Some noodle code, but should be stable now with the patch.

@pyrello would love to get your input on this at some point, see if it's in line with what you were thinking originally. Also might have some overlap with the slider, since this PR changes collections to use paragraphs widget, where the slider is using (I think?) IEF. Don't think that's a huge problem being different, but creates some styling differences in otherwise similar forms.

**Comment by pyrello** [comment]
I like these changes.

@cory-skeers To be clear, you have not made any changes to slider as part of this and you were want to see if I wanted to make similar updates to that component?

**Comment by cory-skeers** [comment]
@pyrello Right--I thought it might be good to get both using the same widget/styling, but haven't made any changes to the slider yet.

**Comment by pyrello** [comment]
@cory-skeers I am cool with making those changes. I am not going to be able to jump into this right away, so if you want to make those updates, please feel free.

**Comment by joewhitsitt** [comment]
Pulling down

**Review by joewhitsitt — APPROVED** [review]
Tested on a new install/new content, and an existing site with existing IEF versions. The transition from IEF with existing content worked.

Can we autocollapse the slide/collection paragraph items? similar to v2? Everything is squished in the settings tray and there are a lot of vertical space used when an item is used.

**Comment by cory-skeers** [comment]
> Can we autocollapse the slide/collection paragraph items? similar to v2? Everything is squished in the settings tray and there are a lot of vertical space used when an item is used.

Yes! Updated for both, and it's a solid improvement especially for the slider.

**Pull request merged**
