### PR TITLE
Switch to symfony_mailer

### LINKED ISSUE #4623: Replace swiftmailer with symfony_mailer
https://www.drupal.org/project/swiftmailer

>Warning: the swiftmailer library is no longer maintained and so this module is obsolete. It has not yet been marked unsupported, but that could change at any time due to discovery of a security bug or on advice of the Drupal Security Team.

https://www.drupal.org/project/symfony_mailer

## Proposed Solution

Uninstall the Swift Mailer module.
Uninstall the Mail System module.
Add the Symfony Mailer module (using Composer).
Install the Symfony Mailer and Symfony Mailer Back-compatibility modules to the default split. Add local env config for DDEV SMTP.
Re-configure, update brand site split and export config similar to how it was before
Try testing the lockup approval email and the local digest email with DDEV's mailhog. Also test that platform email still sets the correct header and adjusts the from address if not a uiowa.edu domain

## Follow-up slice:

Remove Swift Mailer and Mail System composer dependencies if no longer in use.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/4623

This PR moves HTML email support from using SwiftMailer (deprecated) just on brand.uiowa.edu to adding it to the default with Symfony Mailer. It also includes necessary local config for use with DDEV Mailhog.

# To Test
```
ddev composer install
```
- Review code changes

## New site
```
ddev blt di --site=default && ddev drush @default.local uli admin/config/system/mailer/test
```
Send yourself a test email. Regardless of the email address you enter it should instead end up here: https://uiowa.ddev.site:8026

Try changing the site email to a non-uiowa.edu address. It should get the sitenow-no-reply treatment.

## Brand
```
git checkout main \
&& git pull \
&& ddev composer install \
&& ddev drush @brand.local cr \
&& ddev blt ds --site brand.uiowa.edu \
&& git checkout symfony_mailer \
&& git pull \
&& ddev composer install \
&& ddev drush @brand.local updb -y \
&& ddev drush @brand.local cim -y \
&& ddev drush @brand.local cim -y
```
- Trigger digest email after creating a lockup for review
- Approve the lockup which should trigger another email. This one should contain HTML (spacing, links)

# Follow-up

Remove swiftmailer and mailsystem from composer.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
This ended up being more complicated than we wanted to bite off for https://github.com/uiowa/uiowa/issues/6381. Keeping around for more discovery as we will eventually have to switch off swiftmailer

**Comment by pyrello** [comment]
> Trigger digest email after creating a lockup for review

@joewhitsitt Is the process obvious? Or will it require more context?

**Comment by joewhitsitt** [comment]
Yeah sorry, you can manually trigger it with drush `brand_core:lockup-digest`

otherwise it runs at 7 am in PROD

**Comment by joewhitsitt** [comment]
Note for testing: https://sandbox.prod.drupal.uiowa.edu/form/joe-test has fancy html/css and is probably worth triggering

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
>The service "brand_core.commands" has a dependency on a non-existent service "email_factory".

Do we need to add an update hook to turn the module on right away?

Update: The error occurs before the update hooks are called... 😢

**Comment by pyrello** [comment]
> > The service "brand_core.commands" has a dependency on a non-existent service "email_factory".
> 
> Do we need to add an update hook to turn the module on right away?
> 
> Update: The error occurs before the update hooks are called... 😢

The above is an error message you are seeing? At what step is it happening?

**Comment by joewhitsitt** [comment]
On a `ds`, right after the database sync/cache rebuild.

On a `main` sync first, during the manual updb or trying to enable the module beforehand I get the following:

```
TypeError: Drupal\brand_core\Commands\BrandCoreCommands::__construct(): Argument #3 ($emailFactory) must be of type Drupal\symfony_mailer\EmailFactoryInterface, Drupal\mailsystem\MailsystemManager given, called in /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 in Drupal\brand_core\Commands\BrandCoreCommands->__construct() (line 36 of /var/www/html/docroot/sites/brand.uiowa.edu/modules/brand_core/src/Commands/BrandCoreCommands.php) #0 /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drupal\brand_core\Commands\BrandCoreCommands->__construct(Object(Drupal\Core\Session\AccountSwitcher), Object(Drupal\Core\Datetime\DateFormatter), Object(Drupal\mailsystem\MailsystemManager), Object(Drupal\Core\Config\ConfigFactory))
```

**Comment by pyrello** [comment]
Going to take a look.

**Comment by pyrello** [comment]
Fixing merge conflicts.

**Comment by joewhitsitt** [comment]
i wonder if we need to make symfony_mailer module available in PROD first and enable it for brand before rolling the rest of this out before the next digest email (also ask to hold on approval emails)

seems like any drush operation is triggering the lookup of that command and checking dependencies

**Comment by joewhitsitt** [comment]
Fudge. Can't approve as I was PR author. ✅ approved. Thanks for taking this on @pyrello . Everything seems to checkout. No small thing though!

The digest looks a lot better. If it is sent/received as plain text i think it is fine. if it is sent as html, i think the login url is no longer linked compared to the example Sondra sent. I'd be fine with waiting and seeing.

Screenshot 2023-10-16 at 11 58 04 AM
Screenshot 2023-10-16 at 11 58 10 AM

**Review by pyrello — APPROVED** [review]
Approving based on @joewhitsitt's testing and approval.

**Pull request merged**
