### PR TITLE
[ ITS ] fix funky config

### LINKED ISSUE #8241: [ITS] Anchor IDs in headings on service pages
# Story
As an ITS web editor, I want anchors/id’s in the headings for the views blocks (e.g., “Alerts” and “Support and Training”) on service pages so that I can send users directly to these portions of the pages

# Proposed solution
Edit the config on the blocks and add IDs they can use.

### LINKED ISSUE #8272: [ ITS ] Fix broken config.
As seen [in this PR](https://github.com/uiowa/uiowa/pull/8261) there is some very wonky stuff going on with config on ITS right now.

- Config cannot be exported with a config split export command because of incorrect permissions listed in the help desk user role.
- There seems to be some odd moderation state stuff going on

What I did was delete the errant entries from the help desk user config file, import and then try and make my changes, but after that exporting also brought forth the other observed config changes.

Smoothing this out would be nice so that future devs don't have to know how to get around these issues.

### PR DESCRIPTION
**Pull request by GaryRidgway**
closes #8272
closes #8241

## To test
1. Sync down the site
2. Export conig and observe that it does not error out and fail. It may warn you, but that doesn't count!
3. check some service pages to see that they now have id's that allow you to make anchors to them
    i. (eg. #alerts, #support-training, #news)

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I don't think we want this. https://github.com/uiowa/uiowa/pull/8281/commits/8a3846e8dee993350cbe4ba48e55e6b002b54fc6

We are purposely hiding title on alerts for ITS as it is crafted by the field values.

This is one of the things that constantly flips back and we have to fix it.
https://github.com/uiowa/uiowa/pull/8009/commits/3581419e781c404e6cd9e073cbd1cc58c54be549

**Review by bspeare — DISMISSED** [review]
Site sync and export worked without anything funky.  IDs were there too.

**Comment by bspeare** [comment]
Exporting the site I have these changes modified:
```
modified:   config/sites/its.uiowa.edu/config_split.patch.core.entity_form_display.node.alert.default.yml
modified:   config/sites/its.uiowa.edu/config_split.patch.core.entity_form_display.node.article.default.yml
modified:   config/sites/its.uiowa.edu/config_split.patch.core.entity_form_display.node.article.minimal.yml
```

**Comment by GaryRidgway** [comment]
@bspeare After opening the alert content type and saving the form display, the only thing that exports after that is the title change, which we didn't want to keep. If that is the case, would that all be fixed once this update goes out? 


I'm not sure how to convince the config to ignore the title, that part irks me. >:(

**Review by bspeare — APPROVED** [review]
Works mostly as described! Thanks for adding gotchas to https://github.com/uiowa/uiowa/issues/8137.

**Pull request merged**
