### PR TITLE
adding date updated to PDFs

### LINKED ISSUE #4990: Add date in footer text on Admissions Areas of Study pdf's
As an Admissions site owner, I would like the last updated date to appear on an Areas of Study PDF so that printed copies at the Visitor Center can be differentiated between what is recent and what is outdated.

### PR DESCRIPTION
**Pull request by GaryRidgway**
Adding date updated to the PDFs of areas of study
closes #4990 

## To test

sync down admissions
go to /kiosk
print a pdf page
check if it has a last updated at the bottom
make sure that is that same date as it is on the edit page for that area of study

### CODE REVIEW

**Comment by bspeare** [comment]
I updated the position of the date so that it doesn't collide with the main footer information. 

Before:

Screen Shot 2022-03-29 at 8 34 24 AM


After:

Screen Shot 2022-03-29 at 8 33 52 AM

**Comment by GaryRidgway** [comment]
sweet! Thanks ben!

**Comment by richardbporter** [comment]
I will test this.

**Review by richardbporter — APPROVED** [review]
Looks good.

**Pull request merged**
