### PR TITLE
Hotfix config mismatches

### LINKED ISSUE #3293: Fix config mismatches after 3.15.5
New token display mismatches and others:

hr.uiowa.edu:
```
core.entity_view_display.node.article.token                                             
core.entity_view_display.node.page.token 
```  

grad.uiowa.edu:
```
migrate_plus.migration.d7_grad_srop_scholar   Only in sync dir
```

grad.uiowa.edu, immuno.grad.uiowa.edu, amcs.uiowa.edu:
```
core.entity_view_display.node.person.token
```

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/3293
Fix the current deployment issues. Ideally this should go out in the next release.

## To Test

- pull and try syncing hr, grad, immuno.grad, and amcs. They should import just dandy.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
pulling to test

**Comment by GaryRidgway** [comment]
Joe and I talked a bit about some problems I was having with the config, i was getting this large red error when trying to sync grad:
Screen Shot 2021-03-31 at 2 09 40 PM

I think there may be more to do here?

**Comment by pyrello** [comment]
This issue was occurring because I had not disabled the `grad_migrate` split, but I had uninstalled the 5 migration modules that were dependencies of it. The issue above was not specifically related to this PR at all.

**Comment by joewhitsitt** [comment]
The migrate errors are gone from the grad sync. Thanks

**Review by GaryRidgway — APPROVED** [review]
THE QUAD SYNC WORKED. WE GOOD.

**Pull request merged**
