### PR TITLE
exclude Topic Collection content type from related views

### PR DESCRIPTION
**Pull request by quamsta**
See: https://github.com/uiowa/uiowa/issues/4932

# How to test

1. Check out this branch
2. `blt ds --site=basicneeds.uiowa.edu`
3. Click into an individual page from the homepage (Topic Collection)
4. Check for "Find Resources" in related content
5. If there's no "Find Resources" page in related content, then this worked.

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test

**Review by bspeare — APPROVED** [review]
Tested locally and it excludes the topic collection page from the related view.

**Comment by GaryRidgway** [comment]
wellp, I also tested and I agree with Ben! haha

**Comment by quamsta** [comment]
Thanks to you both!!

**Pull request merged**
