### PR TITLE
[Gallery block] Image gallery block enhancements

### LINKED ISSUE #5386: As a site editor, I can select the type of aspect ratio to use in my image gallery block
# Story

As a site editor, I can select the type of aspect ratio to use in my image gallery block.

# Proposed solution

- Add a layout builder style to choose between aspect ratios to add a modifier class to the image block wrapper. 
  - Original/Default (no aspect ratio)
  - Square (1:1)
  - Widescreen (16:9)
  - Portrait (.5)
  - Masonry

https://codepen.io/bspeare/pen/rNvOVZY

### LINKED ISSUE #5566: As a developer, I can reuse the image block gallery styles on other block components
# Story

As a developer, I can reuse the image block gallery styles on other block components using photoswipe. 

# Proposed solution

- Refactor https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/image-gallery-block.scss#L12-L35 to use a reusable image gallery class. 
- Fix awkward flex layout spacing so that all thumbnails retain their aspect ratios.
- Consider including https://github.com/uiowa/uiowa/pull/5552#discussion_r940704613
- Refactor the work in https://github.com/uiowa/uiowa/pull/5552 to use the updated image gallery class. 
- Reconsider mobile experience. 

Screen Shot 2022-08-11 at 3 09 58 PM

### LINKED ISSUE #6650: Photo Gallery Block: Last few images crop strangely
Hi all, greetings from the other side of the river! I'm working on some lab websites over here in the Department of Pathology with photo galleries and while I noticed this before, I'm not sure if there's already an issue made for this.

# Problem

On some display sizes, if there aren't enough images to fill a column, the remaining images in the non-masonry image gallery block are super wide and look strange:

https://labkarandikar.prod.drupal.uiowa.edu/lab-photos/group-photos-over-years

Screenshot 2023-07-13 at 1 26 21 PM

https://labkarandikar.prod.drupal.uiowa.edu/lab-photos/2013-2020-iowa-years

Screenshot 2023-07-13 at 1 32 03 PM

# Steps to reproduce

1. Create an image gallery with at least four images
2. Resize your browser viewport until one or two images "spill over"
3. Note the super wide crop

# Proposed solution

If we are to maintain the square image aspect ratio on the non masonry grid, this (or something similar) may work:

```
.uiowa-image-gallery photoswipe-gallery{
  display: flex;
  flex-wrap: wrap;
}

.contextual-region media media--type-image media--view-mode-image-gallery{
  flex: 0 0 auto; 
  width: 25%; 
  padding: 10px; 
  position: relative; 
}

.contextual-region media media--type-image media--view-mode-image-gallery:before {
  content: "";
  display: block;
  padding-top: 100%; 
}

.block-field-blocknodearticlefield-gallery-images .media--view-mode-image-gallery img, .block-inline-blockuiowa-image-gallery .uiowa-image-gallery .media--view-mode-image-gallery img{
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  padding: 5px;
}
```

Result:

https://github.com/uiowa/uiowa/assets/472923/0d406dc2-f8b1-4a40-b002-ce80a9416782

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6650
Resolves https://github.com/uiowa/uiowa/issues/5386
Resolves https://github.com/uiowa/uiowa/issues/5566

This **could** solve https://github.com/uiowa/uiowa/issues/4795 in that it offers a "No crop" option where, if you uploaded faculty photos of all the same size, the focal point would be respected.  Perhaps if this pr gets merged we can discuss the next steps in that issue.

```
ddev blt frontend && ddev blt ds --site=karandikar.lab.uiowa.edu && ddev drush @labkarandikar.local uli /lab-photos/group-photos-over-years
```

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /multiple-image-gallery-layout-builder-blocks
```
Also test https://sandbox.uiowa.ddev.site/news/2022/09/alan-makes-gallery

## Test Housing and Classrooms grids

```
ddev blt frontend && ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local uli /abw-110
```

```
ddev blt frontend && ddev blt ds --site=housing.uiowa.edu && ddev drush @housing.local uli /residence-halls/catlett
```

## Test P2LB conversion

```
ddev blt sync --site hawkeyemarchingband.uiowa.edu --define drush.aliases.remote=hawkeyemarchingband.test && ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y && ddev drush @hawkeyemarchingband.local uli admin/content/sitenow-converter
```

Convert the "Test page" and scroll all the way to the bottom and confirm that masonry was converted to the masonry style.

### CODE REVIEW

**Comment by bspeare** [comment]
**Update: Portrait has been removed.** 

Options:

Screenshot 2023-09-14 at 2 59 49 PM

Masonry option through the Styles menu only appears if "No Crop" is selected:

Screenshot 2023-09-14 at 2 59 42 PM

Here's some recordings of how this is currently working:

**Widescreen to Portrait** 

https://github.com/uiowa/uiowa/assets/1036433/119480de-ad60-4cc7-a9bd-c534d4b8875f

**Square to Widescreen** 

https://github.com/uiowa/uiowa/assets/1036433/d7f010d2-0daa-4727-994d-bd601f14c9ee

**No crop to Square** 

https://github.com/uiowa/uiowa/assets/1036433/d7fb26ac-729a-4407-807b-ff89e2518991

**Masonry to No crop** 

https://github.com/uiowa/uiowa/assets/1036433/e521113a-5be8-4bf1-81d7-d726b1d5e6e6

**Comment by quamsta** [comment]
@bspeare This looks awesome! The square and widescreen options look great.

My only feedback about the No crop option would be that it may look nice if the photos had a light gray background and were centered within that. Something like:

Screenshot 2023-09-15 at 12 55 56 PM

```
.block-inline-blockuiowa-image-gallery .uiowa-image-gallery .media--view-mode-image-gallery img {
    object-fit: contain;
    height: 220px;
    width: 100%;
    background: #eee;
}
```

That may give the images in the gallery some semblance of visual coherency even if they are wildly different in aspect ratio.

**Comment by joewhitsitt** [comment]
Taking a peek at this

**Comment by joewhitsitt** [comment]
Going through the test instructions, this is working very well and is big improvement over what we currently have. Nice that the masonry order is preserved. I'd argue that square should be the default. As a user, I don't understand what the (.5) is supposed to mean for the portrait option.

Mentioned in a DM that the jquery.once stuff will need to be updated to be d10 compatible.

**Comment by bspeare** [comment]
Thanks for looking @joewhitsitt.   I'd be fine with square as the default.   Is the portrait option worth having?  I agree, the (.5) should definitely be removed from the label if we use it.

**Comment by joewhitsitt** [comment]
>Is the portrait option worth having?

Haven't we been training folks away from portrait images for the person content type, academic profiles, etc. I might not be aware of the current use-case. No crop seems to handle non-ideal ratios just fine.

**Comment by bspeare** [comment]
@quamsta thanks for that suggestion.    I think that it is a good suggestion but I still learning towards the simplicity of the empty space.   What does everyone else think?

Screenshot 2023-09-21 at 2 51 18 PM
Screenshot 2023-09-21 at 2 51 35 PM

**Comment by GaryRidgway** [comment]
Pulling to test

**Comment by GaryRidgway** [comment]
So far all of this looks good!

I tested everything and it looks like it all works as expected. the only thing I am seeing that could possibly be a "Bug" is that the masonry style hangs over the edges of its container:

<details><summary>Example here</summary>


</details> 

As for the No-crop gallery, I'm not incredibly partial to either one to be honest. I feel like I personally would force no-crop to be masonry. 

between the two styles though, I think that either of them could work. The grey pulls MORE attention to the fact that they are not the same size, but it also adds a little bit of structure to the gallery, which I think is what I would be desiring from the masonry. I would say I prefer the grey slightly more than the blank space.

**Review by GaryRidgway — APPROVED** [review]
Looks good to me, if we want to do the grey later, we can make another slice.

**Review by pyrello — APPROVED** [review]
Code reviewed only.

**Pull request merged**
