### PR TITLE
Scheduled hawk alert bash script

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/7502

# Test

`ddev drush @uiowa07.dev ssh`
`cd /shared/logs && tail -f drush-cron.log`
Observe status messages each minute.

Back to filtered_html capability on body and situation updates so they can include images if needed.

Webmaster has the ability to override the import date (created) if need be.

```
/shared/logs$ tail -f drush-cron.log
 [notice] Checking for alerts.
 [notice] Hawk alerts content sync completed. 1 alerts were created and 0 skipped. That is neat.
[HAWK ALERT IMPORT] Mon Apr 15 18:32:49 UTC 2024
 [notice] Starting the hawk alert content sync from drush. This may take a little time.
 [notice] Checking for alerts.
 [notice] Hawk alerts content sync completed. 0 alerts were created and 1 skipped. That is neat.
[HAWK ALERT IMPORT] Mon Apr 15 18:33:49 UTC 2024
 [notice] Starting the hawk alert content sync from drush. This may take a little time.
 [notice] Checking for alerts.
 [notice] Hawk alerts content sync completed. 0 alerts were created and 1 skipped. That is neat.
```

# Follow-up

- Move scheduled job to PROD once script is deployed.
- Remove scheduled job from DEV.
- Empty drush-cron.log

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@pyrello do you recall the solution to the permission denied issue with this hawk-alert script?

>bash: /var/www/html/uiowa07dev/scripts/hawkalert.sh: Permission denied

**Comment by pyrello** [comment]
> @pyrello do you recall the solution to the permission denied issue with this hawk-alert script?
> 
> > bash: /var/www/html/uiowa07dev/scripts/hawkalert.sh: Permission denied

Not 100% on this, but I think I was able to change the permissions for the file. I think I did `chmod +x`.

**Comment by joewhitsitt** [comment]
DEV is running as expected with the permissions change.

**Comment by joewhitsitt** [comment]
well, the importer ran as expected, but the view didn't clear/refresh.

Screenshot 2024-04-16 at 4 30 50 PM

Screenshot 2024-04-16 at 4 32 44 PM

**Comment by joewhitsitt** [comment]
Based on ^^

I think we need a simple invalidation when an alert is created to clear related views cache.

```
    Cache::invalidateTags(['node_list:hawk_alert']);
```

https://www.drupal.org/project/drupal/issues/2145751

The current d7 website has an APE hook to clear after feeds import.

**Review by GaryRidgway — APPROVED** [review]
Did a quick check and looked good to me. Worked in dev so should work in prod.

**Comment by joewhitsitt** [comment]
Going to slice off the views cache issue as it technically unrelated to the base of this PR. Thanks @GaryRidgway

**Pull request merged**
