### PR TITLE
Feature: final pdf updates

### PR DESCRIPTION
**Pull request by bspeare**
**Remaining tasks:**
- [x] Compare D7 pdf fields with D8

# How to test

- `blt ds --site=admissions.uiowa.edu`
- `yarn workspace admissions_core build`
- `drush @admissions.local cr`
- Go to http://admissions.local.drupal.uiowa.edu/areas-of-study/print-links
- Verify that you can wrap a section in the text area with `<div class="print__sidebar--right"></div>` and the content will render in the pdf as a column floated to the right with a gray background.  

Screen Shot 2021-02-26 at 3 57 03 PM

- Verify that you can wrap multiple `<ul>` in `<div class="print__list--column"></div>` and they will stack in a column like:

Screen Shot 2021-02-26 at 3 56 40 PM

- Verify that the `Roboto Bold` font is working as it appears to the example below
- Verify that the Certificates appear without a checkbox as it appears to the example below

Screen Shot 2021-02-26 at 3 45 37 PM

<details>
Possible help text
For the print version, the following adjustments can be made:
<ul>
<li>Pull a block of text out and display it on the right side of the page in a gray box by wrapping the content in `<div class="print__sidebar--right"></div>` </li>
<li>Force a set of lists to display side-by-side by wrapping each one in `<div class="print__list--column"></div>` </li>
</ul>
</details>

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling down to test.

**Comment by pyrello** [comment]
Since we are waiting for feedback from Admissions, I won't mark this as "Approved" yet, but I did test it and everything appears to be working per the instructions.

**Comment by bspeare** [comment]
Based on the conversation from today's meeting, I think we can move forward with reviewing this.

**Review by pyrello — APPROVED** [review]
Updates work as described. Thanks!

**Pull request merged**
