### PR TITLE
Update Area of Study and Transfer tip long text fields to `filtered_html`.

### LINKED ISSUE #3419: Admissions - Report of Long Text Full_HTML fields
## Issue

We suspect that during migration, fields with full_html on the old site were migrated over to the new site the same way where editors don't have access. Additionally, fields have been marked full_html intentionally by developers to provide embeds.

## Proposed Solution

- [x] Query the admissions site for long text and long text summary fields with the full_html format. Provide the entity id associated with one.
  - There are a couple of examples of queries that could be run locally that output messages that could be turned into something to hand over to admissions.
  - https://github.com/uiowa/uiowa/blob/ea2052f6822e02b5c34ceaaca1c73e03c82ac29c/docroot/profiles/custom/sitenow/sitenow.install#L2449
- [ ] Ask Admissions which fields can be turned back to filtered_html and either run an update hook or manually correct.

https://iowaweb.slack.com/archives/C019B2C8K8U/p1619115149056800

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #3419 

# How to test

- `blt ds --site admissions.uiowa.edu` and watch the output.
- Spot check some items from the list below to make sure that the format was updated correctly. 
- Check older revisions, if they exist, of items in the list below to make sure that  the format was updated correctly across all revisions.
- `blt ds` and confirm no additional output for update hook.

## Spot check list:
* https://admissions.local.drupal.uiowa.edu/node/2736
* https://admissions.local.drupal.uiowa.edu/node/2776
* https://admissions.local.drupal.uiowa.edu/node/2956
* https://admissions.local.drupal.uiowa.edu/node/3026
* https://admissions.local.drupal.uiowa.edu/node/3106
* https://admissions.local.drupal.uiowa.edu/node/3111
* https://admissions.local.drupal.uiowa.edu/node/3126
* https://admissions.local.drupal.uiowa.edu/node/3236
* https://admissions.local.drupal.uiowa.edu/node/3261
* https://admissions.local.drupal.uiowa.edu/node/3301
* https://admissions.local.drupal.uiowa.edu/node/3391
* https://admissions.local.drupal.uiowa.edu/node/3416
* https://admissions.local.drupal.uiowa.edu/node/3421
* https://admissions.local.drupal.uiowa.edu/node/3431
* https://admissions.local.drupal.uiowa.edu/node/3441
* https://admissions.local.drupal.uiowa.edu/node/3636
* https://admissions.local.drupal.uiowa.edu/node/3661
* https://admissions.local.drupal.uiowa.edu/node/3666
* https://admissions.local.drupal.uiowa.edu/node/3676
* https://admissions.local.drupal.uiowa.edu/node/3811

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by richardbporter** [comment]
One thing I noticed glancing at this is that if the update hook is moved to admissions_core/admissions_core.install then it won't run on any other site. That should save time/resources on deployment.

**Comment by cory-skeers** [comment]
The update ran without issue, but it looks like it might have only gotten the text with summary body field.

image

Other fields are still `full_html`
https://admissions.local.drupal.uiowa.edu/node/2956/edit
Why Iowa, Admission Requirements, Course Work

https://admissions.local.drupal.uiowa.edu/node/2736/edit
Student Opportunities

**Comment by pyrello** [comment]
> One thing I noticed glancing at this is that if the update hook is moved to admissions_core/admissions_core.install then it won't run on any other site. That should save time/resources on deployment.

Good call, @richardbporter!

> Other fields are still full_html
> https://admissions.local.drupal.uiowa.edu/node/2956/edit
> Why Iowa, Admission Requirements, Course Work
>
> https://admissions.local.drupal.uiowa.edu/node/2736/edit
> Student Opportunities

Thanks for testing, @cory-skeers. I'll take a look.

**Comment by pyrello** [comment]
This is ready for review again. I believe I have resolved the outstanding issues.

**Comment by cory-skeers** [comment]
Pulling down to test

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and all looks good!

Update hook fired and output looks accurate to what would be expected. Spot checked a chunk of both AoS and Transfer Tips, found a few with revisions, and both the current and revision fields updated correctly. Also checked a `blt ds` after, with no additional output.

**Comment by pyrello** [comment]
Because this is limited to Admissions, I think I'm comfortable with the current level of testing.

**Pull request merged**
