### PR TITLE
bumping uids release number

### PR DESCRIPTION
**Pull request by GaryRidgway**
Is resolving https://github.com/uiowa/uids/issues/445. This is intended to give headings and intros a scaling size based upon screen wdth.

# How to test

1. Pull down any site with headings or intros
2. Test that the sizing of any headers or intros scales between 600px and 1310 px viewport width, and that there are clamp rules to change their size and backup rules for unsupported browsers (Which should only be ie7 and before)

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling down to test.  Do we need the updated `yarn.lock` file for this bump?

**Comment by richardbporter** [comment]
I would think so but perhaps not: https://travis-ci.com/github/uiowa/uiowa/builds/221707366#L1771

**Review by bspeare — APPROVED** [review]
Clampage looks good!

**Comment by richardbporter** [comment]
Conflict with latest. Resolved but lets double check Travis build output for correct version.

**Comment by richardbporter** [comment]
3.4.3 https://travis-ci.com/github/uiowa/uiowa/builds/221812341#L1793

**Pull request merged**
