### PR TITLE
Updated to latest version of drupal/core-recommended.

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

Review https://git.drupalcode.org/project/drupal/-/compare/9.2.10...9.2.11?from_project_id=59858. Let me know if you think we need to do more testing beyond that.

### CODE REVIEW

**Review by joewhitsitt — APPROVED** [review]
Reviewed, not tested

**Comment by pyrello** [comment]
Thanks @joewhitsitt! I guess I'm going to add the `jquery_ui_datepicker` module update here as well.

**Comment by joewhitsitt** [comment]
I thought webform was the only one that used jquery_ui_datepicker and bundles it within their module.

**Comment by pyrello** [comment]
> I thought webform was the only one that used jquery_ui_datepicker and bundles it within their module.

```
composer why drupal/jquery_ui_datepicker
drupal/better_exposed_filters  5.0.0-beta3  requires  drupal/jquery_ui_datepicker (^1.0) 
```

**Comment by joewhitsitt** [comment]
😞

**Pull request merged**
