### PR TITLE
Feature: person_extended updates

### LINKED ISSUE #2582: Add option for former students or faculty
# Story

As a site owner I want to be able to indicate that a person is no longer in the group (person type) that they formerly occupied (e.g. past faculty, former students) so that I can distinguish between them in lists.

## Examples of how this would be used
* https://www.amcs.uiowa.edu/students/all-graduates
* https://toxicology.grad.uiowa.edu/program-alumni
* https://toxicology.grad.uiowa.edu/faculty/past

# Proposed solution

- [x] Add a boolean "Allow status" property to person type config entity.
- [x] Add an allowed values function that gets all person types with allow status set and prepends "Former " to the beginning of them.
- [x] Add new person type statuses text list field to the person content type which references the allowed values function. (This happens after the field config is exported).
- [x] Write an update hook targeting any site with the `person_extended` split and for any people content items where the student person type is selected and the "Current student" flag is not set, set the "Former student" person type status.
- [ ] BONUS: Add `#states` behavior to type status checkboxes to only show when their corresponding person type option is checked.

Please check with Sean if any of these items are unclear.

### LINKED ISSUE #3118: Person extended adjustments
# Motivation

The `person_extended` config split was initially developed prior to making a lot of changes to the person content type and has not kept pace with those changes. Some of the fields that have been added to it can be handled via other mechanisms.

# Proposed solution
- [x] Migrate field values for 'Office' and 'Lab' fields into Contact information.
- [x] Move Department field into Immunology split.
- [x] ~~Fix display of person types widget.~~ - This doesn't appear to be an issue anymore.

### LINKED ISSUE #3125: Add programs of study field to person content type in person_extended
# Motivation

The Graduate Student Senate is made of of senators from different programs. It is considered important to display the program of study as part of their record.

# Proposed resolution

Instead of the original plan, as part of #3337, I'm repurposing the `person_extended` split to be grad-specific and adding this field there.

### PR DESCRIPTION
**Pull request by pyrello**
* Resolves #3118 
* Resolves #3125 
* Resolves #2582 
* Renames `person_extended` split to `grad_person_extended`

# How to test
## Check the base case
`blt ds` to check that both update hooks print out the message `>  [notice] person_extended split is not active, so no update to run.` This should be the behavior for all sites where `person_extended` is not enabled.

## Immunology
* `blt ds --site immuno.grad.uiowa.edu`
* `drush @gradimmuno.local uli people/vladimir-badovinac` to verify that Office and Lab fields have been converted to Contact Information records (they will display in the sidebar).
* Also confirm that both contact info records show without a comma between them.
* Verify that 'Former Student' is not selected: http://gradimmuno.local.drupal.uiowa.edu/node/616/edit.
* Verify that 'Former Student' is not selected: http://gradimmuno.local.drupal.uiowa.edu/node/451/edit.
* Verify that 'Former Student' is selected: http://gradimmuno.local.drupal.uiowa.edu/node/631/edit

## AMCS
* `blt ds --site amcs.uiowa.edu`
* `drush @amcs.local uli node/346/edit` and confirm that record has 'Former Student' selected under 'Person type status'.
* Also confirm that there were no contact info records created.

## Show/Hide Former Options

Instead of showing all "allowed former" options by default on the person add/edit forms, there is an AJAX callback that is showing and hiding the former option related to the person type selected.

* Check each person type to see what allows former admin/structure/person-type. Keep those in mind as you proceed.
* Add new person, edit existing. Play with the person type options, selecting and unselecting. Person types that allow former, should display former options below in the Person types status field. A selection of a former option should be cleared if the associated person type is unselected.
* Save and reload, the selections should be maintained.

### CODE REVIEW

**Comment by pyrello** [comment]
I've decided to pull in #2582 because I'm already running updates on `person_extended` sites and it also helps me clear out another blocking issue for AMCS.

**Comment by pyrello** [comment]
With the exception of handling the display of the person types statuses correctly (https://github.com/uiowa/uiowa/issues/2582#issuecomment-815227018), I mostly have this working. The surprising thing I have run into is that I cannot access the new `field_person_type_status` in the custom view that I built for immuno.grad.uiowa.edu to display current and former students. I just doesn't show up as an option for either fields or filters, so I'm somewhat stumped by that.

**Comment by joewhitsitt** [comment]
Do you need to add the configuration entity as a relationship?

**Comment by pyrello** [comment]
I wouldn't think so, since the field I'm trying to add doesn't have any association with the config entity outside of that I reference it inside the allowed values function.

**Comment by joewhitsitt** [comment]
oh sorry, i confused this with the allow former.

**Comment by pyrello** [comment]
This first picture shows the new field and also another "List (text)" field called Program, which also uses an allowed values function:
Screen Shot 2021-04-08 at 9 16 23 AM

Programs field shows up as an option in Filters:
Screen Shot 2021-04-08 at 9 19 07 AM

Person type status does not:
Screen Shot 2021-04-08 at 9 18 48 AM

**Comment by joewhitsitt** [comment]
going to take a peek

**Comment by pyrello** [comment]
I haven't been super consistent with the naming related to #2582, in part because I honestly wasn't sure what to call it. Feel free to make suggestions ;)

**Comment by pyrello** [comment]
For reasons that are not entirely clear to me, when the update hook runs, it is not correctly attaching the address/contact info. In one case it is taking 2 locations and ending up with 4 contact info records (some of which are incomplete): http://gradimmuno.local.drupal.uiowa.edu/node/616/edit. In another it is correctly attaching only one record, but omitting the address: http://gradimmuno.local.drupal.uiowa.edu/node/451/edit. I have been staring at it for too long and need some help figuring out what I am doing wrong.

**Comment by pyrello** [comment]
Still to do:
- [x] Fix logic with address/contact info being attached to node in update hook.
- [x] Update custom view in immuno.grad.uiowa.edu split to reference the new "Person type status" field.
- [x] Remove `field_pt_student_current` field. This may have to be done in a follow-up PR.

**Comment by pyrello** [comment]
I have also tried this: https://drupalabc.xyz/question/how-set-address-field-programatically-drupal-8. Either syntax results in the same results.

**Comment by joewhitsitt** [comment]
This seems to fix node/451 for me. Removing the `address` outer array.

```
$field_uiowa_contact_address = [
  'country_code' => 'US',
  'address_line1' => $address,
];
$contact_info->set('field_uiowa_contact_address', $field_uiowa_contact_address);
```

Looking at the duplicate part of 616 now. Will commit changes if I figure out both.

**Comment by joewhitsitt** [comment]
>Fix logic with address/contact info being attached to node in update hook.

I think this is fixed. Can you test @pyrello?

**Comment by pyrello** [comment]
Thanks, @joewhitsitt! Testing now.

**Comment by pyrello** [comment]
Thank you thank you thank you thank you thank you!

**Comment by joewhitsitt** [comment]
FWIW now that I am biased, I think this looks good. I ran through the existing test steps and ran syncs on gis.sites and admissions (no import config diffs!). I didn't test the custom view. 👍 

Follow-up task: rm `config/features/person_extended` directory

**Comment by pyrello** [comment]
Thanks for testing, @joewhitsitt!

**Comment by GaryRidgway** [comment]
I am going to pull this down for testing Joe's Ajax logic

**Review by GaryRidgway — APPROVED** [review]
I was told that the only thing left to review was Joe's AJAX additions for former tags, and those worked! on that basis, i approve.

**Pull request merged**
