### PR TITLE
Banner mobile overlay

### LINKED ISSUE #4919: As a site owner, I can view a banner on a mobile device with the content separated from the image
# Story

As a site owner, I can view a banner on a mobile device with the content separated from the image so that the content and image are both readable/usable in the small space. 

# Proposed solution

- Add an option to the banner component block so that banner content is not absolutely positioned on top of the banner image for mobile.
- Use https://github.com/uiowa/uids/pull/652 as the starting point.  We will need to create a modifier class to set the mobile styles. 

**Before:**

IowaMBA_current

**After:**

IowaMBA_future

### PR DESCRIPTION
**Pull request by GaryRidgway**
Resolves https://github.com/uiowa/uiowa/issues/4919

## To test
1.  setup:  
  -  `git checkout banner-mobile-overlay`
  - `ddev composer install`
  - `ddev blt frontend`
  - `ddev blt ds --site=sandbox.uiowa.edu`
2.  Replicate
  - https://sandbox.uiowa.ddev.site/banners-imagesvideos-w-black-and-white-gradients
  - https://sandbox.uiowa.ddev.site/banner-backgrounds-w-gradient-dark
  - https://sandbox.uiowa.ddev.site/banner-backgrounds-w-gradient-light
3.  On each of the replicated pages above edit each banner and add the mobile stacking style. 
  - You should have 
    - the 3 original pages 
    - the 3 duplicated pages w/ each banner set to mobile stacked
5. Test the six pages on mobile and desktop and look for any colors that are unreadable like black on black. 
6. Edit each of the six pages and add a black background pattern to the layout section holding all of the banners
 - Test the six pages on mobile and desktop and look for any colors that are unreadable like black on black. 
7.  Repeat step 5 for a white, gray, and gold background color. 

Banners of the same background color as the section will have their margin/padding removed: https://github.com/uiowa/uiowa/pull/3702

### Known issues
 
You might come across a few issues like:
- Blockquote border is not visible on white gradient with gold section background: fixed on https://github.com/uiowa/uids/pull/652/commits/6d8bb2ba204a99221e921d55ee14bb913650c7b1
- Headline highlight background is the same color as the background color on nested backgrounds: https://github.com/uiowa/uids/issues/680

These are background issues related to the blockquote and headline components that will not be resolved within this pull request.   As long as the text colors are adapting and providing accessible color contrast, this should move forward.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
This is potentially done, however there has been a lot of comments in [this slack thread](https://iowaweb.slack.com/archives/C0164FNN1PV/p1649693836612419) about what is going on here, so until we resolve that and/or decide on a path forward I think we should wait on review.

**Comment by GaryRidgway** [comment]
Currently the new styles work, yay!

However, they break for background colors:
1d1877e5af746b18f18fcf38d8889162

If we add css styling based on if it has media or not then titling the style option `Content stacks with media on mobile` could possibly alleviate the issue. We could simply not stack when there is no media is present, as the style option describes.

**Comment by GaryRidgway** [comment]
Started taking a look at things again, noticing a few issues:

<details>
<summary> There are issues with the video play button disappearing on mobile emulation in chrome, which is odd.</summary>


alt text

</details>

<details>
<summary> It seems as though  gradients now only exist on stacked banners, and normal banners just have a transparent overlay.</summary>


f14fea1367b9ebe3a787282ab002b549


</details>

<details>
<summary> Text contrast on black BG</summary>

asdfasdf

</details>

<details>
<summary> Banners with color/pattern backgrounds have no left margin if they are on top of the same color/background section (I have tested this with multiple color combinations)</summary>

Screen Shot 2022-04-14 at 11 10 11 AM

Screen Shot 2022-04-14 at 11 10 26 AM


</details>

**Comment by richardbporter** [comment]
>Since this is using a UIDS hash you will need to run:
rm -rf ./node_modules
ddev yarn cache clean
ddev yarn install
ddev yarn workspace uids_base gulp --development

I'm able to switch between main and this branch and running `ddev blt frontend` seems to get the right version of uids installed without having to do all that cache clearing. I tested this after switching back to the URL format in [2c5ef58](https://github.com/uiowa/uiowa/pull/5123/commits/2c5ef58e7c92a72c7bac1db60cfc255775b1fba8).

**Comment by bspeare** [comment]
@richardbporter Great! I updated the instructions.

**Review by richardbporter — APPROVED** [review]
This looks great! I think only the uids version needs to be updated after a release of that, right?

**Comment by bspeare** [comment]
@richardbporter thanks! Yes, I will move this to draft so we can attach a release to this.

**Pull request merged**
