### PR TITLE
Hotfix: Restore card media classes logic

### LINKED ISSUE #3067: D9 Upgrade seems to have broken horizontal card style
# Problem
Horizontal card style appears to have a visual regression after the D9 upgrade:

Screen Shot 2021-02-15 at 7 41 51 AM
Screen Shot 2021-02-15 at 7 43 41 AM

It seems like there might have been subtle changes to class names or HTML structure. 

# Steps to reproduce
Visit https://grad.uiowa.edu/ or https://sandbox.prod.drupal.uiowa.edu/ to see the above images live.

# Proposed solution

TBD

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #3067 

# How to test

* `blt ds --site=grad.uiowa.edu` or `blt ds --site=sandbox.uiowa.edu`
* Visit http://grad.local.drupal.uiowa.edu or http://sandbox.local.drupal.uiowa.edu and verify that visual regression in above issue is partially resolved.

### CODE REVIEW

**Comment by pyrello** [comment]
Unfortunately, this didn't completely fix the issue, but it is a step in the right direction at least.

Screen Shot 2021-02-15 at 8 34 08 AM

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Step in the right direction. Looks like other block types are separately affected.

**Comment by pyrello** [comment]
I'm going to push a fix for the headline issue in the banner, if it works.

**Pull request merged**
