### PR TITLE
Fix PHPCS warnings.

### PR DESCRIPTION
**Pull request by richardbporter**

### CODE REVIEW

**Comment by joewhitsitt** [comment]
tested articles and people config. works as expected.

**Comment by joewhitsitt** [comment]
`ArgumentCountError: Too few arguments to function Drupal\sitenow_migrate\EventSubscriber\PostRowSaveEvent::__construct(), 0 passed` when trying to run `drush mim d7_file` on the default site

**Comment by richardbporter** [comment]
Thanks. I had tested articles and people but hadn't figured out setting up a migration locally yet.

**Comment by joewhitsitt** [comment]
```Error: Call to a member function getStorage() on null in Drupal\sitenow_migrate\EventSubscriber\PostRowSaveEvent->makeEntity() (line 91```

getting farther

**Comment by richardbporter** [comment]
@joewhitsitt ping

**Review by joewhitsitt — APPROVED** [review]
whew!

**Pull request merged**
