### PR TITLE
Feature: IISC partner content type

### LINKED ISSUE #5031: IISC - Create content type for migrating Partner content.
## Story 

As an IISC editor/webmaster, I want to display information about our Project Partners. 

## Solution

Create a Partner content type with the following fields:
- Title (text)
- Photo (image)
- Description (text, long)
- Related links (URL field)
- References section
- - Related individuals (reference People content)
- - Iowa county (currently a checkbox list of all 99, open to suggestions)

Additionally, the displayed page (view?) for Partner content shows 'Related News' (articles tagged with the partner name) and 'Related Projects' (projects tagged with the partner name).

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5031. 

# How to test

As an editor, webmaster, or publisher, I can add a partner page with all of the fields defined in https://github.com/uiowa/uiowa/issues/5031.

`ddev blt ds --site=iisc.uiowa.edu`
`ddev drush @iisc.local config:import --source ../config/sites/iisc.uiowa.edu --partial`
`ddev drush @iisc.local cim`
`ddev drush @iisc.local uli`

**Verify** 

- Node type
- Fields - uses base field image - should this use any other base fields?
- Default display - Set with layout builder
- Teaser display - Not set
- Form display - Uses a fieldset for References
- Disabled promote to front page 
- Disabled Sticky
- Revisions should be set to max of 10
- Preview settings are set to don't require
- Sitemap should be enabled
- Path alias pattern is not set - should it?
- It is not allowed in main menu
- Metatags - field_meta_tags have been added to the content type with separate partner metatag bucket
- Moderation workflow is set for this content type
- Role permissions are set for this content type
- Uses _sitenow_node_form_defaults() for shared fields in sidebar
- Added `uiowa_core_county_options` to `uiowa_core`: https://github.com/uiowa/uiowa/blob/243f1758aba6b4466bc984a7d0a4320b2f06be88/docroot/modules/custom/uiowa_core/uiowa_core.module#L466

### CODE REVIEW

**Comment by e-marie-w** [comment]
I can test this!

**Comment by e-marie-w** [comment]
Question about permissions: for the most part they match the permissions for other content types on the site, but there are a few differences, do we want those differences? Usually for Viewer role 'view revisions' is allowed and for Webmaster 'override authored on option' and 'override sticky option' are allowed. Right now they aren't for Partners.

**Comment by joewhitsitt** [comment]
>Usually for Viewer role 'view revisions' is allowed

Yeah, this is common for default types, but it really depends on if IISC is going to even use this role.

> 'override authored on option'

This is common for chronological based content like articles.

> 'override sticky option'

If there is a view display of this content with this sticky sort, then this permission makes sense.

**Comment by e-marie-w** [comment]
For the metatags, do we want to limit it to Basic, Advanced, and Open Graph like we did for the 2+2 Majors on Admissions, or should this have different settings?

Also, right now revisions are set to 6, I can update that quick.

**Comment by e-marie-w** [comment]
> Fields - uses base field image - should this use any other base fields?

You could use the base body field for the partner description field, but I'm not sure if it's worth changing at this point.

> Path alias pattern is not set - should it?

I think it's fine to leave unset at this point. When we create the view/display of all partners we can set the path based off that.

**Comment by joewhitsitt** [comment]
Does this need another reviewer or you got it @e-marie-w ?

**Comment by pyrello** [comment]
I'd like to review this too.

**Comment by e-marie-w** [comment]
Currently handling support stuff, if someone else wanted to do the metatag stuff. Otherwise I'll get to it later today.

**Comment by pyrello** [comment]
On the original site for this content type there is a checkbox for "Current partner." Was this left off intentionally?

**Comment by pyrello** [comment]
> On the original site for this content type there is a checkbox for "Current partner." Was this left off intentionally?

Okay, I'm seeing that it wasn't included in the issue. @e-marie-w, was this intentional?

**Comment by bspeare** [comment]
I don't think that was intentional on my part.  I can add it.

**Comment by e-marie-w** [comment]
> Okay, I'm seeing that it wasn't included in the issue. @e-marie-w, was this intentional?

Not intentional, I definitely missed it. Thanks for catching it.

**Comment by pyrello** [comment]
> I don't think that was intentional on my part. I can add it.

Already did. Thanks!

**Comment by pyrello** [comment]
Turns out is was not necessary after all. I asked Travis and he said to get rid of it.

**Review by pyrello — APPROVED** [review]
Looks good. Nice work.

**Pull request merged**
