### PR TITLE
Feature: card person template refactoring

### LINKED ISSUE #3900: As a site owner, I can see the left aligned image as the default option for SiteNow People
# Story

As a site owner, I can see the left aligned image as the default option for SiteNow People Lists.

Now that we have a default image, we should switch the default image alignment to left-aligned to match the approach used by the Directory profiles app.  

# Proposed solution

- Change default People List block "Image Position: Left" instead of "Right"
- Update SiteNow people template to use left alignment modifier class

### LINKED ISSUE #3923: Add `click-target` to admissions counselors and student profiles views
# Problem
After the work in https://github.com/uiowa/uids/pull/552, the admissions and counselor views are not entirely clickable because they don't have the `click-target` class on the `<a>`. 

# Steps to reproduce
Try clicking on an image at https://admissions.uiowa.edu/counselors. 

# Proposed solution
- Update view title `<a>` to have the the `click-target` class.
- Review other views on grad college and check if there are any views that need updating.

### LINKED ISSUE #4097: As a developer, I can extend the node--person--teaser template without duplicating the entire template
# Story

As a developer, I can extend the node--person--teaser template without duplicating the entire template over and over again.

# Proposed solution

Change https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/content/node--person--teaser.html.twig#L97 to use `'card_text': content | render` instead of the teaser. 

- Update templates such as https://github.com/uiowa/uiowa/blob/main/docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/templates/node--person--teaser.html.twig to just extend the node person teaser template. 
- Update `core.entity_view_display.node.person.teaser.yml` to remove the "Links" field from the teaser settings.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3900
Resolves https://github.com/uiowa/uiowa/issues/4097
Resolves https://github.com/uiowa/uiowa/issues/3923

# How to test

```
blt ds --site=sandbox.uiowa.edu
blt ds --site=grad.uiowa.edu
blt ds --site=admissions.uiowa.edu
blt ds --site=pharmacy.uiowa.edu
blt ds --site=hawkeyemarchingband.uiowa.edu
blt frontend
```

This pr moves the card person image alignment to the left for all usages of the node--person--teaser template and consolidates a few node person template files to use node--person--teaser in uids_base.

**Grad**
- Compare https://grad.local.drupal.uiowa.edu/dei/srop/mentors with prod url.
- Compare https://grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2019 with prod url. 
- Compare https://grad.local.drupal.uiowa.edu/academics/thesis-defenses/list with prod url.

**Sandbox**
- Compare https://sandbox.local.drupal.uiowa.edu/sandbox-people with prod url. 

**Admissions**
- Compare https://admissions.local.drupal.uiowa.edu/counselors with prod url. 
- Verify that entire card is clickable. 

**Pharmacy**
- Create a person with palliative care type, and create a new page and place the palliative care list onto the page and verify that the name and territory are showing. 

**HMB**

- Go to https://hawkeyemarchingband.local.drupal.uiowa.edu/people-0 and verify that image alignment for people in featured content layout is left aligned.

### CODE REVIEW

**Comment by richardbporter** [comment]
Card subtitle is not printing on https://grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2019 but is on https://grad.uiowa.edu/dei/srop/past-scholars/2019. Is that intended?

**Comment by richardbporter** [comment]
> HMB
Go to https://hawkeyemarchingband.local.drupal.uiowa.edu/people-0 and verify that image alignment for people in featured content layout is left aligned.

So these images should be on the left?
Screen Shot 2021-09-10 at 2 39 51 PM

**Comment by richardbporter** [comment]
Deleted my last comment b/c I forgot to run `blt frontend`. 🤦🏻

**Comment by richardbporter** [comment]
> Card subtitle is not printing on https://grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2019 but is on https://grad.uiowa.edu/dei/srop/past-scholars/2019. Is that intended?

Example
Screen Shot 2021-09-10 at 2 45 45 PM

Screen Shot 2021-09-10 at 2 45 52 PM

**Comment by bspeare** [comment]
@richardbporter thanks for finding those!  Can you test grad again clear the cache / run `cim` on it to get the latest updates?

**Comment by richardbporter** [comment]
> @richardbporter thanks for finding those! Can you test grad again clear the cache / run `cim` on it to get the latest updates?

Yea that did it.

**Comment by richardbporter** [comment]
Sorry if I missed this in the issues but are the subtle style changes for subtitle spacing and phone/email fields intended? Here is an example: 

Screen Shot 2021-09-10 at 3 24 07 PM

Screen Shot 2021-09-10 at 3 24 00 PM

**Comment by richardbporter** [comment]
Also the font looks different for the date and zoom fields on https://grad.local.drupal.uiowa.edu/academics/thesis-defenses/list.

Screen Shot 2021-09-10 at 3 29 11 PM

Screen Shot 2021-09-10 at 3 28 45 PM

**Comment by bspeare** [comment]
@richardbporter Yes, both of those subtle changes get the template to use the default person styles for the node person teaser template.

**Review by richardbporter — APPROVED** [review]
I'm not sure I understand all the changes here but I don't see anything problematic based on the test instructions and original issues. :)

**Comment by bspeare** [comment]
@richardbporter thanks for testing!

**Pull request merged**
