### PR TITLE
Feature horizontal stat variant

### LINKED ISSUE #2084: Add horizontal stat variant into stat block component
# Proposed Solution

1.  Add "Horizontal" option in Override Style Options menu which adds `stat--horizontal` modifier class. 
2. Add new field to custom stat block for `stat__content` that will appear under the `stat__description`.  
3. Update stat block twig file with new `stat__content`. 
4. View UIDS version here: https://uids.brand.uiowa.edu/branches/feature_lb_feature_maturity/components/detail/stat--horizontal.html

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2084 

Adds a "content" field to the statistic component, as well as a new style option for the horizontal variant.

Waiting on https://github.com/uiowa/uids/issues/300 for finalized styling.

# How to test on home.local:

```
blt ds --site=uiowa.edu
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
drush @home.local cr
```

- Add content to the content block on an existing stat and save the page.  Verify that content appears on hover like in this example: https://uids.brand.uiowa.edu/branches/feature_stat_updates/components/detail/stat--default.html.  
- Add `flex-center` or `flex-left` options and verify that it still works. 
- Add `horizontal` variant and verify that the alignment of the stats changes to look like https://uids.brand.uiowa.edu/branches/feature_stat_updates/components/detail/stat--horizontal.html

### CODE REVIEW

**Comment by cory-skeers** [comment]
I'll leave final approval for another set of eyes since I'd worked on this as well, but tested on uiowa.edu and a fresh SNV3 install, and everything worked/looked great.

Added a short description to the content field on the form to help differentiate it from the excerpt field.

**Comment by GaryRidgway** [comment]
This is working for me. I noticed some reflow inconsistency due to the re-sizing effect when mixing stat types in vertical layouts

https://i.gyazo.com/5c0ca844f239d5e336c837021c978bed.gif

but it did not break anything, it was just inconsistent if anyone wanted another pass.

APPROVED!

**Review by GaryRidgway — APPROVED** [review]

**Comment by bspeare** [comment]
@GaryRidgway That's a good observation about the differing font sizes and reflow issues.  I think I'd like to tackle that before it gets merged in.

**Comment by cory-skeers** [comment]
Post style refactor: If you remove the default spacing (all default, or top default), the mouseover behavior pushes the stat component outside the top edge of the section. 

image

**Comment by bspeare** [comment]
@cory-skeers That's a great observation.  I would probably recommend that sites do not place stats up at the edge of a background color like that.   We might need to make a list of component usage examples and restrictions like the brand site has: https://brand.uiowa.edu/logos/secondary-logos#tigerhawk--4.

**Comment by cory-skeers** [comment]
> We might need to make a list of component usage examples and restrictions like the brand site has: https://brand.uiowa.edu/logos/secondary-logos#tigerhawk--4.

I think having a component-by-component of guidelines/examples like that sounds like a great idea. More necessary for some components than others, but I think it could be a really helpful reference to build out.

**Pull request merged**
