### PR TITLE
Update simple_sitemap module

### LINKED ISSUE #835: XML sitemap using http://
We should be using https:// for links for our sitemap.

### PR DESCRIPTION
**Pull request by joewhitsitt**
# Description
Resolves #835 

Requires post-deploy command within uiowa to generate sitemaps: `./vendor/bin/blt sitenow:multisite:execute ssg`

New sites need to run the same command in PROD before delivery.

# Checklist
- [x] Add appropriate PR labels.
- [x] Request approval from multiple developers across units.
- [x] Dependencies have been properly updated.
  - https://github.com/uiowa/uiowa#updating-dependencies
- [x] Site config splits have been accounted for.
  - Go to https://github.com/uiowa/uiowa/find/master to find split config entities affected by this PR.
- [x] Test PR locally with default site.
- [x] Test PR locally with custom site that might be affected by these changes.
- [ ] Update documentation.
  - Document changes introduced by this PR in application, profile or site README.
- [ ] Notify site provisioners that the provision process changes with this PR.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Requesting review from both sitenow and collegiate due to the composer change.

**Comment by richardbporter** [comment]
> Requires post-deploy command within uiowa to generate sitemaps: ./vendor/bin/blt sitenow:multisite:execute ssg

Will cron regenerate it? It runs fairly often. Otherwise, an update hook would take less time if possible.

> New sites need to run the same command in PROD before delivery.

Everytime a new site is provisioned? If so, we'll want to automate that.

**Comment by joewhitsitt** [comment]
Both are once depending on the site. post-deploy for the existing sites and once for new sites once they reach their final URL. Cron should handle it after that.

**Review by pyrello — APPROVED** [review]
We don't currently have any sitemap modules implemented, so the version change is no problem for us.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
