### PR TITLE
Set Webform configuration on HTML Editor > Element text format to Filtered HTML

### LINKED ISSUE #2971: Webform Basic HTML field cannot use text formats, so uids styling is broken
# Problem
The only option for an HTML markup field in webforms is the Basic HTML field. This field does not use a text format and does not allow p tags, which is causing styling issues (see below). Is this something worth fixing? The following screenshot can be found at [https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/information-sessions/iowa-city](https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/information-sessions/iowa-city).

Screen Shot 2021-01-28 at 4 46 37 PM

# Steps to reproduce

- Create a new webform from Structure > Webforms.
- Add a Basic HTML field and enter basic text, list items, etc.
- Give the form its own dedicated URL under Settings > General > URL path settings.
- Save form and view results.

# Proposed solution
This could be "fixed" by attaching the webform to another node or block, but these Information Session forms get updated regularly with new dates and times. Rather than editing both the node/block and then the field values of the form, we could simply edit both from the webform settings. This may need to be done if this issue isn't high priority.

If we allow the webform markup field to utilize the Filtered HTML and/or Minimal HTML hopefully our uids styling would carry over. I dont see an option to change this in the admin settings or form settings. This may need to be fixed in uids.

There was something about this at [https://drupal.org/project/webform/issues/2952809](https://drupal.org/project/webform/issues/2952809) and [https://drupal.org/project/webform/issues/2888626](https://drupal.org/project/webform/issues/2888626).

### LINKED ISSUE #3133: HTML Markup field in forms are not styled / Preferred method for instructional text above form?
# Problem
When creating a form for an information session to reproduce this page: [https://clas.uiowa.edu/socialwork/undergraduate-program/ba-programs/iowa-city-ba-program/information-sessions](https://clas.uiowa.edu/socialwork/undergraduate-program/ba-programs/iowa-city-ba-program/information-sessions), what is the preferred method moving forward in Drupal 8? Attach the form as a block in a basic page? Add a HTML Markup field above form so that both instructional text and form can be edited in the same window vs two? Third option?

Problem 1: HTML markup fields do not have a text format option, so styling does not carry over. The problem arises from the use of a HTML markup field in the form. The first screenshot shown below is what this HTML Markup field looks like live:
Screen Shot 2021-02-24 at 2 40 55 AM

This second screenshot is what it looks like when a Message field is used:
Screen Shot 2021-02-24 at 2 41 08 AM

Should I be embedding this form as a block inside another page instead?

# Steps to reproduce
Create a basic form, and add a HTML Markup field to the form. No text formats are available, so no styling is available.

# Proposed solution
Allow Plain text and Filtered HTML text formats on the HTML Markup field?
Embed form as block in separate page?
Preferred method determined?

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Sets the Element text format setting for all webforms under Webforms > Configuration > Elements > HTML editor settings to Filtered HTML. This should allow HTML or Markup fields to display text according to that text format. Fixes #3133 .
NOTE: Existing default contact forms are unaffected because they do not use the Markup field.

# How to test

- blt ds --site=socialwork.uiowa.edu
- Navigate to [http://socialwork.local.drupal.uiowa.edu/graduate/msw-social-work/iowa-city/information-sessions](http://socialwork.local.drupal.uiowa.edu/graduate/msw-social-work/iowa-city/information-sessions) or any of the other information session forms to verify that the HTML markup field at the top of the form is formatted correctly.
- Profit!

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Is filtered_html needed or can we get by with minimal?

**Comment by richardbporter** [comment]
I tried minimal locally but the `ul` doesn't render then.

**Review by joewhitsitt — APPROVED** [review]
>I tried minimal locally but the ul doesn't render then.

Ah, okay. Very well then. Looks good.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt The [https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/iowa-city/information-sessions](https://socialwork.prod.drupal.uiowa.edu/undergraduate/ba-social-work/iowa-city/information-sessions) pages on SSW seem to be working properly with what I put in using the HTML Mark up field and filtered_HTML seems to be the default and only option. It does appear that this is working for my concern above.

**Pull request merged**
