### PR TITLE
Initialize freeman.lab.uiowa.edu multisite on uiowa04

### PR DESCRIPTION
**Pull request by makurj**

### CODE REVIEW

**Comment by e-marie-w** [comment]
Is there any urgency to this? If not you could leave it open as this week's provisions PR.

**Comment by makurj** [comment]
I'm not aware of any urgency. Just trying to reduce Sean's load for when he gets back.

**Comment by joewhitsitt** [comment]
@pyrello any more provisions or can this be approved/merged?

**Comment by pyrello** [comment]
> @pyrello any more provisions or can this be approved/merged?

Just added one and waiting to hear back about one more.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
