### PR TITLE
Fix duplicate grad.uiowa.edu mentor credentials.

### LINKED ISSUE #3061: [Grad College] Mentor pages are showing credentials twice
# Problem
On mentor pages, the person's credentials are showing twice. I changed the way mentor page titles are generated to use the mentor's credentials, which is different than how other person type content types are handled.

# Steps to reproduce
https://grad.uiowa.edu/dei/srop/mentors/gordon-buchanan-md-phd

# Proposed solution
TBD

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3061 

### Testing
- Review code changes.
- `blt sync --site grad.uiowa.edu`
- Compare https://grad.local.drupal.uiowa.edu/dei/srop/mentors with https://grad.uiowa.edu/dei/srop/mentors
- Compare https://grad.local.drupal.uiowa.edu/dei/srop/mentors/gordon-buchanan with https://grad.uiowa.edu/dei/srop/mentors/gordon-buchanan

### CODE REVIEW

**Comment by richardbporter** [comment]
Are there any other displays of mentors that I'm not aware of?

**Comment by pyrello** [comment]
The listing page (https://grad.uiowa.edu/dei/srop/mentors) and detail pages for each mentor should be it.

**Comment by richardbporter** [comment]
Looking at some PHPCS warnings while I'm in here. Are these comments still needed?

https://github.com/uiowa/uiowa/blob/4c4c0aa37396a05b71c8434cdceb78ccb7478e7e/docroot/sites/grad.uiowa.edu/modules/grad_core/grad_core.module#L50-L54

**Comment by pyrello** [comment]
@richardbporter That is something left over from before launch. I thought I had come up with a way to not show the end date for the thesis defense content type, but then it was giving us problems during testing, so commented it out with the intention of returning to it eventually.

**Comment by pyrello** [comment]
Pulling down to test.

**Review by pyrello — APPROVED** [review]
Tested and works great! Thanks!

**Pull request merged**
