### PR TITLE
Grad College Thesis Defense Views

### LINKED ISSUE #2836: Create Thesis Defense calendar for Grad College
# Story

As a Grad College site owner I want to display a calendar of Thesis Defenses so that people involved in the process know when they are happening.

Existing page: https://www.grad.uiowa.edu/academics/thesis-and-dissertations/calendar

# Proposed solution

Build a view using the [fullcalendar module](https://www.drupal.org/project/fullcalendar) to display a monthly calendar display thesis defense content items.

### LINKED ISSUE #2837: Create upcoming Thesis Defense listing view
# Story

As a Grad College site owner I want display a list of upcoming Thesis Defenses so that interested parties can easily find out about them.

Existing page: https://www.grad.uiowa.edu/academics/thesis-and-dissertation/list

# Proposed solution

Build a view that displays a list of Thesis Defense teasers that have not occurred yet using the horizontal card style.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/2836
Resolves https://github.com/uiowa/uiowa/issues/2837

## To Test

Create thesis defense content (past dates, future dates) (https://grad.local.drupal.uiowa.edu/node/add/thesis_defense) and view the following pages: 

https://grad.local.drupal.uiowa.edu/academics/thesis-and-dissertation/list (should only show upcoming)
https://grad.local.drupal.uiowa.edu/academics/thesis-and-dissertation/calendar (items should render on calendar)

### CODE REVIEW

**Comment by joewhitsitt** [comment]
82c8f37 Temporarily comment out code that errors to allow for testing. Created follow-up issue.

https://github.com/uiowa/uiowa/issues/2899

**Comment by pyrello** [comment]
I noticed when testing this that, if I changed the date on a thesis defense which causes it to go from being in the past to in the future, that it still didn't show up on the upcoming list. That may just be a caching issue? Doesn't seem like a blocker to me, since it seems unlikely to come up much.

**Review by pyrello — APPROVED** [review]
Works very nicely. Will probably be some adjustments after I get it into the hands of the Academic Affairs team, but can follow up with other issues.

Thanks!

**Comment by joewhitsitt** [comment]
I couldn't replicate the past -> future date views issue. As an anonymous user, when the node was updated, the list view was updated even with an hour past/future change.

**Comment by pyrello** [comment]
Cool. I'd say we can leave this for now and see if anyone reports an issue.

**Pull request merged**
