### PR TITLE
OnIowa - JSON:API Events

### LINKED ISSUE #6363: OnIowa Event API for Hawktools app
# Story

As a Hawktools app owner, I would like to consume a JSON API/feed so that we can continue showing OnIowa events in the Hawktools app once we launch on SiteNow v3.

# Additional Info

**API for Hawktools**
We need to expose events in an API/feed for the Hawktools app to consume. Mark H. in CSI app dev group is the contact with questions about the feed.

I currently see the following on the existing site. I will confirm what is actually in use.
https://oniowa.uiowa.edu/api/hawktools/v1/events.json
https://oniowa.uiowa.edu/api/events.json
https://oniowa.uiowa.edu/api/highlighted.json

# Proposed Solution

- Expose endpoint at https://oniowa.uiowa.edu/api/hawktools/v1/events.json similarly to https://oniowa.prod.drupal.uiowa.edu/api/hawktools/v1/events.json

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/6363

# To Test

```
ddev composer install && ddev blt ds --site=oniowa.uiowa.edu
```

- Add some events (past, future, different moderation states)
- Go to https://oniowa.uiowa.ddev.site/api/node/event?include=field_event_category,field_image.field_media_image&sort=-field_event_when.value&jsonapi_include=1 both as an admin and as an anonymous user. As an anonymous user, you should only see the published ones. It should also display the content in chronological order.
- On first load it should probably take over 200 ms. On subsequent loads as anonymous, it should be under 100 ms. This indicates that the response is cached until the content changes.
- Compare the fields on https://oniowa.prod.drupal.uiowa.edu/api/hawktools/v1/events.json to see that the necessary values are available to consume. [As Brian said](https://github.com/uiowa/uiowa/issues/6363#issuecomment-1607720151), the structure and output can change but we will want to make this known to the developers (see API documentation/old API mapping below).
- Note that /api/node/article and other endpoints besides file, media image, event categories and event are not accessible. These were the minimum required to get this to work.

Screenshot 2023-06-26 at 3 54 56 PM

# OnIowa Events API

Endpoint URL: `/api/node/event`

## Query Parameters

Sort on date DESC: `sort=-field_event_when.value`
Include referenced content: `include=field_event_category,field_image.field_media_image`
Merge referenced content: `jsonapi_include=1`

Example: `/api/node/event?include=field_event_category,field_image.field_media_image&sort=-field_event_when.value&jsonapi_include=1`

## Common Attributes

- `drupal_internal__nid` - Node ID (unique)
- `title` - Content title
- `field_event_attendance` - Attendance required
- `field_event_category` - Collection of referenced event category terms. (Assumes `jsonapi_include=1`)
    - `name` - Event category name
- `field_image` - Container of event image information. (Assumes `jsonapi_include=1`)
    - `field_media_image`
        - `uri`
            - `url` - Relative path to image
- `field_teaser` - Short description of content
- `body` - Container of long description content.
    - `value` - Long description value
- `field_event_when` - Container of event date information.
    - `value` - Start date of event (ISO 8601 format)
    - `end_value` - End date of event (ISO 8601 format)
- `field_event_location` - Container of address information.
    - `organization` - Location name
    - `address_line1` - Street address
    - `locality` - City
    - `administrative_area` - State
    - `postal_code` - Zipcode
- `field_event_geolocation` - Container of geolocation information.
    - `lat` - Latitude
    - `lon` - Longitude
- `field_event_status` - Status of event (`EventScheduled`, `EventCancelled`, `EventRescheduled`)
- `field_event_attendance_mode` - Attendance format (`OfflineEventAttendanceMode`, `MixedEventAttendanceMode`, `OnlineEventAttendanceMode`) 

## API Mapping from Hawktools V1 API

```csv
hawktools_v1,sitenow_v3
events[id],data[drupal_internal__nid]
events[title],data[title]
events[required],data[field_event_attendance]
events[categories],data[field_event_category]
events[image],data[field_image][field_media_image][uri][url]
events[description],data[field_teaser]
events[long_description],data[body][value]
events[start date],data[field_event_when][value]
events[end date],data[field_event_when][end_value]
events[location],data[field_event_location][organization]
events[lat],data[field_event_geolocation][lat]
events[long],data[field_event_geolocation][lon]
events[status],data[field_event_status]
events[event type],data[field_event_attendance_mode]
```

_Note: `events[address]` is now split up within `data[field_event_location]` (address_line1, locality, administrative_area, postal_code)._

<details>
<summary>Example output</summary>

```json
{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    },
    "parsed": true
  },
  "data": [
    {
      "type": "node--event",
      "id": "41662660-487b-4d39-96a8-d7ec8a4d4ad9",
      "links": {
        "self": {
          "href": "https://oniowa.uiowa.ddev.site/api/node/event/41662660-487b-4d39-96a8-d7ec8a4d4ad9?resourceVersion=id%3A802"
        }
      },
      "drupal_internal__nid": 106,
      "status": true,
      "title": "Published Upcoming",
      "body": {
        "value": "<p>Long description</p>\r\n",
        "format": "filtered_html",
        "processed": "<p>Long description</p>",
        "summary": ""
      },
      "field_event_attendance": true,
      "field_event_attendance_mode": "OfflineEventAttendanceMode",
      "field_event_geolocation": {
        "value": "POINT (-91 41)",
        "geo_type": "Point",
        "lat": 41,
        "lon": -91,
        "left": -91,
        "top": 41,
        "right": -91,
        "bottom": 41,
        "geohash": "9zr31p",
        "latlon": "41,-91"
      },
      "field_event_hide": false,
      "field_event_location": {
        "langcode": null,
        "country_code": "US",
        "administrative_area": "IA",
        "locality": "Iowa City",
        "dependent_locality": null,
        "postal_code": "52246",
        "sorting_code": null,
        "address_line1": "Address goes here",
        "address_line2": "",
        "organization": "Location name",
        "additional_name": null
      },
      "field_event_status": "EventScheduled",
      "field_event_virtual": null,
      "field_event_when": {
        "value": "2023-06-27T15:00:00+00:00",
        "end_value": "2023-06-27T16:00:00+00:00",
        "duration": 60,
        "rrule": null,
        "rrule_index": null,
        "timezone": ""
      },
      "field_teaser": "Short description",
      "field_event_category": [
        {
          "type": "taxonomy_term--event_categories",
          "id": "9da3059a-a9f5-46fa-badb-e526ff4923f0",
          "links": {
            "self": {
              "href": "https://oniowa.uiowa.ddev.site/api/taxonomy_term/event_categories/9da3059a-a9f5-46fa-badb-e526ff4923f0?resourceVersion=id%3A12"
            }
          },
          "drupal_internal__tid": 12,
          "name": "shopping",
          "meta": {
            "drupal_internal__target_id": 12
          }
        },
        {
          "type": "taxonomy_term--event_categories",
          "id": "4efdc370-aa47-4b8a-9a46-bc24433b0b06",
          "links": {
            "self": {
              "href": "https://oniowa.uiowa.ddev.site/api/taxonomy_term/event_categories/4efdc370-aa47-4b8a-9a46-bc24433b0b06?resourceVersion=id%3A13"
            }
          },
          "drupal_internal__tid": 13,
          "name": "other",
          "meta": {
            "drupal_internal__target_id": 13
          }
        }
      ],
      "field_image": {
        "type": "media--image",
        "id": "2704f3ba-3d6b-43b1-b597-2fa255eab792",
        "links": {
          "self": {
            "href": "https://oniowa.uiowa.ddev.site/api/media/image/2704f3ba-3d6b-43b1-b597-2fa255eab792?resourceVersion=id%3A376"
          }
        },
        "drupal_internal__mid": 376,
        "meta": {
          "drupal_internal__target_id": 376
        },
        "field_media_image": {
          "type": "file--file",
          "id": "04b895e0-4a57-4b0f-a62a-9c5f22161a52",
          "links": {
            "self": {
              "href": "https://oniowa.uiowa.ddev.site/api/file/04b895e0-4a57-4b0f-a62a-9c5f22161a52"
            }
          },
          "drupal_internal__fid": 396,
          "uri": {
            "value": "public://2023-06/IMG_9105.jpeg",
            "url": "/sites/oniowa.uiowa.edu/files/2023-06/IMG_9105.jpeg"
          },
          "meta": {
            "alt": "On Iowa leader group photo",
            "title": "",
            "width": 2952,
            "height": 1960,
            "drupal_internal__target_id": 396
          }
        }
      }
    },
    {
      "type": "node--event",
      "id": "04b57a8d-da3e-40fc-b22e-ec6384b7afb1",
      "links": {
        "self": {
          "href": "https://oniowa.uiowa.ddev.site/api/node/event/04b57a8d-da3e-40fc-b22e-ec6384b7afb1?resourceVersion=id%3A804"
        }
      },
      "drupal_internal__nid": 110,
      "status": true,
      "title": "Now Event",
      "body": null,
      "field_event_attendance": false,
      "field_event_attendance_mode": "OfflineEventAttendanceMode",
      "field_event_geolocation": null,
      "field_event_hide": false,
      "field_event_location": null,
      "field_event_status": "EventScheduled",
      "field_event_virtual": null,
      "field_event_when": {
        "value": "2023-06-26T20:00:00+00:00",
        "end_value": "2023-06-26T21:00:00+00:00",
        "duration": 60,
        "rrule": null,
        "rrule_index": null,
        "timezone": ""
      },
      "field_teaser": null,
      "field_event_category": {
        "data": [],
        "links": {
          "related": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/04b57a8d-da3e-40fc-b22e-ec6384b7afb1/field_event_category?resourceVersion=id%3A804"
          },
          "self": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/04b57a8d-da3e-40fc-b22e-ec6384b7afb1/relationships/field_event_category?resourceVersion=id%3A804"
          }
        }
      },
      "field_image": {
        "data": null,
        "links": {
          "related": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/04b57a8d-da3e-40fc-b22e-ec6384b7afb1/field_image?resourceVersion=id%3A804"
          },
          "self": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/04b57a8d-da3e-40fc-b22e-ec6384b7afb1/relationships/field_image?resourceVersion=id%3A804"
          }
        }
      }
    },
    {
      "type": "node--event",
      "id": "f72ff4a7-2d9e-4879-a0eb-cf1061dd4146",
      "links": {
        "self": {
          "href": "https://oniowa.uiowa.ddev.site/api/node/event/f72ff4a7-2d9e-4879-a0eb-cf1061dd4146?resourceVersion=id%3A803"
        }
      },
      "drupal_internal__nid": 109,
      "status": true,
      "title": "Old Event",
      "body": null,
      "field_event_attendance": false,
      "field_event_attendance_mode": "OfflineEventAttendanceMode",
      "field_event_geolocation": null,
      "field_event_hide": false,
      "field_event_location": null,
      "field_event_status": "EventScheduled",
      "field_event_virtual": null,
      "field_event_when": {
        "value": "2023-03-01T20:00:00+00:00",
        "end_value": "2023-03-01T21:00:00+00:00",
        "duration": 60,
        "rrule": null,
        "rrule_index": null,
        "timezone": ""
      },
      "field_teaser": null,
      "field_event_category": {
        "data": [],
        "links": {
          "related": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/f72ff4a7-2d9e-4879-a0eb-cf1061dd4146/field_event_category?resourceVersion=id%3A803"
          },
          "self": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/f72ff4a7-2d9e-4879-a0eb-cf1061dd4146/relationships/field_event_category?resourceVersion=id%3A803"
          }
        }
      },
      "field_image": {
        "data": null,
        "links": {
          "related": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/f72ff4a7-2d9e-4879-a0eb-cf1061dd4146/field_image?resourceVersion=id%3A803"
          },
          "self": {
            "href": "https://oniowa.uiowa.ddev.site/api/node/event/f72ff4a7-2d9e-4879-a0eb-cf1061dd4146/relationships/field_image?resourceVersion=id%3A803"
          }
        }
      }
    }
  ],
  "links": {
    "self": {
      "href": "https://oniowa.uiowa.ddev.site/api/node/event?include=field_event_category%2Cfield_image.field_media_image&jsonapi_include=1&sort=-field_event_when.value"
    }
  }
}
```
</details>

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested this with lots of combos of moderation state shenanigans, and it all worked great! Data presented looks to match the old endpoint in what's available, so if they can work with the documented changes to where each bit lives, I think we are good to go.

**Comment by joewhitsitt** [comment]
Thanks for the technical approval. I am going to switch it back to draft until we hear back from the hawktools developers.

**Comment by joewhitsitt** [comment]
Going to send this out to DEV for testing

**Comment by joewhitsitt** [comment]
This is out on DEV. Created an additional event to flush out more details for testing. https://oniowa.dev.drupal.uiowa.edu/api/node/event?include=field_event_category,field_image.field_media_image&sort=-field_event_when.value&jsonapi_include=1

**Comment by joewhitsitt** [comment]
Jeremy has mapped all of the changes in their events application. I think this can be merged and deployed now for further testing.

**Pull request merged**
