### PR TITLE
Event Feature - Event Status

### LINKED ISSUE #5939: As a site editor, I can designate the EventStatus of a local event as Active, Cancelled, or Rescheduled.
# Story

As a site editor, I can designate the EventStatus of a local event as Active, Cancelled, or Rescheduled to inform viewers of the status of an event.

[https://schema.org/eventStatus](https://schema.org/eventStatus) - This is the schema.org property defined for the status of the event.

Screen Shot 2022-11-10 at 11 27 31 PM

# Proposed solution

- Add a new field_event_status field to the local event type at the default level.
- Attach field value to schema.org property "eventStatus".
- ~Does this need to carry over to all "child" or "subEvents" within the updated event???~ - No
- Output badge for rescheduled and cancelled using a single color badge on teasers and entity

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/5939

Screenshot 2023-04-21 at 3 23 28 PM
Screenshot 2023-04-21 at 3 22 16 PM
Screenshot 2023-04-21 at 3 22 28 PM

# How to test

## Test update hook

```
ddev blt ds --site=admissions.uiowa.edu && ddev drush @admissions.local uli node/7166/edit
```
Check that is has a value of Scheduled for the required field. The update hook itself should only run for sites that have the event split enabled. Feel free to test against another site like uiowa.edu

- Test default (event split), iswf, oniowa, admissions for event status functionality. Defaults to "scheduled" and is rendered on the full event node as well as the teaser. Inspect the full node source for event status schema information.
Confirm that https://github.com/uiowa/uiowa/pull/6372/commits/3075ff7639375484b17b08aa72d5ffd051c1cb95 should be added to allow articles/people the list/grid option on Admissions.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Having troubles with the Admissions export. It wants to delete the complete item and replace it a split file containing some unfamiliar bits like `config_split_sequence_3qhidpsnp2a996q5`:

```yaml
adding:
  dependencies:
    config:
      - field.field.node.event.field_event_category
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_settings:
            layout_builder_styles_style:
              - section_order_reversed
          components:
            config_split_sequence_3qhidpsnp2a996q5:
              weight: 2
            config_split_sequence_qvegmgm51mppsmnc:
              weight: 3
            config_split_sequence_asle1hi593u2nvkj:
              region: first
              configuration:
                layout_builder_styles:
                  - content_alignment_left
                  - list_format_list
...
```

**Comment by joewhitsitt** [comment]
Hoping @pyrello can ease my mind a bit with this Admissions split. Is this from https://www.drupal.org/node/3279331 and the fact that Admissions has like four splits turned on?

**Comment by pyrello** [comment]
> Hoping @pyrello can ease my mind a bit with this Admissions split. Is this from https://www.drupal.org/node/3279331 and the fact that Admissions has like four splits turned on?

Yes. Not sure why it is insisting on a partial split instead of a complete split though. I think I ran into something similar with events the last time I was working on it, debugged it, and then ended up either updating the the config manually or manually removing elements that shouldn't be there.

Maybe I opened this issue at the time? https://www.drupal.org/project/config_split/issues/3349737

**Comment by e-marie-w** [comment]
I forgot, is the /events page supposed to not show super events?

**Comment by joewhitsitt** [comment]
>I forgot, is the /events page supposed to not show super events?

I don't recall. I don't think this PR touches any of that functionality.

**Comment by joewhitsitt** [comment]
#5931 looks like the idea of not showing parent events were an ISWF feature.

>Just filtered events that are not referenced as a parent. So, if there are multiple types this applies to, the view might need to look at certain relationships ("lowest layer")

Not sure what was decided in the end.

**Review by e-marie-w — APPROVED** [review]
Event status appears on node and teaser, as well as in schema information. Tested for default, ISWF, OnIowa, and Admissions. Also, grid option is now working for article and people listblocks on Admissions. 

I was worried about existing events, but they still work and will just require a status upon next edit. I have a few questions about the events feature in general, but they're unrelated to this functionality so I'm approving.

**Comment by pyrello** [comment]
> I was worried about existing events, but they still work and will just require a status upon next edit. I have a few questions about the events feature in general, but they're unrelated to this functionality so I'm approving.

@joewhitsitt Is there a reason we are not doing an update hook on this to get our data matching the expected schema?

**Comment by e-marie-w** [comment]
I assumed because there's only one existing event on a live site and only seven on internal prod domains.

**Comment by joewhitsitt** [comment]
>@joewhitsitt Is there a reason we are not doing an update hook on this to get our data matching the expected schema?

No particular reason. 

>I assumed because there's only one existing event on a live site and only seven on internal prod domains.

This is probably part of it. Also that no other code is acting on whether or not it is set. Didn't think too much about it.

I will put something together.

**Comment by e-marie-w** [comment]
>  looks like the idea of not showing parent events were an ISWF feature.

Okay cool I missed that happening. It's also part of default but can be changed if needed, because Admissions shows all events. 

Other not-event-status-but-event-feature thing that confused me is that ongoing, in-progress events don't display in the events listblock. I'm going to double-check I can recreate it and then create an issue for bug smash if so.

**Comment by pyrello** [comment]
> This is probably part of it. Also that no other code is acting on whether or not it is set. Didn't think too much about it.
>
> I will put something together.

I didn't realize there were not very many records. Its probably not worth it. Just double-checking.

**Comment by joewhitsitt** [comment]
I think it is a good habit to get into to. Going to see if I can lift and repurpose something real quick.

**Comment by joewhitsitt** [comment]
Updated the test instructions for the update hook

**Comment by e-marie-w** [comment]
Pulling down to test update hook.

**Review by e-marie-w — APPROVED** [review]
Update hook works as expected, thanks for adding that!

**Comment by pyrello** [comment]
🤣 An update hook with batching!

**Pull request merged**
