### PR TITLE
Feature: Colleges field for area of study

### LINKED ISSUE #3081: College link on Areas of Study should link to a page with other areas of study for that college.
The existing admissions website has a taxonomy for Colleges that contains additional information about the college including title, text, photo, link to college website and areas of study for that college. They would like something similar on their new site. The link to the College page can be output as the first item of the related links section.

https://admissions.uiowa.edu/colleges/college-liberal-arts-sciences

# Proposed solution
- [ ] Add an entity reference field labeled college to the Area of Study content type
- [ ] Must be in the correct form order https://github.com/uiowa/uiowa/issues/3108
- [ ] Create a view with the following constraints:
  - [ ] Filtered to just nodes of type Area of Study
  - [ ] Contextual reference limiting to just Area of Study items that reference a particular page node
  - [ ] Set contextual reference to get the node ID from the current page
  - [ ] Create a block display

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3081. 

# How to test

1. `blt ds --site=admissions.uiowa.edu`
2. `yarn workspace admissions_core build`
3. Reference "College of Liberal Arts & Sciences" in the "College" field on http://admissions.local.drupal.uiowa.edu/academics/art
4. Verify that the college name shows up in the "Links" sidebar block on http://admissions.local.drupal.uiowa.edu/academics/art. 
4. Go to http://admissions.local.drupal.uiowa.edu/college-liberal-arts-sciences and add the "Area of Study College Block" view to the page.  Save the page and the view reference block should appear on the page. 

## Also snuck in a spacing/size fix for the information view sidebar:

Without descriptions:

Screen Shot 2021-03-03 at 12 29 56 PM

With descriptions:

Screen Shot 2021-03-03 at 12 30 52 PM

### CODE REVIEW

**Comment by pyrello** [comment]
FWIW, I tested this and was satisfied with it. I also worked on the code though, so will wait for another approver :)

**Comment by pyrello** [comment]
Need to move the college links to the top of the list.

**Comment by pyrello** [comment]
I think this should be working per customer request now.

**Comment by bspeare** [comment]
I also added a spacing fix for the information sidebar block that I documented with screenshots in the testing instructions.

**Review by pyrello — APPROVED** [review]
Between @bspeare and I we feel this is tested enough :)

**Pull request merged**
