### PR TITLE
Provision afamstudies, amstudies, and naistudies CLAS sites.

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Provision the following three CLAS sites:

- africanamericanstudies.uiowa.edu
- americanstudies.uiowa.edu
- nativeamericanstudies.uiowa.edu

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Not sure what this means, but I don't think we can merge this in quite yet

```
There was 1 failure:
1) Drupal\Tests\sitenow\Unit\FilesystemTest::testMultisiteFiles
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'self'
+'africanamericanstudies.uiowa.edu.local'
/home/travis/build/uiowa/uiowa/docroot/core/tests/Drupal/TestTools/PhpUnitCompatibility/PhpUnit7/TestCompatibilityTrait.php:53
/home/travis/build/uiowa/uiowa/tests/phpunit/src/Unit/FilesystemTest.php:132```

**Comment by mark-bennett-uiowa** [comment]
Yeah, not sure how the heck this error occurred. 

```
git checkout master
git pull
composer install
blt frontend
git checkout -b feature_provision_clas_sites
blt umc africanamericanstudies.uiowa.edu (chose uiowa01)
blt umc americanstudies.uiowa.edu (chose uiowa01)
blt umc nativeamericanstudies.uiowa.edu (chose uiowa01)
```
Saw that all three added and committed their changes.
`git push -u origin feature_provision_clas_sites`
Created PR. Saw it was out of date with master already somehow, merged in master, and travis failed.

Did any of the ITS staff get these errors on their latest provisions? Or is this due to the changes in the provision process without collegiate profile? Is this because I reused a branch name that I used before?

**Comment by richardbporter** [comment]
My bad. Regressions from #1477.

**Review by richardbporter — APPROVED** [review]

**Comment by mark-bennett-uiowa** [comment]
No worries. Its my M.O. to break things somehow, so I just wanted to make sure it wasnt something I was doing wrong.

**Pull request merged**
