### PR TITLE
Feature: Fix for featured content grids 

### LINKED ISSUE #1970: Flex display issue with featured content grid and sidebar
## Problem

The flex styles are not responding to having a sidebar on desktop.

https://iti.uiowa.edu/our-people/staff

Screen Shot 2020-07-21 at 3 19 01 PM

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/1970. 

# How to test

Add featured content grid, events grid, articles grid, and a people grid to a page with a sidebar menu.  Test at all breakpoints with and without the sidebar.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Pulling this down for testing. Going to sneak in a change for ighn.international which used some of the same styles.

**Comment by joewhitsitt** [comment]
This solves it for sidebar pages but not for pages without. There is a difference in padding and then extra on the end. See the iti.local.drupal.uiowa.edu homepage. Mix of cards and articles:

Screen Shot 2020-07-22 at 4 39 10 PM

**Comment by bspeare** [comment]
@joewhitsitt Thanks for testing.  I'll do some further testing on this.

**Comment by bspeare** [comment]
@joewhitsitt could you review again?

**Comment by joewhitsitt** [comment]
pulling down for testing

**Review by joewhitsitt — APPROVED** [review]
Thanks for your work on this. Tested on IE Desktop as well. Added ighn.international specific fixes.

**Comment by bspeare** [comment]
@joewhitsitt Thanks!

**Pull request merged**
