### PR TITLE
[Bug] Spacing fix for grids and lists

### LINKED ISSUE #7135: Admissions - Student Profiles Grid Block display issue
# Problem
Grid display for student profiles on admissions is malfunctioning.

Screenshot 2023-11-27 at 2 22 03 PM

# Steps to reproduce
- [ ] Go to https://admissions.uiowa.edu/student-profiles and click into one of the profiles. See the broken grid display.

# Proposed solution
?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7135

This pr adds the `list-container--list` class to views meant to display as lists ensuring proper spacing between each card. 

# How to test

```
ddev blt frontend && ddev blt ds --site=admissions.uiowa.edu && ddev drush @admissions.local uli /student-profiles/ainsley-hiestand
```
- Confirm sidebar grid renders without spaces
- Go to https://admissions.uiowa.ddev.site/international-student-ambassadors and confirm no visual regressions.  Try adjusting to list and confirm that space between each card is added. 
- Go to /counselors, /news, /tags/admissions-website, enable /admin/config/sitenow/sitenow-people & /counselor add two events and go to /events and confirm spacing

Code review and think of any that I may have missed in exclusion list.

### CODE REVIEW

**Comment by e-marie-w** [comment]
Spacing is looking good for everything. When testing /events I noticed that events marked as 'Attendance Required' do not appear in the upcoming list. If I switch to calendar I can see them as expected. I'm going to pull down main to check if it is an existing bug or actually caused by this PR.

**Comment by e-marie-w** [comment]
> When testing /events I noticed that events marked as 'Attendance Required' do not appear in the upcoming list. If I switch to calendar I can see them as expected. I'm going to pull down main to check if it is an existing bug or actually caused by this PR.

I checked main, this is also happening there. I'll create a bug issue for it and approve this PR since it's unrelated.

**Review by e-marie-w — APPROVED** [review]
Sidebar grid now renders correctly. No visual regressions and spacing as expected for other lists.

**Comment by bspeare** [comment]
Thanks @e-marie-w !

**Pull request merged**
