### PR TITLE
Feature: Event Series content type

### LINKED ISSUE #4018: Create "Event series" content type
# Story 

As an editor, I can create an Event series page that pulls in published upcoming event content dates referencing it and is sorted chronologically.

# Proposed Solution

- Create "Event series" content type
  - [ ] Layout template that is similar to Hawkeye Visit Days content
  - [ ] I doubt we can reliably output the general time summary of all event instances, so providing a "Series schedule summary" long text that captures this would be suitable.
  - [ ] Block that pulls in published upcoming event content dates referencing it (contextual filter on content id) and is sorted chronologically. If linked, this is the one instance where it should link to the event instance.
  - [ ] ~~[EventSeries](https://schema.org/EventSeries) information captured and mapped to the related SEO settings by way of https://www.drupal.org/project/eva or entityQuery collecting details for the subEvent and pulling in event instances meta info. Use hook_metatags_alter() to set. Consider keeping these Schema Event defaults from being overridden by webmasters but still allowing other meta information to be editable.~~ Based on https://github.com/uiowa/uiowa/issues/4018#issuecomment-904720492

### PR DESCRIPTION
**Pull request by bspeare**
Resolves #4018

- [x] Unlink dates on event series
- [x] Admissions default nofollow robots settings for event, event series
- [x] Change summary field label and add clock icon to render

# How to test
`blt ds --site=admissions.uiowa.edu`
`yarn workspace uids_base build`
`drush @admissions.local uli`
- Add an event series and test out the fields (https://admissions.local.drupal.uiowa.edu/node/add/event_series)
  - Verify that nofollow is the default metatag setting for each page
  - Verify that webmaster, publisher, and editor can create a new page
- Add multiple events and (https://admissions.local.drupal.uiowa.edu/node/add/event) reference the event series page using the event series link field. 
  - Verify that nofollow is the default metatag setting for each page

**Story test**
As an editor, I can create an Event series page that pulls in published upcoming event content dates referencing it and is sorted chronologically.

<details>
Screen Shot 2021-08-25 at 3 44 42 PM
</details>

### CODE REVIEW

**Comment by GaryRidgway** [comment]
I was able to add event series:  
   - And have nofollow as the default metatag setting for each page
- And I verified that webmaster, publisher, and editor can create them


I added multiple events and referenced the event series page using the event series link field.
   - And have nofollow as the default metatag setting for each page

I did however find that the "Link directly to source" did not create any links for the event listing page.


<details>
<summary>I also found styling artifacts from the `li` of the listing events</summary>
Screen Shot 2021-08-25 at 4 21 53 PM
</details>


I Observed this with 1 and 3 events, but I am convinced that it would occur at any number of events.

**Comment by bspeare** [comment]
> I did however find that the "Link directly to source" did not create any links for the event listing page.

I forgot to mention that the link directly to source will only work with items listed on https://admissions.local.drupal.uiowa.edu/events.   Is that what you meant?

> I also found styling artifacts from the `li` of the listing events

Did you run `yarn workspace uids_base build` and clear the site cache?  It looks good for me in Opera :)

**Comment by bspeare** [comment]
@GaryRidgway You also might try `blt frontend` or the list of commands below to see if you have the most up to date version of UIDS:
```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
drush @admissions.local cr
```

**Comment by GaryRidgway** [comment]
@bspeare after doing all three things, it finally worked lol. approved!

**Review by GaryRidgway — APPROVED** [review]

**Pull request merged**
