### PR TITLE
[Bug] Iowa bar fixes

### LINKED ISSUE #1253: Regression with search bar + vertical toolbar
Screen Shot 2020-03-24 at 4 34 21 PM

Regression introduced in #1236.

# Proposed solution

Create a new `iowa-bar-admin` partial file for `admin.scss` targeting `.toolbar-vertical.toolbar-tray-open` to adjust the styles to work with the vertical toolbar.

### LINKED ISSUE #6244: Horizontal scroll on toggle
# Problem
When at full width on desktop, having a toggle menu makes a page horizontally scroll.

# Steps to reproduce
Turn on toggle menu, scroll right on homepage

# Proposed solution
figure out spacing solutions?

Related to https://github.com/uiowa/uiowa/issues/6245

### LINKED ISSUE #6245: Search button spacing is not correct.
# Problem
When in the admin interface, having the dropdown admin navigation menu open moves the search field. This could also be causing problems with the Toggle menu horizontal scroll. Turning off its positioning fixes the horizontal scroll.

# Steps to reproduce
Open admin interface, use dropdown menu, observe search button.

# Proposed solution
Try different positioning techniques.

<details><summary>Example gif 1</summary>
<p>

</p>
</details> 

<details><summary>Example gif 2</summary>
<p>

</p>
</details> 

Related to https://github.com/uiowa/uiowa/issues/6244

### LINKED ISSUE #6247: Toggle menu sticky positioning.
# Problem
The toggle menu jumps out of the flow of the page when scrolling up when set to sticky and with site name below the top bar.
ezgif com-gif-maker (1)

Additionally, opening the toggle menu when scrolled opens it over the button.
Screenshot 2023-03-07 at 11 50 51 AM

# Steps to reproduce
Turn on toggle menu with it below the top bar. Scroll down and then up, watching the toggle menu.

# Proposed solution
change positioning of toggle menu?

Possibly related to https://github.com/uiowa/uiowa/issues/6245 and https://github.com/uiowa/uiowa/issues/6244

### LINKED ISSUE #6673: Regents theme bug for Iowa bar
# Problem
**Toggle menu is off with a parent organization**

Screenshot 2023-07-13 at 3 01 58 PM

### PR DESCRIPTION
**Pull request by bspeare**
UIDS pr: https://github.com/uiowa/uids/pull/887

# How to test

- Code review
- When testing, test out all the header options in /appearance and the search toggle. 

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli people-directory
```

#### Test header with vertical/horizontal admin toolbar while logged **IN**
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "toggle navigation style"
- Set site name display with the IOWA bar and after that test with site name below IOWA Bar:
  - Toggle "Manage" button for both vertical and horizontal options
    - Does "Menu" toggle keep up with a correct position?
  - Resize browser from small width to large
    - Does "Menu" toggle keep up with a correct position?
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "sticky" and run through the steps above again. 
- Vertical toolbar only testing
  - Test that "Search" doesn't get squished into the top links
    - Move browser width small to very large and test the search toggle. 
- Use the pager on the /people page - then try the toggle nav and search toggle - do they still work? 

#### Test header while logged **OUT**
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "toggle navigation style"
- Set site name display with the IOWA bar and after that test with site name below IOWA Bar:
  - Toggle "Manage" button for both vertical and horizontal options
    - Does "Menu" toggle keep up with a correct position?
  - Resize browser from small width to large
    - Does "Menu" toggle keep up with a correct position?
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "sticky" and run through the steps above again. 
- Use the pager on the /people page - then try the toggle nav and search toggle - do they still work? 

## "Regents" theme
Switch theme style to "Gray" at https://sandbox.uiowa.ddev.site/admin/appearance/settings/uids_base. 
#### Test header with vertical/horizontal admin toolbar while logged **IN**
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "toggle navigation style"
- Set site name display with the IOWA bar and after that test with site name below IOWA Bar:
  - Toggle "Manage" button for both vertical and horizontal options
    - Does "Menu" toggle keep up with a correct position?
  - Resize browser from small width to large
    - Does "Menu" toggle keep up with a correct position?
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "sticky" and run through the steps above again. 
- Vertical toolbar only testing
  - Test that "Search" doesn't get squished into the top links
    - Move browser width small to very large and test the search toggle. 

#### Test header while logged **OUT**
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "toggle navigation style"
- Set site name display with the IOWA bar and after that test with site name below IOWA Bar:
  - Toggle "Manage" button for both vertical and horizontal options
    - Does "Menu" toggle keep up with a correct position?
  - Resize browser from small width to large
    - Does "Menu" toggle keep up with a correct position?
- Set https://sandbox.uiowa.ddev.site/admin/appearance to "sticky" and run through the steps above again. 

## Regents theme bug for Iowa bar
Resolves https://github.com/uiowa/uiowa/issues/6673
## Toggle menu sticky positioning
Resolves https://github.com/uiowa/uiowa/issues/6247
## Regression with search bar + vertical toolbar
Resolves https://github.com/uiowa/uiowa/issues/1253

## Horizontal scroll on toggle
Resolves https://github.com/uiowa/uiowa/issues/6244
- Happens only on toggle nav without "sticky" enabled. 

## Search button spacing is not correct
Resolves https://github.com/uiowa/uiowa/issues/6245

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Pulling to review

**Comment by GaryRidgway** [comment]
More potential bugs? (Not relevant for this slice, just thought I would log them)

<details><summary>Search and secondary links are colliding / stacking</summary>
<p>

</p>
</details>

**Comment by bspeare** [comment]
@GaryRidgway those are relevant, I don't think there's a great solution there because of how the claro vertical toolbar works.  You can max out the characters for the top menu links and completely overflow the menu bar as well.  If we switched to something like the Gin theme, we would not have to deal with this type of positioning.

**Comment by pyrello** [comment]
> More potential bugs? (Not relevant for this slice, just thought I would log them)

I think we should make note of these for future improvements. They don't look like dealbreakers to me.

**Review by GaryRidgway — APPROVED** [review]
I reviewed this to the best of my abilities for both the iowa and regents theme, checking as many of the things listed as possible, and it seems that they are all good!

**Comment by bspeare** [comment]
Thanks for testing @GaryRidgway!

**Pull request merged**
