### PR TITLE
Find Text - basic permissions test

### LINKED ISSUE #4589: Taxonomy term content search in SiteNow Find Text
# Problem
Taxonomy content is not currently visible to the Find Text module (ie a search for "Space" won't return results for taxonomy terms labeled "space" or that include "space" in their description).

# Proposed solution

Increase the scope of `sitenow_find_text` to include text-based fields which are used by taxonomy terms.

### PR DESCRIPTION
**Pull request by cory-skeers**
Adds additional functionality to the Find Text module (taxonomy term searching) as well as several tests to aid in future development.

Resolves #4589 

# How to test

- `git checkout find-text-tests && git pull`
- Manually run the `sitenow_find_text` tests that have been added
   - https://github.com/uiowa/uiowa/tree/main/tests
   - All tests should pass. For extra thoroughness, you can "break" functionality and check that the tests no longer work. For instance, rename the page permission in the permissions yml, break a case statement in `get_text_field_tables` and see that the related entity tests break, etc.
- Check that the latest Travis CI build passed successfully
- Sync a site that has taxonomy terms, or create some new taxonomy terms
- Try searching for terms that will match taxonomy term names and/or descriptions, see that they appear in the results
- Try searching for a menu and node content, and see that they still appear in the results

### CODE REVIEW

**Comment by richardbporter** [comment]
Nice!

Right now, every test of ours needs to be defined in `phpunit.xml.dist` as a `testsuite` so it runs whenever `phpunit` is run without a path argument: https://github.com/uiowa/uiowa/blob/20e013b8729c4b0e65330d55718e6a3ebc4710f4/phpunit.xml.dist#L25-L41

Also, I think this test will be skipped in our CI environment until #4546 is merged.

**Comment by cory-skeers** [comment]
> Right now, every test of ours needs to be defined in `phpunit.xml.dist` as a `testsuite` so it runs whenever `phpunit` is run without a path argument:

Awesome--thanks! Will likely have some questions about that and reach out. Still need to tweak the second test I added to get it working.

**Comment by GaryRidgway** [comment]
I had all of the tests fail for me sadly.

**Comment by cory-skeers** [comment]
Not sure why, but they're failing on `$this->drupalLogin($this->user);` now, which hadn't been a problem before. But since they're all dependent on a user being able to log in and see the page, they all use this.

**Comment by cory-skeers** [comment]
When `$this->drupalLogin($this->user)` runs, it's failing with the exception `"Button with id|name|label|value \"Log in\" not found."`

**Comment by joewhitsitt** [comment]
How might this test be different than PeopleBlockViewTest and ConfigSplitTestTrait in terms of login?

**Comment by cory-skeers** [comment]
> How might this test be different than PeopleBlockViewTest and ConfigSplitTestTrait in terms of login?

Just tested PeopleBlockViewTest locally and it failed on the `drupalLogin` as well.

Changing `simpletest-base-url:` to 'https://default.uiowa.ddev.site' gets the user login working correctly, but leads to failures accessing other pages later in tests...

**Comment by cory-skeers** [comment]
Reverting ae883997e7235407a4ff2505e7a2d23c0ad16cfb, the tests pass, so it looks to be related to the change to `apache`.

**Comment by cory-skeers** [comment]
Updated the tests README with different "simpletest-base-url" value that should allow for these and other tests to be run locally.

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
`OK (5 tests, 56 assertions)`

Tested on Admissions and it all checks out

Possible future enhancements:

- limit to specific type
- result stats like "3 content instances, 2 taxonomy instances, 1 menu instance"

both would help encourage the user to keep scrolling to the end

**Comment by cory-skeers** [comment]
Thanks @joewhitsitt!

**Pull request merged**
