### PR TITLE
[Event feature] Removed menu entry for /events

### PR DESCRIPTION
**Pull request by bspeare**
```
ddev blt ds --site=oniowa.uiowa.edu
```
```
ddev blt ds --site=iowasummerwritingfestival.uiowa.edu
```

Verify in the main menu settings (https://iowasummerwritingfestival.uiowa.ddev.site/admin/structure/menu/manage/main)  that there is no entry for "Events"

### CODE REVIEW

**Comment by joewhitsitt** [comment]
testing locally

**Review by joewhitsitt — APPROVED** [review]
checks out

**Comment by briand44** [comment]
Can someone help me understand how this is going to affect iowasummerwritingfestival.org? Is the menu going to disappear and they will need to create a new menu item? Will the menu item stay unchanged as it is now with the same menu text?

**Comment by joewhitsitt** [comment]
during testing the "Search Workshops" that points at /events remained

**Comment by bspeare** [comment]
@briand44 I added a separate menu entry for "Search workshops".

**Comment by briand44** [comment]
Thanks @bspeare!

**Pull request merged**
