### PR TITLE
Role-based content access per content type

### LINKED ISSUE #3723: Role-based content access per content type
# Motivation

Provide a system for setting up a content type to allow access based on roles.

# Potential solution

* Add the [node_view_permissions](https://www.drupal.org/project/node_view_permissions) to default profile.
* Set default permissions for default content types.
* Propagate new permissions in each config split that has `user.role.*` configuration items included.

### LINKED ISSUE #3783: SPPA - Set opportunity content type to only be viewable by authenticated users
Story: As an SPPA site owner, I want to keep the Opportunity content type behind a HawkID login so that only current students and alumni can access them.

# Proposed solution
Use the changes made in #3723 to limit viewing the opportunity content type to authenticated users.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3723 
Closes #3783 

# How to test

Will need to check multiple different sites (v2 default, v2 custom, v3 default, v3 custom) and make sure the users can “view own content” & “view any content” - if custom site, make sure available for all custom content types. If perms are diff for Page/Person/Article (for custom sites) that's because it's a one off. 

Admissions
User roles: authenticated, editor, publisher, webmaster (anon, viewer)

Brand
User roles: collaborator, editor, publisher, webmaster

V2 default
sitenow_v2 
User roles: editor, webmaster

Grad
User roles: anonymous, authenticated, editor, webmaster

HR
User roles: editor, publisher, webmaster

IGHN
User roles: editor, publisher, webmaster

policy_clas
User roles: editor, publisher, webmaster

Presidential search
User role: webmaster

SPPA
User role: authenticated

Transportation
User role: webmaster

## Site examples:
Before you sync a site, please run `composer install`

### V2 default:
`blt ds —site=hawkeyemarchingband.uiowa.edu`
`drush @hawkeyemarchingband.local uli`
https://hawkeyemarchingband.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - should be set for editor and webmaster

### V2 custom:
`blt ds —site=hr.uiowa.edu`
`drush @hr.local uli`
https://hr.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - Should be set for editor, publisher, webmaster

`blt ds —site=brand.uiowa.edu`
`drush @brand.local uli`
https://brand.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - Should be set for collaborator, editor, publisher and webmaster
(Default content types should have the anonymous and authenticated perms set) 

### V3 default:
`blt ds —site=sandbox.uiowa.edu`
`drush @sandbox.local uli`
https://sandbox.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - Should be set for editor, publisher and webmaster

### V3 custom:
`blt ds —site=admissions.uiowa.edu`
`drush @admissions.local uli`
https://admissions.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - Should be set for anonymous and authenticated

`blt ds --site=sppa.uiowa.edu`
`drush @sppa.local uli`
https://sppa.local.drupal.uiowa.edu/admin/people/permissions
Search for “Node view permissions” - Opportunity should be set w/ authenticated perms

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to start reviewing

**Comment by joewhitsitt** [comment]
For sppa.uiowa.edu do these permissions look correct? They stuck out to me when comparing to other splits/defaults.

Screen Shot 2021-07-14 at 10 23 42 AM
Screen Shot 2021-07-14 at 10 25 01 AM

**Comment by joewhitsitt** [comment]
Is this module working? Based on the permissions, I expect to not see an opportunity node on sppa.uiowa.edu as an anonymous user.

Screen Shot 2021-07-14 at 10 29 17 AM

unchecking `view published content for anonymous while maintaining these new content type specific permissions doesn't seem to do the trick either. It is a knee jerk in the other direction to the point I can't see any published content.

Screen Shot 2021-07-14 at 10 33 34 AM

I need to checkout another branch for an upcoming meeting but would be happy to revisit this later if I missed something.

UPDATE: See https://github.com/uiowa/uiowa/pull/3776#issuecomment-880709382

**Comment by joewhitsitt** [comment]
I think this needs an update hook that imports the permissions update then runs https://api.drupal.org/api/drupal/core%21modules%21node%21node.module/function/node_access_rebuild/8.9.x with batch set to TRUE.

>Installation: After the module installation you need to rebuild permissions. This can be done on admin page /admin/reports/status/rebuild. Until you do it module may not work correctly.

- https://www.drupal.org/project/node_view_permissions

Just tested this on sppa.uiowa.edu with the opportunity content and it worked, so if we change how this is deployed, we can ignore https://github.com/uiowa/uiowa/pull/3776#issuecomment-879995768

This gets a bit complicated because we have to traverse the splits in order to get the correct config imported last. 

OR

If this is deployed and imported normally then followed-up immediately with the update hook just containing node_access_rebuild(TRUE); and a cache clear should do it.

OR

If this is deployed and imported normally then followed-up immediately with something like:

`blt ume php-eval "node_access_rebuild(TRUE);"`

**Comment by joewhitsitt** [comment]
Since the only content to make use of this functionality so far is SPPA's Opportunity, I created a separate PR https://github.com/uiowa/uiowa/pull/3807 to deploy after this PR is deployed.

**Comment by pyrello** [comment]
It seems like, for this to work correctly, we need to uncheck the "View published content" checkbox for anonymous and authenticated users. Otherwise, that permission seems to override any individually set view permissions per content type. When I test this on SPPA, I am able to view opportunity content items as an anonymous user (after rebuilding permissions) and I suspect that is why. Does that track with your understanding, @joewhitsitt?

**Comment by joewhitsitt** [comment]
I can't replicate https://github.com/uiowa/uiowa/pull/3776#issuecomment-880862611

I didn't change any permissions.

Screen Shot 2021-07-15 at 4 20 46 PM
Screen Shot 2021-07-15 at 4 21 03 PM

Rebuild and `cr` worked for me. as an anon couldn't see opportunity content or the view page, as student could.

**Comment by dnkemper** [comment]
baha whoops

**Review by joewhitsitt — APPROVED** [review]

**Comment by dnkemper** [comment]
whoohoooo!

**Pull request merged**
