### PR TITLE
Migration computer science

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
With the help of Cory and the rest of the development team, here is the migration module for the Computer Science news items. Will solve #3357.

Still to do:

- [x] Add multi-field handling for image gallery field.
- [x] Choose image gallery image format
- [x] Debug inline image replacements
- [ ] New code for inline file updates?

# How to test

- In DevDesktop, clone site and pull database from uiclas application (may not be able to do)
- git checkout migration_computer_science (and the usual stuff)
- blt ds --site=cs.uiowa.edu
- drush @cs.local uli
- Enable "Computer Science Migrate" module in Extend
- Go to Configuration > System > SiteNow Migrate
- Enter default values from comments except for Database name (cs_uiowa_edu) and Base URL (https://cs.uiowa.edu).
- Go to Adminsitration > Structure > Migrations > Edit SiteNow migration group.
- Execute Articles migration (should be at least 257 items).

### CODE REVIEW

**Comment by cory-skeers** [comment]
For reference, the following nodes on the D7 site used the image gallery feature:

```
815,818,825,828,843,844,936,948,953,1003,1013,1041,1113,1196,1211,1213,1285,1346,1381,1426,1491,1581,1611,1751,1886,1891,1946,2271,2306,2381,2461,2466,2636,2676,2836,2911,3451,3461,3466,3611,3631,3891,3906,4041,4051,4116,4121,4126,4146,4461,4481,4506,4621,4706,4871,4956,4961,4996,5226
```

The current plan is to take the images from these galleries and append them as images at the end of the article body contents.

**Comment by cory-skeers** [comment]
@mark-bennett-uiowa Spot-checking still needs to be done, but I believe the images from the D7 galleries are now being brought over and appended to the end of the articles.

**Comment by mark-bennett-uiowa** [comment]
You rock @cory-skeers ! Thank you so much for this major addition! I will check this out tonight or early tomorrow and let you know if I see anything.

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers This looks to be working properly. Made a view list on the existing site to find the nodes with actual entries in the image gallery to find them easier.

Is it possible to increase the image formats to maybe medium (no crop) or higher?

Also, it looks like the images from within the body field arent getting migrated:
[https://cs.uiowa.edu/resources/news/cs-faculty-advised-students-sweep-sstp-awards-ceremony](https://cs.uiowa.edu/resources/news/cs-faculty-advised-students-sweep-sstp-awards-ceremony)
[https://cs.local.drupal.uiowa.edu/news/2019/07/cs-faculty-advised-students-sweep-sstp-awards-ceremony](https://cs.local.drupal.uiowa.edu/news/2019/07/cs-faculty-advised-students-sweep-sstp-awards-ceremony)

**Comment by cory-skeers** [comment]
> Is it possible to increase the image formats to maybe medium (no crop) or higher?

Shouldn't be a problem!

> Also, it looks like the images from within the body field arent getting migrated:

I'll take a look into this along with the gallery image sizing.

**Comment by cory-skeers** [comment]
@mark-bennett-uiowa Think I've gotten both parts working.

For the image gallery, you can now update this line to set the default view_mode for all image gallery images:
https://github.com/uiowa/uiowa/blob/2544b2f909c28f9bb50c2428f03bf6cd4ee8ed8b/docroot/sites/cs.uiowa.edu/modules/cs_migrate/src/Plugin/migrate/source/Articles.php#L150

Setting the default formatting for all inline images (currently also set to `medium__no_crop`) can also be adjusted here:
https://github.com/uiowa/uiowa/blob/2544b2f909c28f9bb50c2428f03bf6cd4ee8ed8b/docroot/sites/cs.uiowa.edu/modules/cs_migrate/src/Plugin/migrate/source/Articles.php#L49

One downside that isn't accounted for here is inline files aren't being pulled over properly, as they're included as HTML in the database rather than Drupal encoding. It looks like there might only be a small number of these to account for, though, if all the files are in the `/files/` subfolder. 

```
SELECT entity_id FROM field_data_body WHERE bundle = "article" AND body_value LIKE "%/sites/cs.uiowa.edu/files/files%"
```


| entity_id |
|----------|
950	
994	
1147	
1193	
1536	
1681	
1726	
2046	
2356	
4006	
4056	
4736	

As long as the files are only the ones located there, I'm thinking it's a small enough number to warrant manually moving those after migration, but if there are other locations and/or any of these pages have a high number of files, we can work out a custom script for it.

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers Thanks so much for your work on this! Looks like we are good to go here. Similarly to the Physics migration, this will sit until closer to launch.

**Comment by cory-skeers** [comment]
@mark-bennett-uiowa do you mind if we merge this in? It can still wait to run until closer to launch, but I realized there are a few edits to the base sitenow_migrate that I'd love to get put in.

**Comment by mark-bennett-uiowa** [comment]
@cory-skeers Absolutely! We can merge in this and the Physics PR.

**Review by cory-skeers — APPROVED** [review]

**Comment by cory-skeers** [comment]
Awesome, thanks @mark-bennett-uiowa!

**Pull request merged**
