### PR TITLE
i3251 - Added default content for aos

### LINKED ISSUE #3251: Add defaults to Areas of Study fields
# Motivation

Per conversation with Admissions, they would like to add some default values to Areas of Study fields.

# Proposed solution

Add the following default content to fields:

**Student Opportunities** 
In addition to having nearly 500 Student Organizations, Iowa students choose from multiple Living-Learning Communities, Study Abroad Programs, and Undergraduate Research Opportunities.

 
**Careers and Outcomes**
Iowa graduates have job placement rates ranging from 86-100 percent, depending on their area of study, and our Pomerantz Career Center offers multiple resources to help students find internships and jobs.
 
**Scholarships**
The University of Iowa provides a variety of scholarships to eligible undergraduate students through the Iowa Scholarship Portal. Scholarships are available to first-year, transfer, and currently enrolled students. For additional details on scholarships for your program of study, check directly with the department or college.
 
The Office of Admissions and the Office of Student Financial Aid are great resources for students seeking scholarships.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3251 

# How to test

1. blt ds --site=admissions.uiowa.edu
2. add a new area of study content
3. make sure these defaults are available:

Student Opportunities
In addition to having nearly 500 Student Organizations, Iowa students choose from multiple Living-Learning Communities, Study Abroad Programs, and Undergraduate Research Opportunities.

Careers and Outcomes
Iowa graduates have job placement rates ranging from 86-100 percent, depending on their area of study, and our Pomerantz Career Center offers multiple resources to help students find internships and jobs.

Scholarships
The University of Iowa provides a variety of scholarships to eligible undergraduate students through the Iowa Scholarship Portal. Scholarships are available to first-year, transfer, and currently enrolled students. For additional details on scholarships for your program of study, check directly with the department or college.

The Office of Admissions and the Office of Student Financial Aid are great resources for students seeking scholarships.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Huh. I guess default values do work sometimes. Though this works, I wonder how it will affect AoS migration. Will the values be overwritten if the old site has a custom value already?

**Comment by dnkemper** [comment]
@joewhitsitt crap.. should I not have merged that?

**Comment by joewhitsitt** [comment]
Knowing nothing about the migration, we probably want to do another test run of the migration before go-time based on this change. attn: @cory-skeers and @richardbporter

**Comment by dnkemper** [comment]
@cory-skeers @richardbporter I am sorry!

**Comment by richardbporter** [comment]
We can do that as part of #3275

**Comment by dnkemper** [comment]
Thank you so much, @richardbporter

**Pull request merged**
