### PR TITLE
Update file_mdm, sophron, imagemagick

### LINKED ISSUE #7108: Update file_mdm to version 3.0.0
https://www.drupal.org/project/file_mdm/releases/3.0.0 (10.1)

We are starting to see a lot of "Uncaught exception 'TypeError' with message 'base_convert(): Argument #1 ($num) must be of type string, array given' in /mnt/www/html/uiowa04/vendor/lsolesen/pel/src/PelConvert.php:143" in #drupal-status and we are still on a version that uses an archived `pel` library.

My hope is that this will help with these messages. I think they can be linked back to photo uploads on webforms.

## Reproduce

stella

58499406-b6233d00-8145-11e9-882e-d3e1e1db59f1

## Known Issue

https://sitenow.uiowa.edu/known-issues#uiowa-issue-7108

# Proposed Solution

- [x] Upgrade file_mdm to version 3.0.0
- [x] test that iphone image exif rotation still works
- [ ] monitor logs and cherwell

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/7108

# To Test

- Before pull this branch, on `main` sync down sandbox:

```
ddev composer install && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli media/add/image
```

- Use the images from the https://github.com/uiowa/uiowa/issues/7108 issue summary
- You should get an error after selection that prevents you moving forward with saving the media entity. Looking at the console log, you should see an error about base_convert() string/array type thing.

```
git checkout update_file_mdm && git pull && ddev composer install && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli media/add/image
```

Try the images again. There should be no error on upload and the images should appear in the correct orientation.

Review the original PR https://github.com/uiowa/uiowa/pull/264 and ImageMagick https://git.drupalcode.org/project/imagemagick/-/blob/8.x-3.x/src/Plugin/ImageToolkit/ImagemagickToolkit.php#L556 to understand that we aren't losing any functionality.

## Additional Notes

We still need these modules/enabled, but I don't think we are directly calling file_mdm in our code anymore.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I wonder if this image will work for testing: https://github.com/uiowa/uiowa/issues/194#issuecomment-496617383

**Comment by joewhitsitt** [comment]
Turns out the image from https://github.com/uiowa/uiowa/pull/7218#issuecomment-1858564171 fails in PROD and on LOCAL 🤷

**Comment by joewhitsitt** [comment]
Actually, I think we may no longer need the file_mdm custom presave

**Comment by joewhitsitt** [comment]
I _think_ @cory-skeers solution for image orientation was done in 2019 with file_mdm. ImageMagick released version 2.4 with file_mdm and file_mdm_exif or whatever as part of the toolkit processing. We didn't upgrade ImageMagick from 2.3 until 2020. I don't think have needed the presave code since then.

**Comment by bspeare** [comment]
Testing this and commenting out `sitenow_media_wysiwyg_form_media_library_add_form_alter` on `main` seems to make the file upload error go away.   Without that hook on `main` is the image from https://github.com/uiowa/uiowa/issues/194#issuecomment-496617383 supposed to appear upside down or do I need to look into the image metadata?

**Comment by joewhitsitt** [comment]
> Testing this and commenting out `sitenow_media_wysiwyg_form_media_library_add_form_alter` on `main` seems to make the file upload error go away. Without that hook on `main` is the image from [#194 (comment)](https://github.com/uiowa/uiowa/issues/194#issuecomment-496617383) supposed to appear upside down or do I need to look into the image metadata?

By commenting out the code on `main` you are essentially doing the same as this PR. It makes the error go away. The rotation on `main` should still work without the code because we have been using the version of ImageMagick for a while that had this functionality. I think if you downgraded or removed ImageMagick, you would see the image uploaded with the wrong orientation.

The module updates turned out to be unrelated to both the error and the orientation feature but are the recommended stable versions at this time.

**Comment by bspeare** [comment]
Thanks, I will presume that all "images should appear in the correct orientation" based on ImageMagick - thanks @joewhitsitt!

**Comment by joewhitsitt** [comment]
Sure you don't want to switch back to GD core processing to test for fun? ;)

All I know is that the one image is from the original issue and Cory mentioned that github strips some exif on upload as well and that my dog picture is currently rotated wrong in Google Photos as a thumbnail but oriented correctly in view mode and was shot with an iPhone back in the day.

**Comment by joewhitsitt** [comment]
"For fun" I decided to uninstall imagemagick on this branch locally and upload one of the images:

Screenshot 2023-12-19 at 3 40 42 PM

**Review by bspeare — APPROVED** [review]
All testing instructions worked out.

**Pull request merged**
