### PR TITLE
Hotfix more lb styles

### PR DESCRIPTION
**Pull request by joewhitsitt**
Test some v3 sites. card templates should have correct styles applied. (no ovals images, not stacked where right/left aligned)

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt This appears to be working for cards, events, news and aggregator. I am attaching screenshots shortly.

**Comment by mark-bennett-uiowa** [comment]
Events block on frontpage of interdisciplinaryprograms.uiowa.edu:
Before:
Screen Shot 2021-02-15 at 9 58 00 AM
After:
Screen Shot 2021-02-15 at 10 06 39 AM

**Comment by mark-bennett-uiowa** [comment]
Frontpage card block containing news from americanstudies.uiowa.edu:
Before:
Screen Shot 2021-02-15 at 10 14 15 AM
After:
Screen Shot 2021-02-15 at 10 17 59 AM

**Comment by mark-bennett-uiowa** [comment]
I did get this error when editing the news item from the americanstudies.local site:
Screen Shot 2021-02-15 at 10 16 14 AM

**Comment by joewhitsitt** [comment]
The schema_metatag is unrelated to this PR: https://www.drupal.org/project/schema_metatag/issues/3174103 we need to update when there is a new release

**Comment by mark-bennett-uiowa** [comment]
I cant provide a screenshot of the aggregator if anyone else was able to check this. The aggregator I use has images turned off and isnt utilizing these feature. Approving this hotfix for now to get it out the door.

**Review by mark-bennett-uiowa — APPROVED** [review]
Approving. Changes seem to fix immediate errors. Code changes look clean. Didnt test aggregator fix.

**Comment by bspeare** [comment]
Tested on sandbox example pages and all looks good too.

**Pull request merged**
