### PR TITLE
Require dispatch signup form email field, change submit message and add headline field.

### PR DESCRIPTION
**Pull request by richardbporter**
Follow up to #3823.

### Setup 
- Configure SiteNow Dispatch settings with csi.drupal API key.
- Add a signup form to a page.

### Stories
- As someone subscribing to a list, I cannot submit the form without entering my email.
- As someone subscribing to a list, I see a confirmation message that makes sense when I submit the form.
- As a site user, I can add a signup form to a page with a headline appropriately sized and styled.

### Alan's added story
- As someone trying to add a sign up form block, I cannot add the block to the page until I have configured an API key.

### CODE REVIEW

**Comment by richardbporter** [comment]
Hm. Noticed one other thing.

**Comment by richardbporter** [comment]
First/last name are not required fields so we can't rely on outputting them in a confirmation message.

**Comment by richardbporter** [comment]
Just noticed we don't have a title field on this block. That would be useful.

**Comment by GaryRidgway** [comment]
I will approve this if someone else can approve my addition to it.

I've added a check to not display an 'add block' button when adding the block if there is no api key configured so that there are no incorrect form submissions.

**Comment by cory-skeers** [comment]
Pulling down to test

**Review by cory-skeers — APPROVED** [review]
> ### Alan's added story
> * As someone trying to add a sign up form block, I cannot add the block to the page until I have configured an API key.

Checked out this story, and looks good!

Also went through the other stories for another pair of eyes.

**Comment by richardbporter** [comment]
Thanks!

**Pull request merged**
