### PR TITLE
[Commencement] Ceremonies page

### LINKED ISSUE #7649: Ceremony filterable list
# Story

We would like to be able to display a list of all commencement ceremonies with the ability to filter so that users can quickly find the ceremony information they are looking for.

# Additional Info

- Ability to filter by Session
  - Default session to webmaster defined default session - On the live site, the session taxonomy has a default boolean field so the webmaster can choose which session the list should default to.
- Ability to filter by College - would like to choose multiple - nice to have would be a select all option.
- Ability to filter by Other Celebration type
- Ability to filter by Venue

**Info to Display**

- Title as a link
- date start and end time if exists
- venue

Theme

# Proposed Solution
```[tasklist]
### Tasks
- [x] Create view to display a list of all ceremonies.
- [x] Add way to set current session - developer's choice if via a form setting or a field on the entity. Either way only one session should be set at a time.
- [x] Add ability to filter by session, with default set to current session. Filter should be a select list.
- [x] Add ability to filter by college, with option to choose multiple. Nice-to-have would be a select all option. Filter should be a select list.
- [x] Add ability to filter by Other Celebration type, perhaps under an Advanced section. Filter should be a select list. Maybe have option to select none?
- [x] Add ability to filter by venue. May need to turn venue autocomplete into a select list.
- [x] Ceremony teaser should display title as a link, start date (and end date if it exists), and the venue.
- [x] Theme view
```

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #7649 

# How to test

```
ddev blt ds --site commencement.uiowa.edu
```
- https://commencement.uiowa.ddev.site/admin/structure/taxonomy/manage/session/overview
- Edit a session to set a default session
- https://commencement.uiowa.ddev.site/ceremonies
- Confirm that selected session in session drop down matches your selection.
- Set a different default session and ensure that it updates in the views exposed filter without needing to clear caches.
- Review these requirements to make sure the view page meets them: https://github.com/uiowa/uiowa/issues/7649#issue-2278252914

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Just wondering about a few things from the issue:

Is it in scope to clean up this display (visually hidden label, inline date)?
Screenshot 2024-05-10 at 11 31 36 AM

>Need to make sure we can display the list of sessions in an appropriate order

Is it in scope to figure out the session dropdown order or is it on the site owner to drag terms manually?

>multiple colleges would solve for their need of a way to see only Collegiate ceremonies

Does this solve the, "how to not show other celebrations"?

**Comment by bspeare** [comment]
> Is it in scope to clean up this display (visually hidden label, inline date)?

This part is cleaned up in the venue pr.

**Comment by briand44** [comment]
The multi-select solves the not showing other celebrations request. I discussed that with Josh

**Comment by briand44** [comment]
I think if we can automagically solve for the session order that would be great. The D7 site currently handles that. I wonder if logic there could be re-implemented here?

**Comment by joewhitsitt** [comment]
>I think if we can automagically solve for the session order that would be great. The D7 site currently handles that. I wonder if logic there could be re-implemented here?

@pyrello do you have capacity to work on that or are you looking to hand that piece off?

**Comment by briand44** [comment]
some logic in commencement_core.module

```
/**
 * Helper function to sort session results.
 * This function allows you to pass in the results from a view then uses the sort function from session sort.
 */
function result_session_sort(&$a, &$b) {
  $a = taxonomy_term_load($a->_field_data['fid']['entity']->field_document_session[LANGUAGE_NONE][0]['tid'])->name;
  $b = taxonomy_term_load($b->_field_data['fid']['entity']->field_document_session[LANGUAGE_NONE][0]['tid'])->name;
  return(session_sort($a, $b));
}

/**
 * Helper function to sort session based on season and year.
 */
function session_sort(&$a, &$b) {
  if ($a != '- Any -') {
    $sessions = array($a, $b);
    foreach ($sessions as $session) {
      $term = taxonomy_get_term_by_name($session, 'session');
      $term = array_pop($term);
      $session_index = $term->field_session_season[LANGUAGE_NONE][0]['value'];
      $session_year_timestamp = $term->field_session_year[LANGUAGE_NONE][0]['value'];
      $session_year = format_date(strtotime($session_year_timestamp), 'year');
      $session_values[] = $session_year . $session_index;
    }

    return ($session_values[0] > $session_values[1]);
  }
}
```

**Comment by pyrello** [comment]
> > I think if we can automagically solve for the session order that would be great. The D7 site currently handles that. I wonder if logic there could be re-implemented here?
> 
> @pyrello do you have capacity to work on that or are you looking to hand that piece off?

I can work on it.

**Comment by pyrello** [comment]
Does this look right?
Screenshot 2024-05-10 at 2 45 55 PM

**Comment by briand44** [comment]
Looks right to me and matches the existing site. Nice work!

**Comment by pyrello** [comment]
Ready for review again.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
