### PR TITLE
Admin pre-footer column options

### LINKED ISSUE #4622: Two and three column layouts available in prefooter are broken
# Problem
As pointed out by @bewoldt Admin users are able to add 2 and 3 column layouts to the prefooter, however, none of the section settings or styles are working. 

# Steps to reproduce
Try adding a 2 or 3 column layout to a prefooter and adjust the section container or spacing. 

Screen Shot 2022-01-05 at 11 29 06 AM

# Proposed solution
Fix the layouts so that they work or remove them as an option.

### PR DESCRIPTION
**Pull request by GaryRidgway**
Fixes Admin pre-footer column options, you can now properly use spacing and styles on them.

## To test
Sync sandbox
You cant add any new sections other than one column? Even as an admin?
This means this is working

### CODE REVIEW

**Comment by bspeare** [comment]
This works great! Nice that it was just a name change issue. 

I did notice one issue that previously existed. Once an admin adds a two or three column layout, then an editor/webmaster can go and add unlimited two and three column layouts.  Unless we have a permissions workaround for this, I think we should just remove two and three column layouts from the pre-footer region now that we know that this isn't a blocker for https://github.com/uiowa/uiowa/issues/4767.

**Comment by bspeare** [comment]
It looks like there would be no data loss either if we removed the two and three column options.   If an admin had created those layouts they will continue to be able to edit those.

**Comment by makurj** [comment]
Pulling down to test.

**Review by makurj — APPROVED** [review]
As an admin, I can add only a one-column section to an existing pre-footer.

**Pull request merged**
