### PR TITLE
Events Follow-Up

### PR DESCRIPTION
**Pull request by joewhitsitt**
- Override events-single styles in uids_base to match Article
- Fix for UHR's event single render being blank.

### CODE REVIEW

**Comment by pyrello** [comment]
I was getting tempted to try to implement the event template, but then I realized that the event template needs to be re-written and that's not going to happen until @bspeare gets back, so I'm leaving it for now.

**Review by pyrello — APPROVED** [review]
Looks good. Nice work!

**Comment by richardbporter** [comment]
1960cea prevents overriding the `card_content` so the location shows on the teaser. Can we revert that or is there another way of handling it?

**Comment by joewhitsitt** [comment]
I didn't realize @pyrello snuck that change in there. I am not familiar enough with Twig to work around it another way.

**Comment by pyrello** [comment]
The `only` keyword just limits the variables to those that are explicitly passed. If you need a implicit variable (one that is available in the current scope but not defined in the current template), just explicitly add it to the `events_card` object that is passed to the template.

What is the variable that is missing?

**Comment by pyrello** [comment]
FYI, I am working on a fix for this.

**Comment by richardbporter** [comment]
Can you add it to https://github.com/uiowa/uiowa/pull/2133?

**Pull request merged**
