### PR TITLE
PHP 8.1 Upgrade

### LINKED ISSUE #5708: Migration comparison operators
Currently, migration scripts still have comparison operators, but it would be very difficult to discern the actual intent of what they are trying to do without running amok migration. This issue is to track all of the old migration scripts that have these comparison operators in them.

https://github.com/uiowa/uiowa/blob/6616743f51645bd0679b19b76bbfe3d12b956015/docroot/sites/tippie.uiowa.edu/modules/tippie_migrate/src/Plugin/migrate/source/Articles.php#L215-L221

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/5315
Resolves https://github.com/uiowa/uiowa/issues/5708

# To do

<details>
<summary>History</summary>

- [x] profiles/custom/sitenow @joewhitsitt
- [x] themes/custom/uids_base @pyrello
- [x] modules/custom/engineering_migrate
- [x] modules/custom/grad_custom @pyrello 
- [x] modules/custom/layout_builder_custom @pyrello 
- [x] modules/custom/sitenow_articles @joewhitsitt
- [x] modules/custom/sitenow_dcv @joewhitsitt - _no changes_
- [x] modules/custom/sitenow_dispatch @joewhitsitt
- [x] modules/custom/sitenow_events @joewhitsitt
- [x] modules/custom/sitenow_find_text @joewhitsitt - _no changes_
- [x] modules/custom/sitenow_intranet @joewhitsitt - _no changes_
- [x] modules/custom/sitenow_media_wysiwyg @joewhitsitt  
- [x] modules/custom/sitenow_migrate @joewhitsitt
- [x] modules/custom/sitenow_p2lb @joewhitsitt
- [x] modules/custom/sitenow_pages
- [x] modules/custom/sitenow_paragraphs @joewhitsitt
- [x] modules/custom/sitenow_people @joewhitsitt
- [x] modules/custom/sitenow_seo @joewhitsitt - _no changes_
- [x] modules/custom/studentlife_migrate @joewhitsitt - _no changes_
- [x] modules/custom/studentlife_topics @joewhitsitt - _no changes_
- [x] modules/custom/uiowa_aggregator @joewhitsitt
- [x] modules/custom/uiowa_alerts @joewhitsitt
- [x] modules/custom/uiowa_apr @joewhitsitt  - _no changes_
- [x] modules/custom/uiowa_area_of_study @joewhitsitt
- [x] modules/custom/uiowa_book @joewhitsitt - _no changes_
- [x] modules/custom/uiowa_core @joewhitsitt
- [x] modules/custom/uiowa_entities @joewhitsitt 
- [x] modules/custom/uiowa_graph @joewhitsitt 
- [x] modules/custom/uiowa_hours @joewhitsitt 
- [x] modules/custom/uiowa_maui @joewhitsitt 
- [x] modules/custom/uiowa_profiles @joewhitsitt 
- [x] modules/custom/uiowa_search @joewhitsitt - _no changes_
- [x] modules/custom/writinguniversity_migrate @joewhitsitt - _no changes_
- [x] modules/uiowa/uiowa_auth @joewhitsitt - https://github.com/uiowa/uiowa_auth/pull/6
- [x] sites/admissions.uiowa.edu @joewhitsitt 
- [x] sites/brand.uiowa.edu @joewhitsitt 
- [x] sites/coronavirus.uiowa.edu @joewhitsitt 
- [x] sites/dentistry.uiowa.edu @joewhitsitt 
- [x] sites/grad.admissions.uiowa.edu @joewhitsitt 
- [x] sites/grad.uiowa.edu @joewhitsitt 
- [x] sites/housing.uiowa.edu @joewhitsitt - _no changes_
- [x] sites/hr.uiowa.edu @joewhitsitt 
- [x] sites/ighn.international.uiowa.edu @joewhitsitt 
- [x] sites/iisc.uiowa.edu @joewhitsitt 
- [x] sites/neuroscience.grad.uiowa.edu @joewhitsitt - _no changes_
- [x] sites/now.uiowa.edu @joewhitsitt 
- [x] sites/pharmacy.uiowa.edu @joewhitsitt 
- [x] sites/sitenow.uiowa.edu - @GaryRidgway 
- [x] sites/sppa.uiowa.edu - @GaryRidgway 
- [x] sites/tippie.uiowa.edu - @GaryRidgway 
- [x] sites/transportation.uiowa.edu - @GaryRidgway 
- [x] sites/uiowa.edu - @GaryRidgway 
- [x] sites/uipress.uiowa.edu - @GaryRidgway 

Please track any migration comparison operators of old migrations here:
https://github.com/uiowa/uiowa/issues/5708

</details>

## Setup

It is recommended that your Docker and DDEV are updated:

- For docker, click the menu bar icon to download and install an update.
- `brew upgrade ddev` if you installed via homebrew

## To Test

- pull
- `ddev restart`
- `ddev composer install`
- `ddev auth ssh`
- `ddev ssh`
- `php -v` and confirm 8.1 or greater

## More Testing
- Generally take a look through this guide to see the types of things that are changing: https://www.php.net/manual/en/migration80.php
- Review the file changes to see if anything sticks out to you: https://github.com/uiowa/uiowa/pull/5611/files
- Review menu block as it relates to https://github.com/uiowa/uiowa/pull/5611/files#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4cR609
- Review replicate as it relates to https://github.com/uiowa/uiowa/pull/5611/files#diff-96158dc2654c9de7f8206491f115c59eec3097e39643d343a870e538e89e5d6fR190
- Review v2/v3 functionality as it relates to the display title, hide headline, more link, use pager, link directly to source boolean options.
- Review that things previously restricted to Admins only are still working (they all use the same access check) so check to see that the advanced fontawesome icon options aren't visible to webmasters on event/timeline block.
- Make sure MAUI API is still sorting dates correctly based on timestamp.
- Check that there are no php errors while poking around law.dev, grad.dev or admissions.dev.

Semi-related, homebrew users should `brew install php@8.1` on their machines and switch to it at some point.
Afterward, update your PHPStorm > Preferences > PHP > CLI Interpreter

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Going to try switching to [jammy](https://docs.travis-ci.com/user/reference/jammy/#php-support) for PHP 8.1

**Comment by joewhitsitt** [comment]
```ddev composer why-not php 8.0
neutron/temporary-filesystem         2.4    requires  php (^5.6 || ^7.0)    
php-ffmpeg/php-ffmpeg                v0.14  requires  php (^5.3.9 || ^7.0)  
richardbporter/drush-users-commands  3.0.2  requires  php (^7.4)
```

**Comment by joewhitsitt** [comment]
@pyrello do you know if this is still needed?

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_search/composer.json

**Comment by pyrello** [comment]
> @pyrello do you know if this is still needed?
> 
> https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_search/composer.json

I think this is an artifact of when it was a standalone repo. I don't think it's needed anymore.

**Comment by joewhitsitt** [comment]
yay, travis went farther. running into this now: https://github.com/uiowa/uiowa/issues/5315#issuecomment-1244311286

**Comment by pyrello** [comment]
I think we need to merge in #5625 either to main or specifically to this branch to make sure we are getting all the correct composer dependency versions.

**Comment by pyrello** [comment]
It looks like the version of `phpstan/phpdoc-parser` in #5625 is set to 1.8, which is not compatible with everything else. When merging in #5625 and resolving conflicts in composer.lock, accept the changes for `phpstan/phpdoc-parser` in this branch. Otherwise, you're going to be in composer incompatible dependency hell.

**Comment by joewhitsitt** [comment]
Moving forward without completely exposing ourselves. PHPUnit seems to be picking up some slack and reporting deprecated stuff.

**Comment by joewhitsitt** [comment]
We are stuck on fontawesome 2.19 (2.2 requires fontawesome 6) I think so instead of upgrading it we need to patch it.. https://www.drupal.org/project/fontawesome/issues/3258575

**Comment by joewhitsitt** [comment]
Still trying to get input from the community about how best to scan for php 8+ deprecated code. Removing php-compatibility from the checks and fixing issues raised by phpunit, I am wondering if we can deploy this to develop, sync some sites and start monitoring logs.

**Comment by joewhitsitt** [comment]
@pyrello thanks for piecing that together and communicating with Mike.

**Comment by pyrello** [comment]
With regard to the string to number comparison changes in PHP8, I have never been a big fan of using `==` to check the value of something unless there is a specific reason to believe that the type won't be the same. We could probably replace 95% of them with no change in functionality. I would be in favor of doing this.

**Comment by pyrello** [comment]
> With regard to the string to number comparison changes in PHP8, I have never been a big fan of using `==` to check the value of something unless there is a specific reason to believe that the type won't be the same. We could probably replace 95% of them with no change in functionality. I would be in favor of doing this.

I started looking into this last night. I think the vast majority of `==` comparisons we are doing are string comparisons (e.g. `$foo == 'bar'`). There are some cases I think we need to investigate where we are comparing a variable and either a numeric string (e.g. `$foo == '0'`) or an actual integer (e.g. `$foo == 0`). I think in either case we need to check the logic because the `$foo` value could be either. Probably we were using the `==` check as a fuzzy way of not having to account for whether it was one or the other (since a `===` check would strictly check the type and could result in a false for a `0 === '0'` check). My guess is that this is a few hours worth of work and potentially a good pairing opportunity for any developers that are less familiar with the idiosyncrasies of the PHP equals and identity operators.

**Comment by pyrello** [comment]
Going to work on the remaining modules in the `docroot/custom` directory in bulk.

**Comment by pyrello** [comment]
I have updated all the string comparisons in custom modules and started to work on remaining `==`. However, I am going to be stepping away shortly, so I am not going to complete the updates for custom modules. I have marked what is done in case someone else wants to work on those.

**Comment by joewhitsitt** [comment]
oops. did something to uiowa_maui that is making me question everything. looking into it.

**Comment by joewhitsitt** [comment]
Just noticed there are php 8 related issues in uiowa_auth https://github.com/uiowa/uiowa_auth/issues. @pyrello did you figure out how to run those tests now that uiowa_auth has been separated out again?

**Comment by pyrello** [comment]
> Just noticed there are php 8 related issues in uiowa_auth https://github.com/uiowa/uiowa_auth/issues. @pyrello did you figure out how to run those tests now that uiowa_auth has been separated out again?

@joewhitsitt Are you talking about locally?

**Comment by joewhitsitt** [comment]
>Are you talking about locally?

Yea

**Comment by pyrello** [comment]
> > Are you talking about locally?
> 
> Yea

I have not tried this, but it looks like this was the old instructions for it: https://github.com/uiowa/uiowa/commit/d4b70054ca9f15ea54814d0dd4fdceb7a9047ceb#diff-897498d28e599e508c48630c6a3ec360535f1d0be801ed4454cdd53c18f0e665

**Comment by joewhitsitt** [comment]
Oh okay. Similar instructions are there now. Thanks @pyrello

**Comment by joewhitsitt** [comment]
I am having troubles with DEV:

```
Schema information for module language was missing from the database. You should manually review the module updates and your database to check if any updates have been skipped up to, and including, language_update_8001().
 [error]   (Currently using Missing or invalid modules The following modules are marked as installed in the core.extension 
configuration, but they are missing:
 * layout_builder_limit
 * mysql

Review the  suggestions for resolving this incompatibility [1] to repair your 
installation, and then re-run update.php.

[1] https://www.drupal.org/docs/8/update/troubleshooting-database-updates
) 
 [error]  The installed version of the /Language/ module is too old to update. Update 
to a version prior to 9.0.0 first (missing updates: 
language_post_update_language_select_widget).
 
 [success] No pending updates.
 [warning] Message: Schema information for module /language/ was missing from the database. You 
should manually review the module updates and your database to check if any 
updates have been skipped up to, and including, /language_update_8001()/.
```

noticed this for the sites I synced down to DEV in order to test this PR (law, grad, admissions)

**Comment by pyrello** [comment]
> noticed this for the sites I synced down to DEV in order to test this PR (law, grad, admissions)

I wonder if this is similar to the issue we have sometimes with config splits, where a module has to be enabled before the split can be enabled?

**Comment by joewhitsitt** [comment]
Not sure how to do that with develop, composer and both a core and contrib module.

SSH'd into uiowa.dev and ran a composer show. layout_builder_limit isn't even listed.

**Comment by joewhitsitt** [comment]
I may have prematurely closed #5709 because now that I merged this branch into develop, deployment to DEV is no longer happening. I am starting to wonder if there is a Acquia Cloud/BLT PHP 8 thing going on..

**Comment by joewhitsitt** [comment]
Opened a ticket with Acquia https://support-acquia.force.com/s/case/5006g00000i6BFUAA2/dev-deploy-issues-while-testing-php-81-upgrade

**Comment by joewhitsitt** [comment]
trying updating blt/travis stuff

for reference: https://github.com/acquia/blt-travis/issues/3

**Comment by joewhitsitt** [comment]
Based on the discussion on https://github.com/uiowa/uiowa/issues/5315 and within this morning's standup, I am removing the php8-isms that seem to be messing with our ability to auto deploy to DEV

**Comment by joewhitsitt** [comment]
This one change https://github.com/uiowa/uiowa/pull/5611/commits/eceb4aed5cb730d62b70d0b15c9e0e1f7043b118 has got auto deployment working again

**Comment by joewhitsitt** [comment]
The #blt Drupal Slack channel helped again. This is now properly auto deploying to DEV. Moving forward with upgrading to php 8.1. This PR is ready for review.

**Comment by pyrello** [comment]
Pulling this to start testing it

**Comment by pyrello** [comment]
Updated testing instructions: `ddev restart` has to happen prior to `ddev composer install` because of composer PHP constraint added to composer.json.

**Review by pyrello — COMMENTED** [review]
I have reviewed all file changes and this is good to go from that perspective.

**Comment by pyrello** [comment]
> Review that things previously restricted to Admins only are still working (they all use the same access check) so check to see that the advanced fontawesome icon options aren't visible to webmasters on event/timeline block.

@joewhitsitt What I am seeing is that the advanced options are visible but greyed out. Is that what is intended?

**Comment by joewhitsitt** [comment]
Correct. `Additional Font Awesome Settings` fields should be disabled

**Comment by pyrello** [comment]
I found two issues while testing:
- List block headlines were not honoring the "visually hide title" setting
- Replicate was broken because of the check to prevent deleting the current node.

I fixed both issues.

**Review by pyrello — APPROVED** [review]
After reviewing and testing this update both locally and on dev, I think that it looks good.

**Pull request merged**
