### PR TITLE
Classrooms - search page enhancements

### LINKED ISSUE #6434: Classroom search page enhancements
# Story

As a Classrooms website owner, I would like to enhance the search/filtering capabilities on the Classroom search page so that users have a better experience finding what they are looking for.

# Additional Info

Search page - https://classrooms.prod.drupal.uiowa.edu/find-university-classroom

- They would like the ability to sort by occupancy asc/desc as well as building asc/desc - There is an example of this on the D7 Registrar site https://registrar.uiowa.edu/ucr-sps.
- They would like to be able to choose multiple items in the building, type, technology and room features filters.

# Proposed solution

- [x] Provide sort by functionality for occupancy and building
- [x] Allow choosing multiple options in filters
- [x] may need to adjust design of filters

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves #6434.

# To do:

- [ ] ~Get mutliselect working for building filter~ - will be fixed in follow-up issue
- [x] See if error with type filter is fixable so that checkboxes can be used
- [x] Move sort options out of filter area
- [x] Fix issue where select list options are overlapping/hidden behind cards
- [x] Check set-up of room/tech features - should rooms only display if they meet all selections, or any?

# How to test:
```
ddev blt frontend && ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local uli find-university-classroom
```

- checkout & pull branch, `ddev blt ds --site=classrooms.uiowa.edu`, `uli` into site
- go to https://classrooms.uiowa.ddev.site/find-university-classroom
- test new sort options (building asc & desc, max capacity asc & desc) work as expected
- test multiselect filters work (type, technology, features)
- Check https://classrooms.uiowa.ddev.site/programmed-classrooms was not affected by these changes

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
>I just noticed a duplication issue. If I set type to classroom-computer, technology to apple air play, and features to a/c and whiteboard - glass, the same room is listed twice. I'm going to see if there's a reduce duplicates setting that will help. https://github.com/uiowa/uiowa/issues/6434#issuecomment-1561565606

pushed a fix for those multi-select filters https://github.com/uiowa/uiowa/pull/6468/commits/d6781a4efcc8ac0c3667b9b186faf3c252f4d2c4

**Comment by joewhitsitt** [comment]
Wondering if auto-submit should be turned off now that there are these multi-select dropdowns. In trying to reproduce the situation above ^^, the dropdown collapsed and submitted while i was trying to scroll and find the other item to click.

**Comment by e-marie-w** [comment]
> Wondering if auto-submit should be turned off now that there are these multi-select dropdowns. In trying to reproduce the situation above ^^, the dropdown collapsed and submitted while i was trying to scroll and find the other item to click.

Great question, that was also bugging me. I can look into turning it off.

**Comment by joewhitsitt** [comment]
Thanks. Going to check one more thing

**Comment by joewhitsitt** [comment]
Ah crud, by turning off autosubmit, the sort feature requires you to select an option and then click search and feels disconnected from all of that like it should just happen.

**Comment by bspeare** [comment]
If that's the case, perhaps we should leave autosubmit on?

**Comment by e-marie-w** [comment]
We could also move the sort options back to being a part of the filter area, maybe that would better signal it's also connected to the search button?

**Comment by bspeare** [comment]
It's a pretty clunky experience to have to hit the search button after every filter change.  This filter was designed for the autosubmit feature and we would need to create an alternative design for the manual submit `bef` filter if we want to move in that direction.

**Comment by joewhitsitt** [comment]
Also noticed the dropdowns aren't alphabetical (e.g. Printer is not where it should be). I think there is an option in BEF for that if we are turning autosubmit back on.

I think I missed the reasoning for separating out the sort from the form but I imagine it had to be something. Generally I am not a fan of autosubmit for other reasons, but also don't want to hold this up over it.

**Comment by bspeare** [comment]
The reasoning is the "Sort" controls the visual display list while the rest of the filters control the content.  Which is why sort is an option outside of the filter settings. 
<details>
Screenshot 2023-05-25 at 10 19 20 AM
</details>

**Comment by e-marie-w** [comment]
If nobody minds, I want to spend some time seeing if there's an easy way to have some filters be autosubmit and some not.

**Comment by bspeare** [comment]
If we turn off autosubmit, we would need to rearrange the form with the "Search" at the bottom so that it is clear that the search button is required for completing the filer task:

Screenshot 2023-05-25 at 10 21 58 AM

**Comment by bspeare** [comment]
@e-marie-w even if https://github.com/uiowa/uiowa/pull/6468#issuecomment-1563094270 is an option, we would still be facing https://github.com/uiowa/uiowa/pull/6468#issuecomment-1563097320.

**Comment by bspeare** [comment]
@joewhitsitt more on the sort/filter thinking from https://design.gs.com/patterns/filter-and-sort:

- Filters set a hard boundary on the search results and exclude anything not falling within the categories selected, while sort sets a soft boundary and only changes the sequence of appearance.
- Sorting helps to organize data by particular attribute or parameter, such as alphabetically or by date. Sorting organizes the content according to a certain parameter while filtering removes it from view.

**Comment by joewhitsitt** [comment]
Yeah I get that it isn't ideal, but they aren't working within the confines of Drupal views/BEF. Technically we could supplement BEF with some of our own JS to trigger the exposed filters on sort change. Again, not trying to hold this up. We are trading one UX win at the cost of another. Maybe something to consider as we continue to refine our pattern for exposed filters.

>Also noticed the dropdowns aren't alphabetical (e.g. Printer is not where it should be). I think there is an option in BEF for that if we are turning autosubmit back on.

If this is done, I will approve

**Comment by briand44** [comment]
Alphabetizing the technology features was brought up by Classroom folks after our meeting yesterday. I had added that to https://github.com/uiowa/uiowa/issues/6477

**Comment by e-marie-w** [comment]
Sounds like we want to stick with autosubmit all for now, I'll switch it back.

**Comment by e-marie-w** [comment]
Only new change is type, technology, and features should display options in alphabetical order now.

**Review by joewhitsitt — APPROVED** [review]
>[Re-enabled autosubmit but excluded checkbox filters from it](https://github.com/uiowa/uiowa/pull/6468/commits/42808b001ea4d7a98b2a3bbc016740dd1ac1307b)

Clever idea here to keep in mind for future use-cases. Thanks for the rest of the changes.

**Comment by bspeare** [comment]
Tested bef out on simplytest.me and it looks like the issue with our filters is that the `<details>` are closing once the form is autosubmitted.   On simplytest.me they remain open unless a user toggles them close.   A future slice of this work could be to make sure the `<details>` do not reset to closed on AJAX submit.

**Pull request merged**
