### PR TITLE
[Grad] Removed permissions to create fellowship content

### PR DESCRIPTION
**Pull request by bspeare**
This is a support request from Makur. 

# How to test

```
ddev blt ds --site=grad.uiowa.edu  && ddev drush @grad.local /admin/people
```
- Code review or Masquerade as editor, publisher, webmaster and confirm you can no longer `/node/add/scholarship`

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>Should this be done in https://github.com/uiowa/uiowa/tree/main/config/features/scholarship instead?

I don't think so because they aren't the only ones to use the feature. It was originally built for Admissions.

**Comment by joewhitsitt** [comment]
pulling to check

**Review by joewhitsitt — APPROVED** [review]
checks out

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
