### PR TITLE
Panopto Support v2/HR

### LINKED ISSUE #3676: As a v2 site editor/publisher/webmaster, I can embed Panopto videos.
# Story

As a v2 site editor/publisher/webmaster, I can embed Panopto videos.

Follow up from #3621 

# Proposed solution

Update v2 permissions to allow for this. Double check it works properly. Probably requires some responsive style updates.

### LINKED ISSUE #3691: Brand - Organization taxonomy permissions
# Story

As a webmaster on the brand.uiowa.edu, I want the ability to add/edit/delete organization terms as requirements change.

# Proposed solution

- [x] Update the webmaster role permission split for brand.uiowa.edu to include Organization add/edit/delete permissions.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3691 & Closes #3676 

# How to test
* `blt frontend`
* As a webmaster on the brand.uiowa.edu, I want the ability to add/edit/delete organization terms as requirements change.
  * blt ds --site=brand.uiowa.edu
  * Make sure you can add/edit/delete organization taxonomy terms  as a webmaster
* As a v2/HR site editor/publisher/webmaster, I can embed Panopto videos.
   * blt ds --site=hawkeyemarchingband.uiowa.edu
   * blt ds --site=hr.uiowa.edu
   * Make sure you can add a UICapture (Panopto video) in WYSIWYG media as a editor/publisher/webmaster
* As a site editor/publisher/webmaster, the remote video/panopto video that I place in the WYSIWYG looks similar to what is rendered.
   *  blt ds --site=sandbox.uiowa.edu https://sandbox.prod.drupal.uiowa.edu/media
   *  https://github.com/uiowa/uiowa/issues/3725

## ToDo

- [x] Original (media--view-mode-default) in uiowa_bootstrap isn't rendering
- [x] Alignment without captions is not working for v2/v3
- [x] General HR support (preview/render)
- [x] Previews for Kaltura are broken

### CODE REVIEW

**Comment by joewhitsitt** [comment]
brand (v2) doesn't have the panopto permissions. there are a few other v2 split sites that this needs to be captured on. ighn.international.uiowa.edu, hr.uiowa.edu and technically sitenow.uiowa.edu (until it changes to v3)

**Comment by dnkemper** [comment]
@joewhitsitt OH DUH! Thank you!

**Comment by dnkemper** [comment]
@joewhitsitt think I got them all. Sitenow seems to be pulling perms from sitenow_v2 split so works correctly already

**Comment by joewhitsitt** [comment]
brand has org but not panopto

**Comment by dnkemper** [comment]
@joewhitsitt done. Sorry about that. Going to take my lunch and nap haha I clearly need it. Thank you for your help!

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Looks like more needs to be done related to the embeds for HR/uiowa_bootstrap #3676. The WYSIWYG previews are gigantic and it doesn't look like the view modes are working correctly. I'd have to review how the panopto functionality changed while I was gone.

**Comment by joewhitsitt** [comment]
If this becomes a mess to support, we could potentially hold off on HR to receive this since they are looking to transition to uids_base here soon... To move this PR forward, we could remove the changes for HR and discuss it in parking lot as another slice.

**Comment by richardbporter** [comment]
This is fresh in my mind. I can take a look quick.

**Comment by richardbporter** [comment]
The preview is huge since original is the default view mode but changing it to small/medium/large seems to work for me on hawkeyemarchingband.uiowa.edu. Did you run `blt frontend`? I know @GaryRidgway did some SASS changes in #3621.

**Comment by richardbporter** [comment]
> he preview is huge since original is the default view mode but changing it to small/medium/large seems to work for me on hawkeyemarchingband.uiowa.edu. Did you run `blt frontend`? I know @GaryRidgway did some SASS changes in #3621.

Wow sorry. Just realized you said HR/uiowa_bootstrap. 🤦🏻

**Comment by joewhitsitt** [comment]
Going to test this again here shortly.

Created a draft doc: https://sitenow.stage.drupal.uiowa.edu/documentation/media/ui-capture-panopto

**Comment by joewhitsitt** [comment]
unfortunately, the latest commit to uiowa_bootstrap caused an issue with other embeds like media space:

https://hr.local.drupal.uiowa.edu/node/7076/edit

Screen Shot 2021-06-25 at 4 26 45 PM

I can help poke at this more on Monday

**Comment by GaryRidgway** [comment]
I will poke around on this today if that is alright

**Comment by GaryRidgway** [comment]
Update for posterity. Issues were observed with the panopto embed where things were not being aligned correctly and/or were not displaying at all in some configurations. Included in this there was some errant code that should have been wrapped up with the `iframe` that s now placed with it, meaning we should go back and test v3 again to make sure it is working before coming back to fix problems with HR.

**Comment by joewhitsitt** [comment]
Media - Panopto Sandbox - https://sandbox.prod.drupal.uiowa.edu/media-panopto

**Comment by GaryRidgway** [comment]
Upon further review of the [permutations that have been made on the sandbox site](https://sandbox.prod.drupal.uiowa.edu/media-panopto), a few things have come to light. 
1. With any size of video with captions, the padding around right or left aligned videos seems to be non-existent. The video should probably not bump up against text.
2. With any size of video without captions, the right aligned option does not right align the video next to text.
3.  With the `original` sizing option with no captions, the right and left aligned options do not display.

**Comment by joewhitsitt** [comment]
4. original with captions are smaller than original no captions

**Update**: marking this issue up as a #wontfix. The change in drupal-media markup is making this challenging if not impossible. Umami demo doesn't even handle this well. Adjusted the wysiwyg styles to reflect what customers can expect so hopefully the can adjust their configuration according to their needs. I will create a known issue tied to a [gh issue](https://github.com/uiowa/uiowa/issues/3725) that we can stuff in the backlog and wait for Drupal 10 to solve.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/3711#issuecomment-868843405 was fixed in uiowa_bootstrap with cf4f453

**Comment by joewhitsitt** [comment]
I have reviewed the permissions that are part of this PR and approve, but hoping someone besides Alan and I can review the work done with regard to remote video/panopto wysiwyg preview and render in uids_base and uiowa_bootstrap.

**Comment by bspeare** [comment]
Pulling to test

**Comment by bspeare** [comment]
Looking at firefox, it appears that it is not working on hr:

Screen Shot 2021-07-08 at 10 30 45 AM
Screen Shot 2021-07-08 at 10 31 02 AM

My guess is that we need a fallback query for browsers that don't support `aspect-ratio` in this line https://github.com/uiowa/uiowa/blob/a97b4aab3c7e2789952fff5e74fb77df2576a14e/docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/media/_embedded-entity.scss#L93.   Here's an example of using the fallback padding hack: https://github.com/uiowa/uiowa/blob/ae3fe9e68915ab1d3518c2a997fa9ea2273112b7/docroot/themes/custom/uids_base/scss/content/person.scss#L142-L143.

**Comment by joewhitsitt** [comment]
Darn! We were so focused on all of the different variations that we forgot browser compatibility. Nice catch @bspeare

**Comment by bspeare** [comment]
It looks like adding a caption on v2 or v3 creates this tiny thumbnail.  Should we fix that now or later?

Screen Shot 2021-07-08 at 1 42 16 PM

**Comment by bspeare** [comment]
Also looks like the fallback mobile padding needs to be updated for HR (safari, firefox):

Screen Shot 2021-07-08 at 1 50 50 PM

**Comment by joewhitsitt** [comment]
>It looks like adding a caption on v2 or v3 creates this tiny thumbnail. Should we fix that now or later?

This is a known issue and something we are avoiding for now unless you have a quick solution. https://github.com/uiowa/uiowa/pull/3711#issuecomment-869846253
https://github.com/uiowa/uiowa/issues/3725

**Comment by joewhitsitt** [comment]
> Also looks like the fallback mobile padding needs to be updated for HR (safari, firefox).

Double darn. Going to slow down this PR again and may request help from the team to deal with these outliers.

**Comment by bspeare** [comment]
@joewhitsitt I think the breakpoint I just added should fix it if you want to test it out.  Otherwise, I haven't found any more issues following the testing instructions above.

**Comment by joewhitsitt** [comment]
Thanks @bspeare. Taking a look at this and one more general pass through

**Comment by dnkemper** [comment]
Question - synced hr and masquerading as webmaster. Added panopto video. Does it matter if I can't remove the video after I add it? Or update the URL? I get I can go into source and remove it that way, just wondering if this is correct approach because when I saw the 'Edit media' button I was hoping to change URL or delete it?

**Comment by dnkemper** [comment]
^^seems to only be an issue for hr so far

**Comment by dnkemper** [comment]
Everything else looks and works as depicted. Nice work, guys!

**Comment by joewhitsitt** [comment]
>Does it matter if I can't remove the video after I add it? Or update the URL?

Similar to a media image, you should be able to select it (turning the yellow border to blue) and press the backspace to remove it. Similarly, if the cursor is in front of it within the wysiwyg you should be able to backspace to remove it just like text.

You can't edit placed media beyond alignment/size/wysiwyg caption. You have to remove and replace similar to an image.


Screen Shot 2021-07-09 at 11 03 13 AM
Screen Shot 2021-07-09 at 11 03 19 AM


 This should be the same behavior for v2/v3.

**Comment by dnkemper** [comment]
@joewhitsitt it works that way for the other sites, but for some reason, it won't let me select it in hr? It instead automatically plays video.

**Comment by dnkemper** [comment]
I can clear my cache - been a hundred years - and have to re-checkout branch anyways. I'll try it again and get back to ya!

**Comment by joewhitsitt** [comment]
Clicking on the video itself does play the video, but in all sizes there should still be some white-space that can be clicked.
Screen Shot 2021-07-09 at 11 08 31 AM

**Comment by joewhitsitt** [comment]
If you are still seeing the issue can you show me in a screen sharing session?

**Comment by joewhitsitt** [comment]
bummer. placed videos with no other wysiwyg content in HR are impossible to select

**Comment by GaryRidgway** [comment]
I am observing that if you put the videos at a small enough size that I am able to remove them. This might be able to be solved by adding padding around them so that the white space is always accessible might be a good option.

adding:
`iframe.panopto-player {
  padding: 20px;
}`

for only the wysiwyg will allow you to be able to select the edged of the player and backspace to delete it. 

additionally adding somethinging like 
`.cke_widget_wrapper.cke_widget_block.cke_widget_drupalmedia.cke_widget_focused {
    background: red;
}`

Obviously with a more tasteful color, will allow users to know for sure they are selecting the video. The key class here is the `.cke_widget_focused` class.

this does leave a portion at the bottom of the video that is cut off, but you win some you lose some. 

Screen Shot 2021-07-09 at 4 43 58 PM
This was all the investigation I was able to get done today.

**Comment by joewhitsitt** [comment]
feca8e0 fixes https://github.com/uiowa/uiowa/pull/3711#issuecomment-877307230

Added margin to top and bottom within ckeditor only to ensure that the media item is focusable and can be removed as previously designed even if it is the _only_ content with the wysiwyg. Also provides enough room to make the red (new line) available above and below the media item.

Screen Shot 2021-07-13 at 9 39 08 AM

This is a bare-bones fix to keep HR running until the switch.

**Comment by bspeare** [comment]
Pulling down to review

**Review by bspeare — APPROVED** [review]
The hr margin fix works.  I was able to edit and remove a video.   I found an additional issue for videos in cards, but I will create a separate issue for that.  Let's merge this and revisit any more bugs in the future.

**Pull request merged**
