### PR TITLE
Delete accidentally exported APR settings from split.

### PR DESCRIPTION
**Pull request by richardbporter**
This must've been exported by mistake, maybe before the ignore rule was active.

### CODE REVIEW

**Review by joewhitsitt — DISMISSED** [review]
reviewed, not tested

**Comment by pyrello** [comment]
Um... wait... don't you want this file to set defaults?

**Comment by richardbporter** [comment]
Hm. Good point. The config form sets all defaults so it works without it but yes, providing one seems like a good idea. I'm looking into it.

**Comment by richardbporter** [comment]
I can't get the config to install when enabling the split and importing. I swear this worked before.

**Comment by richardbporter** [comment]
I guess not. I reverted the last config_ignore update locally to see if something changed and it dit not make a difference. I guess ignored config in a split is not imported initially.

**Comment by richardbporter** [comment]
There is no functional change here. Mostly just want to get that dummy data out of the config.

**Comment by pyrello** [comment]
Thanks for looking into it. I guess the instances where I saw this happening previously were for default config, so that all makes sense. Although it is weird behavior in my opinion that it works one way for the default and different for a split. Might be worth opening an issue for Config Split 2.x.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
