### PR TITLE
Added icons to local tasks tabs, added weight and UIDS red color to "Delete" tab

### LINKED ISSUE #3508: Differentiate actions (especially destructive actions) in the Drupal editor menu by icon or color
Screen Shot 2021-05-10 at 8 21 23 AM

# Story

As a content editor, I find myself accidentally clicking "Delete" too often when I really want to click "Edit" or "Layout" Does the "Delete" button need to be nestled in between "Edit" and "Layout" in the top navigation in Drupal? 

# Proposed solution
Destructive actions should probably be made a bit more obvious/less "easy" to do. There is a confirmation after clicking "Delete" thankfully, but I still feel this sort of action shouldn't be as easy as it currently
 is to initiate.

Either rearrange the delete button to be at the end of the editor's top navigation, or remove it entirely and only allow a user to delete a page while in "Edit" mode or while batch editing pages.

Or differentiate all icons by color or icon like:

Screen Shot 2021-05-10 at 8 32 56 AM

### PR DESCRIPTION
**Pull request by quamsta**
Resolves: https://github.com/uiowa/uiowa/issues/3508

This is my first attempt at doing anything Drupal admin styling/hook-related, so go easy on me! Feedback would be super-appreciated. Willing to work through this with anyone who wants to help

<details>
Preview:

Screen Shot 2021-05-13 at 12 26 42 PM

I wasn't sure how to safely add any icons to the tabs in the "Classy" admin theme due to its tabs already having ::before pseudo elements, so the admin menu only changes the "Delete" tab to the UIDS red.

Screen Shot 2021-05-13 at 12 26 10 PM
</details>

# How to test

`blt ds --site=sandbox.uiowa.edu`
`yarn workspace uids_base gulp --development`

After clearing your cache, you should see icons in the main editor that looks like https://github.com/uiowa/uiowa/issues/3508#issuecomment-854094772.  But like I said, once you click into "Edit" or other admin areas, the icons do go away. Would appreciate some guidance on adding those for consistency's sake.

Thanks!

### CODE REVIEW

**Comment by joewhitsitt** [comment]
haven't tested this yet, but these local tasks can be added to either at the default level or by a site split. it would be nice if there was a default icon if no icon is specified

**Comment by pyrello** [comment]
@quamsta I fixed the PHPCS errors that were causing this to fail the build check. Here are the relevant lines in Travis: https://travis-ci.com/github/uiowa/uiowa/builds/225937197#L1545-L2075. I also refactored the logic for adding the icon classes.

**Comment by bspeare** [comment]
@quamsta I made some slight color and sizing adjustments to use some mixins and variables in `admin.scss`.

**Comment by dnkemper** [comment]
May I move forward with testing this?

**Comment by bspeare** [comment]
@dnkemper Let's hold off until the meeting tomorrow.

**Comment by dnkemper** [comment]
okay! Thank you, @bspeare

**Comment by bspeare** [comment]
Denny mentioned that MAUI is using the the "eye" icon for their "View" page tab.   So we might want to go with the eye instead of the globe for some campus consistency?  The changes I pushed up do have the eye in there.

**Comment by mark-bennett-uiowa** [comment]
Pulling down for testing.

**Review by mark-bennett-uiowa — APPROVED** [review]
Seems to be working as advertised. New icons and color appear on admin task buttons:
Screen Shot 2021-06-04 at 4 54 42 PM

The icons do disappear when editing:
Screen Shot 2021-06-04 at 4 58 38 PM

- Focus on Delete button only underlines the text and changes background color, doesnt darken the icon like the other task buttons.
- Flux Capacitor icon looks like another PR, so didnt see that.

**Comment by quamsta** [comment]
This is awesome!! Thanks all for collaborating on this and accepting this pull request. :)

**Pull request merged**
