### PR TITLE
Hotfix for unstyled unauthorized page in SiteNow Intranet

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

```
ddev blt ds --site intranet.shl.uiowa.edu
```
- Change `FALSE` to `TRUE` in line `62` of `docroot/sites/intranet.shl.uiowa.edu/settings/local.settings.php`
- Visit https://shlintranet.uiowa.ddev.site and confirm that the page is not unstyled.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Preliminary testing indicates that this does solve the SHL Intranet issue.

**Comment by pyrello** [comment]
I just realized that my test instructions assume that CSS aggregation settings are normal for Student Life, but they are not.

**Comment by pyrello** [comment]
Updated docs to reference SHL intranet instead since the settings there are still normal.

**Review by joewhitsitt — APPROVED** [review]
I tested a bit differently for both shl and student life. 

Synced the sites on main, toggled the local settings aggregation to reproduce the broken styles. Pulled the branch. Reloaded to see the styles working. Checked out main again, did a hard refresh to see things broken again.

**Pull request merged**
