### PR TITLE
Feature: Updated AoS coursework label

### LINKED ISSUE #5554: Update AoS Course Work label
As an Admissions site owner, I would like to use the label "Coursework" on AoS pages rather than "Course work" to better align with upcoming University style guide changes.

# Additional Info
https://admissions.uiowa.edu/academics/accounting

Update
- [x] https://admissions.uiowa.edu/admin/structure/types/manage/area_of_study/fields/node.area_of_study.field_area_of_study_course_work
- [x] Make sure "Course Work" isn't used elsewhere on our end.

# Proposed Solution

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5554. 

# How to test

- Make sure that the updated text is correct.

### CODE REVIEW

**Comment by makurj** [comment]
Pulling down to test.

**Comment by makurj** [comment]
Would this be considered an AoS page: https://admissions.uiowa.ddev.site/academics/education (node 3136)
image

**Comment by bspeare** [comment]
@makurj that looks like a text area.  https://admissions.uiowa.edu/academics/actuarial-science is a page that uses the field name.

**Comment by makurj** [comment]
Thanks, Ben!

**Comment by bspeare** [comment]
@makurj that is another text area.  They will have a lot of manual work to change these through https://admissions.uiowa.edu/admin/find-text.

**Comment by makurj** [comment]
Yep, that's what I was using and boy, there are so many results! Checked the code for "Course Work", nothing found, so I'll go ahead and approve.

**Review by makurj — APPROVED** [review]

**Pull request merged**
