### PR TITLE
[Migration] Public files path option

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #6868 

# How to test

Sync a CCOM site locally using DevDesktop. (if you have just gotten access to the CCOM application, in DevDesktop you may need to click More > Refresh Acquia Cloud Sites in order to get it to appear)

```
ddev blt ds --site=default && ddev drush @default.local config-split:activate sitenow_migrate -y && ddev drush @default.local uli /admin/config/sitenow/sitenow-migrate 
```

Complete the config page using the help text.
For the new "Public Files Path", it should be something like "sites/**medicine.uiowa.edu.internalmedicine**/files" where the bolded should match the multisite designation in devdesktop. (You can also log into the site and visit `/admin/config/media/file-system` to check)

```
ddev drush @default.local ms
```
Check that migrations, particularly the `d7_file` migration, are registered.

```
ddev drush @default.local mim d7_file --limit=10
```
Feel free to adjust the `limit`, or remove it to import all files.

Check for no errors
Check the https://default.uiowa.ddev.site/admin/content/media, and see that media entities have been created for the imported files

Try syncing a uiowa70x site and hooking up, running the files migration _without_ filling in the public files path, and see that it works (a code review may also be sufficient, and that the logic should in that case match `initializeIterator` in https://api.drupal.org/api/drupal/core%21modules%21file%21src%21Plugin%21migrate%21source%21d7%21File.php/class/File/8.9.x)

### CODE REVIEW

**Comment by bspeare** [comment]
@cory-skeers does the person testing this need CCOM access to their Acquia application?

**Comment by cory-skeers** [comment]
> @cory-skeers does the person testing this need CCOM access to their Acquia application?

Yes, the tester will need to be able to access their Acquia application in order to pull it down to DevDesktop. The Signage group in AC was added, so people who had not had access previously may now have access.

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Not sure if this is related or not, but in grabbing the CCOM assets, they don't have a file extension. There is not thumbnail, but i can can place the media item. I get an error trying to resave the entity.

Screenshot 2023-10-06 at 1 29 09 PM

With the 703 migration, thumbnails for most appear. I can re-save, etc.

I am going to test with another site but need to step away again for a bit.

**Comment by cory-skeers** [comment]
> Not sure if this is related or not, but in grabbing the CCOM assets, they don't have a file extension.
> I am going to test with another site but need to step away again for a bit.

Thanks @joewhitsitt!

I'd originally tested with anesthesia and internalmedicine and they worked fine from what I'd checked, if you want to try with one separate from those.

What site were you running into this with? I'd be curious to take a look, and try and determine if it's something we want to try and account for, whether by appending extensions where there aren't ones, or skipping if there's something wrong with them in the source.

In the past we've run into issues where files had the wrong extensions, but in those cases, the file copy operation is smart enough to account for and correct it, we just end up with extra noise in the message logs. In this case, if we can at least tell that it's an image, we may even be able to just slap a `.jpg` at the end of it if we can't easily tell the specifics and let it handle things from there.

**Comment by joewhitsitt** [comment]
Still away from my desk but I originally picked immunology but realized it now redirects.. Switched to dermatology and got some headshot files migrated over. Yes, I will test more sites in a bit with a fresh setup

**Comment by joewhitsitt** [comment]
Perhaps it was just something weird with dermatology. Much better results with alumni

Screenshot 2023-10-06 at 2 47 29 PM

**Review by joewhitsitt — APPROVED** [review]
The scope of the PR works. Nice find and nice solution!

**Pull request merged**
