### PR TITLE
Link to edit webform embedded in paragraphs

### LINKED ISSUE #566: Provide a link to a webform embedded with paragraphs
When editing a webform bundle. To get to the edit webform page easier.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #566

### CODE REVIEW

**Comment by cory-skeers** [comment]
AJAX handling of the link update and the $element field selections are a little clunky. Any feedback or suggestions for alternate approaches appreciated.

**Comment by joewhitsitt** [comment]
@richardbporter was this what you were thinking for #566 ?

**Review by richardbporter — APPROVED** [review]

**Comment by richardbporter** [comment]
Yes.

**Comment by richardbporter** [comment]
Seems to be working fine for me.

**Pull request merged**
