### PR TITLE
[Pharmacy] State bug fix

### LINKED ISSUE #7336: State field not appearing when adding people on Pharmacy Alumni Directory
# Problem
The state field appears when adding a person of type Palliative Care Graduate but not when adding a person without a person type or with any other person type.

Pharmacy recently expanded from just a palliative care alumni directory (https://pharmacy.uiowa.edu/pharmd/dual_cert/palliative/certificate_graduates) to having an all alumni directory (https://pharmacy.uiowa.edu/alumni/alumni-directory).

It seems like we just need to remove the conditional logic for showing only when the palliative care type is chosen so the state field always is available. They only add people that are alumni because they are using Directory Profiles for all other person directories.

# Steps to reproduce

# Proposed solution

- remove the conditional logic for showing state field only when the palliative care type is chosen so the state field always is available.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves  https://github.com/uiowa/uiowa/issues/7336

# How to test

```
ddev blt ds --site=pharmacy.uiowa.edu && ddev drush @pharmacy.local uli /node/5981/edit
```
- Confirm that State field is always available

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@briand44 should we make hometown visible to all types as well?

**Comment by briand44** [comment]
>should we make hometown visible to all types as well?

Good question. I'm not sure if they plan to use that field for all alumni or not. It probably doesn't hurt to make it available otherwise we could reach out to Barb and Kayla and find out from them.

**Comment by bspeare** [comment]
The hometown field is disabled on the form.  It has never been in use on Pharmacy.   I can remove it from allowed fields to avoid future confusion.

**Review by joewhitsitt — APPROVED** [review]
Sounds like potentially more cleanup for pharmacy hometown field down the road if they aren't using it. Reviewed, not tested.

**Pull request merged**
