### PR TITLE
i2358 - coronavirus v2 to v3 

### PR DESCRIPTION
**Pull request by dnkemper**
Relates to #2358

- Updated config split to not include v2

# How to test

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Screen Shot 2021-02-10 at 11 55 01 AM
I am getting an error locally trying to save an existing page:

`Drupal\Core\Entity\EntityStorageException: The "field_block:node:page:field_page_content_block" plugin does not exist.`

Update: some pages still the v2 content blocks placeholder in layout builder
`This block is broken or missing. You may be missing content or you might need to enable the original module.`

**Comment by pyrello** [comment]
At this point, I I'm wondering if might make the most sense to just roll these updates into #3048?

**Comment by joewhitsitt** [comment]
I can do that

**Comment by joewhitsitt** [comment]
Closing in favor of #3048

**Pull request closed without merging**
