### PR TITLE
Fix env check for GA settings.

### LINKED ISSUE #278: Google Analytics does not appear to work
The tracking js that does seem to load is the uiowa_bar stuff, not the Google Analytics module tracking code. gis.sites has both for test purposes and I am the owner of the site-specific tracking id.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #278.

### CODE REVIEW

**Comment by richardbporter** [comment]
@joewhitsitt Can you pull and run a `drush cim` to see if GA is uninstalled for you? May require a `cr` first....

**Comment by richardbporter** [comment]
Actually I don't think it worked...

**Comment by richardbporter** [comment]
@joewhitsitt That might have done it.

**Comment by joewhitsitt** [comment]
```
The import failed due to the following reasons:                              
  Configuration <em class="placeholder">google_analytics.settings</em> depend  
  s on the <em class="placeholder">Google Analytics</em> module that will not  
   be installed after import.
```


`blt ds --site=gis.sites.uiowa.edu` after `cr`

**Comment by richardbporter** [comment]
We can't use Config Split to handle installing this module because it is listed for Config Ignore and that will aways take precedence.

**Comment by richardbporter** [comment]
Another option would be to put this in the global settings file, but having test coverage for this is not a bad thing.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
