### PR TITLE
Create README.md for sitenow.uiowa.edu

### PR DESCRIPTION
**Pull request by joewhitsitt**
## Description
Create readme for sitenow.uiowa.edu similar to our other custom sites (brand, hr).

### CODE REVIEW

**Comment by richardbporter** [comment]
Not a big fan of these. They get out of date quickly.

**Comment by richardbporter** [comment]
👎 

A CRM feels more appropriate for this stuff. Also, primary/secondary devs change, leave, etc. and our team should be able to handle support for any site.

**Comment by joewhitsitt** [comment]
Where is the CRM? Until then where should this info live then?

**Comment by joewhitsitt** [comment]
Closing PR in favor of https://github.com/uiowa/uiowa/issues/861

**Pull request closed without merging**
