### PR TITLE
Classrooms - Additional Updates

### LINKED ISSUE #6477: Additional Classroom updates
- [x] alphabetize order of rooms on unit pages - https://classrooms.prod.drupal.uiowa.edu/units/office-registrar
    - see if there is a workable solution without a split, otherwise split it.
- [x] Building names - lower case `and, of`
- [x] ~alphabetize order of technology features~ done
- [x] display number of results on search page - this is a nice to have not absolutely necessary.
- [x] display 4 items on room schedule rather than 3
- [x] remove extra space before colon as seen in https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474
- [x] lessen space between sections as seen in https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves  https://github.com/uiowa/uiowa/issues/6477

# How to test

```
ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local uli ucc-1100
```

- Check alphabetized order of rooms on unit pages - https://classrooms.prod.drupal.uiowa.edu/units/office-registrar
  - `ddev drush @classrooms.local uli units/office-registrar`
   - Review code at https://github.com/uiowa/uiowa/commit/9d737fee928f20527e311fd612ec713cb413951d
- Test building names - lower case `and, of`
  - Review code in `ClassroomsCoreCommands.php`
  - Delete room config in `config/sites/classrooms.uiowa.edu`, then `ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local classrooms_core:buildings && ddev drush @classrooms.local config-split:export site` to test.  
- Test the display number of results on search page
  - `ddev drush @classrooms.local uli find-university-classroom`
  - Review code `hook_views_pre_render()` in `classrooms_core.module`
- Test display 4 items on room schedule rather than 3 
  - `ddev drush @classrooms.local uli ucc-1100`
- Test that extra space before colon has been removed https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474
  - `ddev drush @classrooms.local uli abw-112`
- Test that space is lessened between sections as seen in https://github.com/uiowa/uiowa/issues/6477#issuecomment-1592069474
  - `ddev drush @classrooms.local uli abw-112`

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Should I commit the deleted KRC and SQ buildings (post-import)? I am guessing no since there is room content associated with those. Kirkwood Regional Center and South Quad.

**Comment by bspeare** [comment]
@joewhitsitt that is a little weird.  Why would they suddenly delete?

**Comment by joewhitsitt** [comment]
Hmm. KRC is here https://api.maui.uiowa.edu/maui/api/pub/registrar/courses/AstraBldgRmCompleteList/list but SQ is not. Going to try again after cache rebuild.

**Comment by joewhitsitt** [comment]
KRC is not matching the filtering anymore. Region List is gutted compared to what we are checking against in the import:

```
      $filters = [
        '1) University Classrooms - Level 1',
        '1) University Classrooms - Original',
        '1) University Classrooms',
        '1) University Classrooms - Study Space',
        '1) Programmed Classrooms - Level 2',
        'Classroom-Programmed',
      ];
```

SQ is just straight up missing.

Not related to this PR, but we will want to make sure we aren't removing a building they need before they are ready to remove it: https://github.com/uiowa/uiowa/issues/6557

**Comment by joewhitsitt** [comment]
Crap. I opened the PR. I approve but can't approve. ✅  Thanks for figuring out the small slices to these issues.

**Comment by bspeare** [comment]
@joewhitsitt does that mean you would approve if you could?

**Comment by joewhitsitt** [comment]
yes

**Review by bspeare — APPROVED** [review]
Approving on behalf of @joewhitsitt

**Pull request merged**
