### PR TITLE
Feature: Add SiteImprove module

### PR DESCRIPTION
**Pull request by pyrello**
Adds the SiteImprove Plugin module to the collegiate split, along with associated exported configuration.

### CODE REVIEW

**Comment by pyrello** [comment]
@mjoneill As part of the configuration of the module, it is asking for a token. I'm assuming this will need to be unique per site?

**Comment by mjoneill** [comment]
> @mjoneill As part of the configuration of the module, it is asking for a token. I'm assuming this will need to be unique per site?

OK. Looking into it.  Below are the resources they pointed me to. Adding.

> Here is an article that shows how to set up the API.  I am also including an article on testing the plugin once set up.   If you have any issues let me know and we can help with the set up.  
>  
> How to connect the API: https://support.siteimprove.com/hc/en-gb/articles/360016564611-How-to-connect-to-the-Siteimprove-API
> How to test the CMS plugin: https://support.siteimprove.com/hc/en-gb/articles/360008673838-How-to-test-the-Siteimprove-CMS-Plugin

@pyrello

**Comment by mjoneill** [comment]
@pyrello I'm going through and setting up the API key, etc according to the docs.

**Comment by joewhitsitt** [comment]
This collegiate split has the a-z list permissions. Is this intentional. Also, was this supposed to go out to uiowa.edu too? If so, it has a separate webmaster split https://github.com/uiowa/uiowa/blob/master/config/uiowa.edu/user.role.webmaster.yml

**Comment by pyrello** [comment]
Thanks @joewhitsitt. I'll take a look.

**Comment by pyrello** [comment]
That should be fixed now. As a side note: It seems that when using a site that has its own site split to export to a feature split, you can sometimes end up with items getting exported to the feature split that shouldn't be there.

**Review by richardbporter — CHANGES_REQUESTED** [review]
I think this PR is missing the collegiate split blacklist for siteimprove. I got an error syncing uiowa.edu locally.

**Comment by pyrello** [comment]
@richardbporter Good catch! Will fix.

**Review by richardbporter — APPROVED** [review]
I went ahead and added the blacklist to collegiate. Didn't really test it out too much.

**Comment by pyrello** [comment]
@richardbporter Thanks!

**Pull request merged**
