### PR TITLE
Feature: Footer logo regression, unstyled div text, article list regression

### LINKED ISSUE #1810: Theming of <div> text
Relates to #1660 

## Problem
In uiowa_bootstrap, there is some theming at the body{} level which carries forward to text in `<div>` tags.
image

In uids_base, the `<div>` tags don't get the full theming, and the spacing is tight.
image

### LINKED ISSUE #1811: Footer logo appears smaller in SiteNow sites
What the footer logo is supposed to look like:
Screen Shot 2020-06-19 at 11 09 44 AM
What it looks like on SiteNow sites:
Screen Shot 2020-06-19 at 11 09 38 AM

According to @bspeare this is most likely a conflict with `sitenow.css`.

### LINKED ISSUE #1844: Regression with mobile card view of articles in uids_base
# Problem 

Recent updates removed the bottom border from the mobile view of the card list for paragraphs. 

Screen Shot 2020-06-24 at 3 51 40 PM

# Proposed Solution

Update CSS so that bottom border is only removed at `sm` breakpoint.

### PR DESCRIPTION
**Pull request by bspeare**
In this PR fixes related to https://github.com/uiowa/uiowa/issues/1660.

Resolves https://github.com/uiowa/uiowa/issues/1844
Resolves https://github.com/uiowa/uiowa/issues/1811
Resolves https://github.com/uiowa/uiowa/issues/1810

`blt frontend` 

# How to test https://github.com/uiowa/uiowa/issues/1844
Check articles list and events list on hawkeyemarchingband.local.drupal.uiowa.edu and verify that bottom border appears on the list view at wide desktop width and mobile view.  Make sure that there is not an extra line near the "more" button at the bottom of the list. 

Screen Shot 2020-06-25 at 11 12 47 AM
Screen Shot 2020-06-25 at 11 12 16 AM

# How to test https://github.com/uiowa/uiowa/issues/1810

Test a `<div>` of text on a text paragraph on hawkeyemarchingband.local.drupal.uiowa.edu, a basic page on uiowa.local.drupal.uiowa.edu and on a text area block on uiowa.local.drupal.uiowa.edu  and verify that the div is styled like a paragraph:

Screen Shot 2020-06-25 at 11 14 49 AM
Screen Shot 2020-06-25 at 11 14 29 AM
Screen Shot 2020-06-25 at 11 13 29 AM

# How to test https://github.com/uiowa/uiowa/issues/1811

Change uids_base header to display inline and below the logo and make sure that the footer logo remains looking like this screenshot below at a wide desktop breakpoint. 

Screen Shot 2020-06-25 at 11 17 59 AM

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling this down now

**Review by joewhitsitt — APPROVED** [review]
Everything checked out. I don't think the wysiwyg has the div styles though.

**Comment by bspeare** [comment]
@joewhitsitt Thanks for reviewing.  Is there a better way to scope that `div` so that the wysiwyg sees it?

**Comment by joewhitsitt** [comment]
@cory-skeers knows the wysiwyg styles the most. He might have quick answer.

**Comment by joewhitsitt** [comment]
maybe scoping to `.cke_editable` would cover it but not be in the way

**Comment by bspeare** [comment]
@joewhitsitt It looks like the `sitenow_wysiwyg.scss` file needs to be updated to grab the `uids_base` version of the paragraph component.  Updating that now.

**Pull request merged**
