### PR TITLE
Initialize sanderlab.lab.uiowa.edu multisite on uiowa03

### PR DESCRIPTION
**Pull request by cory-skeers**
# How to test

### CODE REVIEW

**Comment by bspeare** [comment]
Is it worth seeing if they are interested in moving to `sander.lab.uiowa.edu` to reduce duplicate "lab" in the name?

**Comment by bspeare** [comment]
Is it worth seeing if they are interested in moving to sander.lab.uiowa.edu to reduce duplicate "lab" in the name?

**Comment by cory-skeers** [comment]
> Is it worth seeing if they are interested in moving to `sander.lab.uiowa.edu` to reduce duplicate "lab" in the name?

Good point! I hadn't read that closely past that it was an existing lab site.

I'll reach out!

**Comment by cory-skeers** [comment]
Converting to draft until doing some cleanup and re-submitting with the approved sander.lab.uiowa.edu domain.

Great catch, @bspeare!

**Review by joewhitsitt — APPROVED** [review]
Looks good. Saw that the db in AC was removed

**Comment by cory-skeers** [comment]
Thanks @joewhitsitt!

**Pull request merged**
