### PR TITLE
Upgrade node_revision_delete

### LINKED ISSUE #6347: remove revision module paypal link
# Problem
When deleting a revision I get to a page where I am asked to make a donation to the module owners paypal. Is there a way to remove this link? 

image

# Steps to Reproduce

1. Edit any page that has historical edits
2. click on Revisions
3. select Delete from the dropdown next to a revision

### PR DESCRIPTION
**Pull request by joewhitsitt**
Alternative to #6226
Resolves https://github.com/uiowa/uiowa/issues/6347
Relates to #6381 

_Note: some content types are configured with a different number of revisions to keep._

# To Test

- Pick a content type to test. They should all be updated and match their previous settings. Sync the site that has the content type. 
- There should be no issues with the database update or config import.
- Create some revisions of the content. Try manually deleting a revision.
- Create more than the limit and run cron to see what is cleaned up.
- There should still be a message that displays the current limit for the content type.
- Donation link of #6347 should be gone
- _Note the ability to delete prior revisions of the revision you are deleting is no longer a feature. Most of the drush commands have also been removed._

### CODE REVIEW

**Comment by pyrello** [comment]
> Note the ability to delete prior revisions of the revision you are deleting is no longer a feature. Most of the drush commands have also been removed.

Did we decide we were cool with this functionality going away for the meantime? I can't remember.

**Comment by joewhitsitt** [comment]
I haven't recorded any opinion from the team. I am personally okay with it. Most types are set at 10 revisions or less so I don't think the amount of revisions is too overwhelming. It was helpful when we were manually cleaning up coronavirus to switch from v2 to v3.

**Comment by briand44** [comment]
I was also ok with it going away as long as the team wasn't concerned with the loss of drush commands

**Comment by pyrello** [comment]
> as long as the team wasn't concerned with the loss of drush commands

I'm not sure I can remember ever using one of these commands.

**Comment by e-marie-w** [comment]
Pulling down to test.

**Comment by e-marie-w** [comment]
Just to double-check, I should be testing every custom content type we have?

**Comment by joewhitsitt** [comment]
You can see from the files changed that the changes were fairly uniform across sites/content types, so I think testing the default types and maybe one or two others should be enough test coverage. If you see something that stands out, dive-deeper.

**Comment by e-marie-w** [comment]
I'm noticing that we have some content types that don't use node revision delete, like thesis defense. Just wondering if it was purposeful, since I can still delete revisions for it.

**Comment by pyrello** [comment]
I don't think it was purposeful.

**Review by e-marie-w — APPROVED** [review]
Tested article, page, person on default and sandbox
Tested area of study, event, and transfer tips on admissions
Tested building on facilities
Tested mentor on grad
Tested FAQ on hr
Tested opportunity on sppa
Tested book on uipress

All of them worked as expected. I could manually delete a revision, and running cron removed the oldest revisions so the number of revisions matched the limit. Looking at the changes, I can see the content types retained the correct limit number. 

Only thing of note is I often had to drop the local database before I could sync a site successfully, I guess I had a lot of gremlins. 

I can make another comment with a list of content types that don't use node revision delete, if that's something we're interested in knowing.

**Pull request merged**
