### PR TITLE
Feature: uids_base events/footer/safari fixes

### PR DESCRIPTION
**Pull request by bspeare**
In this PR:

Update to uids_base theme to address:
- https://github.com/uiowa/uids/issues/93

UIDS bump that includes fixes for:
- https://github.com/uiowa/uids/issues/95
- https://github.com/uiowa/uids/issues/91
- https://github.com/uiowa/uids/issues/90
- https://github.com/uiowa/uids/issues/89

# How to test

1. Safari scroll issues

Go to https://uiowa.local.drupal.uiowa.edu in Safari and scroll up and down in multiple spots.  There use to be a 40 pixel gap occurring in the right side of the scrollbar and this gap should be gone now. 

2. Footer Updates

- Verify that footer icon no longer appears next to phone number.   
- Verify that there is an updated footer socket menu (see screenshot below)

Screen Shot 2020-04-07 at 12 56 18 PM

3. Event Updates

- Verify that Events background pattern on https://uiowa.local.drupal.uiowa.edu is a white brain pattern after clearing your browser cache. 

4.  Card refactor

Edit the cards on https://uiowa.local.drupal.uiowa.edu and verify that you can:

- Verify that the link buttons on the cards are rendering with a faux link button and that entire card is clickable
- Verify that `aria-describedby` is added to heading link `a` and `aria-hidden=true` is added to faux button
- Remove the photo and save the block and verify that the block renders without an image or image markup
- Remove the link text and save the block and have the block render without a faux link button
- Remove the title and save the block and have the block render without a title
- Remove link url and save the block and have the block render without a link
- Remove title while having a link url and verify that entire block is clickable

### CODE REVIEW

**Comment by bspeare** [comment]
- [x] Image path for brain background has an extra slash that needs to be removed

**Comment by pyrello** [comment]
I tested all these scenarios, and the only one I ran into issues with is:

> Remove the link text and save the block and have the block render without a faux link button

When I do that, I see this:
Screen Shot 2020-04-07 at 10 45 11 PM

It looks like the link is still being rendered:
```html
<div aria-hidden="true" id="desc-a-card" class="bttn bttn--outline bttn--tertiary bttn--sans-serif">
  /
  <svg class="svg-inline--fa fa-arrow-right fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-right" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path></svg><!-- <i class="fas fa-arrow-right"></i> -->
</div>
```

**Comment by bspeare** [comment]
@pyrello I added a fix for the empty card title text here: https://github.com/uiowa/uiowa/pull/1329/commits/e30a98ed800fa0b6931adb4a798066a4aea278d0.  And updated the template to accommodate this adjustment here: https://github.com/uiowa/uiowa/pull/1329/commits/5985df6997745358ac2cb87631a3babf09f8567e. 

Regarding the events icon, I added a font-awesome field to the events block here that defaults to the map icon: https://github.com/uiowa/uiowa/pull/1329/commits/f82282446e5998fa1946d72721c6c5ace6607aeb and https://github.com/uiowa/uiowa/pull/1329/commits/eb5d9ce7b4640c01d4f42796259f6f002950d73e.

**Review by pyrello — APPROVED** [review]
Looks good!

**Pull request merged**
