### PR TITLE
Remove blt:init:settings from sync.commands.

### PR DESCRIPTION
**Pull request by richardbporter**
https://github.com/acquia/blt/issues/4428

# Testing
- On main, run `blt sync --site sandbox.uiowa.edu`
- See that the output from Drush is syncing the default site, not sandbox.
- Check out this branch and run it again.
- See the correct site is synced.

We could leave this out permanently as it doesn't really need to run per-site for every sync. People would just need to remember to run `blt bis` to regenerate local.settings.php files when necessary.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
not going to pretend to know how/why the no-op addition but this works as described. do we need to update docs as part of this so folks get muscle memory with new sites, new setups?

**Comment by richardbporter** [comment]
> not going to pretend to know how/why the no-op addition but this works as described. do we need to update docs as part of this so folks get muscle memory with new sites, new setups?

Yea probably. I can do that.

**Comment by quamsta** [comment]
Ran into the blt problem this morning, tested this branch and it seems to work as expected. Guess this means bacon, lettuce, and tomato is back on the menu?

**Comment by richardbporter** [comment]
@joewhitsitt What do you think of those changes?

**Comment by joewhitsitt** [comment]
Looks fine to me.

**Comment by joewhitsitt** [comment]
Crud. I tried ds sandbox from main. `Could not look up database name for @self`

**Comment by joewhitsitt** [comment]
Duh Joe! read the docs...

**Pull request merged**
