### PR TITLE
Bug fix to resolve checkbox/radio mobile positioning

### LINKED ISSUE #6252: Webform checkboxes need style adjustments for mobile/small columns
# Problem
As reported on https://sociology.prod.drupal.uiowa.edu/alumni/join-alumni-career-network longer input labels break to a new line under the checkbox.  

Screenshot 2023-03-09 at 11 15 14 AM

# Proposed solution
- Adjust webform css by changing to absolutely positioned checkboxes or another choice.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6252. 

```
ddev blt frontend &&  ddev blt ds --site=sandbox.uiowa.edu
```

Go to https://sandbox.uiowa.ddev.site/form and try to overstuff the checkbox form and radio labels with long text.  Verify that the label wraps like the screenshot below.  Test on other combinations that you can think of. 

Screenshot 2023-05-17 at 12 19 58 PM

### CODE REVIEW

**Comment by cory-skeers** [comment]
It looks like the side by side option is broken
image

The `inline-flex` for the side-by-side option is being overwritten by the `flex`:
image


Still doing a bit more testing, but thus far, everything else seems to be working as expected, and is a nice improvement!

**Comment by cory-skeers** [comment]
With long text and descriptions, the behavior changes slightly:
Existing
desktop
image

mobile
image


change
desktop
image
mobile
image


I don't think it's a problematic change, but the adjustment to placement of description text does seem unintentional, and either needs to be addressed or a decision to make that change.

**Comment by cory-skeers** [comment]
From my testing, this is good to go, other than getting some eyes on https://github.com/uiowa/uiowa/pull/6460#issuecomment-1553214524 and either adjusting or deciding to move forward with that change in description placement.

**Comment by bspeare** [comment]
Thanks for testing @cory-skeers, I'd like to take another look at this when I get back.

**Comment by bspeare** [comment]
@cory-skeers I updated these to look better - what do you think?

Desktop:

Screenshot 2023-05-22 at 8 50 56 AM

Mobile:

Screenshot 2023-05-22 at 8 50 14 AM

**Comment by cory-skeers** [comment]
> I updated these to look better - what do you think?

@bspeare I think that looks great--thanks for updating!

**Comment by bspeare** [comment]
This is ready to review again and I updated https://sandbox.uiowa.ddev.site/form with some more complex examples like the ones @cory-skeers found.

**Review by cory-skeers — APPROVED** [review]
Looks good! Thanks for taking the second pass at it, and the bonus sandbox testing updates!

**Comment by bspeare** [comment]
Thanks @cory-skeers!

**Pull request merged**
