### PR TITLE
uiowa.edu - Lazy Loading Images

### PR DESCRIPTION
**Pull request by joewhitsitt**
Related to #697 but only for uiowa.edu

block image gallery and block vertical video need work. getting these others in for now

### CODE REVIEW

**Comment by bspeare** [comment]
I'm having a quirk in my local environment.   Can someone test updating the banner block on https://uiowa.local.drupal.uiowa.edu/node/41/layout with a new photograph and then save the block and layout?  The image won't show up unless I manually clear the cache on the site. Is this just a local caching issue?

**Comment by bspeare** [comment]
@joewhitsitt Is there anything visual that you noticed that Blazy does to the images or does it just lazy load them in the background?

**Comment by joewhitsitt** [comment]
Darn. I noticed the same thing with updating images... I will search the issue queue

No visual was set (didn't want to mess with styles), I think it reserves the space for the image though. The noticable difference is the markup changes and light house doesn't complain about the images loaded by blazy.

**Comment by joewhitsitt** [comment]
Going in a different direction.

**Pull request closed without merging**
