### PR TITLE
Hotfix - update webform permissions, change email body format

### PR DESCRIPTION
**Pull request by joewhitsitt**
Alternative solution to https://github.com/uiowa/uiowa/pull/6983 that supports fancy twig

~~Waiting to hear if the temporary changes on homepage PROD fix the issue.~~
>Looks good to me. https://iowaweb.slack.com/archives/C0164FNN1PV/p1697230776123299?thread_ts=1697227165.958019&cid=C0164FNN1PV

Here is the new format. The toolbar is very similar to Minimal+ but underneath allows things like `style` tags.
Screenshot 2023-10-13 at 3 53 32 PM

### CODE REVIEW

**Comment by joewhitsitt** [comment]
waiting for drupal infrastructure to clear up: https://drupal.slack.com/archives/C51GNJG91/p1697216702727009?thread_ts=1697058461.444399&cid=C51GNJG91

✅

**Comment by pyrello** [comment]
I've reviewed the code updates and they look good. Since there are not specific test instructions, is this meant as review only? Or would you like it tested?

**Comment by joewhitsitt** [comment]
Review only is fine since the fix is already in PROD for uiowa.edu and being used. Thanks

**Review by pyrello — APPROVED** [review]
Reviewed, not tested. Approving based on fix already being tested in production.

**Pull request merged**
