### PR TITLE
Admissions SEO settings for custom content types

### LINKED ISSUE #3215: Add SEO settings for Area of Study CT
Setup basic SEO settings for the aos content type. Meta description and the related SEO description fields should have a default "[Area of Study Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

### LINKED ISSUE #3216: SEO settings for Admissions
# Story

As an admissions user, I want to be able to configure the SEO settings for the available custom content types

# Proposed solution

Setup basic SEO settings for custom admission content types. Meta description and the related SEO description fields should have a default "[Admissions Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

- [x] Setup SEO settings for the AOS content type #3215 
- [x] Setup SEO settings for the Student Profile content type #3218
- [x] Setup SEO settings for the Scholarship content type #3217

### LINKED ISSUE #3217: Add SEO settings for the Scholarship CT
Setup basic SEO settings for the scholarship content type. Meta description and the related SEO description fields should have a default "[Scholarship Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

### LINKED ISSUE #3218: Add SEO settings for the Student Profile CT
Setup basic SEO settings for the student profile content type. Meta description and the related SEO description fields should have a default "[Student Profile Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

### PR DESCRIPTION
**Pull request by pyrello**
# Updates

* Resolves #3215 
* Resolves #3217 
* Resolves #3218
* Resolves #3216 
* Added `field_meta_tags` to Areas of Study, Scholarship, and Student Profile content types.
* Added description meta tag default overrides for Areas of Study, Scholarship, and Student Profile content types.
* Added relevant new configuration to Admissions and Scholarship splits.
* Re-exported everything.

# How to test

* `blt ds --site=admissions`
* `drush @admissions.local uli admin/people` and masquerade as a webmaster.
* Visit http://admissions.local.drupal.uiowa.edu/node/1141/edit (Area of Study) and confirm you can edit SEO Settings.
* Visit http://admissions.local.drupal.uiowa.edu/node/561/edit (Scholarship) and confirm you can edit SEO Settings.
* Visit http://admissions.local.drupal.uiowa.edu/node/821/edit (Student Profile) and confirm you can edit SEO Settings.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
Anyone know of other sites besides Admissions using the Scholarship content type?

Update: Scholarship is "active" on grad but it doesn't exist?!

**Review by joewhitsitt — APPROVED** [review]
Thanks for the stealth work on this.

I couldn't add enable/import of the scholarship feature on default because the field instance was missing. Fixed.
Split the metatag.settings because there are content type specific settings as to which metatag groups are available. Not every content type needs schema article, person.

Retested on default, grad, admissions

**Comment by pyrello** [comment]
> Update: Scholarship is "active" on grad but it doesn't exist?!

@joewhitsitt Scholarships are renamed Fellowships on Grad College.

**Pull request merged**
