### PR TITLE
[Commencement] Venue theming

### LINKED ISSUE #7591: Theme commencement venues
# Additional Info

They mentioned that they plan to use the body field to add content similar to the Information and Polices on https://commencement.uiowa.edu/venue/carver-hawkeye-arena. This and the additional information collection sections and items is the most important info.

Address info, map and directions link would be next most important info.

List of upcoming events is more for internal use and can be lower on page.

Have some concerns about the potential for lots of scrolling and if so would like some sort of built in anchor links to the address/map/directions section and the upcoming events section. These could possibly exist on the featured image banner if necessary?

```[tasklist]
### Tasks
- [x] Display image as featured image banner
- [x] Content above additional information sections (body)
- [x] Ceremony information
- [x] Map
- [x] Venue Directions link
- [x] Upcoming events
- [x] Confirm/Address any issues with heading structure
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7591

```
 ddev blt frontend && ddev blt ds --site=commencement.uiowa.edu && ddev drush @commencement.local en devel_generate && ddev drush @commencement.local devel-generate:content 50 --bundles event && ddev drush @commencement.local uli /venue/carver-hawkeye-arena
```

# How to test

- Code review
- Add featured image
- Test directions link
- Test events and map link
- Test mobile view

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
i don't think the blocks below have the `map` and `events` id attributes to work with the links.

**Comment by bspeare** [comment]
> i don't think the blocks below have the `map` and `events` id attributes to work with the links.

Did they get removed in the merge?  https://github.com/uiowa/uiowa/pull/7659/commits/7a74a1e5e2614a98f617badaf585c54d24222017

**Comment by joewhitsitt** [comment]
oh gosh. sorry. my mergetool got messed up

**Review by joewhitsitt — APPROVED** [review]
Okay. Looks good to me, but based on my merge fiasco, someone might want to double check my commits more.

**Comment by bspeare** [comment]
Thanks @joewhitsitt !

**Pull request merged**
