### PR TITLE
[Contact] URL alias path

### LINKED ISSUE #8151: Add url alias pattern for contact nodes
# Story

As a site owner using the contact feature, I would like to have my contact nodes live at `/contact/[node:title]` rather than `[node:title]` so these paths don't conflict with existing paths.

# Additional Info

Request coming from Registrar but seems like this change could be valuable for the feature.

https://registrar.prod.drupal.uiowa.edu/transcripts-verifications is an example url that Registrar shared.

### PR DESCRIPTION
**Pull request by GaryRidgway**
# How to test

1. Sync registrar
2. Create a piece of "Contact" content
3. Observe that its automatically generated alias is at `contact/[node:title]`

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Review by bspeare — APPROVED** [review]
It works!

**Comment by joewhitsitt** [comment]
Was this issue groomed with updating existing as well or do they know to re-save to trigger the alias update?

Update: realized registrar only has two pieces of contact content.. nvm.

**Comment by GaryRidgway** [comment]
> Was this issue groomed with updating existing as well or do they know to re-save to trigger the alias update?
> 
> Update: realized registrar only has two pieces of contact content.. nvm.

It wont be, but also I emailed them and told them I would edit those pieces of content for them and they said that was fine

**Pull request merged**
