### PR TITLE
[Commencement] Venue only displays events in default session

### LINKED ISSUE #7672: Only show upcoming events for default session on venues
# Story

As a Commencement site owner, I would only like to show events for the default session on Venue pages.

# Additional Info

I think we are showing all events for a particular venue currently. https://commencement.prod.drupal.uiowa.edu/venue/carver-hawkeye-arena

Link to the ceremonies list in case they need to see past/future session ceremonies for a particular venue.

# Proposed 

- [x] Limit view results to the configured "default" session - through views relationship or preprocess
- [x] If view title/heading is still "Upcoming Events", change to something like "Events at [node:title]" or "Ceremonies at [node:title]"
- [ ] Add a link to the ceremonies landing page so visitors can easily see all ceremonies

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #7672 

# How to test
```
ddev blt ds --site commencement.uiowa.edu && ddev drush @commencement.local uli "admin/content?type=venue"
```
- Review venues and confirm that they are only showing events from the current session
- Pick another session and set it as the default by editing and selecting that option: https://commencement.uiowa.ddev.site/admin/structure/taxonomy/manage/session/overview
- Review venues again and confirm that they are only showing events from the session you selected.
- Check https://commencement.uiowa.ddev.site/ceremonies to make sure it is still setting the default session correctly.

### CODE REVIEW

**Comment by e-marie-w** [comment]
Everything is working great! One question, though. The issue mentions having a link to all ceremonies, do we still want to add that?

**Comment by pyrello** [comment]
> Everything is working great! One question, though. The issue mentions having a link to all ceremonies, do we still want to add that?

Good catch. I'll add that.

**Comment by pyrello** [comment]
> > Everything is working great! One question, though. The issue mentions having a link to all ceremonies, do we still want to add that?
> 
> Good catch. I'll add that.

Done.

**Review by e-marie-w — APPROVED** [review]
Venues correctly only display events from the current session. The events update when the current session is switched, same as the ceremonies page. Awesome job!

Note: when first syncing the ceremonies page shows every event ever but I believe that is because a default is not yet set on prod, as whenever I set one it updates fine.

**Pull request merged**
