### PR TITLE
Added content moderation to book content type

### LINKED ISSUE #4769: UI Press - Add content moderation to book content type
# Proposed solution
Refer to how content moderation is setup for the page content type and recreate that for the book type.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #4769 

# How to test

1. blt ds --site=uipress.uiowa.edu
2. drush @uipress.local uli
3. when you go to add a new book, should see options to put said book in draft/review/publish states
4. When you edit the existing book, you should be able to change new versions to draft

### CODE REVIEW

**Comment by e-marie-w** [comment]
I can test this!

**Comment by dnkemper** [comment]
Thank you, @e-marie-w 🥳

**Comment by e-marie-w** [comment]
Everything is working for me, I just want to understand one thing before I approve. In `core.entity_view_display.node.book.default.yml` the `id: system_breadcrumb_block` was replaced with `id: 'extra_field_block:node:book:content_moderation_control'`. And it works, and the breadcrumbs even still work. I just don't follow how. Does the new moderation section also handle what that breadcrumb section was doing?

**Comment by dnkemper** [comment]
> Everything is working for me, I just want to understand one thing before I approve. In `core.entity_view_display.node.book.default.yml` the `id: system_breadcrumb_block` was replaced with `id: 'extra_field_block:node:book:content_moderation_control'`. And it works, and the breadcrumbs even still work. I just don't follow how. Does the new moderation section also handle what that breadcrumb section was doing?

I actually just swapped the order of the fields - instead of removing the breadcrumbs completely. I wanted to follow what other content types did with the moderation field? 🤷🏼‍♀️

**Comment by dnkemper** [comment]
so here is where I added the breadcrumbs: https://github.com/uiowa/uiowa/pull/4988/files#:~:text=components%3A-,4b702de6%2Df99e%2D4ad8%2D8681%2D6781533bfa8f%3A,-uuid%3A%204b702de6%2Df99e

**Comment by e-marie-w** [comment]
Omg it was literally RIGHT THERE and my brain kept skipping over that part, I am SO sorry. Approving now!

**Comment by dnkemper** [comment]
@e-marie-w haha BEEN THERE! It happens to all of us 🤗

**Review by e-marie-w — APPROVED** [review]
Works as expected! Within Edit, newly created books, along with books in draft or review state, can be set as draft, review, or published. Published books can be set to draft, published, or archived. Archived books can be set to published or draft. Within View, archived, draft, or review status can be changed without needing to go to edit. This successfully works and has same status options to as when in Edit. 

Awesome job Dani!

**Comment by dnkemper** [comment]
Thank you so much, @e-marie-w 🥳

**Comment by e-marie-w** [comment]
Thank YOU for being patient with me @dnkemper, you're awesome!

**Pull request merged**
