### PR TITLE
Facilities named building content type + view

### LINKED ISSUE #5803: Searchable named buildings list
# Story

As a Facilities site owner, I would like to display a searchable list of FM managed named buildings so that visitors can quickly find named buildings.

# Additional Information

- [x] Should be able to be placed on a layout builder page so that editors can add additional contextual content.
- [x] Should output honoree and building name (title).
- [x] Should be able to sort by and search each of the fields being output.
- [x] Building name should render as a link to named building entity.
- [x] Change content type from 'Place' to 'Named Building' (change machine name fromplace to named_building).
 ~~- [ ] Add preprocessing logic and field templates to finish getting the node LB template looking like the pages that were built out.~~
- [x] change honoree name field to two fields, first, last name. 
- [x] make table display for searchable named buildings list  "last, first"
- [x] store building ID on "Named Building" content type
- [x] Correct label of "Aeriel" view. It is misspelled. 

Endpoint - https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
Existing code - /docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/includes/facilities_buildings.building_named_building.inc
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/facilities_buildings.module
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_core/facilities_core.module (API call)

Existing site - https://www.facilities.uiowa.edu/named-buildings

Example of individual named building on new site - https://facilities.prod.drupal.uiowa.edu/philip-d-adler-journalism-and-mass-communications-building

# Questions
How do we want to handle linking to these manually created pages? I think on the current site these are all created with a similar url structure (named-building/[BuildingCommonName] but that could create issues if the content isn't managed appropriately. We will want to let Facilities know how we intend to move forward here so they can update url aliases if needed.

What technology/JS libraries to use for search/sort functionality.

# Proposed Solution

### PR DESCRIPTION
**Pull request by pyrello**
Resolves https://github.com/uiowa/uiowa/issues/5803
- Adds a building content type and standard configuration elements.
- Add a building list block view.

# How to test

- `ddev blt ds --site facilities.uiowa.edu`
- `ddev drush @facilities.local cim --source ../config/sites/facilities.uiowa.edu --partial`
- `ddev drush @facilities.local en facilities_core`
- `ddev drush @facilities.local cim` (makes the workflow change stick)
- (one line option: `ddev blt ds --site facilities.uiowa.edu && ddev drush @facilities.local cim --source ../config/sites/facilities.uiowa.edu --partial -y && ddev drush @facilities.local en facilities_core && ddev drush @facilities.local cim -y`)
- General content type standards in place: https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes
  - Permissions, moderation, seo (mix of metatag and schema.org), alias pattern.
- Honoree (first last) displayed on node.
- Honoree (last, first) displayed on views block.

### CODE REVIEW

**Comment by pyrello** [comment]
We are holding off on doing more work on this until we can run it by @briand44.

**Comment by GaryRidgway** [comment]
I am getting some errors to start with here, is tere supposed to be a module that I am missing here? I thought moderation control was core?

https://github.com/uiowa/uiowa/pull/5934/files#diff-d452e29826fd31acc7c01358e5ae0e72c2ed9d81cbdc6c2eeb1e53b0d0e8c072R61-R71

Screen Shot 2022-11-18 at 12 00 46 PM

**Comment by joewhitsitt** [comment]
@GaryRidgway have you tried the `cr` that has been mentioned a few times recently: https://github.com/uiowa/uiowa/pull/5596#issuecomment-1320290850

**Comment by GaryRidgway** [comment]
Clearing cache on the facilities site did not fix it, no.

**Comment by bspeare** [comment]
@GaryRidgway did you try the `cr` immediately after the sync?

**Comment by GaryRidgway** [comment]
Everything should be done here, we shouldn't need to do anything with the "Building" content type in this PR, correct? (NOTE: this is not the "Nameb Building" content type)

**Comment by briand44** [comment]
I don't think there ever will be a "building" content type. The building pages will be dynamically displayed from the data in the APIs.

**Comment by joewhitsitt** [comment]
Got the troublesome preprocess to work. I switched it to a preprocess on the field (name) that then gets the last name value, changes the label and appends the last name if it exists.

I can look at this tomorrow to see if the old field has been cleaned up, that the module is enabled and getting the last, first display and sorting working on the views block.

**Comment by joewhitsitt** [comment]
I know that not all of this is in scope as it relates to https://github.com/uiowa/uiowa/issues/5803 but since this will be merged together I had a look at the content type overall and have some notes:

- The help text on the image field is not particularly helpful: _"An image of the item. This can be a [URL](https://schema.org/URL) or a fully described [ImageObject](https://schema.org/ImageObject)."_
- The year built field is within the Honoree fieldset instead of next to the building fields.
- The Aerial link has optional text. Can we just take the link and provide a consistent label?
- Though it is in layout builder and the styling is not in-scope, the title is not rendering.
- If it is supposed to have moderation, that is not present on the form. If it is just supposed to be published/unpublished, webmasters don't have the ability to un-publish.
- The SEO settings are wired up to use the summary (token), but that field is not available to the editor. Looks like the description field is then used.
  - Schema Article, Schema Webpage and Site Verification SEO settings are available to webmasters. 
- Achievements are currently a bulleted list, but the minimal format does not yet have that formatting option.
- Since existing page content already exists, unless those are deleted first as part of the process, named buildings are going to get a `-0` url alias (e.g. philip-d-adler-journalism-and-mass-communications-building-0)
- Webmasters can't add revision messages.
- Sitemap is not setup

I am probably going to make some of these changes unless I missed a conversation about why we aren't addressing this or that.

**Comment by pyrello** [comment]
> I am probably going to make some of these changes unless I missed a conversation about why we aren't addressing this or that.

I think I thought I had gotten this closer to being done and I represented it that way so we didn't go in-depth on what additional work needed to be done. My apologies.

**Comment by joewhitsitt** [comment]
I think this is ready for review.

**Comment by bspeare** [comment]
Pulling to test.

**Comment by bspeare** [comment]
# Initial review

- Consider using `_sitenow_node_form_defaults()` - This puts certain shared fields in the sidebar.
  - Can we put the image field in the sidebar form?
- Moderation
  - I don't see any moderation settings showing up on the content type. As @joewhitsitt said "If it is supposed to have moderation, that is not present on the form. If it is just supposed to be published/unpublished, webmasters don't have the ability to un-publish." 
  - Webmasters can't add revision messages.

**Comment by bspeare** [comment]
Are we able to exclude "United States" from the display here?  This drupal.org issue seems possibly relevant https://www.drupal.org/node/2753899. 

Screen Shot 2022-11-30 at 10 29 27 AM

**Comment by bspeare** [comment]
The building list block view needs the `table-responsive` class applied to it.

**Comment by bspeare** [comment]
The testing instructions say "Honoree (first last) displayed on node." Is that something to check?  I don't see the (first last) displaying on node.

**Comment by joewhitsitt** [comment]
Thanks for these @bspeare I will pull down and see what needs to be addressed or clarified.

**Comment by bspeare** [comment]
I made some adjustments to the mobile exposed filter in https://github.com/uiowa/uiowa/pull/5934/commits/bb40f4813765fbed2213109bae98b46a9aa61459 after testing out the building search page and noticing all the space. 

Before:

Screen Shot 2022-11-30 at 11 22 16 AM

After: 

Screen Shot 2022-11-30 at 11 21 42 AM

**Comment by joewhitsitt** [comment]
updated the instructions to include the module enable (fixes the honoree field display (first last). moved the image to the sidebar. looking into the address field issue. might have uncovered a bigger problem with our existing functionality around it https://github.com/uiowa/uiowa/issues/4569. trying to figure out why the editorial workflow config is not sticking

**Comment by bspeare** [comment]
All the changes listed in https://github.com/uiowa/uiowa/pull/5934#issuecomment-1332565866 look great. 

**Additional questions:**

- Does it need access to a menu?
- Disable promote to front page unless your custom content type needs it?
- Teaser view?  What's the bare minimum that we want to set with new content types?
- Only the street address is required?  Is there a reason that one field is the only one set to required?

**Comment by joewhitsitt** [comment]
Still need to add the table-responsive right?

>Does it need access to a menu?

No

> Disable promote to front page unless your custom content type needs it?

It is unchecked on the content type settings and Webmaster and below don't have the ability.

> Teaser view? What's the bare minimum that we want to set with new content types?

Good question. This content isn't referenced at this point (doesn't event have tags) so is that out of scope until it is?

> Only the street address is required? Is there a reason that one field is the only one set to required?

I noticed this. The named building seems to only have the one line. @pyrello any insight on this decision.

As for the United States address issue, https://github.com/uiowa/uiowa/pull/5934#issuecomment-1332435371

We have an issue for this related to person content type. I can test the patch, but the issue discussion doesn't seem very healthy.

https://github.com/uiowa/uiowa/issues/4569

Danielle had a PR with a field by field solution using a css class. The address field template is expecting a value and doesn't have any kind of if check around it which causes issues if there is a preprocess unset on it.

**Comment by bspeare** [comment]
@joewhitsitt thanks for making the changes.  I think this looks to be in good shape.  Do we want to try to fix any of the stuff listed in https://github.com/uiowa/uiowa/pull/5934#issuecomment-1332698808?

**Comment by joewhitsitt** [comment]
Actually, the patch from https://www.drupal.org/project/address/issues/2753899#comment-12982080 works pretty well. I didn't encounter the issues the following comments reported. If we went with it, we should probably re-save all of our address fields (across splits) to make sure the functionality is registered correctly whether or not the option is used.

**Comment by bspeare** [comment]
@joewhitsitt should we make a separate issue for that patch work and testing?

**Comment by joewhitsitt** [comment]
Conversed with Ben in DMs. Based on that, only the address issues remain (displaying United States, and why are we only capturing address_line1)?

For the United States issue, I think we should prioritize https://github.com/uiowa/uiowa/issues/4569

For the only capturing address_line1 issue, we are waiting to hear from @pyrello about the initial reasoning, but I don't think it is a blocker if we decide to open it up after content is starting to be added on PROD.

**Comment by pyrello** [comment]
> For the only capturing address_line1 issue, we are waiting to hear from @pyrello about the initial reasoning, but I don't think it is a blocker if we decide to open it up after content is starting to be added on PROD.

There was no reasoning. It was work done quickly. Don't assume that it was intentional :)

**Comment by pyrello** [comment]
> @joewhitsitt should we make a separate issue for that patch work and testing?

I think the patch work should be done separately.

**Comment by pyrello** [comment]
> > For the only capturing address_line1 issue, we are waiting to hear from @pyrello about the initial reasoning, but I don't think it is a blocker if we decide to open it up after content is starting to be added on PROD.
> 
> There was no reasoning. It was work done quickly. Don't assume that it was intentional :)

It seem like maybe we should just use a text field here since it is just showing the street address.

**Comment by bspeare** [comment]
@pyrello if we switch to text field, will we lose the schema?

```


"address": {
--
  | "@type": "PostalAddress",
  | "addressCountry": "US",
  | "streetAddress": "200 University Services Building"
  | }

```

**Comment by pyrello** [comment]
> @pyrello if we switch to text field, will we lose the schema?
> 
> ```
> 
> 
> "address": {
> --
>   | "@type": "PostalAddress",
>   | "addressCountry": "US",
>   | "streetAddress": "200 University Services Building"
>   | }
> ```

I think we could map the text field to `streetAddress`. We aren't including the whole address though, anyways, so I'm not sure if that would be meaningful on its own.

This might be a good question for @mjoneill. Since these pages are not going to be canonical (the generated building pages would be, I think), then we may actually just want to point at the canonical source for the address or the whole listing?

**Comment by cory-skeers** [comment]
> > @pyrello if we switch to text field, will we lose the schema?
> > ```
> > 
> > 
> > "address": {
> > --
> >   | "@type": "PostalAddress",
> >   | "addressCountry": "US",
> >   | "streetAddress": "200 University Services Building"
> >   | }
> > ```
> 
> I think we could map the text field to `streetAddress`. We aren't including the whole address though, anyways, so I'm not sure if that would be meaningful on its own.
> 
> This might be a good question for @mjoneill. Since these pages are not going to be canonical (the generated building pages would be, I think), then we may actually just want to point at the canonical source for the address or the whole listing?

I think this could still use discussion/answering, but in the meantime, I was going to pull down for some testing and review.

**Comment by cory-skeers** [comment]
> > > @pyrello if we switch to text field, will we lose the schema?
> > > ```
> > > 
> > > 
> > > "address": {
> > > --
> > >   | "@type": "PostalAddress",
> > >   | "addressCountry": "US",
> > >   | "streetAddress": "200 University Services Building"
> > >   | }
> > > ```
> > 
> > 
> > I think we could map the text field to `streetAddress`. We aren't including the whole address though, anyways, so I'm not sure if that would be meaningful on its own.
> > This might be a good question for @mjoneill. Since these pages are not going to be canonical (the generated building pages would be, I think), then we may actually just want to point at the canonical source for the address or the whole listing?
> 
> I think this could still use discussion/answering, but in the meantime, I was going to pull down for some testing and review.

Update from daily scrum: Make the switch, add it as partial schema for now, and after there is a canonical source available, we can update to link the schema at that point.

**Comment by cory-skeers** [comment]
Updated the address field to a textfield, and looks like it validates correctly as a "PostalAddress" for the building.

> * Achievements are currently a bulleted list, but the minimal format does not yet have that formatting option.

^ Re-noting this from an earlier comment, just so it doesn't get lost in the shuffle of other changes.

**Comment by cory-skeers** [comment]
We have a few named buildings with more than one honoree that we'll need to account for:

https://www.facilities.uiowa.edu/named-building/blank-honors-center
image

At least at this time, it looks like in all cases both honorees share a last name, so partly can be input as\
```
First Name: John and Jane
Last Name: Doe
```
and this would work for both the individual page as well as the view (matching current view, even). But the Honoree label, photo, and honoree years might need some additional thought.

The First Name, Last Name also works with current honorees, but is not future-proof if we get honorees who do not share a last name.

**Comment by cory-skeers** [comment]
Minimal change needed for multiple honorees, assuming last names are always shared, it can be on the content editor except for the photo.

Example on page:
image

Example view:
image

**Comment by cory-skeers** [comment]
Reviewed and tested, and think this is looking great.

Would love other thoughts on best way to handle the case of multiple honorees, but otherwise I think this is good to go 👍

**Comment by bspeare** [comment]
Good find on the multiple honorees @cory-skeers! I think the photo can be creatively adjusted to fit both into that space.  I think your solution sounds good unless we want to future-proof this for multiple honorees with different names.

**Comment by briand44** [comment]
I don't know that we need to future proof it at this point.

>Achievements are currently a bulleted list, but the minimal format does not yet have that formatting option.

Do we have an issue for this? Seems like we may need to fast track this before the content can be moved.

**Comment by bspeare** [comment]
@briand44 here is the issue to prioritize: https://github.com/uiowa/uiowa/issues/5472

**Comment by cory-skeers** [comment]
> I think the photo can be creatively adjusted to fit both into that space

For this do you mean adjusting the field to allow up to two images, and the adjustment being handled on the display side?

**Comment by bspeare** [comment]
@cory-skeers I just mean some creative Photoshop work to make the two pictures look good in that space.

**Comment by cory-skeers** [comment]
> @cory-skeers I just mean some creative Photoshop work to make the two pictures look good in that space.

Ah...Gotcha.

In that case, I think this is good to be merged, with #5472 getting prioritized and #5962 for styling followup.

**Review by cory-skeers — APPROVED** [review]

**Pull request merged**
