### PR TITLE
i3786 - Genetics - Adapt Thesis Defense content type from grad.uiowa.edu split

### LINKED ISSUE #3786: Genetics - Adapt Thesis Defense content type from grad.uiowa.edu split
Story: As a site owner, I want to publish information about upcoming student thesis defenses.

# Proposed solution
* Move configuration related to the Thesis Defense content type, Views calendar and list displays, as well as anything else related to these from the Grad College split to a feature split.
* Write an update hook for Grad College to turn the split on.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3786 

# How to test

1. `blt ds --site=grad.uiowa.edu` - make sure thesis_defense content still exists and the thesis_defense config split is turned on
2. `blt ds --site=genetics.grad.uiowa.edu` - make sure thesis_defense content can be added - doesn't error on save

### CODE REVIEW

**Comment by dnkemper** [comment]
@joewhitsitt from my understanding w/ your comment [here](https://github.com/uiowa/uiowa/issues/3786#issuecomment-883593231), we push this out then finish migrating over the thesis defense items?

**Comment by joewhitsitt** [comment]
Yeah I commented that but immediately thought someone would comment and make a case for the the other way. 🤷

**Comment by dnkemper** [comment]
@joewhitsitt haha well dang... I agreed with you 🤷‍♀️

**Comment by dnkemper** [comment]
Imma do it all - never wrote an update hook for a d8 module. Now sounds like the perfect time to start 😅

**Comment by cory-skeers** [comment]
I can pull this down to test!

**Comment by dnkemper** [comment]
Yay! Thank you so much, @cory-skeers 🥳

**Review by cory-skeers — APPROVED** [review]
Update hook worked, and thesis defense content is available for both sites, save without errors, and have the correct permissions.

💯

**Comment by pyrello** [comment]
I'm still going to review this for config split organization best practice.

**Comment by pyrello** [comment]
I fixed a couple things that would have caused problems:
* Status of feature splits needs to be `status: false`. Otherwise the split will be turned on by default for every site.
* Added the feature split status to config ignore so that it would not get reverted (and the split turned off) on a subsequent code deployment.

**Pull request merged**
