### PR TITLE
ITS - Site Split and Service Content Type

### LINKED ISSUE #6666: ITS Services content type
# Story

As an ITS webmaster, I would like to to be able to create service content so that services can be dynamically displayed to our users.

# Additional Info

**Existing mockups - based on initial feedback**
All services page: https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy
Results page: https://sandbox.prod.drupal.uiowa.edu/results-page
Services page: https://sandbox.prod.drupal.uiowa.edu/its-service-office-365-mockup

**Fields we are fairly confident ITS needs**
Title
Also known as (alias/synonym/alternate name)
Description/Body/teaser
Need a way to feature
Way to designate audience
Service category
Related services

Fees?
Website?
Quick Links?

# Proposed Solution

- [x] Setup site split
- [x] Create content type and path alias according to https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes
- [x] layout builder

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/6666

# To Test

```
ddev blt ds --site=its.uiowa.edu && ddev drush @its.local config:import --source ../config/sites/its.uiowa.edu --partial && ddev drush @its.local cim && ddev drush @its.local cr && ddev drush @its.local uli admin/structure/types/manage/service/display/default/layout
```

- Upon `uli`, you should see the moderation control block within the layout builder display settings without errors.
- As an editor/publisher/webmaster, you can add/edit any service.
- As a publisher/webmaster, you can delete a service. As an editor, you can delete your own service.
- Basic metatag and schema.org ([Service](https://schema.org/Service)) output should be present in the DOM.
- Alias should match the /services/[node:title] pattern as discussed here: https://github.com/uiowa/uiowa/pull/6801#issuecomment-1686991745

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling to test

**Comment by pyrello** [comment]
I think the path alias for these should be `services/[node:title]`. I know that is different than the old site, but I think its better information organization.

**Comment by pyrello** [comment]
> As an editor/publisher/webmaster, you can add/edit a service.

As an editor, I can add the service, but I'm limited to the states that I can set it to: Draft and Review. Is that correct?

**Comment by pyrello** [comment]
> As a publisher/webmaster, you can delete a service.

As a publisher, I can delete my own service. Is that what is meant?

**Comment by pyrello** [comment]
> As a publisher/webmaster, you can delete a service.

As an editor, I can delete my own service. Is that what is meant?

**Comment by joewhitsitt** [comment]
>I think the path alias for these should be services/[node:title]. I know that is different than the old site, but I think its better information organization.

Maybe we should discuss this with them. It would also require a redirects migration. Their current site is using https://its.uiowa.edu/all-services-and-software as the landing page so /services would be a 404 if folks deconstructed the URL path in the hopes of "going back." They also currently have a breadcrumb redirect that adds to the mess.

>As an editor, I can add the service, but I'm limited to the states that I can set it to: Draft and Review. Is that correct?

Correct.

>As an editor, I can delete my own service. Is that what is meant?

"As a publisher/webmaster, you can delete *any* service." is what I meant, but "As an editor, I can delete my own service" should also be true based on the permissions config.

**Comment by pyrello** [comment]
> > I think the path alias for these should be services/[node:title]. I know that is different than the old site, but I think its better information organization.
>
> Maybe we should discuss this with them. It would also require a redirects migration. Their current site is using https://its.uiowa.edu/all-services-and-software as the landing page so /services would be a 404 if folks deconstructed the URL path in the hopes of "going back." They also currently have a breadcrumb redirect that adds to the mess.

It would be my intention to change the services landing page to just `/services`. If we don't establish a pattern like that, then we are stuck having to try to engineer a breadcrumb solution. I think we should recommend these updates to them.

A redirect migration is probably necessary no matter what because I'm not sure that we can be 100% sure that all the path aliases will get generated the same. I have encountered examples where the slug is different in D7 vs D9.

**Comment by joewhitsitt** [comment]
Fair enough. I'll make that change and we can shop it with them as we develop the content type further.

**Review by pyrello — APPROVED** [review]

**Comment by pyrello** [comment]
Works as advertised. Thanks for the adjustments!

**Pull request merged**
