### PR TITLE
Update P2LB block default styles

### LINKED ISSUE #5317: Update all block default styles `_sitenow_p2lb_block_styles`.
# Problem

New defaults and new block styles have been added since `_sitenow_p2lb_block_styles` was created. 

# Proposed solution

Update block styles in https://github.com/uiowa/uiowa/blob/39a060f31600e9c593b6ac0d9cb64098b77a9309/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L1099 and make sure that new and existing defaults are up to date.  Look for the existing defaults in https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module and compare those against p2lb.

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves #5317 

# How to test

`ddev blt ds --site=hawkeyemarchingband.uiowa.edu`
`ddev drush @hawkeyemarchingband.local en sitenow_p2lb`
`ddev drush @hawkeyemarchingband.local config-split:activate p2lb`
Go to `https://hawkeyemarchingband.uiowa.ddev.site/admin/content` and select a page to convert to p2lb.

## How to test style updates
- Convert a page with cards
  - Verify that subtitle field is rendered within the subtitle card block field and not the body.
  - Verify that the text format is rendered as `minimal` and that the buttons in the blocks on https://hawkeyemarchingband.uiowa.ddev.site/ render as links and not styled buttons. 
  - Verify that the card is converted to a block that has the `card: border` style applied to it. 
## How to test blockquote
- Create a page with a series of blockquote paragraphs and convert it (blockquotes within the WYSIWYG will not be converted). 
  - Verify that the quotes convert to the blockquote block type and not into a text area. 
  - Verify that the converted quote style is left-aligned.
  - Add your opinion on this question on the blockquote alignment options: https://github.com/uiowa/uiowa/blob/3f2a67c01819546713650377ed489c336f619b2d/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L474

## How to test more paths

Either the v2 split needs to then be disabled, or the following code needs to be updated locally to avoid the v2 check: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1240 (eg manually set $is_v2 to FALSE before the check). In either case, a `drush cr` is likely needed after as well.

- Convert a page with Articles and People paragraphs and check:
  - The 'include more link' converts correctly
  - If a link is included but no path is provided, the default more path is properly used
  - If a link is included and a path is provided, that this path replaces the default path

### CODE REVIEW

**Comment by cory-skeers** [comment]
@e-marie-w I went a little rogue and checked out the `@todos` re: the more paths, and I think they should now be working correctly for articles and people blocks.

**Comment by GaryRidgway** [comment]
While reviewing this I got a couple errors for `strtoupper()` that looked like this:

`Warning: strtoupper() expects parameter 1 to be string, array given in Drupal\views\Plugin\views\query\Sql->addOrderBy() (line 1054 of core/modules/views/src/Plugin/views/query/Sql.php).`

Additionally, when I tried to convert a couple of block quotes that were in the same text area it just output a text area with two block quotes in it.

Cards worked fine though!

**Comment by bspeare** [comment]
@GaryRidgway do you still have screenshots on "Additionally, when I tried to convert a couple of black boots that were in the same text area it just output a text area with two block quotes in it."?

**Comment by GaryRidgway** [comment]
> @GaryRidgway do you still have screenshots on "Additionally, when I tried to convert a couple of black boots that were in the same text area it just output a text area with two block quotes in it."?

OOPS. Sorry, speech to text is not always 100% accurate lol, fixed in original comment!

**Comment by bspeare** [comment]
Thanks! I thought that could have also been "black buttons" or something.

**Comment by GaryRidgway** [comment]
After the change that been made in the instructions I believe this to be working. The only thing that I can think of is that if you set a block quote fluid that he will stay on the same section as the next block ", but that is not really a big problem at all.

I have tested cards articles and block quotes.

**Review by GaryRidgway — APPROVED** [review]

**Comment by e-marie-w** [comment]
The blockquote fluid thing is a little weird but I believe the staying in the same section thing is supposed to be the equivalent to that fluid option, for now at least.

Thanks for testing it!

**Pull request merged**
