### PR TITLE
[Classrooms] a11y filter

### LINKED ISSUE #6560: Accessibility features filter on Classrooms search page
# Story

As a Classrooms website owner, I would like users to be able to filter classrooms by accessibility features so they can easily find rooms that meet their needs.

# Additional Info

They want the ability to select multiple accessibility features

We have discussed possibly moving the filters to the side to better accommodate all of the filters.

# Proposed solution

- Expose filter
- Allow multiple to be selected
- Move filters to sidebar?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6560

This pr moves `Better Exposed filter` and `Calendar` styles to their own libraries and I have attached those libraries to each site using those modules instead of loading all of that CSS for any page with a view. 

# How to test

```
ddev blt frontend && ddev blt ds --site=classrooms.uiowa.edu && ddev blt ds --site=admissions.uiowa.edu && ddev blt ds --site=housing.uiowa.edu && ddev blt ds --site=iisc.uiowa.edu && ddev blt ds --site=ighn.international.uiowa.edu && ddev blt ds --site=iowasummerwritingfestival.uiowa.edu && ddev blt ds --site=sandbox.uiowa.edu && ddev blt ds --site=grad.admissions.uiowa.edu && ddev blt ds --site=education.uiowa.edu && ddev blt ds --site=grad.uiowa.edu &&  ddev drush @classrooms.local uli find-university-classroom && ddev drush @admissions.local uli areas-of-study && ddev drush @housing.local uli residence-halls && ddev drush @iisc.local uli projects && ddev drush @internationalighn.local uli home && ddev drush @iowasummerwritingfestival.local uli events && ddev drush @sandbox.local uli people && ddev drush @admissionsgrad.local uli areas-of-study && ddev drush @education.local uli areas-study/program-finder && ddev drush @grad.local uli academics/thesis-defenses 
```

Test new filter and layout on:
- https://classrooms.uiowa.ddev.site/find-university-classroom
  - Does it work?
  - Are items listed alphabetical?
  - Can you select multiple items for filtering?
  - Check mobile and desktop functionality
  - Check result count position - is it under the pager?
  - Test checkboxes
  - Test submit and reset filters at all breakpoints
  - Test "filters" toggle open/close spacing on mobile and desktop
- Test for regressions on https://classrooms.uiowa.ddev.site/spaces/programmed-classrooms. 

## Other sites affected by these style changes

Test for:

- Visual regresssions
- Test checkboxes
- Test submit and reset filters at all breakpoints
- Test "filters" toggle open/close spacing on mobile and desktop

Urls to check:
- https://iowasummerwritingfestival.uiowa.ddev.site/events
- https://oniowa.uiowa.ddev.site/events
- https://admissions.uiowa.ddev.site/events/calendar
- https://admissions.uiowa.ddev.site/events
- https://admissions.uiowa.ddev.site/areas-of-study
- https://admissions.uiowa.ddev.site/counselors
- https://housing.uiowa.ddev.site/residence-halls
- https://iisc.uiowa.ddev.site/projects
- https://internationalighn.uiowa.ddev.site/
- https://sandbox.uiowa.ddev.site/people
- https://grad.uiowa.ddev.site/academics/thesis-defenses
- https://education.uiowa.ddev.site/areas-study/program-finder

### CODE REVIEW

**Comment by e-marie-w** [comment]
Pulling down to test.

**Comment by e-marie-w** [comment]
I'm still working my way through testing classrooms, but I've got one question and one possible issue. 

Question - does the result count being under the pager only apply to desktop? Because on mobile it appears before the results for me.

Issue - the technology filter is behaving weird. For other filters with a select all option, the results will auto-reload after selecting it. For technology it doesn't. What's weirder, though, is the search button becomes unclickable so I can't force it to reload that way either. And none of the other filters auto-reload works after this, so I have to click reset or otherwise reload the page to get anything to work again.

**Comment by bspeare** [comment]
Thanks @e-marie-w, I will check on those!

**Comment by bspeare** [comment]
@e-marie-w I updated it to display the results count in the header like the screenshot below.  After looking at a number of sidebar filters, it looks like a common UX convention to place the results above the content. 

Screenshot 2023-07-06 at 4 00 32 PM

**Comment by bspeare** [comment]
@e-marie-w can you describe what steps you took to get to the "technology filter" acting weird?  I'm not seeing anything and maybe you could demo it for me?

**Comment by bspeare** [comment]
@e-marie-w showed me the issue and here is the database log error.  Anyone have any thoughts on this error? https://www.drupal.org/project/views/issues/3040090, https://drupal.stackexchange.com/questions/290422/using-taxonomy-exposed-filter-in-a-view-ends-in-mysql-can-only-use-61-tables-in#comment363756_290451

`
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Room list[room_list]: SQLSTATE[HY000]: General error: 1116 Too many tables; MySQL can only use 61 tables in a join: SELECT COUNT(*) AS "expression" FROM (SELECT 1 AS "expression" FROM "node_field_data" "node_field_data" LEFT JOIN "node__field_room_technology_features" "node__field_room_technology_features_value_0" ON node_field_data.nid = node__field_room_technology_features_value_0.entity_id AND node__field_room_technology_features_value_0.field_room_technology_features_target_id = :views_join_condition_0 LEFT JOIN "node__field_room_technology_features" "node__field_room_technology_features_value_1" ON node_field_data.nid = node__field_room_technology_features_value_1.entity_id AND 
...
`

Update: checking "reduce duplicates" removes the error...

**Comment by joewhitsitt** [comment]
>Update: checking "reduce duplicates" removes the error...

But what new problem does that create? Is a room with more than one of the multi-select filters listed multiple times in the result?

An alternative check would be if any of the filters (taxonomy) have "show hierarchy," "depth" or whatever configured.

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I did try the hierarchy option and it had the same issue.  I will test the downside of "reduce duplicates".

**Comment by joewhitsitt** [comment]
to clarify, to check to make sure they don't have it checked.

**Comment by bspeare** [comment]
I think "Technology Features" is failing because it has the most entries.   All other settings are the same.   Maybe we remove the option to select all?  Running a select all on the technology features seems a bit overboard.

**Comment by joewhitsitt** [comment]
For consistency, should select all be removed from the others as well? I can't imagine the use-case where someone would select all vs just leaving them unselected as they are treated like ORs.

**Comment by e-marie-w** [comment]
Small regression for https://oniowa.uiowa.ddev.site/events, filters display vertically instead of horizontally in desktop
Screenshot 2023-07-07 at 1 20 53 PM
vs. https://oniowa.uiowa.edu/events

wait the filters are different too uhhh let me resync

**Comment by e-marie-w** [comment]
> Small regression for https://oniowa.uiowa.ddev.site/events, filters display vertically instead of horizontally in desktop 
> wait the filters are different too uhhh let me resync

Resync fixed it! The search and reset buttons are side by side instead of two separate rows like some of the other sites now have.

**Review by e-marie-w — APPROVED** [review]
New filter looks and works as expected on classrooms. Other sites affected by the style changes still look and work as expected also. 

A few sites don't have a reset button, so I really like the flex change that has the search button fill the space on mobile view, it looks nicer.

Thanks for the patience as I slowly made my way through testing it all!

**Comment by bspeare** [comment]
Thanks @e-marie-w!

**Pull request merged**
