### PR TITLE
Remove unused drush config and uninstall automated_cron.

### LINKED ISSUE #4839: Set per-site Drush cache config
Blocked by #4789 

Create a new PR using #3383 as a guide.

The PR should:
- [x] Remove env variables being set in BLT tasks [591f8f9](https://github.com/uiowa/uiowa/pull/3383/commits/591f8f9b6bb717731ed287d56e9484269f7c6915)
- ~~Create a BLT update hook to set site-specific config for all multisites [91788d9](https://github.com/uiowa/uiowa/pull/3383/commits/91788d9bad7a66d7ce0fb4f370a5aeea6b18eadb)~~
- ~~Ensure the same file is created for new multisites in `blt umc` command.~~
- ~~Add a filesystem test for said file.~~
- [x] Remove unused drush config [51f32f7](https://github.com/uiowa/uiowa/pull/3383/commits/51f32f753f53060b3c71c9f3426dbec9dd27b9b7)
- [x] Investigate BLT environment detector usage and determine if there is a way to set AH vars in DDev without breaking stuff. That is, it'd be nice to expand the environment variables used in the drush config files locally. [e16569d](https://github.com/uiowa/uiowa/pull/3383/commits/e16569da74711e1a65c52cb5e689e130436ec7d6)
- [x] Deploy to develop and test code deployments while running Drush commands like `blt ume cr`

~~It would good to do this while also pausing on any new site provisions until it is merged.~~

### LINKED ISSUE #4841: Create and document staggered scheduled task to run cron on all sites
~~Blocked by #4839.~~

This was actually only blocked by #4789.

Read docs:
https://docs.acquia.com/cloud-platform/manage/cron/
https://docs.acquia.com/cloud-platform/manage/cron/drush-cron-cpe/

Disable automated cron via config.

For each application environment, create an hourly scheduled task to run cron on all sites via `blt uiowa:multisite:execute`. Stagger the execution of the command by 10 minutes per application. For example, uiowa -> :00, uiowa01 -> :10, uiowa02 -> :20, etc. Document this in https://wiki.uiowa.edu/display/drupaldev/Acquia+Applications. 

~~Consider adding a CRON_OFFSET environment variable in each prod environment to use in code later. For example, uiowa -> CRON_OFFSET=0, uiowa01 -> CRON_OFFSET=10, etc.~~ This probably isn't needed for #4842 but might be for #723.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #4839 
Resolves #4841 

Drush no longer caches anything and doesn't use the drush-paths-cache-directory config and/or environment variables. This PR removes that unused code. It also removes some Drush config that we weren't using. 

It also uninstalls automated cron.

Cron jobs have been set up on all application dev/test environments. Prod can be configured once this is deployed.

# How to test

- Review docs at bottom on https://wiki.uiowa.edu/display/drupaldev/Acquia+Applications re: setting up new applications.
- Log in to Acquia Cloud.
- Go to each D9 application dev/test env and inspect the scheduled tasks.
- Go to uiowa in AC interface. SSH in to uiowa dev in two separate terminals. Change directory up one level, i.e.`cd ..`
- Start a code checkout on uiowa dev for the develop-build branch.
- Simultaneously run `./vendor/bin/blt ume cr` and `/.vendor/bin/blt ume cron` in the terminal sessions.
- There should be no errors related to Drush cache in the AC task output or the terminals. The AC task is currently failing for config reasons and the terminal running `cron` will show errors for empty databases like this:
```
Command cron was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.
```

Those are expected.

- Sync a site and see that automated_cron is uninstalled and the config deleted.

*This is not exactly the same thing as prod and ultimately that is where this needs to be tested.

### CODE REVIEW

**Comment by richardbporter** [comment]
I'm going to wrap #4841 into this.

**Comment by richardbporter** [comment]
I think this is ready for review.

**Comment by joewhitsitt** [comment]
Going to try and test this

>This will need to be reduced once we acquire more than 6 D9 applications.

Won't this be the the day...

**Review by joewhitsitt — APPROVED** [review]
I followed the instructions to the T and there was a typo with the cron command. I handled it well. Did not panic. I saw everything that was described in the instructions.

`[notice] Synchronized extensions: uninstall automated_cron.`

Onward to PROD! 🚀

**Pull request merged**
