### PR TITLE
Named buildings theming

### LINKED ISSUE #5962: Theme named building pages
As a Facilities website owner, I would like the named building pages to look nice and quickly provide information about the Facility and the Honoree to site visitors.

# Additional Info
They are ok with us putting together the layout and getting feedback though they prefer the Facility description and Honoree info (photo, name, etc. near the top).

- https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-0

There are some named buildings with two honorees (https://www.facilities.uiowa.edu/named-building/blank-honors-center), and can be accounted for similar to https://github.com/uiowa/uiowa/pull/5934#issuecomment-1335806496, but there may be styling considerations there (like pluralizing the Honoree label).

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5962

```
ddev blt ds --site facilities.uiowa.edu && ddev drush @facilities.local cim --source ../config/sites/facilities.uiowa.edu --partial -y && ddev drush @facilities.local en facilities_core && ddev drush @facilities.local cim -y
```

- Attempt to re-create the content from https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-0 and compare visually.

<details>
<summary>Quick-access assets</summary>

robert_c _hardin
Hardin-Library

</details>

# Still todo
- [x] Get featured image working
- [x] Style like the mockup https://sandbox.prod.drupal.uiowa.edu/hardin-library-health-sciences-0

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Update on progress. Can't recall if it is still our solution for these, but I created a views block to combine the bg--gray and padding stuff of the honoree info:

Screen Shot 2022-12-08 at 5 26 37 PM

**Comment by joewhitsitt** [comment]
Realized last night that I could organize the view a bit better and potentially keep the field labels visually hidden for a11y.

**Comment by joewhitsitt** [comment]
Screen Shot 2022-12-09 at 11 11 46 AM

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/pull/5934#issuecomment-1335856405

After working on this, I am not sure how two honorees photoshopped into a square render will work.. Perhaps they can find a single image?

**Comment by bspeare** [comment]
If we were stuck with the aspect ratios of the current website images, probably something like this?  Ideally, two portrait images with more vertical space would work better and fill the space. 

Screen Shot 2022-12-09 at 12 06 07 PM

**Comment by bspeare** [comment]
Pulling to test.

**Comment by bspeare** [comment]
Tested this out and it looks good to me.  I pushed up an adjustment to the headline class to move the date closer to the honoree name.

**Comment by e-marie-w** [comment]
Pulling down to test

**Comment by e-marie-w** [comment]
So the Building ID field does not appear on the view display, correct?

And bullets are not part of minimal text format (yet) so I just turned on full text format locally for the Achievements field and tested it that way. 

Slightly bugging me that the Additional Building information link displays as black, while links in the Achievements section display as blue. I've clicked on both so it shouldn't be different due to that. I spent some time seeing if it was easily changed and came up with nothing. Since it hasn't bothered anyone else we can leave it as-is.

The Building Information title/background appears even if none of those fields are filled out, but I think that's fine as we can assume they will be filling in at least some if not all of the fields.

Let me know if I'm wrong about anything above, otherwise I can approve it.

**Comment by joewhitsitt** [comment]
>So the Building ID field does not appear on the view display, correct?
>And bullets are not part of minimal text format (yet)

Correct and correct.

>Slightly bugging me that the Additional Building information link displays as black, while links in the Achievements section display as blue.

I believe this is a difference between wysiwyg paragraph links and field links on white backgrounds. To get it back to blue, either the css would be expanded or the field markup would have a `<p>` around the link.

>The Building Information title/background appears even if none of those fields are filled out

Good catch. I think I can make a tweak to hide block if empty. Hold off on approval. I will move it back to draft.

**Comment by joewhitsitt** [comment]
>The Building Information title/background appears even if none of those fields are filled out
>>Good catch. I think I can make a tweak to hide block if empty. Hold off on approval. I will move it back to draft.

This is turning into a challenge. The headline field of the views block is causing it always to be rendered. Surely, we have another situation like this somewhere.

**Comment by pyrello** [comment]
> > The Building Information title/background appears even if none of those fields are filled out
> > > Good catch. I think I can make a tweak to hide block if empty. Hold off on approval. I will move it back to draft.
> 
> This is turning into a challenge. The headline field of the views block is causing it always to be rendered. Surely, we have another situation like this somewhere.

I would have thought that we would have encountered this before, but I think since this is mostly used for constructing people and article lists, there is probably usually content. I can help take a look at this later.

**Comment by joewhitsitt** [comment]
We are punting on this a bit by addressing this in https://github.com/uiowa/uiowa/issues/3804. For now requiring the street address which should always be available.

**Comment by joewhitsitt** [comment]
I'll take that approval @e-marie-w now if you think this is good.  ;)

**Review by e-marie-w — APPROVED** [review]
Theming looks as intended and content type still works as intended!

**Pull request merged**
