### PR TITLE
Commencement Event Migration

### LINKED ISSUE #7567: Create migration for past ceremony events
```[tasklist]
### Tasks
- [x] Migration module scaffolding
- [x] Creating mapping config for redirects
- [x] Create mapping config for events
- [x] Custom code to handle situations not handled by a plugin/mapping (document any specific fields as separate items)
- [x] If custom code is necessary, create migration class file for Event
- [x] ~Figure out why Pictures on the Pentacrest taxonomy term is not being added to events (but all other celebrations are)~ fixed, I had added old term from dev site instead of newer one from prod site.
- [x] Check if we need to pull unique id - we don't
```

```[tasklist]
### D10 fields that haven't been mapped (and need to be)
- [x] field_event_ceremony_information - only pulling accordions
- [x] field_event_livestream
- [x] start/end date
- [x] field_event_session
- [x] field_event_order_of_events
- [x] ~field_event_additional_info~ - not needed, not in source
```

### LINKED ISSUE #7627: Content type updates
```[tasklist]
### Tasks
- [x] Both: Ensure that no collection items are prepopulated
- [x] Event: Rename Ceremony information field to Ceremony information collections
- [x] Event: Rename Additional information field to Ceremony information and move ahead of the Ceremony Information collections field
```

### PR DESCRIPTION
**Pull request by e-marie-w**
Closes #7567
Closes #7627

# How to test

- Sync down the D7 Commencement site in DevDesktop
```
ddev blt ds --site=commencement.uiowa.edu && ddev drush @commencement.local en commencement_migrate -y && ddev drush @commencement.local uli admin/config/sitenow/sitenow-migrate && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'"
```
- ^ Note the number that is printed out after the login link, as that is your baseline count for `uiowa_collection_item` paragraphs.
- Configure SiteNow Migrate following instructions for DevDesktop. 
  - Database: `commencement_uiowa_edu`.
  - User: `root`
  - Host: `host.docker.internal`
  - Port: `33067`
  - Base URL: `https://commencement.uiowa.edu`
```
ddev drush @commencement.local mim --all && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'"
```
- The query above will give you the count of `uiowa_collection_items` after running the migration. We expect a number in the 70s or above.
- Spot check events
- Ensure correct order of events are being pulled over
- Example of event with livestream and ceremony information
- Try some redirects by visiting the current site, getting the URL for a ceremony and using it on the local site to ensure that you are redirected as expected.

## Rollback cleanup
- Final check for `uiowa_collection_item` paragraphs:
```
ddev drush @commencement.local mr --all && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'"
```
- Number should match the baseline from earlier.

## Additional updates
- https://commencement.uiowa.ddev.site/node/add/event
- Confirm that Ceremony information field is a text area
- Confirm that Ceremony information details displays below that, is a paragraph widget, and doesn't pre-populate a collection item.
- https://commencement.uiowa.ddev.site/node/add/venue
- Confirm that a collection section is not pre-populated under Additional information
- Click "Add Collection Section"
- Confirm that a collection item is not pre-populated under Collections
---

### Additional helpful commands

- Rollback migration
```
ddev drush @commencement.local mr commencement_event
```
- Stop and reset migration
```
ddev drush @commencement.local mst commencement_event
ddev drush @commencement.local mrs commencement_event
```
- Re-import migration config
```
ddev drush @commencement.local cim -y &&  && ddev drush @commencement.local cr
```

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Comment by pyrello** [comment]
I'm going to make a few minor content type changes here.

**Comment by bspeare** [comment]
I am no longer testing this due to issues getting DevDesktop working.

**Comment by joewhitsitt** [comment]
Is it the redirects migration creating 70 more and then not being able to roll that back?

Added a common escape that we have for migrations with a redirect migration following:

```php
  /**
   * {@inheritdoc}
   */
  public function prepareRow(Row $row) {
    parent::prepareRow($row);

    // Skip over the rest of the preprocessing, as it's not needed
    // for redirects. Also avoids duplicating the notices.
    // Return TRUE because the row should be created.
    if ($this->migration->id() === 'commencement_event_redirects') {
      return TRUE;
    }
```

```
jwhitsit@VPER-OSC-194 uiowa % ddev drush @commencement.local en commencement_migrate -y && ddev drush @commencement.local uli admin/config/sitenow/sitenow-migrate && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'"
The following module(s) will be enabled: commencement_migrate, sitenow_migrate, migrate, migrate_drupal, migrate_plus, migrate_tools

 // Do you want to continue?: yes.                                                          

 [success] Successfully enabled: commencement_migrate, sitenow_migrate, migrate, migrate_drupal, migrate_plus, migrate_tools
http://commencement.uiowa.ddev.site/user/reset/1/1714600239/TI43Hy28OcmaQqB3Sk4a8pRQ8FAXkBuaT52Cz_TgTA8/login?destination=admin/config/sitenow/sitenow-migrate
1

jwhitsit@VPER-OSC-194 uiowa % ddev drush @commencement.local mim --all && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'"
 [notice] Scheduler settings cannot be migrated due to RequirementsException: No database connection configured for source plugin variable, , line 200 in /var/www/html/docroot/core/modules/migrate/src/Plugin/migrate/source/SqlBase.php
  38/247 [====>-----------------------]  15% [error]  Could not load metadata from 'public://media-icons/generic/video.png' because it does not exist. 
 [notice] Processed 247 items (247 created, 0 updated, 0 failed, 0 ignored) - done with 'commencement_event'
 [notice] Processed 247 items (247 created, 0 updated, 0 failed, 0 ignored) - done with 'commencement_event_redirects'
 [error]  Message: No matching provider found.
 
71

jwhitsit@VPER-OSC-194 uiowa % ddev drush @commencement.local mr --all && ddev drush @commencement.local sqlq "SELECT COUNT(*) FROM paragraphs_item WHERE type = 'uiowa_collection_item'" 

 [notice] Rolled back 247 items - done with 'commencement_event_redirects'
 [notice] Rolled back 247 items - done with 'commencement_event'
1
```

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Any chance someone has examples fresh in their mind?

>Example of event with livestream and ceremony information

Update: Found one and confirmed.

**Comment by joewhitsitt** [comment]
Oops. Getting an error here https://commencement.uiowa.ddev.site/node/126

```
Error: Call to undefined method Drupal\block_content\Entity\BlockContent::getType() in commencement_core_preprocess_paragraph__uiowa_collection_item() (line 114 of sites/commencement.uiowa.edu/modules/commencement_core/commencement_core.module).
```

**Comment by joewhitsitt** [comment]
>Ensure correct order of events are being pulled over

Looking at a venue, I see the ceremonies listed oldest to newest, meaning I have to page to the last page to see the May 2024 ceremony.

**Comment by e-marie-w** [comment]
> Any chance someone has examples fresh in their mind?
> 
> > Ensure correct order of events are being pulled over
> > Example of event with livestream and ceremony information

I swear there was a 2023 CLAS ceremony I used a lot, but right now the [2024](https://commencement.uiowa.edu/ceremony/college-liberal-arts-and-sciences-9-am-undergraduate-commencement-ceremony-1) (has livestream and Ceremony Information) and [2022]( https://commencement.uiowa.edu/ceremony/fall-2022/college-liberal-arts-and-sciences-commencement-ceremony) (has basically everything, including Order of Events) are looking like better choices.

Edit: nevermind you already found one.

**Comment by joewhitsitt** [comment]
Generally the migration went fine. The fields and form placement looks correct. Looking for some clarification and/or fixes based on the comments above. Removing review assignment for now.

**Comment by pyrello** [comment]
> > Ensure correct order of events are being pulled over
> 
> Looking at a venue, I see the ceremonies listed oldest to newest, meaning I have to page to the last page to see the May 2024 ceremony.

Order of Events is a PDF file from the old site that gets attached to the event.

**Comment by pyrello** [comment]
> Oops. Getting an error here https://commencement.uiowa.ddev.site/node/126
> 
> ```
> Error: Call to undefined method Drupal\block_content\Entity\BlockContent::getType() in commencement_core_preprocess_paragraph__uiowa_collection_item() (line 114 of sites/commencement.uiowa.edu/modules/commencement_core/commencement_core.module).
> ```

Looking into this.

**Comment by joewhitsitt** [comment]
> > > Ensure correct order of events are being pulled over
> > 
> > 
> > Looking at a venue, I see the ceremonies listed oldest to newest, meaning I have to page to the last page to see the May 2024 ceremony.
> 
> Order of Events is a PDF file from the old site that gets attached to the event.

Ah okay. I was totally off. Seeing this presented in the migration demo. ✅

**Comment by pyrello** [comment]
> > Oops. Getting an error here https://commencement.uiowa.ddev.site/node/126
> > ```
> > Error: Call to undefined method Drupal\block_content\Entity\BlockContent::getType() in commencement_core_preprocess_paragraph__uiowa_collection_item() (line 114 of sites/commencement.uiowa.edu/modules/commencement_core/commencement_core.module).
> > ```
> 
> Looking into this.

Fixed.

**Review by joewhitsitt — APPROVED** [review]
Since the events by venue work isn't in this PR and everything else seems to check out.

**Comment by pyrello** [comment]
Merging that was cathartic.

**Pull request merged**
