### PR TITLE
Adjust role mapping configuration

### LINKED ISSUE #5862: Investigate long term strategy for managing custom AD role mappings
Follow-up to #5702.

When we groomed #5702, we discussed that we want to use a site split to handle setting up custom AD role mappings for the Student Life intranet site. We decided to go with the site split because that would more easily allow us to determine what sites were overriding it should some issue with security come up. If this becomes a more widely-used feature, it would be desirable to not have to create a site split for every site that wants to customize its AD role mappings. This would require us to better understand the security implications so we can have confidence in moving away from customizations via site splits.

# Proposed solution

- Appropriate config ignore settings
- Remove existing splits
- Construct a query to get a list of sites with custom mappings using `blt ume`

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/5862

This PR starts to ignore uiowa_auth.settings:role_mappings so that add/edits can be done directly in the PROD active db. Because of this, the sites that split config for this no longer need it. An update hook is run to implement the ignore before the config splits are updated preserving any custom mappings. A drush command is established that can be run on all sites using `blt ume` to query sites that have custom mappings in addition to the defaults.

# To Test
Setup your local.blt.yml file with the following sites along with a few other sites (e.g. default, gis.sites.uiowa.edu, admissions.uiowa.edu, education.uiowa.edu)

- default
- admissions.uiowa.edu
- brand.uiowa.edu
- connect.studentlife.uiowa.edu
- education.uiowa.edu
- sitenow.uiowa.edu
- sppa.uiowa.edu
- webcommunity.sites.uiowa.edu

```
ddev blt dsa && ddev blt ume uicore-crm
```

- Confirm custom role mappings are still intact for brand, connect.studentlife, sitenow, and sppa

You can also login to the mappings (admin/config/people/hawkid)

### CODE REVIEW

**Comment by makurj** [comment]
Running into issues with education and webcommunity during sync. Will work on those. For now, the other sites seem to look okay. See screenshots below:

<details>
Default:
image

Admissions:
image

Brand:
image

Student Life Connect:
image

Sitenow:
image

SPPA:
image

</details>

**Comment by makurj** [comment]
Education: 
image

Webcommunity:
image

**Comment by makurj** [comment]
Still seeing this: 
image

**Comment by joewhitsitt** [comment]
>Still seeing this

was gis.sites one of the site you sync for testing? might need a `drush cr` to register the command.

**Comment by makurj** [comment]
> > Still seeing this
> 
> was gis.sites one of the site you sync for testing? might need a `drush cr` to register the command.

Yep, it was in the instructions above. I'll try it with a `drush cr`

**Comment by makurj** [comment]
`cr` `sql drop` and a fresh sync fixed it.

image

**Review by makurj — APPROVED** [review]

**Comment by makurj** [comment]
gis:
image

**Comment by joewhitsitt** [comment]
Thanks for testing @makurj

**Pull request merged**
