### PR TITLE
SPPA Opportunity content type

### LINKED ISSUE #3211: SPPA: Build opportunity resource content type
# Story

As an SPPA site owner I want post records of resources for finding opportunities (Jobs, Internships, and Fellowships) so that they can be displayed to appropriate site visitors.

I don't love the name "opportunity resource," so if anyone has any better ideas, let me know.

# Proposed solution

- [x] Create a opportunity resource content type with the following fields:
  - [x] Name (title)
  - [x] Website (link)
  - [x] Opportunities offered (multiple select text list, possibly utilizing an allowed values function): Jobs, Internships, and Fellowships.
  - [x] States (multiple select text list, probably via allowed values function): All US states, United States, International.
- [x] Create a [site split](https://github.com/uiowa/uiowa/blob/main/config/README.md#site-split) for SPPA if one doesn't already exist (`sppa_uiowa_edu`).
- [x] Add content type and field storage for the above-defined fields to the site split.
- [x] Export all the configuration for SPPA: `drush @sppa.local csex sppa_uiowa_edu`

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3211 

# How to test

1. `blt ds --site=sppa.uiowa.edu`
2. `drush @sppa.local en sppa_core`
3. `drush -l sppa.uiowa.edu config:import --source ../config/sppa.uiowa.edu --partial`
4. `drush @sppa.local uli`

## Stories
* As a publisher, editor, and webmaster, I can create Opportunity records.
* As a publisher, editor, and webmaster, when creating an Opportunity, the states option lists all the US states, United States, and International.
* As a site visitor, I can view Opportunity pages.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Should this be reviewed by @pyrello or is open to all?

**Comment by pyrello** [comment]
I'm going to review it, but you are welcome to as well!

**Comment by pyrello** [comment]
If anyone else wants to review it, let me know and I will give you access to the D7 site so that you can compare against the original content types.

**Comment by GaryRidgway** [comment]
> If anyone else wants to review it, let me know and I will give you access to the D7 site so that you can compare against the original content types.

@pyrello  I'd like to try reviewing, may i have access?

**Comment by dnkemper** [comment]
@pyrello crap... I didn't have access to the site to compare? Or did I? I only saw the existing d8 site in prod

**Comment by GaryRidgway** [comment]
I have tested all of the things listed, and can approve all of the instructions parameters. I have not been given access to the d7 site yet, so i will reserve my "Approved" status for when i have tested that.

**Comment by dnkemper** [comment]
Thank you, @GaryRidgway 🥳 . Slightly nervous as I have not either. I even looked at dev desktop before I started issue. Fail.

**Comment by pyrello** [comment]
To be clear there is not an Opportunity Resource content type on the D7 site. Instead, this would be a comparison against the original 3 content types to make sure that we could have a way of migrating the content from all 3 (#3722) without losing data.

**Comment by GaryRidgway** [comment]
Okay, upon further poking i believe we are on the right track. However I am seeing missing fields for the following:

1. Legacy ID
2. Dscription
3. Workflow log

@pyrello are these fields we will need?

**Comment by pyrello** [comment]
Legacy ID, I'm not sure about. Description will be necessary. Apologies for missing this in the original issue, @dnkemper!

**Comment by pyrello** [comment]
I have added a description field and renamed the fields to be more related to the content type rather than the site. It seems that the purpose of the legacy ID has been lost to antiquity, so it will not be going forward with us.

After more consideration, I think that we may not try to fold the fellowship content type into this as well, so I'm not going to worry about those extra fields at this point.

**Comment by joewhitsitt** [comment]
pulling to test a bit

**Comment by joewhitsitt** [comment]
Content type is installed, fields accounted for, as a webmaster I can interact with it. Few observations:

- As a webmaster I can't adjust any SEO for this.
- Not included in the sitemap (separate config file)
- Revision delete settings haven't be set.

Other things to consider:

https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes

**Comment by pyrello** [comment]
@joewhitsitt Thanks for taking a look. I'll go through that documentation to see if I missed anything that needs to be included now.

**Comment by dnkemper** [comment]
Thank you so so much @joewhitsitt and @pyrello

**Comment by pyrello** [comment]
Added 
* Path alias for Opportunity
* Revision deletion settings
* Sitemap settings for Opportunity

I think I want to better understand what allowing the site owner to adjust Metatag settings for this content type means before I dive into that. Also think I will make them request the full workflow settings before adding it.

**Comment by joewhitsitt** [comment]
If you are satisfied @pyrello we can merge this and free up work on https://github.com/uiowa/uiowa/issues/3706

**Review by pyrello — APPROVED** [review]
Looks good.

**Pull request merged**
