### PR TITLE
Feature: Events summary

### LINKED ISSUE #5503: Ability to control summary for events teaser
# Story

As a College of Education event admin, I would like the ability to add a summary to events in content.uiowa.edu and have those summaries used as the teaser text on my website so that I have more control over what is output on event teasers.

# Proposed solution

- [x] Communicate in events-calendar Slack that we will be adding the summary option in Content Hub and making it available in the APIs.
- [x] Create summary field above description that is plain text and has help text.
- [x] Add summary to APIs, keeping description in the APIs as it is currently
- [x] Pull in summary as teaser in uiowa_events if exists otherwise fall back to what is currently being displayed.
- [x] css change to make sure hide descriptions continues to work and hides summary.
- [x] Let Chris C. view and approve the help text, etc. before rolling out.
- [x] communicate that the summary field is available in events-calendar Slack and ping Jeremy Dombrock, Andrew Rinner and Raaj in CSI and Chris Clair so he can communicate with event unit admins

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5503

# How to test
- Review files changed.
- ` ddev blt ds --site=sandbox.uiowa.edu`
- Sync a site and change the sitenow_events endpoint to dev `drush @sandbox.local cset sitenow_events.settings base_endpoint 'https://content.dev.drupal.uiowa.edu/api/v1/'`.
- Go to https://sandbox.uiowa.ddev.site/digital-signage-events and look for events that are using the new summary field. 
- Verify that the description field will work if there is no summary field.

### CODE REVIEW

**Comment by bspeare** [comment]
I tested this out by placing the HTML Kitchen sink into the field and added the `Xss` filter to cleanup the output. 
Screen Shot 2022-08-09 at 1 03 44 PM

This now renders as:


Screen Shot 2022-08-09 at 1 07 09 PM

**Comment by e-marie-w** [comment]
> Verify that the description field will work if there is no summary field.

Just want to check I tested this part correctly. Since none of the events on the Digital Signage events page had a description with no summary, I used https://sandbox.uiowa.ddev.site/events-listing. As well as testing that the description is used if no summary, it also let me check that 'Hide description' hides both descriptions and summaries. (Which it does!)

**Comment by bspeare** [comment]
This one https://content.dev.drupal.uiowa.edu/engie-university-partner-workshop has both a summary and description.  I think you can see it if you remove the department.

**Comment by e-marie-w** [comment]
> This one https://content.dev.drupal.uiowa.edu/engie-university-partner-workshop has both a summary and description. I think you can see it if you remove the department.

Yep, that one works too, for displaying the summary. I didn't know how to tell if an event only had the description filled in, so I could test that was still used if no summary provided. I was worried about the same content being copy pasted into both fields. But I finally remembered that this is new and not public yet, so that isn't a concern.

**Comment by e-marie-w** [comment]
One last check that I tested it right: I only needed to test that the events block is working as expected, correct? I don't need to go into content hub and check that the summary field appears or something.

**Comment by bspeare** [comment]
Yes @e-marie-w, nothing needed to test on content hub.

**Review by e-marie-w — APPROVED** [review]
Code looks good, and summary field is working great! If no summary exists, it falls back to using the description field. 'Hide description' style correctly hides info, whether summary field or description field is being used.

**Pull request merged**
