### PR TITLE
[People] Removed comma to avoid comma city

### LINKED ISSUE #6874: Updating display of multiple person education
> Is there another way to differentiate between the separate line items for the education field outside of commas? I ask because it basically makes it impossible to use commas within those fields without becoming comma city. Example (https://theatre.prod.drupal.uiowa.edu/people/art-borreca):

Image

Requested by Brynne Schweigel w/CLAS

### PR DESCRIPTION
**Pull request by bspeare**
Possibly resolves https://github.com/uiowa/uiowa/issues/6874

# How to test

```
ddev blt ds --site=theatre.uiowa.edu && ddev drush @theatre.local uli /people/art-borreca
```

- Confirm that education field in card no longer has field delimiter comma
- Code review the remaining split updates
- Did I miss any splits that need to be updated?

### CODE REVIEW

**Comment by bspeare** [comment]
This is ready for review if the team is good with this solution https://github.com/uiowa/uiowa/issues/6874#issuecomment-1716384624.

**Review by GaryRidgway — APPROVED** [review]
Looks fine to me, but I don't know If I am qualified to say if you missed any splits.

**Comment by joewhitsitt** [comment]
They messed up the cool search for this, but you can get something like this
Screenshot 2023-09-14 at 10 27 29 AM

So I think all the splits were touched. ighn_person doesn't count and those two patch ones _shouldn't_

**Comment by bspeare** [comment]
Thanks for looking @joewhitsitt!

**Pull request merged**
