### PR TITLE
Fix app id var in umc.

### PR DESCRIPTION
**Pull request by richardbporter**
You can try creating that site on this branch.

### CODE REVIEW

**Review by pyrello — APPROVED** [review]
Reviewed not tested.

**Comment by mark-bennett-uiowa** [comment]
@richardbporter @pyrello So this would just be for testing whether the umc fix works, correct? It wont actually create the site since I wont be pushing any feature branch with my provisions, correct?

**Comment by pyrello** [comment]
@mark-bennett-uiowa I'm not sure that I understand your question.

**Review by mark-bennett-uiowa — APPROVED** [review]
Worked great for me after merging into my feature branch. Approved.

**Comment by joewhitsitt** [comment]
Should this be closed in favor of https://github.com/uiowa/uiowa/pull/1924 ?

**Comment by pyrello** [comment]
I think this should be merged prior to that one.

**Pull request merged**
