### PR TITLE
Feature: Issue templates

### PR DESCRIPTION
**Pull request by pyrello**
# Updates

Added two new issue templates: one for bug reports, and one for creating user stories.

# How to test
Good question. Other than reviewing the contents of the changes, I'm not sure if there is a way to test this without it being merged into the `main` branch.

### CODE REVIEW

**Review by cory-skeers — APPROVED** [review]
Reviewed the templates, and think they look good! Worth merging and trying out 'irl' in my opinion. I particularly like the story template.

**Comment by richardbporter** [comment]
Yea looks good. Probably can't test this until its in the default branch. Do we want to remove the PR template or just leave it for now?

**Comment by pyrello** [comment]
@richardbporter I did update the PR template to provide a prompt for "How to test" which I think is important on most PRs (provisions being the notable exception). However, I am open to getting rid of it if people don't think it has any value.

**Comment by richardbporter** [comment]
Oh duh. I overlooked that. Nevermind!

**Pull request merged**
