### PR TITLE
Require Authentication - Restrict IP method

### LINKED ISSUE #4241: Require Authentication to view all content on SiteNow site
# Story

As a SiteNow v3 site owner, I would like to have all my content behind authentication so it is not available publicly.

# Additional Info
It would be nice if there was some sort of option or split that could be enabled that would automatically make it so authentication was required to view content. That same option or split would also turn on all of the related functionality in future slices.

# Related Issues
#4242 
#4243 
#4244 

# Proposed solution

### LINKED ISSUE #4242: When all content is private, store all files in private files system
# Story

As an owner of a site where all content is private, I would like all my sites files to be private as well.

# Additional Info
Parent issue #4241 

# Proposed solution
- Most of the work for this has already been done.
- [ ] Write test to check for private scheme patch version of config for every default public scheme: https://github.com/uiowa/uiowa/issues/4242#issuecomment-1013324907

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/4241
Resolves #4242

Currently relying on a patch from https://www.drupal.org/project/restrict_ip/issues/2957482, Cory has been working on test coverage to get that fix in sooner.

## To Do

- [x] Freshen up access denied page like https://github.com/uiowa/uiowa/issues/4241#issuecomment-1006894018
- [x] Cache-Control headers set to no-cache? Test in DEV?
- [x] Switch to stable patch file or update module (pending merge)
- [x] Disable search from header
- [x] Private files
- [x] Write test for private files

## Later on

- See https://github.com/uiowa/uiowa/issues/4640

## To Test
- `blt drupal:install --site default`
- `drush en sitenow_intranet`
- `drush cim`
- Non-admins should get an access denied on all drupal paths except for the default content public files. These will be removed manually before delivering to initial customers.
- Run the private files scheme test: `ddev phpunit tests/phpunit/`
  - Try manually deleting one of the file related patch files and run again.
  - Try changing one of the patch files' values from private to something else and run again.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Cleaned up/adjusted the access denied page a bit based on the suggestion in https://github.com/uiowa/uiowa/issues/4241#issuecomment-1006894018. 

image

I think this is enough for this first slice. Individual intranets may have specific requests, and those could be handled at that time in individual splits and/or modules.

**Comment by cory-skeers** [comment]
There's a related issue for https://www.drupal.org/project/restrict_ip/issues/3229792 (relates to the MR for the count() error--automated module tests are mostly broken atm). Following...

**Comment by cory-skeers** [comment]
> There's a related issue for https://www.drupal.org/project/restrict_ip/issues/3229792 (relates to the MR for the count() error--automated module tests are mostly broken atm). Following...

Created a MR with some updates to the module tests that gets most of them functional, and works to test the count() issue's MR. Will keep watching, and I think that's all in the maintainers' hands now.

**Comment by joewhitsitt** [comment]
Going to move this to dev and setup on the default site for caching testing.

**Comment by joewhitsitt** [comment]
By restricting all IP stuff, everything but the /saml/* is redirecting straight to the access denied page which has the following cache-control: `must-revalidate, no-cache, private`

Cache control for a webform submission file (private files) is `cache-control: private` and it also redirects to the access denied. 🤷 👍 
https://default.dev.drupal.uiowa.edu/system/files/webform/contact/6/2000x1000.jpg

**Comment by joewhitsitt** [comment]
Sounds like Rick might poke a bit more at the cache ([result](https://github.com/uiowa/uiowa/issues/4241#issuecomment-1010331836)) and that Cory is working on getting the restrict_ip issues merged so we don't haven't to rely on patches.

**Comment by joewhitsitt** [comment]
going to take a look at the recent private files changes

**Review by GaryRidgway — APPROVED** [review]
Testing instructions worked as detailed

**Comment by richardbporter** [comment]
```
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Testing /var/www/html/tests
.......F                                                            8 / 8 (100%)

Time: 00:00.649, Memory: 14.00 MB

There was 1 failure:

1) Uiowa\Tests\PHPUnit\Unit\FilesystemTest::testFilesScheme
Failed asserting that file "/var/www/html/docroot/../config/features/sitenow_intranet/config_split.patch.field.storage.media.field_media_file_dupe.yml" exists.
```

Yea this is what I had in mind. I was going to scope it just to `field.storage.*` in the finder but this covers more possibilities I think. If it is too fragile going forward, we can decrease the scope of files checked. 👍🏻

**Comment by pyrello** [comment]
Thanks for the rename, @joewhitsitt!

**Pull request merged**
