### PR TITLE
Feature merge uiowa01 code

### LINKED ISSUE #903: Add components from uiowa01
Related to #855. 
  
The following items need to be moved from uiowa01 to this repo to support the above issue:
- [x] collegiate profile
- [x] collegiate_theme
- [x] custom modules
- [x] Multisite provisioning command

The following items need to be merged together:
- [x] blt/blt.yml
- [x] composer.json

### LINKED ISSUE #907: Add sites from uiowa01
Related to #855. Follows #903.

Copy all config, site folders, and drush aliases from uiowa01.

### PR DESCRIPTION
**Pull request by pyrello**
# Description
Resolves #903 and resolves #907 

# Checklist
- [x] Add appropriate PR labels.
- [ ] Request approval from multiple developers across units.
- [ ] Dependencies have been properly updated.
  - https://github.com/uiowa/uiowa#updating-dependencies
- [ ] Site config splits have been accounted for.
  - Go to https://github.com/uiowa/uiowa/find/master to find split config entities affected by this PR.
- [ ] Test PR locally with default site.
- [ ] Test PR locally with custom site that might be affected by these changes.
- [ ] Update documentation.
  - Document changes introduced by this PR in application, profile or site README.

### CODE REVIEW

**Comment by pyrello** [comment]
@richardbporter When I run `blt sbf` to build frontend assets, I am getting an error on the hr site:

```
$ gulp css
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/var/www/uiowa/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/var/www/uiowa/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/var/www/uiowa/docroot/sites/hr.uiowa.edu/themes/hr/gulpfile.js:22:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
error Command failed with exit code 1.
```

I haven't encountered this before. Can you take a look?

This appears to be the same issue that the AC pipelines build is failing on.

**Comment by richardbporter** [comment]
Not exactly sure. I'll keep digging unless @joewhitsitt has ideas. Odd that it is just HR.

**Comment by pyrello** [comment]
I don't immediately see anything in this file that would explain why this is happening, seemingly out of nowhere: https://github.com/uiowa/uiowa/blob/8adc42185a480f039409faffe196a738baa1cdb2/docroot/sites/hr.uiowa.edu/themes/hr/gulpfile.js#L10-L20

Maybe it's not just HR, but it fails on HR and never makes it further than that?

**Comment by richardbporter** [comment]
I think 08269ed should do the trick. Syntax change required from upgrading to Gulp 4.

**Comment by richardbporter** [comment]
Couple things I noticed in this branch:

- BLT is complaining about schema being out of date. I ran it locally and it changes the phpcs.xml.dist file.
- I'm seeing yarn.lock changes after running `blt frontend`. Not exactly sure why.

**Comment by pyrello** [comment]
@richardbporter I can fix those items. I hadn't committed the changes you mentioned above yet.

**Comment by richardbporter** [comment]
Sounds good. I'm switching to something else now.

**Comment by pyrello** [comment]
@richardbporter @joewhitsitt 
The build process seems to be failing on a config operation that happens during the `blt drupal:install` command:
```
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/uiowa/vendor/bin/drush @self config-status --no-interaction --ansi in /var/www/uiowa/docroot
 ----------------------- ----------- 
  Name                    State      
 ----------------------- ----------- 
  crop.type.focal_point   Different  
 ----------------------- ----------- 
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 0.887s
[error]  Configuration in the database does not match configuration on disk. This indicates that your configuration on disk needs attention. Please read https://support.acquia.com/hc/en-us/articles/360034687394--Configuration-in-the-database-does-not-match-configuration-on-disk-when-using-BLT
```

It's not immediately clear how to resolve this issue. Have you encountered this before?

**Comment by richardbporter** [comment]
Yes, we can take a look at this.

**Comment by pyrello** [comment]
When I ran `blt sbf` on my local machine, I did not see that there were changes to yarn.lock that needed to be committed.

**Comment by richardbporter** [comment]
I'm guessing due to a difference in node versions? I re-ran `yarn install` and committed the changes.

**Comment by pyrello** [comment]
So, now that this is passing, I think it is ready for testing against Sitenow sites. Do you want me to move this PR out of a draft state and add reviewers?

**Comment by richardbporter** [comment]
Sure!

**Comment by richardbporter** [comment]
`blt dsa` worked as expected for gis.sites.uiowa.edu, sitenow.uiowa.edu and default. Sites looked fine locally. I think we need to further test the updates to paragraphs, pathauto, etc.

**Comment by richardbporter** [comment]
The paragraphs updates are probably the only real concern here. I tested it out, didn't see anything glaring. Nothing in the release notes between 1.3. and 1.10 sticks out as being problematic. Would still love @joewhitsitt to test though.

Other than that, if we can get https://github.com/uiowa/uiowa_bar/pull/47 done then I'd love to merge this.

**Comment by joewhitsitt** [comment]
Two issues came up this morning. I am trying to get to this next.

**Comment by joewhitsitt** [comment]
Poked around HR's paragraphs for a bit. They all seem to render the same and I was successful with editing (creating, duplicating, collapsing, removing). I saw something about speedier UI but was left unimpressed. Looks like the release has been out there for a while and I don't see any new critical issues because of it.

The composer install/blt ds seemed to go fine.

**Review by richardbporter — APPROVED** [review]
Sounds like we're okay with this being merged, although I'm not sure what that means for uiowa01. Since that app is not connected yet, deployment will be different. 

Let us know when the best time to merge this is.

**Pull request merged**
