### PR TITLE
SiteNow Migrate updates

### PR DESCRIPTION
**Pull request by cory-skeers**
- Attaches images to Article featured image field
 - Edits to link checker/replacer

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Um, I think there was a bad merge. It says 2,876 files have changed in this PR.

**Comment by cory-skeers** [comment]
~~Oof. Looks like my updating it with master is being tracked on the individual change level.~~

Rebase updated to show the correct commits/file changes, and not claim that this PR will change...everything.

**Comment by joewhitsitt** [comment]
Is this ready to be tested/reviewed?

**Comment by cory-skeers** [comment]
Yes, ready for testing/review. 

Couple bug fixes throughout, but the main changes:

- File migrate rollback (drush mr d7_file after a file import) now removes media entities as well as the files.
- Articles migrated which had a featured image now attach the featured image following import
- Article import not a dependency of page -- not all migrations have articles to import; instead post-migrate link checker will check if an article migrate db exists
- Link checker/replacer is iffy, but will output 'troublesome' pages which can be manually checked after

**Review by joewhitsitt — COMMENTED** [review]
It has been a while since I have tried this so I fumbled through it using the wiki docs and may not have been a good tester.

- the file rollback worked. both media and managed file tables were cleared. the files are still in the file directory but nicely contained in date specific folder for easily deletion. will cause _0 filenames if not deleted and done the same day.

- article featured image worked!

- the linkchecker is pretty cool, not sure how to effectively parse the "troublesome" output. I found an internal node path that was corrected to the new node!

Looking at basic page nodes, the html tags are being rendered. But I am not sure if this was in-scope for this PR.
Screen Shot 2020-05-29 at 12 32 49 PM

**Comment by cory-skeers** [comment]
Wasn't in scope for the PR, but a "would-be-nice" addition. Current workaround is to open the page editor and save. Paragraph text fields aren't recognizing the 'format' attribute and defaulting to NULL. Once the editor is opened, it fills the value to the proper filtered_html.

Might be something to update in the docs instead.

**Review by joewhitsitt — APPROVED** [review]
Since the other bit (filtered_html applying) isn't in-scope and the other test items checkout, approved.

**Pull request merged**
