### PR TITLE
Drupal 10 Update PR.

### LINKED ISSUE #6957: D10 Contrib updates continued
When you take a task below, add your initials to the end. Check the box when it's completed. If you open a separate PR, replace the task below with the PR.

```[tasklist]
### Tasks
- [x] `drupal/editor_advanced_link` - JW
- [x] `drupal/focal_point` - BS
- [x] https://github.com/uiowa/uiowa/pull/6958
- [x] Remove `drupal/fullcalendar` module - JW
- [x] https://github.com/uiowa/uiowa/pull/6970
- [x] `drupal/layout_builder_restrictions` - BS
- [x] `drupal/media_entity_facebook` - BS
- [x] `drupal/media_entity_file_replace` - JW
- [x] `drupal/media_entity_twitter` - BS
- [x] `drupal/media_thumbnails` GAR
- [x] `drupal/migrate_plus` - JW
- [x] `drupal/migrate_tools` - JW
- [x] `drupal/mimemail` - JW
- [x] https://github.com/uiowa/uiowa/pull/6975
- [x] Remove `oembed_providers` module
- [x] https://github.com/uiowa/uiowa/pull/6954
- [x] https://github.com/uiowa/uiowa/pull/6963
- [x] `drupal/reroute_email` GAR
- [x] `drupal/schema_metatag` GAR
- [x] `drupal/simplei` - BS
- [x] `drupal/siteimprove` - BS
- [x] `drupal/stage_file_proxy` - BS
- [ ] https://github.com/uiowa/uiowa/issues/4623
- [x] https://github.com/uiowa/uiowa/pull/6966
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
Resolves https://github.com/uiowa/uiowa/issues/6957
Updated `editor_advanced_link` to `2.2.4`
Updated `focal_point` to `2.0.2`
Removed `fullcalendar`
Uninstalled `hal`
Updated `layout_builder_restrictions` to `8.x-2.19.0`
Updated `media_entity_file_replace` to `8.x-1.1`
Updated `media_entity_facebook` to `4.0.2`
Updated `media_entity_twitter` to `8.x-2.9`
Updated `media_thumbnails` to `8.x-1.0-beta2`
Updated `migrate_plus` to `6.0.1`
Updated `migrate_tools` to `6.0.2`
Removed `mimemail`
Removed `oembed_providers`
Updated `reroute_email` to `2.1.1`
Updated `schema_metatag` to `3.0.1`
Updated `simplei` to `2.1.4`
Updated `siteimprove` to `2.0.1`
Updated `stage_file_proxy` to `2.1.1`

# To Test

- Developers have tested these updates as this PR was prepared.
- General review, successful composer install/site sync.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Tested Schema metatag by capturing the source output from an article before and after updating, and found them to be moderately rearranged, but functionally the same.

**Comment by joewhitsitt** [comment]
i've got the merge fix locally, but having a ddev/docker hiccup

**Comment by bspeare** [comment]
@joewhitsitt just got this error syncing, are you still working on this part?
Screenshot 2023-10-09 at 2 42 07 PM

**Comment by joewhitsitt** [comment]
deployment going out now with it. didn't think anyone else was touching the PR at the moment. my bad

**Comment by joewhitsitt** [comment]
Was there any config to be captured with these update hooks?

```
 ----------------------- ---------------------------- --------------- -------------------------------------------------------------------------- 
  Module                  Update ID                    Type            Description                                                               
 ----------------------- ---------------------------- --------------- -------------------------------------------------------------------------- 
  media_entity_facebook   9001                         hook_update_n   9001 - Set value for new setting 'use_embedded_posts' to continue oembed  
                                                                       usage.                                                                    
  siteimprove             8103                         hook_update_n   8103 - Update latest experience settings.                                 
  metatag                 remove_robots_noydir_noodp   post-update     Remove 'noydir', 'noodp' ROBOTS options from meta tag entity fields.      
  schema_metatag          add_ids                      post-update     Read in new config schema with @id definitions.                           
 ----------------------- ---------------------------- --------------- --------------------------------------------------------------------------
```

**Comment by joewhitsitt** [comment]
>By default, the module uses the [Embedded Posts](https://developers.facebook.com/docs/plugins/embedded-posts) which can be used for embedding Facebook content without App Review. You can also use the [Facebook oEmbed API](https://developers.facebook.com/docs/plugins/oembed) which usage needs an App Review from Facebook. You will need to clear cache after changing this setting.

Should we switch to this instead of maintaining the app? Wonder if Instagram has this too?

**Comment by bspeare** [comment]
@joewhitsitt on https://github.com/uiowa/uiowa/pull/6967#issuecomment-1753820342 I found one for facebook and I'm not seeing one for siteimprove.  Could you test out the metatag ones?

**Comment by joewhitsitt** [comment]
Yeah, captured those in https://github.com/uiowa/uiowa/pull/6967/commits/8ffcbba1f8115ecda38b97aa60a4817c2d1135b4

**Comment by joewhitsitt** [comment]
Confirmed that HAL was no longer being used for default_content. It is an optional dependency for backwards compatibility but our default content was re-exported a while back and no longer needs it for import or export.

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
I reviewed the code changes. There is a small but non-zero possibility that changes to config that involve adding a new property could result in a mismatch between what code expects and what is actually there. Most likely this would not result in downtime, but I can't entirely rule it out. I'm not sure this rises to the level of needing a scheduled deployment, but I'm curious about others thoughts.

**Review by pyrello — APPROVED** [review]
I reviewed code, tested `composer install`, synced several sites, and tested clicking around the default site. To the best of my understanding this looks good.

**Comment by joewhitsitt** [comment]
i'd be fine with a scheduled deployment. after the provisions release goes out and we see what is in store for security updates, this can be merged and scheduled.

being out at 3 pm, i may need help if we want it to go out tomorrow morning.

**Pull request merged**
