### PR TITLE
hid taxonomy term feed link

### PR DESCRIPTION
**Pull request by quamsta**
Addresses #4695 

This hides the feed link from the taxonomy term view.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
i know you are going for the easy/quick solution on this, but have you tried to hide it higher up while maintaining it in the head info? (e.g. template, view config). even a `@include element-invisible;` IMO is better than a `display:none;`

**Comment by quamsta** [comment]
> i know you are going for the easy/quick solution on this, but have you tried to hide it higher up while maintaining it in the head info? (e.g. template, view config).

@joewhitsitt Everywhere I've looked online says that the feed link in the body of the document is directly tied to making the feed available in the `<head>`. If there's some other way to disable it via config, I'm all in for that. 

> even a `@include element-invisible;` IMO is better than a `display:none;`

The CSS mixin `element-invisble` we're using in the Drupal theme looks to be similar to a Bootstrap CSS class `.sr-only`, which visually hides the link, but still allows it to be spoken aloud by screen readers. 

This is decidedly not the desired behavior, since visitors that are using screen readers like NVDA, JAWS, or iOS or macOS's voiceover in combination with a common web browser will hear the link "Subscribe to [term]" read aloud and will still experience the confusing dialogs or XML presented to them. 

I would rather have the link not be visible or read aloud, hence `display: none;`.

**Comment by joewhitsitt** [comment]
So I am still in the boat that thinks it should still be "available" so would element invisible plus a "RSS Feed link to [term]" be a compromise?

**Comment by quamsta** [comment]
@joewhitsitt I want to say yes to this in the spirit of compromise and camaraderie, but keeping a specific link on a page visible for screen readers and other assistive devices while hiding it visually for everyone else doesn't seem to jive with the spirit of accessibility and equal access imho, even if we change the text.

I feel that if we're going to hide this link, we should hide it for everyone, and keep the feed in the `<head>` for consumption by any feed reading extensions or apps that people are using.

The inverse, aka keeping the link, but rewriting it to "RSS feed link for [term]" and keeping it visible for everyone would be less confusing than "Subscribe to", but then we're making some assumptions about the user knowing what an RSS feed is, and we're still providing a link that can be activated (possibly by accident) and presenting the user with those browser dialogs or XML, which may seem broken to them.

Couple of questions:

- Is this a matter of trying to let the user know that there's a RSS feed available for the page in question?
- Is this something that we can hide for now, but if there's a resurgence in RSS apps or browsers that can handle these links, we can revisit it in the future? 

My biggest concern is just how RSS/XML links are handled these days. Even if we present the link in the clearest terms possible, browsers simply aren't playing nice with them.

**Comment by joewhitsitt** [comment]
Equal access in my opinion would be leaving it as-is but here I am commenting on an issue that wasn't groomed/planned by the team. Keep in mind, I didn't rule out removing it as long as it stayed in the <head>:

>but have you tried to hide it higher up while maintaining it in the head info? (e.g. template, view config)

I don't like the CSS solutions in general because as a developer I will see that it is supposed to be rendering based on the code/config but will have to dig into the theme to find out why it isn't.

Chrome and Opera show the plaintext which is what I would expect. Doesn't break anything, doesn't hurt anything, might make a user go, "hmm," but the back button is still an option.

FWIW, this is my Safari experience which I don't think is broken either:
Screen Shot 2022-01-25 at 12 22 35 PM

**Comment by quamsta** [comment]
@joewhitsitt I hear you. Today's discussion during the grooming/mid-sprint demo was my attempt at getting visibility on this after I brought it up in @mark-bennett-uiowa's issue (#4435)  a couple of weeks ago, but I'm going back to the drawing board after today's discussion.

Leaving this PR as a draft, and we can continue discussion over on the issue? I have some ideas after today's meeting. Thanks for your help working through this with me.

https://github.com/uiowa/uiowa/issues/4695

**Comment by quamsta** [comment]
Closing in favor of https://github.com/uiowa/uiowa/pull/4714

**Pull request closed without merging**
