### PR TITLE
Feature: Updated headline underline style

### PR DESCRIPTION
**Pull request by bspeare**
# How to test

```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
blt ds --site=sandbox.uiowa.edu
drush @sandbox.local uli
```

- Compare https://sandbox.prod.drupal.uiowa.edu/headline-underline with https://sandbox.local.drupal.uiowa.edu/headline-underline
- Test https://sandbox.local.drupal.uiowa.edu/kitchen-sink by changing the text areas to a different background color and verify that the underline is visible.  Example, a gold background section with a text area with a gray background.
- Look at any other sites that you can think of using this headline style

I've added a number of screenshots in details below with examples of how this will look on sites:

<details>
Screen Shot 2021-11-05 at 4 38 13 PM
Screen Shot 2021-11-05 at 4 37 44 PM
Screen Shot 2021-11-05 at 4 34 03 PM
Screen Shot 2021-11-05 at 4 30 37 PM
Screen Shot 2021-11-05 at 4 31 47 PM
Screen Shot 2021-11-05 at 4 32 23 PM
Screen Shot 2021-11-05 at 4 37 35 PM
</details>

### CODE REVIEW

**Comment by GaryRidgway** [comment]
@bspeare Everything looks good, however it seems as if there is a problem with white background blocks on yellow base background sections, shown in the dropdown below. is this acceptable?

<details>
    <summary>Screenshots here </summary>
    Screen Shot 2021-11-05 at 4 34 03 PM
</details>

**Comment by bspeare** [comment]
@GaryRidgway good find!  Yes, I want to change that.

**Comment by bspeare** [comment]
@GaryRidgway I added a fix for that particular color combo if you can take another look at this.

**Comment by GaryRidgway** [comment]
will do in a moment

**Review by GaryRidgway — APPROVED** [review]
@bspeare I reviewed again and it seems to be fixed, well done!

**Pull request merged**
