### PR TITLE
Turn on per-page LB in coronavirus.uiowa.edu while maintaining existing paragraph layouts

### PR DESCRIPTION
**Pull request by pyrello**
# To test
* `blt ds --site=coronavirus.uiowa.edu`
* `drush @coronavirus.local cim --source ../config/coronavirus.uiowa.edu --partial`

### CODE REVIEW

**Comment by richardbporter** [comment]
Merged main but kept uids on the branch instead of tag.

**Comment by bspeare** [comment]
It looks like we need to set permissions so that webmasters can edit the layout on pages.  @pyrello do we just need to copy over the permissions that we have set on uiowa.edu?

**Comment by pyrello** [comment]
Next steps:
* @bspeare Can you test this and see what changes we want to make to the way layouts and restrictions are set up?
* Create a new UIDS release to incorporate changes to `main` that are necessary for this branch to work.
* Change `main` to latest release version in `uids_base/package.json`.

**Comment by bspeare** [comment]
@pyrello I just tried adding a slider to a page and got this error: 

`Error: Call to a member function hasField() on null in uids_base_preprocess_paragraph() (line 368 of themes/custom/uids_base/uids_base.theme).`

**Comment by bspeare** [comment]
@pyrello I also tried creating a new page and adding a Stat block and then saved the page and the block does not appear after saving.

**Comment by pyrello** [comment]
@bspeare Thanks for testing. I'll take another look.

**Comment by bspeare** [comment]
@pyrello It looks like we need permissions for webmasters to edit layout pages.

**Review by bspeare — APPROVED** [review]
Nice work!

**Pull request merged**
