### PR TITLE
ITS Services View Block

### LINKED ISSUE #6826: Services results page
# Story

As an ITS website owner, I would like to have a services landing page where I can search for a service and see results like the mockups provided or choose a featured service so that our users can find the service they are looking for.

# Additional Info

Use basic page for services landing page https://sandbox.prod.drupal.uiowa.edu/all-services-and-software-copy?

Create results page and wire it up to search block https://sandbox.prod.drupal.uiowa.edu/services?

Do we just use cards for featured services or should we wire services up to be used in the featured content component?

# Proposed Solution

- Develop results view based on mockup https://sandbox.prod.drupal.uiowa.edu/services
- Any additional theming for results/exposed filters
- Confirm the search block will work with this

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/6826

Screenshot 2023-09-11 at 2 48 19 PM

# To Test
```
ddev blt frontend && rm config/sites/its.uiowa.edu/schemadotorg.schemadotorg_mapping.node.service.yml && ddev blt ds --site=its.uiowa.edu && ddev drush @its.local config:import --source ../config/sites/its.uiowa.edu --partial -y && ddev drush @its.local cim -y && git restore config/ && ddev drush @its.local cim -y && ddev drush @its.local cr && ddev drush @its.local uli /admin/structure/taxonomy/manage/service_category/add
```
- Create some audience/category terms
- Create some services. Create a few services that have a leading integer.
- Add a search block to a layout with  `/all-services-and-software` and `name` as the config. Try searching on a partial title.
- See that styling is not too much of a departure from https://sandbox.prod.drupal.uiowa.edu/services and note https://github.com/uiowa/uiowa/issues/6826#issuecomment-1714228825

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Changing A-Z to $secondary for active, $grey for inactive makes the color contrast ratio accessible and provides some differentiation between the two states.

Screenshot 2023-09-11 at 3 18 09 PM

```
diff --git a/docroot/themes/custom/uids_base/scss/global.scss b/docroot/themes/custom/uids_base/scss/global.scss
index d4f393c4d..ccabf4491 100644
--- a/docroot/themes/custom/uids_base/scss/global.scss
+++ b/docroot/themes/custom/uids_base/scss/global.scss
@@ -714,7 +714,7 @@ body:not(.page-node-type-article, .page-node-type-page).layout-builder-disabled
       a {
         display: block;
         text-decoration: none;
-        color: #4F4F4F;
+        color: $secondary;
         line-height: 1;
         @include padding($top: $md, $right: $md, $bottom: $md, $left: $md);
 
@@ -728,7 +728,7 @@ body:not(.page-node-type-article, .page-node-type-page).layout-builder-disabled
       div {
         display: block;
         text-decoration: none;
-        color: $grey-light;
+        color: $grey;
         line-height: 1;
         @include padding($top: $md, $right: $md, $bottom: $md, $left: $md);
       }
```

**Comment by bspeare** [comment]
I updated the view to use some of our a-z list styles.    

Screenshot 2023-09-12 at 9 43 10 AM

**Comment by bspeare** [comment]
I am unable to get the search on the title field working.   I did use devel generate to create a bunch of content.  Could someone else test this out and confirm if it is working?

**Comment by joewhitsitt** [comment]
>Could someone else test this out and confirm if it is working?

I am biased on this and didn't use devel generate but I can't reproduce this.

Screenshot 2023-09-12 at 9 47 03 AM

**Comment by bspeare** [comment]
@joewhitsitt do we need the page in this services view or should that be removed?

**Comment by joewhitsitt** [comment]
Good eye. I think it can be removed. I can do that if you want to move on.

**Review by bspeare — APPROVED** [review]
Tested this out a few times and I was able to get the search working as well.  Devel generate was messing it up a bit.  Nice work!

**Comment by joewhitsitt** [comment]
>do we need the page in this services view or should that be removed?

It appears that we might need it as I am getting a nasty WSOD when I try to use the a-z toc or load the view block.

```
InvalidArgumentException: You cannot create a URL to a display without routes. in Drupal\views\ViewExecutable->getUrl() (line 1949 of core/modules/views/src/ViewExecutable.php).
template_preprocess_views_view_summary_unformatted(Array, 'views_view_summary_unformatted__services', Array)
```

**Comment by joewhitsitt** [comment]
i am going to take another look at this. leaving it in is creating a path conflict for /service which we may encounter issues with later on https://github.com/uiowa/uiowa/issues/6872

**Comment by joewhitsitt** [comment]
Can't get away from the view page. Lives at /service. Made a note in the display settings about it. Rendering service teasers to make sure it is styles appropriately.

Screenshot 2023-09-12 at 5 03 39 PM

**Comment by joewhitsitt** [comment]
Mind if I merge with this @bspeare? The page will be unlisted but presentable if found.

**Comment by bspeare** [comment]
Go for it!

**Pull request merged**
