### PR TITLE
[INRC] Grant migration

### LINKED ISSUE #7896: migrate grants
# Story

As a LAW INRC website owner, we would like to have our grants migrated from our current site to our new site so we do not have to manually move all that content.

# Additional Info

Migrate all published grants (~ 500)

I think we are using the same alias pattern so does that mean we do not need to create redirects as part of the migration?

We should bring over taxonomy terms during migration

**Mappings - v3 -> v1**

- Grantor Name - title
- Filter Friendly Name - field_filter_name
- Employer Identification Number (EIN) - field_grant_employer_id
- Contact Name - field_grant_contact_name
- Contact Title - field_grant_contact_title
- Address - field_inrc_address - Address/Postal Address - country, address 1, address 2, city, state, zip
- Phone - field_inrc_telephone_number - telephone number
- Fax - field_inrc_fax - telephone number
- Email - field_inrc_email - email
- *Grant Classification - field_grant_classification - term reference - unlimited
- Purpose/Mission - body/summary
- Restrictions - field_grant_restrictions - filtered html
- Grant sizes - field_grant_sizes - integer - unlimited
- Total Grants - field_grant_total_grants - integer - single
- Trustees - field_grant_trustees - filtered html
- Sample Grants - field_grant_sample_grants - filtered html
- Website - field_inrc_website - link - single - title and url
- *NTEE Classification - field_grant_ntee - taxonomy - unlimited
- *Areas of interest - field_grant_interest_areas - taxonomy - unlimited
- *Type of Grant - field_grant_ref_types - taxonomy - unlimited
- PDF Version - field_pdf_version - file - single - document
- *Counties - field_entityref_counties - entity reference - unlimited
- Application Info - field_grant_application_info - filtered html
- Application Deadline - field_grant_app_deadline - date - single - year, month, day granularity
- Total Assets - field_grant_total_assets - single
- Date of latest financial data - field_grant_financial_recieved - date - single - we are migrating a date with just month/year granularity to a field with day/month/year granularity so we likely will need to process in a day.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7896 

# How to test

Sync the d7 site locally in DevDesktop (on uiowa703). Pulling files locally is not necessary (and codebase is not necessary either, unless you want to load the site).

Now to SNV3!

```
ddev blt ds --site=inrc.law.uiowa.edu && ddev drush @lawinrc.local en inrc_migrate -y && ddev drush @lawinrc.local uli admin/config/sitenow/sitenow-migrate
```

Complete the migration setup page

- **Database name**: inrc_law_uiowa_edu
- **Database user**: root
- **Database user password**: _leave blank_
- **Database host**: host.docker.internal
- **Database host port**: 33067
- **Base URL**: https://inrc.law.uiowa.edu
- **Public files path**: _leave blank_

```
ddev drush @lawinrc.local mim --all
```
Compare grants from the existing site (https://inrc.law.uiowa.edu/iowa-grants-guide) to those that have been migrated (including that the paths from the existing site resolve to the corresponding grant on the new).

### CODE REVIEW

**Comment by cory-skeers** [comment]
Noting here what didn't "just work" so far with mappings.

- [x] Address only pulled in country
- [x] The various taxonomy fields

So...not bad!

**Comment by cory-skeers** [comment]
Check for media links in filtered html fields?
Double-check the date of latest financial data field--seemed to have defaulted to the first, but make sure it all came over.

**Comment by cory-skeers** [comment]
> Check for media links in filtered html fields? 

I did a site search on the V3 local site after a migration, and didn't find any D7 file embed snippets, so I believe we're in the clear here.

**Comment by cory-skeers** [comment]
> The d7 site has only year/month granularity on the form, but the value gets saved as a timestamp at midnight of the first day of the chosen month, which should in theory transfer over as desired, and default to Year/Month/Day in the new site, for the first of the month, and display only Month Year based on render settings.

Ahhhh...V3 it's stored as a string, so we need to convert it.

**Comment by joewhitsitt** [comment]
pulling to setup and test

**Review by joewhitsitt — APPROVED** [review]
Yay, a taxonomy term process function! Thanks for adding this in.

Migration went smooth. Spot checked each of the fields.

I don't think this is a migration issue but might have been missed in previous slices:

- grant sizes have a comma-separated list even though it is vertically listed.
- total assets needs money formatting.
- headings for grant information and financials show even though there isn't no required fields within.

By the way, Iowa Foundation for Agricultural Advancement is a great filled out example node.

**Comment by bspeare** [comment]
> I don't think this is a migration issue but might have been missed in previous slices:
> 
>     * grant sizes have a comma-separated list even though it is vertically listed.
> 
>     * total assets needs money formatting.
> 
>     * headings for grant information and financials show even though there isn't no required fields within.
> 
I added some adjustments for these in https://github.com/uiowa/uiowa/pull/7917/commits/a2bd9f33f434a82592ee31e55029cf65254e9ed5.

**Comment by joewhitsitt** [comment]
Thanks @bspeare !

**Pull request merged**
