### PR TITLE
Small and br tags allowed in minimal html.

### LINKED ISSUE #2701: Allow <br> and <small> tag in minimal_html format
# Problem
The banner using the `minimal_html` format has brought visibility to the need for adding single line break within the banner text.  

Screen Shot 2020-12-11 at 4 25 03 PM

Also, allowing `<small>` tags in `minimal_html` will address https://github.com/uiowa/uids/issues/275. 

# Steps to reproduce
Try adding a `<br>` or `<small>` tag in the `minimal_html` format. 

# Proposed solution
Allow `<br>` and `<small>` tags in the `minimal_html` format.

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Closes #2701.

Allowed small and br tags under the minimal text format using the americanstudies.uiowa.edu site. Tested by creating a new section and block and adding small and br tags as follows:
Screen Shot 2020-12-21 at 10 01 01 AM

Not sure why it added the media_embed status config, but it is set to false anyways.

@joewhitsitt I attempted to add the small tag to a sitenow v2 site in the minimal text format using the hawkeyemarching band site, but it already existed there, and there was no config/features/sitenow_v2/filter.format.minimal_html.yml file that existed in the code base. Could you check to see if you are missing this still?

To test, just create something that can use the minimal text format and make sure that small and br tags are saved properly.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Looks like v2 is using default config for minimal, so we are good there. Thanks for trying though.

My concern is that ~~media got added to this config~~ and that `<hr>` doesn't need class quotes unless we are restricting what classes are allowed there.

Media is added but status is false. Nevermind

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt I removed the classes from the br and small tags for minimal_html in sitenow_v2. Had to create a new minimal format yml file, so take a look and let me know if this works for you.

**Comment by joewhitsitt** [comment]
Sorry, I think you misunderstood me. The previous commit was fine, but added quote marks to the `<hr>` tag
Screen Shot 2020-12-21 at 12 45 56 PM

`<hr class> <br> <small class>` is what we want and shouldn't split a separate version for the v2 split unless I don't understand something else.

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt my bad. I removed the quotes from the default config for minimal html, and I can just delete the file I pushed for the sitenow_v2 profile to remove it from this PR. Should be good to go now.

**Review by joewhitsitt — APPROVED** [review]
Thanks for the adjustments. Sorry for complicating things with my comment.

**Comment by mark-bennett-uiowa** [comment]
No worries @joewhitsitt thanks for the approval!

**Pull request merged**
