### PR TITLE
Views block exposed filters

### LINKED ISSUE #3804: Add exposed filters to views block display
# Story

As a content editor, I want to be able to expose filters on my view blocks.

# Proposed solution

- [x] ~Help get MR at https://www.drupal.org/project/ctools/issues/2657060 to a fully working state.~ MR got merged and is part of the more recent version of `ctools`.
- [ ] Update to most recent version of `ctools` module.
- [x] Refactor code that transform the people type selector based on updates.
- [x] Add patch to account for issue with multiple exposed forms in blocks for the same views display, possibly the one at this issue: https://www.drupal.org/project/drupal/issues/3163299
- [x] Account for pager and offset options showing up in exposed filter form.
- [ ] Refactor code to work with updated version of `ctools` module.
- [ ] Update hook to convert existing configuration to the new format.

<details>
<summary>Original proposed solution</summary>
Modify the `Drupal\layout_builder_custom\Plugin\Display\ListBlock` class in the following ways:
- For each filter that can be set on the block settings form, add a checkbox to the form to allow the user to expose the filter. Name the checkboxes fields `$filter_id . '_expose`.
- Add `'#states'` to each filter field to disable the field if the corresponding checkbox is checked.
- Adjust the logic in the `blockSubmit()` method to check for an instances where the above fields are set to TRUE and set a new option value on the block called `expose_form` to TRUE if any of them are. Here is a quick example I came up with:
  ```
  $expose_form = FALSE;
  $exposed_inputs = $form_state->getValue([
    'override',
    'exposed_filters',
  ]);
  $exposed_filter_values = [];
  foreach ($exposed_inputs as $input) {
    // if input ends with _expose, $expose_form = TRUE;
    // else add to $input to $exposed_filter_values.
  }
  $block->setConfigurationValue('exposed_filter_values', $exposed_filter_values);
  $block->setConfigurationValue('expose_form', $expose_form);
  ```
- In the `preBlockBuild()` method, check the `expose_form` configuration value from the block and set an option on the display handler (`$this->view->display_handler->setOption('expose_form', TRUE)`) if this value is set to TRUE.
- Adjust the `displaysExposed()` method to check the display handler option and return `TRUE` if any filters are exposed.
- An update hook will be need to update all `layout_builder__layout` field instances to add the `expose_form` default value of FALSE to existing block configurations. This is a serialized field and will need to be deserialized to update it, then re-serialized to store it. There are several examples of this in previous update hook. Just ask @cory-skeers if you have any questions :)

**OR**

Alter the SiteNow People module to allow for displaying individual pages for people types as such:
- Change the configuration settings to allow for showing all people (the current option) and checkboxes for each person type to display a similar page.
- Adjust all the settings to be options for each possible person listing.
- Adjust the custom code that handles saving configuration and display the page to handle multiple pages.
</details>

### PR DESCRIPTION
**Pull request by pyrello**
A replacement PR for #3829 that resolves #3804

# How to test
```
composer install
blt ds --site sandbox.uiowa.edu
```
## Article and people list blocks
* View some existing article and people lists block and compare the settings with the production sandbox site to make sure that the update hook worked as expected.
* Place blocks on a page and try changing the following settings, saving the block, saving the layout, and viewing the page.
  * Test setting headline or not
  * Test changing items to display
  * Test changing offset
  * Test setting pager
  * Confirm that the 3 settings above work predictably with one another
  * Test changing sort options
  * Test hiding fields.
  * Test adding a more link, setting a custom path, and setting custom text
  * Test setting filter values
  * Test exposing filters without setting a value
  * Test exposing filters with a value set
  * Test setting multiple filters at the same time
  * Test setting multiple filters to different variations of exposing the filter and not
  * Test that exposed filter and pager for one block do not affect any other views blocks on the same page of either the same type or a different types
  * Confirm that "Items per page" and "Offset" do not show up in exposed filters

### People list block
* When setting the "Person type" filter, it should limit the options display in "Person type status" drop-down to the same option.

## Event list block
```
drush @sandbox.local config:set config_split.config_split.event status true
drush @sandbox.local cim
```
* Create some local events.
* Run through the above tests.

### CODE REVIEW

**Comment by pyrello** [comment]
There has been quite a bit of work done on the patch code for the related issue adding this functionality to `ctools`: https://www.drupal.org/project/ctools/issues/2657060. Might be time to give it another spin :)

**Comment by pyrello** [comment]
I got excited and a little bit of ahead of myself yesterday when I marked this ready for review.

**Comment by cory-skeers** [comment]
Pulling this down to do some testing! Will update with how much I go through, if it's not all of it.

**Comment by dnkemper** [comment]
@cory-skeers okay are you psychic? Because my environment is... not working at the moment

**Comment by cory-skeers** [comment]
> @cory-skeers okay are you psychic? Because my environment is... not working at the moment

Ha! Not psychic, just had the PR open and hadn't refreshed to see your assignment 😬

**Comment by cory-skeers** [comment]
Testing exposed filter on articles blocks, everything working well with a single articles block on the page. With two (or more) articles blocks on the same page, running into a few issues with the exposed filters (sort, hide, pager, etc working fine regardless of one or many blocks on a page).

If multiple blocks are exposing filters, using any of the filters is applying that filter to all of them on the page (eg adding 'bug test' tag filter to one applies it to all--'bug test' will appear in all the exposed filters and be applied to all blocks, with or without an exposed filter)

With two articles blocks, top with exposed filter and bottom without, using the exposed filter on the top block applies the filter to the bottom block but not the top from which it is exposed.

**Comment by pyrello** [comment]
Converted to draft to investigate the reported issues.

**Comment by pyrello** [comment]
My local testing did not result in the same outcomes that @cory-skeers was seeing, so we did a huddle to confirm that I was testing it right. It seems like there may be an issue with his local development environment that is affecting the testing.

**Comment by pyrello** [comment]
This needs an update hook because we are ditching our homegrown views block filtering solution in favor of a contrib one.

**Comment by pyrello** [comment]
The way that we built the local event content type and its related list block view is not ideal for exposing the virtual event field as a filter. We want it to effectively work as a true/false value, but it is actually a URL, so we are checking to see if the URL is there as our true value and false otherwise. However, this way of doing things means needing to add code to handle this specialized logic for the virtual event field.

We could alternately add a checkbox that serves as our true/false value and then leave the existing field to actually output the virtual event URL if it exists. The downside is that this extra field will require some of its own logic to handle the show/hide of the virtual event URL field.

However we decide to handle this, we should figure it out and include the change as part of this update, since we are already writing an update hook to handle changing the block configuration for these types of values.

**Comment by pyrello** [comment]
After discussing this at our mid-sprint demo, most immediately we would like to sidestep the issue with the virtual filter by removing it. Longer term, we could consider adding a hidden boolean field to track whether the event has a virtual URL and set that on node save based on whether the user set a virtual URL field.

**Comment by briand44** [comment]
Do we know if Admissions is currently using the virtual filter?

**Comment by pyrello** [comment]
> Do we know if Admissions is currently using the virtual filter?

It does not appear that we are currently allowing that as an option.

**Comment by joewhitsitt** [comment]
Going to pull and test

**Comment by joewhitsitt** [comment]
Getting some notices on https://sandbox.uiowa.ddev.site/people-directory

`Notice: Undefined offset: 1 in Drupal\ctools_views\Plugin\Display\Block->preBlockBuild() (line 640 of modules/contrib/ctools/modules/ctools_views/src/Plugin/Display/Block.php).`

`Notice: Trying to access array offset on value of type null in Drupal\views\Plugin\views\display\DisplayPluginBase->getHandlers() (line 852 of core/modules/views/src/Plugin/views/display/DisplayPluginBase.php).`

`Notice: Undefined property: Drupal\views\ViewExecutable::$0 in Drupal\views\Plugin\views\display\DisplayPluginBase->usesExposed() (line 248 of core/modules/views/src/Plugin/views/display/DisplayPluginBase.php).`

There are contrast issues with the form labels on black backgrounds
Screen Shot 2022-04-07 at 10 55 41 AM

I am going to keep testing but wanted to surface these

**Comment by joewhitsitt** [comment]
Looks like it unset the home state: california filter from this views block https://admissions.uiowa.ddev.site/node/4896

**Comment by joewhitsitt** [comment]
Screen Shot 2022-04-07 at 11 25 29 AM

Filters need to respond to layout width

**Comment by joewhitsitt** [comment]
This is unrelated but concerning (https://sandbox.prod.drupal.uiowa.edu/list-block):

Screen Shot 2022-04-07 at 11 31 48 AM

Anyone recall what this block was?

Was the event feature turned on temporarily and a block placed? I am seeing revisions from @bspeare along with Alex and Michael (webmaster masquerading?). The diff shows filters for both people and events

Discussion:
https://iowaweb.slack.com/archives/C0164FNN1PV/p1649350023246039

**Comment by pyrello** [comment]
> Screen Shot 2022-04-07 at 11 25 29 AM
>
> Filters need to respond to layout width

@bspeare created a follow-up issue: #5109 

> Anyone recall what this block was?
>
> Was the event feature turned on temporarily and a block placed? I am seeing revisions from @bspeare along with Alex and Michael (webmaster masquerading?). The diff shows filters for both people and events

It seems likely that I did this when I was testing event list block updates. I removed the broken block from the page.

> Getting some notices on https://sandbox.uiowa.ddev.site/people-directory

It seems like something isn't working quite right. I suspect this is related to another patch we are using being out-of-date with 9.3. I'm going to set this back to draft until I have time to look into it.

**Comment by pyrello** [comment]
This is why I think the patch might not be working anymore: https://www.drupal.org/project/drupal/issues/2605218#comment-14294915

**Comment by pyrello** [comment]
Closing this in favor of #5951.

**Pull request closed without merging**
