### PR TITLE
Feature:  Top links menu and character count limit for inline header

### LINKED ISSUE #1980: Adjust site header to check for a character limit on site name to determine header type
After today's design meeting it sounds like the next steps are:

- Determine character count for https://uids.brand.uiowa.edu/components/detail/iowa-bar--full.html
- Adjust mobile/tablet site name font size in `uids` for that new count. 
- Change sites that meet the character count requirements to use https://uids.brand.uiowa.edu/components/detail/iowa-bar--full.html
- Possibly limit some sites to only use https://uids.brand.uiowa.edu/components/detail/iowa-bar--site_name_below.html.

### LINKED ISSUE #2537: As a site owner, I can place important cta links in the header
# Story

As a Site Owner, I want to place a few call to action links in the website header so that users can directly interact with important website actions. 

Without a good way to place call to action links in the `uids_base` header, site owners are finding creative ways to place calls to action near the website header. 

# Proposed Solution

Investigate design concepts for the uiowa header beyond https://github.com/uiowa/uiowa/issues/2407 and create a feature branch for `uids_base`

## Tasks

- [x] Consider an approach that works best with the existing header
- [x] Create a pull request in `uiowa` demonstrating the cta implementation using the existing top links menu

**Some CTA implementations/inspiration on other sites:**

- https://wgu.edu
- https://snhu.edu - fixed button row in header
- https://online.drake.edu/master-of-arts-in-communication/ - cta appears on scroll
- https://drake.edu - fixed side tabs
- https://www.calpoly.edu/admissions/first-year-student/how-to-apply - ctas appear within off-canvas nav with main nav
- https://www.boisestate.edu - switch to full-width header to allow for more links
- https://www.unr.edu - make block iowa logo and site name smaller to allow for more cta links in header

## Creative examples of CTA buttons on existing uids_base sites:

Screen Shot 2020-11-05 at 9 22 43 AM

Screen Shot 2020-11-05 at 9 23 02 AM

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/2537 and resolves https://github.com/uiowa/uiowa/issues/1980

# How to test 

## How to test top links

1. `blt ds --site=admissions.uiowa.edu`
2. `blt ds --site=uiowa.edu`
3. `yarn workspace uids_base gulp --development`
4. Add 2 top links to http://admissions.local.drupal.uiowa.edu/admin/structure/menu/manage/top-links?destination=/admin/structure/menu
5. Save and view site. 
   - Test how menu adapts to all breakpoints
6. Change header navigation styles at http://admissions.local.drupal.uiowa.edu/admin/appearance/settings/uids_base
   -  Test how menu adapts to all breakpoints
7. Add parent organization and top links
   -  Test how menu adapts to all breakpoints
8. Test on `uiowa.edu` local site and test. 

## How to test character count limit

1. Add a very long site name over 43 characters to http://admissions.local.drupal.uiowa.edu/admin/config/system/site-information and navigate to http://admissions.local.drupal.uiowa.edu/admin/appearance/settings/uids_base and verify that the ability to set the site name display is grayed-out. 
2. Add a very short site name under 43 characters to http://admissions.local.drupal.uiowa.edu/admin/config/system/site-information and navigate to http://admissions.local.drupal.uiowa.edu/admin/appearance/settings/uids_base and verify that the ability to change site name display is available.
3. Save settings and verify that the correct header is displayed. 

## Theme settings changes and update hook
The following items are removed from `uids_base` config (which is entirely config ignored):
* `uids_base` - We used to namespace all items under this key
* `branding` - This was used to allow for the `legacy` setting, which has since been removed.

The update hook runs against all sites and removes those items.  This includes HR, which isn't using `uids_base` but still has config installed for it. This will ensure that whenever HR comes back into the fold, it will have up-to-date theme config. 

I tested it against:
* A new install - to make sure that the settings are installed correctly.
* hawkeyemarchingband.uiowa.edu - V2
* HR - Non-uids_base site
* uiowa.edu

To test, I ran `blt ds --site={site}` and then logged in and checked the config via https://default.local.drupal.uiowa.edu/admin/config/development/configuration/single/export. 

Feel free to check as many sites or potential edge cases as you feel is warranted.

### CODE REVIEW

**Comment by pyrello** [comment]
Testing this now.

**Comment by joewhitsitt** [comment]
So I haven't tested this, but I recall there being a "hacky" workaround by only validating on the theme settings side of things. Change site name to be short, choose the theme setting option, change the site name to a really long one. Do we want to try to account for that or is the render logic in addition to the theme setting good enough?

**Comment by bspeare** [comment]
@joewhitsitt Are users bypassing the settings and using the "hacky" workaround?

**Comment by joewhitsitt** [comment]
No, I mean with this PR, you are doing a check here: https://github.com/uiowa/uiowa/pull/2538/files#diff-e1372828a9838c277506d252da1d61906956f9e9d6c0fdd7f0788ce7a994a561 which _could_ be bypassed by messing with the site name length only to ultimately be stopped here: https://github.com/uiowa/uiowa/pull/2538/files#diff-8b86d0481fbe21d2b3f16cde4ff1be44614d90bdd3154d9ea894b87fae016edbR96

**Comment by bspeare** [comment]
@joewhitsitt Thanks for clarifying.

**Comment by pyrello** [comment]
I think this is done similarly to how we are enforcing the use of the 'below' option when a parent organization is selected. If they set the theme setting and then add a parent organization, it doesn't actually change the value of the setting, but the form acts as though its been changed and it is rendered as though it has been changed.

It was done this way to prevent having a module have to check for a form save from a theme, which is a bit convoluted at this point.

**Comment by pyrello** [comment]
I added an update hook that will clean up some old configuration entries for `uids_base` that are no longer in use. This will allow us to address a few `@todo` items in the comments.

**Comment by pyrello** [comment]
Screen Shot 2020-11-24 at 4 51 49 PM
 
Is this the desired behavior at the smallest breakpoint?

**Comment by pyrello** [comment]
I have tested this for the functionality that @bspeare added and approve it based on that. However, I would like someone else to test the update hook functionality that I added.

**Comment by pyrello** [comment]
This is still testable, but moving it to draft state so that it doesn't get merged until we can review the changes to uiowa.edu next week.

**Comment by bspeare** [comment]
@pyrello good question about the mobile appearance.  I adjusted the stacking order so that it now looks like:

Screen Shot 2020-11-25 at 6 51 09 AM

We could also set it to just extend the top bar below and include the links below the logo:

Screen Shot 2020-11-25 at 6 59 05 AM

**Comment by bspeare** [comment]
**Remaining adjustments:**

- [x] Site name alignment, search button, top links https://user-images.githubusercontent.com/1036433/100938451-50daa580-34ba-11eb-8253-e81e28f4493a.png
- [x] On home page top links not aligning left at below container breakpoint https://user-images.githubusercontent.com/1036433/100938454-51733c00-34ba-11eb-8c01-69a8ad61e6bb.png
- [x] Home page top links line break https://user-images.githubusercontent.com/1036433/100938458-51733c00-34ba-11eb-997a-09246ef96ca7.png
- [x] Top links alignment with search on home page https://user-images.githubusercontent.com/1036433/100938459-51733c00-34ba-11eb-8881-d93ed2fa092b.png
- [x] Firefox bug with site name width https://user-images.githubusercontent.com/1036433/100938461-51733c00-34ba-11eb-8274-de57ddfc6188.png
- [x] Test "below" option in IE11
- [x] Below option with parent organization

<details>
Screen Shot 2020-12-02 at 4 13 37 PM
Screen Shot 2020-12-02 at 4 14 27 PM
Screen Shot 2020-12-02 at 4 14 34 PM
Screen Shot 2020-12-02 at 4 14 41 PM
Screen Shot 2020-12-02 at 4 17 30 PM
</details>

**Comment by pyrello** [comment]
@bspeare In all the cases above where you can see "search" and "menu," "search" seems to be sitting about a pixel higher than "menu."

**Comment by bspeare** [comment]
Added the design tweaks from the feedback from Wednesday.  Marking this as ready to review again.

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
