### PR TITLE
Facilities' alerts template update

### PR DESCRIPTION
**Pull request by joewhitsitt**
# To Test

```
ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli node/3501
```

- Observe no import errors and a single column template in the same order as https://github.com/uiowa/uiowa/issues/6973#issuecomment-1749295647
- See that the dispatch template (https://github.com/uiowa/uiowa/issues/6973#issuecomment-1765101546 OR https://apps.its.uiowa.edu/dispatch/communications/1238605612/edit) is the same as https://github.com/uiowa/uiowa/issues/6973#issuecomment-1749295647

Screenshot 2023-10-17 at 3 20 27 PM

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Comment by bspeare** [comment]
Now that these fields are no longer in a sidebar, should we remove the custom icons and styling?  I think just inline field labels might be easier to read.


Screenshot 2023-10-17 at 1 09 49 PM

**Comment by joewhitsitt** [comment]
Sounds good. Sorry, I approached this like a chop shop initially. I will try to clean it up a bit.

**Comment by joewhitsitt** [comment]
Is this being used anymore?

```
function facilities_core_preprocess_field(&$variables) {
  switch ($variables['element']['#field_name']) {
    case 'field_alert_location':
      uiowa_core_set_attributes($variables, 'fa-ul');
      uiowa_core_set_field_icon($variables, 'fa-map-marker-alt fa-li');
      break;
```

I've looked on https://facilities.uiowa.ddev.site/alerts, https://facilities.uiowa.ddev.site/building/0374 and https://facilities.uiowa.ddev.site/dental-science-building-and-carver-hawkeye-arena-steamcondensate-and-forced-sewer

It is now part of the title in most places and is actually now `field_alert_buildings_locations`

**Comment by joewhitsitt** [comment]
I think I cleaned it up correctly.

**Comment by bspeare** [comment]
Thanks @joewhitsitt, should we go all in with the labels like "Dates of closure" and "Building" and "Reason and details of closure" and display those?

**Comment by joewhitsitt** [comment]
Did you `cim`? https://github.com/uiowa/uiowa/pull/7013/commits/25816fa1bd351ba1df136dd778df70e029b86d11

I thought switching to inline made those labels show. They did locally at least

**Comment by bspeare** [comment]
Thanks, I must have tried it out just before that commit.

**Review by bspeare — APPROVED** [review]
Cleanup and rearrangement looks good!

**Pull request merged**
