### PR TITLE
People sort and other responsive table fixes.

### PR DESCRIPTION
**Pull request by GaryRidgway**
adding wrapper classes so this doesn't get applied on EVERY table, the list of classes should now be manageable in this file

This provides functionality that lays the groundwork for https://github.com/uiowa/uiowa/issues/2313

This also provides a small fix for collections not having a full flex basis on LB pages.

This also fixes Tables in any container, including the previously bugged collections.

This should be merged after https://github.com/uiowa/uids/pull/390 is merged, as the js in the `tables.js` file there is needed for this.

### CODE REVIEW

**Comment by cory-skeers** [comment]
I pulled this and updated the uids hash to use uiowa/uids#390 for testing, and everything appears to be working great! 

One issue I came across, not sure if it's related to this or was present before: When manually sorting people, the `Show Row Weights/Hide Row Weights` button toggles the drag handles like it should, but the weights themselves aren't appearing for editing.

**Review by cory-skeers — APPROVED** [review]
Fixes worked with changing the uids hash to uiowa/uids#390 and using both updates together.

I don't think the `Show Row Weights` not actually showing the row weights is a result of this--can probably make a separate issue to address it, unless you think it can be tackled here too, @GaryRidgway?

**Comment by joewhitsitt** [comment]
@cory-skeers yeah that is a known-issue that was supposed to be fixed soon after v2 MVP... Created a follow-up #2416, but I told Alan he could hide the button as a temp solution

**Comment by GaryRidgway** [comment]
I have hidden the button for row weights for now

**Pull request merged**
