### PR TITLE
Remove extra spacing if node body field isn't used

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #2078.

Primary goal is to remove the extra spacing on an LB page if the body content field is empty.

The previous `{% if content.content %}` led to two nested `<div>` tags with no content but default margins, as content.content resolved to true even though it rendered to empty whitespaces.

I'm not a huge fan of the idea of rendering the content in order to check that there is content to display, but this is the lowest impact way I can think to do it (and at least the rendered content gets stored for use in display after, if it's not empty).

## Testing
Sync, blt frontend
Create a page, leave the body field (in the Edit tab) blank. 
The only `<div class="layout__container ...">` tags should be associated with content added through layout builder.
Edit the body field (in the Edit tab).
The body field content should appear on the page.

General testing that no regressions occur. This should only layout__onecol sections with no renderable content, though.

### CODE REVIEW

**Comment by dnkemper** [comment]
Tested, and seemed to work great for me! Yay!

**Review by dnkemper — APPROVED** [review]

**Comment by joewhitsitt** [comment]
Does something like the following not work? 
```
{% if content.content[0] is not empty %}
{{ content.content }}
{% endif %}

**Comment by cory-skeers** [comment]
@joewhitsitt That didn't work for me, but it could have been a notation error on my part. When I tried, it always came up with something to resolve to true, even if ended up as empty space later.

**Comment by joewhitsitt** [comment]
Ooh. What about?

```{% if content.content|render is not empty %}```

Only thinking about optimization/condensing, if what you have works, I am okay with moving forward.

**Comment by cory-skeers** [comment]
The `{% if content.content|render is not empty %}` route ends up going through the render process once for the logic check, and once again for the page render.

Think I'm going to go down one more short rabbit hole to double check before merging.

**Pull request merged**
