### PR TITLE
Update metatag configuration for default favicons, user access and improved SEO

### LINKED ISSUE #351: Finalize SEO Configuration
### Problem
We have thrown some modules at the content types hoping to check off SEO expectations, but I don't think we are there.

### Proposed Solution
Revisit what global and content specific options are available to the webmaster role. Run a page, article, person and the articles view page through SEO audit tools like Google lighthouse, Twitter cards, open graph to see where we need to improve.

Is it proper to have both schema article options available on the basic page content type?

- [x] View pages (articles, people) need meta description.

Establish SEO defaults for things like twitter cards (image, organization, etc.).

### Test
Above tools and maybe consult with Michael from Tippie to get a MVP thumbs up.

### LINKED ISSUE #451: Metatag configuration not restricted for webmasters
**Describe the bug**
There seems to be a lot more configuration available on the metatag admin pages.

**Expected behavior**
I would expect this extra configuration to be hidden for webmasters.

**Screenshots**
image
 
**Additional context**
I think we updated metatag recently and this could be new config that we need to hide.

### PR DESCRIPTION
**Pull request by GaryRidgway**
base work for #173

Resolves #351 
Resolves #451

### CODE REVIEW

**Comment by richardbporter** [comment]
This configures views to use the default meta description which is now the site slogan. Not great but better than nothing. 

The individual views could be updated to provider more accurate descriptions.

**Comment by richardbporter** [comment]
A follow up should be to update the form description of site slogan and allow webmasters to hide it via #287.

**Comment by richardbporter** [comment]
@GaryRidgway I can't request a review from you but would appreciate one.

**Comment by GaryRidgway** [comment]
I have tested this and determined it does indeed make the favicons work. No idea why i can't approve though.

**Comment by richardbporter** [comment]
This does override a theme's favicon. I think if sites want a custom favicon, they will need to split metatags config.

**Comment by richardbporter** [comment]
Got an UPDB to set existing article page meta descriptions but I'm not going to expose this on the config form now. I think that could be a future enhancement.

I think we should deploy this, review structured data with cloud tools and iteratively improve our SEO config.

**Comment by richardbporter** [comment]
Sites with permission splits are not getting the config changes. 😢

**Pull request merged**
