### PR TITLE
I2748 wysiwyg tables styles

### LINKED ISSUE #2748: As a site owner, I can have more control over my tables in the WYSIWYG
# Story

As a site owner, I can have more control over my tables in the WYSIWYG and how they display on the page. 

Related issues: #139, #995

# Proposed solution

- Add ability to apply table styles/classes via WYSIWYG
- Add Ability to set table width?
  - Add a class that will allow contents of table to determine width?
  - Explore options using layout columns to determine table width.

### PR DESCRIPTION
**Pull request by GaryRidgway**
Tracking for https://github.com/uiowa/uiowa/issues/2748, previously housed in the branch `i468-uids-tables-additional-styles`, ranamed for its new issue name. This PR integrates the changes from https://github.com/uiowa/uids/pull/490 in to uids_base.

# How to test:
1. pull down this PR
2. Sync `sandbox.uiowa.edu` locally.
3. Navigate to http://sandbox.local.drupal.uiowa.edu/tables
2. Test that the following are true:
    1. Adding a caption to a table will show a grey caption above the table itself.
    2. Adding the `table--gray-borders` class to a table will put gray borders on a table.
    3. Adding the `table--hover-highlight` class to a table allows rows to be highlighted on hover.
    4.  Adding the `table--width-default` class to a table allows a table to shrink to only as wide as necessitated.

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling down to test.

**Comment by bspeare** [comment]
The borders on the table headers don't seem consistent.   Maybe we can adjust the rules to be:

```
.table__responsive-container.table--gray-borders .table__responsive-header .table__sticky-heading {
    border-left: 1px solid #7c7c7c;
    border-top: 1px solid #7c7c7c;
    border-bottom: none;
}

.table__responsive-container.table--gray-borders .table__responsive-header .table__sticky-heading:first-child {
    border-left: none;
}

```

Before:

Screen Shot 2021-03-16 at 8 41 43 AM

After:

Screen Shot 2021-03-16 at 8 41 33 AM

Also, if the table doesn't have the `is-striped` styles, should we make the border colors the same?  The dark lines seem a little out of place here:

Screen Shot 2021-03-16 at 8 43 16 AM

**Comment by bspeare** [comment]
Also, can we update the table modifying `is-striped` and `gray-borders` and `hover-highlight` classes to be BEM?

https://github.com/uiowa/uids/blob/main/src/components/tables/tables.scss#L101
https://github.com/uiowa/uids/blob/main/src/components/tables/tables.scss#L151

**Comment by pyrello** [comment]
I have not tested this, but in looking at the images posted by @bspeare, is there a reason that the first column doesn't get borders as well? It seems like the borders should be applied regardless of cell type (e.g. `<th>` or `<td>`) or location (e.g. `<thead>` or `<tbody>`).

**Review by bspeare — CHANGES_REQUESTED** [review]
@GaryRidgway I added some comments on this above.

**Comment by GaryRidgway** [comment]
@bspeare The updates with uids that were recently made should address your issues!

@pyrello I cant find any problems with borders on the left side of the tables.

**Review by bspeare — APPROVED** [review]

**Comment by bspeare** [comment]
Approving the changes, but we need to make a follow-up issue for some of the bugs we found.

**Pull request merged**
