### PR TITLE
Classrooms - Migration Featured Image

### LINKED ISSUE #6395: Classroom room migration updates
# Story

As a Classrooms website owner, I would like the first image in our image gallery to be used as our featured image for migrated rooms in addition to the gallery.

# Proposed Solution

- [x] Update migration to map first gallery image to the featured image
- [x] sync dbs
- [x] re-run migration in dev

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #6395

# To Test

Sync D7 site in devdesktop (uiowa703)
Sync classrooms in D8: `ddev blt ds --site=classrooms.uiowa.edu`
`ddev composer install` if you haven't in awhile, or have been working on other branches
Enable the migrate module: `ddev drush @classrooms.local en classrooms_migrate`
Log in and visit the migrate config page: `ddev drush @classrooms.local uli /admin/config/sitenow/sitenow-migrate`
Complete the page using the form help text and devdesktop info
Check the migration status: `ddev drush @classrooms.local ms`
Import the rooms: `ddev drush @classrooms.local mim classrooms_room`
Go into the site, check out some of the newly migrated rooms, now with featured images.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Looking for technical review before running in DEV

**Comment by GaryRidgway** [comment]
I will review this

**Comment by joewhitsitt** [comment]
Alan mentioned he tried to run this and there was an issue with the files.

**Comment by GaryRidgway** [comment]
> Alan mentioned he tried to run this and there was an issue with the files.

My mistake, I had, unluckily, only seen rooms without images when checking the first few times, and after going through others I am seeing the featured images!

**Review by GaryRidgway — APPROVED** [review]

**Pull request merged**
