### PR TITLE
Metatag Enhancements and Fixes

### LINKED ISSUE #2169: Support Twitter Card Metatag
## Problem

Despite all of the metatags we output, we are missing out on twitter card...

## Proposed Solution

Enable sub module, configure defaults for page/person/article

## Test

https://cards-dev.twitter.com/validator

There was a browser extension that validated the current page (locally) that was nice, but I forget what it was called. Also tested Facebook open graph as well.

### LINKED ISSUE #2978: og:image meta tag is not being populated for Grad homepage
# Problem
The `og:image` metatag is not being populated for https://grad.uiowa.edu/. 

# Steps to reproduce
View source and confirm or use the FB scraping debug tool: https://developers.facebook.com/tools/debug/?q=grad.uiowa.edu

# Proposed solution
TBD

### LINKED ISSUE #3074: Illegal offset type in Drupal\schema_metatag\SchemaMetatagClient->objectInfo()
# Problem
Big "error" appears to admins related to schema_metatag.

# Steps to reproduce
Normal node backend operations

# Proposed solution
Update when new stable release is available: https://www.drupal.org/project/schema_metatag/issues/3174103

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/2169
Resolves https://github.com/uiowa/uiowa/issues/2978
Resolves https://github.com/uiowa/uiowa/issues/3074

To make this possible, I had to establish the token view mode for the default content types. If layout builder is used and the featured image is not displayed, the token is null. This solves this and other situations.

## To Test

- v2/v3, admissions and other splits should have clean imports. Other sites touched include:
  - admissions, brand, policy.clas, ighn.international, grad, uiowa.edu, hr, presidentialsearch
- As a webmaster on a v2/v3 and any of the custom sites where config has been updated, you can see and set Twitter card metatag information (title, summary, image). Defaults are given.
- Inspecting the source you should see twitter metatag information for:
  - twitter:card which should be `summary_large_image`
  - twitter:description
  - twitter:title
  - twitter:image
- The Twitter Card fieldset is collapsed by default within the SEO settings for sites using common node add/edit defaults similar to Advanced and Open Graph.
- There are no notice notifications when add/editing content or metatag configuration as an Admin.

_Note: validating using twitter's https://cards-dev.twitter.com/validator will have to wait till stage or prod._

## Examples

**Regardless of website, as a webmaster you should see this on Page, Article, Person content type add/edit forms within the SEO Settings fieldset (collapsed by default):**
Screen Shot 2021-03-26 at 11 51 57 AM

**Regardless of website, you should see this kind of output in the source for Page, Article, Person assuming there is a Title, Featured Image/Person photo and a Content Description/Article Summary/Short Biography.**
Screen Shot 2021-03-26 at 11 55 23 AM

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling down to test.

**Comment by bspeare** [comment]
@joewhitsitt do you have to manually `cim` the tokens after running `blt ds`?

**Comment by joewhitsitt** [comment]
You shouldn't have to CIM to get the token displays or the pre-filled Twitter Card meta values. What site did you try?

**Comment by bspeare** [comment]
Admissions complained about `Configuration in the database does not match configuration on disk.`

**Comment by joewhitsitt** [comment]
okay, i will take a look this morning. thanks for trying!

**Comment by joewhitsitt** [comment]
Admissions' #3204 strikes again... working on a fix

**Comment by joewhitsitt** [comment]
This should be ready to test again.

**Comment by GaryRidgway** [comment]
pulling down to test

**Comment by bspeare** [comment]
@joewhitsitt I'm only seeing this on the Brand site:

```
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="My Page Title" />
```

Is that the default expectation?

**Comment by joewhitsitt** [comment]
> Is that the default expectation?

Better than nothing. Did you provide a featured image and content description?

**Comment by bspeare** [comment]
Where do I go to establish the `[node:field_teaser]` for the description?

**Comment by joewhitsitt** [comment]
You should see a Twitter Card [closed] field set with a description field

**Comment by bspeare** [comment]
@joewhitsitt Does it pull a fallback value from the node or do you have to specifically set it in the Twitter Card area?

**Comment by GaryRidgway** [comment]
I was able to properly import all config on to admissions, hawkeyemarchingband, and uiowa. I am seeing the twitter metatag dropdown on articles on sandbox, admissions, and hawkeyemarchingband, but not on uiowa.edu.

**Comment by bspeare** [comment]
To verify, are these the correct expectations?

- V2/V3 Articles - Pulls description from body field
- V2 Pages - Does not pull description from body field
- V3 Pages - Only pulls description if you use the body field, not the text area in layout builder

**Comment by joewhitsitt** [comment]
Thanks again for the testing. I am going to bring this down again and iron this out

**Comment by joewhitsitt** [comment]
>Where do I go to establish the [node:field_teaser] for the description?

This is the Content Description/Article Summary/Short Biography field in the sidebar of the node add/edit screen.

>Does it pull a fallback value from the node or do you have to specifically set it in the Twitter Card area?

The tokens in place for title, featured image/photo, Content Description/Article Summary/Short Biography is the default. Body/Person Biography field maps to the field:teaser token/description when that is empty. Otherwise editors can remove the token and provide their own values for these. This is how the other metatags work.

> but not on uiowa.edu

@GaryRidgway what page? Everything but the fronte page should work like the other sites. https://uiowa.local.drupal.uiowa.edu/node/1/edit has hardcoded "front page" metatags for everything. https://uiowa.local.drupal.uiowa.edu/admin/config/search/metatag/front

>To verify, are these the correct expectations?
>V2/V3 Articles - Pulls description from body field
>V2 Pages - Does not pull description from body field
>V3 Pages - Only pulls description if you use the body field, not the text area in layout builder

Body/Person Biography field should be the fallback for description as long as that field:teaser token is still placed. V2 doesn't have a body field on page so the fallback doesn't work there. Layout Builder is not involved in any of this.

**Comment by joewhitsitt** [comment]
Waiting to hear back from Alan on the homepage site issue, but I pulled again and it seems to work as designed. I added example screenshots and more info to the testing.

Thanks for bringing up the body/bio fields. I forgot we wired that up and it seems to work as long as that token is still placed.

**Comment by GaryRidgway** [comment]
Pulling down to retest the problems i saw with uiowa

**Comment by GaryRidgway** [comment]
I seem to have made a mistake, the uiowa twitter card meta is working as intended. I think the last time i checked i was uli'ed in to the default site.

**Comment by joewhitsitt** [comment]
so we good?

**Review by GaryRidgway — APPROVED** [review]
we good!

**Pull request merged**
