### PR TITLE
Initialize research.uiowa.edu multisite on uiowa

### PR DESCRIPTION
**Pull request by e-marie-w**
Using `uiowa` because SSL cert for `*.research.uiowa.edu` already exists there and is covering www.research.uiowa.edu.

### CODE REVIEW

**Review by richardbporter — APPROVED** [review]

**Comment by e-marie-w** [comment]
Thanks @richardbporter!

**Comment by joewhitsitt** [comment]
Heads up @e-marie-w. *.research.uiowa.edu won't cover research.uiowa.edu. only www.research.uiowa.edu if that is needed, so a separate SSL issue should be created to cover research.uiowa.edu on that app

**Comment by e-marie-w** [comment]
#5252 already created! Even remembered the SSL label this time!

**Comment by joewhitsitt** [comment]
Oops. Missed that. Nice!

**Pull request merged**
