### PR TITLE
Display Advisor name as plain text if marked as "Hide on lists" and other Immunology updates

### LINKED ISSUE #2477: When advisor field points to person with "Hidden on lists" checked, do not link to that profile page.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #2477 

# How to test

## Site not using `person_extended`

* `blt ds --site=grad.uiowa.edu`
* View https://grad.local.drupal.uiowa.edu/people/anders-frieberg and see that there are no errors related to logic checking the advisor field, which doesn't exist on this site.

## Site using `person_extended`

* `blt ds --site=immuno.grad.uiowa.edu`
* Add a person of type "Faculty" and select "Hide on lists" from "Promotion options"
* Add the person you just created as an Advisor to http://gradimmuno.local.drupal.uiowa.edu/node/646/edit and save the form.
* View the page to the see that the Faculty name you just added is not linked: http://gradimmuno.local.drupal.uiowa.edu/people/mayo-akinbo
* Visit http://gradimmuno.local.drupal.uiowa.edu/people/students and note that the person in the Advisor column that you just created and connected to Mayo Akinbo is not linked.

## Immunology updates

* Visit http://gradimmuno.local.drupal.uiowa.edu/node/391/edit and view the Publication links field.
* Toggle the "Faculty" Person Types checkbox and see that the above field disappears and reappears.
* View http://gradimmuno.local.drupal.uiowa.edu/people/research and make sure that it is working.

### CODE REVIEW

**Comment by pyrello** [comment]
I am currently stuck on the part of this that alters views field output. I'm not sure how to actually alter the output for an individual field.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Why not build the conditional logic into the rewrite results field using Twig? Ill update this post with an example if I can create one quick.

It looks like People is just displaying the content and not the fields. Ill keep looking.

**Comment by pyrello** [comment]
@mark-bennett-uiowa The view that I'm targeting is a view that is custom to Immunology called `person_custom`.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested. 👍 

Unrelated to this PR: Noticed there are "and transplant immunology" (think it's supposed to exist as part of "Immune tolerance, autoimmunity, and transplant immunology" and not on its own) and "chicken" in the Research Areas taxonomy.

**Pull request merged**
