### PR TITLE
Facilities building content type, view and api

### LINKED ISSUE #5659: Searchable list of FM managed buildings
# Story

As a Facilities site owner, I would like to display a searchable list of FM managed buildings so that visitors can quickly find a FM managed building.

# Additional Information

Should be able to be placed on a layout builder page so that editors can add additional contextual content.
Should output building number, building name and building abbreviation.
Should be able to sort by and search each of the fields being output.
Building name should render as a link to a page that will eventually contain additional building information for that specific building.

Endpoint - https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings
Existing code - /docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/includes/facilities_buildings.buildings.inc
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_buildings/facilities_buildings.module
/docroot/sites/www.facilities.uiowa.edu/modules/custom/facilities_core/facilities_core.module (API call)

Existing site - https://www.facilities.uiowa.edu/buildings

# Proposed Solution

- [x] Building content type (webmasters and below do not need access to add/edit/delete)
  - [x] Building Name
  - [x] Building Abbreviation
  - [x] Building Number
- [x] Create views block utility table to filter, sort on.
- [x] Periodically add/update/delete from https://bizhub.facilities.uiowa.edu/bizhub/ext/buildings (e.g. Feeds, a Facilities type MAUI API integration running on cron)

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/5659

# To Test

- `ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli /node/add/building`
- Create a fake building (e.g. building number = asdf), then create a real building (e.g. 0002, Schaeffer Hall) with a custom name and a blank abbreviation.
- `ddev drush @facilities.local fm-buildings` (383 buildings created, 1 update, 1 deleted)
- https://facilities.uiowa.ddev.site/admin/content?title=&type=building&status=All&field_tags_target_id=
- Visit your real building (e.g. https://facilities.uiowa.ddev.site/building/0002), it should have correct information.
- Visit your fake building (e.g. https://facilities.uiowa.ddev.site/building/asdf), it should be a 404.
- Unlike other content types we create this one will be different in terms of our "content type checklist":
  - As a webmaster, you should be able to see the buildings in the content overview, but you should not have add/edit/delete permissions. Since this content type does not have editor interaction, moderation was not added.
  - On the building node itself you can see the revisions tab and for the one that was updated you should see more than one revision. There is a max of three revisions set.
  - There is basic meta tag/schema type Place information that is in the source, but that there isn't a body/teaser field to fill out meta descriptions.
- Go to a basic page and add the "Building list" views block under Site custom within the More... section. See that the filter works for building name, number and abbreviation. Table responsive is added.
- Test the `bypass node access` permission change by making sure a webmaster can assign a page to the menu system under an unpublished node. Also for the ambitious, you can check all of the custom content types listed below to make sure the webmasters can add/edit/delete them (exception being this building content type on facilities)

<details>
<summary>content types splits</summary>

  config/default/node.type.page.yml
  config/default/node.type.person.yml
  config/default/node.type.article.yml
  config/features/event/node.type.event.yml
  config/features/scholarship/node.type.scholarship.yml
  config/features/topic_page/node.type.topic_collection.yml
  config/features/areas_of_study/node.type.area_of_study.yml
  config/features/periodical/node.type.publication_issue.yml
  config/features/thesis_defense/node.type.thesis_defense.yml
  
  config/sites/hr.uiowa.edu/node.type.faq.yml
  config/sites/now.uiowa.edu/node.type.contact.yml
  config/sites/grad.uiowa.edu/node.type.mentor.yml
  config/sites/grad.uiowa.edu/node.type.scholar.yml
  config/sites/grad.uiowa.edu/node.type.student_profile.yml
  config/sites/uipress.uiowa.edu/node.type.book.yml
  config/sites/brand.uiowa.edu/node.type.lockup.yml
  config/sites/icsa.uiowa.edu/node.type.project.yml
  config/sites/iisc.uiowa.edu/node.type.partner.yml
  config/sites/iisc.uiowa.edu/node.type.project.yml
  config/sites/classrooms.uiowa.edu/node.type.room.yml
  config/sites/admissions.uiowa.edu/node.type.major.yml
  config/sites/admissions.uiowa.edu/node.type.event_series.yml
  config/sites/admissions.uiowa.edu/node.type.area_of_study.yml
  config/sites/admissions.uiowa.edu/node.type.transfer_tips.yml
  config/sites/admissions.uiowa.edu/node.type.student_profile.yml
  config/sites/policy.clas.uiowa.edu/node.type.book.yml
  config/sites/sppa.uiowa.edu/node.type.opportunity.yml
  config/sites/housing.uiowa.edu/node.type.residence_hall.yml
  config/sites/facilities.uiowa.edu/node.type.named_building.yml
  config/sites/grad.admissions.uiowa.edu/node.type.area_of_study.yml
  config/sites/grad.admissions.uiowa.edu/node.type.costs_estimate.yml
  config/sites/ighn.international.uiowa.edu/node.type.ighn_person.yml

</details>

There is a troublesome node: 321 Melrose Avenue (0307) where the abbreviation is different from the others. It is a blank string instead of NULL. Created a temporary check for it as well as a follow-up todo https://github.com/uiowa/uiowa/issues/6084

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Moving back to draft. Remembered that I made a permission change that a few sites will need to update.

**Comment by joewhitsitt** [comment]
Because of the `bypass node access` permission change, I think I need to go through all of the splits to make sure webmasters have access to the content types in those splits...

**Comment by joewhitsitt** [comment]
Anyone know if webmasters should have the ability to add/edit/delete projects on https://icsa.uiowa.edu/projects ?

Nevermind. mjcranston, a webmaster has authored most of the project content. I am going to update their split so that ability is not lost with the `bypass node access` change

**Comment by joewhitsitt** [comment]
Ready for review again

**Comment by GaryRidgway** [comment]
Going to pick this up and test

**Review by GaryRidgway — COMMENTED** [review]
Reviewing these changes, everything functions as it is described in the testing instructions. However, the one thing that I am finding missing is a reset button for the filters on the view. We have used that as a standard piece of functionality across our platform and i think it would do well to have it here as well. Thoughts? 

If explicitly not wanted, I'll approve. If it is agreed we should have the "Reset" button, I will approve after its addition.

**Comment by briand44** [comment]
I don't think the named building view has the reset button either. I think I would be in favor of adding it as well but if we do we should add it to both to be consistent.

**Comment by joewhitsitt** [comment]
This has been added.
Screen Shot 2023-01-18 at 3 43 22 PM

**Comment by GaryRidgway** [comment]
Fantabulous

**Review by GaryRidgway — APPROVED** [review]

**Pull request merged**
