### PR TITLE
[Dev testing] Symfony mailer log feature

### PR DESCRIPTION
**Pull request by bspeare**
Related to https://github.com/uiowa/uiowa/issues/8106.  More conversation at https://iowaweb.slack.com/archives/C0164FNN1PV/p1730739762101199. 

# How to test

```
ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local config-split:activate mailer_log -y && ddev drush @sandbox.local uli /admin/config/system/mailer/symfony_mailer_log/settings
```
1. Confirm log settings are set
2. Confirm transport type is set `/admin/config/system/mailer/transport`
3. Overriding `null` https://github.com/uiowa/uiowa/blob/main/config/envs/dev/config_split.patch.symfony_mailer.settings.yml

### CODE REVIEW

**Comment by joewhitsitt** [comment]
okay. catching up here on the acquia ticket and refreshing my memory about what worked and what didn't.

**Comment by joewhitsitt** [comment]
I think this looks like it would override the env config and allow emails out on a per site basis 🤞 

Based on the ticket and card, just curious about how we plan on providing access to this Acquia user?

**Comment by bspeare** [comment]
@joewhitsitt are they able to ssh into our servers and `uli` into the site?

**Comment by joewhitsitt** [comment]
From a technical standpoint, I would assume so but I feel like they would have asked the question differently if they could or be allowed to do that. New fear has been unlocked for me btw 😟 

It sounded like they were looking for a public facing form to fill out BCC for both webform and a symfony mailer form and then to see the logging happen on the backend.

**Comment by bspeare** [comment]
Good points.  Do you think we have a way for them to test this or will we just test the logging and share the results on the support ticket?

**Comment by joewhitsitt** [comment]
Not as easy as ULI no. Goes back to my original thought on debugging by creating a separate but similar email trigger to that of ITS.

I guess I am fin approaching them with what we got to keep the ticket active.

- logging has been turn on this site (include multisite server path)
- they can uli in and use the test form (bcc field setup) and a webform where bcc has been configured to receive confirmation OR we can enter their details, take note of the timestamp and submit that to them.

**Comment by bspeare** [comment]
@joewhitsitt what is the multisite server path for the sandbox dev site?

**Comment by joewhitsitt** [comment]
We seem to constantly need to help/remind Acquia we are running a multisite so they need to navigate there to `uli` if that is even an option for them: 

`/var/www/html/uiowa02.dev/docroot/sites/sandbox.uiowa.edu`

**Comment by bspeare** [comment]
I have added this to sandbox.dev.drupal.uiowa.edu and responded to the Acquia ticket.

**Comment by bspeare** [comment]
The changes in this pr appear to have BCC working on sandbox.dev.drupal.uiowa.edu.  Acquia support was able to show us that `ddev drush @sandbox.dev cget symfony_mailer.mailer_transport.sendmail --include-overridden` was not returning `/usr/sbin/sendmail -t` and that the updates to the global settings in this pr fixes that.

**Comment by joewhitsitt** [comment]
Can we close this now since https://github.com/uiowa/uiowa/pull/8224 got merged in?

**Pull request closed without merging**
