### PR TITLE
Fix for stage/test deployment issue

### LINKED ISSUE #8119: deployments to uiowa07, uiowa08, uiowa09 test/stage
>It looks like test environments > 06 are not being updated when a branch is merged into main. At least I'm not seeing it reflected in [#drupal-status](https://iowaweb.slack.com/archives/CSQA18BK4)

https://iowaweb.slack.com/archives/C0164FNN1PV/p1727709896178109

Hopefully just drush alias issue otherwise something funky with ACN stage vs prod that isn’t triggering it

### PR DESCRIPTION
**Pull request by e-marie-w**
Fixes #8119. Duplicated hooks/test to create hooks/stage, as suggested in support ticket.

# How to test
Code review.

### CODE REVIEW

**Review by joewhitsitt — APPROVED** [review]
:shipit:

**Comment by pyrello** [comment]
Reviewing

**Comment by pyrello** [comment]
> Reviewing

Nevermind

**Comment by joewhitsitt** [comment]
🏃 💨

**Pull request merged**
