### PR TITLE
Adminimal 2

### PR DESCRIPTION
**Pull request by ethanstjohn**

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I think `.toolbar-tab` is what we are concerned about. It is grey text on our environment bg-color that is inaccessible. The icon is decorative and doesn't have to meet contrast guidelines.

I wouldn't worry about the sub tool bar.

**Review by joewhitsitt — CHANGES_REQUESTED** [review]
See comment about only focusing toolbar-tab

**Comment by ethanstjohn** [comment]
I committed the change.

**Review by ethanstjohn — COMMENTED** [review]
Hopefully, fixed.

**Review by joewhitsitt — APPROVED** [review]
looks good after https://github.com/uiowa/uiowa/pull/235/commits/e3a56d7f03eee625d30d4d3685d4545f2d24a12b'

tour is a button and wasn't getting the 'a' specific style

**Pull request merged**
