### PR TITLE
Grad - Added missing program entries manually

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

Code review.

### CODE REVIEW

**Review by cory-skeers — APPROVED** [review]
Reviewed the changes, and they look good to go

**Review by GaryRidgway — APPROVED** [review]
REVIEWED, SEEMS GOODLY

**Comment by GaryRidgway** [comment]
> Reviewed the changes, and they look good to go

How did we post those at exactly the same time...

**Comment by cory-skeers** [comment]
> > Reviewed the changes, and they look good to go
> 
> How did we post those at exactly the same time...

Pure, unadulterated talent.

**Pull request merged**
