### PR TITLE
Change ddev database container to MySQL 5.7.

### LINKED ISSUE #4577: Switch to MySQL 5.7 locally and remove drupal/mysql56.
# Problem 
AC uses MySQL 5.7 but we're using MariaDB locally. We should try to replicate AC as closely as possible. There can be issues with different versions of MySQL so its good test locally first. https://support.acquia.com/hc/en-us/articles/1500000370601-How-will-MySQL-5-7-affect-Drupal-and-the-database

# Proposed solution
Change the DB type as outlined in the [docs](https://ddev.readthedocs.io/en/stable/users/extend/database_types/). Take note of the [caveats](https://ddev.readthedocs.io/en/stable/users/extend/database_types/#caveats) and plan with the team a good time to do this, explaining what is required.

Also `composer remove drupal/mysql56` and test things out locally. This module is not enabled and does not need to be uninstalled first.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #4577

**Warning**: This will potentially break your existing local databases. Once this PR is merged and developers pull, they will not be able to `ddev stop/start/restart` until the database container is deleted! I'm looking for feedback on how to coordinate merging and notifying our team.

This PR changes the location of drush-backups to be within the synced ddev folder. Otherwise, they are stored in the /tmp directory of the web container which is not easily accessible and volatile. Storing database backups in the synced folder may have performance implications so removing unused database dumps occasionally is probably a good idea.

# Post-merge instructions
1. `git checkout main`
2. `git pull`
3. Back up your databases, if needed.
  a. Configure your blt/local.blt.yml multisites as necessary.
  b. `ddev ssh`
  c. `blt ume 'sql:dump --result-file auto --gzip'`
  d. Backups will be saved to the tmp/drush-backups directory within the application and therefore available on your host machine.
  e. `exit`
4. `ddev poweroff`
5. `ddev delete --omit-snapshot`
6. `ddev start`
7. `ddev auth ssh`
8. `ddev composer install`
9. Restore a database, if needed.
  a. `ddev ssh`
  b. `gunzip tmp/drush-backups/mysite/123456/mydatabase.sql.gz`
  c. `drush @mysite.local sql:create`
  d. `drush @mysite.local sqlc < tmp/drush-backups/mysite/123456/mydatabase.sql`
  e. `drush @mysite.local cr`
  f. `exit`
10. ??
11. Profit

<details>
<summary>Old PR testing instructions</summary>

## Verify MariaDB is in use.
1. `git checkout main`
4. `ddev describe`
10. See the db container is using MariaDB.

## Back up your databases, if needed.
1. Configure your blt/local.blt.yml multisites as necessary.
2. `git checkout ddev-mysql`
3. `ddev ssh`
12. `blt ume 'sql:dump --result-file auto --gzip'`
13. Backups will be saved to the tmp/drush-backups directory within the application and therefore available on your host machine.
14. `exit`
15. `git checkout main`

## Delete ddev containers
1. `ddev stop`
2. `ddev delete --omit-snapshot`

## Change db containers and remove mysql56
1. `git checkout ddev-mysql`
2. `ddev start`
3. `ddev composer install`
4. `ddev describe`
5. See MySQL 5.7 is used for the db container.

## Sync some sites, test stuff
1. `ddev blt sync --site mysite.uiowa.edu --define drush.aliases.remote=mysite.test` (Syncing from prod is currently failing for unrelated reasons.)
2. Log in, test various things.
4. `ddev blt drupal:install`
16. `ddev blt tests` 

## Restore a database, if needed.
1. `ddev ssh`
17. `gunzip tmp/drush-backups/mysite/123456/mydatabase.sql.gz`
18. `drush @mysite.local sql:create`
19. `drush @mysite.local sqlc < tmp/drush-backups/mysite/123456/mydatabase.sql`
20. `drush @mysite.local cr`
</details>

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I'd like to hold on this until we finish https://github.com/uiowa/uiowa/pull/4999 (Makur's local db holds all of the content changes)

**Comment by richardbporter** [comment]
Getting an error trying to blt sync. Looking into it...

**Comment by richardbporter** [comment]
I think this is ready for review.

**Comment by joewhitsitt** [comment]
should testing wait on this until the acquia ticket is updated?

**Comment by richardbporter** [comment]
> should testing wait on this until the acquia ticket is updated?

I don't think so. I updated the sync step to use another remote alias for the test environment. Can't `dsa` at the moment.

**Comment by joewhitsitt** [comment]
Okay. pulling to test

**Comment by richardbporter** [comment]
Percy seems to be having an issue with the new front page. Seems like an image is present and sometimes not. I'm thinking lazy load has not loaded all images when the snapshot is taken.
Screen Shot 2022-03-31 at 1 00 56 PM

**Review by joewhitsitt — APPROVED** [review]
I made the jump and didn't backup so i didn't test the restore. Everything related to the new, worked. Holy guacamole, running all the tests take a while. Hello future.

**Comment by joewhitsitt** [comment]
🤞

**Comment by richardbporter** [comment]
Trying different config listed here: https://docs.percy.io/docs/percy-snapshot#configuration

**Comment by richardbporter** [comment]
I think that did it.

**Comment by richardbporter** [comment]
@joewhitsitt Thoughts on scheduling this or how the steps could be any more clear?

**Comment by joewhitsitt** [comment]
Flexible on scheduling. It would be nice to have a stable local before web community meeting tomorrow.

I had to add-in a `ddev auth ssh` to sync a site again and I think it wanted me to `ddev poweroff` as well

**Comment by richardbporter** [comment]
> Flexible on scheduling. It would be nice to have a stable local before web community meeting tomorrow.
> 
> I had to add-in a `ddev auth ssh` to sync a site again and I think it wanted me to `ddev poweroff` as well

I consolidated the PR description to make it easier to follow and included those two things.

**Pull request merged**
