### PR TITLE
IISC - Lots of updates

### LINKED ISSUE #5037: IISC - Customize Article content type
## Story
As an IISC editor/webmaster, I want to associate articles with the people, partners, and projects mentioned in them. This allows me to display relevant news on the person, partner, or project page. 

## Solution

- Add 'Related Partners' field that allows users to add existing Partners
- Add 'Related Projects' field that allows users to add existing Projects
- Add 'Related Individuals' field that allows users to add existing People

### LINKED ISSUE #5049: IISC - Customize Person content type
## Story
As an IISC editor/webmaster, I want the same fields/options available in D7 Person content to be available in the D9 Person content.

## Solution

Add the 'Groups' field options (Affiliated Faculty and Staff, Community Partner, IISC Faculty & Staff Network, IISC Staff) to our Person Type list. Remove other Person Type options?
Create 'Role with the IISC' textfield (note: this is different from the Job Title field, which can be migrated to the Title/Position field in D9.)

### LINKED ISSUE #5054: IISC - Create Project content type
## Story

As an IISC editor/webmaster, I want a way to showcase our students' projects, including all the details such as what school year was it, who led it, what partner(s) were involved, etc.

## For reference

https://iisc.uiowa.edu/iowa-city-solar-study

## Solution
Create a content type with the following fields:

- Title (text)
- Body (text, long)
- Image (single)
- College/Department (taxonomy)
- Deliverables - usually pdfs
- Academic Year - formatted as 2020-2021 (taxonomy)
- Project Partner (reference Partners content) - If the Partners content type doesn't exist yet, then we can add this field and set up display and form display for it in #5031 
- Led by (reference People content)
- Project Links (URL field)
- Tags (tags)

### LINKED ISSUE #5259: IISC - Create partner content migration
Create a migration and source class to handle migrating partner content type.
- Depends on the person migration.
- Current partner field is not being migrated.

### LINKED ISSUE #5262: IISC - Create person content migration
Create a migration and source class to handle the person type.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5049 
Resolves #5054
Resolves #5037 
Resolves #5262 
Resolves #5259 

# How to test

## Basic setup
- `ddev blt ds --site iisc.uiowa.edu`
- `ddev drush @iisc.local uli`

## Migrations
- In Dev Desktop, pull down database for iisc.uiowa.edu
- `ddev drush @iisc.local en iisc_migrate -y && ddev drush @iisc.local uli admin/config/sitenow/sitenow-migrate`
- Fill in form with the appropriate info for local IISC migration.
- `ddev drush @iisc.local ms` to check that all migrations are showing up: 
  - `iisc_people`
  - `iisc_person_redirects`
  - `iisc_partners`
  - `iisc_partner_redirects`
  - `iisc_projects` - won't be run as part of testing this PR
  - `iisc_project_redirects` - won't be run as part of testing this PR
  - `iisc_articles` - won't be run as part of testing this PR
  - `iisc_article_redirects` - won't be run as part of testing this PR

### People migration
- `ddev drush @iisc.local mim iisc_people`
- `ddev drush @iisc.local mim iisc_person_redirects`
- Review https://github.com/uiowa/uiowa/issues/5262#issuecomment-1124521947 to understand how we are mapping existing field data for Group(s) and Role with IISC fields.
- Check https://iisc.uiowa.ddev.site/people/brenda-nations for Community Partner group being mapped to person type with the same name.
- Check https://iisc.uiowa.ddev.site/people/travis-kraus (click edit tab and expand Relationships section in right sidebar) to see other 3 groups being mapped to tags of the same name.
- Check that `field_teaser` (Short bio) is being generated from the biography field.
- Check that https://iisc.uiowa.ddev.site/carrie-schuettpelz redirects to https://iisc.uiowa.ddev.site/people/carrie-schuettpelz

### Partners migration
- `ddev drush @iisc.local mim iisc_partners`
- Check county field migrated correctly: https://iisc.uiowa.edu/mrwma => https://iisc.uiowa.ddev.site/partners/maquoketa-river-watershed-management-authority
- Check related person: https://iisc.uiowa.ddev.site/partners/iowa-city
- Check that https://iisc.uiowa.ddev.site/mrwma redirects to https://iisc.uiowa.ddev.site/partners/maquoketa-river-watershed-management-authority

### Person content type
- Visit https://iisc.uiowa.ddev.site/node/add/person and check that person types consist of "Community Partner", "Faculty", "Staff", and "Student".

### Partner content type
- Check that migrated partner content uses `/partners/$title` for path aliases.

### Project content type
- Create 2-3 projects. Include references to other content types.
- Check project page display looks okay.
- Check that migrated project content uses `/projects/$title` for path aliases.

### Article content type
- Visit https://iisc.uiowa.ddev.site/node/add/article to see that new Related Content field exists.
- Add some related content of each type (person, partner, and project) to an existing article and view the page to see that all 3 display below in separate lists.

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare I am running into an issue with the layout not looking right. It seems like this is something I have encountered before, but I don't remember how it is solved. I tried copying the settings from the partner content type and that didn't help.

I also encountered another issue that I have run into before and don't remember how to resolve: After adding the project content type to the moderation workflow, it automatically added a block for the moderation control to my layout, but when I try to view the layout template builder page or a content page, I see the broken block plugin error message. I'm not sure what setting I'm missing.

**Comment by bspeare** [comment]
@pyrello it looks like you are using the core two column layout.  You need to use the one further down.   I always run into this issue too. 
<details>
Screen Shot 2022-05-11 at 8 23 24 AM
 </details>

**Comment by bspeare** [comment]
I'm not seeing the moderation block or the error message when I try to edit the project content type manage display page.

**Comment by pyrello** [comment]
Another weird thing that is happening is that when I export the site split, full config for the viewer role is being exported in addition to the patch.

**Comment by pyrello** [comment]
> I'm not seeing the moderation block or the error message when I try to edit the project content type.

I pulled it out for now. But if you try to add it back into the layout, does it work? I tried multiple times and after I added it, it would start showing the error message.

**Comment by bspeare** [comment]
I had the same issue for the project content type and the problem went away after I re-saved the moderation state in the form display page `admin/structure/types/manage/project/form-display`.  Not sure it that will work here.

**Comment by pyrello** [comment]
@joewhitsitt I attempted to add a single related content field to the article content type per #5037 because I was curious about whether that work. However, I can't seem to get the contextual filter working correctly and I can't figure out what I am doing wrong. If you had a chance to take a look and see if you can figure out what I am missing, that would be great!

**Comment by joewhitsitt** [comment]
yeah, i can take a look in a bit

**Comment by pyrello** [comment]
> I had the same issue for the project content type and the problem went away after I re-saved the moderation state in the form display page `admin/structure/types/manage/project/form-display`. Not sure it that will work here.

Huh. That does seem to have worked. No idea why that would be the case. I added a note about this quirk in the wiki: https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes

**Comment by joewhitsitt** [comment]
>Another weird thing that is happening is that when I export the site split, full config for the viewer role is being exported in addition to the patch.

I was getting this on brand for the webmaster role - https://github.com/uiowa/uiowa/pull/5223

**Comment by pyrello** [comment]
Well, with something this big, I'm probably missing something, but I've tried to be thorough in the testing details.

**Comment by pyrello** [comment]
A note here about the migrations: Out of curiosity I decided to generate a migration using the `drush generate` command. The output omitted some fields that we typically have, but I had wondered whether they were necessary or not. It also reorganized the file in ways that I liked. So, I adopted a new-ish format for all the migration files in this PR that I think would be a good model going forward. Also made some adjustments based on #5243.

**Comment by cory-skeers** [comment]
Taking a look at this.

**Comment by cory-skeers** [comment]
For the person redirects, I'm getting only the first redirect created, and the rest are throwing a constraint integrity violation for duplicate hashes:
image
This isn't a problem for the partners redirects.

**Comment by pyrello** [comment]
Hmm... I thought I had fixed this.

**Comment by cory-skeers** [comment]
> Hmm... I thought I had fixed this.

Oh wait--you did! I just didn't have the most recent code.

**Comment by pyrello** [comment]
> Oh wait--you did! I just didn't have the most recent code.

I always forget that I have to re-import the config after making changes to it.

**Comment by cory-skeers** [comment]
For the related content on Articles, it's possible to tag the same thing multiple times. Not an actual issue (can do the same with regular tags), just happened to notice it.

If there are more than 5 items, the pager can be a little confusing in how sections may get split up, or a section like People may appear only on a later page. Not an issue if we know there will be at most a few related pieces.
image

image

**Comment by pyrello** [comment]
> If there are more than 5 items, the pager can be a little confusing in how sections may get split up, or a section like People may appear only on a later page. Not an issue if we know there will be at most a few related pieces.

Hmm... I wonder if making 3 discrete views would be a better idea. Either way, I'm cool with moving forward with it as is for now so that we can test it out more and see what might need to change about it.

**Comment by joewhitsitt** [comment]
Outside looking in, not sure if it has changed, but when i was working with this, I found the field (comma-separated) hard to use as the titles were longer than most tags, etc.

**Comment by pyrello** [comment]
> Outside looking in, not sure if it has changed, but when i was working with this, I found the field (comma-separated) hard to use as the titles were longer than most tags, etc.

I changed this to use the regular autocomplete widget so that you add new items by clicking the "Add another..." button.

**Comment by cory-skeers** [comment]
> Hmm... I wonder if making 3 discrete views would be a better idea. Either way, I'm cool with moving forward with it as is for now so that we can test it out more and see what might need to change about it.

That sounds good to me. I think part of it depends on how much of what kinds of relations might be there when it comes to real content.

One other note with it--the form is a little confusing as it allows you to drag-and-drop to reorder items, but that ordering isn't reflected in the display. It's another nit that's consistent with how other multi-value fields (tags) are presented, but I think it's more noticeable here with the multiple content types. Maybe a bit of help text could be useful?

**Comment by pyrello** [comment]
> That sounds good to me. I think part of it depends on how much of what kinds of relations might be there when it comes to real content.
>
> One other note with it--the form is a little confusing as it allows you to drag-and-drop to reorder items, but that ordering isn't reflected in the display. It's another nit that's consistent with how other multi-value fields (tags) are presented, but I think it's more noticeable here with the multiple content types. Maybe a bit of help text could be useful?

I eventually like to get @joewhitsitt's eyes on it, since he was interested in experimenting with one field as opposed to several. The other thing that this runs into is that it is essentially another way of handling what Dustin had been working on and I think the two approaches might merit some comparing and contrasting since it would likely be confusing to implement them alongside each other. It may just be the case that one field is not the best way to handle this.

**Comment by cory-skeers** [comment]
I've gone through the testing instructions and notes, and everything is looking good, along with the few ongoing discussions (I believe academic year is also being decided?).

I'd be comfortable giving approval since there is continued work that will be done (other migration work, etc) before it really goes primetime, and I don't see anything particularly holding this back, but can leave it if @pyrello or @joewhitsitt (or anyone else) want to dig in more with the related content field or other pieces.

**Comment by joewhitsitt** [comment]
I agree there is a lot going on with one field, so if y'all think there are more cons than pros, it was probably one of the reasons it was multiple fields the first time around. Just on the look out for reuse over one-off for a default content type.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested. Further refinement can happen in follow-up PRs as part of the continued work on these content types and their respective migrations.

**Comment by pyrello** [comment]
Thanks again for testing this, @cory-skeers!

**Pull request merged**
