### PR TITLE
[Tables] Table header scope module

### LINKED ISSUE #8152: Probe table header scope issue
# Story

As a Digital Accessibility Coordinator, I would like to see SiteNow tables include the `scope` attribute on table headers without content editors having to manually apply the html.

# Additional Info

This may have been a regression introduced when upgrading to ckeditor 5.

A couple upstream issues:
https://www.drupal.org/project/drupal/issues/3427076
https://github.com/ckeditor/ckeditor5/issues/3175

A possible related issue in our backlog:
https://github.com/uiowa/uiowa/issues/7440

Should we probe this to see if there is anything we can do to help the upstream issues or to resolve this for SiteNow while we wait for solutions upstream?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/8152. 

# How to test

```
ddev composer install && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /table-without-scope
```
1. Confirm `scope="col"` is on each of the `<th>` tags.
2. Add a new table with a header row. 

Screenshot 2024-11-06 at 11 28 22 AM

2. Save the page and inspect the markup and confirm that `scope="col"` is on each of the `<th>` tags.

### CODE REVIEW

**Comment by bspeare** [comment]
This is ready for review.  Should we create a separate issue for the `'allowed_sources' is not a supported key` work or do we think it should be included as part of adding this module?

**Comment by joewhitsitt** [comment]
just curious on how you worked around the error on save? if this works, the allowed_sources and such can be a separate slice.

Sean raised some concerns about the UX with this solution in the issue. I take it you are fine with moving forward with the module's solution?

**Comment by bspeare** [comment]
@joewhitsitt I just added the config manually which we have done at other times when we needed to update the formats.  I'm fine with the UX because it solves our accessibility problem.

**Comment by GaryRidgway** [comment]
pulling to test

**Review by GaryRidgway — APPROVED** [review]
Re-tested this after the twig fix and it is still working

**Comment by bspeare** [comment]
Thanks @GaryRidgway!

**Pull request merged**
