### PR TITLE
Adopt responsive images part 1

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #1499

For page, article, person teasers as well as the paragraphs card, this PR switches out the programatic single image styles (sitenow_card and sitenow_square_m) for close equivalent responsive image styles using drupal view modes.

Originally scoped to just touch brand.uiowa.edu for adoption of uids_base, with the preprocessing logic in SiteNow profile and custom modules, it was easier to just refactor it.

I don't think an image flush will be necessary for this update. I don't like it, but I am seeing the need for a double refresh on pages with several images.

Follow-up issues will be needed to set a replacement image style and to delete the unused image styles.

## To Test

- I recommend testing a site where you have all the files local and that stage file proxy is not turned on.
- `blt sync --site mysite.com --sync-public-files` and then `pmu` or uninstall stage file proxy locally before rendering front end pages.
- Start viewing pages with content type teaser images and paragraph cards implemented. The images should eventually load via lazy and you should see responsive image information instead of a single image tag. Refreshing the page a couple times might be necessary on pages with a lot of images.

## Split config that was not updated:
**core.entity_view_display.node.article.teaser.yml**
-  docroot/modules/custom/entity_types/entity_types_article/config/install/core.entity_view_display.node.article.teaser.yml

**core.entity_view_display.node.page.teaser.yml**

- config/features/collegiate/core.entity_view_display.node.page.teaser.yml
-  config/policy.clas.uiowa.edu/core.entity_view_display.node.page.teaser.yml
-  config/cogscilang.grad.uiowa.edu/core.entity_view_display.node.page.teaser.yml
- docroot/modules/custom/entity_types/entity_types_page/config/install/core.entity_view_display.node.page.teaser.yml

**core.entity_view_display.node.person.default.yml**

-  docroot/modules/custom/entity_types/entity_types_person/config/install/core.entity_view_display.node.person.default.yml

**core.entity_view_display.node.person.teaser.yml**

-  docroot/modules/custom/entity_types/entity_types_person/config/install/core.entity_view_display.node.person.teaser.yml

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I just tried this branch on policy.clas.uiowa.edu (from prod) locally and there are import issues related to:

- core.entity_view_display.node.article.teaser

```
@@ -58,15 +58,6 @@ content:
     settings:
       link_to_entity: false
     third_party_settings: {  }
-  field_image:
-    type: entity_reference_entity_view
-    weight: 5
-    region: content
-    label: hidden
-    settings:
-      view_mode: large__widescreen
-      link: false
-    third_party_settings: {  }
   field_teaser:
     weight: 3
     label: hidden
@@ -78,6 +69,7 @@ hidden:
   body: true
   content_moderation_control: true
   field_article_author: true
+  field_image: true
   field_image_caption: true
   field_meta_tags: true
   field_tags: true
```

- core.entity_view_display.node.person.default

```
@@ -29,15 +29,6 @@ content:
     region: content
     settings: {  }
     third_party_settings: {  }
-  field_image:
-    type: entity_reference_entity_view
-    weight: 6
-    region: content
-    label: hidden
-    settings:
-      view_mode: large__square
-      link: false
-    third_party_settings: {  }
   field_person_bio:
     weight: 4
     label: visually_hidden
@@ -74,6 +65,7 @@ content:
     settings: {  }
     third_party_settings: {  }
 hidden:
+  field_image: true
   field_person_credential: true
   field_person_first_name: true
   field_person_hide: true
```

- core.entity_view_display.node.person.teaser

```
@@ -24,15 +24,6 @@ targetEntityType: node
 bundle: person
 mode: teaser
 content:
-  field_image:
-    type: entity_reference_entity_view
-    weight: 6
-    region: content
-    label: hidden
-    settings:
-      view_mode: large__square
-      link: false
-    third_party_settings: {  }
   field_person_credential:
     type: string
     weight: 0
@@ -78,6 +69,7 @@ content:
     third_party_settings: {  }
 hidden:
   content_moderation_control: true
+  field_image: true
   field_person_bio: true
   field_person_first_name: true
   field_person_hide: true
```

- core.entity_view_display.paragraph.card.default

```
@@ -30,12 +30,10 @@ content:
     type: text_default
     region: content
   field_card_image:
-    type: entity_reference_entity_view
+    type: entity_reference_entity_id
     weight: 0
     label: hidden
-    settings:
-      view_mode: large__widescreen
-      link: false
+    settings: {  }
     third_party_settings: {  }
     region: content
   field_card_link:
```

As far as I can tell, these were not split

**Comment by pyrello** [comment]
@mark-bennett-uiowa?

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt and @pyrello Im not sure how to answer that really. I didnt include either of those in the split because I wasnt changing anything. Articles, people and paragraphs arent going to be used on the policy site. Cards are only used on the frontpage. Everything else is a book page or basic page. So Im not sure why this is failing.

**Comment by joewhitsitt** [comment]
So the only way I could get around this issue was to split off this config for this site. I also have no idea what the config status of this site is. Did the multiple splits thing get resolved?

I ran this PR on a bunch of sites and policy.clas was the only one with the issue.

```
multisites:
  - brand.uiowa.edu
  - cogscilang.grad.uiowa.edu
  - demo.sitenow.uiowa.edu
  - dentistry.uiowa.edu
  - gis.sites.uiowa.edu
  - hr.uiowa.edu
  - icsa.uiowa.edu
  - ighn.international.uiowa.edu
  - iowasuperfund.uiowa.edu
  - policy.clas.uiowa.edu
  - sitenow.uiowa.edu
  - uiowa.edu
```

The other option is to manually update prod to match the config?

**Comment by pyrello** [comment]
@mark-bennett-uiowa You should review https://github.com/uiowa/uiowa/pull/1530/commits/01bb383c5825fc79bf180e6293ca3ebee931964a and make sure you are comfortable with those changes being added to your split. Alternately, these files could be removed and the changes should revert during the next deployment.

**Comment by joewhitsitt** [comment]
Ideally, I would like to revert that commit and get the site ready to accept the changes if those features aren't currently being used but might in the future.

**Comment by joewhitsitt** [comment]
I believe i have reverted the policy.clas split commit

**Comment by pyrello** [comment]
Hmm... those files still seem to be there. I'm going to manually adjust them and give this a try.

**Comment by joewhitsitt** [comment]
because of the force push you you need to `git clean -f` i think if you have previously pulled this branch

**Comment by mark-bennett-uiowa** [comment]
Okay, I tried to put this in the #drupal channel but after typing it out and submitting, it vanished.
In the policy_clas_uiowa_edu site split, these items are being changed:
**Complete Split:**
Book
Search API
Search API Autocomplete
Database Search
UIowa Book
Views TreeItem
**Partial Split:**
config_split.config_split.policy_clas_uiowa_edu
core.entity_form_display.node.book.default (for some reason the form display was hiding the fields the module added, so I un-hid them and add this item)
core.entity_view_display.node.page.default (Not sure why this was showing as 'changed' but had to add this. This might be part of the problem)
core.entity_form_display.node.page.default
user.role.editor (so that these roles can add/update book nodes)
user.role.publisher
user.role.webmaster
views.view.book_search (this and the following contain updates to the views that will be moved to an update to the module itself shortly)
views.view.book_toc

**Comment by pyrello** [comment]
I did a quick comparison of iowasuperfund and policy.clas to see if there was anything obviously different about their config splits. The one thing I noticed is that policy.clas is blacklisting modules. So I am going to try commenting out each module to see if I can get a different outcome during `blt ds`

**Comment by pyrello** [comment]
Okay, that idea immediately failed because those modules need to be present.

**Comment by joewhitsitt** [comment]
`Search result excerpt` is on the displays.. and this must be the first time the config for these are trying to change since the policy site switched over. unless all sitenow sites adopt this, this is going to throw off the config files. That is why we decided to adopt moderation on all sites because of dynamic fields like this.

**Comment by mark-bennett-uiowa** [comment]
Created #1547 is order to add wildcard fix. Will this help solve current issue properly?

**Comment by pyrello** [comment]
@mark-bennett-uiowa I pushed an update to this PR with the same change. This is because, without the change, the post deployment for this site will fail and prevent other sites from running their updates. When I tested your #1547 PR and tried to export config changes, it didn't pick any up, so even if that was run ahead of this, it would still require exporting the config changes as part of this PR. Better to just do them all at once.

**Comment by mark-bennett-uiowa** [comment]
Yep, just saw that. Thanks for doing that.

**Comment by joewhitsitt** [comment]
that worked. thanks

**Review by pyrello — APPROVED** [review]
Tested locally against hawkeyemarchingband.uiowa.edu. Nice work!

**Pull request merged**
