### PR TITLE
Feature: banner hotfix

### PR DESCRIPTION
**Pull request by bspeare**
Implements this code change from UIDS4 (https://github.com/uiowa/uids/pull/739/files) that reverses the transparent button to white on all background colors but gold and white.  Previously, it was only set to white. 

# How to test

- `blt frontend`
- `blt ds --site=webcommunity.sites.uiowa.edu`
- `ddev drush @siteswebcommunity.local uli`
- Test out the "Build" banner on the home page and try to change the background to all the different colors and verify that the button has sufficient color contrast.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down

**Review by joewhitsitt — APPROVED** [review]
checks out!

**Comment by joewhitsitt** [comment]
actually, i am not seeing the patterns with this (lb preview)

**Comment by bspeare** [comment]
Great observation @joewhitsitt!  I removed some older background definitions in our layout builder admin css if you want to test this again: https://github.com/uiowa/uiowa/pull/5496/commits/eddafe1c19776e3c6527dd5b01fc098e30908ee0.

**Comment by joewhitsitt** [comment]
Just checked it. Works. Thanks!

**Pull request merged**
