### PR TITLE
Feature: banner backgrounds and collections hotfix

### LINKED ISSUE #3660: Banner background image/color options are broken
# Problem

Banner background image/color options are broken from this commit: https://github.com/uiowa/uiowa/commit/2b3f45603e823ef06e5ad132c8cd5dd3b58e791b. 

Screen Shot 2021-06-16 at 8 59 57 AM

# Steps to reproduce
Try adding a banner on prod. 

# Proposed solution
Fix the issue with the noted commit.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3660. 

# How to test
- Try adding a new banner and verify that the Background select appears:

Screen Shot 2021-06-16 at 9 39 25 AM

- Try adding a collection and verify that the view mode sits above the collection items:

Screen Shot 2021-06-16 at 9 40 07 AM

- Create a people block and use the person type and person type status filters to person list block and verify that they aren't broken.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulled this, and it looks like it resolves #3657 as well (haven't dived into what changes have been made or might still need to be made, but in its current state the collections form works like a charm with it).

**Comment by bspeare** [comment]
@cory-skeers any thoughts on how we should fix this part?   This is the line that was causing the form problems: https://github.com/uiowa/uiowa/pull/3658/commits/7aadae53fc46c93e34707132bc1960f478909e4e#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4cL147.

**Comment by bspeare** [comment]
Here's the commit where that check was added: https://github.com/uiowa/uiowa/pull/3587/commits/2b3f45603e823ef06e5ad132c8cd5dd3b58e791b.

**Comment by cory-skeers** [comment]
> @cory-skeers any thoughts on how we should fix this part? This is the line that was causing the form problems: [7aadae5#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4cL147](https://github.com/uiowa/uiowa/commit/7aadae53fc46c93e34707132bc1960f478909e4e#diff-22455fd1cfa159b58a0289784a91064192c27738f06b23e252be3a46271afb4cL147).

It looks like for collections, at least, it has the `$form['settings']` but is failing because it doesn't have a `$form['settings']['override']` set. Can we just change it to `if (isset($form['settings'])) {`, or do we need to check for `override` for other blocks?

**Comment by cory-skeers** [comment]
@bspeare I'm thinking at least as a hotfix, take the `isset($form['settings']['override'])` check out for now--we may need to add it in later for specific blocks, or check for something else, but as a hotfix, it should get things functional again without explicitly breaking the people block if that gets handled in `sitenow_people`. I think that's the main block that has/needs an `override` key.

Edit: And after, maybe we can get @pyrello's input on the change, and help with accomplishing what that commit had originally intended.

**Comment by GaryRidgway** [comment]
pulling to test!

**Comment by GaryRidgway** [comment]
All of this is working well! I did notice that while I was checking if the filters on the `people list` block that if I checked `faculty` on a person as a `person type`, that `former faculty` did not show up. I had to save the node and re-edit the person to then find a new checkbox field titled `former faculty`. is this something we should deal with here? or make a separate issue?

**Comment by bspeare** [comment]
@GaryRidgway I noticed the same thing and tested it on prod and had the same result.   I'm not sure if that is the intended functionality - @cory-skeers @richardbporter @mark-bennett-uiowa are you familiar with those checkboxes?

**Comment by briand44** [comment]
>I noticed the same thing and tested it on prod and had the same result.

Then I would create a separate issue if it is not desired functionality and not deal with it here.

**Review by GaryRidgway — APPROVED** [review]
Works for everything listed!

**Comment by cory-skeers** [comment]
> I did notice that while I was checking if the filters on the `people list` block that if I checked `faculty` on a person as a `person type`, that `former faculty` did not show up. I had to save the node and re-edit the person to then find a new checkbox field titled `former faculty`. is this something we should deal with here? or make a separate issue?

This is when making a new person, right? Not the people list block filters? That should be separate from this, but also not the intended functionality...

**Comment by GaryRidgway** [comment]
it was during the editing of a person, not on the filters, just thought I would surface it!

**Pull request merged**
