### PR TITLE
Feature: Academic groups

### LINKED ISSUE #3110: Academic Groups for areas of study
# Story

As an admissions site owner, I want to have academic groups so that users can optionally navigate areas of study by first choosing the academic group they are interested in.

# Additional Info
* Taxonomy or similar functionality to create list of academic groups.
* Each academic group should be able to have a title, photo, description and video.
* Ability to reference multiple groups from an individual area of study.
* Full academic group page should have all the above mentioned fields as well as teasers for each area of study that has referenced the specific group, with link to those areas of study (https://admissions.uiowa.edu/academics/biz-econ-mgmt).
* Have ability to filter by these groups on future Areas of study search page (https://admissions.prod.drupal.uiowa.edu/academics/undergraduate-areas-of-study)
* These referenced group(s) do not need to be output on an area of study entity.
* Must be in the correct form order: https://github.com/uiowa/uiowa/issues/3108

# Proposed solution

### LINKED ISSUE #3130: Create "Create your own path" page for Admissions
# Story

As a prospective student I can view a list of academic groups as a starting point to exploring things I might study. Follow up to #3110 

# Proposed solution

Create a view to list terms in the Academic Groups vocabulary similar to https://admissions.uiowa.edu/academics/groups.

### PR DESCRIPTION
**Pull request by bspeare**
This resolves https://github.com/uiowa/uiowa/issues/3110 and resolves https://github.com/uiowa/uiowa/issues/3130. 

This pr does not contain "Have ability to filter by these groups on future Areas of study search page", that should be addressed in https://github.com/uiowa/uiowa/issues/3203. 

# How to test

- `blt ds --site=admissions.uiowa.edu`
- `yarn workspace uids_base gulp --development`
- `drush @admissions.local uli`
- Add a "Business, Economics, and Management" taxonomy term to "Academic Groups" at: http://admissions.local.drupal.uiowa.edu/admin/structure/taxonomy/manage/academic_groups/add and add Name, Description, Add an image, and a Video. 
<details>Screen Shot 2021-03-08 at 11 20 44 AM</details>

- Add a reference to "Business, Economics, and Management" on an Area of Study page: http://admissions.local.drupal.uiowa.edu/node/1021/edit?destination=/admin/content and verify that the page is referenced at the bottom of http://admissions.local.drupal.uiowa.edu/academic-groups/business-economics-and-management in a 3 column card grid. 
- Go to https://admissions.local.drupal.uiowa.edu/academics/groups and place the "Academic Groups Block" onto the layout builder page and verify that it renders as a three column card grid:

<details>Screen Shot 2021-03-08 at 11 21 04 AM</details>

- Masquerade as a `webmaster`, `editor`, or `publisher` and verify that you can edit the Academic Groups taxonomy.

### CODE REVIEW

**Comment by richardbporter** [comment]
Making a note there that it might make sense to tackle https://github.com/uiowa/uiowa/issues/3130 as part of this.

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Can the taxonomy form be reordered to not show up after the save button? Missed it the first time. Not up-to-date with fielding taxonomies in D9.

Also the block says a default is to display 5 when it it is a grid of three. Should this be changed to 3, 6 or 9?

**Comment by bspeare** [comment]
@joewhitsitt great points, thanks!

**Pull request merged**
