### PR TITLE
Admissions - 2 Plus 2 Major content type with Community Colleges term display

### LINKED ISSUE #5003: Create structure to capture checkpoints specific to a community college and major.
As a 2plus2 transfer student, I would like to be able to see what specific checkpoints and courses I need to complete at my community college to meet the University of Iowa requirements for that major.

# Additional Information
Here are examples of the requirements needed for an American Studies major through Eastern Iowa Community College compared to an American Studies major through Des Moines Area Community College.

https://2plus2.admissions.uiowa.edu/majors/eastern/american-studies.html
https://2plus2.admissions.uiowa.edu/majors/dmacc/american-studies.htm

The majority of information appears to be static with the exception of the community college checkpoints and University checkpoints.

This content will need to reference a community college and an area of study?

Here is a link provided by Admissions to some info about the fields needed here https://iowa-my.sharepoint.com/:w:/g/personal/katmills_uiowa_edu/EaQbdfwQQIJDgKED1dvJ7jQB143-R7ErxZPSZ8B019J6gA?e=j1aece. Provided 3/30/22

# Proposed Solution

### LINKED ISSUE #5132: Separate taxonomy term view
With Community colleges as a taxonomy vocabulary, 2plus2 majors content are automatically being pulled in due to the default taxonomy term view. Currently it is un-styled, at the bottom and probably by modified date instead of title. 

## Proposed Solution

- [x] Create a separate view of 2plus2 majors contextually filtered based on taxonomy on node displaying all as teasers in alphabetical order.
- [x] Create a teaser template for 2plus2 majors to render similar to basic page teasers with title only for now.
- [x] Similar to Colleges, use TVI to override and replace the default taxonomy term view display with the new view OR override the community colleges template to remove the taxonomy term view and consider an pseudo extra field to display the new view within the content where desired.

## For reference:

https://2plus2.admissions.uiowa.edu/majors/iowa-valley.htm

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves #5003 
Resolves https://github.com/uiowa/uiowa/issues/5132

As a 2plus2 transfer student, I would like to be able to see what specific checkpoints and courses I need to complete at my community college to meet the University of Iowa requirements for that major.

As a 2plus2 transfer student, I can see all 2plus2 majors within a participating community college.

# How to test

- `ddev blt ds --site=admissions.uiowa.edu`
- `ddev drush @admissions.local uli`
- As a webmaster a term for the community college taxonomy so you'll have a college to reference. Go on, fill it out with some content.
- As a webmaster add at least Major (2 Plus 2) piece of content. Fill out all of the main fields. Save.
- Check that the title of the content is '(chosen area of study) Major Through (chosen community college)'.
- Also check that the community college checkpoints field displays as '(chosen community college) checkpoints'.
- Notice the breadcrumb links to the community college you selected. Navigate there and see the related AoS titles show within the taxonomy term fielded content with a contextually aware heading that includes the term name. If there is more than one 2plus2 major referencing the community college, it should show in alphabetical order.
- See if you can break anything.

### CODE REVIEW

**Comment by e-marie-w** [comment]
There was interest in seeing the Area of Study link as a button, but now I'm wondering if it's too much, since there's a normal link just a few lines below. Would it be better to have no styles or both links styled instead? 

current_major

Hoping @bspeare will have some ideas.

**Comment by bspeare** [comment]
@e-marie-w you could try `bttn bttn--outline bttn--tertiary bttn--sans-serif` which is not as heavy.   It's worth adding the button.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
I think this looks good. I looked at the template. By changing the label for the field to visually hidden and processing in a bg--white class to a parent div I was _almost_ able to get the embed field template to work. It still had letter spacing, etc. to overcome. Instead, I just cleaned up the template a bit to add natural spacing through a paragraph tag instead of a horizontal rule and removed the for loop and just targeted the required first instance.

**Comment by joewhitsitt** [comment]
I mentioned this to @e-marie-w earlier, but I wonder if this also should wait for customer approval before merge and because of that, should we keep going in this PR with https://github.com/uiowa/uiowa/issues/5132?

Thoughts @briand44 ?

**Comment by briand44** [comment]
If we think we should get customer approval before merging, I think we should add #5132 to this PR so we are not waiting another week to move forward. Not sure if we need customer approval before merging though. If someone wants to demo what is all in this PR I could try to weigh in more on that?

**Comment by joewhitsitt** [comment]
Now that Admissions is live, I am more hesitant in merging in stuff without their thumbs up. It is establishing a new content type that references both AoS and Community Colleges.

**Comment by joewhitsitt** [comment]
I think this is available for technical review again. Instructions have been updated. Leaving in draft until customer reviews it.

**Comment by joewhitsitt** [comment]
Visual summary of changes:

Screen Shot 2022-04-21 at 4 18 50 PM
Screen Shot 2022-04-21 at 4 19 33 PM

**Comment by joewhitsitt** [comment]
Trying to merge into DEV for customer review while respecting existing stuff 😬

**Comment by joewhitsitt** [comment]
Deployed to DEV after fixing and remerging https://github.com/uiowa/uiowa/pull/4643. Reached out to Scott in Slack.

**Comment by joewhitsitt** [comment]
Admissions would like some changes, but we don't want this PR to block further work elsewhere. Looking for technical approval for what we have now so we can merge and start a fresh branch

**Review by cory-skeers — APPROVED** [review]
Pulled and tested--everything looked good, and I wasn't able to break anything.

Further work/improvements can be continued in followup PRs 👍

**Pull request merged**
