### PR TITLE
Fixed headline display for image gallery block

### LINKED ISSUE #2419: Fix/add headline styling for image gallery block
Either fix or add headline styling for the image gallery block to display it above block instead of next to it. Looks especially wonky when the bold, highlighted styling is selected
image

With `flex basis: 100%` 

image

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2419 

# How to test
1. install default site (blt drupal:install --site=default)
2. Run `blt frontend`
3. Add an image gallery block with a headline and choose the bold, highlighted styling option
4. Inspect the HTML of the image gallery element on the page that is opened up and observe that the headline element is rendered outside the image gallery block. Make sure displays correctly.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I think https://github.com/uiowa/uiowa/pull/2494 should be the approach here. scope increased to make sure all blocks are covered.

**Comment by dnkemper** [comment]
@joewhitsitt so leave it like this?
image

**Comment by dnkemper** [comment]
@joewhitsitt oh gosh... I misread that completely haha

**Review by joewhitsitt — APPROVED** [review]
This works. Thanks for adjusting the method.

**Comment by dnkemper** [comment]
@joewhitsitt thank you for pointing me to it and for testing it!

**Pull request merged**
