### PR TITLE
Updated Classroom content type with basic fields

### PR DESCRIPTION
**Pull request by pyrello**
Related issue #5769 

# How to test
Setup one-liner:
```
ddev blt ds --site classrooms.uiowa.edu && ddev drush @classrooms.local uli
```
- `ddev blt ds --site classrooms.uiowa.edu`
- `ddev drush @classrooms.local uli`

Test that the content type meets the criteria described in https://wiki.uiowa.edu/pages/viewpage.action?spaceKey=drupaldev&title=Content+type+creation+notes

Test that these fields work as expected:

- Featured Image
- Image gallery
- Seating Chart 
- Video
- Map 

Double check that the fields here match the fields described in the "Fields" section on https://github.com/uiowa/uiowa/issues/5769.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by cory-skeers** [comment]
Is there a specific URL pattern that's been discussed? I don't recall any...

Current site is `/building_abbreviation-room_number`, and new setup uses `/building_name-room_number` based on the title, so different but perhaps a more descriptive.

**Comment by cory-skeers** [comment]
I think in the future we can map the `containsPlace` and `containedInPlace` schemas for buildings and rooms, but that it'll need to come as a future slice of fully linking things together as content types get completed.

Other than double-checking that the PathAlias pattern doesn't need updating, I think this is ready to go.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested 💯

**Comment by bspeare** [comment]
Thanks @cory-skeers! I think we are fine with the pattern but we may need to create redirects though when we migrate the content over.

**Pull request merged**
