### PR TITLE
[Commencement] Venue theming updates

### LINKED ISSUE #7877: Venue theme changes
https://commencement.prod.drupal.uiowa.edu/venue/hancher-auditorium

>We're wondering if we could reduce the margins between the sections a little bit? Especially between the first "ceremony info" section and the first collection header? Just seems like quite a bit of blank space.

>For the collection section titles/headers we're wondering if those could also be the underline style? I don’t know if it’s possible/easier to hide those titles but we could use the headers/style options in the text editor instead?

image

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #7877 

# How to test

```
ddev blt ds --site commencement.uiowa.edu
```
- Review https://commencement.uiowa.ddev.site/venue/hancher-auditorium, #7877, and https://commencement.prod.drupal.uiowa.edu/venue/hancher-auditorium to confirm that the visual changes fulfill what was requested.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
Checks out. Loses some of the hierarchal visual effect though. Noticed that they don't have the anchors setup for this page but that is a content issue right?

**Comment by pyrello** [comment]
> Loses some of the hierarchal visual effect though.

What visual effects are lost?

**Comment by bspeare** [comment]
When we use the `headline--underline` modifier class on a field it creates more space between the underline and the heading.   Ideally, we would unset the field classes on this `headline headline--serif headline--underline h3 field field--name-field-coll-section-title field--type-string field--label-hidden field__item` to accurately reflect the spacing used on all `headline--underline` headings.

Screenshot 2024-07-03 at 10 58 37 AM

**Comment by joewhitsitt** [comment]
> > Loses some of the hierarchal visual effect though.
> 
> What visual effects are lost?

Just that before it looked more different between the h2 and h3. Now it just looks like a couple of pixels worth of spacing.

**Comment by pyrello** [comment]
> When we use the `headline--underline` modifier class on a field it creates more space between the underline and the heading. Ideally, we would unset the field classes on this `headline headline--serif headline--underline h3 field field--name-field-coll-section-title field--type-string field--label-hidden field__item` to accurately reflect the spacing used on all `headline--underline` headings.
> 
> Screenshot 2024-07-03 at 10 58 37 AM

As far as I can tell, we don't have access to any of the `field` or `field-*` classes during preprocess. These classes get added in the template (in this case its the generic `field.html.twig` template). This means that to "remove" them, we'll need an overriding template for this field. Longer term, we should probably just fix the `field` classes so that they play nicely with the `headline` classes so we don't need to add extra template to unset them. Not sure how much work that is. Going to pause for additional feedback.

**Comment by pyrello** [comment]
It doesn't look like the change in https://github.com/uiowa/uiowa/pull/7878/commits/a3fa1de2b4ff6a1931d6b320ff809b7cd407f647 made any difference that I could see with regard to the spacing for the h3's. There is still more space between the h3's and their underline than the h2 and its underline.

**Comment by pyrello** [comment]
@bspeare confirmed that my change fixed the issue we were seeing before.

**Pull request merged**
