### PR TITLE
[Bug] Bug fix for template, views, and css for ITS services view

### LINKED ISSUE #7159: ITS services view bugs
# Problems

1. Twig template error
```
php-error web-33201 [01-Dec-2023 09:04:15 America/Chicago] Uncaught PHP Exception Twig\Error\SyntaxError: "Unexpected token "name" of value "if" ("end of statement block" expected)." at /mnt/www/html/uiowa03/docroot/sites/its.uiowa.edu/modules/its_core/templates/views-view-summary-unformatted--services.html.twig line 22 request_id="v-e4a61d4a-905a-11ee-8b2a-4f6dba3cbb4f"
```
2. View shows duplicate headings if title is lowercase.  Such as two headings for "E" for eFax and "E" for Encryption

# Steps to reproduce
Go to https://its.prod.drupal.uiowa.edu/services. 

# Proposed solution
Update template and views grouping rewrite

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7159

# How to test

1. Test services page and services block
2. Test with "eFax" and "Encryption" service names
3. Test with "3D Printing and Machining" example
4. Test that top jump menu is rendered correctly
5. Test uiowa and claspolicy and confirm no visual regressions

```
ddev blt frontend && ddev blt ds --site=its.uiowa.edu && ddev drush @its.local uli /services
```
```
ddev blt frontend && ddev blt ds --site=uiowa.edu && ddev drush @home.local uli /a-z
```
```
ddev blt frontend && ddev blt ds --site=policy.clas.uiowa.edu && ddev drush @claspolicy.local uli /a-z
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Assuming this is up for review, I'll pull down and take a look

**Comment by joewhitsitt** [comment]
@bspeare, i am noticing a slight style regression here with active and hover (the grey doesn't fill the outer box):

Screenshot 2023-12-06 at 3 58 35 PM

**Comment by bspeare** [comment]
@joewhitsitt great eyes! I will fix that.

**Review by joewhitsitt — APPROVED** [review]
Thanks for the quick adjustment. That and everything else looks good.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
