### PR TITLE
Patch for node_revision_delete and content update for default_content

### LINKED ISSUE #4849: As a site owner, I can use the default home page install as a starting point for my site design instead of a showcase of components
# Story

As a site owner, I can use the default home page install as a starting point for my site design instead of a showcase of components.

# Problem 
- The current installed home page (https://default.dev.drupal.uiowa.edu/) is a kitchen sink of component and text areas. 
- Customers cannot use the "Featured image" field since the template does not allow it. 

# Proposed solution
- [x] Initial slice: Design for new default home page on the Sandbox site.
- [x] Add two more default articles to the site install
- [x] Move current home page install to a new page so we can still track changes with Percy - call the page "Components Showcase"?
- [x] Convert https://sandbox.prod.drupal.uiowa.edu/homepage-example-4 into default content.

### LINKED ISSUE #4977: Node Revision Delete no longer works with core 9.3
# Problem
```
Error: Object of class Drupal\node\Entity\Node could not be converted to string in Drupal\Core\Entity\EntityStorageBase->buildCacheId() and Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple()
```

# Steps to reproduce
- Try deleting a revision through the UI while looking at teh logs

# Proposed solution
- [ ] See if latest patch works: https://www.drupal.org/project/node_revision_delete/issues/3249493

### PR DESCRIPTION
**Pull request by makurj**
# How to test

1. composer install
2. blt ds --site=default.uiowa.edu
3. Try deleting an older revision of a page.
4. You should be able to delete 1 and all older revisions.

For the default content: 
1. Install a fresh default or sandbox site with blt drupal:install --site default or blt drupal:install --site sandbox.uiowa.edu.
2. Do you get the new homepage? See https://github.com/uiowa/uiowa/issues/4849#issuecomment-1080811154
3. Do you see the "Component Showcase" page in the main menu? It should look like the old default homepage. This was done to preserve the old homepage.

General editorial check/comparison between https://sandbox.prod.drupal.uiowa.edu/homepage-example-4 and the new homepage.

Will also address #4849 and #4977

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Seeing as this is the `default-content` branch, should this stay as a draft and wait until the updated default content is part of this?

**Comment by joewhitsitt** [comment]
After a quick install/glance things seem to be in place now. I can do a closer content comparison tomorrow.

**Comment by joewhitsitt** [comment]
Makur is swapping out an image per Michael's request

**Comment by joewhitsitt** [comment]
I think something happened between replicate and exporting default content... Hopefully it can be fixed on Makur's machine.

**Comment by joewhitsitt** [comment]
Getting `You are not allowed to edit or remove this Paragraph.`

**Comment by joewhitsitt** [comment]
Will want @bspeare to approve the Percy build once everything else has been approved.

**Comment by richardbporter** [comment]
> Will want @bspeare to approve the Percy build once everything else has been approved.

I think the Percy snapshot config will need to be updated as part of this. Looks like URLs have changed maybe?

https://github.com/uiowa/uiowa/blob/4eb313fea4912aaf94cafbd0552d444251a757fc/snapshots.yml#L1-L14

**Comment by bspeare** [comment]
I think we need to update our Percy configuration to watch the new page names.

**Comment by GaryRidgway** [comment]
Immediately as I tried deleting a revision I got this error:
<details>
<summary>Click here for error</summary>

`The website encountered an unexpected error. Please try again later.
Error: Object of class Drupal\node\Entity\Node could not be converted to string in Drupal\Core\Entity\EntityStorageBase->buildCacheId() (line 176 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
Drupal\Core\Entity\EntityStorageBase->buildCacheId(Object) (Line: 216)
Drupal\Core\Entity\EntityStorageBase->getFromStaticCache(Array) (Line: 316)
Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array) (Line: 296)
Drupal\Core\Entity\EntityStorageBase->load(Object) (Line: 247)
Drupal\node_revision_delete\NodeRevisionDelete->getPreviousRevisions(Object, Object) (Line: 195)
node_revision_delete_form_node_revision_delete_confirm_alter(Array, Object, 'node_revision_delete_confirm') (Line: 539)
Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'node_revision_delete_confirm') (Line: 835)
Drupal\Core\Form\FormBuilder->prepareForm('node_revision_delete_confirm', Array, Object) (Line: 279)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`
</details>

**Review by richardbporter — CHANGES_REQUESTED** [review]
I can work to update the Percy snapshot URLs if nobody else has started.

**Comment by makurj** [comment]
@GaryRidgway `drush @default.local cr`? Also cron?

**Comment by GaryRidgway** [comment]
> @GaryRidgway `drush @default.local cr`? Also cron?

seemed to work after syncing the database a third time and clearing the cache

**Comment by joewhitsitt** [comment]
the test instructions didn't have `composer install` which are necessary for node revision delete and the slider issue. there was an update for existing patch as well

**Comment by GaryRidgway** [comment]
> 2. Do you get the new homepage? See https://github.com/uiowa/uiowa/issues/4849#issuecomment-1080811154 
> 3. Do you get Component Showcase in the main menu? It's the old homepage.

This was confusing me forever, I thought that if I saw the Component showcase in the menu that I had erroneously gotten the old homepage. I am actually getting the new homepage it seems, so that is good!

**Comment by makurj** [comment]
> > 3. Do you get Component Showcase in the main menu? It's the old homepage.
> 
> This was confusing me forever, I thought that if I saw the Component showcase in the menu that I had erroneously gotten the old homepage. I am actually getting the new homepage it seems, so that is good!

I'm glad you figured it out. I can update the instructions.

**Review by richardbporter — APPROVED** [review]

**Review by GaryRidgway — APPROVED** [review]
I checked all the things listed in the #To test instructions and they all seemed good!

**Pull request merged**
