### PR TITLE
Initialize strategicplan.clas.uiowa.edu multisite on uiowa01

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Provisioning a new Strategic Plan site for CLAS. Smaller site similar to strategicplan.uiowa.edu. Would appreciate this getting merged and released quickly if possible; sorry for the lack of advanced notice.

### CODE REVIEW

**Review by pyrello — APPROVED** [review]
Reviewed

**Comment by mark-bennett-uiowa** [comment]
@richardbporter @pyrello Any idea why Im getitng these conflicts when Sean's provision PR went through successfully? Is this because we did two different provision PRs at the same time?

**Comment by mark-bennett-uiowa** [comment]
It looks like box/config.yml is missing two lines for the strategicplan.clas.uiowa.edu site:
```
    documentroot: '{{ drupal_core_path }}'
    extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
```

**Comment by pyrello** [comment]
This is the first time I have seen this.

**Comment by richardbporter** [comment]
Yea thats weird. You could resolve it manually or run it again on a fresh feature branch created off the latest main.

**Comment by pyrello** [comment]
Sorry if I messed you up!

**Pull request merged**
