### PR TITLE
D7 comms report command

### PR DESCRIPTION
**Pull request by pyrello**
Related to #7156 

# How to test

This was already used to develop the initial list of emails/websites that we used in #7156. I think code review is sufficient.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I told Sean I'd take a look at this, particularly the issue where some emails aren't returned. pulling down

**Comment by pyrello** [comment]
We'll be using this again for #7248

**Comment by joewhitsitt** [comment]
Did we want to include any safeguard from running this on a remote instead of locally?

**Comment by pyrello** [comment]
> Did we want to include any safeguard from running this on a remote instead of locally?

We didn't previously, but I can add something.

**Comment by pyrello** [comment]
> > Did we want to include any safeguard from running this on a remote instead of locally?
> 
> We didn't previously, but I can add something.

I thought I would find an example of this, but it seems like we don't actually implement this type of guard with most of our BLT commands. If you have an example, please surface it!

**Comment by joewhitsitt** [comment]
My concern is the CSV export. I think only this ReportCommands has them and I didn't think of this before when we first shipped it out. I don't have an example to surface, but I wonder `isDDev()` from blt/src/Blt/Plugin/Commands/ValidateCommands.php or `$env = EnvironmentDetector::getAhEnv() ?: 'local';` would be enough to prevent a CSV from being saved on one of the remotes in a directory where it shouldn't be.

**Comment by pyrello** [comment]
> My concern is the CSV export. I think only this ReportCommands has them and I didn't think of this before when we first shipped it out. I don't have an example to surface, but I wonder `isDDev()` from blt/src/Blt/Plugin/Commands/ValidateCommands.php or `$env = EnvironmentDetector::getAhEnv() ?: 'local';` would be enough to prevent a CSV from being saved on one of the remotes in a directory where it shouldn't be.

I'm not sure about this, but I don't think permissions would allow a file to be written in the project root on prod. I can look into adding this.

**Comment by GaryRidgway** [comment]
Would someone be able to review this code for me? I think it works but I need someone else to try it remotely and see if it terminates before trying to create the CSV. (Reason: My ddev is giving me grief.)

**Comment by joewhitsitt** [comment]
Sorry, my thought from https://github.com/uiowa/uiowa/pull/7220#issuecomment-1883199328 is that we just don't want to export a csv to a remote environment, not prevent the command from running at all. 

https://github.com/uiowa/uiowa/pull/7220/files#diff-e58379d737967dfd847c0da29f5198c12e242c198a048fe22c46c9ea35bf93e7R417

**Comment by joewhitsitt** [comment]
in picking up https://github.com/uiowa/uiowa/issues/7248, I am pulling this down and will try to articulate my thought process from https://github.com/uiowa/uiowa/pull/7220#issuecomment-1898984856

**Review by joewhitsitt — APPROVED** [review]
My original concerns has been addressed. Previously reviewed and have been using this command locally. I approve, but since I was the last to touch, another thumbs up would be neat.

**Pull request merged**
