### PR TITLE
P2LB updates for Staff Council site

### PR DESCRIPTION
**Pull request by pyrello**
# What's in it?
- Updates P2LB node processing to handle the case where a menu block is showing in the V2 version
- Adds a condition to the node analyzer to display a message in the case where we are showing a menu since it is a high likelihood that it will change the previous design.
- Refactors P2LB to use a class to handle conversions to allow more flexibility in how the page and sections are processed.
- Adds edge case handling for cards where the user has included a single link with a `bttn` class to extract that link for use as a card link to cover more cases where cards might have been turned into text areas.
- Fixed permissions and EVD options as outlined in https://github.com/uiowa/uiowa/pull/6775#issuecomment-1686974091.
- Fixed issue where the V3 Status tab would report a page as not being converted if the new revision was not published.

# How to test
```
ddev blt sync --site staff-council.uiowa.edu && ddev drush @staff-council.local config-split:activate p2lb -y && ddev drush @staff-council.local uli admin/content/sitenow-converter
```
- Staff council prod site for reference: https://staff-council.uiowa.edu/

## Menu block
- https://staff-council.uiowa.ddev.site/node/26/conversion-status
- Observe the message about how the page might look different because of the menu
- Convert the "Committees" page
- https://staff-council.uiowa.ddev.site/node/26/conversion-status
- Confirm that V3 Status tab reports that the page has been converted
- https://staff-council.uiowa.ddev.site/node/26/latest
- Please note the menu block does not display for revisions
- Publish the page and compare the result with https://staff-council.uiowa.edu/about-staff-council/committees
- Confirm that menu block displays showing children of the current page

## Refined card logic
- https://staff-council.uiowa.ddev.site/node/1/conversion-status
- Observe that each message related to cards only indicates one card will be transitioned to a text area
- Convert the "Home" page
- https://staff-council.uiowa.ddev.site/node/1/latest
- Observe that the 3 V2 cards in a row under the banner + text area are converted to V3 cards

## Misc
- As a webmaster, I can view the Layout tab for pages
- As a webmaster, when I click "Add component" and then "More", I am shown the same list of blocks as in a V3 site
- Convert all remaining pages
- Observe that there are no error messages

```
ddev blt sync --site sandbox.uiowa.edu && ddev drush @sandbox.local uli
```
- Confirm that changes to default page EVD have not affected the page layout: https://sandbox.uiowa.ddev.site/admin/structure/types/manage/page/display/default/layout

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Wondering if I am missing a step. Included `ddev drush @staff-council.local config-split:activate p2lb`, see the conversion stuff, but get the following on triggering:

```
Error: Class "Drupal\sitenow_p2lb\P2LbConversionManager" not found in Drupal\Component\DependencyInjection\Container->createService() (line 259 of core/lib/Drupal/Component/DependencyInjection/Container.php).
Drupal\Component\DependencyInjection\Container->createService(Array, 'sitenow_p2lb.conversion_manager') (Line: 177)
Drupal\Component\DependencyInjection\Container->get('sitenow_p2lb.conversion_manager') (Line: 207)
Drupal::service('sitenow_p2lb.conversion_manager') (Line: 37)
Drupal\sitenow_p2lb\Plugin\Action\ConvertParagraphsToLayoutBuilder->execute(Object) (Line: 22)
```

**Comment by joewhitsitt** [comment]
Is is it supposed to be `P2LbConverterManager` instead of `P2LbConversionManager`?

Update: I made these changes locally and it seems to work.

```
git diff
diff --git a/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.services.yml b/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.services.yml
index 2ca7e33a3..022fc30c4 100644
--- a/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.services.yml
+++ b/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.services.yml
@@ -2,5 +2,5 @@ services:
   logger.channel.sitenow_p2lb:
     parent: logger.channel_base
     arguments: ['sitenow_p2lb']
-  sitenow_p2lb.conversion_manager:
-    class: Drupal\sitenow_p2lb\P2LbConversionManager
+  sitenow_p2lb.converter_manager:
+    class: Drupal\sitenow_p2lb\P2LbConverterManager
diff --git a/docroot/modules/custom/sitenow_p2lb/src/Form/P2LbSettingsForm.php b/docroot/modules/custom/sitenow_p2lb/src/Form/P2LbSettingsForm.php
index a28b6e4a7..078a37718 100755
--- a/docroot/modules/custom/sitenow_p2lb/src/Form/P2LbSettingsForm.php
+++ b/docroot/modules/custom/sitenow_p2lb/src/Form/P2LbSettingsForm.php
@@ -31,7 +31,7 @@ class P2LbSettingsForm extends ConfigFormBase {
   protected EntityTypeManagerInterface $entityTypeManager;
 
   /**
-   * The sitenow_p2lb.conversion_manager service.
+   * The sitenow_p2lb.converter_manager service.
    *
    * @var \Drupal\sitenow_p2lb\P2LbConverterManagerInterface
    */
@@ -64,7 +64,7 @@ public static function create(ContainerInterface $container) {
       $container->get('config.factory'),
       $container->get('config.storage'),
       $container->get('entity_type.manager'),
-      $container->get('sitenow_p2lb.conversion_manager'),
+      $container->get('sitenow_p2lb.converter_manager'),
     );
   }
 
diff --git a/docroot/modules/custom/sitenow_p2lb/src/Plugin/Action/ConvertParagraphsToLayoutBuilder.php b/docroot/modules/custom/sitenow_p2lb/src/Plugin/Action/ConvertParagraphsToLayoutBuilder.php
index b97bee623..933e75f3a 100644
--- a/docroot/modules/custom/sitenow_p2lb/src/Plugin/Action/ConvertParagraphsToLayoutBuilder.php
+++ b/docroot/modules/custom/sitenow_p2lb/src/Plugin/Action/ConvertParagraphsToLayoutBuilder.php
@@ -34,7 +34,7 @@ public function access($object, AccountInterface $account = NULL, $return_as_obj
    */
   public function execute(ContentEntityInterface $entity = NULL) {
     /** @var \Drupal\sitenow_p2lb\P2LbConverter $converter */
-    $converter = \Drupal::service('sitenow_p2lb.conversion_manager')->createConverter($entity);
+    $converter = \Drupal::service('sitenow_p2lb.converter_manager')->createConverter($entity);
 
     $converter->convert();
   }
```

**Comment by joewhitsitt** [comment]
>Please note the menu block does not display for revisions

Should we note that as part of the conversion report message to help get folks up to speed with v3?

**Comment by joewhitsitt** [comment]
The resources page on staff-council says 8 cards will be converted to text areas but are actually converted to cards. Does the report code need to be updated based on being able to bring more cards over as cards?

**Comment by joewhitsitt** [comment]
I think something got messed up in the EVD default page

Screenshot 2023-08-24 at 11 59 36 AM

Screenshot 2023-08-24 at 12 01 06 PM

**Comment by pyrello** [comment]
Setting back to "draft" while I look into the issues that @joewhitsitt raised.

**Comment by pyrello** [comment]
> Is is it supposed to be `P2LbConverterManager` instead of `P2LbConversionManager`?

@joewhitsitt It seems like maybe the code you were testing was out of date for some reason? I have gone back and forth on the `converter` versus `conversion` nomenclature and settled on `converter`. I'm not seeing any instances of `conversion_manager` in the code anymore.

**Comment by pyrello** [comment]
> Wondering if I am missing a step. Included `ddev drush @staff-council.local config-split:activate p2lb`, see the conversion stuff, but get the following on triggering

Thanks for this. I updated the testing instructions. I think the rest of your comment is related to code being out of sync with the most recent version.

**Comment by pyrello** [comment]
> The resources page on staff-council says 8 cards will be converted to text areas but are actually converted to cards. Does the report code need to be updated based on being able to bring more cards over as cards?

I was comparing the wrong format in the analyzer 🤦

**Comment by pyrello** [comment]
Okay. I think this is ready for review again.

**Comment by joewhitsitt** [comment]
pulling again

**Review by joewhitsitt — APPROVED** [review]
the referenced issues have been fixed and everything else seems to check out. got lost in the code moves but the results seem to be the same.

**Pull request merged**
