### PR TITLE
Create sitenow:multisite:delete command.

### LINKED ISSUE #551: Deprovision rdmevents.sites.uiowa.edu
D8 Deprovision

### LINKED ISSUE #556: Automate and document D8 deprovision process

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #551 
Resolves #556 

Opted not to automate files deletion since we don't have readily available backups of those.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Is there a deprovision site to test with? Where are you on: https://github.com/uiowa/uiowa/issues/551

**Comment by richardbporter** [comment]
I used that as a test. Its gone.

**Comment by joewhitsitt** [comment]
Task is still open...

**Comment by richardbporter** [comment]
This PR will close it...

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
