### PR TITLE
Vertical remote video

### LINKED ISSUE #6243: Add vertical display option for SiteNow service video embeds
# Story

As a site owner, I can display video content from YouTube shorts. 

# Proposed solution
-  Add a “Vertical” display option in addition to “Large, Medium, Small” for embedded videos. 

<details>
Currently the vertical video block on uiowa.edu is a manual process of uploading local files:
- Manual .vtt file upload and subtitle positioning
- Manual file upload
- Manual poster image upload
- Works with H264 encoding only

# Proposed solution

- Update the vertical video block to use youtube short video links
  - Requirements
    - Needs to still work with our custom play/pause button
    - Needs to not display recommended ads/videos at the end of the video
</details>

Here are links to the YouTube shorts versions of the homepage videos.

- https://youtube.com/shorts/GAdS3JW3KSM
- https://youtube.com/shorts/ofQsz0O_CTg
- https://youtube.com/shorts/QOqQOgV8juc

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6243

# How to test

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /media-vertical-vimeo-and-youtube
```

1. Adjust videos to use the `vertical` orientation and preview in layout builder and save. 
2. Adjust the same videos in the /node/edit section and preview and save

Known issues:
- `Default` Vimeo preview was previously broken, it is not fixed but still wonky - compare against https://sandbox.prod.drupal.uiowa.edu/node/486/layout
- Vertical crop works on normal youtube and vertical youtube videos 
- Vertical crop only works on portrait style Vimeo videos - https://help.vimeo.com/hc/en-us/articles/12426488754449-How-do-I-change-my-video-s-aspect-ratio-in-the-editor

### CODE REVIEW

**Comment by GaryRidgway** [comment]
~Pulling to test~

I will review this when planned is done!

**Comment by joewhitsitt** [comment]
pulling to test and write some draft documentation

**Review by joewhitsitt — APPROVED** [review]
Looks good. No matter what though, my brain thinks that vertical is spelled wrong. 😜

**Comment by pyrello** [comment]
Looks like I forgot to assign myself to this, but I was also testing this. Seems like it functions as expected, but I'm wondering about S, M, L vs Vertical. I'm not sure how to parse the size versus orientation/shape choice. And I'd like to make sure we think this through since whatever we choose is likely to be with us for a long time.

**Comment by pyrello** [comment]
Marking as draft since I think we'll be making changes to it.

**Comment by joewhitsitt** [comment]
Screenshot 2024-05-24 at 9 53 53 AM

Also updated the doc https://sitenow.uiowa.edu/node/176/latest

**Comment by joewhitsitt** [comment]
Tested the container query this morning and it is a nice safeguard I think.

Based on the discussion over at https://github.com/uiowa/uiowa/issues/6243, we are dialing back the slice here. Modifying CKEditor5 plugins is just not worth the squeeze for these customizations. Hope to prioritize https://github.com/uiowa/uiowa/issues/7195 in the near future to bring more clarity to our media sizing functionality.

I stand by my earlier approval but have opened it up for others.

**Review by e-marie-w — APPROVED** [review]
Vertical option is working as expected.

**Pull request merged**
