### PR TITLE
Composer security update and Drupal update to 9.2.7

### PR DESCRIPTION
**Pull request by pyrello**
Updates Drupal to 9.2.7, which allows composer to be update to 2.1.9, which is the most recent secure version.

Also had to update to a new patch in https://www.drupal.org/project/drupal/issues/2605218 to get the update to work.

# How to test

* If builds pass, we probably think this is okay, except...
* Test views block pager functionality on sandbox locally to make sure that selected people list block properties stay in place between AJAX block loads.

### CODE REVIEW

**Comment by pyrello** [comment]
As far as I can tell, the new patch that was used has not resulted in any regressions with the people list block stuff. I reviewed the code changes too and did not expect any regressions based on that.

**Review by dnkemper — APPROVED** [review]
Couldn't find any regressions as well. Nice work, @pyrello

**Comment by joewhitsitt** [comment]
testing the pager real quick.

**Comment by dnkemper** [comment]
Crap... sorry, @joewhitsitt

**Comment by joewhitsitt** [comment]
apologies. didn't see you were testing it. if you think it is good. let's go with it

**Pull request merged**
