### PR TITLE
SPPA - opportunities view listing

### LINKED ISSUE #3706: SPPA - Build opportunity resource listing page
# Story

As an SPPA student, I can view opportunities (jobs, fellowships, etc.) in a list on the site.

# Proposed solution

* Build a view to list content created via the result of #3211.
* Provide filters for name, location, type of opportunity.
* May involve minimal styling based on timely feedback from the client.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #3706

_Disclaimer: No styling notes have been provided at the time of this development._

## Story 
As a site visitor to the SPPA website which is full of opportunity content, I can view a list of the content at /opportunities and be able to filter based on the name, location and type. If content doesn't exist or there isn't any content matching my filter criteria, I can see a no results message.

## To Test
1. `blt ds --site=sppa.uiowa.edu`
2. `drush @sppa.local uli opportunities`

You can enable devel generate and populate content. https://sppa.local.drupal.uiowa.edu/admin/config/development/generate/content

Screen Shot 2021-07-08 at 4 29 47 PM

### CODE REVIEW

**Comment by dnkemper** [comment]
I can review this while waiting on clarification for panopto PR. Crushin' it, Joe!

**Review by dnkemper — APPROVED** [review]
Noiice!

**Comment by pyrello** [comment]
@joewhitsitt If you had mentioned it to me, I would have enabled the split in PROD before now :)

I updated the instructions to reflect that the SPPA site split is now active.

**Comment by pyrello** [comment]
It is not exactly true that no styling notes were provided. I offered to get anyone working on this access to the original site to view the pages that this is replacing.

I have made some updates to the address the styling, which I think is good enough for now.

**Comment by pyrello** [comment]
Going to merge this based on previous approval and my testing of changes.

**Comment by joewhitsitt** [comment]
>It is not exactly true that no styling notes were provided.

Wasn't meant as a jab. The PR summary was just based on the issue bullet:

> May involve minimal styling based on timely feedback from the client.

which wasn't captured on the issue when I approached the issue and got the PR out for initial review.

> I offered to get anyone working on this access to the original site to view the pages that this is replacing.

I think I had a bit of a disconnect between this issue and the content type issue and didn't think we were recreating for the view page.

**Comment by pyrello** [comment]
@joewhitsitt Not a problem. Sometimes with these issues, I'm not sure how much work we should be doing until I get into actually working on it.

**Pull request merged**
