### PR TITLE
[IWP] Rabbit hole taxonomy term permissions fix

### LINKED ISSUE #8014: IWP permissions issue
# Story

As an editor, publisher and webmaster of the IWP website, I would like the permission to "Bypass Rabbit Hole action for Taxonomy Term" so we can view those term pages.

# Additional Information

Masquerade as one of the roles listed above and try to navigate to a Rabbit Holed term page https://iwp.prod.drupal.uiowa.edu/countries/afghanistan. You should get a page not found.

I assume we just missed this as it looks like we granted this permission on other sites to these roles.

### PR DESCRIPTION
**Pull request by e-marie-w**
Closes #8014 

# How to test
- `ddev blt ds --site=iwp.uiowa.edu`
- Masquerade as editor, publisher, and webmaster, and check that you can now actually view taxonomy term pages like https://iwp.uiowa.ddev.site/countries/afghanistan

### CODE REVIEW

**Comment by GaryRidgway** [comment]
pulling to review

**Review by GaryRidgway — APPROVED** [review]
CONFIRMED

**Comment by e-marie-w** [comment]
Thanks @GaryRidgway!

**Comment by e-marie-w** [comment]
Converting back to draft to add the other IWP JDI to this.

**Comment by bspeare** [comment]
Merging this in so that the other JDI can happen in a new pr.

**Pull request merged**
