### PR TITLE
Test honeypot patch

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #798

This is a small step to test before trying things like cache busting timeouts or reCAPTCHA.

### CODE REVIEW

**Comment by briand44** [comment]
added Alan as a reviewer, he was looking for something to work on.

**Comment by joewhitsitt** [comment]
it can't really be reviewed locally besides confirming that there is a honeypot field at the top of webforms (hidden). to test, we need to go where the spambots are

**Comment by briand44** [comment]
I realize that but I thought you had asked for someone to confirm that during our meeting. If you just want me to approve, tell me.

**Comment by joewhitsitt** [comment]
of course i would love a blind approval, but given that there is a composer update, it would probably be safer to have at least one other successfully update their local with this branch.

**Review by GaryRidgway — APPROVED** [review]
I have tested this and confirmed the field is now at the top of the page

**Pull request merged**
