### PR TITLE
Initialize tech.clas.uiowa.edu multisite on uiowa01

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Provisioning tech.clas.uiowa.edu for the IT/Technology Services group in CLAS based on their request. This will act as another separate site within the College to break apart the massive amount of information/content in the existing CLAS site, just as hr.clas.uiowa.edu, finance.clas.uiowa.edu, alt.clas.uiowa.edu is doing.

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
Will need to set Mark Fullenkamp (mfullenk) and Hans Hoerschelman (hoersche) as webmasters of this site after install.

**Comment by joewhitsitt** [comment]
Our normal process includes getting approval/pointing from hostmaster before provisioning. Has that been done?

https://wiki.uiowa.edu/display/drupaldev/Website+requests+via+sitenow.uiowa.edu

**Comment by mark-bennett-uiowa** [comment]
> Our normal process includes getting approval/pointing from hostmaster before provisioning. Has that been done?
> 
> https://wiki.uiowa.edu/display/drupaldev/Website+requests+via+sitenow.uiowa.edu

~~My apologies, I forgot that step in my quickness to get this out. Notifying Hostmaster right now.~~
Hostmaster is now pointing this domain to the LB.

**Review by joewhitsitt — APPROVED** [review]

**Comment by joewhitsitt** [comment]
> Will need to set Mark Fullenkamp (mfullenk) and Hans Hoerschelman (hoersche) as webmasters of this site after install.

Site installed/users created. Used the resend email functionality to send an email to Hans and Mark even though this wasn't a submission.

**Pull request merged**
