### PR TITLE
Hotfix for views exposed form reset link

### PR DESCRIPTION
**Pull request by bspeare**
Test the reset button https://iowasummerwritingfestival.prod.drupal.uiowa.edu/events. 

`ddev blt frontend`
`ddev blt ds --site=iowasummerwritingfestival.uiowa.edu`
Test https://iowasummerwritingfestival.uiowa.ddev.site/events in a private window.  Reset button should be placed under search and not above.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Tested, and works well!

On a note unrelated to the reset button: Should there be a "No results" text added to the view? I don't remember if there was a reason to specifically not include it or not.

**Review by cory-skeers — APPROVED** [review]
Approving for the specific change this addresses. Extra question in https://github.com/uiowa/uiowa/pull/6096#issuecomment-1382186469 that could be snuck in here if desired, but not necessary.

**Comment by bspeare** [comment]
Thanks @cory-skeers! Do you want to sneak that in?

**Comment by cory-skeers** [comment]
> Thanks @cory-skeers! Do you want to sneak that in?

Er, after looking at it more, it should probably be updated in the Event feature split for the default view. I don't think that would be an issue for the few sites that have it turned on, but I also don't want to hold this up for an unrelated change. I'll open a separate issue.

**Pull request merged**
