### PR TITLE
Updated Antonio local font for better browser consistency

### PR DESCRIPTION
**Pull request by bspeare**
This fixes the font-weight issue was appearing lighter in Safari without having to switch to Google fonts. 

# How to test

`ddev blt frontend`
Review `uids_base` code changes that switch font paths to use UIDS3 fonts
`ddev blt ds --site=sandbox.uiowa.edu`
Test on chrome and safari and make sure that font weight looks the same.  The current prod site page in Safari should appear as a lighter font weight.
- Test out Antonio usage on https://sandbox.prod.drupal.uiowa.edu/button-page
- Test out Antonio usage on https://sandbox.prod.drupal.uiowa.edu/statistics
- Test out Antonio usage on https://sandbox.prod.drupal.uiowa.edu/banner-backgrounds-w-gradient-dark

### CODE REVIEW

**Comment by bspeare** [comment]
This is **currently not on** dev if anyone wants to check it out: http://admissions.dev.drupal.uiowa.edu/.   It looks like we will need to resolve some vertical alignment issues for Antonio.

**Comment by bspeare** [comment]
Stll to do, Antonio is sitting lower within buttons and stats:

Screen Shot 2022-11-04 at 2 16 10 PM

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Safari does look more consistent with this PR. Probably more of a criticism of the font, but `4` just looks like it isn't the same font.. (from brave, ddev)

Screen Shot 2023-01-11 at 10 09 32 AM

**Comment by bspeare** [comment]
@joewhitsitt was `4` that specific to this update?  Did you compare the live site to the local?

**Comment by joewhitsitt** [comment]
That screenshot was local chrome. I think it is more noticeable with the update. brave (chrome) prod seemed to be thicker and hid the different in stroke.

prod chrome:
Screen Shot 2023-01-11 at 10 09 48 AM

**Comment by bspeare** [comment]
Thanks for testing @joewhitsitt!  I tested it on https://fonts.google.com/specimen/Antonio/tester and the weird 4 is showing up there so I'm going to blame the font.

**Pull request merged**
