### PR TITLE
Feature add search api to platform

### LINKED ISSUE #2091: Enable search_api module for default platform to prevent need to re-export policy.clas.uiowa.edu config
Currently, when new entities are added to the system or when existing entities are changed in the system, this sometimes results in needing to re-export the config for policy.clas.uiowa.edu. If we were to enable the search_api module platform wide, the entry that gets added to entity_view_display for each entity would be present for the whole platform and not need to be split for the policy site. While this may add a small amount of unnecessary overhead to each site, it would reduce on ongoing maintenance burden.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #2091 

# To test

 I'm not too worried about the `search_api` module just being turned on affecting functionality negatively, since it is a very commonly used module. Mostly it is necessary to make sure that config is syncing.

* Sync a site, ensure that there are no issues, check basic site functionality.
* @mark-bennett-uiowa Check policy.clas.uiowa.edu to make sure I didn't break any functionality.
* @joewhitsitt Check hr.uiowa.edu to make sure that I didn't break any functionality.

### CODE REVIEW

**Comment by pyrello** [comment]
I started this, but there are a lot of files that need to be updated, so I won't be able to finish it until next week, most likely.

**Comment by pyrello** [comment]
It looks like all the config has been updated except for HR, which has a few `entity_view_display` instances which will need to be re-exported: `drush @hr.local csex hr_uiowa_edu`

**Comment by joewhitsitt** [comment]
Haven't pulled/tested yet, but I am confused as to why hr uiowa footer settings are now tracked in config? Webmasters should be able to update this info without it getting reverted.

**Comment by pyrello** [comment]
That's my bad, @joewhitsitt. I didn't remember that uiowa footer config was ignored.

**Comment by mark-bennett-uiowa** [comment]
@pyrello I am testing out this PR, and everything updated/installed without an error (unlike a few days ago). I tested out some search items on the policy.clas.uiowa.edu site and most worked just fine. However, when I searched for "probation", even though there were results displayed at the bottom, I got this large error message:
```
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\search_api\Plugin\search_api\processor\Highlight->highlightField() (line 628 of modules/contrib/search_api/src/Plugin/search_api/processor/Highlight.php).
Drupal\search_api\Plugin\search_api\processor\Highlight->highlightField('...
```
Also, when I run a Status Report on that site, I have numerous warnings under the Configuration Inspector heading:
Screen Shot 2020-09-17 at 10 43 38 AM

I am searching for some solutions as I write this.

**Comment by mark-bennett-uiowa** [comment]
@pyrello UPDATE: I cant seem to reproduce the initial parameter error now, no matter what I throw at the search box. The status report errors are showing configuration that primarily should not have been changed by the policy.clas.uiowa.edu site split. Is this because of any changes in the collegiate split?

**Comment by richardbporter** [comment]
@mark-bennett-uiowa The status report errors are unrelated. That is the [config inspector](https://www.drupal.org/project/config_inspector) module, which is only enabled locally. It indicates which config entities have a schema mismatch.

The idea behind is that we should fix our own schema issues but safely ignore contirb/core.

**Comment by mark-bennett-uiowa** [comment]
@richardbporter okay, thats what I was hoping. Thanks bud.

**Review by joewhitsitt — APPROVED** [review]
I did a sync on several v2 custom sites including HR with no configuration issues. HR I was able to edit the footer without the config exporting.

**Review by mark-bennett-uiowa — APPROVED** [review]
Approved for the policy.clas.uiowa.edu site. Did not cause any permanent issues during testing.

**Pull request merged**
