### PR TITLE
Require cards be rendered horizontaly if placed in a onecol layout.

### LINKED ISSUE #1987: Allow card component to display in onecol layout as horizontal variant only
# Problem

The regular card component is not meant to render within a onecol layout.  However, the horizontal variant does render well within the onecol layout: https://uids.brand.uiowa.edu/components/detail/card--horizontal.html. 

# Proposed Solution

Force the `horizontal` style variant if card is placed within a onecol layout.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1987. Some PHPCS as well.

### Testing
- Try adding a card to a onecol layout.
  - See the form returns an error.
- Try adding a card to a non-onecol layout.
  - See the form styles can be changed.

### CODE REVIEW

**Comment by bspeare** [comment]
@richardbporter Both tests worked for me!  I can live without being able to add the border option to a one column card.

**Comment by richardbporter** [comment]
I ran into an issue where the border style seems to be set even though it is not visible in the style field. I'm going to try the form validation method. 

Screenshot this for comparison later.
Screen Shot 2020-08-10 at 9 51 51 AM

**Comment by richardbporter** [comment]
Got the custom validation working. If the horizontal style is not set, the form returns an error on submission. This makes it possible to use the border style or any future styles.

Screen Shot 2020-08-10 at 10 36 41 AM

**Review by bspeare — APPROVED** [review]
It works great! I tested it on https://uiowa.local.drupal.uiowa.edu/ and I was able to use both override style options.   Thanks!

**Pull request merged**
