### PR TITLE
Feature: Adding event series link to event content type

### LINKED ISSUE #4010: Extend event content type feature to provide Series Link and Directly link to Series functionality
# Story

As an editor, I can provide a Series Link for event content that displays as a button on the event node but also provides and option to link directly to it from teasers and view titles.

# For reference

Look at sitenow_articles for functionality similar to this.

# Proposed Solution

- [x] Extend event content feature to provide a "Series Link" link field.
  - [x] Output the title/link as a button so visitors to the event instance can navigate to the Event Series
- [x] Extend event content feature to provide a "Directly link to Series" boolean field.
  - [x] Teasers and views row titles link to Event Series if direct link is checked.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/4010. 

## To Test

- `blt ds --site=default`
- `drush @default.local uli`
- Go to https://default.local.drupal.uiowa.edu/admin/config/development/configuration/config-split/event/enable
- `drush @default.local cim && drush @default.local cr`
- Add a "Series Link" and it should show up in the sidebar when the page is published.
- If there is content in the link field, the checkbox for direct linking should appear below the link field. 
  - If that box is checked, https://default.local.drupal.uiowa.edu/events should link directly to the Series Link url.
- Test on admissions events calendar using the link to series link field and verify that the item in the calendar view links directly to the url.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
taking a look

**Review by joewhitsitt — APPROVED** [review]
Clever solution for the calendar display!

Everything checks out.

I did notice something odd when viewing the teaser in preview that I want to document. With the default site, the teaser was always linked correctly. On admissions, when the series link was filled out but not direct, the teaser was without a link. This same behavior did not show up on the view displays. It is not clear to me what the difference is or why it is happening.

**Comment by bspeare** [comment]
> I did notice something odd when viewing the teaser in preview that I want to document. With the default site, the teaser was always linked correctly. On admissions, when the series link was filled out but not direct, the teaser was without a link. This same behavior did not show up on the view displays. It is not clear to me what the difference is or why it is happening.

Thanks! I'll take another look at this before merging.

**Comment by bspeare** [comment]
Screen Shot 2021-08-23 at 11 38 33 AM

@joewhitsitt Were you saying that teasers on this list were not linking to anything? Or are you saying that the link should appear under the title in this list if "Link directly to source" is unchecked?

**Comment by joewhitsitt** [comment]
I can't replicate it consistently so probably a cache issue. But I am talking about the node edit preview functionality.
Screen Shot 2021-08-23 at 11 44 25 AM

Screen Shot 2021-08-23 at 11 42 22 AM

**Comment by bspeare** [comment]
@joewhitsitt thanks for the clarification!

**Pull request merged**
