### PR TITLE
Provision remaining clas and department sites on uiowa04

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Provisioning the following sites in order to setup the remaining CLAS sites:

https://linux.clas.uiowa.edu/ (added to uiowa01)
https://gwss.uiowa.edu/
https://hhp.uiowa.edu/
https://philosophy.uiowa.edu/
https://politicalscience.uiowa.edu/
https://religion.uiowa.edu/
https://rhetoric.uiowa.edu/

https://clas.uiowa.edu/
https://art.uiowa.edu/
https://biology.uiowa.edu/
https://chem.uiowa.edu/
https://dance.uiowa.edu/
https://deltacenter.uiowa.edu/
https://dpa.uiowa.edu/
https://english.uiowa.edu/
https://instructional-resources.physics.uiowa.edu/ (added to uiowa01)
https://iowamommoodbooster.org/
https://math.uiowa.edu/
https://music.uiowa.edu/
https://nanotech.uiowa.edu/
https://pda.uiowa.edu/
https://psychology.uiowa.edu/
https://sloancenter.uiowa.edu/
https://speakingcenter.uiowa.edu/
https://stat.uiowa.edu/
https://geemap.stat.uiowa.edu/
https://sustainability.uiowa.edu/
https://theatre.uiowa.edu/
https://writersworkshop.uiowa.edu/
https://writingcenter.uiowa.edu/

# How to test

Standard site provision check.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa do you have capacity to resolve the merge conflict here?

**Comment by mark-bennett-uiowa** [comment]
> @mark-bennett-uiowa do you have capacity to resolve the merge conflict here?

How exactly do I do that @joewhitsitt. I havent had to resolve something like that before. If someone could assist, I could do that now.

**Comment by joewhitsitt** [comment]
I can't dive in to "resolving git merge conflicts" (lots of search results) at the moment, but you started this branch and/or added to sites.php after main had already been updated https://github.com/uiowa/uiowa/blob/main/docroot/sites/sites.php. Ben had put together site requests as part of the support shift which added to the file. Your file doesn't have it so you need to resolve to make sure the recent additions are kept and your stuff is added beneath it. This same problem will come up with the other open provisions PR.

Checkout this VSCode mergetool setup which makes things easier: https://stackoverflow.com/questions/44549733/how-to-use-visual-studio-code-as-the-default-editor-for-git-mergetool-including/44549734#44549734

**Comment by mark-bennett-uiowa** [comment]
Well, thank you @pyrello. I was working on trying to figure it out, but looks like you got it. My apologies you had to fix this after hours.

**Comment by pyrello** [comment]
This was a pretty easy merge, so I just did it. @mark-bennett-uiowa, if you want me to show you what I did, we can go through it after this gets merged and we need to resolve the same conflict with #5956.

**Comment by pyrello** [comment]
> Well, thank you @pyrello. I was working on trying to figure it out, but looks like you got it. My apologies you had to fix this after hours.

No worries. I was just catching up on some things.

**Comment by mark-bennett-uiowa** [comment]
> This was a pretty easy merge, so I just did it. @mark-bennett-uiowa, if you want me to show you what I did, we can go through it after this gets merged and we need to resolve the same conflict with #5956.

Sounds good. I want to know how to do this properly for next time, just in case. Thanks again for the fix!

**Review by pyrello — APPROVED** [review]
Reviewed, not tested.

**Pull request merged**
