### PR TITLE
Updated linkit to D10.0 compatible version

### LINKED ISSUE #6343: As a content creator, I would like to be able to link to draft pages with auto-complete
# Problem
As a content creator, I would like to be able to link to draft pages with auto-complete whether the page I'm on is draft or published, because I create many draft pages at one time that go live later, sometimes at the same time. It works if I grab the relative URL manually and paste it.

# Steps to reproduce

https://user-images.githubusercontent.com/52135878/231269950-c44db6f5-391d-4e7b-876d-f95025e8a94d.mp4

# Proposed solution

### PR DESCRIPTION
**Pull request by pyrello**
Code changes: https://git.drupalcode.org/project/linkit/-/compare/6.0.0-rc1...6.0.2

# How to test
```
ddev blt ds --site sandbox.uiowa.edu && ddev drush @sandbox.local uli node/add/page
```
- Test suggestions for content
- Test suggestions for webform
- Test paths that don't get suggestions (views page paths or paths that don't exist)
- Test external links
- Test anchor links
- Ensure that Title and Advanced properties still work

New functionality (unpublish highlight), resolves #6343 :

Screenshot 2023-10-16 at 9 42 18 AM

### CODE REVIEW

**Comment by pyrello** [comment]
I added this PR because I was seeing the following when running `ddev composer prohibits drupal/core ^10.0`:

```
drupal/linkit            6.0.0-rc1  conflicts         drupal/core (>=10.1)
```

But now I'm realizing that if I change the command to `ddev composer prohibits drupal/core 10.0` there is no problem.

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
Looks good.

**Comment by pyrello** [comment]
Good catch on the new functionality!

**Pull request merged**
