### PR TITLE
UI Press - Book migrations

### LINKED ISSUE #4662: UI Press - Build migration for UI Press Book content type
1108 items to migrate on the original site.

# Proposed solution
- [x] Write migration from UI Press Book content to Book content.
- [x] Account for change in how book types are handled. On the old site, there are discrete fields for all book type fields. On the new site, there is a paragraph bundle with generic fields.
- [x] Additionally account for the fact that ebook ownership license is also handled differently. Previously there was a price field for both types of ownership. Now, the ownership type is property of the book type. If there was price information for both types of ownership, then two book type bundles will need to be created to account for both of them.
- [x] We would like to do some DOM manipulation on the Reviews field: Find every instance of `<p></p>` tags and replace them with `<blockquote></blockquote>` tags. It seems like it might also be possible to parse each review (each is inside its own `<p></p>` tag in examples I examined) and figure out the part that is the attribution and format it correctly.
- [x] Add redirect migration.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #4662 

# How to test

Sync uipress in DevDesktop (grad container)
git checkout uipress_book_migration && git pull
blt frontend
blt ds --site=uipress.uiowa.edu
drush @uipress.local en uipress_migrate -y
drush @uipress.local uli /admin/config/sitenow/sitenow-migrate
Complete the form using the help text
drush @uipress.local ms <- check that migrations register
drush @uipress.local mim --all

## Books to compare:

Compare "[Zig-Zag-and-Swirl](https://www.uipress.uiowa.edu/books/9781587294662/zig-zag-and-swirl)" for author, subjects, book cover, publication date (2010 year), pages/art/..., book types (paper, ebook 120 and perpetual), summary, reviews/blurbs, related
Compare "[They Don’t Want Her There](https://www.uipress.uiowa.edu/books/9781609388195/they-don%E2%80%99t-want-her-there)" for foreword author, afterword author
Compare "[Women Adapting](https://www.uipress.uiowa.edu/books/9781609386498/women-adapting)" for series, awards
Compare "[Whitman & Dickinson](https://www.uipress.uiowa.edu/books/9781609385316/whitman-dickinson)" for editors, contributors
Compare "[The Raptors of Iowa](https://www.uipress.uiowa.edu/books/9781609381660/the-raptors-of-iowa)" for illustrator, essay, table of contents
Compare "[Vivid and Continuous](https://www.uipress.uiowa.edu/books/9781609381561/vivid-and-continuous)" for excerpt
Compare "[Wildflowers of Iowa Woodlands](https://www.uipress.uiowa.edu/books/9781587298233/wildflowers-of-iowa-woodlands)" for interior images
Compare '[“The Million Dead, Too, Summ’d Up”](https://www.uipress.uiowa.edu/books/9781609387464/%E2%80%9Cthe-million-dead-too-summ%E2%80%99d-up%E2%80%9D)' for introductory author
Compare "[Turtles in Your Pocket](https://www.uipress.uiowa.edu/books/9781609380618/turtles-in-your-pocket)" for photographer
Compare "[Poems from Guantánamo](https://www.uipress.uiowa.edu/books/9781587296062/poems-from-guant%C3%A1namo)" for preface authors
Compare "[Memoirs of a Revolutionary](https://www.uipress.uiowa.edu/books/9780877458272/memoirs-of-a-revolutionary)" for translator

## Note

There will be 38 "stub" nodes in the top of the content overview. Other nodes referenced this content, the migration stubbed it out, but ultimately the content to fill these out no longer exists. Manual deletion of these should be done after migration. When the referencing nodes are saved again, those references should be cleaned up.

### CODE REVIEW

**Comment by pyrello** [comment]
Yet to be done:
- Create book type paragraph bundles to attach to the `field_book_type` field. These will be created from the "Cloth", "Paper", and "eBook" fields. Each one becomes its own bundle.
- Test series mapping logic. This is a multi-value field, although I'm not sure if there are any books that use it.
- Account for https://github.com/uiowa/uiowa/issues/4662#issuecomment-1068649016.
- Review fields in the D7 site that are not being moved over with the folks who worked on the content type to make sure that we didn't miss something.
- Test both migrations.

**Comment by pyrello** [comment]
When I try to run `drush @uipress.local ms`, I am getting a "Connection timed out" error. I believe the D7 database synced in Dev Desktop without any issues.

I tried running this with the `-vvv` flag on and it seems like the step it is stalling out on is `Try to validate bootstrap phase 0`

I'm not sure how to resolve this.

**Comment by pyrello** [comment]
@cory-skeers I am realizing that the image fields don't seem to be transferring over. I have compared this migration with what you did in the Author migration and I can't see what I am doing wrong. Any chance you can check this to see if you can figure it out?

**Comment by cory-skeers** [comment]
> the image fields don't seem to be transferring over

I haven't tested it, but think I found the problem. The image field was getting processed into `field_image` as the source property, but the YML was mapping from `field_image_attach`

**Comment by pyrello** [comment]
> I haven't tested it, but think I found the problem. The image field was getting processed into `field_image` as the source property, but the YML was mapping from `field_image_attach`

This doesn't seem quite right to me. The source field is called `field_image_attach`:
Screen Shot 2022-04-08 at 4 10 44 PM

When you say that it is getting processed into `field_image` what do you mean?

**Comment by cory-skeers** [comment]
> > I haven't tested it, but think I found the problem. The image field was getting processed into `field_image` as the source property, but the YML was mapping from `field_image_attach`
> 
> This doesn't seem quite right to me. The source field is called `field_image_attach`: Screen Shot 2022-04-08 at 4 10 44 PM
> 
> When you say that it is getting processed into `field_image` what do you mean?

The line `$row->setSourceProperty('field_image', $this->processImageField($image[0]['fid'], $image[0]['alt'], $image[0]['title']));` is creating a new source property called `field_image` rather than replacing the original source data in `field_image_attach`. The other fix would be to change this to set it to the original `field_image_attach` and undo the change I made to the YML.

**Comment by pyrello** [comment]
That change did the trick, @cory-skeers!

There is another file field that is not pulling over images:
```
field_book_file_uploads: uploads
```

Also, any ideas about how to remove text like `[bg|1938]` from the description field?

**Comment by cory-skeers** [comment]
> Also, any ideas about how to remove text like `[bg|1938]` from the description field?

Is it always in brackets like that, or how regular is it?

We do a little bit in the `extractSummaryFromText` in `BaseNodeSource` that removes some things like `figcaption`s before truncating. Just a series of `$output = preg_replace('/<figcaption[^>]*>.*?<\/figcaption>/is', ' ', $output);` and then removing extra spaces if they get doubled up (replacing with no space immediately could lead to words running together in some instances).

If it's just bracketed text, altering that `preg_replace` should work, but might need more work if there are other instances to account for as well.

**Comment by cory-skeers** [comment]
Taking a look at the file uploads.

**Comment by pyrello** [comment]
> Is it always in brackets like that, or how regular is it?

I believe it will always follow a pattern of `[bg|{$nid}]` where `$nid` is the (D7) node ID of the node being processed.

**Comment by cory-skeers** [comment]
> There is another file field that is not pulling over images:
> 
> ```
> field_book_file_uploads: uploads
> ```

Does the file uploads field need to be added still, or am I missing something locally? Otherwise, I think the changes I pushed up should work...looks like we do have instances of multiple files for individual books, so it's using the multi-value fetcher to grab the FIDs, then individually processing each into a media entity and MID.

**Comment by pyrello** [comment]
> Does the file uploads field need to be added still, or am I missing something locally? Otherwise, I think the changes I pushed up should work...looks like we do have instances of multiple files for individual books, so it's using the multi-value fetcher to grab the FIDs, then individually processing each into a media entity and MID.

The `uploads` field is just turning into the `field_book_file_uploads` field, which is just the interior book page images. I haven't tested, but it looks like your change should do the trick.

This also gave me an idea for a potential enhancement to the migration suite we have built: If there was a way in the YAML file for a migration to indicate that a field was an image, we could potentially just have a generic process that loops through any of those fields and does the same thing your change does: https://github.com/uiowa/uiowa/pull/4968/commits/92333dda00dbf1cf616b76b62c01519d54946b88. Alternately, we could also have a property on the base node class called `$imageFields` that is an empty array on the abstract class, but could be overridden on a particular implementing class to contain a list of image fields and above processing could act on that list.

**Comment by cory-skeers** [comment]
> > Is it always in brackets like that, or how regular is it?
> 
> I believe it will always follow a pattern of `[bg|{$nid}]` where `$nid` is the (D7) node ID of the node being processed.

Pushed up a small addition for this, and it looks like you were right about the format as far as I could tell. Most of them were also alone inside `<p>` tags, so I removed those as well (where that was the case). There are some spots (<20) where there might still be an extra `<br>` tag or something similar, but nothing breaking.

**Comment by pyrello** [comment]
> I haven't tested, but it looks like your change should do the trick.

@cory-skeers I guess I was wrong about this. It's not working for me. 

I also noticed that none of the fields referencing people seem to be working either. I have tried a few things to get it working, but I have had no luck thus far. I did think it was because I hadn't run the authors migration, but it was still an issue after ran that migration.

@joewhitsitt Was this working when you were working on this?

**Comment by pyrello** [comment]
I pushed up a small enhancement: Making the process for getting multi-value fields something that can be specified by setting a `$multiValueFields` property on a source migration class.

The rest of my commit is my tinkering to try to get the upload field working, but without luck.

**Comment by joewhitsitt** [comment]
I'll be honest, when I was working on this, I was pretty focused on the "left todo." Assumed most everything else was working because at a glance I did see other content get migrated.

Would you like me to pull this down and do a field by field inspection?

**Comment by pyrello** [comment]
> Would you like me to pull this down and do a field by field inspection?

No. I'm just trying to get a sense of any of those fields were ever working. I filled them in but never got to the point of testing them before I had to set this down. I thought I was following a clear pattern, but when I look for similar instances in other migrations, I'm not seeing much to go on.

@cory-skeers and/or @richardbporter I'm stuck on this for the time being. Any help would be appreciated.

**Comment by joewhitsitt** [comment]
Pulling down

**Comment by joewhitsitt** [comment]
I think got the references to uipress_authors fix. needed a dependency and to map target_id instead of nid. i noticed a few other fields that don't seem to working but I haven't had a chance to look into it:

- subtitle - this is being captured in the db but the field is not on the form 
- ~~publication date~~ - fixed https://github.com/uiowa/uiowa/pull/4968/commits/71e14dcdd27e2e7e7e6c8fa11801ce7ada79e684
- ~~season~~ - fixed https://github.com/uiowa/uiowa/pull/4968/commits/6d9e7959e8891c1ef14b3dd8f49007dcff50e7dc
- ~~related reads~~ https://github.com/uiowa/uiowa/pull/4968#issuecomment-1098376689

**Comment by pyrello** [comment]
@e-marie-w Can you remind me where we ended up with the Subtitle field?

**Comment by pyrello** [comment]
> I think got the references to uipress_authors fix. needed a dependency and to map target_id instead of nid. i noticed a few other fields that don't seem to working but I haven't had a chance to look into it:
> 
> * subtitle
> * publication date
> * season
> * related reads

Related reads seems to be working. I think it just requires that you run a good portion of the migration before entries in this field will show up because they are depending on other books that haven't been migrated yet.

**Comment by e-marie-w** [comment]
At one point we discussed having the subtitle be entered as part of the title, because that's how other book-selling sites do it. I think I might've hid and/or removed the field based off that discussion, but I don't remember exactly.

**Comment by joewhitsitt** [comment]
So the publication date on the d7 is just `Y` (e.g. 2002). The publication date on the d9 site is expecting `Y-m-d`. So I got it to capture the year, but the field fills out `today` for the rest of the date field. So I imagine this field needs to be recreated to capture year only? I think this is only possible using the number field...

**Comment by pyrello** [comment]
> So the publication date on the d7 is just Y (e.g. 2002). The publication date on the d9 site is expecting Y-m-d. So I got it to capture the year, but the field fills out today for the rest of the date field. So I imagine this field needs to be recreated to capture year only? I think this is only possible using the number field...

I'm not sure there is a way to do this. I just looked at it quickly and the current field type doesn't have a way to define a date format that limits it to just. Nor is there a way to set it up that way in form display settings. I seem to recall having this conversation before when we were setting up the content type. I think we had just explained to the customer that she was going to have to set arbitrary month and day. Are the month and day showing up on the book page?

**Comment by joewhitsitt** [comment]
The full date is being displayed on the node. That could be adjusted if we are concerned about the accuracy of past data.

I am struggling to get list value to taxonomy term figured out with "Season." I have been trying all kinds of iterations surrounding entity_generate. It doesn't error out but it doesn't work either.

```
  field_book_season:
    plugin: entity_generate
    source: field_uibook_season
    entity_type: taxonomy_term
    bundle_key: vid
    bundle: season
    value_key: name
    values:
      name: field_uibook_season_value
```

**Comment by pyrello** [comment]
> At one point we discussed having the subtitle be entered as part of the title, because that's how other book-selling sites do it. I think I might've hid and/or removed the field based off that discussion, but I don't remember exactly.

@e-marie-w I guess I'm hesitant to combine the fields because there is no going back from that. We can display them as one thing to end users while keeping the data separate on the backend. That way if they decide they need to be separate in the future, we have that option. If we combine them, we are stuck with that.

**Comment by cory-skeers** [comment]
Planning on taking a look into the upload fields today, and try to get that working.

**Comment by pyrello** [comment]
> Planning on taking a look into the upload fields today, and try to get that working.

Thank you, thank you, thank you, thank you..!

Very curious to see how this gets resolved. I tried at least half a dozen different tweaks to get it working.

**Comment by joewhitsitt** [comment]
I think i got the season field kind of working. Might need to pair it with an entity_lookup because i think only the first one is being created and referenced properly. Downside is that rolling back doesn't remove the taxonomy terms.

Update: fixed field_book_season by using sub_process. Still no rollback of terms with this though.

**Comment by joewhitsitt** [comment]
Did I just fix the image issue?
Screen Shot 2022-04-14 at 1 12 30 PM
Screen Shot 2022-04-14 at 1 11 57 PM

**Comment by cory-skeers** [comment]
> Did I just fix the image issue?

It looks like it! I made that same change locally, though, and it's not working for me...I might have made some other change that broke it at the same time though? 🤷

**Comment by pyrello** [comment]
Well, I feel dumb.

**Comment by cory-skeers** [comment]
> > Did I just fix the image issue?
> 
> It looks like it! I made that same change locally, though, and it's not working for me...I might have made some other change that broke it at the same time though? 🤷

Typoed the machine name. Working correctly--nice find @joewhitsitt!

**Comment by joewhitsitt** [comment]
Did an audit of the book migration and updated the PR summary with left todo

**Comment by joewhitsitt** [comment]
Going to run through the full thing again this morning based on yesterday's changes.

Should I start displaying the subtitle form item again? Future slice, decide how to render it? Update from standup: do nothing for now.

**Comment by pyrello** [comment]
I'm going to test this locally. If it looks good, I'm going to merge it into `develop` and sync the UI Press site to dev.

**Comment by pyrello** [comment]
I'm looking at [Whitman & Dickinson](https://www.uipress.uiowa.edu/books/9781609385316/whitman-dickinson) and it appears that 120 day e-book was not created for it: https://uipress.uiowa.ddev.site/books/whitman-dickinson. This is the first instance I have seen of a book type not getting created correctly. I'm going to keep reviewing the other books to see if I can find anything else. @cory-skeers, @richardbporter, or @joewhitsitt if you are available to take a look in the meantime, it would be greatly appreciated!

**Comment by cory-skeers** [comment]
> I'm looking at [Whitman & Dickinson](https://www.uipress.uiowa.edu/books/9781609385316/whitman-dickinson) and it appears that 120 day e-book was not created for it: https://uipress.uiowa.ddev.site/books/whitman-dickinson. This is the first instance I have seen of a book type not getting created correctly. I'm going to keep reviewing the other books to see if I can find anything else. [...] if you are available to take a look in the meantime, it would be greatly appreciated!

Pulling down, and can take a look after this meeting!

**Comment by joewhitsitt** [comment]
>I'm looking at [Whitman & Dickinson](https://www.uipress.uiowa.edu/books/9781609385316/whitman-dickinson) and it appears that 120 day e-book was not created for it

It wasn't created because it doesn't have an ISBN-13 which is a required field on d9 and was the validation in the migration. It has a ISBN-10 for the d7 which aren't migrating. If that can be corrected, it should migrate.

**Comment by pyrello** [comment]
Just discovered that there are embedded MP3 links that are hosted on the UI Press site. This will require additional processing similar to what we are doing for images.

**Comment by pyrello** [comment]
I was able to solve it by re-saving the page, but I encountered the following error when visiting a test book:
`The website encountered an unexpected error. Please try again later.
Error: Call to a member function getFileUri() on null in Drupal\photoswipe\ImageDTO->__construct() (line 109 of modules/contrib/photoswipe/src/ImageDTO.php).`

Not clear on what the error is all about, but it seems like maybe there is a reference to a media item that is not actually there. Re-saving the form clears it out, so it displays after that. Not sure how to troubleshoot this just yet.

It occurred on this book: https://uipress.uiowa.ddev.site/books/poems-guantanamo

**Comment by pyrello** [comment]
> Just discovered that there are embedded MP3 links that are hosted on the UI Press site. This will require additional processing similar to what we are doing for images.

@cory-skeers I pushed some code in an attempt to get this working. The media entity for the audio file is being created, but the link is not being re-written. I'm not clear on why yet. If you have a chance to look at this tomorrow morning, that would be great!

**Comment by cory-skeers** [comment]
> > Just discovered that there are embedded MP3 links that are hosted on the UI Press site. This will require additional processing similar to what we are doing for images.
> 
> @cory-skeers I pushed some code in an attempt to get this working. The media entity for the audio file is being created, but the link is not being re-written. I'm not clear on why yet. If you have a chance to look at this tomorrow morning, that would be great!

Can do!

**Comment by pyrello** [comment]
> I was able to solve it by re-saving the page, but I encountered the following error when visiting a test book:
The website encountered an unexpected error. Please try again later. Error: Call to a member function getFileUri() on null in Drupal\photoswipe\ImageDTO->__construct() (line 109 of modules/contrib/photoswipe/src/ImageDTO.php).
>
> Not clear on what the error is all about, but it seems like maybe there is a reference to a media item that is not actually there. Re-saving the form clears it out, so it displays after that. Not sure how to troubleshoot this just yet.
>
> It occurred on this book: https://uipress.uiowa.ddev.site/books/poems-guantanamo

I think I figured this out. This is the same book that has MP3's linked in its description. The MP3s are attached using the upload field. Our `processImageField` method doesn't detect non-images and filter them out. I added some logic that does this and it seems to fix the above issue.

**Comment by pyrello** [comment]
>> @cory-skeers I pushed some code in an attempt to get this working. The media entity for the audio file is being created, but the link is not being re-written. I'm not clear on why yet. If you have a chance to look at this tomorrow morning, that would be great!

> Can do!

Actually, it appears that this only affects 5 files and their links on one page. So, I don't think it is worth resolving why its not working correctly in this PR as we can just fix the links after the migration is run.

**Review by pyrello — COMMENTED** [review]
Like most complex migrations, there are a few details that are not quite perfect but also not worth fixing programmatically. Follow-up tasks have been documented at #4903. I think this PR is good to go, pending review by the customer on dev.

**Comment by pyrello** [comment]
I can't approve, so someone else will need to do that.

**Review by cory-skeers — APPROVED** [review]
Approving--let's get this rolled out on dev and into the customer's hands!

**Comment by pyrello** [comment]
I really wanted this to be over, but now that I am looking at it again, the redirects don't seem to be getting set up correctly.

**Comment by pyrello** [comment]
> I really wanted this to be over, but now that I am looking at it again, the redirects don't seem to be getting set up correctly.

I just checked all the books in the test list above on dev and all the redirects worked, so I'm not sure what was going on.

**Comment by pyrello** [comment]
Merging to be ready to run migrations per customer request.

**Pull request merged**
