### PR TITLE
Joe's fantastic pull of fixes

### LINKED ISSUE #4070: Show Canceled Info on Event Teaser (v2/v3)
# Story

As an event attendee, I can see from an events listing whether a particular event has been cancelled.

# Background

- We have a "Canceled" badge on the single display (`event.canceled`).
- Customer was concerned that this information is not easy to see at a glance.

# Proposed solution

- [x] Find a way to incorporate `event.canceled` to the event teaser used by v2/v3.

### LINKED ISSUE #4969: Consistent field_tags widget across platform
Follow up from https://github.com/uiowa/uiowa/issues/4042

For consistency, other field_tags fields should be updated.

- All media types
- https://github.com/uiowa/uiowa/blob/main/config/features/event/field.field.node.event.field_tags.yml
- https://github.com/uiowa/uiowa/blob/main/config/features/topic_page/field.field.node.topic_collection.field_topic_collection_tags.yml
- Grad - https://github.com/uiowa/uiowa/blob/main/config/sites/grad.uiowa.edu/field.field.node.student_profile.field_tags.yml

### LINKED ISSUE #5150: imagecache_external update to fix batch cron job
# Problem

As a developer, I can see that imagecache_external images, pulled in by sitenow_events and other modules, are periodically being cleaned up as expected.

# Proposed Solution
- [x] Try the patch from https://www.drupal.org/project/imagecache_external/issues/3138005 to see if we get consistent cleanup going based on our 7-day configuration.

### LINKED ISSUE #5153: Imagecache External configuration is incorrect
noticed a warning for Imagecache External. fresh in my mind. not sure if it is new, but could we just set this to uiowa.edu for now or is this being used by aggregator in which case we should turn off this validation?

Screen Shot 2022-04-20 at 1 11 11 PM

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/5152#issuecomment-1104266700_

### LINKED ISSUE #5156: Consider link title attribute on image block for additional accessibility
# Story

Follow up from https://github.com/uiowa/uiowa/pull/5126
As a sighted user, I'd like to see the text related to a linked image I am about to click

# Background

https://github.com/uiowa/uiowa/pull/5126#issuecomment-1103198070

# Proposed Solution

- [x] Add title attribute to `<a>` using link text for image block

### LINKED ISSUE #5229: Taxonomy term feeds contain breadcrumbs and duplicate titles
# Problem
The out of the box taxonomy term view feed displays are pulling in the full node render for items.

Screen Shot 2022-05-04 at 12 14 26 PM

# Steps to reproduce
Pull in a v2/v3 feed into aggregator/rss block and see how it is displayed: https://education.uiowa.edu/taxonomy/term/196/feed

# Proposed solution
- [x] Modify the taxonomy_term_view RSS display to breakup items into the proper RSS spec elements similar to SiteNow Articles.

### PR DESCRIPTION
**Pull request by joewhitsitt**
# To Test Taxonomy Term RSS

(fixes #5229)
- Pull a site that has tagged content (articles, pages, people). View the RSS feed, preferably with twig debug turned off (false, docroot/sites/blt.development.services.yml). See that there aren't duplicate titles/dates, breadcrumbs, etc. Description should be filled if field_teaser is filled.

Screen Shot 2022-06-10 at 10 52 02 AM

# To Test imagecache external configuration change

(fixes #5153)
- Go to the status report page of any pulled down site. See that imagecache external is "properly configured" and that you are able to add an events or aggregator block and have images loaded.

Screen Shot 2022-06-09 at 4 57 33 PM

# To Test imagecache external clean up patch

(fixes #5150)
- This is hard to test unless you have a local site with several files/externals. The idea though is that you pull this site down, and run cron. that directory along with it's respective styles directory should clean up some if not all the images there and you should be able to revisit an events or aggregator block with images and have those folders fill up again. This doesn't run every cron however and a state timestamp is set. You can try adjusting the frequency temporarily, manually adjusting the timestamp in the db or you might have to trust me on this one.

Before:
Screen Shot 2022-06-10 at 10 44 17 AM

After:
Screen Shot 2022-06-10 at 10 47 48 AM

# To Test Image block title attribute

(fixes #5156)
- Add an image block with link text. View the published page. Hover over the image and see that the title tooltip appears with the text.

Screen Shot 2022-06-10 at 10 50 44 AM

# To Test Events teaser canceled

(fixes #4070)
- Create two events blocks:
  - One that brings up a canceled event: 
    - https://default.uiowa.ddev.site/event/77436/0
    - https://content.uiowa.edu/neuroscience-pharmacology-seminar-elizabeth-heller-phd
    - unit: pharmacology
    - interest: Research
    - type: Seminar
  - One that just brings up general upcoming events. 
- Notice that https://content.uiowa.edu/neuroscience-pharmacology-seminar-elizabeth-heller-phd shows up with a canceled badge. This is the same for v2. Note that the date, virtual, location, description of the other events is unaffected.

Screen Shot 2022-06-10 at 11 57 25 AM

# To test consistent tag widget

(fixes #4969)
- pull down a site and try adding different media types through the add media interface. they shouldn't be a single line field but the multi line option. help text describing comma-separated was removed. I didn't change the media library/browser versions because it was acting funky in the modal and putting the `add another item` button down with the `save and select` button.

Screen Shot 2022-06-10 at 1 57 11 PM

Screen Shot 2022-06-10 at 1 58 54 PM

### CODE REVIEW

**Comment by e-marie-w** [comment]
I don't want to commit to testing all the fixes at this time, but I'm going to pull this down and start testing a couple at least.

**Comment by e-marie-w** [comment]
Tested so far:

- Imagecache external - status now 'properly configured' on synced sites, vs. prod sites displaying 'not properly configured'.
- Cancelled events teaser - cancelled events now have a Cancelled badge displaying in the events block. Otherwise, their display looks identical to non-cancelled events. I tested this on v2 and v3.
- Image block title attribute - hovering over a linked image block shows a tooltip with the link text. Other functionality unchanged-actual URL still appears in lower left, and users need to fill in both link text and URL, or leave both fields empty in order to save block.
- Consistent tag widget - I tried adding different media types, for all of them you could add tags and each tag would be on its own line. Unrelated to this PR, but making visible some questions/issues: I couldn't save the Instagram media due to oembed error, I think we're aware of this one already. Facebook saves fine but doesn't actually title the media, is that known/expected behavior? Lastly, is the (local) video media type not used anymore? There's no upload button like for images. 
- Taxonomy term RSS - no duplicate titles/dates or breadcrumbs appearing in the taxonomy term feeds now.

Edit: 
Tested last fix, imagecache external clean up patch. Ran cron on existing local site I haven't synced in a month. Externals directory was cleared of outdated images. Adding a new events block repopulated the folder with current images.

**Comment by joewhitsitt** [comment]
>Unrelated to this PR, but making visible some questions/issues: I couldn't save the Instagram media due to oembed error, I think we're aware of this one already. Facebook saves fine but doesn't actually title the media, is that known/expected behavior? Lastly, is the (local) video media type not used anymore? There's no upload button like for images.

Instagram and Facebook oEmbed need local credentials to work. Might be the errors you are thinking of. If not, you can post an issue.

Local video is restricted to certain block types only (e.g. banner) and can only be uploaded through block edit forms.

**Review by e-marie-w — APPROVED** [review]
All six fixes work correctly for me, awesome job!

**Comment by joewhitsitt** [comment]
Thanks for your patience with my lackluster testing instructions @e-marie-w

**Pull request merged**
