### PR TITLE
Combine position styles for card person view and teaser view.

### LINKED ISSUE #3908: People in listings with multiple titles don't show titles on separate lines or with commas
# Problem
People in listings with multiple titles don't show titles one separate lines or with commas.

# Steps to reproduce
See https://law.uiowa.edu/faculty-and-scholarship/meet-our-faculty

# Proposed solution
Adjust people card template to display multiple titles using new lines. Notify laura-kivlighan@uiowa.edu when this is fixed.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3908 

I wasn't really sure where to put this. It appears by this comment that there are some shared styles: https://github.com/uiowa/uiowa/blob/af9d98402292db41b8b93cee14ecea8bd0c2f410/docroot/themes/custom/uids_base/scss/content/person.scss#L61-L63

Although, what is the difference between "card person view and card person teaser views"?

Requesting review from @bspeare since this touches a previous commit: https://github.com/uiowa/uiowa/commit/9ea9a6c419e6ffccc84802c09eafa52849e4ed82

### Testing
```
blt sync --site law.uiowa.edu &&
yarn workspace uids_base gulp --development
```

Inspect the following pages, perhaps more where this style is used that I'm not aware of.
https://law.local.drupal.uiowa.edu/faculty-and-scholarship/meet-our-faculty
https://law.local.drupal.uiowa.edu/people

### CODE REVIEW

**Comment by richardbporter** [comment]
Tagging @joewhitsitt too because he is a people person. :)

**Comment by joewhitsitt** [comment]
>Although, what is the difference between "card person view and card person teaser views"?

Card person view is the sidebar of a person node I believe.

**Review by bspeare — APPROVED** [review]
Looks good! Glad you found that previous commit.

**Comment by richardbporter** [comment]
> > Although, what is the difference between "card person view and card person teaser views"?
> 
> Card person view is the sidebar of a person node I believe.

Ok, then I think moving it in ca1b2e7 might be better since that field is not in the sidebar.

**Pull request merged**
