### PR TITLE
graduate college - workbench access

### LINKED ISSUE #2549: Create workbench access feature split
# Story

As a custom site owner I want the ability to limit editorial access to content based on association with a term or group.

# Proposed solution

Building on the work started in #748, build a feature split to allow for sites to turn on workbench access.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #2549
Relates to #748

This PR establishes workbench access on the grad.uiowa.edu website split. Originally, I thought it might make sense to establish some of this for the default to limit configuration splits, but with the complexity surrounding it, I decided to start with a full split for now.

- Editorial Groups taxonomy
- Reference field on page, article, book, person
- Editorial Access scheme that is enabled for page, article, book, person

# To Test

## Setup
`composer install`

## Testing
As a webmaster, this role is auto added to the Editorial Access scheme and allows management of users per Editorial Groups terms. Taxonomy hierarchy works with this system in that a parent term can manage all content classified with a child term. Webmaster is the only role that can add/edit terms for this.

Users are assigned by the webmaster role via a user's page. There should be a workbench access tab.

Content controlled by a term that a user doesn't have access to should get an access denied when they try to visit the edit form.

Additional grad website permissions might need to be adjusted based on this new functionality (e.g. book permissions)

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Continuing https://github.com/uiowa/uiowa/issues/1905#issuecomment-733745835, I was hoping to get @pyrello's opinion regarding the additional role before marking the PR as reviewable.

**Comment by pyrello** [comment]
In the case of the Grad College, anyone with the webmaster role would be above the editorial group restrictions. Or at least, I can't come up with a reason why they would need to be subject to them.

I'd be curious if @briand44 has an opinion, since he is the other person I know who has articulated a need for this one some sites.

**Comment by joewhitsitt** [comment]
Since Brian is out, to move this forward and if that is the case for Grad right now, I will remove the role and map it to webmaster. I think #1905 can be kept open as we discuss the future of permissions for default.

**Comment by pyrello** [comment]
Testing this out.

**Comment by pyrello** [comment]
My initial impressions of using this are that:
1. It would work for the described functionality.
2. It has some aspects of it that are undesirable, such as being able to select the whole "Editorial group" to add someone to, instead of just the terms/groups themselves. Also, although it was used with roles in the past, being able to add people directly to the groups makes that unappealing because it would just result in a bunch of extra config to have to maintain. And therefore, having the option to add roles is potentially not desirable.
3. Using this made me wonder if I even need this to be an access control feature. I don't think there is a problem with people modifying or deleting one another's content. Rather, I just need a way to present a certain subset of the content to the user when they log in so that they can focus on the content that they are responsible for.

I'll revisit this after the break.

Thanks for your work on this, @joewhitsitt!

**Comment by pyrello** [comment]
I'm fixing the conflicts, FYI.

**Comment by pyrello** [comment]
Getting #2623 merged will make resolving the conflicts in this a little more straightforward.

**Comment by joewhitsitt** [comment]
Moved back to draft until we decide what to do with this. This is all grad specific, so if it isn't needed we can close this PR.

**Comment by pyrello** [comment]
So, after some consideration, I think that we are not going to use this functionality in our D8 site. If we need this down the road, I think it will actually be good for us to consider it from a fresh perspective. Thanks for the work on this and sorry that it didn't end up getting used.

**Pull request closed without merging**
