### PR TITLE
P2LB updates

### LINKED ISSUE #5610: Investigate and clean up P2LB tracking issue
# Motivation
The issue at #3878 has gotten a bit unwieldy and parts of it are unclear as to what our next step should be.

# Proposed solution
- Set up the P2LB module locally and test its usage.
- Review the remaining bullet points and make note of any that are unclear.
- Clarify unclear bullet points with the team/original author.
- Test all incomplete items to ensure that they haven't been fixed.
- Create issues for any outstanding tasks and make sure they have enough detail that you would be able to know how to get started a year from now.

## Setup instructions
- `ddev blt ds --site hawkeyemarchingband.uiowa.edu` or another V2 site.
- `ddev drush rsync @hawkeyemarchingband.prod:%files @hawkeyemarchingband.local:%files`
- `ddev drush @hawkeyemarchingband.local uli admin/config/development/configuration/config-split`
- Enable P2LB split
- `ddev drush @hawkeyemarchingband.local cim`
- Visit converter tool at https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter

### LINKED ISSUE #5634: V2 - Allow articles to replicated
# Motivation

As part of #5610, it came to my attention that replication is not allowed for articles on V2 sites. I think this was based on the idea that we weren't adding new features for V2. However, the article content type is not a V2-specific feature and so I don't see any reason why we wouldn't allow this, especially since I don't think we have to add any custom code or change anything in our `sitenow_v2` config split to get this to work as expected.

# Proposed solution

Create an update hook that will update the `uiowa_core.settings:uiowa_core.replicate_allowed` setting for V2 sites to add the article content type.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5610 
Resolves #5634 

# How to test

- `ddev blt ds --site hawkeyemarchingband.uiowa.edu`
- `ddev drush @hawkeyemarchingband.local uli admin/config/development/configuration/config-split`
- Enable the P2LB split.
- `ddev drush @hawkeyemarchingband.local cim -y && ddev drush @hawkeyemarchingband.local cim -y`

## Articles allowed for replication in V2
- https://hawkeyemarchingband.uiowa.ddev.site/admin/config/development/configuration/single/export
- Select `uiowa_core.settings` under "Configuration name"
- Check that `article` is listed under `uiowa_core.replicate_allowed`.
- https://hawkeyemarchingband.uiowa.ddev.site/admin/content
- Find an article in the list, check that "Replicate" comes up under the operations drop-down for it.
- Click on the article title. Check that the "Replicate" tab displays. Click it
- Confirm that no messages displays and submit button is not disabled.
- Find a page in the list, check that "Replicate" comes up under the operations drop-down for it.

## Other updates
- https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-upgrader
- Click the "Edit" operation link
- Confirm that you can see a message about using the SiteNow Converter tool to convert the format of the page.
- Upgrade a page from v2 to v3, and check its revisions. Make sure the latest, "Converted page to v3" revision lists your user_id (whether your admin login, or masqueraded login), and not the page/article author.
- Confirm that you see a message that the page has been converted from the V2 format to the V3 format.
- Visit https://hawkeyemarchingband.uiowa.ddev.site/node/add/page and confirm that the Sections (Paragraphs) widget is not visible. Also confirm that

### CODE REVIEW

**Comment by cory-skeers** [comment]
Made a few small updates. One that I started but didn't get in place was including the user who converted (migraded?) the page on the "converted" view. Including the user of the latest revision is simple enough, but I'm less sure about making sure it's the user who actually did the conversion, and not just the latest revision user.

E.g. `user_1` converts a page, and is included in the revision. `user_2` makes an edit and/or publishes the page. Do we show `user_2` on this page, or `user_1`? My thought would be `user_1`, but I'm not sure how to do that in Views. 

We have the converted revision id on the node, so we could do it with a preprocess, but it feels like something that should be possible in Views if I were more views savvy.

**Comment by cory-skeers** [comment]
I think https://github.com/uiowa/uiowa/pull/5613/commits/41c9ff1fa95f358398ba54d5a9941d7bfed6ee88 and https://github.com/uiowa/uiowa/pull/5613/commits/21b1a80f471ba76d1b79fd8656a4816ba60406eb dropped a few extra Es ('upgrader' to 'convertr', 'upgraded' to 'convertd')

**Comment by pyrello** [comment]
> I think [41c9ff1](https://github.com/uiowa/uiowa/commit/41c9ff1fa95f358398ba54d5a9941d7bfed6ee88) and [21b1a80](https://github.com/uiowa/uiowa/commit/21b1a80f471ba76d1b79fd8656a4816ba60406eb) dropped a few extra Es ('upgrader' to 'convertr', 'upgraded' to 'convertd')

Good catch, @cory-skeers!

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and looks good to go 👍 

Really like the updates to the node edit page for users, and the extra work reconciling the ListBlock for our own sanity in testing!

**Pull request merged**
