### PR TITLE
[Articles] Pagination bug

### LINKED ISSUE #8049: Pagination issue causing the skipping of articles in /news
# Problem

During a content migration and audit for the Department of Pathology, I noticed that a single article that was migrated was not showing up in `/news` despite it existing in the system, being dated correctly, and showing up in taxonomy views.

# Steps to reproduce

1. Visit https://medicinepathology.prod.drupal.uiowa.edu/news
2. Go to page 9 -- note that the "**Iowa Association of Pathologists Award Winners from May 4, 2021**" is the last article on page 9.

Screenshot 2024-09-06 at 8 19 47 AM

3. Go to page 10 -- note that the same article is at the top of the page.

Screenshot 2024-09-06 at 8 24 12 AM

4. Go to May, 2021's filtered-by-date page: https://medicinepathology.prod.drupal.uiowa.edu/news/2021/05
5. Note that there are two articles from May, 2021 from the same day, but the article "**Steven Moore receives Impact Scholar award...**" is also in May 2021 listings, but does not show up on the main `/news` page.

Screenshot 2024-09-06 at 8 25 09 AM

This also seems to affect article list blocks, since you can see the same behavior on an article list block here:
https://medicinepathology.prod.drupal.uiowa.edu/news-events

# Proposed solution

Review any internal offsets used by the pagination system to ensure that we aren't skipping over items in a page.

As an enhancement, maybe figure out a way to adjust the URL when navigating through pages in order to retain back button functionality when navigating through the pagination. It was a bit of a challenge to write this issue when pagination was reset while using the web browser's back/forward navigation through the news section.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/8049. 

# How to test
```
ddev blt ds --site=pathology.medicine.uiowa.edu && ddev drush @medicinepathology.local uli /news 
```
- Review update hooks
   - Check views block update hook - is there a better way to do this for blocks?

1. Click on page 9 in the pager
2. Confirm `Iowa Association of Pathologists Award Winners` appears at the bottom
3. Click on page 10 in the pager and confirm that `Steven Moore receives Impact Scholar award April 27, 2021 from Dean Brooks Jackson` appears at the top of the list
4. Test against https://medicinepathology.uiowa.ddev.site/articles-block with same test as above. 
5.  Test newly exposed "Sort" filter for title in the block settings
6. Are there any downsides to adding this additional sort filter?

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I am glad you remembered...

93xblg

**Comment by bspeare** [comment]
This is ready to test.  In particular, I am wondering if anyone has any suggestions on how to make the update hooks here better.

**Comment by joewhitsitt** [comment]
I don't think we can update the list blocks like this because they can have custom sorts already by configuring the block:

Screenshot 2024-09-19 at 10 32 55 AM

If we wanted to do something, wouldn't we have to obtain the current sorts and just add the title to the end? I haven't pulled down yet. Do the blocks error if we don't update them?

**Comment by joewhitsitt** [comment]
I don't think we need sitenow_update_10012

https://sandbox.prod.drupal.uiowa.edu/node/1381/layout (changed the sort order and one of the asc/desc)

If we just update the views page and not the listblock, can we move it to docroot/modules/custom/sitenow_articles/sitenow_articles.install where we are doing similar updates?

**Comment by bspeare** [comment]
Thanks for the suggestions @joewhitsitt!

**Comment by bspeare** [comment]
> Do the blocks error if we don't update them?

The blocks don't error if we don't update them.  The block just needs to be resaved by the user to get the new title sort.

**Comment by joewhitsitt** [comment]
i don't know if we want to update all displays as they don't all have the same sorts currently. though I don't think it hurts anything, the block_articles_archive is a month by month display and wouldn't necessarily use this. i think feed_articles is already out of date with not having sticky sort but maybe that was by design.

Screenshot 2024-09-19 at 11 21 39 AM

do you want help with https://github.com/uiowa/uiowa/pull/8079#issuecomment-2361399517 ?

confirmed test instructions. re-saved config backend (admin/config/sitenow/uiowa-articles) and the page display was still sorted correctly. New site install also looks good for new list blocks and the page view page.

**Comment by bspeare** [comment]
@joewhitsitt I removed the block update hook and moved the hook to sitenow_articles and adjusted to target the `default` and `page_articles` display.

**Review by joewhitsitt — APPROVED** [review]
Thanks for this. Looks good. Sorry about the hoops you had to jump through.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
