### PR TITLE
Hotfix: Added a check for `class` member of attributes array to be an array

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

```
ddev blt ds --site usg.uiowa.edu && ddev drush @usg.local uli branches/legislative-branch/constituency-senators
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
The deployment finished and seems to have resolved the underlying issue. Is this still something worth adding in?

**Comment by pyrello** [comment]
> The deployment finished and seems to have resolved the underlying issue. Is this still something worth adding in?

On the one hand, this seems like a pretty obvious way to prevent issues in the future. On the other hand, this failing would seem to indicate a problem that we need to look into and so implementing this fix means that we won't get that feedback.

**Comment by cory-skeers** [comment]
> > The deployment finished and seems to have resolved the underlying issue. Is this still something worth adding in?
> 
> On the one hand, this seems like a pretty obvious way to prevent issues in the future. On the other hand, this failing would seem to indicate a problem that we need to look into and so implementing this fix means that we won't get that feedback.

My initial thought is to log a message in the event it's getting skipped over, so that we can avoid the wsod but still get that feedback. But I worry that'll just end up being noise.

**Comment by pyrello** [comment]
I think it was a mistake to design this method so that it gets passed the `$attributes` array when all we care about is updating the `$attributes['class']`. Ideally, it should be rewritten so that it gets passed `$attributes['class']` instead.

**Comment by pyrello** [comment]
Closing this in favor of a potential rewrite of the affected functionality down the road.

**Pull request closed without merging**
