### PR TITLE
WhitmanWeb Setup

### LINKED ISSUE #3868: WhitmanWeb - Add writing content type with translation enabled
# Motivation

As a follow-up to #3867, we need to actually implement the recommendations that come out of that investigation.

# Stories

* As a content editor for WhitmanWeb, I can publish pages with separate URLs for each translated version of a piece of content.
* As a content editor, I can group pieces of writing together in a collection and control the order in which they display.
* As a visitor to WhitmanWeb, I can choose which language I want to view the site in.

# Proposed solution
* [x] Add site split.
* [x] Enable content translation and language switching modules for the site and add to the site split.
* [x] Place language switching UI and add block changes to site split.
* [x] Add Writing content type (see definition below)
* [x] Document process for adding/editing translated content.
* [ ] Add writing collection either using taxonomy or a separate content type.
* [ ] Figure out how to handle translating field labels.
* [ ] Add translations for all field labels.

## Writing content type definition
- [x] Title - built-in
- [x] Featured Image - use existing field
- [x] Featured Audio - multi-value media field restricted to audio media type
- [x] Foreword - text area (minimal)
- [x] Content - multi-value text area (minimal)
- [x] Afterword - text area (minimal)
- [x] Question - text area (minimal)

Note: for now we are not adding fields for Section Number and Category, or the Previous and Next buttons, as the menu should cover it. They may need to be added down the road if the menu isn't sufficient.

### PR DESCRIPTION
**Pull request by pyrello**
Replaces #4043 
Resolves #3868 

# How to test

- `ddev blt ds  --site=whitmanweb.iwp.uiowa.edu`
- `ddev drush @iwpwhitmanweb.local en content_translation`
- `ddev drush @iwpwhitmanweb.local cim --source ../config/sites/whitmanweb.iwp.uiowa.edu --partial`
- `ddev drush @iwpwhitmanweb.local cim`
- `ddev drush @iwpwhitmanweb.local cr`

# Story
As a WhitmanWeb user, I can add a piece of writing content.
As a WhitmanWeb user, I can add translations for a piece of writing content in multiple languages.
As a WhitmanWeb user, I can add translations for a writing collection vocabulary term.

### Translating Writing content
* Create a Writing item and save.
* Click the "Translate" tab.
* Under the desired language, click Add/Edit to work on translation for another language.
* Make changes and save.
### Translating Writing Collection terms
* Visit the Writing Collection and click the "Translate" tab.
* Under the desired language, click Add/Edit to work on translation for another language.
* Make changes and save.

### CODE REVIEW

**Comment by pyrello** [comment]
Going to merge this to dev to allow the client to check it out and make sure they think it will work.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by pyrello** [comment]
Ope. Just realized I didn't set up permissions that would allow the site owners to test this on dev.

**Comment by joewhitsitt** [comment]
As a webmaster, I can create writing content but none of the translation related stories.

Not sure if these are part of the slice but:
As a webmaster I don't have any publishing/moderation control.
As a webmaster I can't fine-tune writing content seo settings and the node does not appear in sitemap.xml

I want to test on another site but wanted to get this feedback out.

**Comment by pyrello** [comment]
Permissions updated. Thanks for the reminder on these other content type features, @joewhitsitt. I'm going to get confirmation from client that they are okay with this approach and then I'll add those other items.

**Comment by joewhitsitt** [comment]
So I understand that you are getting initial approval from the customer, but I think this should be switched back to draft in terms of technical approval/merge. Introducing this language stuff to default that we are going to have config diff issues for things not in the default. Some examples:

Config diff import errors on sitenow_v2:
```
core.entity_view_display.media.image.edgy  
core.entity_view_display.media.image.image_large
core.entity_view_display.media.image.image_medium
core.entity_view_display.media.image.image_small
core.entity_view_display.media.image.sitenow_16_9
core.entity_view_display.node.page.default
```

Config diff import errors on admissions:
```
core.entity_form_display.block_content.area_of_study_search.default     
core.entity_form_display.fragment.stat.default                          
core.entity_form_display.node.area_of_study.default                     
core.entity_form_display.node.event.default                             
core.entity_form_display.node.event_series.default                      
core.entity_form_display.node.person.default                            
core.entity_form_display.node.person.minimal                            
core.entity_form_display.node.scholarship.default                       
core.entity_form_display.node.student_profile.default                   
core.entity_form_display.node.transfer_tips.default                     
core.entity_form_display.taxonomy_term.academic_groups.default          
core.entity_form_display.taxonomy_term.colleges.default                 
core.entity_view_display.aggregator_feed.aggregator_feed.default        
core.entity_view_display.aggregator_feed.aggregator_feed.summary        
core.entity_view_display.aggregator_item.aggregator_item.summary        
core.entity_view_display.block_content.area_of_study_search.default     
core.entity_view_display.block_content.uiowa_banner.default             
core.entity_view_display.block_content.uiowa_card.default               
core.entity_view_display.block_content.uiowa_cta.default                
core.entity_view_display.block_content.uiowa_event.default              
core.entity_view_display.block_content.uiowa_hero.default               
core.entity_view_display.block_content.uiowa_image_gallery.default      
core.entity_view_display.block_content.uiowa_page_title_hero.default    
core.entity_view_display.block_content.uiowa_slider.default             
core.entity_view_display.block_content.uiowa_spacer_separator.default   
core.entity_view_display.block_content.uiowa_statistic.default          
core.entity_view_display.block_content.uiowa_text_area.default          
core.entity_view_display.fragment.stat.default                          
core.entity_view_display.node.area_of_study.default                     
core.entity_view_display.node.area_of_study.pdf                         
core.entity_view_display.node.area_of_study.teaser                      
core.entity_view_display.node.article.teaser                            
core.entity_view_display.node.event.default                             
core.entity_view_display.node.event.teaser                              
core.entity_view_display.node.event.token                               
core.entity_view_display.node.event_series.default                      
core.entity_view_display.node.event_series.teaser                       
core.entity_view_display.node.page.default                              
core.entity_view_display.node.page.pdf                                  
core.entity_view_display.node.page.teaser                               
core.entity_view_display.node.person.default                            
core.entity_view_display.node.person.token                              
core.entity_view_display.node.scholarship.default                       
core.entity_view_display.node.scholarship.teaser                        
core.entity_view_display.node.student_profile.default                   
core.entity_view_display.node.student_profile.teaser                    
core.entity_view_display.node.transfer_tips.default                     
core.entity_view_display.node.transfer_tips.teaser                      
core.entity_view_display.paragraph.admissions_card.default              
core.entity_view_display.paragraph.degree.default                       
core.entity_view_display.paragraph.uiowa_contact.default                
core.entity_view_display.paragraph.uiowa_slide.default                  
core.entity_view_display.taxonomy_term.academic_groups.default          
core.entity_view_display.taxonomy_term.academic_groups.teaser           
core.entity_view_display.taxonomy_term.colleges.default                 
```

**Comment by pyrello** [comment]
Thanks for checking that, @joewhitsitt. I had not yet thought about the impact on existing splits, which will be extensive. Maybe we need to talk through this a bit more.

**Comment by pyrello** [comment]
Another idea for getting around the issue I ran into with enabling the `language` module and its conflict with config would be to turn it on in production, then export to a site split based on that. We could do a PR that just involves turning that module on for WhitmanWeb, then follow-up with this to add the rest of the functionality. I think if the module is already installed, then there won't be a problem with the UUID not matching. However, we would need to do something similar for any other site that we were going to turn that module on for.

**Comment by pyrello** [comment]
@richardbporter The build is failing because it is complaining that `language.negotiation` is different. As far as I can tell it is not. When I try to sync the default site, I am getting an error that the prod server is unavailable, so I'm not about to do that currently to try to resolve it.

**Comment by richardbporter** [comment]
Taking a look...

**Comment by richardbporter** [comment]
I added a step (a full import) after doing the partial import to the PR description. I also had to export the site split again to re-sort it - I was seeing "stuck" config trying to sync the site.

**Comment by pyrello** [comment]
> I added a step (a full import) after doing the partial import to the PR description. I also had to export the site split again to re-sort it - I was seeing "stuck" config trying to sync the site.

Thanks! That was probably one step beyond what was needed, since I basically just needed it to build for `develop`, but good to have it done either way!

**Comment by pyrello** [comment]
Going to merge this as soon as I get an approval on it. We will do any follow up work in an additional PR

**Comment by pyrello** [comment]
Removing from the board but keeping for now in case its useful.

**Comment by pyrello** [comment]
Closing this because WhitmanWeb is launching without customizations.

**Pull request closed without merging**
