### PR TITLE
Catch type error in moderation state messaging viewing old revisions

### PR DESCRIPTION
**Pull request by joewhitsitt**
Remove moderation message as it is causing errors like:
```
drupal-watchdog web-33202 Mar 26 16:03:19 web-33202 uiowa01[4634]: https://coronavirus.uiowa.edu|1585238599|php|72.168.160.15|https://coronavirus.uiowa.edu/node/66/revisions/1236/view|https://coronavirus.uiowa.edu/node/66/revisions|81||Error: Call to a member function getRevisionId() on string in sitenow_preprocess_page() (line 549 of /mnt/www/html/uiowa01/docroot/profiles/custom/sitenow/sitenow.profile) 
```

### CODE REVIEW

**Comment by cory-skeers** [comment]
I moved up the moderation message so that the $node gets checked prior to calling for it's revision id. This should catch the fatal error without taking out the message on nodes that wouldn't have hit the fatal error.

**Comment by joewhitsitt** [comment]
I just checked this locally. nice fix. can't officially approve this PR as I started it.

**Comment by richardbporter** [comment]
Can someone update the PR title to summarize the changes? Thanks.

**Review by cory-skeers — APPROVED** [review]

**Comment by richardbporter** [comment]
👍

**Pull request merged**
