### PR TITLE
Event split: Attendance Required Field

### LINKED ISSUE #6469: Attendance required for events
# Story

As a SiteNow events creator, I would like to be able to designate if attendance is required for events on our website since so participants of OnIowa events know which events are mandatory.

# Additional Information

- Boolean field (Yes/No) to designate if attendance is required
- Output on full node
- Should we output on teaser? They will have the ability to filter based on this value in a future slice so I am not sure if it is needed. Their current site has an asterisk before the event title on the event search page https://web.archive.org/web/20220815131834/https://oniowa.uiowa.edu/events

# Proposed Solution

- [x] Add boolean
- [x] Output on full node
- [ ] Output on teaser?

### PR DESCRIPTION
**Pull request by makurj**
Resolves #6469

# How to test

```
ddev blt ds --site=iowasummerwritingfestival.uiowa.edu && ddev blt ds --site=oniowa.uiowa.edu && ddev blt ds --site=admissions.uiowa.edu && ddev drush @iowasummerwritingfestival.local uli node/add/event && ddev drush @oniowa.local uli node/add/event && ddev drush @admissions.local uli node/add/event
```
- Review code and verify that enough defensive checks are in place so that an update hook is unnecessary. 
- Verify that the new "Attendance Required" field is available on all of the above sites. 
- Verify that checking the box will render an "Attendance Required" badge on the full event node and the /events teaser list for oniowa and iowasummerwriting festival.
- Verify that the event status badge has moved to the bottom of the card to display inline with the  "Attendance Required" badge 
- Test all fields and their teaser and full page display on oniowa, admissions, and iowasummerwriting festival to check for regressions like https://github.com/uiowa/uiowa/pull/6495.

### CODE REVIEW

**Comment by makurj** [comment]
Thanks @bspeare for all your help with this!

**Comment by cory-skeers** [comment]
Going to pull down and test

**Review by cory-skeers — APPROVED** [review]
Works great! Tested on each of the three sites--functionality works as expected for existing events without a value in place, and is consistent/up-to-date across full node and teaser displays.

Didn't find any regressions, and from the code review, everything looks good. Kept seeing the removal of the iswf registration link and thinking it was an error, but is moved slightly within the config file.

**Comment by bspeare** [comment]
Thanks @cory-skeers!

**Pull request merged**
