### PR TITLE
Feature: Add config to collegiate sites

### PR DESCRIPTION
**Pull request by pyrello**
Addresses the issue of sites not having config.

### CODE REVIEW

**Comment by pyrello** [comment]
@mark-bennett-uiowa We'll need to add config for your two sites. We can go over that and add them to this PR when we get together later today.

**Comment by richardbporter** [comment]
This resolves #1040 - collegiate should use `core-only` strategy until ready to adopt config_split which is the default BLT strategy. Otherwise, config_split gets enabled during the drupal:update process.

**Comment by richardbporter** [comment]
I am able to `blt dsa` all collegiate sites without error on the CLI. Was #1040 showing up on the CLI or in the Drupal admin interface?

**Comment by pyrello** [comment]
@richardbporter In the CLI. I think that uninstalling those modules on `@gradcogscilang` fixed that issue.

**Review by richardbporter — APPROVED** [review]
Assuming CI passes, I think this is good to go. 👍

**Comment by richardbporter** [comment]
We can check out master-build in stage on uiowa01 once this is merged.

**Pull request merged**
