### PR TITLE
Update core to 9.1.11

### PR DESCRIPTION
**Pull request by richardbporter**
Had to update the patch added in https://github.com/uiowa/uiowa/pull/3249.

### Testing
- `composer install`
- `blt dsa` some sites. Poke around.
- Maybe test #3249?
- Maybe test ListBlock on sandbox?

### CODE REVIEW

**Comment by richardbporter** [comment]
Noticed my plugin PR was whitescreening on this. Got some errors in `composer install`. Wonder if I goofed something up...

**Comment by joewhitsitt** [comment]
WAT

**Comment by joewhitsitt** [comment]
trying this

no blt issues
https://admissions.local.drupal.uiowa.edu/areas-of-study worked fine.
people list block using research areas and person type worked fine (default site)
cex on default returned identical

**Review by joewhitsitt — APPROVED** [review]

**Comment by joewhitsitt** [comment]
Though I approved @richardbporter, I am curious what you ran into and if I should be concerned...

**Comment by richardbporter** [comment]
I was seeing this on `composer install`:
```
- Downgrading nikic/php-parser (v4.12.0 => v4.10.5): Extracting archive
  - Downgrading pear/archive_tar (1.4.14 => 1.4.13): Extracting archive
    Update of drupal/core failed
  - Downgrading sebastian/type (2.3.4 => 2.3.2): Extracting archive
  - Downgrading phar-io/manifest (2.0.3 => 2.0.1): Extracting archive
  - Downgrading phpunit/phpunit (9.5.7 => 9.5.5): Extracting archive
  - Downgrading mikey179/vfsstream (v1.6.9 => v1.6.8): Extracting archive
  - Downgrading doctrine/cache (1.12.1 => 1.11.3): Extracting archive
  - Downgrading drupal/core-recommended (9.1.11 => 9.1.9)
 7/7 [============================] 100%
                                                  
  [InvalidArgumentException]                      
  Package is not installed: drupal/core-9.1.11.0  
                                                  ```

**Comment by richardbporter** [comment]
I removed `docroot/core` and ran `composer clearcache` and tried again. All good this time. 👍🏻

**Pull request merged**
