### PR TITLE
Allow up to three links in banner.

### LINKED ISSUE #2404: Change banner link field settings to allow for 3 links to be added for button rows
# Problem

The current banner block only allows for one banner link button to be placed within the block. 

# Proposed Solution

Change the banner link field to allow up to 3 links to be placed within a banner block. 

## Next steps

- Change banner_link field to allow multiple links
- Adjust banner template in `uids_base`
- If necessary, adjust UIDS component to allow for a button row: https://uids.brand.uiowa.edu/components/detail/banner--default.html
- If necessary, adjust UIDS js https://github.com/uiowa/uids/blob/main/src/components/banner/banner.js to change accessible link strategy.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2404 

Depends on https://github.com/uiowa/uids/pull/412.

### Testing
- Sync a site on this branch.
- Add a banner with:
  - No links
  - One link
  - More than one link
  - Different layout builder styles
- Review:
  - Link field label change
  - Link field description change (related to #2513)
  - Banner template changes

### ToDo
- [x] Remove uiowa/uids feature branch lock.

### CODE REVIEW

**Comment by dnkemper** [comment]
Can see if my computer will let me test this

**Comment by dnkemper** [comment]
Only thing that isn't working for me is the three links styling. If third overlaps, there's not a clear separation
Screen Shot 2020-12-01 at 3 33 59 PM

**Comment by richardbporter** [comment]
Thanks. Does `blt frontend` fix that?

**Comment by dnkemper** [comment]
I can try a third time to triple check...

**Comment by dnkemper** [comment]
It doesn't fix it for me :(

**Comment by bspeare** [comment]
@dnkemper I was just working on updating this styling.  I will see if the update fixes that.

**Comment by dnkemper** [comment]
@bspeare awesome! Thank you!

**Comment by bspeare** [comment]
The pr doesn't seem to be updating with the latest version of https://github.com/uiowa/uids/pull/412.   @richardbporter Do you mind if I change https://github.com/uiowa/uiowa/blob/three-but-not-four-links/docroot/themes/custom/uids_base/package.json#L6 to pull in the pr hash?

**Comment by richardbporter** [comment]
No. I haven't been able to execute the Yarn commands to do that because then my computer crashes.

**Comment by dnkemper** [comment]
@richardbporter RELATABLE

**Comment by bspeare** [comment]
I'll give it a shot :).

**Comment by bspeare** [comment]
It looks like I need to fix another issue for with the buttons.  I'll do that first thing tomorrow morning.

**Comment by dnkemper** [comment]
@bspeare I'll approve it in the mean time because looks good to me :)

**Review by dnkemper — APPROVED** [review]

**Comment by richardbporter** [comment]
I think this is blocked by uiowa/uids#412.

**Comment by pyrello** [comment]
Setting this to 'draft' in the meantime so it doesn't accidentally get merged.

**Comment by pyrello** [comment]
Reviewed the template structure and this all looks good to me!

**Comment by bspeare** [comment]
@cory-skeers the update works great!   

@richardbporter one thing that I am noticing is that the links are being rendered as `<a href="entity:node/96">`.  Is there a setting that we need to adjust to get the correct url?

**Comment by richardbporter** [comment]
Good catch. That should be fixed now.

**Comment by bspeare** [comment]
One more issue with the new links.   It looks like we lost the ability to add a link without a button.   Did we remove that from the template structure?  Does `{% if link.link_text is not empty %}` need to be added back in?

Screen Shot 2020-12-02 at 2 19 44 PM

**Comment by bspeare** [comment]
Looks like we also need to update the Slider templates to work with the new link implementation in the template:

- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/uids/slider--slide.html.twig
- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/paragraphs/paragraph--uiowa-slide.html.twig

Screen Shot 2020-12-02 at 2 23 27 PM

**Comment by bspeare** [comment]
I can add a fix for https://github.com/uiowa/uiowa/pull/2609#issuecomment-737472696.

**Comment by pyrello** [comment]
This is now blocked by #2545. There are updates in that PR that are needed to be able to roll with the updated version of UIDS. I'm not going to make those same changes in this PR. After we get #2545 merged, I'll get this updated.

**Comment by pyrello** [comment]
It looks like the slider issue has been resolved as well. As far as I can tell, there are no more outstanding (reported) issues to resolve.

**Comment by bspeare** [comment]
Remaining tasks:
- [x] Change this to only apply to `card` and `banner`: https://github.com/uiowa/uiowa/blob/8b22467cf7cdd58906bcab2afba5c950b9c465af/docroot/themes/custom/uids_base/templates/uids/headline.html.twig#L2
- [x] Update with new UIDS release

**Comment by GaryRidgway** [comment]
I will pull this down now to test tomorrow

**Comment by GaryRidgway** [comment]
I am currently not seeing the ability to link the entire banner without a link, and the banner is not being linked with one link. Where would i look to enable those settings?

**Comment by pyrello** [comment]
It's long enough since I worked on this that I don't remember what I tested and checked. I will pull this down in a little bit and take a look.

**Comment by bspeare** [comment]
@GaryRidgway Are you able to leave the link text empty?

**Comment by GaryRidgway** [comment]
@bspeare  I am, and it did not link the banner.

**Review by bspeare — APPROVED** [review]
It works!

**Comment by GaryRidgway** [comment]
It works x2!

**Pull request merged**
