### PR TITLE
Feature: work to integrate card updates from UIDS

### LINKED ISSUE #3416: As a developer, I can integrate card style changes from UIDS and see them work in all `v2` and `v3` sites
# Story

As a developer, I can integrate card style changes from UIDS (https://github.com/uiowa/uids/pull/533) and see them work in all `v2` and `v3` sites

# Proposed solution

Test and integrate changes from https://github.com/uiowa/uids/pull/533 on `v2` and `v3` sites.

### PR DESCRIPTION
**Pull request by bspeare**
This pr contains work to integrate the work from https://github.com/uiowa/uids/pull/533 into `uids_base`. 

Resolves https://github.com/uiowa/uiowa/issues/3416. 

# How to test

```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
yarn workspace admissions_core build
```

1. Test on all 6 of the card-based pages linked on https://sandbox.local.drupal.uiowa.edu/card-and-event-background-testing, view on desktop and mobile and look for any visual regressions. 
2. Test on a `v2` site like https://hawkeyemarchingband.local.drupal.uiowa.edu/people-0.  Try adding articles, events, and featured content to that page and test mobile and desktop views. 
3. Test on https://admissions.local.drupal.uiowa.edu/academics/actuarial-science and verify that the "Admission Process" card images remain small on mobile. 
4. Test mobile and desktop versions of https://admissions.local.drupal.uiowa.edu/counselors and verify that circle image remains the same size on desktop and mobile. 
5. Test mobile and desktop versions of https://admissions.local.drupal.uiowa.edu/student-profiles and verify that circle image remains the same size with spacing inside the enclosed card. 
6. Test mobile and desktop views of https://grad.local.drupal.uiowa.edu/academics/thesis-defenses/list, https://grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2019, https://grad.local.drupal.uiowa.edu/dei/srop/mentors

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
also tested on ighn.international's non-person content type

**Comment by joewhitsitt** [comment]
Actually, forgot to mention, I didn't see images here: https://grad.local.drupal.uiowa.edu/academics/thesis-defenses/list

**Comment by bspeare** [comment]
@joewhitsitt Thanks!  Are there supposed to be images? https://grad.uiowa.edu/academics/thesis-defenses/list.

**Comment by joewhitsitt** [comment]
Just following step 6. not sure what i was supposed to test there

**Comment by bspeare** [comment]
@joewhitsitt Good point!

**Comment by bspeare** [comment]
Moving this back to draft until I can update this with the final UIDS release/commit.

**Comment by pyrello** [comment]
Thesis defense items don't have images, FYI.

**Pull request merged**
