### PR TITLE
Revert "Added .htaccess redirect for www.(cs|math|stat).uiowa.edu/~ to homepage.divms.uiowa.edu/~."

### PR DESCRIPTION
**Pull request by richardbporter**
Reverts uiowa/uiowa#3879

### CODE REVIEW

**Comment by richardbporter** [comment]
Forgot we need to update the patch file along with this. Just gonna revert for now.

**Comment by mark-bennett-uiowa** [comment]
@richardbporter Dang, I knew I was forgetting something. Could you show me this file so I dont forget about it in the future?

**Review by mark-bennett-uiowa — APPROVED** [review]
Yes, revert until patch file updated.

**Comment by richardbporter** [comment]
Yea its in the https://github.com/uiowa/uiowa/tree/main/patches directory.

**Pull request merged**
