### PR TITLE
Move uiowa_bootstrap to docroot/themes/custom.

### PR DESCRIPTION
**Pull request by richardbporter**
So it is tracked in the repo.

### CODE REVIEW

**Comment by richardbporter** [comment]
I'm looking into frontend asset compilation with BLT.

**Comment by richardbporter** [comment]
Nevermind. I'll follow up later with that.

**Comment by joewhitsitt** [comment]
the updb didn't do the trick. HR says `Base theme uiowa_bootstrap has not been installed.`

**Comment by richardbporter** [comment]
HR does not seem to have any problems with the theme living in docroot/themes/custom.  

@joewhitsitt You good with this?

We may want to take a similar approach to modules, eventually. #174

**Review by joewhitsitt — APPROVED** [review]
Changed HR uiowa_bootstrap paths back. I think this is good to go.

**Pull request merged**
