### PR TITLE
Feature mega menu

### PR DESCRIPTION
**Pull request by bewoldt**
Styles the Mega Menu option to expose the 3rd level menu links.

Notes:
It looks like there might be some missing JS that needs to be added. On the mobile accordion menu, the 3rd level ul's are missing the class of .sf-hidden. There is some filler css to fix this.

# How to test

- Review the code changes
  - We have refactored the menu SCSS into separate partials for maintainability.  Please test out all three menu options in the theme settings and verify that they are working as expected. 

```
ddev blt ds --site=nursing.uiowa.edu
yarn workspace uids_base build
ddev drush @nursing.local uli /admin/appearance/settings/uids_base
```
Change navigation style to Mega Menu:

Screen Shot 2021-12-22 at 12 04 39 PM

- Try tabbing through the mega navigation and look for any accessibility issues. 

**There is an issue for the mobile view that we are hiding with CSS.  Without it, hovering over the menu shows the expanded menu like in the screenshot below:**

Screen Shot 2021-12-21 at 11 11 16 AM

### CODE REVIEW

**Comment by bspeare** [comment]
Notes from the web community meeting today:

- Check if tabbing through the mega menu works as expected for accessibility
- Change the font size to `1.1rem` or `1rem` to make the visual hierarchy from the main menu links better?

Screen Shot 2021-12-03 at 2 37 48 PM

- Use `auto-fit` or `auto-fill`?

**Auto fit**:

Screen Shot 2021-12-03 at 2 42 04 PM

**Auto fill:**

Screen Shot 2021-12-03 at 2 41 49 PM

**Comment by GaryRidgway** [comment]
I can test this

**Review by GaryRidgway — APPROVED** [review]
menu types work as expected and tabbing of megamenu works as expected

**Comment by bspeare** [comment]
Just noticed an issue with this menu and iPads, I'm going to move this back to draft.

**Comment by bspeare** [comment]
I changed the sf-touchscreen settings so that it doesn't add a cloned menu link into the mega menu.  Instead, you have to tap to open the menu on a touch device and tap it again to go to the parent page. 

Before:

Screen Shot 2022-01-04 at 1 15 12 PM

After:

Screen Shot 2022-01-04 at 1 17 56 PM

Screen Shot 2022-01-04 at 1 19 54 PM

**Review by GaryRidgway — APPROVED** [review]
Tested on browser stack and Ben's new changes are working!

**Comment by bspeare** [comment]
Thanks @GaryRidgway!

**Pull request merged**
