### PR TITLE
facilities post launch

### LINKED ISSUE #7607: Facilities post launch updates
**Art**
- Have "Status" filter default to "Active" on Art on Campus Gallery - https://facilities.uiowa.edu/art-campus/art-campus-gallery
- Move "Status" filter below "Medium"
- Remove artist photo
  - Probably need to move the Artist website link as well
  - https://github.com/uiowa/uiowa/issues/6588
- Change the order of info on the individual art page:
  - Artist (1st)
  - Artist website (2nd)
  - Building (3rd)
  
**Building Information Pages**
- On the [Building Information webpage](https://facilities.uiowa.edu/buildings), previously, when you typed a building acronym or name, it would start to populate the search and you could click on the building instead of continuing to type. Could this feature be re-implemented?

**Alerts**
- They would like to grant collaborators the ability to edit and delete any alert rather than just edit and delete own alerts.
```[tasklist]
### Tasks
- [x] Investigate setting a default filter value on the gallery view
- [x] Adjust display settings from the IS above
- [x] Adjust the display settings for person on Facilities only to remove the person photo. Account for any remaining fields in the sidebar
- [x] Change the order of info on the individual art page
- [x] Buildings view should autosubmit
- [x] Update permissions for alerts so that collaborator role can edit/delete any alert
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
tracks https://github.com/uiowa/uiowa/issues/7607

## To test

- Code review

```
ddev blt frontend && ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli /art-campus/art-campus-gallery
```

1. Sync site
2. [Go here and](https://facilities.uiowa.ddev.site/art-campus/art-campus-gallery) see that the `Status` filter is autopopulated with `Active`, and that the view is autofiltered.
3. Also observe on that same page that the `Status` filter is at the bottom of the filter list.
4. Go find an artist and check that the photo is gone, and that the website is moved under the birth/death year fields.
    - Also checking the content type display page would be good to make sure that the sidebar is completely removed, and all fields no longer sit in a different section away from the website.
5. Go to a piece of art, and observe that the following fields are in the following order:
    - Artist (1st)
    - Artist website (2nd)
    - Building (3rd)
6. [Go here and](https://facilities.uiowa.ddev.site/buildings) see that the filter now autosubmits.
7. Masquerade as a collaborator and check that you can now delete and edit any alert.

## Icon updates

`fa-ul` and `fa-li` classes have been replaced by the `fa-field-item` wrapper class and targeted CSS for positioning the font awesome icon absolutely outside of the field text.  Percy shows that events, article, people teasers are the same but click through any other icon heavy sites like classrooms or alert teasers if you want to test this out further.  

## Person field label updates

Person field labels have been updated to be visually hidden.  You should see a number of updates to `core.entity_view_display.node.person.default.yml` here.

### CODE REVIEW

**Comment by bspeare** [comment]
This is ready for review again.

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
I discussed with @bspeare that the icons on the classrooms website are a little off in their positioning and he is going to try to fix it.

**Review by pyrello — APPROVED** [review]
Tested and looks good. Thanks!

**Pull request merged**
