### PR TITLE
Uninstall `node_view_permissions` mode, add `private_content` module to SPPA split

### PR DESCRIPTION
**Pull request by pyrello**
- Resolves #3925 
- Adds an update hook that attempts to pull in all the updated config related to roles and then rebuilds node access with the hopes of preventing any access denied messages being shown to users.

# How to test
Compare file changes against https://github.com/uiowa/uiowa/pull/3833 to see that all the `view any...` and `view own...` content type permissions have been removed. This excludes `view any unpublished` or `view any webform submissions`.

## Default
`blt ds`

### Stories
- As an editor, publisher, and webmaster, I can create and edit article, page, and person content.
- As an anonymous user, I am able to view published article, page, and person content.

## Admissions
`blt ds --site brand.uiowa.edu`

### Stories
- As an editor, publisher, and webmaster, I can create and edit area of study, event, scholarship, student profile, and transfer tips content.
- As an anonymous user, I am able to view published area of study, event, scholarship, student profile, and transfer tips content.

## Brand
`blt ds --site brand.uiowa.edu`

### Stories
- As a collaborator, I am able to create lockup content.
- As a collaborator, I am able to edit my own lockup content.
- As an editor, I am able to move lockup content from "Draft" to "Needs review."
- As a publisher, and webmaster, I am able to approve and publish lockup content.

## Grad
`blt ds --site grad.uiowa.edu`

### Stories
- As an editor, publisher, and webmaster, I am able to create and edit mentor, scholar, scholarship (fellowship), student profile, and thesis defense content.
- As an anonymous user, I am able to view published mentor, scholar, scholarship, student profile, and thesis defense content.

## HR
`blt ds --site hr.uiowa.edu`

### Stories
- As an editor, publisher, and webmaster, I am able to create and edit FAQ content.
- As an anonymous user, I am able to view published FAQ content.

## IGHN
`blt ds --site ighn.international.uiowa.edu`

### Stories
- As an editor, publisher, and webmaster, I am able to create and edit ighn person content.
- As an anonymous user, I am able to view published ighn person content.

## CLAS Policy
`blt ds --site policy.clas.uiowa.edu`

### Stories
- As an editor, publisher, and webmaster, I am able to create and edit book content.
- As an anonymous user, I am able to view published book content.

## SPPA
`blt ds --site sppa.uiowa.edu`

### Stories
- As a site owner/editor, I can choose to make a page "private" (under Promotion options) and it can only be seen by editors, publishers, students, and webmasters.
- As an anonymous, authenticated, requester, and viewer, I am not able to view opportunity content or https://sppa.local.drupal.uiowa.edu/opportunities

### CODE REVIEW

**Comment by pyrello** [comment]
I'm going to add some logic to the update hook to check all the splits that are turned on and see if any of them include role config updates.

**Comment by richardbporter** [comment]
Haven't tested this yet but I would be in favor of this approach over #3925 since it lets people make existing pages private/public without having to move content manually to another content type.

**Comment by GaryRidgway** [comment]
pulling to test, I have roped in @cory-skeers to help because there are a lot of things to test.

## Default
The stories listed seem to be true.

## Admissions
The stories listed seem to be true, except that the event content type has no publishing options for any role.

## Brand
Collaborator permissions look good.

> As an editor, publisher, and webmaster, I am able to approve and publish lockup content.

Publisher and webmaster are able to approve and publish, but editor is only able to move between draft and needs review.

## Grad
Mentor seems to not be working, I am getting this white-screen error even filling out the un-required title field

<details>
<summary>Expand Bug Code</summary>
<div>

```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null: INSERT INTO {node_field_data} ("nid", "vid", "type", "langcode", "status", "uid", "title", "created", "changed", "promote", "sticky", "default_langcode", "revision_translation_affected") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12); Array ( [:db_insert_placeholder_0] => 6935 [:db_insert_placeholder_1] => 37710 [:db_insert_placeholder_2] => mentor [:db_insert_placeholder_3] => en [:db_insert_placeholder_4] => 1 [:db_insert_placeholder_5] => 1 [:db_insert_placeholder_6] => [:db_insert_placeholder_7] => 1629233124 [:db_insert_placeholder_8] => 1629233124 [:db_insert_placeholder_9] => 0 [:db_insert_placeholder_10] => 0 [:db_insert_placeholder_11] => 1 [:db_insert_placeholder_12] => 1 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 810 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
Drupal\Core\Database\StatementWrapper->execute(Array, Array) (Line: 823)
Drupal\Core\Database\Connection->query('INSERT INTO {node_field_data} ("nid", "vid", "type", "langcode", "status", "uid", "title", "created", "changed", "promote", "sticky", "default_langcode", "revision_translation_affected") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12)', Array, Array) (Line: 98)
Drupal\Core\Database\Driver\mysql\Connection->query('INSERT INTO {node_field_data} ("nid", "vid", "type", "langcode", "status", "uid", "title", "created", "changed", "promote", "sticky", "default_langcode", "revision_translation_affected") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12)', Array, Array) (Line: 32)
Drupal\Core\Database\Driver\mysql\Insert->execute() (Line: 1011)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->saveToSharedTables(Object) (Line: 949)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->doSaveFieldItems(Object) (Line: 622)
Drupal\Core\Entity\ContentEntityStorageBase->doSave(NULL, Object) (Line: 452)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 801)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object) (Line: 339)
Drupal\Core\Entity\EntityBase->save() (Line: 270)
Drupal\node\NodeForm->save(Array, Object)
call_user_func_array(Array, Array) (Line: 113)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('node_mentor_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object) (Line: 39)
Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 706)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

</div>
</details>

The Profile content type has no published/unpublished state selection options.

Editors can do all things stated in the story, save the mentor issue above.
Publishers can only add Articles, Fellowships, Page, and Person content types.
Webmasters can do all things stated in the story, save the mentor issue above.

## HR

Stories listed check out.

## IGHN

Stories listed check out.

## CLAS Policy

Stories listed check out.

## SPPA

Stories listed check out.

**Comment by pyrello** [comment]
Thanks for all the testing on this, @GaryRidgway and @cory-skeers!

Re: the branding permissions, I may have gotten the details wrong on that. I wouldn't mind a double check from @joewhitsitt, when he is feeling up to it :)

**Comment by pyrello** [comment]
I'm taking a look at the issues with Grad.

**Comment by pyrello** [comment]
@GaryRidgway I think I have fixed the issue related to the mentor form not working. The title field wasn't being filled in correctly with the mentor's first and last name prior to save (as happens with the scholar). I think that was causing the duplicate entry issue.

**Comment by pyrello** [comment]
@GaryRidgway I have updated the brand stories above. I had written them out incorrectly.

**Comment by GaryRidgway** [comment]
Re-checking the grad mentor problem!

**Comment by GaryRidgway** [comment]
@pyrello On Grad, Mentors can now be added by editors and webmasters, but the problem where publishers still have a limited set of content types they creates still persists. They can only add these content types:

Screen Shot 2021-08-18 at 9 58 44 AM

Is this intended behavior?

**Comment by pyrello** [comment]
I don't know that it is intended, but I don't think it is a regression.

**Comment by pyrello** [comment]
I attempted to sort out the publisher permissions on Grad. This should not be considered a necessary to approve.

**Review by GaryRidgway — APPROVED** [review]
Based upon Sean's specifications, I APPROVE

**Pull request merged**
