### PR TITLE
Mega PR: WYSIWYG Buttons Refactor, Admissions card link updates, Table updates

### LINKED ISSUE #3078: Button style not appearing in v3 text area block
# Problem
Buttons don't appear to work in SiteNow v3 text area blocks. I found this bug when moving the SiteNow website from v2 to v3.

# Steps to reproduce
Go to a text area block on a SiteNow v3 website and style in a button.

# Proposed solution

- [ ] Update the Linkit modal overrides in docroot/modules/custom/sitenow_media_wysiwyg/js/button_style.js to be UIDS specific.
- [ ] Programmatically update v2/v3 websites similar to the media markup update https://github.com/uiowa/uiowa/pull/3048

### LINKED ISSUE #3262: Remove entire card link on Areas of Study Admission Process
It was brought up during the Admissions design meeting that they don't like how the entire card is a link on the Areas of Study Admissions Process cards since there are multiple links.

An example was on an Area of Study page (https://admissions.prod.drupal.uiowa.edu/academics/biology).

Screen Shot 2021-03-19 at 3 08 22 PM

They also mentioned  it may be nice to have a hover effect or something to make the non button link stand out more.

# Proposed solution

- Once https://github.com/uiowa/uids/issues/531 is completed, update Areas of Study admission process card template (https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/paragraph--admissions-requirement--default.html.twig) with modifier class to remove card link.

### LINKED ISSUE #3330: Implement UIDS table changes, strip table classes from text areas, update table JS
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

As a tables user, after https://github.com/uiowa/uids/issues/509 and https://github.com/uiowa/uids/issues/510 are completed the `table--static` and `table--is-striped` classes will no longer be relevant.

# Proposed solution
- [ ] Implement UIDS table default styles and responsive solution updates.
- [ ] Iterate through all text areas and remove the `table--static` and `table--is-striped` classes from them in an update hook.
- [ ] Update UIDS tables JS implementation to match UIDS.

### LINKED ISSUE #3395: Admissions authenticated users lacking print permissions
# Problem
Webmasters and other roles get an access denied message when visiting test print pages.

# Steps to reproduce
Masquerade as a non-admin and click the links at https://admissions.prod.drupal.uiowa.edu/areas-of-study/print-links.

# Proposed solution
Grant `Page: Use all print engines` to the authenticated use role. Export config, commit, push.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #3078 
Relates to https://github.com/uiowa/uiowa/issues/260
Relates to https://github.com/uiowa/uiowa/issues/2532
Resolves #3262 
Resolves #3330 
Resolves #3395

- Removes our custom LinkIt solution for adding button classes to WYSIWYG links and replaces it with style dropdown options on the `<a>` tag.
- On all sites but HR, loops through text_long and text_with_summary type fields along with our ignored view config and replaces bootstrap button classes with uids classes.
- Does the same thing to remove table classes.
- Add bold and light intro classes to style dropdown on the `<p>` tag.
- Splits the filtered_html text format for HR which has different classes for the lead and buttons.

# To Test

To make sure that you get the UIDS update, follow these steps:
```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
yarn workspace admissions_core build
```

## Button updates

- Sync `sandbox` `hr` and other sites (e.g. a website with separate content type with text_long or text_with_summary fields).
- See https://sandbox.local.drupal.uiowa.edu/bootstrap-buttons. All of the markup has been changed from btn* classes to bttn* classes. Revert to a previous revision. You should still see the bttn* markup.
- Make changes to the content to confirm the markup stays and that there are no weird errors.
- See https://sandbox.local.drupal.uiowa.edu/sandbox-people. See the header content buttons are bttn* markup.
- See https://hr.local.drupal.uiowa.edu/advanced-layout-guide-not-publication and see that the buttons on the page are still the HR bootstrap based styles. Edit the page and see that Lead and Button style options still use bootstrap classes.

### Go the extra mile

- Query the entire database to see if `btn-` exists. It shouldn't except maybe for a key_value_expire table entry.

## Area of Study (Admissions) card link updates

- `blt frontend`
- Edit http://admissions.local.drupal.uiowa.edu/academics/accounting and add links to to the Admissions Requirement link fields.  Save the page and verify that the link button works but the entire card is not linked. 
- Edit the page again and add a "Story" to the page and verify that the story card is still clickable. 

## Print links (Admissions) permissions updates
- Masquerade as a webmaster and go to https://admissions.local.drupal.uiowa.edu/areas-of-study/print-links.   Try clicking on a pdf link in the "Tests" table at the bottom of the page.   You should **not** be seeing an "access denied" message. 

## Table updates
- Add a large table to every layout region and verify that the table shows the `overflow-y` scrollbar:
<details>

```
<table>
	<caption>Tables can have captions now.</caption>
	<thead>
		<tr>
			<th>Person</th>
			<th>Number</th>
			<th>Third Column</th>
			<th>Fourth Column</th>
			<th>Fifth Column</th>
			<th>Sixth Column</th>
			<th>Seventhth Column</th>
			<th>Eighth Column</th>
			<th>Ninth Column</th>
			<th>Tenth Column</th>
			<th>Eleventh Column</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Someone Lastname</th>
			<td>900</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th><a href="#">Person Name</a></th>
			<td>1200</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Another Person</th>
			<td>1500</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>some other person</th>
			<td>2800</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Someone and a Lastname</th>
			<td>500</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th><a href="#">Linked Name</a></th>
			<td>1720</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Another random person</th>
			<td>1200</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Some other Person</th>
			<td>2200</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Firstname and something</th>
			<td>920</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th><a href="#">Linked Other Name</a></th>
			<td>1208</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Another Person Randomly selected</th>
			<td>1550</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
		<tr>
			<th>Last One</th>
			<td>2830</td>
			<td>9999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
			<td>1999</td>
		</tr>
	</tbody>
</table>
```

</details>

### CODE REVIEW

**Comment by pyrello** [comment]
This PR now contains the updates from #3382.

**Comment by joewhitsitt** [comment]
Downside to this update is that it will replace _all_ instances. For example, the table documentation here https://sitenow.uiowa.edu/documentation/wysiwyg will be stripped of the table class strings with no replacement, so we will have to plan update this in advance or fix immediately after.

**Comment by pyrello** [comment]
Waiting for Xcode to finish downloading, then I'm going to take a look at this.

**Comment by pyrello** [comment]
@joewhitsitt My concern with the approach in your update hook is that it is going to produce, in some cases, instances of empty class attributes in the stored HTML, like `class=" "`. Maybe this isn't a big concern, but it feels like it kind of defeats the purpose of the update hook I was planning on doing to clean up the table styles.

**Comment by joewhitsitt** [comment]
Yeah, that is a fair point. Technically `class=" "` could be added as a last pass to replace with "" which would clean up other instances like outside of tables and links. My concern with the previous DOM method was the time it would take to process all of the fields and revisions. There also were those instances where line breaks were shown but I know that we didn't pin those to the update hook. If we went with the longer update process, we probably want to schedule off-hours.

**Comment by joewhitsitt** [comment]
Looks like a right-arrow is added to wysiwyg btn-primary in uids_base. @bspeare does this need to be accounted for or are basic buttons good and the [button component](https://github.com/uiowa/uiowa/issues/2873) the place for icons?

**Comment by bspeare** [comment]
@joewhitsitt Is there a screenshot you can post to go along with that last point?

**Comment by joewhitsitt** [comment]
oh, maybe not. https://brand.uiowa.edu/lockups they are added to the markup

**Comment by pyrello** [comment]
For the button updates, would these ever be used on an HTML element other than `a`?

**Comment by pyrello** [comment]
I have gone ahead with the assumption that the `a` tag is the sole element used for buttons. Code can be updated to accommodate others as needed.

I have not fully vetted this yet, but I think the logic is sound and could use some other eyes on it. @joewhitsitt if you could test against the cases you have already tested, that would be helpful. We could also push this to dev and look at it there.

**Comment by pyrello** [comment]
Do we need to remove table classes from ignored views?

**Comment by joewhitsitt** [comment]
>For the button updates, would these ever be used on an HTML element other than a?

If they are, they aren't supported.

>Do we need to remove table classes from ignored views?

Wasn't tables.js creating a list of tables not to add it to? sitenow people draggable views? If you mean the header content like i did with buttons, it wouldn't hurt

---
Pulling down to try out

**Comment by pyrello** [comment]
Started testing on brand.uiowa.edu and noticed that the first button on their homepage doesn't look right:
Screen Shot 2021-04-22 at 4 05 42 PM
Here is the button HTML (mostly):
```html
<a class="bttn bttn--secondary bttn--caps" href="/platform" title="Brand platform">Learn about our brand <span class="fa-arrow-right fas"></span></a>
```
The issue seems like it might be related to how our background styles are defined:
Screen Shot 2021-04-22 at 4 07 35 PM

**Comment by pyrello** [comment]
Moved back to draft until we figure out the button styling issue.

**Comment by joewhitsitt** [comment]
Re: brand.uiowa.edu

the background on that paragraphs section is yellow and the button is inheriting it to color the text. remove the background color and it is fixed. since the image is in front, i don’t know of a way to catch and fix this.

update: remove the image, add the yellow background and it is a problem.
Screen Shot 2021-04-22 at 4 36 20 PM

inherits from docroot/themes/custom/uids_base/scss/paragraphs/uiowa_paragraphs.scss line 66

**Comment by pyrello** [comment]
I found the [responsive_table_filter](https://www.drupal.org/project/responsive_table_filter) module, which is a filter that allows adding a wrapping element (configurable) with a class (configurable). We are adding this to the project to allow for implementing the responsive solution that depends on the wrapper as this prevents us from having to temporarily manually add it.

**Comment by bspeare** [comment]
It looks like the buttons don't work with our `background.css` file.   I think a temporary solution for the `v2` sites would be to add some `v2` specific rules to `sitenow.scss` and see if that fixes the majority of the issues. 

For instance, adding `!important` to the button definitions so that they don't inherit the container color:

```
.bttn--primary {
    color: #151515 !important;
}
.bttn--secondary  {
    color: #fff !important;
}
```

**Comment by GaryRidgway** [comment]
I'll add those, I think as a stopgap those rules work fine ben

**Comment by GaryRidgway** [comment]
So this solution works fine, but it does cause some loss of possible "buttonality" when a button is the same color as its BG. it still works, it just wont look like a button. However, it IS accessible.

Screen Shot 2021-04-23 at 11 45 44 AM

So we have two options here:
1. continue on with this, understanding that v2 users may need to take an extra step when adding buttons to make sure that they don't add the same color button on the same color background.
2.  try and do a huge cascading style update for the `bttn` classes like we have done for BGs in v3, which would take a while.

**Comment by bspeare** [comment]
@GaryRidgway I vote for option #1.  They can easily switch the button to the other style in the WYSIWYG.

**Comment by GaryRidgway** [comment]
@bspeare that's what I would vote for too

**Comment by pyrello** [comment]
I concur.

**Comment by GaryRidgway** [comment]
So I've been doing some testing and I got to everything except for tables before I had to skidaddle. 

The only two things I noticed are these:

The card is still clickable after adding links for Admissions Requirement link fields.
6cfae4c6c98a897cddbe0b8c3be40fda

Also, the tables for print links are no longer styled as striped tables:
Screen Shot 2021-04-23 at 1 48 53 PM

those were the only things that I saw

**Comment by joewhitsitt** [comment]
I followed the initial uids yarn steps and ran `yarn workspace admissions_core run build` instead of `blt frontend` and cannot replicate the following (story is still clickable):
>The card is still clickable after adding links for Admissions Requirement link fields. - https://github.com/uiowa/uiowa/pull/3379#issuecomment-825854569

I also see the rows on the test links as a webmaster:
Screen Shot 2021-04-26 at 1 45 48 PM

**Comment by joewhitsitt** [comment]
I am biased and not sure where this PR is from Friday, but I am seeing a lot of good work! Thanks all.

Of all of current test instructions, I was able to get the expected result. Spot checked admissions, brand, sandbox, hr.

FYI, this is also a good page to test tables on: https://admissions.local.drupal.uiowa.edu/apply/academic-requirements-country

**Comment by pyrello** [comment]
I have a note on the board to discuss what I see as being the final issue holding this up. An inquiry from Parking and Transportation about why sticky headers only seem to show up for non-authenticated users led to me telling them about our pending table update and they are concerned they will need to add the sticky header to all their tables after the update. However, the new sticky header solution doesn't handle horizontal scrolling, so the experience is essentially broken on mobile. I'm fine with moving ahead with this, but I would like to have an answer for them about what our path forward is going to be.

**Comment by dnkemper** [comment]
I'm getting this error when I am testing the "Print links (Admissions) permissions updates" part. I have a computer update and am going to do that then retry this? Maybe I'm just behind?
Screen Shot 2021-04-27 at 3 28 38 PM

**Comment by pyrello** [comment]
@dnkemper i think that might be related to local environment changes from a PR that @richardbporter worked on last week

**Comment by bspeare** [comment]
@dnkemper I couldn't get the PDFs to work locally either.

**Comment by pyrello** [comment]
I'm not sure how exactly, but I think the change to forcing HTTPS is affecting the PDF download: https://github.com/uiowa/uiowa/pull/3363

The first time we got an error message about this was around the same time that PR got merged.

**Comment by bspeare** [comment]
I just ran the updates on https://github.com/uiowa/uiowa/pull/3363 and the PDFs are now generating.

**Comment by dnkemper** [comment]
@bspeare @pyrello it's working for me now! Sorry about that!

**Review by dnkemper — APPROVED** [review]
Tested following the instructions and looks good to me! 👍

**Comment by pyrello** [comment]
Thanks for testing!

**Comment by pyrello** [comment]
I'm not sure if we agreed upon a communication plan for this update yet, but I'm waiting to merge it until I'm clear on that, so that we are not in a position where we have to work around it being in `main`.

**Comment by richardbporter** [comment]
Yea PDF generation requires a valid SSL cert unless the local config is split and modified. I think setting up the cert using the directions in #3363 is a better option. This shouldn't be a problem in cloud environments. Good catch.

**Comment by richardbporter** [comment]
Re: communications, can we just mention this in the April Updates news article on sitenow.uiowa.edu then send out the dispatch message for it?

**Comment by joewhitsitt** [comment]
Woot!

**Pull request merged**
