### PR TITLE
Deprovsions 2024-11-14

### LINKED ISSUE #8164: Redirect for dei.athletics.uiowa.edu/ to diversity.uiowa.edu/.
Would redirecting the old https://dei.athletics.uiowa.edu/ to https://diversity.uiowa.edu/ Be a vulture redirect? And should I be waiting for the redirect to be created and the sea name to be repointed before the provisioning the old DEI site?

```[tasklist]
### Tasks
- [x] request the vulture redirect be setup to redirect dei.athletics.uiowa.edu and all subpages to https://diversity.uiowa.edu/
- [x] Request Hostmaster lower TTL for dei.athletics.uiowa.edu
- [x] locally test redirect once setup on Vulture
- [x] make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [x] have hostmaster set TTL back to default for dei.athletics.uiowa.edu
- [x] deprovision or create deprovision issue for dei.athletics.uiowa.edu(don't reclaim DNS) (uiowa02)
- [x] Contact Wendy D that site has been removed
```

### LINKED ISSUE #8225: Deprovision v3 sites from uiowa07
* masongroup.lab.uiowa.edu

Per Maggie B
> It was determined during our Chemistry site migration that the Mason Group lab site could go away, due to faculty no longer being with the University. Therefore, this site is no longer needed.

 * orsc-colloquium.sites.uiowa.edu

Per Jerry Gehling
> I checked with Dr. Sukalski and Matthew.  This site can be shut down there is no need for migration.  It was used during covid and has no use since we put that behind us.

* fab.law.uiowa.edu

Per Ann Laquer Estin
> Thank you for this message and reminder. I've taken the opportunity of this transition period  to save what I want of the content from my old site (including posts that were brought forward to the "old" platform in 2014 when it was new) and I've decided not to build out a new v3 site. 
Please put me in your third category: no longer needing my current website, and not planning to replace it.

* mil.lab.uiowa.edu

Per Nichole Jenkins
> the person in charge of this lab left, so we can go ahead and remove the staging site.  We can likewise retire her current site.

### LINKED ISSUE #8226: Deprovision v3 sites from uiowa04
* matthew-arndt.sites.uiowa.edu
* nanotech.uiowa.edu - https://nanotech.prod.drupal.uiowa.edu - Maggie said this can be removed.

Per Mike Cranston
> I have checked with Matthew Arndt, and he no longer needs the v1 site and doesn’t plan to replace it.

### LINKED ISSUE #8245: Deprovision https://statgeemap.prod.drupal.uiowa.edu on uiowa04
Brynne gave approval to remove https://statgeemap.prod.drupal.uiowa.edu/

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/8164
Resolves https://github.com/uiowa/uiowa/issues/8226
Resolves https://github.com/uiowa/uiowa/issues/8225
Resolves https://github.com/uiowa/uiowa/issues/8245

# How to test

### CODE REVIEW

**Comment by james917** [comment]
Reclaimed
masongroup.lab.uiowa.edu
orsc-colloquium.sites.uiowa.edu
fab.law.uiowa.edu
mil.lab.uiowa.edu
and notified Hostmaster

**Review by pyrello — APPROVED** [review]
7 (sites) * 7 (files removed per site) + 2 (aggregate files changed) = 51

**Comment by joewhitsitt** [comment]
Throwing a curve ball. Adding one more.

**Comment by briand44** [comment]
fyi, I previously asked hostmaster to reclaim the following domains when I removed them from D7 earlier this week:

- orsc.colloquium.sites.uiowa.edu
- masongroup.lab.uiowa.edu
- matthew-arndt.sites.uiowa.edu
- nanotech.uiowa.edu

**Review by pyrello — APPROVED** [review]
8 * 7 +2 = 58

**Pull request merged**
