### PR TITLE
Sprint 233 de/provisions

### LINKED ISSUE #8089: 2+ week decommissioning plan for coronavirus website
We have some key pages on the coronavirus website that we want to redirect to new destinations elsewhere on campus. The goal is that we add redirects to these pages, give Google 2 weeks to pick up the signal, then decommission the coronavirus website entirely.

2 week timer starts after pages are redirected and sitemap for coronavirus.uiowa.edu site is resubmitted in google search console.

* https://coronavirus.uiowa.edu/returning-campus/showing-symptoms redirects to https://studenthealth.uiowa.edu/covid-19
* https://coronavirus.uiowa.edu/testing-information redirects to https://studenthealth.uiowa.edu/covid-19
* https://coronavirus.uiowa.edu/vaccine-information redirects to https://studenthealth.uiowa.edu/covid-19

After 2 weeks:
* Decommission coronavirus website entirely
* vulture redirect all coronavirus traffic to https://studenthealth.uiowa.edu/covid-19.  Duration 1 year or whatever their standard is.

Tagging @briand44 and @mkyoder 

```[tasklist]
### Tasks
- [x] create the three redirects listed above in Drupal
- [x] resubmit sitemap to google
- [x] add reminder for 2 weeks to update DNS for the vulture redirect
- [x] submit request for vulture redirect
- [x] ask hostmaster to lower TTL for coronavirus.uiowa.edu
- [x] test vulture redirects locally once created
- [x] after the 2 week period, have hostmaster update DNS
- [x] ask hostmaster to set TTL to default
- [x] deprovision coronavirus website
```

### PR DESCRIPTION
**Pull request by cory-skeers**
Delete rvap.uiowa.edu multisite on uiowa
Delete coronavirus on uiowa01 resolves https://github.com/uiowa/uiowa/issues/8089

# How to test

### CODE REVIEW

**Comment by joewhitsitt** [comment]
*.tippie.uiowa.edu is already covered on uiowa03 and uiowa02

**Comment by joewhitsitt** [comment]
I thought we fixed it but the site custom config was not properly added to git but was deleted as part of the umd command. https://github.com/uiowa/uiowa/issues/8135

**Review by bspeare — APPROVED** [review]
4 sites * 7 + 1 sites.php + 1 manifest.yml + 13 deleted files = 43 total file changes

**Comment by joewhitsitt** [comment]
If that math makes sense to you, then alright, alright, alright!

**Pull request merged**
