### PR TITLE
Feature: Timeline

### LINKED ISSUE #3314: As a site owner, I can build a timeline layout with layout builder
# Story

As a site owner, I can build a timeline layout with layout builder

# Proposed solution

- Create a separate timeline block with paragraph items for each timeline entry
  - Technical details
    - Block will need to be created programmatically in order to place in the "More" block section
    - Media field that allows image or video
    - Font awesome Icon picker field
    - Title
    - Date (date range?) 
      - Date field will be used to group by year in future slice?
    - Description
    - Link w/title
  - Styling
    - Use https://ultimateelementor.com/widgets/timeline/ as design inspiration using card template
    - Alternate position left and right
    - Card alignment and styles options from card block

## Future Slices
- Vertical dot navigation for year based navigation like on https://viewbook.admissions.uiowa.edu/. 
- Waypoints and animate.css scroll animations for each timeline item

### LINKED ISSUE #3951: Some sites are missing option to add the People block in LB
We suspect that several sites (grad, pharmacy, transportation) did not get the allowed block permission when the people block was refactored due to split page default config.

## Proposed Solution

- Update sites that have split page.default to be up to date with people block and any other missing additions.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3314. 
Resolves https://github.com/uiowa/uiowa/issues/3951.

- [x] Admissions split
- [x] Permissions for webmasters and editors need to be added across all v3 splits
- [x] Can the fontawesome field be moved down? As an optional field, it feels stuffy at the top.
- [x] Restrict additional font awesome settings
- [x] Headline field doesn't seem to link up to children.

# How to test
```
blt ds --site=sandbox.uiowa.edu
yarn workspace uids_base gulp --development
drush @sandbox.local cr
```

- Add a "Timeline" block to a one column layout (the block is/should be restricted to one column layouts only).
- Add a number of timeline items and test out the fields
- User stories:
 -  "As a site owner, I can build a timeline layout with layout builder"
 - As an admin, I can use the additional font awesome settings on the timeline icon field
 - As an webmaster, I can see the additional font awesome settings on the timeline icon field but they are disabled for use

## Also
- Added access to People block list for Grad, Transportation, and Admissions which previously did not have the people list block.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
- These need to be split for Admissions ([entity print](https://github.com/uiowa/uiowa/issues/3204)):
  - core.entity_view_display.block_content.uiowa_timeline.default
  - core.entity_view_display.paragraph.uiowa_timeline_item.default

- Permissions for webmasters and below need to be added across all v3 splits
- Can the fontawesome field be moved down? As an optional field, it feels stuffy at the top.
- I still think we should limit fontawesome icon settings.. (re: event). I was able to make a really large inverted icon that spins and overflows.
- ~~Does preview work?~~ had preview turned off
- ~~Multiple timeline blocks on a page don't seem to work. Overlap.~~ cache issue?
- Headline field doesn't seem to link up to children.

Screen Shot 2021-08-11 at 12 08 56 PM
Screen Shot 2021-08-11 at 12 17 14 PM

**Comment by bspeare** [comment]
@joewhitsitt What do you suggest for limiting the font awesome settings?  Do we just want to remove/unset that toggle option from the block form?

**Comment by joewhitsitt** [comment]
I would see if it could be done like the main menu block in layout_builder_custom for event and timeline.

```php
case 'menu_block:main':
          /** @var Drupal\uiowa_core\Access\UiowaCoreAccess $check */
          $check = \Drupal::service('uiowa_core.access_checker');

          /** @var Drupal\Core\Access\AccessResultInterface $is_admin */
          $access = $check->access(\Drupal::currentUser()->getAccount());

          if ($access->isForbidden()) {
            // Restrict block settings on main navigation block.
            $form['settings']['menu_levels']['#access'] = FALSE;
            $form['settings']['advanced']['#access'] = FALSE;
            $form['settings']['style']['#access'] = FALSE;
          }
...
```

**Comment by joewhitsitt** [comment]
Should there be an access check around those FA settings? It would allow admins to "fix" existing event blocks (if any) but also allow us to do something custom in a pinch (if needed).

**Comment by bspeare** [comment]
@joewhitsitt I'll give that a try.

**Comment by bspeare** [comment]
@joewhitsitt on "Headline field doesn't seem to link up to children" did you mean the heading levels changing based on the block headline or something else?

**Comment by joewhitsitt** [comment]
Correct. When I set a parent headline of h3, I didn't see the children switch to h4 on render (can't remember if it worked in preview)

**Comment by bspeare** [comment]
@joewhitsitt thanks, I think all the issues listed in https://github.com/uiowa/uiowa/pull/3928#issuecomment-896994724 have been addressed now.

**Comment by bspeare** [comment]
Just updated the splits for Grad, Transportation, and Admissions to allow access to the people list block.    Please double-check those config changes if you are reviewing this pull request.

**Comment by joewhitsitt** [comment]
commits look good. testing one more time

**Comment by joewhitsitt** [comment]
>Could not apply patch! Skipping. The error was: The "https://www.drupal.org/files/issues/2019-12-11/menu_block-remove_duplicates-3062278-11.patch" file could not be downloaded: failed to open stream: Connection timed out

build error is not this code but upstream

**Review by joewhitsitt — APPROVED** [review]
Looks good!

**Comment by bspeare** [comment]
Thanks @joewhitsitt !

**Pull request merged**
