### PR TITLE
Adjust permissions for webmasters on uiowa.edu.

### LINKED ISSUE #1663: Update permissions for uiowa.edu
- [x] Navigation (e.g. search menu)
- [x] A-Z Terms

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1663

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Oh shoot, I forgot uiowa.edu is using collegiate split permissions. We are going to have to split because of the a-z list

**Comment by richardbporter** [comment]
Ok. Anyone know why acquia_connector.settings are in the uiowa.edu split?

**Comment by joewhitsitt** [comment]
> Anyone know why acquia_connector.settings are in the uiowa.edu split?

nope, but that explains why it gets exported when i do stuff locally. alerts stuff gets exported too.

**Comment by richardbporter** [comment]
Actually its not. Yea I see the alerts too. Export filtering does not seem to work in certain situations.

**Review by pyrello — APPROVED** [review]
Reviewed, not tested. Looks good.

**Pull request merged**
