### PR TITLE
Copy quick links to top links uiowa_bootstrap -> uids_base

### LINKED ISSUE #1817: Migrate uiowa_bar quick links
Relates to #1660 

As part of the move to uids_base and from uiowa_bar to uiowa_search, look into programmatically migrating links currently in quick links, possibly to the Top Links menu.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #1817 

If quick links are present (set in /admin/config/system/uiowa-bar in uiowa_bootrap using uiowa_bar), they are added to the Top Links menu, which roughly translates to the same link positioning/usage after transitioning to uids_base.

## Testing
Run the update, switch to uids_base. If quick links had been included on the site, they should be included in the top bar with the same title and link. If no links were included, or if they were incomplete (i.e. no link or title), they should not be brought over.

If there are links already present in the Top Links menu, quick links should be appended to the end of the menu links.

## Notes
Update hook does not check for broken links, or links that could be duplicated by being moved to the Top Links menu. Assumptions are that if they were broken, they will remain broken for general maintenance work to fix, and that the sites which may have links appearing in both quick links and top links is limited enough, and the possibility low enough, that this does not need to be accounted for.

Depending on order of updates, an additional check to run only on sites using uiowa_bootstrap, or something similar could be added. It also leaves the links in the uiowa_bar settings, so this could run prior to uids_base rollout, with the understanding that there could be a data loss for changes made between this and uids_base.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
worked as expected. i am resistant to approve this PR because I think it should be merged and rolled out as part of #1806

**Comment by cory-skeers** [comment]
Thanks for the review, @joewhitsitt -- I'd agree it can be merged and rolled out as part of #1806. Since this update isn't doing anything with config, there shouldn't be any update time concerns like with #1755.

**Comment by joewhitsitt** [comment]
Alright, can you attempt the merge into #1806 modify the description to resolve the issue automagically, and close this PR? I know the update hooks are conflicting so let me know if you need help.

**Comment by cory-skeers** [comment]
Yep! I'll get on it shortly, and let you know if I run into trouble.

**Comment by cory-skeers** [comment]
This has been rolled into #1806.

**Pull request closed without merging**
