### PR TITLE
Tippie Redirects import

### LINKED ISSUE #5265: As a Tippie webmaster, I would like redirects from D7 site imported programmatically into the D9 site.
# Story

As a webmaster, I would like redirects from D7 site imported programmatically into the D9 site so that I don't have to manually recreate over 60 pages of redirects manually. 

Prioritize for May 20th sprint to give James time to clean up the URLs and create the spreadsheet.

# Proposed solution

1. Create a spreadsheet. The CSV file must include columns in the following order: "From URL","To URL","Redirect Status","Redirect Language". Make sure you use "/node" instead of custom URLs.
2. Write an update hook to use the spreadsheet to bulk import the bookmarks. Refer to uiowa, HR update hooks.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #5265 

# How to test

- `git checkout tippie-redirects && git pull`
- `ddev blt site=tippie.uiowa.edu`
- Watch that tippie core update hook 9001 runs.
- some redirects will be deleted if they form redirects to themselves, `/alumni` was one of these such redirects. Check to make sure it is functioning.
- Spot check the listed redirects, check number of redirects in db before and after update hook, and/or any other method of checking that the correct number of redirects have been created

### CODE REVIEW

**Comment by cory-skeers** [comment]
The basic update hook is set up here. Couple things in case I'm not the one to take this over the finish line:

- I don't think batching is absolutely needed, especially because the site is not live, but if it's determined, there are some examples of batching in `profiles/custom/sitenow/sitenow.install::sitenow_update_9003` and elsewhere in there
  - Another option would be to include one csv per worksheet, but this would be fairly uneven batching
- We're waiting on an updated version of the redirects in #5265, but the included CSV can be used for testing
  - To prepare the original spreadsheet for use here, I simply combined the 4 separate worksheets into one, removed the headers, and exported as a plain csv
- In my initial tests, it ended up creating 1200 new redirects, though the csv has 1218 listed. Likely there are 18 redirects in the spreadsheet that already existed in the system, but I'm not 100% sure

**Comment by GaryRidgway** [comment]
I am going to try to make this work so someone other than cory can back up it working.

> * We're waiting on an updated version of the redirects in [As a Tippie webmaster, I would like redirects from D7 site imported programmatically into the D9 site. #5265](https://github.com/uiowa/uiowa/issues/5265), but the included CSV can be used for testing

@briand44 [ referenced that the current spreadsheet even with small errors is going to be the one we use.](https://github.com/uiowa/uiowa/issues/5265#issuecomment-1136034339)

**Comment by GaryRidgway** [comment]
Currently getting this error when trying to look at the redirects created.
```php
The website encountered an unexpected error. Please try again later.

InvalidArgumentException: The URI '/people/robin-akers' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of core/lib/Drupal/Core/Url.php).
Drupal\link\Plugin\Field\FieldType\LinkItem->getUrl() (Line: 240)
Drupal\link\Plugin\Field\FieldFormatter\LinkFormatter->buildUrl(Object) (Line: 178)
Drupal\link\Plugin\Field\FieldFormatter\LinkFormatter->viewElements(Object, 'en') (Line: 89)
Drupal\Core\Field\FormatterBase->view(Object, 'en') (Line: 263)
Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) (Line: 267)
Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay->buildMultiple(Array) (Line: 256)
Drupal\views\Entity\Render\EntityFieldRenderer->buildFields(Array) (Line: 143)
Drupal\views\Entity\Render\EntityFieldRenderer->render(Object, Object) (Line: 833)
Drupal\views\Plugin\views\field\EntityField->getItems(Object) (Line: 1149)
Drupal\views\Plugin\views\field\FieldPluginBase->advancedRender(Object) (Line: 238)
template_preprocess_views_view_field(Array, 'views_view_field', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('views_view_field', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 1745)
Drupal\views\Plugin\views\field\FieldPluginBase->theme(Object) (Line: 779)
Drupal\views\Plugin\views\style\StylePluginBase->elementPreRenderRow(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 772)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 363)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 718)
Drupal\views\Plugin\views\style\StylePluginBase->renderFields(Array) (Line: 584)
Drupal\views\Plugin\views\style\StylePluginBase->renderGrouping(Array, Array, 1) (Line: 475)
Drupal\views\Plugin\views\style\StylePluginBase->render(Array) (Line: 2170)
Drupal\views\Plugin\views\display\DisplayPluginBase->render() (Line: 1533)
Drupal\views\ViewExecutable->render() (Line: 199)
Drupal\views\Plugin\views\display\Page->execute() (Line: 1630)
Drupal\views\ViewExecutable->executeDisplay('page_1', Array) (Line: 81)
Drupal\views\Element\View::preRenderViewElement(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 772)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 363)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by GaryRidgway** [comment]
I assume that this isn't working because the local site doesn't have people set up correctly? Is there a test people directory API key that I should be using?

**Comment by GaryRidgway** [comment]
I was able to find an API key that worked, but it seems like it doesn't like the people redirects specifically even with the API key. I will investigate further on how the people redirects might be implemented in a different way.

**Comment by GaryRidgway** [comment]
Builds are currently failing, but not due to this PR. Reviewing is good!

**Comment by e-marie-w** [comment]
Redirects now all work for me. Any redirects pointing to themselves have been removed, so I'm no longer getting errors resulting from looping. Comparing before update hook and after, removing these looped redirects results in 30 less redirects than in the CSV. Not sure how to identify those specifically, but it doesn't seem needed. The redirects with unprintable unicode characters are also working correctly for me now.

**Review by e-marie-w — APPROVED** [review]

**Pull request merged**
