### PR TITLE
SiteNow People View Page Filtering

### LINKED ISSUE #3043: Filtering at the top of person page
## Story

As a site owner, I can opt-in to views filtering on the SiteNow People view page.

## Proposed Solution

- [x] Locally establish all the filtering that should be made available on the "Default" Master display. Do not expose the filters.
  - [x] Name, Title or Position (first name/last name, title/position contains) - filter query name = `search`
  - [x] Person Type (preferably a dropdown of available options) - filter query name = `type`
  - [x] Research Areas autocomplete - filter query name = `research`
- [x] Provide reset button (shouldn't show unless filters are exposed)
- [x] Save the config so that it is setup but not exposed for new sites (you need to temporarily remove the view from config ignore to export)
- [x] Convert that exported yml diff to an update hook as this view is ignored and custom to every website. Assumes, the update hook will only touch the filters portion of config and that no sites have added their own filter.
- [x] Add booleans to the SiteNow People configuration form to toggle the exposure of these filters. View #2526 for additional details on setting this up.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #3043 

Title/Position has been removed from the scope but could be included later as part of the combined filter.

This PR assumes existing sites haven't modified the view beyond the configuration allowed here: admin/config/system/sitenow-people. The update hook grabs that current config, imports the view changes and adds the site's modifications back.

Originally, this was setup so that the filter existed in the view and the configuration form only toggled the exposed status. When not exposed, this resulted in no results based on the "hardcoded" empty values for the filters. Not how I originally envisioned it, but creating/deleting the filter each time was the only way I could get it to work and keep the same order of filters.

## To Test

- `composer install && blt dsa` v2/v3 new and existing sites. default, customized, disabled SiteNow People configuration.
  - Example sites: gis.sites.uiowa.edu/people (v2, heading text, manual sort), sandbox.prod.drupal.uiowa.edu/sandbox-people (v3, custom title, path, heading, sticky/first/last)
- Import runs correctly (existing configuration is preserved, no config diff issues, and admin/structure/views/view/people should have changed from "content" render to "fields" render with rendered entity and other fields.
- As a webmaster, changing configuration and enabling/disabling filters should work as expected (admin/config/system/sitenow-people)
- As a visitor with filters enabled, you should be able to see a dropdown of person types, and filter by values contained in the view.
- Test with a pager (more than 30 rows, https://law.local.drupal.uiowa.edu/people)
- Short of going into views ui and manually changing the view, try to break the functionality.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Good to check, but BEF doesn't save the day in this situation.

Screen Shot 2021-03-25 at 1 51 47 PM

**Comment by joewhitsitt** [comment]
Changing direction. After talking with the team, position/title should not be in-scope. I am going to see about leaving it as a combine filter though in case we want to add it or something else in the future (much easier update process for an ignored view). This will remove the changes to the person content type.

**Comment by GaryRidgway** [comment]
I tried syncing down and had some problems with the config import. I manually imported config for sandbox and then tried turning on the filters in `admin/config/system/sitenow-people`. The filters did show up, but upon trying to search by a name or filter by a category the filters did not filter any portion of the people listing. Every time I hit apply I am getting this ajax error

`
{
    "message": "\nAn AJAX HTTP error occurred.\nHTTP Result Code: 200\nDebugging information follows.\nPath: /views/ajax\nStatusText: OK\nResponseText: TypeError: Argument 1 passed to Drupal\\Core\\Render\\BubbleableMetadata::createFromRenderArray() must be of the type array, null given, called in /var/www/uiowa/docroot/core/modules/views/src/Controller/ViewAjaxController.php on line 198 in Drupal\\Core\\Render\\BubbleableMetadata::createFromRenderArray() (line 65 of /var/www/uiowa/docroot/core/lib/Drupal/Core/Render/BubbleableMetadata.php).",
    "name": "AjaxError"
}
`

**Comment by joewhitsitt** [comment]
I'd like, if you are available after my meeting, to screenshare with you and see what is happening. Just sync'd on sandbox and not able to reproduce.

**Comment by GaryRidgway** [comment]
of course, that sounds fine to me. Talk to you at noon!

**Comment by GaryRidgway** [comment]
On second sync this is working as Joe describes, moving on to other testing

**Comment by joewhitsitt** [comment]
Order of operations issue maybe. Updated test instructions. Also included law as an example of 30+ people

**Comment by joewhitsitt** [comment]
@mark-bennett-uiowa did you want the opportunity to test this as well?

**Comment by mark-bennett-uiowa** [comment]
> @mark-bennett-uiowa did you want the opportunity to test this as well?

Absolutely. Ill pull this down for testing right now.

**Comment by GaryRidgway** [comment]
Tested with all filter combinations, as a webmaster, searching works well, etc. All looks good!

**Review by GaryRidgway — APPROVED** [review]
WE GOOD!

**Comment by mark-bennett-uiowa** [comment]
Looks good to me, and seems to be working as intended. Tested with Computer Science and Journalism. Computer Science did not have any research areas assigned to its people, so that select field only showed 'Any'. Pulled down Journalism to test the research area filter, and it appears to be working properly (after adding several research areas).

Only concern is the sorting in these dropdown lists:
Screen Shot 2021-03-31 at 2 17 46 PM
The checkboxes do not seems to have a consistent order when editing a profile node, and the dropdown list above isnt alphabetical. The research area dropdown list DOES seem to be in alphabetical order however.

**Review by mark-bennett-uiowa — APPROVED** [review]
Approved, with one concern noted in comments. Working enough to merge however.

**Comment by joewhitsitt** [comment]
I will create an issue for https://github.com/uiowa/uiowa/pull/3269#issuecomment-811374550

**Comment by joewhitsitt** [comment]
I will merge this after the the release rush

**Pull request merged**
