### PR TITLE
Update dependencies.

### LINKED ISSUE #141: administerusersbyrole update - Users only see people that they can manage
Updating from 8.x-3.0-alpha2 to beta1 changes how users are listed on the overview page. Users will only see people that they can manage. This is nice for filtering out admins and our alter could be removed but it is is suboptimal for editors because they see nobody.

This is the commit that introduced the change: https://cgit.drupalcode.org/administerusersbyrole/commit/?h=8.x-3.x&id=40b6bec130359708a32787004d8e57b81a88ebbc

Our alter: https://github.com/uiowa/sitenow/blob/master/sitenow.profile#L57

### LINKED ISSUE #853: Unpin drupal/stage_file_proxy version constraint
During the 8.8 update, stage_file_proxy rc4 caused a database error:
```
[warning] Update function stage_file_proxy_update_8002 not found
[error]  Update failed: stage_file_proxy_update_8002 
```
This should be investigated so that the version constraint can be loosened.

### LINKED ISSUE #921: Update to drupal/core-dev from webflo/drupal-core-require-dev
https://www.drupal.org/docs/8/update/update-core-via-composer#s-removing-or-replacing-dev-packages.

This will make updates to `drupal/core` easier :)

### LINKED ISSUE #1238: Bug in Sitenow - D8 for character counts in MetaDescription field.
Also, description box in Article schema should be sized for multi-line entry and not single field.

### LINKED ISSUE #1281: [Story] As a web developer, I can see that modules and other dependencies have been updated before the homepage go-live.
~~Require https://www.drupal.org/project/lb_claro~~ #1233 
- [x] drupal/acquia_connector
- [x] drupal/address
- [x] ~~drupal/administerusersbyrole~~ #141 
- [x] drupal/coder
- [x] drupal/config_ignore
- [x] drupal/crop
- [x] drupal/entity_browser
- [x] drupal/entity_embed
- [x] drupal/entity_reference_revisions
- [x] drupal/entity_usage
- [x] drupal/field_group
- [x] drupal/file_mdm
- [x] drupal/file_mdm_exif
- [x] drupal/focal_point
- [x] drupal/google_analytics
- [x] drupal/imagecache_external
- [x] drupal/imagemagick
- [x] drupal/inline_entity_form
- [x] #1427 drupal/layout_builder_restrictions @pyrello 
- [x] drupal/layout_builder_styles
- [x] drupal/lb_direct_add
- [x] drupal/masquerade
- [x] drupal/media_entity_twitter
- [x] drupal/media_library_theme_reset
~~drupal/menu_block~~ https://www.drupal.org/project/menu_block/issues/3066521
- [x] drupal/menu_breadcrumb
- [x] drupal/metatag
- [x] drupal/node_revision_delete
- [x] drupal/paragraphs
- [x] drupal/robotstxt
- [x] drupal/simplei
- [x] drupal/stage_file_proxy
- [x] drupal/twig_tweak
- [x] drupal/webform
- [x] drupal/workbench_email
---
- [x] drupal/colorbox               
- [x] drupal/config_update                           
- [x] drupal/ctools                 
- [x] drupal/date_recur_modular     
- [x] drupal/externalauth Requires uiowa_auth update.
- [x] drupal/mailsystem               
~~drupal/migrate_plus~~ 5.x not yet recommended.
- [x] drupal/search_api             
- [x] drupal/search_api_autocomplete
- [x] drupal/simple_sitemap         
---
- [x] drupal/core
---
- [x] acquia/blt --with-dependencies
--- 
- [x] PHP 7.3

### LINKED ISSUE #1391: [Story] As a site editor, I can see a similar Drupal 8 backend theme across campus
## Problem
The backend experience is fragmented across D8 sites and relying on Adminimal to be ready for D9 is one more thing we have to think about later.

## Proposed Solution
Revisit adopting Claro for the base profile and switch all sites over to use it once we have ironed out a few issues that remain with the experimental theme as it relates to Paragraphs.

- [x] Port and adapt the space saving drag handle tweaks we have in Adminimal. https://github.com/uiowa/uiowa/blob/master/docroot/profiles/custom/sitenow/css/admin-overrides.css
- [x] Update paragraphs to take advantage of the recent Claro fixes, most notably: https://www.drupal.org/project/paragraphs/issues/3079128
- [x] Chosen looks skinny/dated and doesn't match the green focus style
- [x] experimental dropbutton spacing
- [ ] fields extending to the border of parent
- [x] Duplicate drag handles
- [ ] Consider tightening up the white-space when it relates to paragraphs.
- [x] Set claro as admin theme.
- ~~Remove adminimal~~ https://github.com/uiowa/uiowa/issues/1471

Screen Shot 2020-04-15 at 2 31 03 PM
Screen Shot 2020-04-15 at 2 19 27 PM

>Most problematic is the loss of margin/padding when expanding paragraphs items. Also, the negative space is nice but the expanded pages makes it harder to work with our page building tools. A more compact UI is better for us.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1281 
Resolves #1391 
Resolves #921
Resolves #1238
Resolves #853 
Resolves #141 

Configuration changes related to the following exist but were not updated:
- uiowa_lb_blocks (layout_builder_styles)
- entity_types_seminar (field_group, paragraphs)

Testing (dev)
- Log in to a dev site and test out any and all functionality.
  - https://uiowa.dev.drupal.uiowa.edu

Testing (local)
- Run `vagrant provision` locally to get PHP 7.3.
- Sync a few sites via `blt dsa` and ensure functionality (paragraphs, layout, default, custom) is as expected.

### CODE REVIEW

**Comment by richardbporter** [comment]
@joewhitsitt Want to do the field group update? https://www.drupal.org/project/field_group/releases/8.x-3.0 I skipped that one.

**Comment by joewhitsitt** [comment]
doing this (composer) at the same time is tough. if you stop for a while and there are more to do, i can step in again

**Comment by joewhitsitt** [comment]
We should move forward with #1391 since paragraph styles break in Adminimal and just fix it once.
Screen Shot 2020-04-22 at 4 53 21 PM

**Comment by richardbporter** [comment]
I'm stuck trying to resolve #921. I think upgrading to Drush ^10.2 will fix this but it requires a large update to https://github.com/richardbporter/drush-users-commands.

**Comment by joewhitsitt** [comment]
i think i am running into a chicken/egg issue with https://github.com/uiowa/uiowa/pull/1461 and this. Claro needs the updated paragraphs and some composer edits, the PR needs us to adopt Claro. Anyone opposed to combining the two into this PR? @richardbporter

**Comment by richardbporter** [comment]
Nope

**Comment by joewhitsitt** [comment]
> I'm stuck trying to resolve #921. I think upgrading to Drush ^10.2 will fix this but it requires a large update to https://github.com/richardbporter/drush-users-commands.

@richardbporter Have you started to do this or are you still waiting for opinions?

**Comment by richardbporter** [comment]
Working on it.

**Comment by richardbporter** [comment]
Not sure how to resolve the views_tree failures. ¯\_(ツ)_/¯

**Comment by richardbporter** [comment]
@joewhitsitt Do you know if the sitenow_articles/events/people settings validation worked to validate against each other before this change? Ex. configure articles path to foo and then set events path to foo - it doesn't catch that collision.

**Comment by richardbporter** [comment]
@joewhitsitt Do you know if the sitenow_articles/events/people settings validation worked to validate against each other before this change? Ex. configure articles path to foo and then set events path to foo - it doesn't catch that collision.

**Comment by joewhitsitt** [comment]
> @joewhitsitt Do you know if the sitenow_articles/events/people settings validation worked to validate against each other before this change? Ex. configure articles path to foo and then set events path to foo - it doesn't catch that collision.

Just tried on STAGE. Apparently not...

**Comment by richardbporter** [comment]
I'd like to resolve #141 in this PR as well.

**Comment by richardbporter** [comment]
c27b657 seemed to work. Re-deploying to dev.

**Review by pyrello — APPROVED** [review]

**Comment by pyrello** [comment]
I have not found anything amiss with these updates at this point. I have checked on 6 different sites, across different configurations. I think it is unlikely that this will introduce no problems, but I'm not sure how to go about testing it more rigorously and am inclined to just figure out any problems that come up.

**Comment by richardbporter** [comment]
I agree. We should merge this later in case anyone needs to roll a release today. I think we want to send a communication to webmasters re: theme change.

One thing I was wondering is if adminimal and seven can be uninstalled as part of this.

**Comment by joewhitsitt** [comment]
I thought this would be a follow up task: https://github.com/uiowa/uiowa/issues/1471

I wasn't able to talk to Brian about the communication regarding the theme switch. I was planning on writing up a quick something for the sitenow site and then can we hit the webmaster api?

**Comment by joewhitsitt** [comment]
Going to pull a bunch of sites down and see what kind of broken functionality we can expect while this stuff rolls out.

**Pull request merged**
