### PR TITLE
i3011 transfer tips

### LINKED ISSUE #3011: Create Transfer Tips content type for Admissions website
# Story

As an Admissions Site owner I want to be able to create Transfer Tips so that that information is available to prospective Transfer students.

An example of this can be seen by visiting this page: https://admissions.uiowa.edu/academics/accounting; scroll down to the Admissions Requirements section, then click on the Transfer Students tab.

# Proposed solution

- [x] Separate content type (title/body/path pattern)
- [x] Entity reference on AoS that then displays on the transfer admissions requirements card
- [x] Must be in the correct form order https://github.com/uiowa/uiowa/issues/3108
- [x] See below

## Updated path to success

- [x] Add a required reference field to transfer tips that references a single AoS. 
- [x] This reference should display as a back link to the AoS on the full/teaser view modes.
- [x] Remove the transfer tip field on AoS
- [x] Remove the current logic in admissions_core that looks for the field to pass path data to the template. Leave the template as-is.
- [x] Pattern should be /academics/[area-of-study-title]/transfer-tips for now
- [x] A transfer tips presave function should update the title to be "[Area of Study] Transfer Tips", hide the title field on the form. This way it is distinguishable content on both the node and the content overview.
- [x] Update the admissions split to reflect the field changes on AoS and Transfer Tips
- [x] Setup basic SEO settings for the transfer tips content type (Ahem probably need to revisit a couple other content types later on :cough: scholarships, etc.). No need to go full field_teaser with this. Yet. Meta description and the related SEO description fields should have a default "Transfer tips for [Area of Study Reference Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.
- [x] "Transfer Tips List" views block (admissions core category) needs to be created with a list of linked titles that should be available in LB assuming the category is correct. A webmaster should be able to see and place this views block. For reference their current list: /transfer-plan but no accordion is needed and this will be placed on a basic page so header text can be supplied.
  - [x] The title for each row should just be the AoS label but link to the transfer tip.
- [x] Rework the transfer requirement card preprocess to query transfer tips that have the AoS as the reference. Since multiple references _could_ exist, just grab the first result and link to that.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3011 

# How to test

1. blt ds --site=admissions.uiowa.edu
2. blt frontend
3. Add a [transfer tip](http://admissions.local.drupal.uiowa.edu/node/add/transfer_tips)
4. Go to an area of study page (http://admissions.local.drupal.uiowa.edu/node/956/edit) and search for the transfer tip you added previously. Add it, save to page.
5. See that the 'transfer tip' link displays in the 'Transfer' card under the 'Admission Process' section of AOS page
6. Click on it -> make sure it takes you to full view of transfer tip ct
7. Make sure the AOS button is displayed and when you click on it, it takes you back to the full aos page
8. Masquerade as webmaster
8. Add a new page
9. Go to layout -> add a 'more' block and search for the transfer tips view
10. Add transfer tips view block to page and save the page
11. Make sure the transfer tips you've added display as an accordion on the page

### CODE REVIEW

**Comment by joewhitsitt** [comment]
taking a look

**Comment by dnkemper** [comment]
S/O to @joewhitsitt and @cory-skeers for this!

**Comment by joewhitsitt** [comment]
pulling down to test (biased)

**Review by joewhitsitt — APPROVED** [review]
Looks good to me and I think this is ready to get Admissions' feedback.

**Review by joewhitsitt — DISMISSED** [review]
Hold up! The admissions meeting revealed some things left to do. I will update the issue summary.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by dnkemper** [comment]
Thank you so much, @joewhitsitt

**Comment by joewhitsitt** [comment]
A few changes and then I will approve. Everything else looks good.

- [x] SEO overrides not visible to webmaster on transfer tip content type. (Add existing field_meta_tags to content type similar to other content types)
- [x] Remove view title as the title override doesn't work (title = none)
- [x] Remove view number of items (remove from allow settings)

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
