### PR TITLE
Refactor uiowa_alerts to allow webmaster control with increased a11y and custom message.

### LINKED ISSUE #1275: As a site owner, I can turn on hawk alerts and/or specify a custom hawk alert message.
- [x] #1277 Ability to select message options: Feed/Feed + Custom Message/Custom Only
- [x] #1278 Color selection? for alert levels
- [x] #1280 Meaningful a11y experience

### LINKED ISSUE #1277: Add ability to select HawkAlert message options: Feed/Feed + Custom Message/Custom Only
As a site owner, I should have the ability to select among the following alert message options:

- Site displays HawkAlerts from a selected feed
- Site displays custom text in the HawkAlert box (no feed)
- Site displays both HawkAlerts from a selected feed AND site displays custom text in the HawkAlert box simultaneously

Parent: #1275

### LINKED ISSUE #1278: Add HawkAlert container color options
As a site owner, I would like the ability to select one of a predetermined set of colors for the background of the HawkAlert.

Potentially:
- Orangeish - Urgent - Safety/Health Alert 
- Grayish - Information Alert

Parent: #1275

### LINKED ISSUE #1280: Identify and address HawkAlert accessibility issues
As a user experiencing the website using a screen reader, I need to be able to consume and understand HawkAlert information as an alert and, conversely, when a HawkAlert is not enabled, I do not hear misleading/confusing alert information

Parent: #1275

### LINKED ISSUE #1312: Change date format in uiowa_alerts module
# Problem

 The current date format for the uiowa_alerts module is: `03-01-2020 7:35 am`

# Proposed Solution

Change to something more readable like: `March 1, 2020 - 7:35am`

### LINKED ISSUE #1323: Refactor uiowa_alerts block to use dependency injection to avoid PHPCS warnings
The uiowa_alerts module defines a custom block plugin that triggers a PHPCS warning:
```
\Drupal calls should be avoided in classes, use dependency injection instead
```

Here is an article I have found describing how it would be done: https://drupal.stackexchange.com/questions/239783/how-to-use-dependency-injection-for-plugins-blocks-drupalformbuilder-and

### PR DESCRIPTION
**Pull request by richardbporter**
- [x] Resolves #1275 
- [x] Resolves #1277 
- [x] Resolves #1278 
- [x] Resolves #1280 
- [x] Resolves #1323 
- [x] Resolves #1312 
- [x] Optimize cache/refresh settings
- [x] Show Hawk Alerts to authenticated users
- [x] ~~Enable in default config and update permission for webmasters~~

### Test
Remote: Inspect alerts already configured https://uiowa.dev.drupal.uiowa.edu/

Local: 
1. `blt dsa`
2. `blt frontend`
3. Go to admin -> config -> University of Iowa Alerts.
4. Make sure 'Display Hawk Alerts' is checked by default.
5. Change any config value.
6. Test that config values are self-explanatory, reflected on the frontend and are config-ignored.

### CODE REVIEW

**Comment by richardbporter** [comment]
@joewhitsitt Feel free to jump in here on the a11y stuff whenever.

**Comment by joewhitsitt** [comment]
@richardbporter are you still looking for me to "jump in here on the a11y stuff"?

**Review by makurj — APPROVED** [review]
Tippie is not using University of Iowa alerts module.

**Comment by makurj** [comment]
Tippie isn’t using University of Iowa alerts module. I approved it.

___________________________________
Makur Jain, Ph.D., M.F.A., M.A., Fulbright
She/her
The University of Iowa
Tippie College of Business
Iowa City, Iowa 52242-1994
319-335-5395 | makur-jain@uiowa.edu

**Comment by richardbporter** [comment]
Some sort of a11y review would be great, @joewhitsitt. Maybe @inspector508 could check out the dev site? (https://uiowa.dev.drupal.uiowa.edu)

**Comment by joewhitsitt** [comment]
I see the role alert and aria-label on the hawk alert, but not the custom message. Additionally, should the aria-label change based on severity or just say 'custom message'

**Comment by joewhitsitt** [comment]
This is also being turned on for all sites and is configurable by webmasters but does not output for uiowa_bootstrap.

**Comment by richardbporter** [comment]
>I see the role alert and aria-label on the hawk alert, but not the custom message.

That should in there now.

>Additionally, should the aria-label change based on severity or just say 'custom message'

I changed it to be set dynamically based on the severity.

**Comment by richardbporter** [comment]
I think we should back this out for UIBS and make it homepage specific.

**Comment by joewhitsitt** [comment]
Can the module enable just be split out for uiowa.edu?

**Review by joewhitsitt — APPROVED** [review]

**Comment by richardbporter** [comment]
I think this is good enough for now. I'll demo it and we can go from there based on feedback.

**Pull request merged**
