### PR TITLE
Deprovision sandboxnext.sites.uiowa.edu

### LINKED ISSUE #7202: deprovision covidresponse.research.uiowa.edu on uiowa
This is a v2 site that we removed the production domain for to deactivate the site upon the owners request. They did not want us to remove it at that time in case they needed to quickly restore it. They have now granted us approval to remove the site.

### LINKED ISSUE #7258: Deprovision physicshalosat.prod.drupal.uiowa.edu on uiowa01
Deprovision physicshalosat.prod.drupal.uiowa.edu on uiowa01

The faculty member associated with this mission has left the university and the content from an old site is no longer available.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/7017
Resolves https://github.com/uiowa/uiowa/issues/7202
Resolves https://github.com/uiowa/uiowa/issues/7258

# Test

- Mainly looking for code review as this updated script has successfully deleted files for a site on Acquia Cloud Next (sandboxnext.sites) as well as two sites on Acquia Cloud Classic. The parent site folder will still exist at mnt/gfs/... but according to the acquia ticket, that is the way it is now based on server permissions.

```
/mnt/gfs/uiowa07.stage/sites/sandboxnext.sites.uiowa.edu/files$ ls -la
total 8
drwxr-xr-x. 2 uiowa07.stage uiowa07    6144 Nov 30 16:47 .
drwxr-xr-x. 4 root          cloudadmin 6144 Nov 30 16:47 ..
```

```
/mnt/gfs/uiowa.test/sites/covidresponse.research.uiowa.edu/files$ ls -la
total 0
drwxr-x--- 2 uiowa uiowa  6 Jan 17 18:34 .
drwxr-x--- 4 uiowa uiowa 38 Apr 30  2020 ..
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
ideally, need to adjust to know if cloud classic or cloud next and then if cloud next adjust the `$env` variable from the default `test` to `stage`. Not sure how to go about this at the moment.

**Comment by joewhitsitt** [comment]
waiting on https://github.com/uiowa/uiowa/pull/7273

**Comment by pyrello** [comment]
Going to code review this

**Review by pyrello — APPROVED** [review]
Reviewed, not tested. Approving based on @joewhitsitt's testing again Cloud Next and Cloud Classic sites.

**Pull request merged**
