### PR TITLE
I2555 srop view

### LINKED ISSUE #2555: Add view to display Grad College SROP Scholars by year
# Story

As a visitor or prospective SROP Scholar I want view lists of past SROP participants so that I can get an idea of what to expect.

Example: https://www.grad.uiowa.edu/ogi/srop/past-scholars

# Proposed solution

- [x] Build a view listing SROP scholars with a contextual filter to limit them to a certain year.
- [x] Add a summary display that shows each year if a contextual argument is not passed.
- [x] Add this to the grad.uiowa.edu split and export config.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2555 

# How to test
1. blt ds --site=grad.uiowa.edu
2. blt frontend
3. Add a few 'people' with the 'Scholar' person type selected and multiple srop sessions selected (some similar, some unique to each individual)
4. go to grad.local.drupal.uiowa.edu/past-scholars
4a. Make sure there's a linked list of the srop sessions that were selected for the newly created people.
4b. Click on list and see that it displays a summary of users that have selected that current session (ex: 2020 (2) if two people have selected the year 2020)
4c. Make sure the 2020 session year URL path displays as: grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2020

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@dnkemper can you explain the current issue keeping this from moving forward? What is the expected?

**Comment by dnkemper** [comment]
@joewhitsitt Sorry! That would probably be helpful haha. Okay, when you add people with the 'scholar' person type selected AND with different SROP Session years, go to grad.local.drupal.uiowa.edu/dei/srop/past-scholars. 

It shows the Session years correctly, but when you actually click on 2020 (or whatever year), the URL shows `grad.local.drupal.uiowa.edu/dei/srop/past-scholars/1` instead of `grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2020` and I'm not sure how to fix it?

**Comment by joewhitsitt** [comment]
Okay, pulling down to take a look.

**Comment by joewhitsitt** [comment]
So the problem is Chosen. It is being added to all select lists and stores the key as 0, 1, ... instead of how the allowed values function writes the key: 2000, 2001.

Screen Shot 2021-01-07 at 10 09 18 AM
wondering if there is a way to have chosen preserve keys or disable it on particular fields where keys are important.

**Comment by cory-skeers** [comment]
> So the problem is Chosen. It is being added to all select lists and stores the key as 0, 1, ... instead of how the allowed values function writes the key: 2000, 2001.
> [...]
> wondering if there is a way to have chosen preserve keys or disable it on particular fields where keys are important.

Possibly related to #2412? Would expand the scope more than if there is a way to preserve keys, etc., but a non-deprecated replacement for Chosen might provide options as well.

**Comment by joewhitsitt** [comment]
Hold the thought. Might not be chosen.

**Comment by joewhitsitt** [comment]
>It shows the Session years correctly, but when you actually click on 2020 (or whatever year), the URL shows grad.local.drupal.uiowa.edu/dei/srop/past-scholars/1 instead of grad.local.drupal.uiowa.edu/dei/srop/past-scholars/2020

I think 7dc6fec fixes it. Doesn't look like there is any content using this field yet in PROD so hopefully there isn't any data loss by this change. Most likely just a resave is needed if the content already exists.
Screen Shot 2021-01-07 at 10 29 48 AM

**Comment by dnkemper** [comment]
@joewhitsitt YOU ARE A GENIUS! THANK YOU THANK YOU THANK YOU!

**Review by joewhitsitt — APPROVED** [review]
approved from a technical standpoint

**Comment by pyrello** [comment]
There is no content yet, this is going to be migrated automatically. I will review this as soon as I am able.

Thanks all!

**Comment by pyrello** [comment]
Pulling down to test.

**Comment by pyrello** [comment]
This looks good. Thanks!

**Pull request merged**
