### PR TITLE
Remove Schemadotorg

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/6847

# How to test

On `main`:

```
ddev drush @default.local sql-drop && ddev drush @default.local cr && ddev blt di --site=default
```

On this branch, repeat and see there is no issue with person entity_view_display configuration.

You can also test events on a site to double-check that removing the schemadotorg function from the sitenow_events module did not cause any issues.

### CODE REVIEW

**Comment by e-marie-w** [comment]
I've tested the default site install and the sites touched by this change and had no issues. Mostly looking for confirmation the function removal does not cause problems.

**Comment by joewhitsitt** [comment]
Maybe the test should be a big `dsa` on the sites and splits affected by the removal.

**Comment by bspeare** [comment]
I'm running a `ddev blt ume sql:drop && ddev blt dsa` on these sites right now:
```
  - default 
  - classrooms.uiowa.edu
  - facilities.uiowa.edu
  - iowasummerwritingfestival.uiowa.edu
  - oniowa.uiowa.edu
  - its.uiowa.edu
  - 91stmeridian.iwp.uiowa.edu
  - admissions.uiowa.edu 
  ```

**Comment by bspeare** [comment]
I was able to sync the sites listed in https://github.com/uiowa/uiowa/pull/6902#issuecomment-1753281635 without any issues.

**Comment by bspeare** [comment]
Fresh install `ddev drush @default.local si sitenow` worked without previous errors too.

**Review by bspeare — APPROVED** [review]
I synced a number of sites without an issue.

**Comment by joewhitsitt** [comment]
Updated https://github.com/uiowa/uiowa/issues/6959 to remove the module from composer instead of update for d10

**Pull request merged**
