### PR TITLE
Added light/white and gray background functionality

### LINKED ISSUE #2387: Add additional background color options for banner block
# Problem

There is not an option to set `Light` or `Gray` background options for the banner block. 

# Proposed Solution

Add `Light` and `Gray` background options for the banner block. 

Screen Shot 2020-10-21 at 2 10 17 PM

### PR DESCRIPTION
**Pull request by ethanstjohn**
Resolves #2387 

Adds Gray and White background functionality.

I believe Gray works, but White shows up as transparent. I would like some help figuring this out if possible.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I don't think the css is needed. If you update your branch, there should be new UIDS styles that cover this if the class names are correct.

**Comment by ethanstjohn** [comment]
I'll give that a shot right after the stand up meeting. Thanks!

**Comment by bspeare** [comment]
@ethanstjohn Sorry for the confusion.   You can map it to this class for now: https://github.com/uiowa/uids/blob/main/src/components/colors/colors.scss#L45 and then it will be updated at a later point.

**Comment by joewhitsitt** [comment]
Don't know if we want to push this option up yet...

Screen Shot 2020-11-03 at 10 03 53 AM

**Comment by bspeare** [comment]
To fix that we need to add the code below to https://github.com/uiowa/uids/blob/main/src/components/banner/banner.scss#L110 

```
  &.bg--light, 
  &.bg--white, 
  &.bg--gray {
```

**Comment by ethanstjohn** [comment]
It's a tad bit white.

**Comment by ethanstjohn** [comment]
I'm unsure of what to change to make it work. Should I keep trying? Or is it an outside problem?

**Comment by ethanstjohn** [comment]
https://github.com/uiowa/uids/pull/402 I cloned down the UIDS code and added the change.

**Comment by bspeare** [comment]
@ethanstjohn I created a new release for this if you to test it with this pr:

- Change uids version number to `3.0.9` in uids_base `package.json`
- Then run yarn upgrade @uiowa/uids
- git commit -m "Bumped up uids version to 3.0.9"

**Review by joewhitsitt — APPROVED** [review]
That's better.

Screen Shot 2020-11-04 at 11 03 50 AM

**Pull request merged**
