### PR TITLE
Update drupal/core to 8.8.4.

### PR DESCRIPTION
**Pull request by richardbporter**
No updates to contrib projects. No config changes.

### CODE REVIEW

**Comment by pyrello** [comment]
`composer install` ran fine. Then I ran `blt dsa` to check the updates on a few site. While it was running on demo.sitenow.uiowa.edu, it failed on `blt drupal:sync:db` with the following error:
```
[error]  Error: Class 'Drupal\entity_usage\EntityUsageBatchManager' not found in Drupal\Component\DependencyInjection\Container->createService() (line 277 of /var/www/uiowa/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php) #0 /var/www/uiowa/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'entity_usage.ba...')
```

I'm going to run it again to see if it works on a subsequent try.

**Comment by pyrello** [comment]
It worked fine on @cogscilang and @home, but then failed on @sitenowdemo multiple times :|

**Comment by pyrello** [comment]
Switching to the latest beta of entity_usage got me past not being able to run `blt dsa`. I checked out the local version of demo.sitenow.uiowa.edu and was able to edit a page with paragraphs. I'm not sure what other tests would be prudent, but it seems like it works okay.

**Review by pyrello — APPROVED** [review]
Looks good. Tested some, but not sure all the ways to test against SiteNow.

**Comment by richardbporter** [comment]
I was able to get demo synced without the entity usage update but had to sql:drop first. Doesn't look like the update has any config changes and auth works on dev. 👍

**Pull request merged**
