### PR TITLE
Admissions - add header and title from mockup

### PR DESCRIPTION
**Pull request by joewhitsitt**
Copied from https://admissions.prod.drupal.uiowa.edu/academics/undergraduate-areas-of-study

### CODE REVIEW

**Comment by bspeare** [comment]
Mind if I add a design adjustment to this?

**Comment by joewhitsitt** [comment]
don't mind at all!

**Comment by bspeare** [comment]
Pulling down to test and add a design adjustment.

**Comment by bspeare** [comment]
@joewhitsitt I'm done adding some styling if you want to review the changes.

**Comment by joewhitsitt** [comment]
Fancy! Thanks!

**Comment by joewhitsitt** [comment]
I assume you approve then?

**Review by bspeare — APPROVED** [review]
Looks good!

**Pull request merged**
