### PR TITLE
Allow pre tags in filtered_html text fields

### LINKED ISSUE #2791: Add support for <pre> tag in text area
# Story

As a site owner I want to be able to use the `<pre>` tag to display pre-formatted content so that I can display content like poetry without having to recreate its structure.

# Proposed solution

Add `<pre>` tag to list of allowed tags for filtered_html and/or minimal_html formats.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2791, relates to #3052 

# How to test

`blt ds --site=writinguniversity.uiowa.edu`
Check that config update completes.
Visit http://org-writinguniversity.local.drupal.uiowa.edu/news/2019/04/jason-r-iowa-three-boxes
See that the text is in a `<pre>` tag, allowing for poetic license in spacing (https://www.writinguniversity.org/blog/jason-r-iowa-three-boxes can be used as reference)

### CODE REVIEW

**Comment by cory-skeers** [comment]
Current styling for `pre`:

```
font-family: monospace,monospace;
    font-size: 1rem;
```

image

Works well for poetry, particularly on a site that is looking to go serif by default. @bspeare curious on your thoughts whether this needs adjustment prior to allowing?

**Comment by joewhitsitt** [comment]
>and/or minimal_html

Do we want to address minimal as well?

**Comment by cory-skeers** [comment]
> > and/or minimal_html
> 
> Do we want to address minimal as well?

Good question! It's at least needed in filtered_html, since it has a use case in articles which have a single text body that likely can't use minimal.

Not sure if it's needed in minimal, but I also have no objections to it. Line breaks are accounted for already for blocks like CTAs.

**Comment by joewhitsitt** [comment]
If the immediate use-case is resolved, I am in no rush to add more to minimal. Reviewed. Not tested. Approved but waiting to hear what Ben has to say.

**Comment by bspeare** [comment]
I think we want to add some different styles for this.  I won't be able to look further into this until later today.

**Comment by bspeare** [comment]
I think the brand team would like to see this poetry formatted in the `<pre>` tag using the `Lora` font: https://github.com/uiowa/uids/pull/483.

**Comment by bspeare** [comment]
Pulling this down to test.

**Comment by bspeare** [comment]
Looks good.  I updated the UIDS version so that the Lora fonts are applied:

Screen Shot 2021-02-15 at 1 13 39 PM

**Comment by bspeare** [comment]
Definitely no rush to add this to minimal.

**Review by bspeare — APPROVED** [review]
Tested this locally and it works!

**Pull request merged**
