### PR TITLE
ITS Sprint 232 Updates

### LINKED ISSUE #5609: Editor user permission role can access some configuration options
# Problem
A user with the "Editor" permission role can access two sections in the Configuration section of Drupal:

- Region settings
- Layout Builder Direct Add

This allows them to change the "Add Component" button text in Layout Builder and/or create Pre-Footer regions and layouts and apply them to the entire site.

## Screenshot:
Screen Shot 2022-08-24 at 9 03 07 AM

# Steps to reproduce
1. Add a user to a site and give them an editor role
2. Login as an admin and masquerade as that user
3. Click the "Configuration" section and see that you can edit these two settings

Or

1. Ask a user who currently has the Editor role assigned to them to login
2. Ask them to go to the Configuration section and see that they can edit these two settings

I've tested this by both masquerading as a user and asking an actual user to look at the "Configuration" setting and was able to reproduce this by following the steps above.

# Proposed solution
Restrict those configuration options to Webmaster, Publisher, or a higher level role.
- Update lb_direct_add with patch or release from https://www.drupal.org/project/lb_direct_add/issues/3305765

### LINKED ISSUE #8087: ITS permissions/roles updates
> Ok, I have some answers and a new request. Yes, can we go ahead and move forward with the update on giving editors the ability to delete any support article. Thank you for looking at that so quickly.
>
> Here's a new request: I think we need a new role. We realized that all publishers have the ability to modify pages that have layout builder. And all Help Desk staff have the publisher role so that they can publish alerts. We like those 15+ people having the ability to edit and publish alerts, but we definitely do not want them to have the ability to modify the homepage or any other top-level pages. I understand we're trying to limit the amount of roles we have and not go back to having 7 or 8 roles like we did on the old site, but this one feels important enough to add. I'd like to limit the amount of folks who could edit these pages down to maybe 4 or 5 max, and I have a list of people who I would need to give access to.
> I'd be happy to have a meeting about this to discuss further. I hope this isn't a big lift.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/8087
Resolves https://github.com/uiowa/uiowa/issues/5609

# ToDo

- [x] Confirm permissions are correct for ITS editor, publisher, help desk roles
- [x] Make sure workflows/workbench email all still work as expected based on roles changing
- [x] Check/update permissions on Admissions and Grad related to fragments
- [x] Check docs about fragments mentioning permissions
- [x] Write up summary of permission adjustments for ITS to review
- [x] Deploy branch to DEV for ITS to review

# Summary of ITS website permissions

Here is an overview of the default permissions:
https://sitenow.uiowa.edu/documentation/user-management-and-roles

_We will be making a change to the default permissions that editors can no longer work with fragments (pre-footer, after content)._

## Editor

Includes SiteNow defaults except:

- Create/edit/delete any support article with the draft/publish/archive workflow transitions. Viewing/reverting/deleting revisions is also included.
- Create/edit/replicate any alert with the draft/submit workflow transitions. Viewing/reverting revisions is also included.
- Edit any service with the draft/publish workflow transitions. Viewing/reverting/deleting revisions is also included.
- Cannot manage main menu items
- Cannot create/edit/delete/revert pages
- Cannot edit the footer contact info block

## Publisher (still expected to be stacked on top of Editor role)

Includes SiteNow defaults except:

- Override "authored by" on support articles
- Cannot work with fragments (pre-footer, after content)
- Cannot edit the footer contact info block

## Help Desk (still expected to be stacked on top of Editor role)

Similar to publisher on SiteNow default except:

- Create/edit/delete/replicate any alert with the draft/submit/publish/archive workflow transitions. Viewing/reverting/deleting revisions is also included.
- Allows sending an email on alert save.
- Cannot create/edit/delete/revert pages
- Cannot manage main menu items
- Cannot work with fragments (pre-footer, after content)
- Cannot edit the footer contact info block

# How to test

```
ddev blt ds --site=its.uiowa.edu
```

- Go to /admin/people to see the list of users. There should be no editor/publisher stacked users. Instead there should be editor/help-desk stacked users.
- Feel free to check the permissions as highlighted above, but this has already been confirmed by ITS.

```
ddev blt ds --site=admissions.uiowa.edu
```

- Confirm that the editor role can still reach the fragments overview page and can create the site-specific fragment, "program"

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Here is a brief summary of the additional permissions a webmaster has over a editor/publisher on the ITS website with this PR's changes:

- Aggregator (RSS Feeds)
- Page
- Service
- Webforms
- Fragments (pre-footer, after content)
- Banner videos
- Manage menus
- Manage all taxonomy vocabularies
- User management
- Advanced SEO settings
- Redirects
- Administer Google Analytics/Google Tag manager (on-site, not upstream)
- Administer SiteNow page, people, articles, dispatch, alerts, search, theme and site settings

**Comment by joewhitsitt** [comment]
Though there are currently no editors on admissions and grad with only that role, i am updating their splits to include access to the fragments overview so that their permissions for stat and program, respectively, can still continue.

**Comment by joewhitsitt** [comment]
https://sitenow.uiowa.edu/documentation/layout-builder/regional-content makes no mention of permissions.

**Comment by joewhitsitt** [comment]
Noticing some redundancy and some leftovers from previous workflows. With the editor/publisher editor/helpdesk stacking in mind, I am going to see about making these a bit leaner for clarity.

For example, helpdesk is basically the ITS publisher role without page abilities and with alert abilities. besides those differences and some service/support article publisher abilities, everything else should come from the editor role. Then remove the default permissions related to contact block, fragments, menu.

**Comment by joewhitsitt** [comment]
Pushing out to DEV ITS for their review.

**Comment by joewhitsitt** [comment]
Ope. Need https://github.com/uiowa/uiowa/pull/8123 before I can deploy out to DEV.

**Comment by joewhitsitt** [comment]
Notified ITS that the changes are in DEV for review and provided a permissions summary similar to the one above.

**Comment by joewhitsitt** [comment]
Hmm. there must be a separate permission to see the links on the admin/config page. if i type the path in as a help desk role I can access and save the config form just fine.

**Comment by joewhitsitt** [comment]
Oops. Forgot to get technical approval on this. Got customer approval and they are expecting to have it deployed today.

**Review by cory-skeers — APPROVED** [review]
Code review looks good. 

Pulled and tested and things worked as expected. Didn't do a lot of specific testing of the various roles for ITS since they've done their own testing, but the update hook ran cleanly and everything appears to be correct. Also checked admissions, and 👍

**Pull request merged**
