### PR TITLE
[Registrar] Accessibility work for academic calendar list

### LINKED ISSUE #7858: Accessibility work for academic calendar list
```[tasklist]
### Accessibility tasks
- [x] Setup callback to announce calendar date changes in the block like https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_hours/src/Form/HoursFilterForm.php#L132
- [x] ensure wcag 2.1 aa accessibility - test on voiceover - webaim/siteimprove/lighthouse/ainspector page scans - voiceover guide https://dequeuniversity.com/assets/pdf/screenreaders/voiceover-macos-guide.pdf
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7858

# How to test

```
ddev blt frontend && ddev blt ds --site=registrar.uiowa.edu && ddev drush @registrar.local uli   /calendars-and-deadlines/academic-calendar
```
- Confirm that category filtering works and chosen is removed
- Confirm that date filters work in Safari and that date filter will show previous events when a past date is selected
- Confirm submit and reset buttons work and show/hide visibility of reset button works
- Confirm that card headings are now h3 instead of h2
- Confirm that "show previous events" checkbox has been removed from sidebar filter
- Confirm that if a session is selected, the start date field is hidden
  - Confirm that if "All Sessions" is selected the start date is visible
- Test with different combinations of block config settings
  - Test with all unchecked and confirm that display is sorted by session and selecting a session will display sessions grouped by session
  - Test with "Group by month" checked and "Expose group by month" checked and confirm that default display is grouped by month and selecting a session will display sessions grouped by month.  Toggle "Group by month" off and confirm that display is sorted by session and selecting a session will display sessions grouped by session
  - Test with "Group by month" checked and "Expose group by month" unchecked and confirm that default display is grouped by month and selecting a session will display sessions grouped by month
- Confirm that end date has been removed and if you think we should remove the rest of the `endDate` functionality in the JS

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling to test.

**Comment by GaryRidgway** [comment]
> Pulling to test.

Thanks Sean!

**Comment by pyrello** [comment]
Moved to draft until we are ready to finish it.

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
> Confirm that end date has been removed and if you think we should remove the rest of the endDate functionality in the JS

Maybe we leave it for now until we can get final confirmation from the registrar team that they are good with it? And add comments that help identify what should be removed eventually.

**Review by pyrello — APPROVED** [review]
This all checks out. Nice work @bspeare!

**Comment by bspeare** [comment]
Thanks @pyrello!

**Pull request merged**
