### PR TITLE
adjust publish_options_allowed_values

### LINKED ISSUE #5740: publish_options_allowed_values cannot be empty for generateSampleValue
# Problem
```
ValueError: array_rand(): Argument #1 ($array) cannot be empty in array_rand() (line 67 of core/modules/options/src/Plugin/Field/FieldType/ListItemBase.php).
```

# Steps to reproduce
Try to open page display settings

# Proposed solution
- There is an upstream issue to allow generateSampleValue to fail (https://www.drupal.org/project/drupal/issues/3208480), but I think we can work around this.
- This function so far is only being used on the page content type so defining the options as default should be fine, leaving the alter within the bundle check.
- Additionally, I think this and several other options_allowed_values functions are setup wrong. https://api.drupal.org/api/drupal/core%21modules%21options%21options.module/function/options_allowed_values/9.2.x
  - Change function to use [\Drupal\Core\Field\FieldStorageDefinitionInterface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Field%21FieldStorageDefinitionInterface.php/interface/FieldStorageDefinitionInterface/9.2.x) and [\Drupal\Core\Entity\FieldableEntityInterface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21FieldableEntityInterface.php/interface/FieldableEntityInterface/9.2.x) 
  - Adjust the call for bundle to `getEntityTypeId`

### LINKED ISSUE #5924: Update our options_allowed_values() code
# Issue

Our docblocks regarding allowed options functionality are incorrect.

https://api.drupal.org/api/drupal/core%21modules%21options%21options.module/function/options_allowed_values/9.2.x

Should be something like this:

```php
/**
 * Set dynamic allowed values for the publish_options field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function mymodule_myselect_options_allowed_values(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, bool &$cacheable): array {
  // Do something.
}
```

# Proposed Solution

Do a code search for `options_allowed_values()` and update our existing code.

### PR DESCRIPTION
**Pull request by joewhitsitt**
fixes #5740
resolves https://github.com/uiowa/uiowa/issues/5924

This function is only being used for the page content type, so the bundle check is redundant but problematic in instances (generateSampleValues) where the bundle info doesn't exist.

# To Test
Before checking out this branch, go to https://default.uiowa.ddev.site/admin/structure/types/manage/page/display and see the WSOD.

- Checkout this branch. `cr`
- Go to https://default.uiowa.ddev.site/node/add/page and see hide title and no sidebar publish options.
- Go to https://default.uiowa.ddev.site/admin/structure/types/manage/page/display and not WSOD
- Additionally, several other `options_allowed_values` functions were updated to be correct

### CODE REVIEW

**Comment by bspeare** [comment]
This works great for `v3`, for `v2` I'm getting this error at`/admin/structure/types/manage/page/display`

```
TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in method_exists() (line 433 of modules/custom/sitenow_paragraphs/sitenow_paragraphs.module).
```

**Comment by pyrello** [comment]
I'm confused by these instructions. On the `main` branch, I can hit https://default.uiowa.ddev.site/node/add/page and I see the options under "Page Options". I'm not able to visit https://default.uiowa.ddev.site/admin/structure/types/manage/page/display. Is that what is being fixed by this?

**Comment by bspeare** [comment]
Yes, the WSOD on https://default.uiowa.ddev.site/admin/structure/types/manage/page/display is what is being fixed here.

**Comment by pyrello** [comment]
> This works great for `v3`, for `v2` I'm getting this error at`/admin/structure/types/manage/page/display`
> 
> ```
> TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in method_exists() (line 433 of modules/custom/sitenow_paragraphs/sitenow_paragraphs.module).
> ```

FWIW, I think this is an unrelated problem and something we failed to find and fix as part of the PHP8.1 upgrade. I have a fix for it though.

**Comment by joewhitsitt** [comment]
Apologies on the test instructions. Had my copy/paste mixed up.

>FWIW, I think this is an unrelated problem.

Yes, this is not the original error, but might have become more visible after the previous issue was fixed.

**Comment by pyrello** [comment]
I have fixed all the unnecessary `method_exists()` checks, but now am getting another error that I think is going to require fixing the other allowed values functions for V2.

**Comment by joewhitsitt** [comment]
Sorry, this was rogue work to begin with, maybe we sprint plan for https://github.com/uiowa/uiowa/issues/5924 then

**Comment by pyrello** [comment]
> Sorry, this was rogue work to begin with, maybe we sprint plan for #5924 then

Eh. We committed to pulling it in when we planned this sprint, so I say we just finish it.

**Comment by pyrello** [comment]
After fixing the other allowed values functions in `sitenow_paragraphs`, I'm still getting:
`ValueError: array_rand(): Argument #1 ($array) cannot be empty in array_rand() (line 67 of core/modules/options/src/Plugin/Field/FieldType/ListItemBase.php).`

The stack trace doesn't seem to contain a reference to the function that is the culprit. How did you trace the issue that was preventing viewing the manage display for pages on V3 sites back to the allowed values function that was causing it, @joewhitsitt?

**Comment by pyrello** [comment]
A side note: These functions all seem to set `$cacheable` to FALSE. First, wondering why these are not considered cacheable? Also, it seems like we could move that into the default value in the function signature (e.g. `&$cacheable = FALSE`), unless we are worried that it sometimes gets passed as TRUE.

**Comment by joewhitsitt** [comment]
>How did you trace the issue

I think I found that generateSampleValue function, set a breakpoint which identified the field name

**Comment by joewhitsitt** [comment]
`sitenow_paragraphs_uip_classes_allowed_values` is the backbone of several field instances and is what is causing the latest issue. looking into it

**Comment by joewhitsitt** [comment]
>A side note: These functions all seem to set $cacheable to FALSE. First, wondering why these are not considered cacheable? Also, it seems like we could move that into the default value in the function signature (e.g. &$cacheable = FALSE), unless we are worried that it sometimes gets passed as TRUE.

If I remember correctly for the ones that have switch statements, we want them to be false so that options for one bundle don't show up in another. For functions that are used on one field only with no conditional, I think they can be cacheable. These functions have been copy/pasted from the beginning so I think moving it should be fine.

**Comment by pyrello** [comment]
My computer restarted, so I'm not in a position to test the update to see if it resolves the WSOD page for V2 sites. However, I'm happy to approve if you got that page to load @joewhitsitt.

**Comment by joewhitsitt** [comment]
>Eh. We committed to pulling it in when we planned this sprint, so I say we just finish it.

Should I continue with updating the others?

**Comment by joewhitsitt** [comment]
Just tested the latest changes with v2 page. Fine. Pulling down Admissions to test the states options and featured image.

**Comment by joewhitsitt** [comment]
Screen Shot 2022-11-16 at 12 28 25 PM
Screen Shot 2022-11-16 at 12 29 05 PM

Still got options

**Review by pyrello — APPROVED** [review]
Approving based on my own testing and that of @joewhitsitt. Thanks to @bspeare for noticing that V2 was still broken.

**Pull request merged**
