### PR TITLE
Feature: Topic collection page

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

```
blt ds --site=sandbox.uiowa.edu
blt frontend
Enable `topic_page` split at admin/config/development/configuration/config-split
drush @sandbox.local cim
```

- Add a topic collection page: https://sandbox.local.drupal.uiowa.edu/node/add/topic_collection
- Add body, tags, and featured image

### CODE REVIEW

**Comment by quamsta** [comment]
Hey all, just requesting a review of this work @bspeare and I did on the newly renamed "Topic collection." Thanks everyone for your help with this!!

**Comment by joewhitsitt** [comment]
Introducing a new content type as part of a feature/site split, the one thing that sticks out is missing permissions config.

We have a wiki article that might be of some help thinking through the pieces (e.g. moderation, sitemap, node revision delete) related to a new content type: https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes

**Comment by joewhitsitt** [comment]
taking a look

**Review by joewhitsitt — APPROVED** [review]
Works as expected. Tested as a webmaster on engineering.

I get a 500 error trying to render a topic collection using one tag on Engineering (Audience: Alumni (2296)). Three view displays are being called with no limit to how many results are shown. I know this could be an issue with other views, but something to keep in mind.

Added a limit to the topic metatag settings so options like schema person and site verification are not presented to webmasters.

**Comment by quamsta** [comment]
> Works as expected. Tested as a webmaster on engineering.
> 
> I get a 500 error trying to render a topic collection using one tag on Engineering (Audience: Alumni (2296)). Three view displays are being called with no limit to how many results are shown. I know this could be an issue with other views, but something to keep in mind.
> 
> Added a limit to the topic metatag settings so options like schema person and site verification are not presented to webmasters.

Thanks Joe, we'll continue iterating on that and possibly impose some limits on the results. Going to squash and merge for now, but yeah, super-good to know that.

**Pull request merged**
