### PR TITLE
Adjust person list media format

### PR DESCRIPTION
**Pull request by pyrello**
# Updates
* Changes card media format for person lists to use `media--circle`, `media--border`, and `card__media--medium`.
* Updates the media view mode for person teaser image to use "Medium - Square."

# How to test

* `blt frontend`
* `blt ds --site=sandbox.uiowa.edu`
* View effect in people block lists: http://sandbox.local.drupal.uiowa.edu/people-directory
* View effect on people page: http://sandbox.local.drupal.uiowa.edu/people
* `blt ds --site=hawkeyemarchingband.uiowa.edu` or your fav v2 site.
* `drush @hawkeyemarchingband.local uli`
* Create a page, add a featured content paragraph and a person list paragraph.
* Check each in the grid and masonry options with and without a section background color and the "hide images" option.

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare Did you mean to add a white background to all the card list items?

**Comment by bspeare** [comment]
@pyrello No, I will remove that.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
Padding for v2 featured content grid with background color still needs adjustment.
Screen Shot 2021-03-02 at 2 41 39 PM

I think this is a change we should communicate so that people can adjust to clipped images. This is a big change visually.
Screen Shot 2021-03-02 at 2 38 02 PM

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I'll work on fixing that.

**Comment by pyrello** [comment]
We switched to small images, but maybe we should switch to medium instead to mitigate some of the impact?

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
Sorry if this was existing and unrelated to this PR. v2 people content block grid section black

Screen Shot 2021-03-03 at 10 45 28 AM

**Review by joewhitsitt — APPROVED** [review]
If https://github.com/uiowa/uiowa/pull/3135#issuecomment-789874182 is unrelated to this PR, I approve with the idea that this can be addressed as a follow-up. Shouldn't merge until we plan to release though.

**Comment by bspeare** [comment]
@joewhitsitt Thanks!  I can fix that issue, I missed that on my demo site.

**Comment by pyrello** [comment]
Thanks for testing, @joewhitsitt! Moving this back to "draft" until our planned release.

**Pull request merged**
