### PR TITLE
Removed aggregator library

### LINKED ISSUE #4340: Aggregator is loading `assets/css/blocks/aggregator.css` that doesn't exist
# Problem
Pages using the Aggregator block are loading `assets/css/blocks/aggregator.css` that doesn't exist.

# Steps to reproduce
View console logs on https://admissions.uiowa.edu/. 

# Proposed solution
Remove `aggregator` library from `uids_base`

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #4340 

# How to test

1. blt ds --site=admissions.uiowa.edu
2. inspect page -> console -> make sure doesn't display error
3. also make sure aggregators still look fly... even though library doesn't exist but if want to go that extra mile why not haha 😆

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I think we should clean up calls to this library since this is removing more than just the call to the css file.

https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.theme#L621

**Comment by dnkemper** [comment]
@joewhitsitt good idea!

**Comment by dnkemper** [comment]
@joewhitsitt only call I could find too

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by dnkemper** [comment]
@joewhitsitt you're just helping me out all over the place this morning! Thank you!

**Review by joewhitsitt — APPROVED** [review]

**Comment by dnkemper** [comment]
@joewhitsitt THANK YOU!

**Pull request merged**
