### PR TITLE
[AFR] File structure

### PR DESCRIPTION
**Pull request by bspeare**
Relates to https://github.com/uiowa/uiowa/issues/7966. 

# How to test

```
ddev blt ds --site=afr.fo.uiowa.edu && ddev drush @foafr.local config:import --source ../config/sites/afr.fo.uiowa.edu --partial -y &&  ddev drush @foafr.local cim -y &&  ddev drush @foafr.local uli /media/add/file
```

- Upload a file
- Confirm that file uploads to `sites/afr.fo.uiowa.edu/files/[filename]` directory

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Seeing it uploaded at `https://foafr.uiowa.ddev.site/sites/afr.fo.uiowa.edu/files/2024-10/FILENAME.pdf`, perhaps 10.3 did something goofy?

**Comment by bspeare** [comment]
@GaryRidgway looks like it needs an additional `ddev drush @foafr.local cim` after importing the split.

**Comment by GaryRidgway** [comment]
> @GaryRidgway looks like it needs an additional `ddev drush @foafr.local cim` after importing the split.

Sounds good! I'll take another crack at it

**Review by GaryRidgway — APPROVED** [review]
IT WORKS

**Comment by bspeare** [comment]
Thanks @GaryRidgway!

**Pull request merged**
