### PR TITLE
Feb 14 Provisions

### PR DESCRIPTION
**Pull request by dnkemper**
Provisioned sites on uiowa01

### CODE REVIEW

**Comment by richardbporter** [comment]
We'll need to add the wildcard SANs to the uiowa01 certificate.

**Comment by richardbporter** [comment]
Be sure to pull now if there are more site creations happening on this PR. Looks like some old Drush local aliases slipped through.

**Comment by briand44** [comment]
I'll work on the cert

**Comment by mark-bennett-uiowa** [comment]
What wildcards need to be added to the uiowa01 cert? I can add them and get a new cert pushed out.

**Comment by briand44** [comment]
*.conference.uiowa.edu, *.course.uiowa.edu, *.lab.uiowa.edu, *.org.uiowa.edu, *.sites.uiowa.edu, *.studio.uiowa.edu

**Comment by briand44** [comment]
thanks

**Comment by mark-bennett-uiowa** [comment]
SSL certificate on uiowa01 has been updated to include wildcards above and installed on the uiowa01 docroot.

**Review by richardbporter — APPROVED** [review]
Thanks.

**Pull request merged**
