### PR TITLE
update robots to disallow saml/login

### PR DESCRIPTION
**Pull request by joewhitsitt**
This may fix some Google warnings we have been getting. If not, a follow up task should be created to consult with the DNA team about adding no-index to their header.

### CODE REVIEW

**Comment by richardbporter** [comment]
Did you see warnings for additional SAML routes? We may want to add:
- saml/metadata
- saml/acs
- saml/sls

**Comment by joewhitsitt** [comment]
No other warnings (gis.sites.uiowa.edu)

I think saml/login is all we _need_ because it is linked from our footer. Are those others routes post-login which Google won't see?

**Comment by richardbporter** [comment]
Yes, you’re right. Nevermind!

-----------------------
Richard B. Porter
ITS Web Services
2800 UCC
(319) 467-1113

**Comment by joewhitsitt** [comment]
well than, can i get an approve?

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
