### PR TITLE
Drupal 8.8

### LINKED ISSUE #677: Evaluate/Test Drupal Core 8.8
## Problem
8.8 is on the way (December 4, 2019) and has a lot of changes, specifically to Media. We need to evaluate the release ahead of time.

The following patches can go away:
- "View output is not used for entityreference options": "https://www.drupal.org/files/issues/2019-08-08/drupal-use_view_output_for_entityreference_options-2174633-323.patch"

## Proposed Solution
Get a config diff, evaluate any changes that we want from the standard profile, revisit our media/wysiwyg issues to see if it is time to switch from entity browser to media core.

Prepare a branch so that we can swiftly adopt the latest release.

## TEST
Last time we missed a lot of configuration, etc.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Establishing a branch for testing and fixes. Resolves #677 

- Updated core and dependencies.
- Adjusted .htaccess without removing customizations.
- Removed entity reference view output patch.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
```------ --------------------------------------------------------------------- 
  16     Call to deprecated function file_scan_directory():                   

         in drupal:8.8.0 and is removed from drupal:9.0.0.                    
         Use \Drupal\Core\File\FileSystemInterface::scanDirectory() instead.  
 ------ --------------------------------------------------------------------- 

 ------ --------------------------------------------------------------- 
  Line   sitenow_seo/sitenow_seo.module                                 
 ------ --------------------------------------------------------------- 
  28     Call to deprecated function pager_find_page():                 
         in drupal:8.8.0 and is removed from drupal:9.0.0. Use          
         \Drupal\Core\Pager\RequestPagerInterface->findPage() instead.  
 ------ --------------------------------------------------------------- 
```

**Comment by joewhitsitt** [comment]
I am beginning to think that we don't use media core yet for ckeditor media placement.

**Comment by joewhitsitt** [comment]
Screen Shot 2019-12-13 at 11 24 58 AM

**Comment by richardbporter** [comment]
Following the instructions required updating all dependencies: https://support.acquia.com/hc/en-us/articles/360039081454-Upgrading-from-BLT-10-x-to-11-x

**Comment by joewhitsitt** [comment]
Screen Shot 2019-12-19 at 12 11 07 PM

**Comment by richardbporter** [comment]
Tested fresh install, BLT commands. All seems normal. We should merge for further testing on dev.

**Comment by richardbporter** [comment]
Got a config mismatch on brand.uiowa.edu during a DSA:
```
--------------------------------------- ----------- 
  Name                                    State      
 --------------------------------------- ----------- 
  core.entity_form_display.node.lockup.   Different  
  default                                            
  system.mail                             Different  
  views.view.lockup_moderation            Different  
  views.view.lockups                      Different  
 --------------------------------------- ----------- 
```

**Comment by joewhitsitt** [comment]
i think this is good from the custom split side of things. i opened up brand and hr and poked/saved content without white-screens. i didn't know if the config sync changes were good to go.

**Comment by joewhitsitt** [comment]
This bothers me, but it looks like the correct workflow is used in the UI: https://github.com/uiowa/uiowa/pull/811/files#diff-0dff385c28d3c6884eb4c4197bab8200R12

**Pull request merged**
