### PR TITLE
Padding adjustments for bg-colors

### LINKED ISSUE #2053: Default padding for sections with background color is not being applied if "extended width container" is selected
# Problem 

Selecting "Extended width container" in the layout builder styles removes the default padding for sections using a background color:

Screen Shot 2020-08-20 at 12 58 21 PM
Screen Shot 2020-08-20 at 12 48 51 PM

# Proposed solution

Adjust css in `global.scss`.

### LINKED ISSUE #2054: Add default padding to text area block if it is used with a background color
# Problem

If you add a background color to the text area block, it will appear without default padding. 

Screen Shot 2020-08-20 at 1 19 38 PM

# Proposed solution

Add default padding to text area block if it is used with a background color. 

Screen Shot 2020-08-20 at 1 19 58 PM

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2054. Text Area blocks currently don't receive padding when a bg color is added, leading the text to run up against the bg boundary.

Resolves #2053 . Sections with 'extended-width' style losing top and bottom padding, leading contents to run up against edges. This adds in a $desktop-width-gutter padding in these cases.

Resolves padding issue with (vertical) card bodies.

## Testing
Sync, blt frontend
Add text areas with and without background colors, on sections with and without backgrounds.
Check that there is appropriate spacing (or if no bg-color, no extra spacing) between the text and the box boundaries.

Add sections with and without the 'extended-width container' style, with and without addition to a background color.
Check that the spacing is appropriate for each of the 4 above combos.

Add cards onto a section with a background color or pattern, with or without the card border style override.
Check that the spacing around the card body is appropriate, and matches spacing on non-bg sections.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
I have tested this and the former half with the background color padding seems to work, however i found that the padding for the extended-width-container worked only below 1350px. 

This is 1349px width
Screen Shot 2020-08-24 at 3 38 01 PM

this is 1350px width
Screen Shot 2020-08-24 at 3 38 10 PM

**Comment by joewhitsitt** [comment]
Could this be extended to cover the card component as well?

Screen Shot 2020-08-24 at 4 21 16 PM


https://github.com/uiowa/uiowa/pull/2032#issuecomment-678425668

**Comment by cory-skeers** [comment]
@joewhitsitt Absolutely.

@GaryRidgway Thanks for testing and catching that!

**Comment by cory-skeers** [comment]
This has been updated and is ready for testing again.

@GaryRidgway If you have time to check the breakpoint issue (for sections w/bg and extended width) and see if it's properly resolved, I'd appreciate it!

@joewhitsitt This addresses the card-body for vertical cards, but not for horizontal cards. They'll need a bit of a different approach because of the image placement.

@bspeare Does your work on #2076 overlap with these padding adjustments for sections with backgrounds?

**Comment by bspeare** [comment]
@cory-skeers, Yes the work in #2076 will unfortunately overlap/overwrite some of these padding adjustments.   I have a padding adjustment for horizontal cards on https://github.com/uiowa/uids/pull/301.    I will pull this down and test the padding with the horizontal card.

**Comment by cory-skeers** [comment]
Sounds good, @bspeare! This PR is a pretty light one--if the issues it addresses aren't already addressed in #2076, it might be easier to roll these few issues into that one as well.

**Comment by bspeare** [comment]
@cory-skeers I might prefer to close this and fold these fixes into #2076 - do you mind?

**Comment by cory-skeers** [comment]
@bspeare Nope! I think that's a good way to go.

**Comment by bspeare** [comment]
Closing this and moving the work to https://github.com/uiowa/uiowa/pull/2076.

**Pull request closed without merging**
