### PR TITLE
Upgrade to Drupal 9.3.5 with dependencies.

### LINKED ISSUE #4411: Update Drupal version to 9.3
Blocked until December 8, 2021

Currently unavailable,  [9.3.0 alpha version](https://www.drupal.org/project/drupal/releases/9.3.0-alpha1) is available is not recommended for production sites. Wanted to bring attention to this since a lot of patches I looked at use version 9.3

# Proposed Solution

Wanted to add this as a reminder. Might need Rick to add more since he's the master of this.

- [x] Check dependency compatibility and make note of dependencies that need to be updated at the same time.
- [x] Read all the release notes and make note of any changes that might affect our codebase: https://www.drupal.org/project/drupal/releases/9.3.0 and https://www.drupal.org/project/drupal/releases/9.3.1
- [x] Then test out our functionality
- [x] ~Add/Test: https://www.drupal.org/project/drupal/issues/3195764#:~:text=USER-,Comment,%2317,-dwisnousky%20Credit~ Not needed. Fixed. 
- [x] Remove from composer.json:`"Fix Webform ui button contrast deprecation": "https://www.drupal.org/files/issues/2021-11-07/webform-button-contrast-3195764-12.patch"` - Related to patch above
- [x] Look at other composer.json patches that might be incompatible w/ v9.3

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #4411 

# How to test

- `composer install`
- Test that default content is created correctly on site install (related to "Expose Layout Builder data to REST and JSON:API" patch).
- Test that entity reference filters for views (related to "Add Views EntityReference filter to be available for all entity reference fields" patch)
- Sync a bunch of sites! Maybe one or more of:
```
  - default
  - admissions.uiowa.edu
  - amcs.uiowa.edu
  - brand.uiowa.edu
  - coronavirus.uiowa.edu
  - dentistry.uiowa.edu
  - genetics.grad.uiowa.edu
  - grad.admissions.uiowa.edu
  - grad.uiowa.edu
  - hawkeyemarchingband.uiowa.edu
  - hr.uiowa.edu
  - icsa.uiowa.edu
  - ighn.international.uiowa.edu
  - immuno.grad.uiowa.edu
  - iowasuperfund.uiowa.edu
  - pharmacy.uiowa.edu
  - neuroscience.grad.uiowa.edu
  - policy.clas.uiowa.edu
  - presidentialsearch.uiowa.edu
  - recserv.uiowa.edu
  - sitenow.uiowa.edu
  - sppa.uiowa.edu
  - tippie.uiowa.edu
  - transportation.uiowa.edu
  - uiowa.edu
  - uipress.uiowa.edu
```
- Test stuff.

Helpful diff tip:
`git diff --color-moved=plain main...drupal_9_3 -- config/`
`git diff --color-moved=plain main...drupal_9_3 -- docroot/`

### CODE REVIEW

**Comment by pyrello** [comment]
The last time I ran the `blt uiowa:usplits:site` command, it seemed to work for the first site, Admissions, but then was not finding the alias for subsequent sites. So that needs some troubleshooting. There is also a `config:status` command being run at the end, mostly for me to be able to see what is happening, but that probably isn't necessary.

Once the split stuff is working, then I think this is mostly ready to go. I made note above of the patches that changed and the related functionality that should be tested.

**Comment by richardbporter** [comment]
I'm having to change the `Multisite::getIdentifier` homepage exception to `home` from `uiowa` to the get the commands to work. This changes the internal domains to `home.uiowa.ddev.site`, `home.dev.drupal.uiowa.edu`, etc.

**Comment by richardbporter** [comment]
>[Manually move admissions migrate_drupal.settings config hash... shrug)

Realized migrate are not stored in config dir so reworking the command to find those and export.

**Comment by joewhitsitt** [comment]
>Test that default content is created correctly on site install (related to "Expose Layout Builder data to REST and JSON:API" patch).

I don't see any noticeable issues with site install/default_content.

**Comment by joewhitsitt** [comment]
Ran a site export after syncing Admissions:

```
+    318: 'create transfer_tips content'
+    319: 'delete any area_of_study content'
```

I am confused. Are permissions and stuff supposed to be keyed now or not?

**Comment by richardbporter** [comment]
> Ran a site export after syncing Admissions:
> 
> ```
> +    318: 'create transfer_tips content'
> +    319: 'delete any area_of_study content'
> ```
> 
> I am confused. Are permissions and stuff supposed to be keyed now or not?

I am too. I saw that once but then thought another cex changed it back.

**Comment by richardbporter** [comment]
> Ran a site export after syncing Admissions:
> 
> ```
> +    318: 'create transfer_tips content'
> +    319: 'delete any area_of_study content'
> ```
> 
> I am confused. Are permissions and stuff supposed to be keyed now or not?

Also, all site splits should be exported as part of this. Shouldn't be necessary to export again. What diff were you seeing?

**Comment by joewhitsitt** [comment]
I figured trying to export again i should see identical:

        modified:   config/sites/admissions.uiowa.edu/config_split.patch.user.role.editor.yml
        modified:   config/sites/admissions.uiowa.edu/config_split.patch.user.role.webmaster.yml

**Comment by joewhitsitt** [comment]
you keep moving the goal posts!

**Comment by joewhitsitt** [comment]
I ran a dsa on all these sites, no import errors.
```
  * @admissions.prod => @self
  * @amcs.prod => @self
  * @brand.prod => @self
  * @coronavirus.prod => @self
  * @education.prod => @self
  * @gradgenetics.prod => @self
  * @grad.prod => @self
  * @hr.prod => @self
  * @icsa.prod => @self
  * @internationalighn.prod => @self
  * @gradimmuno.prod => @self
  * @iowasuperfund.prod => @self
  * @international.prod => @self
  * @pharmacy.prod => @self
  * @claspolicy.prod => @self
  * @presidentialsearch.prod => @self
  * @sitenow.prod => @self
  * @tippie.prod => @self
  * @transportation.prod => @self
  * @home.prod => @self
  * @iwpwhitmanweb.prod => @self
```

However, running `blt ume config-split:export site` on the same sites, I still get that permissions modification for editor and webmaster on admissions.

For a v2 test, I get a diff on export:

```
diff --git a/config/features/sitenow_v2/config_split.patch.core.entity_form_display.node.page.default.yml b/config/features/sitenow_v2/config_split.patch.core.entity_form_display.node.page.default.yml
index 96a1a162d..c4b1abf36 100644
--- a/config/features/sitenow_v2/config_split.patch.core.entity_form_display.node.page.default.yml
+++ b/config/features/sitenow_v2/config_split.patch.core.entity_form_display.node.page.default.yml
@@ -2,7 +2,6 @@ adding:
   dependencies:
     config:
       - field.field.node.page.field_page_content_block
-      - field.field.node.page.layout_builder__layout
     module:
       - paragraphs
   content:
```

Should I disregard these?

**Comment by richardbporter** [comment]
>Should I disregard these?

Probably not. It'd be worth understanding both more.

**Comment by joewhitsitt** [comment]
Lockup generator failed. Looking into it.

I think i fixed one issue (will push soon) but ran into another:

~~https://www.drupal.org/project/reroute_email/issues/3261064~~, now it is complaining about this: ~~https://www.drupal.org/project/reroute_email/issues/3254806~~

**Comment by richardbporter** [comment]
I will work on resolving the conflicts and updating the uipress config split.

**Comment by richardbporter** [comment]
@dnkemper if you have time, could you double check the functionality from #4702 on this PR? I kinda struggled with the merge. :/

**Comment by richardbporter** [comment]
Getting a config diff on dev for reroute_email.settings:
```
 ------------------------ ----------- 
  Name                     State      
 ------------------------ ----------- 
  reroute_email.settings   Different  
 ------------------------ ----------- 
```

Importing doesn't seem to work though. Here is the diff:

```
   default_config_hash: FWyW0pDoSvPRtqOVlIbk4PxTLiS9S_Ng7zS1JOflWVE
 enable: true
 address: ''
+whitelist: ''
 description: false
 message: true
 mailkeys: ''
-whitelist: ''
```

**Comment by joewhitsitt** [comment]
brand lockup stuff seems to now be working from start to finish

**Comment by dnkemper** [comment]
Everything looks good for uipress book (alias got lost somewhere along the way but fixed now) - at least that I can see. @e-marie-w might have better insight on this, but tested everything I could think of.

**Comment by joewhitsitt** [comment]
tested admissions entity print links (https://admissions.uiowa.ddev.site/areas-of-study/print-links)

**Comment by joewhitsitt** [comment]
hey, guess what. media library now has per instance alt text!
Screen Shot 2022-02-16 at 9 40 38 AM

**Comment by dnkemper** [comment]
> hey, guess what. media library now has per instance alt text! Screen Shot 2022-02-16 at 9 40 38 AM

GAME CHANGER

**Review by joewhitsitt — APPROVED** [review]
i've done all of the testing i can stomach at this time. sounds like folks have tested other parts as well and aren't saying to stop moving forward.

is this an off-hours type release though?

**Comment by e-marie-w** [comment]
UI Press book content type looking good and working as expected, awesome job!

**Comment by dnkemper** [comment]
I've tested admissions, hawkeyemarchingband, brand, grad, uipress, sandbox... hours upon hours. Agree with Joe.

**Comment by dnkemper** [comment]
Even if it's an off hour release, can we merge it ASAP? So we can fix existing PR's/get that over with?

**Comment by richardbporter** [comment]
>hey, guess what. media library now has per instance alt text!

 Cool! We should remember to demo that. 

Thanks all for testing. I haven't produced a WSOD locally yet but off-hours might be best still.

**Pull request merged**
