### PR TITLE
Accordion accessibility

### PR DESCRIPTION
**Pull request by GaryRidgway**
Relates to https://github.com/uiowa/uiowa/issues/5106
Added accessible label to accordion header to make sure that it was properly added into the aria mapping. Ran lighthouse, increased accessibility score.

## To test

- sync down sandbox
- go to this page https://sandbox.uiowa.ddev.site/really-cool-accordions
- run a lighthouse scan (This may only work in chrome??) (inspect > click the arrows in the row with the elements tab > Lighthouse > Generate report)
- under the accessibility section check that we are not getting dinged for `Make sure the element is contained by another element that has the required context role.`
- PROFIT

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Does this work without the role presentation? Seems weird to me to mark a heading as presentational

>Writing `<h2 role="presentation">Democracy Dies in Darkness</h2>` removes the heading semantics of the `<h2>`element, making it the equivalent of `<div>Democracy Dies in Darkness</div>`. The heading role semantics are removed, but the content itself is still available. - https://developer.mozilla.org/en-US/docs/Web/accessibility/ARIA/roles/presentation_role

**Comment by e-marie-w** [comment]
> Does this work without the role presentation? Seems weird to me to mark a heading as presentational

At the moment the presentation role is the fix. It seems like the nesting is causing the problems, with the `role=tab` items not being children of `role=tablist`. `role=presentation` keeps the heading content available but doesn't make it part of the accessibility tree, allowing the `role=tab` items to be seen as children instead of grandchildren. 

I based this off of https://www.w3.org/WAI/standards-guidelines/act/rules/ff89c9/proposed/#test-cases, passing example 3. That example is using list and list-items instead of tablist and tabs, but it seems to work the same. 

Removing the heading semantic but leaving the content is weird, but I don't think it causes problems. Let me know if I'm wrong, I don't completely follow if there's consequences of that part. 

We could try the `aria-owns` attribute used in passing example 5 instead?

**Comment by joewhitsitt** [comment]
>We could try the aria-owns attribute used in passing example 5 instead?

Might be tricky to get all of the child information for that up to the parent.

The role presentation on a heading essentially removes the work we did with the headline helper to get the correct headings for child items and makes the document more navigable by screen readers.

So while this might fix one a11y issue, it sends us back a step for an a11y feature.

I'd like to find some time to pull this down

**Comment by e-marie-w** [comment]
> The role presentation on a heading essentially removes the work we did with the headline helper to get the correct headings for child items and makes the document more navigable by screen readers.

> So while this might fix one a11y issue, it sends us back a step for an a11y feature.

Oh shoot, thanks for catching this! If I have time when you pull this down I'd be interested in pairing.

**Comment by joewhitsitt** [comment]
I am not going to have time today.

If nesting is the issue, should we be trying to find a way to bring role tab to the heading element, not the button within it? I am sure there is a javascript reason for the button, but how easy would it be to change that besides revisiting in UIDS?

Or is this an issue we address later in https://github.com/uiowa/uiowa/issues/4004

**Pull request closed without merging**
