### PR TITLE
Block form missing styles

### LINKED ISSUE #3224: Articles and events list block edit form does not display selected layout builder styles after saving page
# Problem
Articles and events list blocks do not display selected layout builder styles after saving page.

# Steps to reproduce
Edit the first articles block on http://sandbox.local.drupal.uiowa.edu/articles.    Hide the images and description and save the page.   Edit the page again and try to adjust the same styles and it should appear empty:

Screen Shot 2021-03-10 at 3 31 47 PM

# Proposed solution
- Logs show:`Notice: Undefined index: #description in Drupal\uiowa_core\HeadlineHelper::getElement() (line 67 of /var/www/uiowa/docroot/modules/custom/uiowa_core/src/HeadlineHelper.php)` that could be causing the issue.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #3224 

# How to test

TBD

### CODE REVIEW

**Comment by cory-skeers** [comment]
On initial work, this should fix the log error mentioned in #3224, but not the main bug.

On the plus side, field descriptions were missing, and this'll fix that now too.

**Comment by cory-skeers** [comment]
Looks like the issue comes in when there are 2 or more styles chosen.

**Comment by pyrello** [comment]
I'm going to take a look at this.

**Comment by pyrello** [comment]
Per #3224, I think this is ready for testing.

**Review by bspeare — APPROVED** [review]
Tested locally and I was able to apply and remove multiple styles.  Thanks!

**Pull request merged**
