### PR TITLE
Article Contact reference field

### LINKED ISSUE #5999: Article contact for SiteNow Articles
# Story

As an editor creating articles, I would like the ability to reference a person as a contact for an article so that readers with questions know who to reach out to.

# Additional Information

# Proposed solution

- Use some of the Iowa Now work and move it to default, but still keep the extra Iowa Now functionality separate.
  -  Person reference only - allows multiple
- Check splits and features for article content type
- Possibly reorganize fields on form display

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #5999 

# How to test

`git checkout article-contacts && git pull && ddev blt ds --site=default && ddev drush @default.local uli`
Create an article or edit an existing article
Add existing Persons as a contact and/or create new contacts from the field
Check that the contact(s) show up on display

`ddev blt ds --site=now.uiowa.edu && ddev drush @now.local uli`
Create an article or edit an existing article
Add existing Persons as a contact and/or create new contacts from the field
Add existing Contacts as a contact and/or create new contacts from the field
Proofread the help text, check that it is clear and informative
Check that the contact(s) show up on display
Repeat for creating People and adding contact references to them

Check that features/splits that touch articles also work with the new contact (periodical, 91stmeridian.iwp, and iisc, but double check that there weren't others missed).

> Possibly reorganize fields on form display

No changes have been made in reorganizing the form display here; primarily, the addition of the new Point of Contact field has been added as collapsed by default in order to avoid mussing things up too much. Keep this in mind while testing, if there are other thoughts of ways to clean up/optimize the form display.

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
Pulled for testing.

**Comment by mark-bennett-uiowa** [comment]
I pulled this for some initial testing. For Default, everything appears to be working correctly. Here is the individual test article with authors and contacts appearing:
Screen Shot 2022-12-15 at 10 32 30 AM

Here is the article in the list view, with no contacts appearing:
Screen Shot 2022-12-15 at 10 32 58 AM

I then pulled down Iowa Now to test there. Jane Doe is a contact, Jeneane Beck is a person. This also appears to be working correctly, with some concerns (see below):
Screen Shot 2022-12-15 at 10 38 46 AM

What I did notice was the addition of the select list of Person vs Contact. This seems okay, maybe add additional spacing between the select and the "Add new Point of Contact" button and update the field description above to mention this additional select list (??):
Screen Shot 2022-12-15 at 10 36 39 AM

The issue came when adding a new Person vs Contact. The Person form asks for First Name, Last Name, Email, and Phone. The Contact asks for Name, Email, and Phone. I checked the existing content types, and this appears to be working, but is this intended? Is there a reason why it isnt separated into First Name and Last Name??
Screen Shot 2022-12-15 at 10 46 16 AM

Screen Shot 2022-12-15 at 10 46 03 AM

**Comment by cory-skeers** [comment]
> The issue came when adding a new Person vs Contact. The Person form asks for First Name, Last Name, Email, and Phone. The Contact asks for Name, Email, and Phone. I checked the existing content types, and this appears to be working, but is this intended? Is there a reason why it isnt separated into First Name and Last Name??

Yep, that should be the expected functionality for Iowa Now only. They have regular person contacts, and then contacts that are departments, units, etc. that go by a single field name.

> This seems okay, maybe add additional spacing between the select and the "Add new Point of Contact" button and update the field description above to mention this additional select list (??):

This is a weird one: the select list only applies to adding a new point of contact, where you need to decide whether they will be created as a Person or Contact node, but when adding an existing point of contact, the autocomplete matches either type. The lack of spacing and 'attaching' it to that button is ideally a visual indicator of this, but it is confusing. Updating the help text could probably help a lot.

**Comment by cory-skeers** [comment]
This had some in-progress reviewing completed, but I believe is now ready for complete review.

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Added the field to the sppa article form as that is a complete split item. Looks good. Glad we could reuse some functionality here!

**Pull request merged**
