### PR TITLE
Update drupal core dependencies to 9.5

### LINKED ISSUE #6061: Update to Drupal core 9.5
# Motivation
Prior to updating to Drupal 10, we should update to 9.5 to ensure the smoothest possible transition.

# Proposed solution

```
ddev composer require drupal/core-recommended:9.5.0 drupal/core-composer-scaffold:9.5.0 drupal/core-project-message:9.5.0 --update-with-all-dependencies
```

See https://www.drupal.org/docs/updating-drupal/updating-drupal-core-via-composer#s-unpinning-from-a-specific-version-of-core. Note that the above will only work if all of our dependencies are compatible with Drupal 9.5.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #6061

# How to test

```
ddev blt ds --site sandbox.uiowa.edu && ddev drush @sandbox.local uli
```
- Spot check functionality to try to find regressions.
- Attempt to review the changes: https://git.drupalcode.org/project/drupal/-/compare/9.4.14...9.5.9

## LB off-canvas resizing regression
- https://sandbox.uiowa.ddev.site/node/1386/layout
- Click 'Add section' and note the width of the off-canvas tray
- Click 'Add block' and note that it displays in a wider tray
- Click 'Configure' on an existing block and note that it displays in a wider tray

### Updating media attributes in layout builder blocks works

- https://sandbox.uiowa.ddev.site/node/1606/layout
- Add a text area block
- Add an image
- Save block
- Configure the block you just saved
- Change the image "Display" to another format and save the block
- Configure the block you just updated
- Confirm that your changes are saved

### Selected style options in list blocks are preserved when pager links are clicked

- https://sandbox.uiowa.ddev.site/debug-one-article-list-block or https://sandbox.uiowa.ddev.site/debug-one-people-list-block
- Click layout tab, configure the list block
- Check the checkbox to "Show pager" and save the block
- Click through pager links to ensure that displayed content matches style options
- Optionally, update the block to change the style options, save the block, and check clicking pager links again

### Unique ID feature for blocks
- Add a unique ID to the block you were just editing
- Save the block, save the layout
- Confirm that the ID is rendered in the HTML markup for the block
- Edit the layout, edit the block
- Change the unique ID, save the block, save the layout
- Confirm that the new ID is rendered in the HTML markup for the block

### Unpublished node in menu selection
- https://sandbox.uiowa.ddev.site/admin/structure/menu/manage/main/add
- In the "Link" field, start typing "Link for" and confirm that "Link for unpublished auto-complete" shows up as a suggestion and can be selected.

### Able to access the LB entity from `'#entity'` when in the LB context
- The best way I could think of to test this is to set a breakpoint here: https://github.com/uiowa/uiowa/blob/6c61debb1e89f57bf8301d25e0f3738e11b2a12d/docroot/themes/custom/uids_base/uids_base.theme#L515 and then ensure that the `$node` object is populated when visiting the Layout tab on a page.

### CODE REVIEW

**Comment by pyrello** [comment]
I thought that this was close to being ready, but it turns out that hard-coding the width means setting it in a lot of places. I think the only places that really matter are the add block and update block links. I've figured out how to set it for the add block links, but cannot for the life of me figure out how to set it for the update block links. The update block links are contextual links and we do not have access to them in a meaningful way in our `LayoutBuilderPreRender` class.

**Comment by pyrello** [comment]
I added the following code and set breakpoints in each one:
```php
/**
 * Implements hook_contextual_links_alter().
 */
function layout_builder_custom_contextual_links_alter(array &$links, $group, array $route_parameters) {
  $foo = 'bar';
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function layout_builder_custom_contextual_links_view_alter(&$element, $items) {
  $foo = 'bar';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function layout_builder_custom_preprocess_layout_builder_choose_block_list(&$variables, $element) {
  $foo = 'bar';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function layout_builder_custom_preprocess_links(&$variables) {
  $foo = 'bar';
}
```

I was not able to get any of them to trigger their breakpoint when viewing Layout Builder (or viewing the page for that matter). I'm stuck on this for now.

**Comment by cory-skeers** [comment]
> I was not able to get any of them to trigger their breakpoint when viewing Layout Builder (or viewing the page for that matter). I'm stuck on this for now.

I was able to set the `layout_builder_custom_contextual_links_alter` and `layout_builder_custom_preprocess_links` and get them to trigger on loading the page, but am not seeing the right links in either. The latter seems to hit the links for adding new that is already covered elsewhere, and the former seems to get the other contextual links (like configure block for the footer blocks), but I haven't been able to find any of the layout builder block config links in it.

**Comment by pyrello** [comment]
I'm not sure why this wasn't getting triggered before in xdebug for me before, but it seems that after the page is loaded the contextual links get add in a followup AJAX request. Today it was triggering in xdebug for me and I could see what I needed to be able to add the width to the configure links.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
i can provide more detail tomorrow, but i am getting config import errors during a big dsa.

hawkeyemarchingband, admissions, grad.admissions so far. entity_view_display of some sorts so far.

**Comment by joewhitsitt** [comment]
It looks like I am encountering these config diff issues on `main` so not related to this PR. Sorry for the noise. Not sure why we aren't seeing these on deployment.

**Comment by pyrello** [comment]
Hmm... I tried running `ddev blt ds --site hawkeyemarchingband.uiowa.edu` on both this branch and `main`. I got a config diff warning on this branch and not on `main`.

**Comment by joewhitsitt** [comment]
🤦 i didn't actually switch to main before i ran it... i properly setup my `main` and ran a few sites with no issues.

So, should we start evaluating the config changes, package them up and commit?

**Comment by pyrello** [comment]
> 🤦 i didn't actually switch to main before i ran it... i properly setup my `main` and ran a few sites with no issues.
> 
> So, should we start evaluating the config changes, package them up and commit?

I was able to fix this on HMB by running `ddev drush @hawkeyemarchingband.local cex` and then undoing the default config file deletion. It also updated a file in the v2 split, which I kept the changes for. After that I was able to do a clean sync.

**Comment by pyrello** [comment]
Converting back to draft to investigate if there are additional config changes that need to happen.

**Comment by joewhitsitt** [comment]
Should we try `uiowa:usplits:feature` and `uiowa:usplits:site` for this?

Update: Trying `uiowa:usplits:feature` to see what it comes up with.

**Comment by joewhitsitt** [comment]
There is some layout builder noise to remove from the export, but I see this in sitenow_v2

```
 dependencies:
   config:
     - field.field.node.page.body
+    - field.field.node.page.field_after_content_override
     - field.field.node.page.field_featured_image_display
     - field.field.node.page.field_image
     - field.field.node.page.field_meta_tags
     - field.field.node.page.field_page_content_block
+    - field.field.node.page.field_pre_footer_override
     - field.field.node.page.field_publish_options
     - field.field.node.page.field_tags
     - field.field.node.page.field_teaser
 ```
Should I commit it based on https://github.com/uiowa/uiowa/pull/6526/commits/2f5a20d5bbd7da66e4130991d0233a618bea6e3b ?

**Comment by pyrello** [comment]
@joewhitsitt I'm not clear on what you are asking.

**Comment by joewhitsitt** [comment]
I guess I am trying to confirm that these fields should be included as dependencies since your commit introduces them.

**Comment by pyrello** [comment]
> I guess I am trying to confirm that these fields should be included as dependencies since your commit introduces them.

That commit is what cleaned up HMB for me, so I'd assume it would be necessary for any other V2 sites as well.

**Comment by joewhitsitt** [comment]
noticed the same dependencies flagged for HR (complete) so I went ahead and added them to the sitenow_v2 version.

**Comment by pyrello** [comment]
Okay, I was getting confused because it seemed like we had two commits that were adding the same thing. But in mine, its adding those fields to the `hidden` section and in yours it is adding them as dependencies.

**Review by joewhitsitt — APPROVED** [review]
Short of running another big dsa, I am no longer getting sync config errors on the usual suspects.

I previously went through the testing instructions and those were looking good.

Did not read through the changelog

**Comment by joewhitsitt** [comment]
Sounds like @pyrello is looking into the effects of bringing back the handle

https://github.com/uiowa/uiowa/issues/6061#issuecomment-1644026896

**Comment by joewhitsitt** [comment]
Pulled https://github.com/uiowa/uiowa/pull/6526/commits/27df00fa0244c4adc07541d68cda82343e578107 and like it this way! Core folk doesn't know what they are missing.

**Pull request merged**
