### PR TITLE
Implement google search schema for uiowa.edu frontpage

### LINKED ISSUE #1326: [Task] Implement Google Search Schema on new uiowa.edu home page
Add Google Search schema to uiowa.edu.

- [x] @mjoneill to capture specification/code for search schema
- [ ] Developer add it to site

Parent: #1290

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves: #1326 

## Test
- Successfully pull and apply schema_metatag patch.
- Import uiowa.edu specific front page metatag configuration.
- See the added schema info in the `<script type="application/ld+json">` tag that matches what is in the issue text file #1326

### CODE REVIEW

**Comment by richardbporter** [comment]
If you push this to dev, @mjoneill could test it there.

**Comment by joewhitsitt** [comment]
@mjoneill this is now available on the DEV site for review

**Comment by joewhitsitt** [comment]
I got comment approval for this: https://github.com/uiowa/uiowa/issues/1326#issuecomment-610961283, can i get github approval?

**Review by pyrello — APPROVED** [review]
Reviewed not tested.

**Pull request merged**
