### PR TITLE
Hotfix LBC form alter fatal error.

### LINKED ISSUE #2085: Error: Call to a member function bundle() on null in layout_builder_custom_form_alter line 84
## Problem

As a webmaster I can't add any of the "More" blocks due to this console error.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2085 

I noticed its possible to add a collection with no items in it. While I'm in here, I can make the collection items field required? Or does that cause other problems?

### CODE REVIEW

**Comment by richardbporter** [comment]
Sorry for imposing my whitespace OCD. I tend to add whitespace subconsciously. :)

**Comment by cory-skeers** [comment]
Ah, good catch--Yes, I think a collection item should be required.

**Comment by richardbporter** [comment]
When I exported that change, it ended up in the sitenow_v2 split somehow. Probably some config dependency I'm not going to debug right now. I changed it manually.

**Review by joewhitsitt — APPROVED** [review]
Thanks! Now back to locking them down https://github.com/uiowa/uiowa/issues/1920

**Pull request merged**
