### PR TITLE
Person Types

### LINKED ISSUE #2291: Person Types
# Issue

Brian asked me to create this issue for discussion in parking lot.

In working on #2205, I noticed the person_extended work that has been done and also recall a conversation with the APR team back in 2019 about their PersonType. For v2, we moved away from the idea only because we were unsure where APR was going and that to simplify the service initially, we went with one tagging taxonomy (tags) that could be used internally to filter content (featured content, people, content overview #781)

```
    FACULTY("Faculty"),
    EMERITUS("Emeritus"),
    GRAD_ASSISTANT("Grad Assistant"),
    STAFF("Staff"),
    PHD_CANDIDATE("PhD Candidate"),
    STUDENT("Student"),
```

If we pulled the person_extended person type field in, would we establish a default set of terms? Prevent them from deletion so we can target them across all sites?

# Story

As a developer I can maintain a list of person types in configuration and present those options to a webmaster/editor on the person content type. Depending on the person type selection(s), fields will show/hide so that only relevant fields are visible/available.

# Proposed solution

- [x] Establish a person types configuration entity with sitenow_people module to hold these values. Drush generate might have a wizard for this, otherwise https://www.drupal.org/docs/drupal-apis/configuration-api/creating-a-configuration-entity-type
- [x] Add initial list of terms through UI and export
- [x] Add Person Types (checkboxes, multiple) field referencing the configuration entity to the person content type.
  - There is existing logic/config related to the person_extended split that should be accounted for.
- [x] Setup up "visible fields" per person type in config entity. Pull in all non-default person fields
- [ ] Output person types to full node. Styled like footer/meta info. Basic output to uiowa_bootstrap.

Process of establishing a switch statement on the form alter to show/hide fields will happen later.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #2291 

* Adds a configuration entity called `sitenow_people.person_type.*` that stores different options for person types. The configuration can also define fields which should be shown when it is selected.
* Adds a field to the person type that allows for a user to select the person types defined using the configuration entity.
* Adds logic to the person node form that sets `#states` for a field that is allowed for some people types. If any person types are associated with it, it will only show up when those options are selected for the Person types field.
* Runs an update hook for sites that have the `person_extended` split enabled that converts previous instances of the taxonomy-based person type field to the new field. Also removes any person type terms so that the vocabulary can be removed.
* Updates the split definitions and associated config for `person_extended` and `immuno_grad_uiowa_edu` to use the new config entity and remove unneeded configuration items.

# How to test

## Test that Person types field shows up for default profile
* `blt ds --site=default`
* Visit http://default.local.drupal.uiowa.edu/node/add/person and observe that the new field shows up.

## Test that updates to Person types config is exportable
* Visit http://default.local.drupal.uiowa.edu/admin/structure/person-type/faculty and update the "Allowed fields"
* `drush @default.local cex --diff` should show the updates you just made.
* You can export the config or not, but please don't commit any changes back to this branch.

## Test that Person types field controls visibility of other fields
* `blt ds --site=immuno.grad.uiowa.edu`
* Visit http://gradimmuno.local.drupal.uiowa.edu/node/add/person
* Toggle either "Faculty" or "Student" and observe that additional fields are shown/hidden in response.

# Original post

Not exactly what was discussed, but I just wanted to get something working for now.

All existing person fields are displayed regardless of person type. As new fields get added to the content type, the show up as a person type option to "allow." Similar to permissions, the field must be added to the default_fields config or added to one or more of the types to display.

If we want to explore reworking it so that the config has a visible/hidden option to determine how the individual field booleans work that is fine, but I can't seem to wrap my head around how that would work on the form_alter.

### CODE REVIEW

**Comment by pyrello** [comment]
I'm wondering about adding an `active` key to the person_type config. This is something that could be config ignored and allow for a UI to select which options to show on a given site. We wouldn't need to build all that as part of this PR, but it might be good to lay the groundwork.

**Comment by pyrello** [comment]
@joewhitsitt I'm wondering about the "Person types" label for the field being added here. It seems a little confusing, especially in that it can have multiple types applied to a person. I wonder about using a label like "Roles" instead?

@mark-bennett-uiowa Do you have any sites that are implementing the `person_extended` split? I have tested the update against both sites that I have it installed on and it installs cleanly, but I'm willing to test it against any other sites if you have it turned on.

**Comment by mark-bennett-uiowa** [comment]
@pyrello At this point, no. All my sites should be using the default sitenow people since that content type has been extended.

**Comment by mark-bennett-uiowa** [comment]
@pyrello and @joewhitsitt I also think that using "roles" may be counter productive. "Person type" has always referred to whether they are faculty, staff or student (including other additional types) where "Role" tends to blend with job titles and responsibilities within the type. For instance, there may be a staff member with the person type Staff, but under roles, they may be the Accountant, Key Manager, Undergraduate advisor, etc. Just my two cents here.

**Comment by joewhitsitt** [comment]
Yeah, person type is currently the terminology on campus for this data. APR, WhitePages. Roles also creates confusion in the Drupal sense. We already have description text on the person content type, explaining that it does not give people access to the website.

>Use person to create individual profiles of people. This is **not** used to give users access to your site.

**Comment by joewhitsitt** [comment]
pulling down for biased testing

**Comment by joewhitsitt** [comment]
Update hook looks good. Rest of the functionality works after fresh set of weekend rested eyes. Output for default/uiowa_bootstrap is fine for MVP.

**Review by GaryRidgway — APPROVED** [review]
I have gone through and tested all steps in the `to test` section and they have functioned as expected.

**Comment by joewhitsitt** [comment]
Drafted a brief update to the person content type documentation.

**Pull request merged**
