### PR TITLE
Feature: Set layout builder section container settings to "Normal"

### LINKED ISSUE #3451: Remove `page__container` class from the `Normal` option in the layout builder container styles
# Problem
Selecting `Normal` for a layout container adds extra margins on smaller breakpoints. 

# Steps to reproduce
As reported by @bewoldt, try to add a background color to a `Normal` section and move the browser to a smaller breakpoint and notice that extra margins are added. 

# Proposed solution
- Remove `page__container` class from https://github.com/uiowa/uiowa/blob/c05630523a8d365227edb66a78d40195da167a2e/config/default/layout_builder_styles.style.section_margin_fixed_width_container.yml. 
- Remove `-None-` as an option and set `Normal` as the default option

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3451. 

- [x] Removed "-None-" option
- [x] Set label for "Normal" to "Normal (Default)"
- [x] Set Default setting to "Normal" if creating a new section
- [x] Update hook to set sections to "Normal" if they were previously set to "-None-"

May want to push code up to Dev first, as a test to see if batching is needed; but otherwise this is ready for testing.

# How to test

Check the labeling
 - Add a new section or edit the configuration of an existing section
 - Verify that there is no "- None -" option available in the Container settings
 - Verify that the "Normal" option is available, and that it is labelled "Normal (Default)" in the Container settings

Check the new default
 - Add a new section
 - Verify that the Container settings defaulted to "Normal (default)"

Regular update hook testing

- Note sections which currently have `- None -` container style selected, or add your own
- Run the update hook--check that the "(after)" message for both node and node_revision tables list 0
- Edit the layouts for any pages noted originally, and check that the section configurations are set to the `Normal (default)` container styles

Temp Store testing

- Checkout main and sync a site
- Edit layout(s) and add sections with the `- None -` container style selected, but do not save
- Checkout `feature_lb_container_normal_settings` and run the update hook (can visit `/update.php` in the browser to run it)
- Edit layout(s) (they should still be listed with "You have unsaved changes"--check that the newly added sections, as well as any existing sections, have properly updated to `Normal (default)` container styles

### CODE REVIEW

**Comment by cory-skeers** [comment]
Got an update hook generally working for this, but it's pretty inefficient--on sandbox.uiowa.edu, for instance, it individually unserializes data, updates it, reserializes, and inserts back into the database as about 1500 separate operations and SQL calls. We'll at least want to batch them, then, unless there's another way to handle it.

Also going to look into checking the tempstore like with the people list block update, to make sure we don't miss any unsaved changes that might have an empty section container style.

**Comment by cory-skeers** [comment]
I think the update hook is fully functional now. Can have a convo about whether batching is necessary or not, and then testing needs to be done.

**Comment by dnkemper** [comment]
I can test this  😎

**Comment by dnkemper** [comment]
aaaand assigning myself instead of putting myself as a reviewer so I can actually approve it lol. It's not even Monday 🙃

**Comment by dnkemper** [comment]
Check the labeling

- [x] Add a new section or edit the configuration of an existing section
- [x] Verify that there is no "- None -" option available in the Container settings
- [x] Verify that the "Normal" option is available, and that it is labelled "Normal (Default)" in the Container settings

Check the new default

- [x] Add a new section
- [x] Verify that the Container settings defaulted to "Normal (default)"

 Regular update hook testing

- [x] Note sections which currently have - None - container style selected, or add your own
- [x] Run the update hook--check that the "(after)" message for both node and node_revision tables list 0
- [x] Edit the layouts for any pages noted originally, and check that the section configurations are set to the Normal (default) container styles

Temp Store testing

- [x] Checkout main and sync a site
- [x] Edit layout(s) and add sections with the - None - container style selected, but do not save
- [x] Checkout feature_lb_container_normal_settings and run the update hook (can visit /update.php in the browser to run it)
- [x] Edit layout(s) (they should still be listed with "You have unsaved changes"--check that the newly added sections, as well as any existing sections, have properly updated to Normal (default) container styles

**Comment by dnkemper** [comment]
Okay, after I checked out main, then checked out the feature branch and went to the pages I edited in Sandbox (after going to the update.php page), it had the containers set to 'Edge-to-edge' I'm going to try again to double check

**Comment by dnkemper** [comment]
Strange - after I dropped all of my databases, then checked out main etc, it worked fine. Nice job!

**Review by dnkemper — APPROVED** [review]

**Comment by cory-skeers** [comment]
Thank you for testing, @dnkemper!

**Pull request merged**
