### PR TITLE
Move from uiowa_bar to uiowa_search for all sites except hr.uiowa.edu.

### LINKED ISSUE #1939: Turn on uiowa_search uids_base sites (not hr)
## Problem

When deprecating uiowa_bar, uiowa_search needs to take over for search configuration

## Proposed Solution

need to turn on and update permissions to configure uiowa_search, split uiowa_bar for HR.

query any sites that have a custom search engine id or "search this site" setting and update those either manually or through an update hook.

### LINKED ISSUE #2336: Remove links in University of Iowa Branding Bar configuration
Related:
https://github.com/uiowa/uiowa/issues/2151
https://github.com/uiowa/uiowa/issues/1980

I noticed there is a top links menu. Should customers be using this instead. Lots of confusion here.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1939 
Resolves #2336 

### Testing
- Sync multiple sites with `blt dsa` including:
  - default
  - hr.uiowa.edu
  - A site with different CSE settings (need to identify some).
- Test branding bar looks identical to production.
  - Markup, styles, etc.
- Test branding bar functions identically to production.
  - Search toggle, search results, etc.
- Test top links.
- Test changing uiowa_search config.
- Test uiowa_bar for hr.uiowa.edu is:
  - enabled after sync
  - is configurable by webmasters
  - has the same top links as before

### Review
- Review theme changes.
  - There are other references to uiowa_bar in uids_base. Do those need to change?
- Review sitenow_update_8042.
  - Anything missing?

### ToDo
- [x] Update all webmaster permissions, probably after #2577 is merged to avoid conflicts.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>A site with different CSE settings (need to identify some)

@richardbporter were you able to find any?

**Comment by joewhitsitt** [comment]
pulling down for testing

**Comment by joewhitsitt** [comment]
I am getting cseScope and engineID errors in the console on HR.

Also not getting results on any of the sites. When on the main branch I get "no results" and the search for {search terms} on google 

Toggling off `Display search box` on uiowa search config does not do I what I expect.

**Comment by richardbporter** [comment]
Thanks. I'll take a look. Maybe uiowa_search is not ready for primetime?

Also, you'll never get search results locally but I see what you mean.

**Comment by richardbporter** [comment]
@joewhitsitt That should be fixed with 3234004.

> Toggling off Display search box on uiowa search config does not do I what I expect.

Yea that doesn't seem to work. I think we need more Twig changes in uids_base to make that happen and probably in general with this PR.

Also, @joewhitsitt do you know if the tag-manager library should be removed from uiowa_search? Isn't that implemented in uiowa_core?

https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_search/js/tag-manager.js

**Comment by joewhitsitt** [comment]
Yes, gtag is being loaded here: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/uiowa_core.module#L17

**Comment by richardbporter** [comment]
> Toggling off Display search box on uiowa search config does not do I what I expect.

Fixed by 013061c.

**Comment by richardbporter** [comment]
Should top links show with the inline header? They don't seem to be on this PR.

**Comment by joewhitsitt** [comment]
I am running out of time today, but https://github.com/uiowa/uiowa/issues/2151 addresses the current issue with top links/header type and https://github.com/uiowa/uiowa/issues/2537 fills the need.

**Comment by richardbporter** [comment]
Thanks. Just wanted to make sure it wasn't something in this PR.

Unrelated: I added a blurb to https://sitenow.uiowa.edu/news/2020/11/november-updates.

**Comment by richardbporter** [comment]
I'm curious why the results pages cannot be cached. Tracked it down to https://github.com/uiowa/uiowa_bar/pull/40/commits/fc61cda11fa91c6d13e6f9713bcd5db970fdca3d. I would assume the actual results are not cached as they are loaded via JS, just the form itself, parameters, etc.

**Comment by richardbporter** [comment]
Looks like the route path is different in uiowa_search compared to uiowa_bar. This PR is switching search results pages to uiowa.edu/uiowa-search as opposed to uiowa.edu/google-search. What is preferred?

**Comment by pyrello** [comment]
@richardbporter I may have made that change thinking that it was preferable not to use "google" in the route name, but I'm definitely fine with making it consistent with what was in uiowa_bar.

**Comment by richardbporter** [comment]
I think you are right in case we ever use something else besides the Google CSE. I wonder if we just use /search even. Does that conflict with anything?

**Comment by pyrello** [comment]
If core search is disabled, I don't think so.

**Comment by richardbporter** [comment]
> I'm curious why the results pages cannot be cached. Tracked it down to [uiowa/uiowa_bar@fc61cda](https://github.com/uiowa/uiowa_bar/commit/fc61cda11fa91c6d13e6f9713bcd5db970fdca3d). I would assume the actual results are not cached as they are loaded via JS, just the form itself, parameters, etc.


This was because the results form render array was caching the search terms for one context. Ex. searching for foo and then foo bar would still show foo in the link markup. I got around this by adding url.query_args cache context.

**Comment by richardbporter** [comment]
> > A site with different CSE settings (need to identify some)
> 
> @richardbporter were you able to find any?

Not easy to find. The site kuehn.lab.uiowa.edu has display_search set to FALSE. Looks like that doesn't actually work now so this PR fixes it (https://labkuehn.prod.drupal.uiowa.edu).

Another option is to temporarily change the uiowa_bar config values at https://default.prod.drupal.uiowa.edu and sync.

**Comment by richardbporter** [comment]
I think is ready for another review.

**Comment by joewhitsitt** [comment]
pulling down for testing

**Comment by richardbporter** [comment]
I'm also trying to get this deployed to dev and running into issues. I'm trying to work through those.

**Comment by joewhitsitt** [comment]
Don't know if it is the issue, but https://github.com/uiowa/uiowa/pull/2521 was merged into DEV

**Review by joewhitsitt — APPROVED** [review]
Tested HR, v2 default, v3 default sites. I didn't dig much deeper than general functionality and looks. Thanks for fixing those search js issues

**Pull request merged**
