### PR TITLE
Change homepage search config and add basic promotion styling.

### LINKED ISSUE #3405: Promoted search results for HawkShop
# From the email request:
I’m hoping for those search terms to bring up the bookstore url as a result.
 
The urls that would be good for these terms are:
 
BOOKS - https://www.bkstr.com/iowastore/home
CLOTHING - https://www.bkstr.com/iowastore/shop/clothing-accessories
T-SHIRTS - https://www.bkstr.com/iowastore/search/keyword/tshirts
SUPPLIES - https://www.bkstr.com/iowastore/shop/school-supplies/school-supplies-sub
 
Since your site uses Google as its search engine, here is a helpful link with information on how to promote the link to the bookstore to the top of results pages for certain search terms https://developers.google.com/custom-search/docs/promotions

More details in email titled **Iowa Hawk Shop Search Terms** in ITS-web email account archive.

# Proposed solution

See @richardbporter's [comment below](https://github.com/uiowa/uiowa/issues/3405#issuecomment-825721302). After complete, follow up with @mjoneill.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3405

### Testing
- `blt sync --site uiowa.edu`
- Test out the following search terms and review the promotions:
  - title nine,title 9,title ix
  - sexual assault,rape,dating violence,domestic violence,stalking,sexual misconduct	
  - books	
  - clothing	
  - t-shirts,t shirts,tee shirts	
  - supplies	
  - hawkmail,email,owa	
  - emergency	
  - fraud,misappropriation,theft,whistleblower,ethics,confidential hotline,hotline,embezzlement,ncaa violation,sabotage,athletics violation,gambling,vandalism,illegal activity,financial misconduct,forgery,bribery	
  - food
  - ethics

### CODE REVIEW

**Comment by richardbporter** [comment]
@bspeare or @GaryRidgway any thoughts on style/design? Should promotions be styled differently?

**Comment by bspeare** [comment]
@richardbporter probably.   That could be a good topic of discussion for the design meeting next Wednesday with the brand team.

**Comment by mjoneill** [comment]
Any concerns with getting this out there by the end of the sprint?  Our new bookstore partner is asking just about every day, and I'm expressing "in this sprint" (but not committing to a day).

**Comment by richardbporter** [comment]
Not from me. It looks just like another search result right now:
image

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Without having the info as to what each keyword should map to, I was seeing similar styled promotion divs with relevant links.

The search all link works as described and makes sense to me. I think I recall someone bringing that up when we were building the homepage.

**Comment by joewhitsitt** [comment]
Talked with Rick about the logic behind the "search all..." link. It seemed to cover all the use-cases except if down the road there is a site that:

- has a university brand exception (regents tri-funded)
- has their own cse id
- wants to limit search to their site

Rick wondered if then it should be a config option. I think that would be the easiest long term instead of dealing with politics down the road. On by default, turned off for the homepage. Let webmasters decide.

**Comment by pyrello** [comment]
That sounds like a good option.

**Comment by richardbporter** [comment]
> Talked with Rick about the logic behind the "search all..." link. It seemed to cover all the use-cases except if down the road there is a site that:
> 
> * has a university brand exception (regents tri-funded)
> * has their own cse id
> * wants to limit search to their site
> 
> Rick wondered if then it should be a config option. I think that would be the easiest long term instead of dealing with politics down the road. On by default, turned off for the homepage. Let webmasters decide.

I copied these comments to #3409.

**Pull request merged**
