### PR TITLE
Update JS and CSS dependencies for uiowa_profiles

### PR DESCRIPTION
**Pull request by dcrall**
Changes to the uiowa_profiles module to support the new Vue 3 based Academic Profiles application that is replacing Directory Profiles.

- Update external dependencies to Vue 3 and related libraries
- Update profiles client script to new profiles-client.umd.js

# How to test

### CODE REVIEW

**Comment by dcrall** [comment]
@briand44  @pyrello @joewhitsitt - Thanks for helping out with these uiowa_profiles changes. I believe the changes in this PR are the needed dependency updates. If we can get these changes deployed to https://tippie.dev.drupal.uiowa.edu/people, I can test and confirm everything is working.

**Comment by joewhitsitt** [comment]
Anyone opposed to me merging this into [uiowa:update_profiles_endpoint](https://github.com/uiowa/uiowa/tree/update_profiles_endpoint) and sending it out to develop again?

**Comment by joewhitsitt** [comment]
@dcrall I believe this is now out to tippie.dev

**Comment by dcrall** [comment]
Thanks, @joewhitsitt. I'll test this morning.

**Pull request merged**
