### PR TITLE
AoS Feature Revisited

### LINKED ISSUE #4034: Areas of Study: Create a clear split from admissions
Continue within https://github.com/uiowa/uiowa/pull/3926
Move everything that Admissions needs over and eventually disable the feature split on Admissions

## Notes

The #3926 PR is currently adding the new stuff to Admissions but not placing the field on the content type nor providing permissions for the taxonomy vocabularies.

### LINKED ISSUE #4041: Area of study: "Search" filter block similar to admissions.uiowa.edu that sends queries to URL specified in block config
Create search block similar to the one displayed on the home page of admissions.uiowa.edu that sends queries to URL specified in block config:

Screen Shot 2021-08-30 at 12 52 27 PM

<details>
-  Moved functions related to `admissions_core` out of `uiowa_area_of_study` and back into `admissions_core` so that the admissions.local site doesn't WSOD when editing or viewing an area of study https://github.com/uiowa/uiowa/pull/3926/commits/2ac9348145725a758c4b943c6217fc302db4ccc4
-  Set `admissions_core` up with a replacement search block so that it doesn't use the `uiowa_area_of_study` block https://github.com/uiowa/uiowa/pull/3926/commits/25013b4148edb51ab8af1d43146bccb7c045d348
-  Set up `uiowa_area_of_study` with search styles for the `uiowa_area_of_study` block https://github.com/uiowa/uiowa/pull/3926/commits/6a1e33cbabea2384bc54747c68c663394a391cf0
</details>

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #3837
Resolves #4034
Resolves #4041

This PR creates a 90% clean split of AoS functionality as it relates to Admissions. The AoS Feature Split has been stripped down and rebuilt. Additionally, a generic search block has been added to uiowa_core to allow off-page filtering of the AoS view page (eventually a views block).

## Stories

- As an Admissions visitor and site owner, I don't see a change in my AoS functionality and can still search AoS from the homepage.
- As a developer the only changes I see to Admissions is where `field_degree_abbreviation` calls options from as well as some updated display configuration (moderation block, etc.). The module is enabled but the feature split is inactive.
- As a developer I can enable the AoS split without issue.
- As a webmaster of a site with the AoS split on, I can create AoS content and have it show up at /areas-of-study. Depending on how I fill in the source link, link direct fields, I can see that the content in the view and teasers are appropriately linked.

## To Test

- pull and `composer install && blt frontend && blt ds && blt ds --site=admissions.uiowa.edu`
- Note default sync doesn't have any AoS config imported
- Note admissions sync only field_degree_abbreviation, split config and AoS display settings are updated as it relates to AoS.
- The default site, once the AoS split is enabled and imported now has degree_types, locations taxonomies and their corresponding fields.
- There is a separate Search Block that webmasters can place that can be wired up to send queries to /areas-of-study using the `title` query parameter or /search with the `terms` query parameter. The endpoint field should only allow autocomplete internal paths (/node/6) and relative links (/search), not external URLs (e.g. https://google.com)

<details>
<summary>completed todo</summary>
## TODO
- [x] #4034
- [x] https://github.com/uiowa/uiowa/issues/4041
  - [x] Block description, more help text? 
  - [x] Change endpoint to link field
    - [x] style autocomplete (doesn't meet contrast ratio)
    - [x] validate for internal/relative paths only? 
  - [x] Fix SearchBlock Form to construct the redirect using the endpoint and query.
  - [x] Style Tweaks?
- [x] Permissions
- [x] SEO
- [x] Prettify
- [x] Account for or remove sticky at top of lists.
- [x] Adjust layout alignment so button doesn't move based on main content
- [x] Confirm path is /areas-of-study/[node:title]

</details>

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Checking out on DEV

**Comment by joewhitsitt** [comment]
@mjoneill and @briand44 - at your convenience, please review https://default.dev.drupal.uiowa.edu/areas-of-study, https://default.dev.drupal.uiowa.edu/node/add/area_of_study

Additionally, http://admissions.dev.drupal.uiowa.edu/ should not have any loss in AoS functionality.

**Comment by mjoneill** [comment]
Pretty sweet.  I think our next step is to get feedback from Education.  

As it is now, can sites add new and/or different taxonomy facets for filtering?

**Comment by joewhitsitt** [comment]
>As it is now, can sites add new and/or different taxonomy facets for filtering?

If I have it setup correctly, editors can add new degree types/locations on the fly and go to the taxonomy overview to edit/delete. i think only webmasters can delete

**Comment by mjoneill** [comment]
Sweet.  And if (for example) I wanted to add a facet for type with terms "Online, In Person, Hybrid"?

**Comment by joewhitsitt** [comment]
Each additional one would have to built on top or split and added for a site specifically. I was just going off what was defined in the [issue](#3837) and [card](https://github.com/orgs/uiowa/projects/1#card-59038297) to start.

**Comment by mjoneill** [comment]
> Each additional one would have to built on top or split and added for a site specifically. I was just going off what was defined in the [issue](#3837) and [card](https://github.com/orgs/uiowa/projects/1#card-59038297) to start.

Yep!  I think this an awesome probe as it is. Just wanted to understand the scope. Let's learn something from it with the first partner.

**Comment by joewhitsitt** [comment]
I should also note. Admissions is still "accepting" these additions from the feature, but they are hidden or not given the permissions. I think if this got bigger and Admissions didn't want these things, we should completely separate the feature from Admissions.

**Comment by joewhitsitt** [comment]
waiting for stakeholder feedback

**Comment by pyrello** [comment]
Since these potentially link off to other places directly from the listing/search page, I would be in favor of adding the degree type and location to the table listing.

**Comment by bspeare** [comment]
I'm getting `Error: Call to undefined function uiowa_area_of_study_allowed_values_function() in options_allowed_values() (line 89 of core/modules/options/options.module). ` when testing this on admissions, does this need to be in `admissions_core`?

**Comment by joewhitsitt** [comment]
Important comment related to this PR: https://github.com/uiowa/uiowa/issues/4041#issuecomment-909593878

**Comment by joewhitsitt** [comment]
I left the AoS module (not feature split) on for Admissions. This was to allow Admissions to continue to use the AoS search block for now. I then created a generic search block in uiowa_core that can then be a replacement once deployed. Once the block is swapped on Admissions' homepage, we can remove the AoS module from the Admissions split.

The new generic block is using an entity reference at the moment but last night I was thinking that maybe a generic link field would be better for this so that people could use this for non-node routes like the Google Search page or a view page.

Not sure where, if at all, this intersects with the Topics PR, but this search block could be used to send "searches" to contextual based view results.

**Comment by joewhitsitt** [comment]
Maybe this generic search block should be added to uiowa_search instead of uiowa_core?

**Comment by pyrello** [comment]
> Maybe this generic search block should be added to uiowa_search instead of uiowa_core?

I'm not sure I agree with this. The generic "search" block is really more like a trigger to redirect to a page with a particular query string fragment. Its applications potentially go beyond searching. I think that `uiowa_search` should be focused on actual search functionality.

**Comment by joewhitsitt** [comment]
I was going to set block defaults so it worked with the search results page which uses a query.

**Comment by pyrello** [comment]
I think my point still stands. This isn't providing any search functionality on its own. Just directing the user to a different search page.

**Comment by joewhitsitt** [comment]
>Just directing the user to a different search page.

Isn't that what this is doing? `docroot/modules/custom/uiowa_search/src/Form/SearchForm.php`

**Comment by joewhitsitt** [comment]
I do recall the thought that uiowa_search wasn't going to be on every site. If that is the case and since the proposed SearchBlock can extend beyond Google Search, maybe it should stay in uiowa_core.

**Comment by bspeare** [comment]
@joewhitsitt Good point about not having uiowa_search enabled on every site.   Seems like keeping it in uiowa_core makes sense if we want to stick with that plan.

**Comment by joewhitsitt** [comment]
working more on searchblock validation

**Comment by joewhitsitt** [comment]
going to review PR as it relates to #4034

**Comment by dnkemper** [comment]
Wanted to give this a look since already in this branch, and when I turn on and import the AOS config split in default, I see the degree and location taxonomies but not their corresponding fields? For instance, I don't see the degree abbreviation or label fields - and when I go to the fields section of the degree taxonomy term in default, there are no fields visible? I turned on AOS split, imported it and rebuilt cache... am I missing a step?
Screen Shot 2021-09-07 at 12 32 46 AM

**Comment by bspeare** [comment]
@dnkemper I think the degree_types and locations are just general taxonomy fields.  The degree abbreviations have been moved to `admissions_core`.

**Comment by dnkemper** [comment]
Awesome! Thank you, @bspeare 🥳

**Review by dnkemper — APPROVED** [review]
Tested this. Worked through questions with @bspeare and this looks good to me (an outside person that has never touched/viewed this PR before Friday haha)

**Pull request merged**
