### PR TITLE
uids_base - node preview header and actions

### LINKED ISSUE #1678: uids_base - node preview header and actions
## Problem
Screen Shot 2020-05-22 at 12 36 18 PM

## Proposed Solution
Port and refactor styles from uiowa_bootstrap:
Screen Shot 2020-05-26 at 9 50 27 AM

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #1678

Update: nobody seems to want to add on to this PR as it relates to #1660. Moving this along by itself.

## Testing

- Go to a content node edit form and click the preview link at the bottom of the form. The preview container form should be styled to a usable degree. The submit button is hidden due to .js-hide, so make sure you can switch between full and teaser view modes without.

**Before:**
Screen Shot 2020-06-10 at 4 11 48 PM

**After:**
Screen Shot 2020-06-10 at 4 13 42 PM

### CODE REVIEW

**Comment by richardbporter** [comment]
Is this PR just for the issue referenced? Or as a starting point for more UIDS/sitenow work?

**Comment by joewhitsitt** [comment]
I think it can house a lot of tasks related to #1660. I just tried to stay on top of writing the test as I was doing the work.

**Comment by joewhitsitt** [comment]
This might be affected by the re-organization being done in #1757. Marking as blocked for now.

**Review by bspeare — APPROVED** [review]
It looks a lot better - thanks!

**Pull request merged**
