### PR TITLE
Update smart_date

### LINKED ISSUE #5664: Use smart_date min and max field settings for events block's range field.
# Story

As a developer, I can re-configure the smart date range field on the events block to use the new min/max field settings.

# Proposed solution (updated 10/11/2022)

- ~~Create separate issues to address undefined array keys for min/max and next hour default value when max is set. https://www.drupal.org/project/smart_date/issues/3300768#comment-14726415~~ being handled in the same issue.
- [x] Submit patches to the module for the two issues.
- [x] Test and implement next stable release of smart_date with the functionality above.
- [x] Update the the range field on the events block and remove the override code from layout_builder_custom.

### LINKED ISSUE #5804: PHP error for smart_date
`Deprecated function: Calling static trait method Drupal\smart_date\SmartDateTrait::isAllDay is deprecated, it should only be called on a class using the trait in Drupal\smart_date\Plugin\Field\FieldWidget\SmartDateWidgetBase->massageFormValues() (line 285 of modules/contrib/smart_date/src/Plugin/Field/FieldWidget/SmartDateWidgetBase.php).`

# Steps to reproduce
Try setting "original publication date" on a "in the news" article type https://now.prod.drupal.uiowa.edu/news/2022/07/ui-researcher-wins-funding-study-regional-air-quality. 

# Proposed solution
- Update to `3.6.x`?
- https://github.com/uiowa/uiowa/issues/5664

### PR DESCRIPTION
**Pull request by joewhitsitt**
resolves #5804

error was fixed in 3.6, min-max is coming out in 3.6.2 so holding off #5664 for now.

# To Test 

- `ddev composer install`
- Try setting original publication date (in the news) on https://now.uiowa.ddev.site/news/2022/07/ui-researcher-wins-funding-study-regional-air-quality
- event features (admissions), events block (v3).

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Seeing an issue on Now's article form `Undefined array key "#type" in Drupal\Core\Form\FormHelper::processStates()`

**Comment by makurj** [comment]
Choosing "In the News" and entering an "Original Publication Date" gives this error on save. If I refresh, it goes away, but the moment I go to Edit > Save (even if I'm not making any changes to the 2 fields), the error returns.

image

**Comment by joewhitsitt** [comment]
@makurj I wasn't explicit with the test instructions. did you run `ddev composer install` for this module update PR before starting?

**Comment by makurj** [comment]
Just did it now. Testing again.

**Comment by makurj** [comment]
Now: error disappeared. Works as expected.
Admissions: error disappeared. No issue creating a single event or event series.
Default: event block works. Events block with upcoming, past and date range works.

**Comment by makurj** [comment]
Could someone also test this from a deployment perspective? I'd like to pair when this is done, if possible.

**Comment by joewhitsitt** [comment]
>Could someone also test this from a deployment perspective?

What do you mean?

**Comment by makurj** [comment]
Second reviewer who would code review, like we've been doing recently with PRs.

**Review by pyrello — COMMENTED** [review]
I code reviewed this with an eye towards potential issues with a deployment causing downtime. Sorry that you were not able to pair on this, @makurj, but here is my assessment in case its helpful:
- I'm assuming that all the configuration changes correspond to things that are changing in the smart_date module.
- Since the smart_date module is already on for the service, the code updates associated with the module update will happen immediately at the beginning of the deployment.
- The associated config updates will not get loaded until each site runs.
- Without specifically reviewing the code changes in the module, if there are any places where the updates need the new configuration and don't gracefully fail, then that could potentially be an issue that would cause a white screen.
- This is potentially mitigated by the code being cached in the database. Until a cache rebuild happens, the old code should be in effect. Although I'm not totally clear on what gets cached in the DB... all the code or only some of it. Generally, it is hard to know how much we can count on this because the cache can be cleared right after a deployment happens, canceling any benefit we would have gotten from it.
- We can potentially test around this by doing the following:
  - `git checkout main && git pull && ddev composer install`
  - Sync the relevant site for testing
  - `git checkout smart_date_update && git pull && ddev composer install`
  - Test the relevant functionality on the site without running any config imports or database updates. This is the state of the application we are worried about encountering. If you don't find anything worrisome in this testing, then I would say that we don't have to worry about scheduling a deployment.

**Comment by makurj** [comment]
> git checkout main && git pull && ddev composer install
Sync the relevant site for testing
git checkout smart_date_update && git pull && ddev composer install

I already did this, so I should be able to go ahead and approve, correct?

**Comment by joewhitsitt** [comment]
>I already did this, so I should be able to go ahead and approve, correct?

I'm biased, but I would say so. ;)

**Review by makurj — APPROVED** [review]
Tested functionality.

**Pull request merged**
