### PR TITLE
Emergency Hawk Alerts API Tweaks

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/7818

# How to test

```
ddev blt ds --site=emergency.uiowa.edu
```
Login and edit a couple existing alerts. Make some published/complete, unpublished/complete, published/incomplete, unpublished/incomplete. They should already have different created dates.
Go to https://emergency.uiowa.ddev.site/api/active and see that the unpublished content is not included, the complete content is not included and that the ones that are there are sorted with the most recent date first in the list.

The CORS change needs live-testing - See the comments on https://github.com/uiowa/uiowa/issues/7818

The sort is important because Signage only fetches the first one in the API.

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
> Make some published/complete, unpublished/complete, published/incomplete, unpublished/incomplete.

Does `complete` => `closed` and `incomplete` => `open`?

**Comment by joewhitsitt** [comment]
yes, terminology carried over from their v1 site.

**Comment by pyrello** [comment]
I'm just seeing there is a separate `Completed` checkbox. So I'm assuming that is the thing I actually want to toggle.

**Review by pyrello — APPROVED** [review]
This seems to be working as expected.

**Pull request merged**
