### PR TITLE
Updated policy_clas_uiowa_edu site split to contain entity_view_displ…

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Added wildcard core.entity_view_display.* to partial split to handle core entity updates in the future and fix current issue.

### CODE REVIEW

**Review by pyrello — CHANGES_REQUESTED** [review]
This should be closed in favor of being solved as part of #1530

**Comment by mark-bennett-uiowa** [comment]
So just close this PR?

**Comment by joewhitsitt** [comment]
@pyrello or should it stay here and go out first?

**Comment by joewhitsitt** [comment]
then the other PR can be tested again

**Comment by pyrello** [comment]
The config exports will still need to happen in the other PR, so I don't see the point of doing them separately.

I applied this change to the other PR and ran `drush @claspolicy.local csex policy_clas_uiowa_edu`, which resulted in the same config files being added to the split. That does not happen in this PR.

**Comment by joewhitsitt** [comment]
closing since duplicated in https://github.com/uiowa/uiowa/pull/1530

**Pull request closed without merging**
