### PR TITLE
Writing University blog entry: image migration module

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #2792 

# How to test
Need a local copy of writinguniversity.org in Dev Desktop.
Pull the `vwu` multisite from the Graduate College Acquia Cloud docroot.
Leave the DD Apache/MySQL stack running.

`git checkout writinguniversity-migrate` and `git pull`
`blt ds --site=writinguniversity.org`
`drush @org-writinguniversity.local en writinguniversity_migrate`
`drush @org-writinguniversity.local mim d7_writinguniversity_blog`
Check http://org-writinguniversity.local.drupal.uiowa.edu/news and that blog entries from writinguniversity.org have been migrated in, that their teaser images/descriptions look good, and that the actual pages don't appear to have any issues (site-wide default for article image is set to do not display; featured image should only appear on the teaser)

Can also run `drush @org-writinguniversity.local mim d7_writinguniversity_blog_redirect`--sets up redirects from old url alias paths to the new url path. Might not be necessary to migrate.

# Note

This PR contains the module/config to run the migration for #2792, but the actual migration and pushing db/files up will need to be run separately, and will still be pending following merge.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test, get familiar with.

**Comment by joewhitsitt** [comment]
I think I am missing a step. Do I need to have the D7 site local?

`SQLSTATE[HY000] [1049] Unknown database 'vwu'`

**Comment by cory-skeers** [comment]
Oh yeah...that's kind of an important step!

Yes--need to have a local copy of the database in DD; `vwu` on the grad college docroot.

**Comment by joewhitsitt** [comment]
I was like, "oh wow, Cory really made progress with this migration stuff. Dev Desktop is no longer needed!"

**Comment by cory-skeers** [comment]
Nope! Really wish that was the case rather than my being bad at writing testing instructions...

**Review by joewhitsitt — APPROVED** [review]
Stuff was migrated! Here is my log output:
```
16/544 [>---------------------------]   2% [warning] A non-numeric value encountered PelIfd.php:611
  38/544 [=>--------------------------]   6% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  39/544 [==>-------------------------]   7% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  50/544 [==>-------------------------]   9% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  58/544 [==>-------------------------]  10% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  60/544 [===>------------------------]  11% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  79/544 [====>-----------------------]  14% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
  85/544 [====>-----------------------]  15% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 152/544 [=======>--------------------]  27% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 159/544 [========>-------------------]  29% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 163/544 [========>-------------------]  29% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 182/544 [=========>------------------]  33% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 196/544 [==========>-----------------]  36% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 217/544 [===========>----------------]  39% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 222/544 [===========>----------------]  40% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 226/544 [===========>----------------]  41% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 228/544 [===========>----------------]  41% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 231/544 [===========>----------------]  42% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 236/544 [============>---------------]  43% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 263/544 [=============>--------------]  48% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 287/544 [==============>-------------]  52% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 290/544 [==============>-------------]  53% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 357/544 [==================>---------]  65% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 358/544 [==================>---------]  65% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 361/544 [==================>---------]  66% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 366/544 [==================>---------]  67% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 369/544 [==================>---------]  67% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 374/544 [===================>--------]  68% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 377/544 [===================>--------]  69% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 379/544 [===================>--------]  69% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 382/544 [===================>--------]  70% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 398/544 [====================>-------]  73% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 408/544 [=====================>------]  75% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 411/544 [=====================>------]  75% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 415/544 [=====================>------]  76% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 416/544 [=====================>------]  76% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 420/544 [=====================>------]  77% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 421/544 [=====================>------]  77% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 423/544 [=====================>------]  77% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 425/544 [=====================>------]  78% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 426/544 [=====================>------]  78% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 434/544 [======================>-----]  79% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 435/544 [======================>-----]  79% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 436/544 [======================>-----]  80% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 446/544 [======================>-----]  81% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 447/544 [=======================>----]  82% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 450/544 [=======================>----]  82% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 452/544 [=======================>----]  83% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 453/544 [=======================>----]  83% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 454/544 [=======================>----]  83% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 456/544 [=======================>----]  83% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 457/544 [=======================>----]  84% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 458/544 [=======================>----]  84% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 483/544 [========================>---]  88% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 502/544 [=========================>--]  92% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 504/544 [=========================>--]  92% [error]  Invalid marker found at offset 0: 0x89 
 515/544 [==========================>-]  94% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 519/544 [==========================>-]  95% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 523/544 [==========================>-]  96% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 527/544 [===========================>]  96% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 531/544 [===========================>]  97% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 532/544 [===========================>]  97% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 533/544 [===========================>]  97% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 534/544 [===========================>]  98% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 535/544 [===========================>]  98% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 537/544 [===========================>]  98% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 539/544 [===========================>]  99% [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:266
 [notice] Processed 542 items (542 created, 0 updated, 0 failed, 0 ignored) - done with 'd7_writinguniversity_blog'
 ```

**Pull request merged**
