### PR TITLE
2plus2 Admissions - Available Majors as a block

### PR DESCRIPTION
**Pull request by joewhitsitt**
# How to test
`composer install`
`blt frontend`
`ddev blt sync --site admissions.uiowa.edu --define drush.aliases.remote=admissions.dev`
Go to https://admissions.uiowa.ddev.site/academics/2plus2
- Verify that participating colleges and major blocks are displaying
- Click through colleges and majors and verify that breadcrumb paths are all the same and displaying on each 2plus2 page. 
- Verify that urls are set to `academics/2plus2/title`

### CODE REVIEW

**Comment by bspeare** [comment]
Still to do:  Update "Contact us" link to use `academics/2plus2` url path.

**Review by GaryRidgway — APPROVED** [review]
tested and determined that all things listed in the test instructions were true!

**Comment by bspeare** [comment]
Moving this back to draft until we get the default image set on prod.

**Comment by bspeare** [comment]
Once this is merged and deployed to admissions prod we need to create the 2plus2 overview page https://admissions.uiowa.ddev.site/academics/2plus2.

**Pull request merged**
