### PR TITLE
Added padding fix to banner backgrounds

### LINKED ISSUE #3630: Remove default left/right banner padding if specific background and section colors are selected
# Problem

Selecting a banner background color adds extra padding that is unnecessary when banner is sitting within a section container with the same background color.  

# Steps to reproduce

Go to https://sandbox.prod.drupal.uiowa.edu/banner-examples-0. 

Screen Shot 2021-06-09 at 12 43 24 PM
   

# Proposed solution

- Add a rule in `banners.scss` that will remove default padding if the selected background color is the same as the container background color. 
```

.layout:not([class*="bg-"]),
.layout[class*="bg--white"], {
  .banner[class*="bg--white"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--black"], {
  .banner[class*="bg--black"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--gray"], {
  .banner[class*="bg--gray"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}

.layout[class*="bg--gold"], {
  .banner[class*="bg--gold"] {
    .banner__content {
      padding: 1.5rem 0;
    }
  }
}
```

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3630 

# How to test

Test all banner background colors please - ie section color = gold, banner background = gold -> test with gold, black, white, grey and brain patterns please

- As a site editor, I can expect left/right padding to be added to my banner if the selected banner background is different from the section background color
- As a site editor, I can expect left/right padding to be removed from my banner if the selected banner background matches the section background color

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by dnkemper** [comment]
@cory-skeers thank you so much!

**Comment by bspeare** [comment]
I think we might want to update the layout builder style class names used in the banners in order to get this to work.  I will push up an update shortly.

**Comment by dnkemper** [comment]
@bspeare okay, awesome! I can update banner styles accordingly!

**Comment by bspeare** [comment]
Should be fixed now.  This was the issue I saw.  Screen Shot 2021-06-23 at 10 30 01 AM

**Comment by bspeare** [comment]
@dnkemper I think we also need to adjust https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/admin.scss#L275-L288 to include the updated class names.   Can you add that to this pr?

**Comment by dnkemper** [comment]
@bspeare sure thing!

**Comment by bspeare** [comment]
I had to update the section background classes too in order to get this to work as well.

**Comment by bspeare** [comment]
I think we can remove https://github.com/uiowa/uiowa/pull/3702/files#diff-adb6fa86d25d551e959411615f08e7b36615f750c7509c086d0cdc6febc84777R229-R251 now that we are updating the background classes.

**Comment by bspeare** [comment]
@dnkemper we also need to move these lines above the background image declarations: https://github.com/uiowa/uiowa/blob/90979f5f8c95d7f68eb56f6a14e0b7e4c598100b/docroot/themes/custom/uids_base/scss/admin.scss#L290-L292.

**Comment by cory-skeers** [comment]
@dnkemper @bspeare Is this good to test now? :)

**Comment by dnkemper** [comment]
@cory-skeers solid question haha.. @bspeare is there anything else we need to do?

**Comment by bspeare** [comment]
It is now, thanks for your patience!

**Comment by bspeare** [comment]
Updated the testing instructions with two user stories.

**Comment by cory-skeers** [comment]
Great! Pulling the updates, and I'll get to testin'.

**Review by cory-skeers — APPROVED** [review]
Tested all matching background combos, and the correct top/bottom but no left/right padding is applied. Tested multiple non-match banner backgrounds for each section background, including images, and the expected top/bottom and left/right padding appears.

Looks good to go! 👍

**Pull request merged**
