### PR TITLE
[Regents theme] Add footer logo toggle.

### LINKED ISSUE #6661: As a Journal site owner, I can toggle the display of the Iowa logo in the footer
As a Journal site owner, I can use SiteNow without the Iowa logo in the header so that I can provide a journal experience without immediate association with the University of Iowa. 

# Proposed solution
 

```[tasklist]
### Tasks
- [ ] Add a new option to the uids_base theme settings form to toggle whether the footer logo is displayed
- [ ] This new option should only be available and set if the regents theme option is also selected
- [ ] Adjust any styles based on the absence of the logo in the footer.
- [ ] Set the 91st website to use the regents theme for now, holding on setting this new footer logo option.
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
tracks [#6661](https://github.com/uiowa/uiowa/issues/6661)

## To Test
1. Pull a site
2. Change it to Regents theme
3. Notice a new checkbox there to turn on the logo!
4. Turn on the logo
5. OBSERVE THE LOGO
6. approve if the logo is present?
7. Or maybe try to break it? who knows

### CODE REVIEW

**Comment by bspeare** [comment]
@GaryRidgway can you update this with the UIDS commit from the `main` branch?

**Comment by bspeare** [comment]
Also, did you run `ddev yarn upgrade @uiowa/uids` after adjusting the UIDS version here?

**Comment by GaryRidgway** [comment]
@bspeare Good catches! These have been done.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested the options turning on the regent's theme on a non-regent's site, synced a site using the regent's theme (iowalakesidelab.org), and one using the UIHC Healthcare. Everything looked good for the fresh syncs, and functionality worked great for turning on Regent's and toggling on/off the logo. 💯

**Pull request merged**
