### PR TITLE
Classrooms - Accessibility Features

### LINKED ISSUE #6488: Classrooms accessibility features
# Story

As a Classrooms website owner, I would like accessibility features to be pulled in from Astra so that we do not have to manually manage those features.

# Additional Info

>Is it possible to change how we do the accessibility section? We originally planned on manually inputting this information and I didn’t realize until I took a closer look that a lot of the things we would list there are already features in Astra. Is that something you could change for us by chance? To add a taxonomy section for that? If we’re too far into things I understand.
> 
>The following are accessibility features that we would want in that taxonomy:
[Lectern - Mobile Height Adjustable](https://classrooms.uiowa.edu/features/lectern-mobile-height-adjustable) (currently in room features taxonomy)
[Podium - Height Adjustable](https://classrooms.uiowa.edu/features/podium-height-adjustable)
[Table - ADA Student Desk](https://classrooms.uiowa.edu/features/table-ada-student-desk)
[Assistive Device - Hearing Assist](https://classrooms.uiowa.edu/features/assistive-device-hearing-assist)
[Assistive Device - Loop](https://classrooms.uiowa.edu/features/assistive-device-loop)
[Table - 24" x 60" Adjustable Height](https://classrooms.uiowa.edu/features/table-24-x-60-adjustable-height)
Power Door Opener

They would also like a filter for accessibility features on the search page with the ability to choose multiple, similar to the technology features. We can make this a separate slice if needed?

# Proposed solution

- Add taxonomy similar to technology features so they can manage API mapping to a term
- Remove existing field
- Update import to loop through new taxonomy
- Style similar to existing field
- Disable field on node form similar to other fields coming from API

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/6488

Holding off on adding the filter till a later slice per https://github.com/uiowa/uiowa/issues/6488#issuecomment-1599304704

# To Test

```
ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local uli admin/structure/taxonomy/manage/accessibility_features/add
```

There should be no sync/import errors.

Add some of these api mappings:

Podium - Height Adjustable
Table - ADA Student Desk
Assistive Device - Hearing Assist
Assistive Device - Loop
Table - 24" x 60" Adjustable Height
Power Door Opener

`ddev drush @classrooms.local classrooms-rooms`

Go back into the recently created terms and see the that there are rooms now associated with them. Click into one of the rooms and see the Accessibility Features field is placed as it currently is on PROD. Edit the room and see that the field itself is in the disabled imported section of the form.

Screenshot 2023-06-23 at 2 38 05 PM

Screenshot 2023-06-23 at 2 43 47 PM

### CODE REVIEW

**Comment by joewhitsitt** [comment]
ruh roh. did something wrong...

Screenshot 2023-06-23 at 10 40 59 AM

UPDATE: Fixed it. https://github.com/uiowa/uiowa/pull/6573/commits/898ba6215682c2f7acf9b410dbd0a250cda43745

**Comment by cory-skeers** [comment]
pulling down to test

**Comment by cory-skeers** [comment]
It's a tiny detail, but can we change the field machine name from `field_room_accessibility_feature` to `field_room_accessibility_features` to match the others like `field_room_technology_features`?

**Comment by joewhitsitt** [comment]
> It's a tiny detail, but can we change the field machine name from field_room_accessibility_feature to field_room_accessibility_features to match the others like field_room_technology_features?

Ha. Max length limit. I thought nobody would notice... Could change to field_room_a11y_features maybe. Open to other ideas.

**Comment by cory-skeers** [comment]
> > It's a tiny detail, but can we change the field machine name from field_room_accessibility_feature to field_room_accessibility_features to match the others like field_room_technology_features?
> 
> Ha. Max length limit. I thought nobody would notice... Could change to field_room_a11y_features maybe. Open to other ideas.

Ah, dang. I'm good with `field_room_accessibility_feature` then, and still roughly match labels and the vocab designation.

**Review by cory-skeers — APPROVED** [review]
Works great!

**Pull request merged**
