### PR TITLE
[Registrar] CeCredential Validation module

### LINKED ISSUE #7724: Port CeCredential Validation to v3
Need to port https://registrar.uiowa.edu/credential-validation to v3 site.

Reports from outside the University that others are having issues with integrating. UNI also reached out to us because they were having issues integrating. Haven't heard yet if they have been successful.

Josh to get new test data from Vendor and any additional docs/info.

If we use a block that can be placed in layout builder, Josh can handle the additional content that needs to appear on that page.

>I have set up a new link to your Dropbox which now includes a plugin for Drupal 10. I will send you a password for the link.
The Drupal 10 plugin is located in: Updated Sample Code 6-5-24.

https://www.dropbox.com/scl/fo/0sfl9i67u3fhefggwgyjh/AH8dxBftUztdxgN1ZsJc4N4?rlkey=7mffu4ffs4l27ovjylnm1t0hv&st=2e08z2m3&dl=0

Password is in an email pinned in the web team inbox.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7724. 

# How to test

```
ddev blt ds --site=registrar.uiowa.edu && ddev drush @registrar.local en cevalidationsr -y && ddev drush @registrar.local config:import --source ../config/sites/registrar.uiowa.edu --partial -y && ddev drush @registrar.local cim -y && ddev drush @registrar.local uli /node/316/layout
```
1.  Check phpcs warnings. 
2. Add a "More.." block to /node/316/layout.
3. Add "CeCredential Validation Scholar Record Form block" and save page. 
4. Test form validation:
   - Submit empty form
   - Submit half-filled form
   - Submit CeDiD = `1628-A38C-J8E8`
   - Submit bad CeDiD = `1628-A38C-J8E9`
   - Confirm id is rendered with dashes as you type.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Since we are essentially forking the module to bring it local, is there more we can gut from this? Bootstrap library? The blank js file? https://github.com/uiowa/uiowa/pull/7784/files#diff-f5053218957727655174444629cae79a8a15adfa4abff3da11af9378de3bef58

Also, should we ignore the settings config and set those in the DB once we have PROD info?

Is registrar_core module needed yet or just the site split enabling the CeCredential module?

**Comment by joewhitsitt** [comment]
Pulling to test

**Review by joewhitsitt — APPROVED** [review]
Thanks for cleaning up the unnecessary extras. Since this module resides within the site directory, i made the config ignore site specific as well. Saw a low-hanging phpcs.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
