### PR TITLE
Adding block_margin_default_removed style to all blocks

### LINKED ISSUE #4917: As a developer, I can apply a default set of layout builder styles to any field or custom block
# Story

As a developer, I can apply a default set of layout builder styles to any new or existing block so that I can add margin, padding, and background colors. 

# Proposed solution
- Allow style options to be added for all field blocks and custom blocks. 
  - Exclude for existing layout builder page inline blocks
    - Our text area block's styles are a good example for possible defaults to offer:
      -   Padding
      -   Margin
      -   Background colors (white, gray)

### LINKED ISSUE #6341: Card 4_x post-deployment todo: layout_builder_custom_preprocess_block 'base_plugin_id' constraint is too broad
# Problem

The background color on the custom views block used on https://admissions.uiowa.ddev.site/international-student-ambassadors can no longer be applied because https://github.com/uiowa/uiowa/blob/card_4x/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1031 is too broad.  

# Proposed solution
- Start an allowlist to use with this function when https://github.com/uiowa/uiowa/pull/6054 is merged.

### LINKED ISSUE #7245: Facilities named building pages have lost some background color styles
# Problem
Due to https://github.com/uiowa/uiowa/issues/6341, the named building content type on the new facilities site has lost some of the background color classes that we set on the layout. 

<details>
Screenshot 2024-01-03 at 1 29 31 PM

</details>

# Steps to reproduce
Go to https://facilities.prod.drupal.uiowa.edu/named-building/pappajohn-business-building. 

# Proposed solution
https://github.com/uiowa/uiowa/pull/7201

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/4917. 
Resolves https://github.com/uiowa/uiowa/issues/6341. 
Resolves https://github.com/uiowa/uiowa/issues/7245. 

# How to test

## How to test adding block_margin_default_removed style to all blocks

```
ddev blt ds --site=facilities.uiowa.edu  && ddev drush @facilities.local uli /node/3636
```
- Confirm that margin is removed for nationality and birth year
- Edit a content type and confirm that this style is available on all blocks
- Edit a page and confirm that this style is available on all blocks

## How to test the allowed list on layout_builder_custom_preprocess_block 'base_plugin_id'

-  Test these views blocks and confirm that you can set a background color style and grid style on the cards. 
   - 'views_block:article_list_block-list_article',
   - 'views_block:events-card_list',
   - 'views_block:events_list_block-card_list',
   - 'views_block:people_list_block-list_card',
     - Can you think of any other list blocks that use this functionality?  I did not find any.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
going to debug tomorrow, but I am wondering if we can capture something in the view config that we can use instead of hardcoding this allow list. we have future issues where we are thinking of ignored active db config for faster views development.

**Comment by joewhitsitt** [comment]
Wonder if we can use the block category to classify these through view config? It looks like all of the above use `Lists` except for `views_block:events-card_list` which is currently using `Restricted`

`$variables['elements']['content']['#view']->display_handler->options['block_category']`

>Can you think of any other list blocks that use this functionality? I did not find any.

How did you find this initial list @bspeare?

**Comment by bspeare** [comment]
@joewhitsitt I just did a manual audit of the views blocks using this functionality.

**Comment by bspeare** [comment]
@joewhitsitt I like your idea of the lists category!

**Review by joewhitsitt — APPROVED** [review]
Approving this as-is for now. The test instructions check out and I couldn't identify other views_blocks that need to handle the card/list/grid stuff.

Category is already being used for other functionality and it would be easy to confuse and get right. I think going forward we could leverage the machine name by reserving `list_block`, matching on contains and grandfathering in the couple blocks that don't use that convention. We had previously talked about using the machine name to ignore certain views from being tracked in config so this could be similar and just part of our documented workflow.

```
    $allowlist = [
      'views_block:events-card_list',
      'views_block:student_card-block_student_card',
    ];

    if ($variables['base_plugin_id'] === 'views_block') {
      // Check if the current block plugin ID is in the allowlist or list_block.
      $current_plugin_id = $variables['plugin_id'];
      if (in_array($current_plugin_id, $allowlist) || str_contains($current_plugin_id, 'list_block')) {
```

**Pull request merged**
