### PR TITLE
[Bug] Fixed library regression for exposedFormEnhancements

### LINKED ISSUE #7162: Update uiowa_core exposedFormEnhancements to work with core bulk operations form
> I think docroot/modules/custom/uiowa_core/js/exposedFormEnhancements.js is affecting this new form by not making the selection contrast compliant. follow up issue?

Screenshot 2023-12-01 at 9 54 09 AM

_Originally posted by @joewhitsitt in https://github.com/uiowa/uiowa/issues/7098#issuecomment-1836352534_

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7162

# How to test

- Code review to see how the library file is now fixed. 
- You could also follow testing instructions from https://github.com/uiowa/uiowa/pull/7198.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
so was this just a loading order issue or am i missing a misspelling or something?

**Comment by joewhitsitt** [comment]
pulling to test quick

**Comment by bspeare** [comment]
The `exposedFormEnhancements` was being loaded in a different library.

**Review by joewhitsitt — APPROVED** [review]
Fixed! Thanks!

**Pull request merged**
