### PR TITLE
Include stylesheets for WYSIWYG ckeditor

### LINKED ISSUE #1662: UIDS_Base WYSIWYG Styles
## Problem
WYSIWYG text areas are currently unstyled and don't offer a "preview" of uids_base rendering.

## Proposed Solution
Load the theme styles similarly to how uiowa_bootstrap did.

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #1662 and #1714

Current SiteNow theming styles includes Lead and multiple Alert levels--these are available in the editor, but do not render within the editor. Additional styles and classes should also be available.

## Test
SiteNow: Edit a text body, check that WYSIWYG properly renders styling options, including allowable HTML, series of WYSIWYG editor buttons, and style/format dropdowns.

Collegiate: Edit a text body, check that appropriate uids styles are available, and appear correctly.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Not sure if these are the stylesheets to use. I think we want to capture WYSIWYG related styles in a separate aggregated file and reference that. We need to create a list of the styles associated with the wysiwyg buttons and allowed html... This turned into a bit of a rabbit hole since there isn't a "master" css file.

I created a separate issue that can be part of this PR: https://github.com/uiowa/uiowa/issues/1714

**Comment by joewhitsitt** [comment]
I think this will need to be updated after #1681 is merged in as paths have changed

**Comment by joewhitsitt** [comment]
Tested this a bit. Not sure if it is pulling the same alert styles as rendered. Also I think some typography is missing.
Screen Shot 2020-06-04 at 4 22 53 PM
Screen Shot 2020-06-04 at 4 22 38 PM

**Comment by cory-skeers** [comment]
For the alerts, alerts.scss has a few adjustments for pages that aren't using layout builder--these adjustments aren't pulled in at the wysiwyg editor-level, so the non-adjusted styling is being rendered in the editor.

For the typography, looks like the wysiwyg editor is overriding the body styling for fonts, and needs to either be prevented from doing so, or ordering of how the styling gets pulled in adjusted.

Working on it...

**Comment by cory-skeers** [comment]
Removed the non-layout-builder adjustments to alerts as no longer needed--UIDS alerts theming is now rendered on the page as well as in the editor.

body{font-family:...} in ckeditor-iframe.css in core ckeditor module is the culprit for the typography issues for styling that does not indicate specific font-family to override. Needs to be targeted.

**Comment by cory-skeers** [comment]
Added the Roboto sans-serif font-family to the ckeditor css through js addition. Takes care of typography mismatches when a font-family isn't explicitly declared in a class. There's still a small difference in typography of button text

**Comment by cory-skeers** [comment]
Will need slight adjustments following #1756

**Comment by joewhitsitt** [comment]
Because of #1756 / #1757, marking as blocked for now

**Review by joewhitsitt — APPROVED** [review]
Nice progress. I think this can go for now. Had an issue with font-weight related to the .lead class. Not sure how that can be resolved without making sure all font variants are loaded (heavy).

**Pull request merged**
