### PR TITLE
Patch entity_usage to fix WSOD with empty data- attributes.

### LINKED ISSUE #3167: Malformed HTML causes WSOD
*I keep getting this error on one particular page when trying to save the Layout:
"Temporarily Unavailable
The website that you're trying to reach is having technical difficulties and is currently unavailable.
We are aware of the issue and are working hard to fix it. Thank you for your patience."*

*This is the page:
https://writinguniversity.org/node/116/layout*

*I am able to save the page through Edit without that error but every time I try to save the Layout I get this error. It started happening yesterday around 11am? I've tried on several browsers too.*

Error: 
```
Uncaught PHP Exception Drupal\Core\Entity\EntityStorageException: "The "" entity type does not exist." at /mnt/www/html/uiowa01/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 810
```

Seems to be caused by the following actions:

- Removing URL from a link
- Attempting to link an image using WYSIWYG toolbar

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3167 

### Testing
To see the error on the main branch, add the markup in https://github.com/uiowa/uiowa/issues/3167#issuecomment-789729782 to a text area block in LB on a page. Save and view the page. 

Check out this branch, `composer install` and follow the steps again. No more WSOD. 

Also included in this PR is some updates to dependencies and documentation to test Drupal core and contrib projects within uiowa/uiowa. If you are interested, follow the steps in the new tests/README file to try it out: https://github.com/uiowa/uiowa/pull/4063/files#diff-dacac2ebf9792f0d23c0f922a744486ded01901957d5281290925acd89cf83acR21

### CODE REVIEW

**Comment by richardbporter** [comment]
Just noticed something.

**Comment by richardbporter** [comment]
~~Lets go with it for now.~~

**Comment by richardbporter** [comment]
I think this is ready now.

**Comment by GaryRidgway** [comment]
pulling for review

**Review by GaryRidgway — APPROVED** [review]
I have tested on both branches, main and this one, and determined that this branch does not white screen, and main does white screen. APPROVED.

**Comment by richardbporter** [comment]
Thanks!

**Pull request merged**
