### PR TITLE
Directory profiles style bugs i4438

### LINKED ISSUE #4438: Directory profiles style bugs
# Problem
- Breadcrumbs in Safari are not displaying inline
- Page title sitting on top of page filters
- Container has `tab-index: 0` creating blue border - is this tab index necessary?

Screen Shot 2021-11-15 at 8 49 06 AM

Screen Shot 2021-11-15 at 8 48 52 AM

Screen Shot 2021-11-16 at 2 27 02 PM

# Steps to reproduce
Go to https://education.uiowa.edu/directory and see the page title sitting on top of the page filters. 
Go to https://education.uiowa.edu/directory/john-achrazoglou in Safari

# Proposed solution
- Fix.

### PR DESCRIPTION
**Pull request by GaryRidgway**
resolves #4438 

# How to test

Read the issue listed above.

verify that the first two problems are fixed.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to take a look!

**Review by cory-skeers — APPROVED** [review]
Tested these out locally (thank you again @GaryRidgway for the assistance!) and the changes look good for the first two issues!

Third bullet in the issue ("Container has tab-index: 0 creating blue border - is this tab index necessary?") to be handled on the directory side of things.

**Comment by GaryRidgway** [comment]
@cory-skeers i lied. The tabindex stuff is on our part. it has been fixed! Plz check again for it to not be there, and then it will be mergerino'd

**Comment by cory-skeers** [comment]
Yep! Checked, and the tabindex is no longer appearing.

Think this is good to go, then 💯 
image

**Pull request merged**
