### PR TITLE
change import format and set allowed formats 

### LINKED ISSUE #1831: Set import to minimal and set default to minimal for new banner/card excerpts
## Problem
Follow-up to https://github.com/uiowa/uiowa/pull/1790 we decided to import to minimal instead of filtered_html to avoid mis-use/display problems with rendering rich markup in these components.

## Proposed Solution
Update the import and set format default

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #1831

As a follow up to https://github.com/uiowa/uiowa/pull/1790. All previous test steps apply, but the main thing is that content is imported as minimal instead of filtered_html and the allowed formats for card and banner excerpts are restricted to minimal and plain text.

This also needs to be changed before the next release. No pressure...

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling this down to test now.

**Review by bspeare — APPROVED** [review]
I tested this locally on uiowa.local.drupal.uiowa.edu and I didn't notice any issues or regressions with the banners or cards.   I did create an issue for future work to make these components work with the new text formats: https://github.com/uiowa/uids/issues/255.  Thanks!

**Comment by joewhitsitt** [comment]
@bspeare is this a uiowa/uids#255 for release? editors could potentially start creating markup that isn't styled

**Comment by bspeare** [comment]
@joewhitsitt I could create a kitchen sink fix and add it to this PR until it can be addressed in UIDS.  What do you think?

**Comment by joewhitsitt** [comment]
That would be great because we with #1790 we can't create a release until this change goes out with it.

**Comment by bspeare** [comment]
@joewhitsitt sounds good.  I'll add it to this PR later this evening.

**Comment by bspeare** [comment]
@joewhitsitt I added some fixes for `banner--reversed` as well as an adjustment to the banner template changing the `banner__summary` to a `<div>` instead of a `<p>` tag.   I believe this fix is all that is necessary for now.

**Comment by pyrello** [comment]
Looks like the spacing is a little tighter:
Updated:
Screen Shot 2020-06-24 at 9 22 03 PM
Original:
Screen Shot 2020-06-24 at 9 21 45 PM

I don't know that that matters.

**Comment by bspeare** [comment]
I'm not too worried about that spacing.  As soon as the block text is updated the spacing will return.  I can update the banners on uiowa.edu manually after this is deployed.

**Comment by bspeare** [comment]
@joewhitsitt I'm done making changes to this unless you see anything else that needs to be addressed.

**Pull request merged**
