### PR TITLE
Feature: Adding missing fields for AoS program types

### LINKED ISSUE #3001: As a site owner, I can add additional details within the program types AoS section
# Story

As a site owner, I can add additional details within the program types AoS section so that it matches the options available on the D7 site. 

# Proposed solution

Add the additional checkbox fields to the "Program Types" section on the AoS content type:
- [x] **Teaching Licensure** - If checked, show text field. 
- [x] **Honors Courses** - If checked, show text field. 
- [x] **Four-Year Graduate Plan**  - If checked, show text field. 
- [x] **Selective Admission** - If checked, show text field. 
- [x] **Competitive Admission** - If checked, show text field. 
- [x] **Add the fields to the sidebar view block:** https://github.com/uiowa/uiowa/blob/main/config/admissions.uiowa.edu/views.view.areas_of_study_block.yml. 
- [x] **Show/hide fields**: https://github.com/uiowa/uiowa/blob/8f2030801324a02149a2d66d6b3759ad80829c4b/docroot/modules/custom/uiowa_alerts/src/Form/SettingsForm.php#L66
- [x] **Style the fields:** with an icon checkbox `<p><span class="fa-check-square fas"></span>&nbsp;<strong>Teaching Licensure</strong></p>` and list the description field below.

Screen Shot 2021-02-02 at 9 48 21 AM

Screen Shot 2021-02-02 at 8 31 46 AM

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3001. 

# How to test

- `blt ds --site=admissions.uiowa.edu`
- `yarn workspace admissions_core build`
- `drush @admissions.local cr`
- Go to http://admissions.local.drupal.uiowa.edu/node/add/area_of_study and verify that the new fields are showing and show/hide based on checkbox. 

Screen Shot 2021-02-02 at 4 32 47 PM
Screen Shot 2021-02-02 at 4 32 58 PM

- Go to http://admissions.local.drupal.uiowa.edu/areas-of-study/accounting and verify that sidebar block is showing up with a new option like "Teaching Licensure" with a checkbox icon. 

Screen Shot 2021-02-02 at 4 37 07 PM

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by cory-skeers** [comment]
Only thing I'm noticing is that if you check the fields and add descriptions, then later uncheck a field, the descriptions still appear on display:
image
On the form, the description is then hidden unless you check the field, after which you can then delete the description and uncheck the field to remove it completely.

## Steps to reproduce
Check one of the fields with a description (teaching licensure)
Add a description and save
Uncheck the field

**Comment by bspeare** [comment]
Thanks @cory-skeers, do you have any suggestions on how to remove that content if the field is unchecked?

**Comment by cory-skeers** [comment]
@bspeare I was thinking a presave that checks if those fields are unchecked, and removes any descriptions if they are. Would be "losing" data if a user unchecked the box, but I think it fits expectations if you're unchecking the box.

I can push a commit up momentarily.

**Comment by joewhitsitt** [comment]
Not sure if we want to wipe out data. I think unsetting during preprocess or hiding in twig with a wrapping if statement would be a better approach.

**Comment by cory-skeers** [comment]
Between the two there, I'd lean toward the preprocess to unset it, then.

**Comment by cory-skeers** [comment]
So, kinda weird--hadn't realized the fields were being pulled in through a view.

Added some display logic to the view, so that the descriptions are only written if their corresponding boxes are checked.

@bspeare Want to double check I didn't break anything in there?

**Comment by bspeare** [comment]
@cory-skeers It looks good - thank you!

**Review by cory-skeers — APPROVED** [review]
If my updates to the view looked good, this should be ready to go! 👍

**Pull request merged**
