### PR TITLE
LB contextual links don't work after dragging block

### LINKED ISSUE #2716: LB contextual links don't work after dragging block
# Problem
After dragging a block within the layout builder editor, contextual links no longer work until the layout changes have been saved.

# Steps to reproduce
Edit a page layout.
Drag a block into a new section or a new region within the section.
Attempt to edit/move/remove the block using the contextual link.

# Proposed solution
Unsure, but my guess is the contextual link is attempting to load a block based on the section/region in which the block is appearing in the layout preview, but as the layout has not yet been saved, the block does not exist by that reference. Some way that reference chain needs to be retained and/or updated upon dragging. Can maybe look into how the contextual move option works, as that appears to work correctly.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2716 

# How to test

1. composer install
2. blt ds --site=sandbox.uiowa.edu
3. Try editing https://sandbox.local.drupal.uiowa.edu/node/586/layout and move the block to a section above the section it's in and then move the block way below to the bottom region

### CODE REVIEW

**Comment by makurj** [comment]
Pulling down to test.

**Comment by dnkemper** [comment]
@makurj THANK YOU SO MUCH! You ROCK!

**Review by makurj — APPROVED** [review]
Tested. Working as expected.

**Comment by dnkemper** [comment]
@makurj THANK YOU SO SO MUCH! YOU ROCK!

**Comment by pyrello** [comment]
Nice work on this, @dnkemper. Way to stick with it!

**Pull request merged**
