### PR TITLE
UIHC Branding Update

### LINKED ISSUE #7403: IOWA HEALTH CARE BRANDING - SiteNow V3
As the digital strategy team for UI Health Care, we want to be able to assist more directly and completely with new website requests that span our main public brands so that site requests can be fulfilled accurately, on brand, and in a platform we are investing in.

Asks:
1. Right now an Iowa, CCOM, and REGENTS branding option exists. We would like to explore adding an additional branding option for UI Health Care.
2. This would impact site logo, Favicon, Title/Meta Tag details, and possibly default URL architecture. (*.uihealthcare.org) - Needs discussion.
3. In order to be better stewards of these requests and reroute off brand requests, explore uncovering on the SIteNOw request wbeform the option to select: CCOM or UI HEALTH CARE. If selected, explore how those requests get routed to our UI Health Care team for review, and approval.

# Proposed Solution

```[tasklist]
### Tasks
- [x] Review CCOM theme changes in https://github.com/uiowa/uiowa/pull/6869 and update those changes with new logo and favicon below
- [x] Rename CCOM theme setting to UIHealthCare
```

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/7403

# Test

- code review
- `ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli admin/appearance/settings/uids_base`
- See and change to the UIHC Healthcare option. Notice that the CCOM option is no longer present.
- Navigate to the front and see the UIHC Healthcare logo in the header and footer. Centered and seemingly the same width as the block IOWA logo on sandbox.prod.
- Note that the favicon is a yellow background icon with all of the variations available in the `<head>`.
- See that the SVG's fallback png is linked and available. (https://sandbox.uiowa.ddev.site/themes/custom/uids_base/assets/images/uihc.png)

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Comment by joewhitsitt** [comment]
Thanks for testing. Just let's not merge it yet if approved. Waiting on UIHC to finish their Parent Org switchover.

**Comment by bspeare** [comment]
I checked with Jess, and I think we will need to adjust the spacing of the tab around the new logo.  Below are quick screenshots, but we want to:
- Have extra space above the Iowa
- Have equal spacing on left, right, and bottom of logos

Screenshot 2024-05-06 at 2 08 37 PM
Screenshot 2024-05-06 at 2 02 03 PM

**Comment by bspeare** [comment]
Saw this in the console: `site.webmanifest:1 Manifest: property 'start_url' ignored, should be same origin as document.`

**Comment by bspeare** [comment]
Does the `<title>` need to be something like `UI Health Care | The University of Iowa`?

**Comment by bspeare** [comment]
I know that we have the parent org working in the page title now, but should we check that this meets their expectations?  Locked into the "Display Below IOWA bar" option with redundant text next to the logo if they want `UI Health Care` in the page `<title>`?

Screenshot 2024-05-06 at 2 49 09 PM

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/7403#issuecomment-2088451942

I believe Max said they probably won't use the parent org much for these sites.

**Comment by joewhitsitt** [comment]
>Does the <title> need to be something like UI Health Care | The University of Iowa?

Oops. We went a bit delete crazy thinking they would just use the The University of Iowa. Added back in the org override so they don't have to use the regents way of setting it.

**Comment by joewhitsitt** [comment]
>Have extra space above the Iowa
>Have equal spacing on left, right, and bottom of logos

Is that just for desktop? What is an extra space in terms of pixels here?

**Comment by joewhitsitt** [comment]
EoD it was mentioned that padding on the logo--tab might help bring the results requested. Out of my element here, but I pushed an adjustment that might be close.

**Review by bspeare — APPROVED** [review]
Nice work!

**Comment by joewhitsitt** [comment]
Thanks for helping Marie and I get over the finish line @bspeare.

Converting to draft to avoid merging at this time.

**Comment by briand44** [comment]
Ethan says all the sites on uiowa06 are now on the Iowa brand.

**Comment by joewhitsitt** [comment]
So good to merge @briand44 ?

**Pull request merged**
