### PR TITLE
i3077 - Made featured image required for aos and added to config split

### LINKED ISSUE #3077: Make featured image required for Area of Studies
# Story

As an Admissions site owner, I want to require a featured image on areas of study so that they all have a consistent look and feel.

# Proposed solution

Make the field required?

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3077 

# How to test

1. blt ds --site=admissions.uiowa.edu
2. Go to http://admissions.local.drupal.uiowa.edu/admin/structure/types/manage/area_of_study/fields/node.area_of_study.field_image and make sure featured image is required in AOS content type

### CODE REVIEW

**Comment by pyrello** [comment]
LOL. Your point is taken :)

**Comment by dnkemper** [comment]
@pyrello bahaha :innocent:

**Review by joewhitsitt — APPROVED** [review]
nice rogue

**Comment by dnkemper** [comment]
@joewhitsitt haha I learned from the best 🙈 Thank you kindly!

**Pull request merged**
