### PR TITLE
Hotfix - Fix Grad Thesis Defense with future date

### LINKED ISSUE #5050: Grad - Thesis defense creation for date in the future is broken
# Problem
When creating a Thesis Defense on grad.uiowa.edu with a date in the future, the user gets an error message
Screen Shot 2022-03-28 at 11 51 29 AM

# Steps to reproduce
* `blt ds --site grad.uiowa.edu`
* `drush @grad.local uli node/add/thesis_defense`
* Set the date field to a future date and save the node

# Proposed solution
Investigate if some of the code removed in https://github.com/uiowa/uiowa/pull/5014 is still necessary after all.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5050 

# How to test
* `composer install`
* `blt ds --site grad.uiowa.edu`
* `drush @grad.local uli node/add/thesis_defense`
* Set the date field to a future date and save the node
* Confirm there is no error
* Test same day date and date in the past too, just to be safe

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down

**Comment by joewhitsitt** [comment]
Screen Shot 2022-03-28 at 1 05 57 PM

still getting the error

**Comment by quamsta** [comment]
I was able to save the node with both a future and a past date in the field with no errors: 
Screen Shot 2022-03-28 at 1 38 08 PM
Screen Shot 2022-03-28 at 1 38 23 PM

Is that the expected behavior?

**Review by quamsta — APPROVED** [review]
As mentioned in https://github.com/uiowa/uiowa/pull/5051#issuecomment-1081006358, this is working for me.

**Pull request merged**
