### PR TITLE
Move SiteNow "Additional Info" content into uids_base

### LINKED ISSUE #1820: Include 'Additional Information' from SiteNow footers in uids_base
Relates to #1660 

## Problem
'Additional Information' in basic site settings (admin/config/system/site-information) for SiteNow sites includes Title and textarea Details fields that can be included in the footer. This has been used for various content: contact details, site slogans, acknowledgement/attribution info.

### New home for existing content
Content already in place needs to be handled. Currently, after transitioning to uids_base, content in these fields are no longer displayed on the site.

### ~~Update basic site settings~~
~~The 'Additional Information' section is available in basic site settings with uids_base theme, but is not used in the site.~~
uiowa_footer module will likely be deprecated, which would remove this from the site settings.

## Proposed solution
Create a pre-footer region block to hold content currently in place in SiteNow.
~~Remove Additional Information section from basic site settings.~~

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #1820 

## Testing
- Run update hook on a uiowa_bootstrap site.
- (maybe) Add some info to the Additional Info fields in basic site settings
- Switch theme to uids_base.
- If site used Additional Info
  - Content (title and/or details) should now be in a block in the footer, below the Contact Info
- If site wasn't using Additional Info
  - No change to the footer

Two SiteNow sites currently using the Additional Info fields are protostudios.uiowa.edu and igec.prod.drupal.uiowa.edu.

Note: There is some basic regexp logic to add link/icon to phone numbers which are not currently linked, to match default content styling/usage, and to remove lone instances of the site title to avoid repetition in the uids_base footer. It's not robust, and only a "nice if it works" addition, so not needed if it breaks.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling this down for testing. i got quite a test case in mind. muhaha!

**Comment by joewhitsitt** [comment]
Looks like the update hook ran and footer content's timestamp was updated, but diversity.uiowa.edu only shows the site name now.
Screen Shot 2020-06-25 at 10 24 42 AM

**Comment by cory-skeers** [comment]
AAAahhhh..... one of the preg_replace uses '@' as a delimiter, so the pattern's cut off early from the diversity site title.

**Comment by cory-skeers** [comment]
@joewhitsitt Updated to escape delimiters in the site title, and add a class to Titles moved to `<h2>` to avoid black-text/black-bg.

Would be an issue if existing Additional Info fields have any <h#> tags without a class...

**Comment by joewhitsitt** [comment]
> AAAahhhh..... one of the preg_replace uses '@' as a delimiter, so the pattern's cut off early from the diversity site title.

Told you I had a good test case in mind! That and the long disclaimer. Unfortunately, I got my local env all setup for demo, so unless you want to screen-share, I can't re-review till later.

**Comment by joewhitsitt** [comment]
pulling down

**Comment by joewhitsitt** [comment]
Alright, 👍 type approval. Re-tested diversity and ITI with their broken images. Worked as expected. Can you merge this into #1806 ?

**Comment by cory-skeers** [comment]
I can! Thanks for the review(s).

**Comment by cory-skeers** [comment]
Changes merged into #1806

**Pull request closed without merging**
