### PR TITLE
Started adding uiowa_auth module to uiowa

### LINKED ISSUE #2630: Remove custom Composer install path for drupal-custom-module packages
### Problem
Currently, we install drupal-custom-modules to the custom path `docroot/modules/uiowa` because they are not contrib but can't go in custom otherwise they'd be tracked in VCS. However, this is a really odd location and could cause confusion if we use a non-UI custom module in the future.

### Possible solutions
1. ~~Remove the custom install path and treat anything not in this repository as contributed. This would move uiowa_auth to `docroot/modules/contrib` which would require a cache rebuild.~~

2. Copy/paste uiowa_auth into this repository in `docroot/modules/custom` and ~~then make use of GitHub release file uploads for extracting and sharing that module, _if necessary_~~.  Update the composer.json file to remove the custom install path to `docroot/modules/uiowa`.

~~This is blocked by #1907 and #1713 which are blocked by #2629.~~

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2630 
# How to test

1. composer install
2. drush @sandbox.local cr
2. blt ds --site=sandbox.uiowa.edu
3. drush @sandbox.local uli
4. make sure uiowa_auth is enabled

### CODE REVIEW

**Comment by dnkemper** [comment]
@richardbporter I hope I implemented this correctly and I'm sorry for being a brat and "stealing" your issue of choice 🥺

**Comment by richardbporter** [comment]
No worries. I'll look at this when I can.

 One thing I know that needs to be done is adding another `testsuite` entry to `phpunit.xml.dist` much like the other ones but for uiowa_auth:

https://github.com/uiowa/uiowa/blob/7302e42f81251f490e6bde7b059b7fb8fdb4c560/phpunit.xml.dist#L25-L44

This will get the automated tests to run in Travis.

**Comment by richardbporter** [comment]
We'll also need an update hook in sitenow.install to flush all caches because Drupal won't be able to find this module until then since it is changing locations.

**Comment by dnkemper** [comment]
@richardbporter AWESOME! On it!

**Comment by pyrello** [comment]
> We'll also need an update hook in sitenow.install to flush all caches because Drupal won't be able to find this module until then since it is changing locations.

Does that mean this also needs to be an off-hours deployment? Because the location of the module will change immediately when the deployment occurs, but the cache rebuild will happen slowly site-by-site.

**Comment by richardbporter** [comment]
> > We'll also need an update hook in sitenow.install to flush all caches because Drupal won't be able to find this module until then since it is changing locations.
> 
> Does that mean this also needs to be an off-hours deployment? Because the location of the module will change immediately when the deployment occurs, but the cache rebuild will happen slowly site-by-site.

Yes. I was looking for that label.

**Comment by richardbporter** [comment]
Might also be good to merge this branch into develop and test logging in there since we can't test shib login locally.

**Comment by richardbporter** [comment]
Finally starting to look at this. 👀

**Review by richardbporter — APPROVED** [review]
Everything seems to work for me. I will approve now but leave in draft mode. I will plan on merging at the end of the day today and scheduling an overnight release. Thanks @dnkemper !

**Comment by dnkemper** [comment]
Thank YOU @richardbporter!

**Pull request merged**
