### PR TITLE
Quote block type

### LINKED ISSUE #2881: Add Quote block type
# Story

As a content editor I want to be able to embed structured block quotes in my page so that I can display quotes and associate them with a person.

# Motivation

It looks like there is a V2 blockquote paragraph type and we maybe decided at some point to just translate that into text areas formatted as `<blockquote>` when we migrate the content.

However, in trying to construct a nice looking block quote like what is currently on the Grad College homepage, it is very hard to do it.

<details>

Grad College homepage example:
Screen Shot 2021-01-17 at 10 18 48 AM

My attempt at recreating this:
Screen Shot 2021-01-17 at 10 19 23 AM

My recreation doesn't look terrible, although it could look much nicer. It is however, not intuitive at all. I ended up creating a text area to create the actual quote above, then a card with the additional information below it. It would be nice to be able to create a structure like this without having to go to so much trouble.

</details>

# Proposed solution
- [x] Set permissions for this block
- [x] Check site split permissions?
- [ ] Use existing prototype code listed at https://github.com/uiowa/uiowa/issues/2881#issuecomment-952281022
- [x] Create a Blockquote block with:
  - Content field
  - Footer field
  - Citation field with url and link text 
  - Image fields
  - Blockquote style settings:
    - Left (default)
    - Right 
    - Center
  - Image position: 
    - Within `<footer>`
    - Above content  

**Examples of how this would look:**

https://uids.brand.uiowa.edu/branches/feature_blockquote_prototyping/components/detail/blockquote--default.html

## Future slice

- [ ] Add a reference field that would reference the profile content type without manually adding image, content, citation, etc.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2881 
# How to test

```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
blt ds --site=sandbox.uiowa.edu
drush @sandbox.local uli
```
- Test on v2 to see if it still works, the only change should be that the cite url displays below the footer instead of inline. 

Screen Shot 2021-11-12 at 12 12 34 PM

- Test on v3

## Still Todo
- [x] Will need to merge blockquote [PR](https://github.com/uiowa/uids/pull/603) in uids so can commit to hash - so PLEASE DON'T SOLVE MERGE CONFLICT!

### CODE REVIEW

**Comment by cory-skeers** [comment]
Taking a look at this! (And I won't fix the merge conflict, I promise.)

**Comment by dnkemper** [comment]
baha THANK YOU, @cory-skeers! Also thank you for reading everything first 🙈

**Comment by makurj** [comment]
You beat me to it @cory-skeers!

**Comment by cory-skeers** [comment]
In the farthest right blockquote here, the gold border color is being overwritten by the `border-color: inherit` leading to a gray border accent only on that one. Not sure if that's the intended behavior and the others should be gray, or it it should be gold in this case. (It's on the white community background.)

image

Edit: Looks like the far right is correct--switching to gold background then leads to the proper white accent on that one, but gold border accents on gold bg in the others.

**Comment by dnkemper** [comment]
@cory-skeers first of all, I'm here for your testing content 🤣 Second, I have a feeling that is definitely not intentional behavior, but also think we might need to wait for @bspeare on this. Dang. I'm sorry about that! BUT NICE TESTING! Ninja! Thank you!

**Comment by quamsta** [comment]
Is it expected for the user to provide the left/right angled quotation marks for a quotation?

**Comment by bspeare** [comment]
> Is it expected for the user to provide the left/right angled quotation marks for a quotation?

Yes, that is the current expected behavior.

**Comment by bspeare** [comment]
Thanks for finding that anomaly @cory-skeers, we will work on a fix.

**Comment by cory-skeers** [comment]
There's a similar case of border color not adjusting for background in v2--noting to make sure it gets tested as well after the v3 fix.

Otherwise, I've tested the block on v2 and v3 generally. For v2, I'm not sure of a site that is currently using the blockquote to check on, but when adding new blockquotes it works (and looks) as expected.

**Comment by cory-skeers** [comment]
Checked on the existing blockquotes in law.uiowa.edu/node/126 and law.uiowa.edu/node/661, and there's no visual change there.

**Comment by bspeare** [comment]
@cory-skeers the background colors issue should be fixed if you want to run through the testing commands in the "how to test" section again to update the UIDS version.

**Comment by cory-skeers** [comment]
The borders are working great for v3. v2 doesn't have the background adjustment, and has gold for all backgrounds (but it's consistent for all alignments).
image

There's some inconsistency in the sizing of the images that I'm not sure where it's coming in. I expect some of it is the content setup I've done here, but I'm not sure what's leading to the three different sized images in the second, third, and fourth regions here.

image

Edit:
Updated the third and fourth regions to have the exact text content in addition to same image, and they both end up sized the same, so maybe it's only a poor content setup with it.
image

**Comment by bspeare** [comment]
Thanks @cory-skeers, Great finds - again!

**Comment by dnkemper** [comment]
@cory-skeers Is a super sonic tester 🙌🏼

**Comment by bspeare** [comment]
@cory-skeers I've added a few updates to help that squishing, but I think the right and left aligned will struggle in the four column layouts unless we add some overrides if it is used within those columns.  Preferably, we could wait until https://css-tricks.com/say-hello-to-css-container-queries/ is ready to make those types of overrides.    We could advise users to use the "Image above content" option if they want to use these in four column layouts and reduce the amount of image squish. 

V2 background combos should be working now as well.

**Comment by cory-skeers** [comment]
> V2 background combos should be working now as well.

Yup! Tested it with the latest changes, and can confirm. Thanks!

**Comment by cory-skeers** [comment]
> We could advise users to use the "Image above content" option if they want to use these in four column layouts and reduce the amount of image squish.

@bspeare I think that's definitely a good recommendation: The image above content seems to always work well, regardless of other settings. Can still create some squishing, but with the latest updates it appears more consistent, and the word-wrapping sometimes prevents it.

Were you thinking including it in known issues until CSS queries are available, or did you have a different idea of where to make that kind of recommendation visible?

That's the last thing in my testing I've seen, so if we have that covered through documentation somehow, I think this could be ready for the uids PR and final prep for merge.

**Comment by bspeare** [comment]
@cory-skeers Now that you mention it, it might be worth creating some overrides for three and four column layouts.   I'll push something up shortly.

**Comment by bspeare** [comment]
@cory-skeers I added some overrides for three and four column layouts.   Thanks for noticing this!  I think these changes will make it look a lot better in those layouts.

**Comment by GaryRidgway** [comment]
I have REVIEWED. I have been told to review the stackiness of three and four column footer style placements, so i have done just that and they look good!
Screen Shot 2021-11-16 at 10 50 03 AM
Screen Shot 2021-11-16 at 10 49 58 AM
 If this is all that was needed for final testing i would say we are good!

**Review by GaryRidgway — APPROVED** [review]
REVIEWED

**Comment by joewhitsitt** [comment]
As I mentioned to @dnkemper, might want to hold on merging this if https://github.com/uiowa/uiowa/pull/4091 is close. Should simplify the permissions work in the PR.

**Comment by pyrello** [comment]
I'm having trouble deciding whether I want to add the "CATS CATS CATS CATS CATS..." or "SALAD SALAD SALAD SALAD SALAD..." to my site.

**Comment by dnkemper** [comment]
Going to remove perms then merge this beaut after grooming. Or should I hold off on merging it until CS2 is deployed?

**Comment by pyrello** [comment]
Don't need to wait until #4091 has been deployed, but wait until we have merged it?

**Pull request merged**
