### PR TITLE
CORS Handling for paths and json file extensions

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/7667 and https://github.com/uiowa/uiowa/issues/7686

This opens things up a bit with specifying file types and paths instead of handling a list of allowed origins and opening everything up using the Drupal Core CORS functionality in the services.yml file.

# How to test

## JSON:API endpoints:

- Using https://signage-dev.uiowa.edu/admin/config/services/hawkalert set the endpoint to https://emergency.stage.drupal.uiowa.edu/api/active
- Go to https://signage-dev.uiowa.edu/admin/config/development/performance and clear caches
- Visit https://signage-dev.uiowa.edu/college-education/coe-main in an anonymous browser session and open up the console log. See that there are CORS related errors about every min.
- Go back to https://signage-dev.uiowa.edu/admin/config/services/hawkalert and set the endpoint to https://emergency.dev.drupal.uiowa.edu/api/active
- Go to https://signage-dev.uiowa.edu/admin/config/development/performance and clear caches
- In the anonymous browser session, do a hard refresh. CORS issues should no longer be outputting.
- Go to https://emergency.dev.drupal.uiowa.edu/node/51/edit and change the authored date to now.
- Wait for the anonymous browser session on signage-dev to update. The hawk alert should display.

## Workflow Form

_Waiting on workflow form to test against_

## JSON file extensions:

This should work:
https://cors-test.codehappy.dev/?url=https%3A%2F%2Fgrad.dev.drupal.uiowa.edu%2Fsites%2Fgrad.uiowa.edu%2Ffiles%2F2024-05%2FJSON.json&origin=https%3A%2F%2Fworkflow.uiowa.edu&method=get

This should not:
https://cors-test.codehappy.dev/?url=https%3A%2F%2Fgrad.uiowa.edu%2Fsites%2Fgrad.uiowa.edu%2Ffiles%2F2024-05%2FJSON.json&origin=https%3A%2F%2Fworkflow.uiowa.edu&method=get

For more in-depth testing, I think a workflow form is necessary.

## Alternative testing

With a postman account you can run these tests and observe the access-control headers responses for DEV tests.
https://www.postman.com/joewhitsitt/workspace/sitenow-postman/collection/19389417-833749e4-ed0e-4250-9042-cd0041555cf2?action=share&creator=19389417

Screenshot 2024-05-21 at 4 00 52 PM

### CODE REVIEW

**Comment by joewhitsitt** [comment]
~~well shoot. postman can consume emergency.stage just fine leading me to believe something is wrong with my local environment instead. this may still be useful for https://github.com/uiowa/uiowa/issues/7667~~

UPDATE: Nope, turns out Postman web isn't doing the same kind of request so we do have a CORS issue.

**Comment by joewhitsitt** [comment]
This seems to be working for the emergency site. https://github.com/uiowa/uiowa/issues/7686#issuecomment-2122772426

I am scratching my head as to why OnIowa events api didn't have this issue.

**Comment by joewhitsitt** [comment]
Going to push a change to cover the starting pattern of `/api/` instead of the emergency specific `/api/active` to cover future JSON:API endpoints.

**Comment by joewhitsitt** [comment]
I believe this version is working for both paths and the *.json file type.

**Comment by pyrello** [comment]
I have confirmed this works for a workflow form.

**Review by pyrello — APPROVED** [review]
This works. Nice solution!

**Comment by joewhitsitt** [comment]
Something I noticed in setting up for demonstrating v1 support for the new hawk alerts is that initially when I switch endpoints it doesn't like the CORS response. This seems similar to what Sean experienced when testing the PR. As soon as I make an update to the emergency.stage site and refresh the consuming site, it likes the CORS response. Using CORS testers on the web, it looks like the CORS response is part of the varnish response back, but I worry that there is something not quite right with the request/response to keep this reliable unless it is only on the consumer side and we just need to trigger a change on the website after everything is deployed/switched.

**Pull request merged**
