### PR TITLE
Feature split for uiowa_maui

### LINKED ISSUE #6407: Uiowa MAUI module to feature split
Move the uiowa_maui module to a feature split so it can be enabled per site. 

Annette Beck would like to recreate it on https://ucbasbls.prod.drupal.uiowa.edu/

Example: https://basbls.uc.uiowa.edu/

image

Please reach out to Annette when this is ready. Email flagged in ITS Web inbox.

### PR DESCRIPTION
**Pull request by makurj**
Resolves #6407 

# How to test

```
ddev blt ds --site=default
```
```
ddev drush @default.local config-split:activate uiowa_maui
```

Go to layout builder page and look for "Academic Dates" Block in "Site Custom" area.

### CODE REVIEW

**Comment by makurj** [comment]
After deployment, enable on https://ucbasbls.prod.drupal.uiowa.edu/

Also, note https://github.com/uiowa/uiowa/issues/6407#issuecomment-1545901314

**Comment by bspeare** [comment]
@joewhitsitt any concerns with making this change: https://github.com/uiowa/uiowa/pull/6446/commits/6db3be2501f96ba534fc853532f7f86f3d7ab6e9?

**Comment by joewhitsitt** [comment]
> @joewhitsitt any concerns with making this change: [6db3be2](https://github.com/uiowa/uiowa/commit/6db3be2501f96ba534fc853532f7f86f3d7ab6e9)?

No concerns from me. That may allow some split display settings to go away if that was the only diff.

**Comment by bspeare** [comment]
Thanks @joewhitsitt, do we clean up those split display settings here or later?

**Comment by joewhitsitt** [comment]
I assume after once the feature has been successfully enabled for the sites that need it. Looks like housing, grad and config/default/core.entity_view_display.node.page.banner.yml would benefit

**Review by bspeare — APPROVED** [review]
Works great!

**Pull request merged**
