### PR TITLE
[ P2LB ] Clear tempstore on con/revert

### PR DESCRIPTION
**Pull request by cory-skeers**
# How to test

```
ddev blt ds --site hawkeyemarchingband.uiowa.edu && ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y && ddev drush @hawkeyemarchingband.local cim -y && ddev drush @hawkeyemarchingband.local uli
```

1. Sync down a v2 site of your choice, we used hawkeyemarchingband
2. Enable p2lb
4. Change the layout on two pages
3. Convert those two pages
13. Neither of them should have the "You have unsaved changes" message on the LB page. 
5. on the first page  
    a. publish it
    b make a change
8. On the second page. 
    a. leave it draft
    b. make a change 
11. they should both say "You have unsaved changes" on the LB page
12. Revert them both
13. Neither of them should have the "You have unsaved changes" message on the LB page.

### CODE REVIEW

**Comment by cory-skeers** [comment]
This currently works by going directly to the tempstore and manually crafting the key, which is probably suitable enough for this, but would be fragile against any changes  to layout builder or our system that could affect the key.

Going to look into using the dedicated https://api.drupal.org/api/drupal/core%21modules%21layout_builder%21src%21LayoutTempstoreRepositoryInterface.php/interface/LayoutTempstoreRepositoryInterface/9.3.x and how the clearing gets done from the "Discard Changes" link, as I'm sure there is a better way to do this.

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
```
FILE: ...wa/uiowa/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1530 | ERROR | [x] Data types in @param tags need to be fully
      |       |     namespaced
```

**Comment by joewhitsitt** [comment]
Testing instructions checkout out after putting on the "as an admin..." hat.

Looks like Travis is upset though.

>Use dedicated layout_builder.tempstore_repository service instead

Why not now?

**Comment by cory-skeers** [comment]
> > Use dedicated layout_builder.tempstore_repository service instead
> 
> Why not now?

Leftover from the initial commit. It's since been updated.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
