### PR TITLE
UIPress Cart Button

### LINKED ISSUE #4797: UI Press - Create "view cart" button to appear in the top nav or top links
# Story

As a UI Press customer, I can see a persistent "View cart" button in the top navigation. 

Screen Shot 2022-02-10 at 3 58 58 PM

# Proposed solution

- https://github.com/uiowa/uiowa/issues/2873?
- Create custom block for uipress_core?
- Add the ability to select font awesome icon and add a custom class to a link in the main navigation?

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #4797 

# How to test

1. blt ds --site=uipress.uiowa.edu
2. blt frontend
3. drush @uipress.local cr
4. View cart button  - should have a cart icon

NOTE: Not a fan of the styling needed to get this inline with the menu text. Need another opinion. Also looked into menu block button... big fan of that BUT understand

### CODE REVIEW

**Comment by dnkemper** [comment]
NOTE: Not a fan of using a negative margin style. Had to apply class of fa-icon to menu list item instead of link inside of the menu list item since when hover over link, font icon would move below link underline action. 

I changed the stylesheet to 'global' since the book styles targeted the book. Removed the book specific library and created a preprocess function to apply globally. Updated stylesheet and labeling for consistency and clarity.

**Comment by dnkemper** [comment]
Wanted to learn how block button would work, so here's how if need to go that route: https://github.com/uiowa/uiowa/pull/4813/files

**Review by bspeare — APPROVED** [review]
@dnkemper I made a couple adjustments to make it look a little closer to the mockup.  Otherwise, it looks good! There's not a great solution to show the "View cart" link for mobile since it is in the accordion menu.   Perhaps that can be addressed in a future slice.

**Comment by bspeare** [comment]
Should we remove the "view cart" button from the content type in this pr?   If so, let's move this back to draft.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
Oops. Got confused about the state of this PR:

>bspeare marked this pull request as ready for review [2 hours ago]

Reviewed it chrome/firefox. Looks fine.

**Comment by bspeare** [comment]
@joewhitsitt thanks I just wanted a second look!

**Pull request merged**
