### PR TITLE
Update simplei colors to match brand.

### LINKED ISSUE #1556: Change environment indicator colors to match brand
These are hex values set in settings: https://github.com/uiowa/uiowa/blob/2557c1dfc2f289465e6363cf6c6951dd6560dab6/docroot/sites/settings/sitenow.settings.php#L15-L30

Multiple people have complained about them. We should change them to colors set in UIDS.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1556 

I swapped test and prod because I thought we mentioned toning down the prod indicator since most customers do not interact with local, dev, or test instances. Thoughts?

Prod
image

Test/Stage
image

Dev
image

Local
image

How to test
Check out the branch locally and override the `$env` variable in sitenow.settings.php to dev/test/prod/local. Refresh. Don't commit.

### CODE REVIEW

**Review by bspeare — APPROVED** [review]
I like the switch!  Reviewed and not tested locally.

**Comment by mark-bennett-uiowa** [comment]
I agree. Great change! Thanks Rick.

**Review by mark-bennett-uiowa — APPROVED** [review]
Also reviewed, not tested. Seems like a simple, single file change.

**Comment by richardbporter** [comment]
Added mention of the environment indicators to the docs but could probably be worded better. https://sitenow.uiowa.edu/documentation

**Pull request merged**
