### PR TITLE
[Registrar] GPA Calculator

### LINKED ISSUE #7852: GPA Calculator
# Story

As a site owner of registrar.uiowa.edu, I would like to have a GPA calculator so transfer students and other users that do not have a hawkid, still have access to a University branded GPA Calculator.

# Additional Info

They are happy with existing GPA calculator - https://registrar.uiowa.edu/gpa-calculator

Allows for figuring out gpa for credits/grades entered as well as overall gpa if cumulative gpa and number of credits are entered.

Current site has a configuration page that contains letter grade to GPA mappings and additional config. They didn't think this is necessary as they didn't think this has been updated since it was launched.

Last time I checked there was a D10 compatible release of the module we used for D7 https://www.drupal.org/project/gpa_calculator.

Block component would be great so they can add supporting text themselves.

Open to this being a little different if necessary (if add row functionality is complex, we could possibly just have a specific number of rows available).

UNI example https://registrar.uni.edu/students/gpa-calculator.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #7852 

# How to test

```
ddev blt ds --site registrar.uiowa.edu && ddev drush @registrar.local uli
```
- Create a page or select an existing one to use.
- Visit the layout tab and add the GPA Calculator block.
- Test the form
- Test adding a new row
- Try to enter a non-numeric key on https://registrar.uiowa.ddev.site/admin/config/gpa_calculator

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Comment by bspeare** [comment]
Maybe this was discussed at EoD, do we need the "Previous" in the form labels like on the D7 site?  And the help text for _GPA is based on graded (A,B,C,D,F) courses. Total semester hours should be the number of hours in graded courses. (No Pass/Fail courses)_?Screenshot 2024-07-09 at 9 41 39 AM

**Comment by briand44** [comment]
I'm not sure leaving out the word "Previous" was discussed in EOD. Sean did mention he removed the School and Instructions fields from the configuration page to keep maintenance down on this module. I think the assumption is that they can provide instructions/support context through existing functionality outside the module. We can get feedback from Josh later today.

**Comment by bspeare** [comment]
It looks like this gpa calculator table is just made of divs with table classes on it.  Could we update the module to use table markup to make this accessible?  Also, should the "Add row" link be a button to make this more accessible as well?

**Comment by pyrello** [comment]
> It looks like this gpa calculator table is just made of divs with table classes on it. Could we update the module to use table markup to make this accessible? Also, should the "Add row" link be a button to make this more accessible as well?

This would start with opening an issue in the module issue queue. 

Based on the lack of a proposed solution and grooming notes that don't provide clear parameters, this issue is ambiguously scoped. I'm not sure if making these changes to the module should be a part of this work or not. Possibly changing the markup is a trivial issue, but maybe its not. The state of the module and this PR at the point I put it up for review reflected my best guess on what would be appropriate scope. I'm open to expanding the scope but would like the input of @briand44  and the rest of the team.

**Review by bspeare — APPROVED** [review]
Works as expected!

**Pull request merged**
