### PR TITLE
Events by presenter listing

### LINKED ISSUE #5968: Show events on person page (presenter)
# Story
As a SiteNow events user, I would like events that reference a person (presenter) to be displayed on that person's profile page so that users can easily find more events where that person is presenting.

# Additional Info
[https://iowasummerwritingfestival.org/zach-savich](https://iowasummerwritingfestival.org/zach-savich)

# Proposed Solution

- [x] Establishing a view block that takes a contextual argument for entity id
- [x] Output using sub event display format (title, date, presenter, short description)
- [x] Show both upcoming and past events
- [x] Display in reverse chronological order
- [x] Limit number of items to 10

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5968 

# How to test

Event feature:
```
ddev blt ds && ddev drush @default.local config-split:activate event -y && ddev drush @default.local uli people/herky-hawk
```
- View Herky's page to ensure that no view display shows up.
- Go to https://default.uiowa.ddev.site/node/add/event
- Add an event called "Parent event" and add Herky as a presenter.
- Add another event called "Child event" and add Herky as a presenter.
- Add an event in the future and in the past.
- If you want to add a total of 12 events to make sure that no more than 10 show up, I won't stop you.
- View Herky's page again: https://default.uiowa.ddev.site/people/herky-hawk
- Check that the event listing meets the criteria in #5968
- Ensure that "Parent event" doesn't show up on Herky's page

ISWF:
```
ddev blt ds --site iowasummerwritingfestival.uiowa.edu && ddev drush @iowasummerwritingfestival.local config-split:activate event -y && ddev drush @iowasummerwritingfestival.local en better_exposed_filters -y && ddev drush @iowasummerwritingfestival.local config:import --source ../config/sites/iowasummerwritingfestival.uiowa.edu --partial -y && ddev drush @iowasummerwritingfestival.local cim -y 
```
- Repeat similar testing as above.

Admissions:
```
ddev blt ds --site admissions.uiowa.edu && ddev drush @admissions.local uli counselor/jessica-klein
```
- Just ensure that the present events block does not display on the person page.

### CODE REVIEW

**Comment by bspeare** [comment]
Empty person page event listings are a little weird.   Should we try to figure out a better way to render empty person images?

Screen Shot 2022-12-21 at 11 47 41 AM

**Comment by bspeare** [comment]
This build is currently failing because of Percy and the Hawk Alert.   Should we adjust our Percy settings to hide the Hawk Alert wrapper?

**Comment by joewhitsitt** [comment]
>Should we try to figure out a better way to render empty person images?

Should they display at all? Was there a technical hurdle here previously? Or if the other fields below it are also empty, unset?

**Comment by bspeare** [comment]
@joewhitsitt that is a good idea about unsetting it.  However, what about profiles that are just image and email? https://uicb.uiowa.edu/people/mariana-mazer

**Comment by joewhitsitt** [comment]
>However, what about profiles that are just image and email?

I mean if there is content, it should be displayed. I thought you were only concerned about empty person images. Part of the downside of the left/right layout on desktop is that there isn't always content or enough content on the left.

**Comment by bspeare** [comment]
@joewhitsitt do we want to preprocess to check all the fields for https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/views/views-view-unformatted--person-card.html.twig#L83.  Plan that for future work?

**Comment by joewhitsitt** [comment]
IMO if things are just a "little weird," let's not let this work slow down. We could potentially hide the view if empty instead of checking everything in twig. https://github.com/uiowa/uiowa/pull/5951#issuecomment-1351675470

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
looks good. thanks for working on it.

**Pull request merged**
