### PR TITLE
SPPA -  News Story Migration

### LINKED ISSUE #3343: SPPA: Build article migration
# Proposed solution

- [x] Create SPPA migration module.
- [x] Add article migration.
  - [x] First delta of `field_image_attach` can become the featured image. Any other deltas can be ignored.
- [x] Add article redirect migration.

The following fields can be ignored:
* `field_d8_migration_status`
* `field_multi_public_file`
* `field_newsstory_caption`

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/3343

## To Test

- Sync D7 sppa (urban) site within grad application using Dev Desktop.
- Run the following and configure/save SiteNow Migrate
```
blt sync --site sppa.uiowa.edu && 
drush @sppa.local en sppa_migrate --yes && 
drush @sppa.local uli /admin/config/system/sitenow-migrate
```
```
database = urban
user = root
host = 10.0.2.2
port = 33067
base url = https://sppa.uiowa.edu
```
- `drush @sppa.local cr && drush @sppa.local migrate:status`
- You should see articles and redirects migrations
- `drush @sppa.local migrate:import --all`
- Watch as I ride the hard work of migration experts before me. The migration should be successful.
- Refresh the content overview. There are a lot of articles that got imported but only like three that are published. The first three published items all have images to check. The first image was imported.
- You should be redirected if you go to https://sppa.local.drupal.uiowa.edu/news/2021-03-01/new-certificate-in-urban-studies-for-undergraduates

### CODE REVIEW

**Comment by pyrello** [comment]
I will test this later. Nice work on figuring this out, even if you are standing on the shoulder of those who came before! ;)

**Comment by pyrello** [comment]
I did do a test run of this and noticed some errors that I'm assuming are related to images. Probably not a deal breaker, but want to dig in a little more to that.

**Review by pyrello — APPROVED** [review]
Tested and works well!

**Comment by joewhitsitt** [comment]
Sorry, but I have never gotten this far with a migration PR. What is the next step?

**Comment by pyrello** [comment]
This will be run in prod (right @richardbporter?) and so it needs to be merged for that to happen. So I think we just treat them like regular PRs now.

**Comment by richardbporter** [comment]
Yes. I can help out with running it in prod.

**Comment by pyrello** [comment]
FYI, I don't think we want to run this until we get a bit closer to launch, which seems a bit up in the air at the moment, so we are getting it off the list of things that need to be done!

**Pull request merged**
