### PR TITLE
Create tedabel.lab.uiowa.edu, update Drupal to 9.2.9 and small edit to README.md.

### PR DESCRIPTION
**Pull request by richardbporter**
# How to test

Removed patch for https://www.drupal.org/node/2957953 because it was committed. Updated patch for https://www.drupal.org/node/2429699 to https://www.drupal.org/project/drupal/issues/2429699#comment-14285954.

### CODE REVIEW

**Review by dnkemper — APPROVED** [review]

**Comment by richardbporter** [comment]
Looking for help debugging a visual change on the uiowa search block. Here is an example on admissions, also happening on education:

Screen Shot 2021-11-18 at 10 17 52 AM

**Comment by richardbporter** [comment]
Tested basic WYSIWYG functionality. 👍🏻

**Comment by bspeare** [comment]
I can take a look at the search block.

**Comment by bspeare** [comment]
Looks like these classes are not being applied to the search form: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Form/SearchBlock.php#L26.

**Comment by richardbporter** [comment]
> Looks like these classes are not being applied to the search form: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/uiowa_core/src/Form/SearchBlock.php#L26.

I can look into that.

**Comment by richardbporter** [comment]
I think the key was 9834ee9 but that had some effects on the SearchBlock form build and submit methods. Still trying to understand what core change may have caused this and whether there might be other blocks/forms impacted but this should be working now.

**Comment by joewhitsitt** [comment]
docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/ScholarshipsJumpMenuBlock.php also has a form like that. if you have the branch local can you test https://admissions.local.drupal.uiowa.edu/finances/scholarships

**Comment by joewhitsitt** [comment]
taking a look

update: just checked admissions against the other form i was concerned about and a split export to see if there was any diff. no issues

**Comment by richardbporter** [comment]
Tested uiowa_alerts locally. Seems ok.

**Review by joewhitsitt — APPROVED** [review]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1637273883072000

**Pull request merged**
