### PR TITLE
Redirects don't work with trailing slash in source path

### LINKED ISSUE #3979: Redirects don't work with trailing slash in source path
Looks like there is a patch out there if we want to fix this: https://www.drupal.org/project/redirect/issues/2932615

## Issue
If you go to the redirect configuration (ex https://africanamericanstudies.local.drupal.uiowa.edu/admin/config/search/redirect/add), and add a link with a trailing slash (`/asdf/`) to the `path* field`, and then add where you'd like the redirect to point to (`/about`), if you go to /asdf/ or /asdf, it should take you to the '/about' URL

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3979

Before running composer install, if you go to the redirect configuration (exhttps://africanamericanstudies.local.drupal.uiowa.edu/admin/config/search/redirect/add), and add a link with a trailing slash (/asdf/) to the path* field, and then add where you'd like the redirect to point to (/about), if you go to /asdf/ or /asdf, it should take you to the '/about' URL

After running composer install, if you add a link with a trailing slash (/asdf/) to the path, and then add where you'd like the redirect to point to, if you go to /asdf/ it will redirect you to what you configured - ie the correct way

# How to test

1. checkout branch
2. composer install
3. sync a site (for instance, default)
4. Go to redirect config (https://default.local.drupal.uiowa.edu/admin/config/search/redirect)
5. Add a redirect path with a trailing "/" (ie add "asdf/") and redirect to the about page
6. When you save, make sure trailing slash is removed from redirect. 
7. Go to https://default.local.drupal.uiowa.edu/asdf and https://default.local.drupal.uiowa.edu/asdf/ and make sure b oth redirect to about node

### CODE REVIEW

**Comment by joewhitsitt** [comment]
wonder if we should create a patch off https://www.drupal.org/project/redirect/issues/2932615#comment-14253130 and try that. that is the latest, returns to a more scoped version and has a known core committer

**Comment by dnkemper** [comment]
> wonder if we should create a patch off https://www.drupal.org/project/redirect/issues/2932615#comment-14253130 and try that. that is the latest, returns to a more scoped version and has a known core committer

Ah, okay. Guess I misunderstood this comment then: https://github.com/uiowa/uiowa/issues/3979#issuecomment-898522041

**Comment by joewhitsitt** [comment]
yeah, my comment was back in august, the latest comment/merge request was 4 days ago

**Comment by dnkemper** [comment]
@joewhitsitt cool beans. I'll apply it instead and test it out 🥳

**Comment by joewhitsitt** [comment]
https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/creating-issue-forks-and-merge-requests#s-downloading-a-patch-file-from-a-merge-request

**Review by richardbporter — APPROVED** [review]
Works as advertised.

**Comment by dnkemper** [comment]
@richardbporter you ROCK! Thank you so much!

**Pull request merged**
