### PR TITLE
Initial framework for engineering migrate module.

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #2893.

Initial work for an engineering migration module for use with engineering articles.

# How to test

Need a local copy of www.engineering.uiowa.edu in Dev Desktop (on uiowa703, listed with the www).
Leave the DD Apache/MySQL stack running.

`git checkout engineering-migrate` and `git pull`
`blt ds --site=engineering.uiowa.edu`
`drush @engineering.local en engineering_migrate`
`drush @engineering.local mim d7_engineering_article`

It will most likely terminate. 
 - If it terminates with a ` [warning] Memory usage is now 442.78 MB (86% of limit 512 MB), not enough reclaimed, starting new batch` you can simply run the `mim` command above again. 
 - If it terminates with a `Drush command terminated abnormally`, you will have to run: 
     - `drush @engineering.local mst d7_engineering_article` to stop the migration, then 
     - `drush @engineering.local mrs d7_engineering_article` to reset the migration to Idle, 
     - and then run the `mim` command again.
   
`drush @engineering.local mim d7_engineering_article_redirect`

Check that migration completes successfully. Currently there is a discrepancy in row counts--a 'complete' migration should import 1139 articles.

Spot check articles and see that nothing looks out of place, that articles from the existing site which had featured images have featured images post-migration.

For inline images, can check the database for any body fields containing a `<!--Missing image: @filepath-->` token.

Spot check for any other gotchas that you can think to check for that may not have migrated over correctly.

With the redirect migrate, can start at https://www.engineering.uiowa.edu/news, pick and choose articles, and use the same aliases on the prod site.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Should look into batching these. In testing, running into memory usage errors and needing to run multiple imports in order to complete the migration.

Edit: There's a `batchSize` variable to set in `SqlBase` (extended by the source class), as well as a `batch_size` option in the source plugin, but either they are not working properly, or there is a separate memory usage problem not solved by batching.

**Comment by cory-skeers** [comment]
Mapping appears to be complete and functioning, including pulling in tags and mapping author field as plain text into the source organization field.

**Comment by joewhitsitt** [comment]
I am not going to be much help in finding the memory leak from the migrate side of things, but one thing I will say is that the Engineering site as it exists has had database corruption issues in the past that we have had to work through. Not articles related (to my knowledge) but stuff related to panelizer/page manager. Could it be choking on a particular node or could there a base64 image in the markup that makes this time out/leak? Keep in mind, articles were originally migrated from an old site so this could be a remnant of that, etc. Let me know if I am way off, but been thinking about how I could help and this is what came to mind.

**Comment by richardbporter** [comment]
IDK if this is much of a solution but I was able to run both migrations in one go by adding `ini_set('memory_limit', -1);` to the `local.settings.php` file for engineering.uiowa.edu. This disables the memory limit for this site in the local environment. It can and probably should be removed afterwards.

Is this migration going to be run once locally and then synced? If not, disabling the memory limit won't work obviously.

**Comment by cory-skeers** [comment]
Maybe I've just looked at it too much, but I'm confused by the row counts:

`drush @engineering.local ms` gives 1318 rows, when the true count is 1139. Only 1139 nodes will process, which is accurate. Looks like it's joining the `field_data_field_image` that leads to the higher count, but that field doesn't offer multiple values (so no `delta` or otherwise leading to otherwise repeated node entries), and the `leftJoin` should take care of the fact that there are image entries for nodes other than article.

Otherwise, the migration still crashes but can now be restarted and executed to the end (or the crash can be avoided altogether--thanks @richardbporter!).

Few loose ends to tie up, then ready for testing and migration.

**Comment by cory-skeers** [comment]
Marking as ready to review, in case any others want to test. The issue has some notes on the different mappings (old department taxonomy being mapped to tags, etc). I'm currently running a test migration to check that everything looks good, which may lead to updates, but no further work is expected at this time.

**Comment by cory-skeers** [comment]
~Inline "fid" text in the following pages; checking to see if they're links to PDFs, files, etc., that may be broken from migration.~

~43 total--not too bad.~

False positives. Looks like we're clear.

**Review by richardbporter — APPROVED** [review]
I tested this the other day. Looks like enabling it results in a config diff which is fine since it will only run locally and then be turned off.

**Pull request merged**
