### PR TITLE
sitenow field_reference clean-up/hr.uiowa.edu split

### LINKED ISSUE #860: field_reference clean-up
Blocked until #841 has been deployed.

- [x] Remove field_reference from sitenow profile. keep it in hr.uiowa.edu for now.
- [x] Remove References view.
- [x] Move remaining field_reference logic out of sitenow into hr_core.
- Update docs
  - [x] https://sitenow.uiowa.edu/node/121
  - [x] https://sitenow.uiowa.edu/node/126

### PR DESCRIPTION
**Pull request by joewhitsitt**
# Description
Resolves #860 , blocked by #841.

# Checklist
- [x] Add appropriate PR labels.
- [x] Request approval from multiple developers across units.
- [ ] Dependencies have been properly updated.
  - https://github.com/uiowa/uiowa#updating-dependencies
- [x] Site config splits have been accounted for.
  - Go to https://github.com/uiowa/uiowa/find/master to find split config entities affected by this PR.
- [x] Test PR locally with default site.
- [x] Test PR locally with custom site that might be affected by these changes.
- [x] Update documentation.
  - Document changes introduced by this PR in application, profile or site README.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I think this is ready, but blocked until a new release (1.4.6) has been deployed.

**Comment by joewhitsitt** [comment]
no longer blocked.

**Comment by richardbporter** [comment]
I'm not sure what to test here, if anything.

**Comment by joewhitsitt** [comment]
Default sites should not have a References field. Just a Tags field. HR should have a Units and Tags field. No config import errors.

**Pull request merged**
