### PR TITLE
Update uids to 3.5.0

### LINKED ISSUE #4771: Adjust `blt frontend` to upgrade the `uiowa/uids` package
# Problem
`blt frontend` is not updating UIDS properly when run locally.   We've been using workarounds like `rm -rf ./node_modules` and
`yarn cache clean` to make sure it updates properly and removes the previous version.  

# Proposed solution
Investigate `blt frontend` process and find out why `node_modules/@uiowa/@uids` is either not updating or is still cached after running `blt frontend`.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #4771, maybe.

# How to test

- Check out branch.
- Run `blt frontend`
- Ensure node_modules/@uiowa/uids/package.json says 3.5.0
- Test other stuff.
- yeehaw

### CODE REVIEW

**Comment by GaryRidgway** [comment]
https://github.com/uiowa/uiowa/issues/4759

**Comment by bspeare** [comment]
As I mentioned https://github.com/uiowa/uiowa/issues/4771#issuecomment-1035541603, there are a bunch of breaking changes to this UIDS update that Percy is not seeing because it doesn't take screenshots at larger screen resolutions.  I can update `uids_base` in this pr so we can get this change merged in.

**Review by bspeare — APPROVED** [review]
This works, I was able to see the update to 3.5.0.

**Comment by richardbporter** [comment]
Ok. Let's try out this workflow for a bit and hopefully it resolves #4771. 🤞🏻 Thanks for catching those!

**Pull request merged**
