### PR TITLE
[Bug] Blockquote 

### LINKED ISSUE #7923: Blockquote block footer paragraph sizing is incorrect
# Problem
In https://github.com/uiowa/uiowa/pull/5569, we didn't account for the sizing difference that would occur with introducing the Basic HTML `<p>` tags into the blockquote footer. 

Unknown

Unknown-1

# Steps to reproduce
Compare these two blockquote implementations:

- https://tippie.uiowa.edu/undergraduate/majors/entrepreneurship
- https://tippie.uiowa.edu/iowa-mba/curriculum

# Proposed solution
In UIDS, update CSS scoping to include `<p>` in footer.

### LINKED ISSUE #7926: Blockquote left alignment options are not getting the classes from `quote_left` layout builder style
# Problem
The Blockquote left alignment options are not rendering as expected.   In https://github.com/uiowa/uiowa/pull/6054, we made some updates to the layout builder style defaults.   

The "Left (default)" option is set as the default, but we need the "Left" option to apply the `blockquote--left` styles to the block. 

Screenshot 2024-07-18 at 2 35 56 PM

**Currently rendering as:**

Screenshot 2024-07-18 at 10 43 22 AM

**Expected:**

Screenshot 2024-07-18 at 10 43 38 AM

# Steps to reproduce
- https://sandbox.prod.drupal.uiowa.edu/blockquotes

# Proposed solution
- Rewrite blockquote styles so that left aligned is the default style so that it no longer needs the `quote_left` lb style and `blockquote--left` modifier.

### LINKED ISSUE #7982: CKEditor presents blockquotes in italics, when UIDS and published pages don't
# Problem
Small issue, but anytime a `<blockquote>` tag is used in CKEditor, in the editor itself we see text presented in italics:

Screenshot 2024-08-14 at 1 14 13 PM

[But according to UIDS](https://uids.brand.uiowa.edu/3.x/components/detail/blockquote--default.html), blockquotes are not presented in italics by default, and the resulting published page/block looks like:

Screenshot 2024-08-14 at 1 15 48 PM

# Steps to reproduce
1. Make a new page/block with a blockquote in it
2. Note that the text within the blockquote appears in italics
3. Save and publish the page
4. Note that the text within the blockquote does not appear in italics

# Proposed solution(s)

In UIDS, ensure that `<blockquote>` elements have the proper CSS defining the `font-style`, currently, UIDS 3 has the erroneous line in [blockquote.scss](https://github.com/uiowa/uids/blob/3.x/src/components/blockquote/blockquote.scss):

`font-style: none;`

That should be:

`font-style: normal;`

Additionally, investigate and/or remove CKEditor styles that are appearing in `<style>` tags after all CSS `<link>` tags since it appears UIDS styles are being overriden by this `<style>` tag placed in the DOM after all `<link>` tags:

```
<style data-cke="true">.ck-content blockquote{border-left:5px solid #ccc;font-style:italic;margin-left:0;margin-right:0;overflow:hidden;padding-left:1.5em;padding-right:1.5em}.ck-content[dir=rtl] blockquote{border-left:0;border-right:5px solid #ccc}</style>
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7923.
Resolves https://github.com/uiowa/uiowa/issues/7926. 
Resolves https://github.com/uiowa/uiowa/issues/7982. 

# How to test https://github.com/uiowa/uiowa/issues/7923

```
ddev blt frontend && ddev blt ds --site=tippie.uiowa.edu && ddev drush @tippie.local uli /undergraduate/majors/entrepreneurship
```

- Review https://github.com/uiowa/uids/pull/937
- Compare `/undergraduate/majors/entrepreneurship` against `/undergraduate/majors/entrepreneurship` and confirm the text on each of the blockquotes look pretty much the same.   Check the prod site or screenshots on the original issue to compare. 

# How to test https://github.com/uiowa/uiowa/issues/7982.

- Edit a blockquote in the WYSIWYG and confirm that text is not italic.

# How to test https://github.com/uiowa/uiowa/issues/7926

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /blockquotes
```

- Compare `/blockquotes` against prod `/blockquotes`
- Confirm that the prod `/blockquotes` https://sandbox.prod.drupal.uiowa.edu/blockquotes second blockquote with the image that has the `Left` selection is set to `Left (Default)` after syncing and renders the same way. 
- Confirm duplicate `Left` options are no longer appearing in the `Content Alignment` options. 
- Does this need an update hook?

### CODE REVIEW

**Comment by joewhitsitt** [comment]
now that this resolves _three_ issues, i gotta see it for myself! pulling to test

**Comment by joewhitsitt** [comment]
Ack! I see @e-marie-w had the same idea but started at the other end of this: https://github.com/uiowa/uids/pull/937#event-13886368688

**Review by e-marie-w — APPROVED** [review]
Blockquotes are now identical (no more font size differences) and do not appear italicized in the WYSIWYG. The Left option is now removed and any blockquotes using it are successfully switched to the Left (Default) option. 

I don't believe this needs an update hook so I'm approving. But a second opinion might be nice, as I'm not 100% certain.

**Comment by bspeare** [comment]
Thanks @e-marie-w!

**Pull request merged**
