### PR TITLE
v2 articles and people column width bug

### LINKED ISSUE #7665: v2 Articles and People column width settings offers a `-none-` option that does not apply width to the container
# Problem
v2 Articles and People column width settings offers a `-none-` option that does not apply width to the container when the default of `Full` should be selected. 

Screenshot 2024-05-09 at 3 05 18 PM

# Steps to reproduce
https://pentacrestmuseums.uiowa.edu/about/staff-directory has `-none-` selected. 
Screenshot 2024-05-09 at 3 06 56 PM

# Proposed solution
- Remove `-none-` option and update hook to set as `Full`?

### PR DESCRIPTION
**Pull request by GaryRidgway**
resolves https://github.com/uiowa/uiowa/issues/7665

1. On `main`, sync `pentacrestmuseums.uiowa.edu`
2. Run `ddev drush @pentacrestmuseums.local sqlc`
3. In the MySQL terminal, run the following commands, and copy their output to a scratch text file:
    1.  Get all people with the `paragraph__field_uip_colwidth` field set
    ```
    select * from paragraph__field_uip_colwidth where bundle="people";
    ```
    2.  Get all articles with the `paragraph__field_uip_colwidth` field set
    ```
    select * from paragraph__field_uip_colwidth where bundle="articles";
    ```
    3.  Get all people revisions with the `paragraph__field_uip_colwidth` field set
    ```
    select * from paragraph_revision__field_uip_colwidth where bundle="people";
    ```
    4.  Get all articles revisions with the `paragraph__field_uip_colwidth` field set
    ```
    select * from paragraph_revision__field_uip_colwidth where bundle="articles";
    ```
4. Checkout this branch, and sync the site again
5. Check that the update hook ran smoothly, and didn't error out.
6. Repeat step 3
7. Note that there are now more entries in the queried data, showing that we found entries without a default set, and we set them, so now they are discoverable by the SQL queries.
8. Sync another v2 site like `hawkeyemarchingband.uiowa.edu` and make sure that the update hook runs with no issues.
9. Code review?

<details><summary>Example output gathered during initial testing.</summary>

```

--BEFORE--

MySQL [pentacrestmuseums_uiowa_edu]> select * from paragraph__field_uip_colwidth where bundle="people";
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| bundle | deleted | entity_id | revision_id | langcode | delta | field_uip_colwidth_value |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| people |       0 |       671 |      122726 | en       |     0 | col-md                   |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
1 row in set (0.000 sec)

MySQL [pentacrestmuseums_uiowa_edu]> select * from paragraph_revision__field_uip_colwidth where bundle="people";
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| bundle | deleted | entity_id | revision_id | langcode | delta | field_uip_colwidth_value |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| people |       0 |       671 |      122696 | en       |     0 | col-md                   |
| people |       0 |       671 |      122711 | en       |     0 | col-md                   |
| people |       0 |       671 |      122726 | en       |     0 | col-md                   |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
3 rows in set (0.002 sec)

--AFTER--

MySQL [pentacrestmuseums_uiowa_edu]> select * from paragraph__field_uip_colwidth where bundle="people";
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| bundle | deleted | entity_id | revision_id | langcode | delta | field_uip_colwidth_value |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| people |       0 |       671 |      122726 | en       |     0 | col-md                   |
| people |       0 |       681 |        6156 | en       |     0 | col-md-12                |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
2 rows in set (0.001 sec)

MySQL [pentacrestmuseums_uiowa_edu]> select * from paragraph_revision__field_uip_colwidth where bundle="people";
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| bundle | deleted | entity_id | revision_id | langcode | delta | field_uip_colwidth_value |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
| people |       0 |       671 |        6246 | en       |     0 | col-md-12                |
| people |       0 |       671 |        6261 | en       |     0 | col-md-12                |
| people |       0 |       671 |        6276 | en       |     0 | col-md-12                |
| people |       0 |       671 |        6291 | en       |     0 | col-md-12                |
| people |       0 |       671 |      122651 | en       |     0 | col-md-12                |
| people |       0 |       671 |      122666 | en       |     0 | col-md-12                |
| people |       0 |       671 |      122681 | en       |     0 | col-md-12                |
| people |       0 |       671 |      122696 | en       |     0 | col-md                   |
| people |       0 |       671 |      122711 | en       |     0 | col-md                   |
| people |       0 |       671 |      122726 | en       |     0 | col-md                   |
| people |       0 |       681 |        6156 | en       |     0 | col-md-12                |
+--------+---------+-----------+-------------+----------+-------+--------------------------+
11 rows in set (0.001 sec)

```

</details>

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
The none option still exists for these paragraphs types. I can make the change to those and check to see if it all still works as expected. Would hate to update all of these and then have new ones added.

**Comment by GaryRidgway** [comment]
> The none option still exists for these paragraphs types. I can make the change to those and check to see if it all still works as expected. Would hate to update all of these and then have new ones added.

Good catch Joe! thanks for adding that in

**Review by joewhitsitt — APPROVED** [review]
Looks good. Nice detective work.

I think the display issue was mainly with article and people, but I updated column width config for a couple other types just to capture a proper value going forward.

**Pull request merged**
