### PR TITLE
UIPress authors migration

### LINKED ISSUE #4663: UI Press - Build migration for Author content type
- 1249 items
- will be migrated into the Person content type

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #4663 

# How to test

Sync `uipress` in DevDesktop (grad container)
`git checkout uipress-authors-migrate && git pull`
`blt ds --site=uipress.uiowa.edu`
`drush @uipress.local en uipress_migrate -y`
`drush @uipress.local uli /admin/config/sitenow/sitenow-migrate`
Complete the form using the help text
`drush @uipress.local ms` <- check that migrations register
`drush @uipress.local mim --all`
See that migration completes, and that 'low dimension image' reporting works
Spot check some authors

### CODE REVIEW

**Comment by dnkemper** [comment]
Alright, someone else def needs to test this. Been two hours and still haven't been able to sync down grad in devdesktop
Screen Shot 2022-03-03 at 11 33 55 AM

**Comment by dnkemper** [comment]
FINALLY! DevDesktop synced grad repo - now synching uipress


Update: same situation as before. UGH

**Comment by richardbporter** [comment]
Is it expected that 10 redirects remain unprocessed after the migration? 
```
 ------------------- ----------------- -------- ------- ---------- ------------- --------------- 
  Group               Migration ID      Status   Total   Imported   Unprocessed   Last Imported  
 ------------------- ----------------- -------- ------- ---------- ------------- --------------- 
  sitenow_migrate     uipress_authors   Idle     1263    1263       0             2022-03-04     
  (sitenow_migrate)                                                               19:23:41       
  sitenow_migrate     uipress_author_   Idle     1273    1263       10            2022-03-04     
  (sitenow_migrate)   redirects                                                   19:24:05       
 ------------------- ----------------- -------- ------- ---------- ------------- ---------------
```

**Comment by richardbporter** [comment]
Randomly checked one author and they seem to have two first names?
Screen Shot 2022-03-04 at 1 32 42 PM

I'm also seeing people with commas at the end of their name:
Screen Shot 2022-03-04 at 1 33 51 PM

**Comment by cory-skeers** [comment]
> Is it expected that 10 redirects remain unprocessed after the migration?

Hrm...Think that's a result of there being more than one alias for some nids, but each nid should only be processed once.

**Comment by richardbporter** [comment]
I should say I'm testing this in the context of #4896 to test Drush but also migrate_tools which was upgraded in that PR. Assuming what I found isn't related to those, our migrate stuff seems to work with that.

**Comment by cory-skeers** [comment]
Takin' a look at the weird names stuff.

**Comment by cory-skeers** [comment]
Fixed the comma issue with some people's names.

> Randomly checked one author and they seem to have two first names?

I'm confused. The site appears to show his name correctly (https://www.uipress.uiowa.edu/people/henderson), but in the node form his first name is repeated in the last name field?
image

**Comment by richardbporter** [comment]
>I'm confused. The site appears to show his name correctly (https://www.uipress.uiowa.edu/people/henderson), but in the node form his first name is repeated in the last name field?

Sounds like that works as designed then. :) Didn't see anyone else with duplicate names.

**Comment by cory-skeers** [comment]
The names have been fixed re: suffixes and errant commas. For the URL aliases, below is the full list of the 10 that don't get processed as part of the migration. They're duplicate aliases for the same node, and seem to have been added or created due to difficulty handling the accented characters (other than volkman/volkmans).

The migration has a lot of trouble handling these as duplicates, and I'm wondering if it would be better to drop the non-accent aliases. Otherwise, I think it would be more efficient to add these manually post-migration than to troubleshoot the duplicate hashing issue the migration runs into trying to handle these.
```
 [notice] Multiple alias found for source id 489: people/virgil-su-rez
 [notice] Multiple alias found for source id 489: people/virgil-suárez
 [notice] Multiple alias found for source id 572: people/marí-carla-sánchez
 [notice] Multiple alias found for source id 572: people/mar-carla-s-nchez
 [notice] Multiple alias found for source id 585: people/jennine-capó-crucet
 [notice] Multiple alias found for source id 585: people/jennine-capó-crucet
 [notice] Multiple alias found for source id 728: people/karen-volkmans
 [notice] Multiple alias found for source id 728: people/karen-volkman
 [notice] Multiple alias found for source id 768: people/mark-muller
 [notice] Multiple alias found for source id 768: people/mark-müller
 [notice] Multiple alias found for source id 906: people/ren-e-manfredi
 [notice] Multiple alias found for source id 906: people/renée-manfredi
 [notice] Multiple alias found for source id 988: people/louis-i-szathm-ry-ii
 [notice] Multiple alias found for source id 988: people/louis-i-szathmáry-ii
 [notice] Multiple alias found for source id 1095: people/g-sli-p-lsson
 [notice] Multiple alias found for source id 1095: people/gísli-pálsson
 [notice] Multiple alias found for source id 1120: people/walter-gr-nzweig
 [notice] Multiple alias found for source id 1120: people/walter-grünzweig
 [notice] Multiple alias found for source id 1236: people/tereze-gl-ck
 [notice] Multiple alias found for source id 1236: people/tereze-glück
```

**Comment by pyrello** [comment]
> The migration has a lot of trouble handling these as duplicates, and I'm wondering if it would be better to drop the non-accent aliases. Otherwise, I think it would be more efficient to add these manually post-migration than to troubleshoot the duplicate hashing issue the migration runs into trying to handle these.

These can be handled manually after the migration. Thanks!

**Review by GaryRidgway — APPROVED** [review]
I have gone through the testing steps and everything worked completely fine for me. I was able to sync, migrate, and see image output for images under 300px. I was experiencing no commas, and no duplicate names in the last name spot. Spot checking a few authors left nothing out of the ordinary.

**Pull request merged**
