### PR TITLE
bulk publishing permissions

### LINKED ISSUE #3610: Ability to bulk unpublish/publish
Admissions said they can't unpublish scholarships. 

I believe the bulk operation for unpublishing may not work on any sites based on perms. 

The below screenshot is from default.prod.drupal.uiowa.edu

Screen Shot 2021-06-03 at 10 30 24 AM

### PR DESCRIPTION
**Pull request by GaryRidgway**
[Admissions wants to be able to bulk un-piblish/publish items](https://github.com/uiowa/uiowa/issues/3610)

# How to test

1. Check out this branch.
2. Sync admissions.
3. Check that the bulk operations are enabled in permissions for webmaster and publisher.
4. try masquerading as webmaster or publisher and un-piblishing/publishing some content in bulk.
5. try masquerading as an editor and see that you cannot do bulk un-piblishing/publishing.

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling down to test.

**Comment by bspeare** [comment]
It looks like this works well with Article, Page, Person, and Scholarship but for the Areas of Study, Student Profiles, and Transfer Tips I get the error message "Something went wrong, the entity must be unpublished by this point. Review your content moderation configuration make sure you have archive state which sets current revision and a draft state and try again. " 

Is that the expected behavior?

**Comment by GaryRidgway** [comment]
I'll check that ben, i totally just checked the scholarship content type, so i didnt even see those. I will take another pass. Thanks!

**Comment by GaryRidgway** [comment]
@bspeare this should be fixed now, try again?

**Review by bspeare — APPROVED** [review]
The changes look good! Was able to bulk update as a webmaster/publisher but not as editor.

**Pull request merged**
