### PR TITLE
[UIDS] Storybook 8 update

### LINKED ISSUE #6584: `uids_base` UIDS3/4 cleanup
# Story

As a developer, I can import UIDS4 base components for all `uids_base` components:

- _variables.scss";
- _utilities.scss";
- headings.scss";
- headline.scss";
- typography.scss;
- lists.scss
- Use https://github.com/uiowa/uids/tree/4.x/src/assets/scss as the complete list of files. 

After working on https://github.com/uiowa/uiowa/pull/6576/files, there is a number of components pulling in UIDS3 and UIDS4 components.  We might even be loading duplicate files from each library in some cases. 

# Proposed solution

```[tasklist]
### Tasks
- [ ] Audit usages of @import "uids3/ in uids_base and see if any of them can be replaced using the files in https://github.com/uiowa/uids/tree/4.x/src/assets/scss.
- [ ] Like we are doing in, https://github.com/uiowa/uiowa/pull/6654,  audit UIDS3 components that will not be moved to 4 and move them into uids_base
- [ ] Pull out V2 specific mixins from https://github.com/uiowa/uids/blob/4.x/src/assets/scss/_utilities.scss#L209-L317 and move them to uids_base for use in sitenow.scss.
- [ ] Revert the work done in [Bug] V2 card titles on dark backgrounds #6581.
- [ ] Change sitenow.scss to sitenow_v2.scss for clarity.
```

### LINKED ISSUE #8161: Roboto bold+italic webfont variant is not being loaded
# Problem
When combining bold and italics in CKEditor, we're not seeing the Roboto webfont rendered correctly.

What renders (note the title "Front in Microbiology"):
Screenshot 2024-10-23 at 8 40 30 AM

What we should see:
Screenshot 2024-10-23 at 8 40 40 AM

It's a little easier to see the difference between the browser's "faux italics" vs the real thing when it's animated:

https://github.com/user-attachments/assets/8fe53b08-ea2c-40b8-afc9-571d38f433aa

# Steps to reproduce
Combine bold + italics in a content area, block, etc.

# Proposed solution
Ensure the Google Web Font contains the proper italic/bold weight, e.g.:

What we're currently using:
https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400&display=swap

Potential fixed version (would need review):
https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap

Alternatively, in the future perhaps consider self hosting the fonts, since this is encouraged more these days.

### PR DESCRIPTION
**Pull request by bspeare**
Relates to https://github.com/uiowa/uids/pull/938. 
Resolves https://github.com/uiowa/uiowa/issues/8161. 
Resolves https://github.com/uiowa/uiowa/issues/6584. 

- This pr moves us off of `node-sass` to use `sass`.  `node-sass` has been deprecated for years and `sass` is the current version.  

# How to test
- Review https://github.com/uiowa/uids/pull/942. 
- This pr moves us off of `node-sass` to use `sass`. 
- Review files changed. 

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli
```
- Confirm workspace(s) JS/CSS is being generated correctly by clicking through the relevant parts of each site
  - uiowa_alerts es6 compilation for example.
- Confirm all the `uids_base` changes by clicking through the sandbox site and checking for regressions. Check major components and Check nested background colors, etc. 
- Confirm all of `uids3` have been removed.
- Double check that sitenow v2 CSS is working correctly.  Check nested background colors, etc. 
- Test for https://github.com/uiowa/uiowa/issues/8161.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
I am curious if https://github.com/uiowa/uiowa/pull/8199 should merge into this as I am now relying on storybook 8 and have temporarily moved the gulpfile.js changes from this into it.

**Comment by bspeare** [comment]
@joewhitsitt good question.   It appears the CSS is compiling fine in https://github.com/uiowa/uiowa/pull/8199 so I don't think you need to merge into this.  Just make sure that part of the testing instructions in your pr relate to the switch to `sass` from `node-sass` for uids_base only.

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
Making a list of things to check:
- Student Life Topic Collections
- UIowa Alerts
- UIowa Profiles
- Admissions
- Grad Admissions
- Housing
- HR
- IGHN
- Pharmacy
- UI Press
- UIDS Base

**Comment by pyrello** [comment]
Discussed with @bspeare in Slack that it doesn't make sense to me that we are moving components from UIDS 3 to UIDS Base now so that we can move them to UIDS 4 later. He agreed and is going to move components to UIDS 4.

**Comment by bspeare** [comment]
Added https://github.com/uiowa/uiowa/issues/8238 to deal with the removal of `--silence-deprecation=import` in a future issue.

**Review by pyrello — APPROVED** [review]
I believe this is all good to go. I've checked file generation, did some file comparison spot checking, and clicked through a number of pages on the sandbox side-by-side between prod and my local and didn't see anything that looked different.

**Comment by bspeare** [comment]
Thanks @pyrello!

**Pull request merged**
