### PR TITLE
updated config to support ddev 1.23.0

### PR DESCRIPTION
**Pull request by joewhitsitt**
# How to test

- `git checkout ddev_upgrade`
- `brew upgrade ddev`
- `ddev delete images --all`

# Few notes:

- I think the python stuff is necessary for the Debian web server.
- default port makes it easier for database apps to connect like phpstorm
- switch to mysql which aligns more with Acquia
- ~php 8.2 in preparation for our future~

### CODE REVIEW

**Comment by joewhitsitt** [comment]
WARNING: Because of the database change, this will wipe out your local dbs and start fresh.

**Comment by pyrello** [comment]
> php 8.2 in preparation for our future

I'm not seeing that the PHP version is being changed in this except in a commented out line which is essentially documentation on settings we could be using.

**Comment by pyrello** [comment]
Honestly, I'd be good with entirely removing all the commented out stuff at the bottom of the config.yaml file. It makes it harder to see at a glance what is actually modified.

**Comment by joewhitsitt** [comment]
Since this is auto generated each time `ddev config --update` is run, I think we should leave the commented stuff in to better understand new options, etc.

**Review by pyrello — APPROVED** [review]
Reviewed code changes and ran through instructions. Not sure how to test it, honestly.

**Pull request merged**
