### PR TITLE
add media_entity_file_replace, delete old orphaned files

### LINKED ISSUE #883: Add media_entity_file_replace to provide file replace functionality
## Problem
Unlike in D7 with file entity I believe, there is currently not a way to replace an existing file. There is a core issue out there https://www.drupal.org/project/drupal/issues/2648816.

## Proposed Solution
Until then this module solves the issue and is written and used by Princeton University ([bkosborne](https://www.drupal.org/u/bkosborne)).

https://www.drupal.org/project/media_entity_file_replace

### LINKED ISSUE #1867: Files aren't being deleted
## Problem

Media deletes a file, but it doesn't actually get removed from the server. All files are currently being marked as permanent and this doesn't change even if the file usage is 0. A change in 8.4 made this behavior the default to prevent unwanted data loss. 

`make_unused_managed_files_temporary`

Additionally, revisions are also keeping the file_usage count up.

https://www.drupal.org/node/2891902

The result is that files are still available on a server and there is nothing a site owner can do to remove the file. This can be problematic if the file contains outdated/sensitive information.

Our current configuration is set to delete temporary files after 6 hours next cron, but because of the variable, that is not happening.

This also affects our hosting storage.

## Proposed Solution

- [x] Switch the variable introduced in 8.4 to TRUE. "This will work for files going forward."
- [x] Adopt media replace functionality which overwrites files reducing the amount of orphaned files, duplicates. #883 
- [x] Run an update hook to mark existing files with 0 usage (file_usage) and flag them for deletion (file_managed status = 0). https://www.drupal.org/node/2891902#comment-13350023
- [x] Lower time till expire

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #883 
Resolves #1867 

- [x] Create follow-up documentation regarding replace functionality, known issues - https://github.com/uiowa/uiowa/issues/2180
- [x] Get stats on how much disk space is cleaned up after the update hook runs (BEFORE: 69% PROD, 75% DEV/STAGE)

## To Test Media Entity File Replace

Try using the replace field on existing media entities (audio, file, image). If the media was referenced on content, that content should get the updated file/version.

File metadata (dimensions, size, etc.) might not be updated, because Media doesn't really know anything has changed. https://www.drupal.org/project/media_entity_file_replace/issues/3109553 which leads to core issues

## To Test Orphan File Deletion Update Hook

Pull down an old existing site with a lot of files. The update hook should mark status = 0 for at least a couple files in file_managed table. Run cron. Those entries should go away and your files directory should not have those files.

On a v2 site since the entity embed icon was probably deleted from file_managed, open up a WYSIWYG and make sure an icon loads. It should be recreated in your local directory but not in the files_managed table.

If you have a site that relied on non-Media reference fields, make sure you aren't getting unintended consequences with those fields (e.g. uiowa_footer lockups, brand site lockups, dcv files)

### CODE REVIEW

**Comment by pyrello** [comment]
What is a good example of an existing site with lots of files?

**Comment by joewhitsitt** [comment]
hr, brand, ap-purchasing.fo

**Comment by pyrello** [comment]
In testing this on a local version of uiowa.edu, I got the following error:
```
The website encountered an unexpected error. Please try again later.

Drupal\Core\File\Exception\DirectoryNotReadyException: The specified file 'temporary://2018_10_23-Fall-Boom-Truck-1433_1.jpg' could not be copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. in Drupal\Core\File\FileSystem->prepareDestination() (line 488 of core/lib/Drupal/Core/File/FileSystem.php).
Drupal\Core\File\FileSystem->copy('temporary://2018_10_23-Fall-Boom-Truck-1433_1.jpg', 'public://2020-04/underwater-research-test.jpg', 1) (Line: 234)
_media_entity_file_replace_submit(Array, Object)
call_user_func_array('_media_entity_file_replace_submit', Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('media_image_edit_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object) (Line: 39)
Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```
@joewhitsitt I'm wondering if this is related to what you mentioned in our meeting earlier about the way that Collegiate sites are configured?

**Comment by joewhitsitt** [comment]
Ooh, I think I know this issue. It is because the file doesn't exist locally yet. You need to either sync files down or stage file proxy the file before attempting to replace.

https://www.drupal.org/project/media_entity_file_replace/issues/3130452

**Comment by pyrello** [comment]
I'll try syncing files. I already have stage file proxy set up for that site.

**Comment by pyrello** [comment]
That worked. Thanks, @joewhitsitt!

**Comment by pyrello** [comment]
I have tested:
* Replacing an image on uiowa.edu. Also ran cron and checked a few pages.
* Ran cron on hr.uiowa.edu and checked some pages.
* Ran cron on cogscilang.grad.uiowa.edu and checked the homepage.

I feel like I don't quite have a sense of how to go about testing this rigorously, so I'm not marking as approved yet. However, I didn't encounter any issues in my testing.

**Comment by richardbporter** [comment]
>Get stats on how much disk space is cleaned up after the update hook runs

Files aren't deleted immediately unless we run cron at the end of the update hook.

**Comment by richardbporter** [comment]
I have tested the update hook on multiple sites and noticed 10-20 files being marked as temporary on average. None that I spot-checked had a row in file_usage. Seems to work as intended. 👍

**Comment by richardbporter** [comment]
>unless we run cron at the end of the update hook.

Can't do that due to #1782. We'll just have to wait until the next day or so.

**Comment by richardbporter** [comment]
Spot-checked a few more files marked as temp and was unable to find them on the media overview page, as expected.

One thing I'm confused about is there are still files in the media overview with no usage.
image

**Comment by richardbporter** [comment]
Replace seems to work as expected and does not allow replacing with a different extension.

**Comment by joewhitsitt** [comment]
The file_usage table count only pertains to the amount of times a file is "used" by media or other.
Media usage UI count is where that File/Media combination is being used within certain tracked content (fields, wysiwyg).

This PR does not remove media files with no usage. That would be bad. Someone uploads a file to their site, doesn't use it in a page right away, cron runs, it would get deleted. We don't want that.

This PR finishes cleaning up what should have been cleaned up before we set the flag. Before when an editor deleted a media file, they only deleted the media part of that combination. The actual file and the entry in file_managed still existed. The editor thought it was gone, but it was hanging around as an unmanaged file inside the file_managed table and server directory.

**Review by richardbporter — APPROVED** [review]
I think is good to go. I noticed on one site I had to run cron twice. Not sure if that was gremlins or just how it might work in prod. Maybe its batched.

**Pull request merged**
