### PR TITLE
Person Additions

### LINKED ISSUE #2205: Person Content Type Additions/Updates
- [x] Make title/position field allow multiples (Professor of ..., chair of ...)
- [x] Add a multi valued link field with required title for person to list websites (link to cv, google scholar, pubmed, etc)
- [x] Add multi valued field for Education
- [x] Add multi valued field for Research Interests
- [ ] Styling updates

Here is a link to a profile page of a person to give an idea of what type of content will lieve in the Education and Research Interest fields.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #2205 

- Set position/title field to unlimited.
- Pulled field_person_website from person_extended feature split
- Created multi text long for field_person_education
- Pulled research areas field and taxonomy from person_extended feature split
- Updated permissions across splits to catch up and prepare.
- Changed education and research areas to render as unordered lists.

## To Test

- No regressions to sites using person_extended. (e.g. immuno.grad)
- The above person functionality, including the ability to interact with the research areas taxonomy as an editor/publisher/webmaster is working and rendering to the person full view mode.
- HR will have the fields and the content will render, but no formatting/styling has been done.

### CODE REVIEW

**Comment by dnkemper** [comment]
Going to test this!

**Comment by mark-bennett-uiowa** [comment]
Tested. I really like the additions thus far. A few minor thoughts for feedback:
**(1) Is the Education field supposed to be a text area vs a simple text field?**
Screen Shot 2020-10-07 at 1 24 09 AM

**(2) Could we adjust the template so that the headings are actual headings rather than styled divs?**
**Current:**
Screen Shot 2020-10-07 at 1 28 43 AM
**Adjusting the element to an h2 instead:**
Screen Shot 2020-10-07 at 1 31 18 AM

**(3) Long titles wrap a little funny, and the multiple field headings could use a tweak:**
Screen Shot 2020-10-07 at 1 25 25 AM

**Comment by joewhitsitt** [comment]
For the education field, I wasn't sure how long some of these could get. Instead of risking topping out at 255 characters, I went text plain long with a smaller input.

No real attention has been given to the look and feel beyond matching the bulleted list from the issue example to provide separation. Open to ideas. I think I heard the design meeting is packed today, but it could be a discussion item. Keep in mind websites and research areas are already out there in the wild with the person_extended split

**Comment by joewhitsitt** [comment]
Sounds like bigger person design work will be done in the future as we add more fields, etc.. For now to push this one to done, I am willing to reduce the font size of the person position/titles and add a h5 class (same as card) to those main content field labels (research areas and education). Does that sound good to everyone?

**Comment by mark-bennett-uiowa** [comment]
@joewhitsitt Sounds good to me to push this PR to done. I look forward to working on this alot once the group decides what the extent of this project actually is.

**Comment by joewhitsitt** [comment]
Screen Shot 2020-10-08 at 5 10 41 PM

h5 classes on the main content field labels. I kept the h5 on the position title but separated the field items. I think it looks fine for now at full browser display.

**Comment by cory-skeers** [comment]
Haven't tested for regressions on a site currently using the person_extended, but on a fresh install the field additions/alterations are working well, as are the permissions.

I'll try to check for regressions shortly, but if anyone else has had a chance to already, or can get to that section, it has my blessing to be approved and merged 👍

**Comment by dnkemper** [comment]
@cory-skeers I can look into it! You rock!

**Review by dnkemper — APPROVED** [review]
Looked at immuno.grad.uiowa.edu and thanks for clarifying things for me haha! Good job, Joe!

**Review by pyrello — APPROVED** [review]
Reviewed, tested against immuno.grad.uiowa.edu. Nice updates!

**Pull request merged**
