### PR TITLE
Add person schema to profile pages.

### LINKED ISSUE #5093: Implement structured JSON-LD for directory profile people
The Directory profiles team has an endpoint that includes structured JSON-LD `{{host}}/api/people/{{slug}}/structured?api-key={{dentistryKey}}`

Place in script element with type attribute `application/ld+json`

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #5093.

While working on this, I realized that profiles functionality does not work in IE11 at all. Therefore, I used JS features like fetch and backticks which are not supported in IE11. Somewhat related: #4036

# How to test

- Pull down education.uiowa.edu.
- Go to the profiles directory config page.
- [Change the API key to this one.](https://iowaweb.slack.com/archives/C0164FNN1PV/p1647377146635319?thread_ts=1647377129.307609&cid=C0164FNN1PV)
- Navigate to https://education.uiowa.ddev.site/directory.
- Check that there is a `meta` element in the `head` element that has `name="description"` that describes the directory.
- Click on an individual person.
- Check that there is a `meta` element in the `head` element that has `name="description"` that describes that person.
- Check that there is a canonical meta element set.
- Check that there is a script tag in the head that has type `application/ld+json` and contains the appropriate person schema markup.
- Go back to the directory using the breadcrumbs. 
- Make sure the person-specific metadata is not set.
- Go back to a person. Do a full page reload and ensure metadata again.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
All the test steps worked, however, the I am wondering if something is being truncated which results in invalid markup because it isn't closed properly.
Screen Shot 2022-04-19 at 12 12 33 PM

https://education.uiowa.ddev.site/directory/john-achrazoglou
https://profiles.uiowa.edu/api/people/john-achrazoglou/structured

Screen Shot 2022-04-19 at 12 17 41 PM

**Comment by richardbporter** [comment]
Good catch, thanks. Taking a look.

**Comment by richardbporter** [comment]
AFAIK, this is just certain browser inspectors limiting the number of characters. The text is not truncated in the API response or anywhere else. If you copy the element to a text editor, you should see the full output. Frustratingly, I can't figure out to just display it all in Chrome. It might be because it pretty-prints JSON. I can see the full value in Firefox.

**Review by joewhitsitt — APPROVED** [review]

**Comment by mjoneill** [comment]
In case it's ever useful - schema validators and linters:
* https://validator.schema.org
* https://search.google.com/test/rich-results
* https://webmaster.yandex.com/tools/microtest/?status=ok&am_social=false
* http://linter.structured-data.org

**Comment by richardbporter** [comment]
> In case it's ever useful - schema validators and linters:
> 
> * https://validator.schema.org
> * https://search.google.com/test/rich-results
> * https://webmaster.yandex.com/tools/microtest/?status=ok&am_social=false
> * http://linter.structured-data.org

Thanks @mjoneill. I ran the schema through the first validator and it reported the following two errors:
```
The property selectedPublications is not recognized by the schema (e.g. schema.org) for an object of type Person.
The property selectedPresentations is not recognized by the schema (e.g. schema.org) for an object of type Person.
```

If those need to be removed/altered, thats something that AIS would have to do.

**Comment by mjoneill** [comment]
@richardbporter Yep, I should have mentioned that.  It's a known error and I’m ok with it. 

We have content in our people directory that’s not typically part of the Person schema type.  

It's probably worth me checking and making sure there's not a better supported way of handling that now, as this approach was current as of several years ago...but I wouldn't pause anything for that.

**Pull request merged**
