### PR TITLE
Temporary hotfix for entity_print + dompdf

### PR DESCRIPTION
**Pull request by pyrello**
# How to test

- `ddev blt ds --site admissions`
- `ddev drush @admissions.local uli kiosk`
- Spot check AOS PDFs for consistency.

### CODE REVIEW

**Comment by pyrello** [comment]
I guess how I have this setup isn't going to work because Drupal expects keys or authentication from an issue fork branch.

**Comment by pyrello** [comment]
I thought I had found a way around Travis not being able to get this, but it seems like we need SSH keys set up that would allow Travis to clone the repo. There are existing SSH keys, but they are already saved and encoded in Travis. Rick set this up, so I'm not sure if we passed the actual keys on to anyone or if they were set up and then discarded because they were never meant to do anything but provide the connection for Github.

**Comment by bspeare** [comment]
Tested out the PDFs and they look the same.

**Review by bspeare — APPROVED** [review]
Tested and PDFs look the same.

**Pull request merged**
