### PR TITLE
Feature: fix for PDF style regression

### LINKED ISSUE #5184: Admissions PDF title wrap issue
https://admissions.uiowa.edu/print/pdf/node/3416
Screen Shot 2022-04-27 at 3 12 59 PM

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5184. 

# How to test

- `blt frontend`
- `ddev blt ds --site=admissions.uiowa.edu`
- Test PDF on https://admissions.uiowa.ddev.site/areas-of-study/print-links, scroll to the bottom and test the "Tests" section as well. 
- Test long PDF like https://admissions.uiowa.ddev.site/print/pdf/node/3416 and short titles like https://admissions.uiowa.ddev.site/print/pdf/node/2816. 
- Test multiple batched PDF on https://admissions.uiowa.ddev.site/kiosk.

### CODE REVIEW

**Review by richardbporter — COMMENTED** [review]
Looks like the AoS reported in the issue is fixed but I'm still seeing the problem on others with long titles. For example:

- https://admissions.uiowa.ddev.site/print/pdf/node/3611
- https://admissions.uiowa.ddev.site/print/pdf/node/2771
- https://admissions.uiowa.ddev.site/print/pdf/node/3856

Attached a screenshot of one. Ran `blt frontend` and cache cleared multiple times. 

None of the basic pages seem to have this problem.

Screen Shot 2022-05-02 at 9 56 04 AM

**Comment by bspeare** [comment]
@richardbporter weird! They are showing up like this for me:

Screen Shot 2022-05-02 at 10 02 02 AM

**Comment by richardbporter** [comment]
Let me try another browser and/or clearing history.

**Comment by bspeare** [comment]
I re-synced the site and tried a few different browsers and still not seeing the issue.

**Review by richardbporter — APPROVED** [review]
Yea I see it now. Looks good. 

Probably user error. :)

**Pull request merged**
