### PR TITLE
Add exposed filters to views block display

### LINKED ISSUE #3804: Add exposed filters to views block display
# Story

As a content editor, I want to be able to expose filters on my view blocks.

# Proposed solution

- [x] ~Help get MR at https://www.drupal.org/project/ctools/issues/2657060 to a fully working state.~ MR got merged and is part of the more recent version of `ctools`.
- [ ] Update to most recent version of `ctools` module.
- [x] Refactor code that transform the people type selector based on updates.
- [x] Add patch to account for issue with multiple exposed forms in blocks for the same views display, possibly the one at this issue: https://www.drupal.org/project/drupal/issues/3163299
- [x] Account for pager and offset options showing up in exposed filter form.
- [ ] Refactor code to work with updated version of `ctools` module.
- [ ] Update hook to convert existing configuration to the new format.

<details>
<summary>Original proposed solution</summary>
Modify the `Drupal\layout_builder_custom\Plugin\Display\ListBlock` class in the following ways:
- For each filter that can be set on the block settings form, add a checkbox to the form to allow the user to expose the filter. Name the checkboxes fields `$filter_id . '_expose`.
- Add `'#states'` to each filter field to disable the field if the corresponding checkbox is checked.
- Adjust the logic in the `blockSubmit()` method to check for an instances where the above fields are set to TRUE and set a new option value on the block called `expose_form` to TRUE if any of them are. Here is a quick example I came up with:
  ```
  $expose_form = FALSE;
  $exposed_inputs = $form_state->getValue([
    'override',
    'exposed_filters',
  ]);
  $exposed_filter_values = [];
  foreach ($exposed_inputs as $input) {
    // if input ends with _expose, $expose_form = TRUE;
    // else add to $input to $exposed_filter_values.
  }
  $block->setConfigurationValue('exposed_filter_values', $exposed_filter_values);
  $block->setConfigurationValue('expose_form', $expose_form);
  ```
- In the `preBlockBuild()` method, check the `expose_form` configuration value from the block and set an option on the display handler (`$this->view->display_handler->setOption('expose_form', TRUE)`) if this value is set to TRUE.
- Adjust the `displaysExposed()` method to check the display handler option and return `TRUE` if any filters are exposed.
- An update hook will be need to update all `layout_builder__layout` field instances to add the `expose_form` default value of FALSE to existing block configurations. This is a serialized field and will need to be deserialized to update it, then re-serialized to store it. There are several examples of this in previous update hook. Just ask @cory-skeers if you have any questions :)

**OR**

Alter the SiteNow People module to allow for displaying individual pages for people types as such:
- Change the configuration settings to allow for showing all people (the current option) and checkboxes for each person type to display a similar page.
- Adjust all the settings to be options for each possible person listing.
- Adjust the custom code that handles saving configuration and display the page to handle multiple pages.
</details>

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #3804 

# How to test

* Check that this doesn't break v2 person paragraph functionality. Test that it doesn't affect any existing view blocks with exposed filters.

## Stories
- As a non-administrator editing a people block, I am not able to filter by person type status.
- As an administrator, when I select a person type, the person type status options update to reflect on the corresponding options.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Update to current state for anyone who may jump in on this: Exposing filters functionally works. Could use some work on how the filter fields work (eg Person Type is a text field, not select list).

Main issue: The filters don't function. Hitting "Apply" appears to work, but the results do not change. May be related to https://www.drupal.org/project/drupal/issues/2605218 and any work that went into getting around that.

**Comment by joewhitsitt** [comment]
taking a look

**Comment by joewhitsitt** [comment]
oops. regression to getting the person type filter showing the options... duplicate filter on settings tray
Screen Shot 2021-07-21 at 2 12 26 PM

**Comment by cory-skeers** [comment]
Update re: the AJAX issue--it appears the call gets made, but the display doesn't update. There are no console errors, but choosing an option that doesn't have any results (Research Areas is a good one for testing on sandbox) and refreshing the page will display a "no matches" Drupal message.

**Comment by cory-skeers** [comment]
Also a note to remember, if anything needs to be updated in code: AJAX reloads do trigger `elementPreRender`, but not `preBlockBuild`.

**Comment by cory-skeers** [comment]
Followed the ajax query through, and it is being formed correctly and returning correct results. So it does seem to be narrowed down to the display not updating with the returned results.

**Comment by cory-skeers** [comment]
Apparently `preBlockBuild` is supposed to fire on AJAX reloads, and I'd had something going on where it wasn't.

Removed lines in that method that set exposed filters to match config values, which fixes the AJAX loads, but may have broken functionality elsewhere. Need to check on that.

**Comment by cory-skeers** [comment]
To do: Update Person Type field on form to operate as a select list.

**Comment by cory-skeers** [comment]
Person type and person type status fields are working as exposed forms; research areas and tags are not, and exposing them leads to "no results."

**Comment by cory-skeers** [comment]
So, the Research Areas and/or Tags exposed filter fields seem to work properly if they are used along with either or both the Person Type and Person Type Status exposed filters. But they don't work on their own. "Don't work" here means returning no results regardless of the filter selections.

e.g. Exposing Research and Person Type will lead to a functioning filter form; Exposing only Research will not; Exposing only Person Type will.

There is currently extra stuff going on with Research/Tags to turn them into single select dropdowns when exposed, but removing this and leaving the multi autocomplete has the same issue.

**Comment by joewhitsitt** [comment]
Taking another poke-see

**Comment by joewhitsitt** [comment]
While trying to figure out:

>But they don't work on their own. "Don't work" here means returning no results regardless of the filter selections.

I set research on the block config to "history" and then made the filter exposed which on save, caused this illegal choice error. digging more. might be related?

Screen Shot 2021-07-27 at 11 15 32 AM

**Comment by joewhitsitt** [comment]
Sorry, I am not getting anywhere with this. Just noticing things.

This is what research looks like when the block sends the filter to the view:
Screen Shot 2021-07-27 at 11 33 00 AM

This is what research looks like when the filter is exposed and submitted:
Screen Shot 2021-07-27 at 11 35 59 AM

**Comment by pyrello** [comment]
I'm taking a look at this.

**Comment by pyrello** [comment]
A couple things going on here:
- When exposing the operator for an exposed filter, the two items are built with a wrapper around them and our code mostly just assumes that the filters will all be direct children of `$form['override']['exposed_filters']`.
- Filters are stored early on in the process using their Views-generated ID (e.g. `field_tags_target_id`) and when the exposed filter ID is customized (e.g. `tags`). Our code doesn't fully account for that. I started working on this problem in #3815, but I think it will require a more significant refactor now that we are exposing filters.

I started working on some changes to account for these items, but more work needs to be done to fully account for the above conditions.

**Comment by pyrello** [comment]
Changing the filter names was a little disruptive as we had some bunch of instances where the `type` filter was hard-coded in form override code in `sitenow_people`. I attempted to fix that, but it's not totally working yet. When a selection is made for person type, it is not populating the corresponding option in person type status.

**Comment by cory-skeers** [comment]
> I set research on the block config to "history" and then made the filter exposed which on save, caused this illegal choice error. digging more. might be related?

Could be! I'd be interested to see if this still happens if you set research on the block config, and then make both the research and person filter exposed. If it doesn't happen there, it's likely related. If it does, it may be a separate issue (might need to remove values in `blockSubmit` in addition to disabling the field prior?). I don't have it pulled down currently to test, but can try later.

When the exposed filter is sent to the view, the data appears the same between the two scenarios of only the research filter exposed and both the research and person type filters exposed--in the former, no results are returned, but in the latter the correct results are returned using seemingly the same data structure.

**Comment by cory-skeers** [comment]
Haven't dug into the proposed solutions in this issue (https://www.drupal.org/project/drupal/issues/2842525), but getting the Person Type Status exposed filter to populate with only the correct values given a chosen Person Type isn't as straightforward as adding an `#ajax` attribute to the exposed filter form, as I'd tried.

**Comment by pyrello** [comment]
When building out the configure filter functionality, I used the patch at this issue as a little bit of a guide: https://www.drupal.org/project/ctools/issues/2657060

However, at the time we were not trying to expose filters, so I didn't go all in for their solution as it seemed overly complex. I'm going to revisit this to see what there is to learn from it.

**Comment by pyrello** [comment]
> Haven't dug into the proposed solutions in this issue (https://www.drupal.org/project/drupal/issues/2842525), but getting the Person Type Status exposed filter to populate with only the correct values given a chosen Person Type isn't as straightforward as adding an `#ajax` attribute to the exposed filter form, as I'd tried.

I think that we may want to consider using custom JS here instead of continuing to go the AJAX form route. We could load JS that is triggered by changes to the person type field and updates the person type status field to only allow the appropriate options. If we did this, we could completely bypass this problem, I believe.

**Comment by pyrello** [comment]
Note to attempt to address #3661 as part of this work.

**Comment by pyrello** [comment]
As part of the refactor on this, some of the work is now going on in this MR for the `ctools` module: https://git.drupalcode.org/project/ctools/-/merge_requests/4/diffs

**Comment by pyrello** [comment]
As I noted in our huddle yesterday, there seems to be an inconsistency in the way that views expects the filter data for entity references to be stored vs. how a form builder expects it to be stored. 

Views expects something like:
```php
$handler->value = [
  0 =>  16,
];
```

While FormBuilder expects something like:
```php
$handler->value = [
  0 => [
    'target_id' => 16,
  ],
];
```
If FormBuilder doesn't get the above format, then there is a fatal error when the values are passed into `EntityAutocomplete::valueCallback()` because it is passed to an array_map function that needs the above format to work.

In the current version of the patch we are using for Ctools (https://www.drupal.org/project/ctools/issues/2657060), I have ensured that the filter data for entity references gets stored in the block configuration in the second format. I was in the process of trying to understand the implications of the above information when I ran out of time to work on this.

Also, per https://www.drupal.org/project/ctools/issues/2657060#comment-10824250, I added patches from the following two issues:
* https://www.drupal.org/project/drupal/issues/2653938
* https://www.drupal.org/project/drupal/issues/2662978

I reviewed the patches and the second one at least makes sense to me logically. However, after adding those patches, the stored filter values from the block stopped working on the view block. So there may be something there to investigate.

**Comment by pyrello** [comment]
I also add this issue for Drupal core, which would make all the checks we are doing in `ctools_views` for a filter's expose identifier easier: https://www.drupal.org/project/drupal/issues/3227124

**Comment by pyrello** [comment]
A guide to working with the ctools MR that is part of this issue:

Note: I found it helpful to open a second terminal window to be able to run commands in the `ctools` directory while still being able to run `drush` and `blt` commands in the root directory.

To check out the MR and make changes to it:
```
cd docroot/modules/contrib
rm -rf ./ctools
git clone https://git.drupalcode.org/project/ctools.git
cd ctools
git remote add ctools-2657060 git@git.drupal.org:issue/ctools-2657060.git
git fetch ctools-2657060
git checkout -b '2657060-add-configure-filter' --track ctools-2657060/'2657060-add-configure-filter'
```
Make code changes, test, debug, and commit. Once you are satisfied that the changes should be added to the MR, `git push`.

To update the patch (for being able to share progress with other developers on the team):
- Make note of what the next comment number will be on https://www.drupal.org/project/ctools/issues/2657060. It will say the comment number after "Add new comment #" before the form to add a new comment.
- Make note of the last comment number where a patch was added.
- Download the last patch to the `ctools` module directory.
```
git diff 8.x-3.x > 2657060-[next-comment-number].patch
interdiff 2657060-[last-comment-number].patch 2657060-[next-comment-number].patch > interdiff_[last-comment-number]-[next-comment-number].txt
```
- Upload the patch and the interdiff and add a new comment.
- Update `composer.json` to point to the most recent patch and run `composer update --lock`
- Commit and push changes.

# References
- https://www.drupal.org/project/ctools/git-instructions
- https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/creating-an-interdiff#s-create-interdiff-using-patchutils
- https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/making-a-patch#s-make-the-patch

**Comment by richardbporter** [comment]
I looked at this but I think I'll need help understanding in greater detail.

**Comment by richardbporter** [comment]
Initial (potential) steps to get ctools tests running in uiowa app:

### Set up ctools or another project using source repo.
```
rm -rf docroot/modules/contrib/ctools
composer install --prefer-source
cd docroot/modules/contrib/ctools
```
Follow Git instructions on issue for setting up another remote within that project directory.

### Run test
Example
``` 
./vendor/bin/phpunit -c docroot/core docroot/modules/contrib/ctools/modules/ctools_views/tests/
```

If xDebug gets stuck on `Standard input code`, configure PHPStorm Debug servers to not break at first line.

The browser output URLs should work and are very useful.

#### Initial test debugging
```
POST request to: https://local.drupal.uiowa.edu/admin/structure/block/add/views_block%3Actools_views_entity_test-block_filter_text/classy
The website encountered an unexpected error. Please try again later.

Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for block.block.views_block__ctools_views_entity_test_block_filter_text with the following errors: block.block.views_block__ctools_views_entity_test_block_filter_text:settings.exposed.filter-field_ctools_views_text_value missing schema, block.block.views_block__ctools_views_entity_test_block_filter_text:settings.exposed_raw missing schema in Drupal\Core\Config\Development\ConfigSchemaChecker->onConfigSave() (line 94 of core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php).
```

Setting `protected $strictConfigSchema = FALSE;` on `CToolsViewsEntityViewBlockTest` gets past this.

```
GET request to: https://local.drupal.uiowa.edu/admin/structure/block/list/classy?block-placement=views-block__ctools-views-entity-test-block-filter-text
The website encountered an unexpected error. Please try again later.

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "ctools.views.handlers.helper". in Drupal\Component\DependencyInjection\Container->get() (line 151 of core/lib/Drupal/Component/DependencyInjection/Container.php).
```
There is no dependency on ctools itself which is where the `ctools.views.handlers.helper` service gets loaded. Adding it to the `$modules` property of the test or as a dependency of `ctools_views` gets past this.

Thats as far as I got. I can add this info the d.o issue if you'd like, or if it gets me credit. :)

**Comment by richardbporter** [comment]
We might want to check BLT docs on testing in case we missed something on setting this up.

**Comment by richardbporter** [comment]
I think 78cc8aa needs to be reverted. I took a deeper dive into this in #4063 and think we should probably use BLT as a wrapper for running core/contrib tests within this project. I can successfully run ctools_views tests in #4063 using the method outlined in the tests/README on that branch: https://github.com/uiowa/uiowa/pull/4063/files#diff-dacac2ebf9792f0d23c0f922a744486ded01901957d5281290925acd89cf83acR21

**Comment by richardbporter** [comment]
Reverted. I updated the instructions in https://github.com/uiowa/uiowa/pull/3829#issuecomment-910490182 to use core's PHPUnit config. The top-level phpunit.xml.dist file should be used for our own application tests.

**Comment by pyrello** [comment]
Running tests for `ctools_views` locally to see why they are failing and fixing the issues is the next step on this.

**Comment by pyrello** [comment]
To trigger the fatal error that is forcing us to use both the `exposed` and `exposed_raw` filter config currently, follow these steps:
* `blt ds --site sandbox.uiowa.edu`
* `drush @sandbox.local uli node/1/layout`
* Add a people block in the section under the "Getting Started" heading. Set the exposed filter for Tags to "Mascot (16)". Save settings.
* In `Drupal\ctools_views\Plugin\Display\Block` (`docroot/modules/contrib/ctools/modules/ctools_views/src/Plugin/Display/Block.php`) on line 582 change
  ```php
  foreach ($config['exposed_raw'] as $key => $value) {
  ```
  to
  ```php
  foreach ($config['exposed'] as $key => $value) {
  ```
* Reload the page and you should see the error.

To the best of my knowledge, this is what we need to resolve to get rid of the `exposed_raw` config. The format of the values in `exposed` matches up with what Views is expecting (even though this is different than how these types of values are sometimes stored). This is primarily a problem with the `TaxonomyTermTid` filter (which is what is being used for the Tags filter), but we have to solve it in a generalized way by using filter plugin methods. It is not outside the realm of possibility to create a core patch to change something related to the `TaxonomyTermTid` filter if we can figure out how to make that work.

**Comment by pyrello** [comment]
The error that is generated by the above steps specifically happens in `Drupal\Core\Entity\Element\EntityAutocomplete::valueCallback()` because that function is expecting the format of the stored term IDs as:
```php
$input = [
  ['target_id' => 1],
  ['target_id' => 3],
  // etc.
];
```
Instead, it is stored as:
```php
$input = [
  0 => 1,
  1 => 3,
  // etc.
];
```
The error happens here: https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php#L126-128

However, when an exposed filter is shown on a Views page display this is not an issue so it seems like it should work here. Trying to figure out what we are doing different and correcting it is going to be part of the process here.

**Comment by pyrello** [comment]
# Some points of code comparison:
## Form generation
`Drupal\views\Form\ViewsExposedForm:buildForm()`:
https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/modules/views/src/Form/ViewsExposedForm.php#L69-157
`Drupal\ctools_views\Plugin\Display\Block::blockForm()`:
https://git.drupalcode.org/project/ctools/-/blob/51d9d152d63195bcdc5f952d6d3606c4e7a17413/modules/ctools_views/src/Plugin/Display/Block.php#L260-348

## Form validation
`Drupal\views\Form\ViewsExposedForm:validateForm()`: https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/modules/views/src/Form/ViewsExposedForm.php#L162-175
`Drupal\ctools_views\Plugin\Display\Block::blockValidate()`: https://git.drupalcode.org/project/ctools/-/blob/51d9d152d63195bcdc5f952d6d3606c4e7a17413/modules/ctools_views/src/Plugin/Display/Block.php#L403-436

**Comment by pyrello** [comment]
I think that all the relevant changes from #4479 have been moved over and therefore I am going to close this PR.

**Pull request closed without merging**
