### PR TITLE
connect.studentlife.uiowa.edu AD role mappings

### LINKED ISSUE #5702: AD role mappings connect.studentlife.uiowa.edu
As an owner of the intranet connect.studentlife.uiowa.edu, I would like to grant access to specific AD groups so that we do not have to manually control access.

Examples from other websites:
https://github.com/uiowa/uiowa/blob/main/config/sites/sitenow.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
https://github.com/uiowa/uiowa/blob/main/config/sites/brand.uiowa.edu/config_split.patch.uiowa_auth.settings.yml

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5702. 

# How to test
- Code review
- `ddev blt ds --site=connect.studentlife.uiowa.edu`
- `ddev drush @studentlifeconnect.local config:import --source ../config/sites/connect.studentlife.uiowa.edu --partial`
- `ddev drush @studentlifeconnect.local config-split:activate site`

### CODE REVIEW

**Comment by briand44** [comment]
I think `CN=Student-Services-Exception,OU=Departments,OU=Domain Groups,DC=iowa,DC=uiowa,DC=edu` needs removed still based on https://github.com/uiowa/uiowa/issues/5702#issuecomment-1287022282.

**Comment by bspeare** [comment]
Thanks for that clarification @briand44!

**Review by cory-skeers — APPROVED** [review]
Followed the testing instructions, and everything synced/activated without issue.

For the role mappings, I put both the updates here and the original spreadsheet (with the corrected exception from issue comments) into Excel with some string comparisons. Everything checked out as accurate 👍

**Comment by bspeare** [comment]
Thanks @cory-skeers!

**Pull request merged**
