### PR TITLE
Added adjustments to classrooms room layout

### LINKED ISSUE #6435: Classroom design changes
- Output building name on card as a link to the building page within the classrooms site. https://classrooms.prod.drupal.uiowa.edu/find-university-classroom
- rework section displaying all the features on an individual room - they don't love tech features being different and potentially long
- Make technology guide link more prominent on individual room
- Today's schedule - use Zilla?

# Proposed solution

### LINKED ISSUE #6437: Classroom Unit term page updates
Example unit page https://classrooms.prod.drupal.uiowa.edu/units/carver-college-medicine

>The College of Dentistry lists two schedulers. So I have two names and email addresses. Is there any way to have a “Alternative Scheduler” and a second “Email” field available?

- Add an alternate scheduler field
- Add an alternate email field
- An alternate phone field would be a nice to have as well.
- Update order of how fields are rendered
    - Link
    - Scheduler
    - Email
    - Phone
    - Alternative Scheduler
    - Email
    - Phone

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6437. 
Resolves https://github.com/uiowa/uiowa/issues/6435. 

# How to test

```
blt ds --site=classrooms.uiowa.edu
```
Verify that the checkboxes below are complete.  Some images are provided in the `<details>` below. 

- [x] Output building name on card as a link to the building page within the classrooms site. `/find-university-classroom`
   - Review code changes in `classrooms_core.module` file.  
- [x] Reworked section displaying all the features on an individual room 
- [x] Made technology guide link more prominent on individual room
- [x] Today's schedule - switched to Zilla.
- [x] Unit pages - https://classrooms.uiowa.ddev.site/units/carver-college-medicine
  - [x] Update order of how fields are rendered
      -  Link
      -  Scheduler
      -  Email
      -  Phone
      -  Alternative Scheduler
      -  Alternative Email
      -  Alternative Phone
      -  Description

<details>

This pr adjusts the classroom page layout from:

Screenshot 2023-05-09 at 3 04 19 PM

Screenshot 2023-05-09 at 3 03 17 PM

To:

Screenshot 2023-05-09 at 3 02 52 PM

Screenshot 2023-05-09 at 3 04 26 PM

</details>

### CODE REVIEW

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and all looks good.

I wondered about the spacing between and placement of the tech features/guide and the Additional Details now that they're both on the same background and don't have that natural separation. I don't think there needs to be a change, but wanted to note it since it did stand out to me.

**Comment by bspeare** [comment]
@joewhitsitt I added two additions since Cory reviewed this last week.   Do you mind looking at https://github.com/uiowa/uiowa/pull/6440/commits/dbcd5010e6ed317e3f03c3981d63e917c1082aed and let me know if you see any issues in moving the `building_link` to ClassroomsRoom.php?

**Comment by joewhitsitt** [comment]
Yeah, I can pull down and look at this

**Comment by joewhitsitt** [comment]
@bspeare I think this is fine. Like we have encountered before, i don't think the "weight" of adding building_link to meta before processing (L52) it is doing what you may want it to do. room name is showing up before on https://classrooms.uiowa.ddev.site/units/college-law

adding a '#weight' => -1, to building_link does seem to work.

**Comment by joewhitsitt** [comment]
Tested on https://classrooms.uiowa.ddev.site/units/college-law, https://classrooms.uiowa.ddev.site/find-university-classroom and added the programmed rooms views block to a page.

**Pull request merged**
