### PR TITLE
[Wellbeing] filters as checkboxes

### LINKED ISSUE #7497: Well Being Filters
# Story

As a Well Being site owner, I would like our audience, topic, and type filters to be exposed as a drop down list of checkboxes so that users can choose multiple terms for each to filter by.

# Proposed solution

```[tasklist]
### Tasks
- [ ] Set page list block filters to allow multiple and try to preprocess filters to use details and checkboxes like BEF does
- [ ] Use BEF styles https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/views/bef/view-bef.scss#L82
```

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves #7497.

# How to test

```
ddev blt frontend && ddev blt ds --site=wellbeing.uiowa.edu && ddev drush @wellbeing.local uli /well-being-resources-test
```
1. Confirm chosen library is working and you can select multiple items.  View the page logged in/out and confirm no visual changes.
2. Confirm reset button is added.
3. Confirm chosen still works on layout builder block styles.
4. Test anything else.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@bspeare keep in mind we might be using this for other backend form api selects besides off-canvas settings tray https://github.com/uiowa/uiowa/blob/main/docroot/profiles/custom/sitenow/sitenow.profile#L102

**Comment by bspeare** [comment]
@joewhitsitt yup, I haven't touched that separate library.  For some reason we are loading a duplicate version of the CSS for our layout builder forms.  ~I'll see if we could possibly drop that here.~

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
Looks good.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
