### PR TITLE
[Wellbeing] Remove display of new taxonomy terms

### PR DESCRIPTION
**Pull request by cory-skeers**
The new taxonomy terms (Audience, Topic, Type) ended up getting included in the page display.

It's been confirmed that these are not to be displayed, and should be for back-end use only.

# How to test

```
ddev blt ds --site=wellbeing.uiowa.edu && ddev drush @wellbeing.local uli node/add/page
```

Check for a clean sync and config import.
Add some terms (audience, topic, and type) and save the page
See that they are not displayed on the page

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Aren't we supposed to complete split `core.entity_view_display.node.*.default` or has there been progress there in terms of handling config diffs? Ping @pyrello

https://iowaweb.slack.com/archives/C0164FNN1PV/p1642689940252600 , https://github.com/uiowa/uiowa/issues/4452

**Comment by pyrello** [comment]
> Aren't we supposed to complete split `core.entity_view_display.node.*.default` or has there been progress there in terms of handling config diffs? Ping @pyrello
> 
> https://iowaweb.slack.com/archives/C0164FNN1PV/p1642689940252600 , #4452

If the difference doesn't affect the LB template, then its okay to partially split this config. If the LB template is being altered at all, then it has to be completely split.

**Comment by cory-skeers** [comment]
> Aren't we supposed to complete split `core.entity_view_display.node.*.default` or has there been progress there in terms of handling config diffs? Ping @pyrello
> 
> https://iowaweb.slack.com/archives/C0164FNN1PV/p1642689940252600 , #4452

In this case in particular, I think we can partial split. The actual layout display should be the same as core, but it needs the extra `hidden: field: true` for each of the 3 additional fields.

**Review by joewhitsitt — APPROVED** [review]
Thanks for chiming in. Based on that and pulling locally, this works as expected. Tried to re-export to trip things up and it was identical. As an editor I could rely on the default permissions and still edit in layout builder

**Pull request merged**
