### PR TITLE
Added json file extension

### LINKED ISSUE #3784: Grad - Investigate json export feed solution
# Motivation

To finally retire the D7 Grad site, we need to come up with a replacement for the following json export, which is currently in use on several Qualtrics forms: https://grad.prod.drupal.uiowa.edu/json/GradFellowProgramsV2.json

# Proposed solution

Add json extension to document media type.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3784 
# How to test

1. `git checkout json-media`
2. `blt ds --site=sandbox`
3. to be on safe side - can `drush @sandbox.local cim` & `drush @sandbox.local cr`
3. `drush @sandbox.local uli`
4. Go to https://sandbox.local.drupal.uiowa.edu/media/add/file and add a json file
5. make sure can link to existing json file you created
6. Also add a new json file to WYSWYG to make sure adding a new json file in Media Library works correctly as well

### CODE REVIEW

**Comment by dnkemper** [comment]
@pyrello Don't want to request review before you take a look and make sure this is okay/will satisfy the needs laid out in issue

**Comment by pyrello** [comment]
I can test this out in the morning. Thanks!

**Comment by dnkemper** [comment]
@pyrello marvelous! Thank you so much!

**Review by pyrello — APPROVED** [review]
Nice work, thanks!

**Comment by dnkemper** [comment]
Yay! Thank you so much @pyrello 🥳

**Pull request merged**
