### PR TITLE
[ 10.3 ] Update drupal to drupal 10.3

### LINKED ISSUE #7753: Update Drupal Core 10.3.x
https://www.drupal.org/project/drupal/releases/10.3.2

plus core-composer-scaffold

# Proposed solution

To check if all our dependencies are compatible with Drupal 10.3, run the following command:

```
ddev composer prohibits drupal/core 10.3
```

Once all dependencies that need to be upgraded to be compatible and can be upgraded ahead of time have been upgraded, we can run the following command:

```
ddev composer require drupal/core-recommended:^10.3 drupal/core-composer-scaffold:^10.3 --update-with-all-dependencies
```

If there are problems with the above command, it is also possible to update the version constraints for the above packages in composer.json and then run

```
ddev composer update --lock
```

```[tasklist]
### Tasks
- [x] Fix deprecations (only required, mark warnings for later issues.)
- [x] Update default config `ddev blt di --site=default && ddev drush @default.local cex`
- [x] Update config split config ⤵
- [x] - feature splits first `ddev blt uiowa:usplits:feature`
- [x] - Then site splits `ddev blt uiowa:usplits:site `
- [x] Review file changes to decide on necessary testing [Alan]
- [x] Review P2LB config updates to decide whether to keep or ignore them
- [ ] Fix tests (potentially not going to be needed) `ddev phpunit -c docroot/core/ --verbose --debug docroot/modules/custom/`
- [x] Fix PHPCS updates
```

```[tasklist]
### Updated patches to test
- [x] Responsive image: Go to https://sandbox.prod.drupal.uiowa.edu/small-and-medium-responsive-images and check the small image style and confirm that the fallback image sizes are `width="384" height="384" `
- [x] A patch, "Expose Layout Builder data to REST and JSON:API" was updated related to https://www.drupal.org/project/drupal/issues/2942975 This was introduced to provide layout builder flavored default content. To test, one should run a site install (it should be successful) and try exporting the default content again, there should be no major changes besides revision numbers and such. 
- [x] A patch, "ImageItem::getUploadValidators() should be the source of truth for validating uploaded images," was updated related to https://www.drupal.org/project/drupal/issues/3008292      This was introduced to enforce max image sizes. Media was skipping over it. To test, upload an image beyond our max image size. You should get the message it was sized down, but now inspect the original that was uploaded it should have actually been sized down.
- [x] A patch, "Support third party settings for components within a section," was updated related to https://www.drupal.org/project/drupal/issues/3015152      This was introduced to make our unique id field on blocks a reality and we have run with it since. To test, make sure you are still able to see/add/edit unique ids on our blocks.
- [x] Patch for "Breadcrumbs block within Layout Builder causes errors when moving blocks" or "Fix LB contextual links after dragging block to new section" https://www.drupal.org/project/drupal/issues/3160785 - Try editing https://sandbox.local.drupal.uiowa.edu/node/586/layout and move the block to a section above the section it's in and then move the block way below to the bottom region
- [x] Views Block Display skips preBlockBuild() call on ajax rebuild. Test list blocks with non-default LB style options and/or hidden fields and filters AND a pager to check that second "page" results match the expected block settings.
```

```[tasklist]
### Things to fix
- [x] Drupal messages no longer appear to be using alert component styles
- [x] Media library console error: `RuntimeException: linkit_media_library.opener.editor must be an instance of Drupal\media_library\MediaLibraryOpenerInterface in Drupal\media_library\OpenerResolver->get() (line 46 of /var/www/html/docroot/core/modules/media_library/src/OpenerResolver.php).` solved by https://www.drupal.org/project/linkit_media_library/issues/3461637
```
```[tasklist]
### Changes to check
- [x] Config now wants `true` or `false` instead of `1` or `0`. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-7c611824bf25aa3ec43edddc7bb3388146a5a74ec54b814a18887c0e3a2ca4fdL4-L8)) [Alan]
- [x] Config now wants `null` instead of an empty string. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-5f07830815dcda5db1ba1afcf7700bf5c47fcc9fa338451d974cc543d2df5d51L39-L45))
- [x] PHP no longer wants optional parameters in the middle of argument definitions. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-c881dcdf122b0b68cea8d3731d01e360d728de9449c69e293767cb93ffd75d4bL93-L99))
```

```[tasklist]
### Weird config to check
- [x] SPAA - sync and export the site config. Completely deletes config_split.patch.* and replaces with full split. This happens on main as well. Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] Wellbeing - views page list block is being exported instead of config_split patch.  Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] HR -  Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] config/default/editor.editor.* config changes
- [x] P2lb
- [x] sitenow_intranet, uiowa.edu siteimprove permission changes
- [x] Admissions events split changes
- [x] Admissions areas of study view: plugin_id: numeric -> plugin_id: entity_target_id
- [x] ITS config changes
- [x] ITS views.view.service_related_articles.yml: plugin_id: numeric -> plugin_id: entity_target_id
- [x] Warning: Undefined array key "type" in Drupal\field_ui\Form\ITS alert: https://its.uiowa.ddev.site/admin/structure/types/manage/alert/form-display - EntityDisplayFormBase->buildFieldRow() (line 362 of core/modules/field_ui/src/Form/EntityDisplayFormBase.php).  This happens in 10.2 as well.
- [x] What to do about https://www.drupal.org/node/3223395#s-layout-builder-expose-all-field-blocks?
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
closes #7753

# How to test

_To mimic the production environment for the configuration changes related to siteimprove, devel, etc._

In settings/local.settings.php of the local site:
```
$config['config_split.config_split.local']['status'] = FALSE;  
$config['config_split.config_split.prod']['status'] = TRUE;
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
The commit here https://github.com/uiowa/uiowa/pull/8133/commits/941a7bc65252bdb319b58eb29b6ec78a4629b50f indicates more config work probably as it relates to the feature and site splits unfortunately

**Comment by joewhitsitt** [comment]
@pyrello suggested looking at establishing a baseline list of deprecations instead of generating them one-by-one like I did yesterday: https://phpstan.org/user-guide/baseline

I'd like to look at a couple of these to see if they are worth fixing now and then try doing that.

UPDATE:

```
ddev exec vendor/bin/phpstan analyse \
  --level 7 \
  --configuration /var/www/html/phpstan.neon \
  --generate-baseline /var/www/html/phpstan-baseline.neon \
  /var/www/html/tests/ \
  /var/www/html/docroot/profiles/custom/ \
  /var/www/html/docroot/modules/custom/ \
  /var/www/html/docroot/themes/custom/ \
  /var/www/html/docroot/sites/

 1745/1745 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


                                                                  
 [WARNING] Baseline generated with 9120 errors.                   
           Some errors could not be put into baseline. Re-run     
           PHPStan with "-vv" and fix them.
```

**Comment by GaryRidgway** [comment]
Found [this nice issue](https://www.drupal.org/node/3414511) for [this deprecation](https://github.com/uiowa/uiowa/blob/10.3-updates/phpstan.neon#L12), gonna try and use the before and after to fix it.

**Comment by joewhitsitt** [comment]
I am guessing I broke something here:

`Drupal\Tests\uiowa_core\Functional\CardElementTest::testCard
Behat\Mink\Exception\ElementNotFoundException: Element matching css ".card" not found.`

https://github.com/uiowa/uiowa/pull/8133/commits/1780ef3071b6e62b060635b6811c1da4ee564156

I'll try to pull down and see what the issue is.

Update: didn't have time to see what the issue was. https://www.drupal.org/node/3436275

**Review by pyrello — APPROVED** [review]
Reviewed thread. It appears that everything has been tested and we are comfortable moving forward. Approving based on other folks testing.

**Pull request merged**
