### PR TITLE
initial commit of Student Life Migrate

### PR DESCRIPTION
**Pull request by quamsta**
Counterpart to our SilverStripe XML export module: https://github.com/StudentLifeMarketingAndDesign/silverstripe-migration-tools

This module parses pages, posts, people, categories, and files (PDFs, etc) and actively used images that are exported from our SilverStripe sites and imports them into SiteNow.

# How to test

Example SilverStripe site:

Content XML file: [content.xml.zip](https://github.com/uiowa/uiowa/files/7204923/content.xml.zip)
Website the XML file comes from: https://spock.imu.uiowa.edu/student-space/ (for reference)

1.  Download an XML file provided by one of the SilverStripe sites (example attached above)
2. Place the XML file in uiowa/files-private/migrations/current/content.xml
3. Enable studentlife_migrate (and dependencies) in local Drupal environment (Sandbox in this example): `drush @sandbox.local en studentlife_migrate -y`
4. Run `drush @sandbox.local migrate:import studentlife_content_staffpage,studentlife_images_import,studentlife_images_to_media,studentlife_categories,studentlife_tags,studentlife_content_page,studentlife_content_post,studentlife_files_import_remote,studentlife_files_to_media_remote`
5. Ensure that the pages, posts, people, tags, files, and actively used images have been migrated (there should be at least one of each of those in the example:

- Pages:
  - Home
  - Available Spaces
  - Example StaffHolderPage
  - Example Blog
- Posts:
  - Example Post
 - People:
   - Dustin Quam
 - Tags: 
   - Test tag
   - Another tag
 - Files:
   -  New-Attorney-Referral-List.pdf
  - Images: 
    - IMU-General2__ResizedImageWzYwMCwzMzhd.jpg
    - 165149720_10108953978731789_669086232225469991_n__FitMaxWzI1OTIsMTQ1OF0.jpg (Dustin wearing a rain coat)

Things that don't quite work right:
* Images are only imported and not attached to the nodes themselves and need to be manually linked
* Same with files, files are merely imported into the media library and usually have to be manually linked up
* There's always a duplicate of the final post/page imported,possibly due to: https://www.drupal.org/project/migrate_plus/issues/2891964

### CODE REVIEW

**Review by richardbporter — CHANGES_REQUESTED** [review]
CI is failing on a simple PHPCS violation: https://app.travis-ci.com/github/uiowa/uiowa/builds/238165917#L1462

**Comment by richardbporter** [comment]
You can run PHPCS locally with `blt validate:phpcs`. That will scan everything defined in `phpcs.xml`. You can scan individual files running it directly like `./vendor/bin/phpcs docroot/modules/custom/studentlife_migrate`.

**Comment by richardbporter** [comment]
I don't see a config split to enable in production to run the migrations but maybe thats not needed - is the intention to run this locally and then sql:sync?

**Comment by quamsta** [comment]
> CI is failing on a simple PHPCS violation: https://app.travis-ci.com/github/uiowa/uiowa/builds/238165917#L1462

Thanks! Will fix this

> I don't see a config split to enable in production to run the migrations but maybe thats not needed - is the intention to run this locally and then sql:sync?

This was made well before I knew how config splits were setup haha. But also, yes, this should be run locally for a number of reasons, one of which is the remote file/image migration being somewhat unpredictable with malformed MIME types (e.g., a content editor uploaded a PDF to their SilverStripe site that was actually a JPG). 

We're currently running the migration first, disabling the module and then sql:sync'ing to prod, and it's gone very well.

**Comment by richardbporter** [comment]
> > CI is failing on a simple PHPCS violation: https://app.travis-ci.com/github/uiowa/uiowa/builds/238165917#L1462
> 
> Thanks! Will fix this
> 
> > I don't see a config split to enable in production to run the migrations but maybe thats not needed - is the intention to run this locally and then sql:sync?
> 
> This was made well before I knew how config splits were setup haha. But also, yes, this should be run locally for a number of reasons, one of which is the remote file/image migration being somewhat unpredictable with malformed MIME types (e.g., a content editor uploaded a PDF to their SilverStripe site that was actually a JPG).
> 
> We're currently running the migration first, disabling the module and then sql:sync'ing to prod, and it's gone very well.

Ok that makes sense, especially since the source of this is an XML file you probably don't want on a prod server somewhere.

**Comment by quamsta** [comment]
@richardbporter This phpcs error was fixed, sorry it took so long!

**Comment by richardbporter** [comment]
>drush @sandbox.local migrate:import studentlife_content_staffpage,studentlife_images_import,studentlife_images_to_media,studentlife_categories,studentlife_tags,studentlife_content_page,studentlife_content_post,studentlife_files_import_remote,studentlife_files_to_media_remote

A shortcut for this, if you want to run all active migrations, is `drush @sandbox.local mim --all`.

**Comment by richardbporter** [comment]
I initially thought the `content.xml` file should go into the private files directory for the specific site migrating data. However, it seems that BLT sets that to `files-private` locally so I guess it _is_ in the correct private files directory. Thats odd though because if you sync private files with `blt sync --site sandbox.uiowa.edu --sync-private-files` they go into `files-private/sandbox.uiowa.edu`. I will look into that outside of this.

I also thought that the `migrate_plus.migration_group.shared_configuration.source.urls` config should use the `private://` filesystem stream wrapper but I couldn't get that working.

Last, we could enable this module as part of the local environment split so it gets turned on automatically for all sites. I don't think thats necessary though as most sites won't use it and syncing the DB to another environment will trigger a config import and it'll get turned off.

**Comment by richardbporter** [comment]
>Last, we could enable this module as part of the local environment split so it gets turned on automatically for all sites. I don't think thats necessary though as most sites won't use it and syncing the DB to another environment will trigger a config import and it'll get turned off.

Actually, I think we should set this up similarly to our other *_migrate modules. I've done that and pushed it up. The advantages are:

- consistency
- config in default state
- you can edit the migration YAML files and then run `drush @mysite.local cim` to get the changes. This makes it easier to work with.

Mostly just copied the slis_migrate code in https://github.com/uiowa/uiowa/pull/4148.

I think the general process remains the same: enable the module, run the migrations, uninstall the module. The config split lets you modify the migration and import changes as you go. Hope this is ok.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
