### PR TITLE
Display config changes for person field updates

### LINKED ISSUE #3847: Update grad_person_extended display configs
# Story

As a visitor to https://amcs.uiowa.edu/graduates and individual graduate pages, I want to see certain details such as current position in the profile teasers and full pages.

(Five fields were moved into the grad_person_extended split as work in #3789, and while these fields are available to editors, they are not currently used in the display.)

# Proposed solution

### PR DESCRIPTION
**Pull request by cory-skeers**
- Resolves #3847
- Updates in preparation for SPPA launch
- Fixes Grad College thesis defense view permissions regression 

# How to test

Check that a default site syncs with no config weirdness. View a person page--no changes or errors should be present.

Sync amcs.uiowa.edu, and check that it syncs properly.
Check any people from https://amcs.local.drupal.uiowa.edu/graduates, and check that any new fields from #3789 are visible (dissertation topic/thesis title, defense date, current position institution and title, and advisor(s))

## Stories 
- As an SPPA student, I can filter the opportunities page (https://sppa.local.drupal.uiowa.edu/opportunities), click an opportunity, hit the back button and my filters are still preserved.
- As a content editor on the grad college site I can see and edit thesis defense content on the content admin page (https://grad.local.drupal.uiowa.edu/admin/content?title=&type=thesis_defense).

### CODE REVIEW

**Comment by cory-skeers** [comment]
@pyrello and @e-marie-w, before making available for review/deployment, I wanted to check if there were any other updates needed.

Basic setup was taken from the immuno_grad split. The dissertation topic, position title, and position institution fields have their labels hidden, and the defense date field is currently not shown. (example below with dummy position information)

image

**Comment by pyrello** [comment]
This looks right to me. I would like to piggyback on your PR to make some unrelated changes to other config.

**Comment by cory-skeers** [comment]
> I would like to piggyback on your PR to make some unrelated changes to other config.

Sounds good to me--have at it!

**Comment by e-marie-w** [comment]
I have tested @cory-skeers part of this work. Only need the section under Stories tested by someone else.

**Comment by GaryRidgway** [comment]
The first story point is working, and I approve that

@cory-skeers, is a `content editor` someone with the `editor/publisher` role? I cannot access the edit page for  `Theseis Defense`s masquerading as a `editor/publisher`.

Screen Shot 2021-07-30 at 1 47 28 PM

**Comment by cory-skeers** [comment]
> is a `content editor` someone with the `editor/publisher` role? I cannot access the edit page for `Theseis Defense`s masquerading as a `editor/publisher`.

Good question! @e-marie-w or @pyrello?

**Comment by pyrello** [comment]
Good catch, @GaryRidgway! I have updated the PR and I think it should work correctly now. It appears that some permissions have gotten unset at some point along the way.

**Review by pyrello — APPROVED** [review]

**Pull request merged**
