### PR TITLE
Drush logging updates

### LINKED ISSUE #7444: Add logging back to our Drush commands
Follow-up from #7345 

After upgrading to Drush 12, our Drush Commands are logging to the terminal but not db logging. From the probe, the best solution seems to be to call the `\Drupal::logger()` directly. This can be done either in a module process which is called from the drush command, or by using the `LoggerChannelTrait`, like in https://github.com/uiowa/uiowa/commit/866f51001a7af52e03410d71726b9334b95b149f

Each of our drush commands (search our codebase for `DrushCommands` for the related classes) needs this done, outside the `alertsDigest` in `ItsCoreCommands`.

# Proposed solution

- Look at the files changed in https://github.com/uiowa/uiowa/pull/7310/files#diff-99429ce72219f6e2187c56f69cf3eafe16693c9419c44e8b1b0abd84f8d778f5
- For each class that extends `DrushCommands` and makes a call to `$this->logger()`
  - Add the `LoggerChannelTrait` to the class
  - For each call to `$this->logger()->notice($message)`, add an additional call like `$this->getLogger('module_name')->notice($message)` using the same log level (notice, error, etc) and same message
  - (https://github.com/uiowa/uiowa/commit/866f51001a7af52e03410d71726b9334b95b149f can be used as a reference for how the end result should appear)

For testing db logging:
`ddev drush @site.local en dblog`
Run the drush command you are testing
`ddev drush @site.local watchdog-show --count=10`
Any messages from the drush command should appear here

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7444 

# How to test

The following sitenow and site drush commands have been updated:

- Uiowa Core: `uiowa_core:toggle-gtag`, `uiowa_core:custom_role_mappings`
- Sitenow p2lb: `sitenow_p2lb:cleanup`
- its.uiowa.edu: `its_core:alerts-digest`
- brand.uiowa.edu: `brand_core:lockup-digest`
- classrooms.uiowa.edu: `classrooms_core:buildings`, `classrooms_core:rooms_import`
- facilities.uiowa.edu: `facilities_core:buildings_import`, `facilities_core:projects_import`

For each, test that on a fresh site sync 

1. the command functions and you see terminal output
2. Enable dblog and re-run the command, and check that
  1. you see terminal output 
  2. watchdog has caught the log (eg `ddev drush @site.local watchdog-show --count=10` you see a line item for what you just ran, or at /admin/reports/dblog)
3. Clear cache on the site you're working with, re-run again, and check that 
  1. you see terminal output
  2. watchdog has caught the log

Couple notes: 
On step 2 the terminal output will be doubled; that's okay and to be expected. It will go back to a single instance after the cache clear for step 3.

If the command ran properly in step 1, for steps 2 and 3 you only need to let it run far enough to get output and/or logging (for instance, facilities building import, you can cancel after the initial "starting" message)

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
I am not getting the expected double output or the watchdog output for `uiowa_core:custom_role_mappings` on connect.studentlife.uiowa.edu via `ddev drush @studentlifeconnect.local uiowa_core:custom_role_mappings` and `ddev drush @studentlifeconnect.local watchdog-show --count=10`

Should this be in-scope or not based on the instruction? It is more of a developer reporting command than something triggered on a schedule.

**Comment by cory-skeers** [comment]
> I am not getting the expected double output or the watchdog output for `uiowa_core:custom_role_mappings` on connect.studentlife.uiowa.edu via `ddev drush @studentlifeconnect.local uiowa_core:custom_role_mappings` and `ddev drush @studentlifeconnect.local watchdog-show --count=10`
> 
> Should this be in-scope or not based on the instruction? It is more of a developer reporting command than something triggered on a schedule.

I think since it's a developer reporting command, it's one we can probably leave as is.

**Review by joewhitsitt — APPROVED** [review]
For the commands that were touched this is working as described in the instructions. I appreciate the deep dive to ensure logging consistency.

**Pull request merged**
