### PR TITLE
Lazy Load Images

### LINKED ISSUE #697: Lazy Load Images Using Blazy
## Problem
Our web performance score is low. I don't know what that means but off-screen images on page load have something to do with it and with basic page we are indirectly encouraging long pages and lots of images.

https://www.drupal.org/project/blazy

https://www.symphonythemes.com/drupal-blog/speed-your-drupal-8-sites-image-lazy-loading

Probably not for section images, but everything else makes sense to me.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #697 

This implements lazy load images for both SiteNow and uiowa.edu.

### Editors
Editors should be able to add, edit images like before. Need to test all image fields, view modes and wysiwygs. For both layout and paragraphs, caches should be invalidated and editors should see new and replacement images right away. Inspecting the DOM, editors should see lazy load markup around the image markup.

### Visitors
Visitors should see a fade-in effect for images on page load. The network tab should show that the majority of image assets are loaded later than other assets.

**Note:** SiteNow Carousel in my testing could be one instance where we don't want lazy load. The load doesn't seem to happen until the carousel navigation is clicked. The carousel uses a unique view mode so other images should not be affected if removed. There is lazy load compatibility with Slick slider if we adopt that after Bootstrap.

### CODE REVIEW

**Review by bspeare — APPROVED** [review]
Love it! It works great on my local version of uiowa.edu.

**Comment by joewhitsitt** [comment]
Cool! I'd like to make sure that it is working as expected in most instances (paragraph bundles, view modes)

**Comment by richardbporter** [comment]
I tested the demo site locally but adding a bunch of widgets with images. 👍

**Comment by joewhitsitt** [comment]
The other issue I had to setup config for is related to the entity embed, entity browser and media library to make sure images loaded correctly for editing interfaces.

I'd like to also get thoughts on SiteNow Carousel. Is it a problem to load on slide change?

**Comment by joewhitsitt** [comment]
@dnkemper spotted an issue with the global caption displaying when it isn't supposed to. working on a fix

**Comment by dnkemper** [comment]
@joewhitsitt at first, the second image lagged a bit with loading and only showed the caption... but it eventually showed after a couple seconds then loaded fine. Might just be me though.

**Comment by dnkemper** [comment]
> @dnkemper spotted an issue with the global caption displaying when it isn't supposed to. working on a fix

discovered that the global caption only appears in wysiwyg when you display the original picture. Works correctly with displaying large, small and medium images

**Comment by dnkemper** [comment]
Tested w/ updated code using the original image setting in the wyswyg and works correctly now! Great job, Joe!

**Comment by richardbporter** [comment]
I don't think the carousel lazy loading is an issue.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
