### PR TITLE
Set bot crawl-delay and unset internal pages from HTML head.

### LINKED ISSUE #2956: Remove metatags for 'delete-form', 'edit-form', 'latest-version' from Taxonomy term pages
# Problem
SiteImprove appears to be picking up some links that it thinks are broken links and seem to actually be metatags:
Screen Shot 2021-01-27 at 8 40 37 PM

# Steps to reproduce
View source on this page and search for `taxonomy/term/291/`: https://grad.prod.drupal.uiowa.edu/tags/2020-3mt-finalist

# Proposed solution

This issue seems to indicate a potential solution: https://www.drupal.org/project/metatag/issues/2625300

TBD

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2956

Also adds `crawl-delay: 1` to robots.txt config as recommended by SiteImprove. This does not affect Google bot as they ignore this directive.

### Testing
- Sync a site.
- View a term page as an anonymous user and inspect HTML head for the `<link>` elements relating the delete-form, edit-form, etc. pages.
- Go to VM IP https://192.168.184.241/robots.txt and inspect for crawl-delay directive. Have to do this because we override for internal domains.

### CODE REVIEW

**Review by cory-skeers — APPROVED** [review]
Checked on default, and the `crawl-delay: 1` was set. Checked on engineering.uiowa.edu and both the `crawl-delay: 1` was set, and checked a term page as anonymous, and several links (edit, delete, version-related links) were removed from the `<head>`.

**Comment by richardbporter** [comment]
> Checked on engineering.uiowa.edu 

I'm assuming you mean https://engineering.local.drupal.uiowa.edu/robots.txt. That should only have the `disallow: /` directives, unless its cached. I hit a few sites and that seems to be the case.

**Comment by cory-skeers** [comment]
> I'm assuming you mean https://engineering.local.drupal.uiowa.edu/robots.txt. That should only have the `disallow: /` directives, unless its cached. I hit a few sites and that seems to be the case.

Yep--meant that I followed the testing instructions after syncing engineering.uiowa.edu. https://192.168.184.241/robots.txt has the `crawl-delay: 1`, https://engineering.local.drupal.uiowa.edu/robots.txt has only the `disallow: /`.

**Comment by richardbporter** [comment]
Perfect thanks!

**Pull request merged**
