### PR TITLE
Add privacy notice popup on uiowa.edu

### LINKED ISSUE #3943: Add privacy notice popup on uiowa.edu
Because I expect a reputable brand to be upfront about how they respect my privacy as a web visitor, I expect a notice on first visit to any page on the uiowa.edu website

### Examples
The notice appears on first visit, requires acknowledgement to clear, & sets a cookie, and does not appear again unless: 
- the Privacy page content changes
- 1 year has passed? 

### Future
In the future, will likely extend this first to admissions, then to other primary colleges, etc...
This may preface future options that include specific cookie enumeration and consent, etc...
We may consider vended solutions like OneTrust, etc...

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3943 
# How to test

### CODE REVIEW

**Comment by dnkemper** [comment]
Screen Shot 2021-10-25 at 2 24 57 PM

**Comment by bspeare** [comment]
Adding design meeting notes before we forget:
- Can we reduce the text?  Can it just be a notification about cookies with a link explaining them?
- Smaller font size and line-height and a good use case for a smaller variant of the button.
- Use container for text and button so they are not so far apart.
- Investigate smaller/minimal implementations.

**Comment by joewhitsitt** [comment]
Can this be closed since we are going with a vendor for this need? https://github.com/uiowa/uiowa/issues/6490

**Comment by joewhitsitt** [comment]
Closing since we ended up going with OneTrust

**Pull request closed without merging**
