### PR TITLE
i1392 people paragraph bundle

### LINKED ISSUE #1392: People Paragraph Bundle
## Problem
We didn't quite reach feature parity with SiteNow v1 when it comes to people. Site owners are requesting a way to create dynamic lists of filtered people on their sites. The current option is to either use the full people listing or to manually curate people via featured content.

## Proposed Solution
Similar to the Articles paragraph bundle, create one that handles people. Start with a generic person view and through paragraph bundle settings allow the list to be filtered by tag and allow the sort order to switch between sticky/last/first or sticky/first/last. Similar styles can be extended from featured content where images and fields can be hidden along with the list/grid/masonry style options.

Depending on the timeline of this feature, styles should be done building off the patterns defined in UIDS. Work is currently be done to handle SiteNow articles in UIDS and this shouldn't be too much different.

## References:
https://github.com/uiowa/uiowa/blob/master/docroot/modules/custom/sitenow_articles/sitenow_articles.module#L275

### PR DESCRIPTION
**Pull request by dnkemper**
i1392 people paragraph bundle

Will add testing info Monday

Closes #1392

### CODE REVIEW

**Comment by dnkemper** [comment]
<h1>Testing</h1>

1. Content -> Person -> Add People with different last and first names
2. Be sure to add a short biography and make sure at least two have the same relationship tag
3. Set to ‘Published’ and save
4. Create a new Basic Page
5. Add a ‘People’ Content Block
6. Filter by one of the relationship tags you put in the individual Person nodes
    1. When you uncheck the ‘Display Title’ make sure a title doesn’t display
    2. Change around the number of items to display and make sure the correct number displays
    3. Select ‘Show Pager’ and make sure the pager shows and works
    4. Select the ‘Display More Link’ and make sure a ‘View more people’ button appears at bottom
        1. Link should take you to ‘people’ page
        2. If you add a URL to ‘Path’, the button should take you there
    5. When you select Sticky/First/Last - make sure they’re sorted correctly (by first name then last)
        1. Vice versa with Sticky/Last/First
    6. When you select ‘Hide Images’ or ‘Hide Biographies’, make sure they hide the person’s featured image and short bio (which will be the bio that displays in the teaser)

**Review by GaryRidgway — APPROVED** [review]
I have checked all of the items laid out by Danielle, and have verified that they work.

**Comment by joewhitsitt** [comment]
Don't merge yet. I'd like to do further testing with this. Overall it looks good but there are a few things I have noticed so far:

- I am not seeing the default more link if no custom path/url is provided. I think the elseif logic around this might be tripping things up.

>Check to include a 'display more' link. To use the default people path set within SiteNow People, make sure the ‘Enable people listing’ box is checked. Alternatively, a custom URL path can be provided in the ‘Path’ text box below.

- Though I didn't explicitly say no styles for uiowa_bootstrap, this should wait and adopt UIDS styles before merge similar to https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uids_base/scss/components/sitenow/paragraphs/uiowa-articles.scss

- If we are to move forward with uiowa_bootstrap styling for this, we need to resolve the existing `@extend` issue with uiowa_bootstrap as I believe this is now causing `blt frontend` failure for the HR subtheme (at least for me).

**Comment by joewhitsitt** [comment]
After talking about this during check-in, the plan is to remove the uiowa_bootstrap styles and merge this functionality if otherwise ready along with the new theme rollout. Marking as blocked.

**Comment by joewhitsitt** [comment]
Did this get fixed?

>I am not seeing the default more link if no custom path/url is provided. I think the elseif logic around this might be tripping things up.

**Comment by dnkemper** [comment]
@joewhitsitt thought I had to abandon it for now because of funding

**Comment by joewhitsitt** [comment]
Ah. okay. I'll bring it up tomorrow in check-in

**Comment by joewhitsitt** [comment]
This is a bad merge. 2k files should not be changed in this PR

**Comment by dnkemper** [comment]
@joewhitsitt strange. I only edited one file. FUN!

**Review by richardbporter — DISMISSED** [review]
Yea this can't be merged. Its undoing a ton of work unless the GitHub diff is wrong.

**Comment by joewhitsitt** [comment]
I will clean this up in a bit and document the process for future reference

**Comment by dnkemper** [comment]
@joewhitsitt @richardbporter SORRY! Going to go hide in a corner now

**Comment by richardbporter** [comment]
NP. Just wanted to flag this PR so it wasn't merged.

**Comment by joewhitsitt** [comment]
For reference: I pulled this locally, git reset --hard c20f5d7104d0dcfba456bf5a1b9509f0f1f28329, git push origin i1392-people-paragraph-bundle --force. then i pulled down master, checked out the branch again, git merge master, fixed merge conflicts, and pushed the successful merge.

fyi, i believe since i force pushed to fix: other folks that have pulled this branch down will need to 
`git pull origin i1392-people-paragraph-bundle`
`git clean -fd`

**Comment by bspeare** [comment]
A few notes on the updates I just added:

- Does anyone else get this error after adding a person paragraph? `errorNotice: Undefined property: stdClass::$region in field_group_form_process() (line 366 of modules/contrib/field_group/field_group.module)`
- I'm not sure this is necessary, but I wasn't sure the best way to grab the `field_person_credential` field: https://github.com/uiowa/uiowa/pull/1468/commits/47b1fc79bb79fa12c512ec95f568e9e8272f6104
- How the `field_person_credential` is being displayed is currently not displaying how it is in `uiowa_bootstrap`.   This could be a good conversation piece for the design meeting?

**Comment by bspeare** [comment]
This is ready to be reviewed to check for:

**/people page**
- List view?

**Featured Content**
- Grid?
- List?
- Masonry?
- Hide Images?
- Hide descriptions?

**Masonry**
 - masonry hide descriptions work? 
- masonry hide images and descriptions work?
- masonry hide images work?
- all mobile views?

**Grid View** 
- grid hide descriptions work?
- grid hide images and descriptions work?
- grid hide images work?
- all mobile views?

**Normal List View**
- Hide images work?
- hide descriptions work?
- hide images and descriptions work?

**Every background color**
- Light
- Gold
- Dark
- Black

**Node person page**
- Are all fields displaying?

**Comment by bspeare** [comment]
I just noticed that the "Featured Content" display is not styled yet.  This still needs to be done in this PR.

**Comment by joewhitsitt** [comment]
>Does anyone else get this error after adding a person paragraph? errorNotice: Undefined property: stdClass::$region in field_group_form_process() (line 366 of modules/contrib/field_group/field_group.module)

Yes, I will look into that.

**Comment by joewhitsitt** [comment]
I don't think the paragraph bundle got the field_group update hook a while back. Re-ran it, exported. Haven't tested yet.

**Comment by joewhitsitt** [comment]
@bspeare sub_title was supposed to be a utility variable for other things in the future, but is only being used for person I believe. It gets appended to the page title (full/teaser) if available and was inspired by bootstrap 3 small heading: https://getbootstrap.com/docs/3.4/css/#type-headings
https://github.com/uiowa/uiowa/blob/master/docroot/themes/custom/uiowa_bootstrap/templates/content/page-title.html.twig

I am flexible on how this is displayed in uids_base, if it is going to be rendered in the content view mode, the sub_title logic is not needed.

**Comment by bspeare** [comment]
@joewhitsitt Thanks for the clarification on that!

**Comment by joewhitsitt** [comment]
So, when ready, I suggest this just get pushed out but without the modification to config/default/field.field.paragraph.section.field_section_content_block.yml (enables the bundle for use). That way we can clear this PR from the queue and enable it with the uids_base rollout.

**Comment by bspeare** [comment]
@joewhitsitt @dnkemper This should be ready to review now.  I probably missed a few variations but I can't think of them.

**Comment by joewhitsitt** [comment]
Found one and corrected. Going to keep looking at it. I think this is really close!

**Comment by joewhitsitt** [comment]
Whew! I think this is ready. new functionality with uids_base support, "disabled" for now until the theme rolls out.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
