### PR TITLE
Update Tagging Functionality

### PR DESCRIPTION
**Pull request by joewhitsitt**
## Description
Initial step at removing field_reference on SiteNow websites in favor of a simpler approach.

For all sites except for HR, this will move all field_reference tags to field_tags, writes a revision message and saves the node (page, article, person). This also updates the articles paragraph functionality to use field_tags instead and limits/restricts access to field_reference until it can be deleted/split only for HR.

Four sites at the time of writing this use tags: hr, mnh, oldcap and sitenow.

There is a risk in validation errors if a node with field_refrerence containing tags is reverted, but there is limited use and a follow-up issue #860 to eliminate the possible validation/access errors.

This change should be communicated with HR.

## Related Issue
#841 

## Follow-Up
#860

### CODE REVIEW

**Comment by richardbporter** [comment]
Tested `dsa`-ing all the sites mentioned with no problems.

Possibly unrelated but I noticed the article view filtering by tags acting wonky. Also, the people view seems to be weird as well.

**Comment by richardbporter** [comment]
mnh.uiowa.edu
- Article "foo" tagged with "bar"
- Page with article listing filtering on tag "bar", configured to show 3 articles
- Article "foo" displays along with two others not tagged with "bar"

Is this expected?

**Comment by joewhitsitt** [comment]
i will try to reproduce this locally, thanks for testing

**Review by richardbporter — CHANGES_REQUESTED** [review]
I think the issues with articles is related to this PR. Not sure exactly what yet but master works fine.

**Comment by richardbporter** [comment]
The people issue seems unrelated as it is currently an issue in prod. I have to re-save person nodes to get them to show up in the people view.

**Comment by richardbporter** [comment]
A simpler article test case for the default site:

- Create two terms foo and bar
- Tag "Keep Moving Forward" with foo
- Filter articles on front page by tag bar
- The article "Keep Moving Forward" still displays

**Comment by richardbporter** [comment]
Same issue in https://github.com/uiowa/uiowa/pull/863#issuecomment-569793722 still.

**Comment by joewhitsitt** [comment]
@richardbporter it won't let me re-re-request a review... but i think i fixed the issue

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
