### PR TITLE
Feature: Update lb_direct_add module and related styles.

### LINKED ISSUE #3244: "Add Articles" dropdown-like button is unclear
As I've worked with layout builder recently, I've found myself (and some others I've talked to) getting lost when I'm adding blocks into sections when I see a button simply labeled "Add Articles." I often overlook the arrow that provides more options. 

Screen Shot 2021-03-12 at 12 00 42 PM

Is there a way to clarify (visually or otherwise) that there are more options for blocks besides articles if you click the arrow? The user experience is a bit confusing because it's not really presented as a dropdown list of options of things to add, but instead looks more like a simple action button that will only "Add Articles," with an arrow being the only indicator of... something else when you click it, but it doesn't necessarily imply adding additional things. It appears to be a sort of hybrid between a dropdown and a button, where changing a dropdown value will change the action button

I've researched layout builder a bit and I'm wondering if there's a reason (besides maybe fewer clicks needed) we aren't simply saying "Add block" here as a clear, direct action, as screenshotted here from Ohio State's documentation:

Screen Shot 2021-03-12 at 12 35 11 PM

### PR DESCRIPTION
**Pull request by pyrello**
This PR tracks changes going on in [this issue](https://www.drupal.org/project/lb_direct_add/issues/3157440). 

Resolves #3244.

# How to test

* `blt ds`
* `drush @default.local uli node/1/layout` and observe popover functionality for "Add blocks".
* Ensure that clicking block links and "More..." link still works.
* Visit http://sandbox.local.drupal.uiowa.edu/admin/config/content/layout-builder-direct-add to view the new settings page.

### CODE REVIEW

**Comment by pyrello** [comment]
As soon as I merge this, it will be ready for review.

**Comment by joewhitsitt** [comment]
Pulling down to test

**Review by joewhitsitt — APPROVED** [review]
Works for me. I'd love to see a better tab focus but there wasn't much of one before so that can be a future enhancement.

**Comment by pyrello** [comment]
If you have any specific suggestions of how this could work, please consider opening an issue to add it to the module: https://www.drupal.org/node/add/project-issue/lb_direct_add

**Comment by joewhitsitt** [comment]
I thought we had a custom layout builder experience. blocks get a mouse hover (dark gray) and keyboard outline focus change (blue), the add button doesn't get the keyboard focus.

Screen Shot 2021-03-30 at 12 25 58 PM
Screen Shot 2021-03-30 at 12 26 20 PM

**Comment by joewhitsitt** [comment]
Sean would like to tweak some styling for this before merge

**Comment by pyrello** [comment]
I added some styles to this, but I think it could use the @bspeare touch!

No interaction:
Screen Shot 2021-04-01 at 4 56 23 PM

Hover:
Screen Shot 2021-04-01 at 4 56 37 PM

Focus:
Screen Shot 2021-04-01 at 4 56 48 PM

**Pull request merged**
