### PR TITLE
Enable drupal-check and other additional code linting.

### LINKED ISSUE #717: Drupal 9 Code Audit
## Problem
We should probably start preparing our codebase for Drupal 9 and making sure our contrib modules will be ready for Drupal 9.

## Proposed Solution
https://www.drupal.org/project/site_audit
https://www.drupal.org/project/upgrade_status
https://github.com/mglaman/drupal-check/

Create separate issues for things that come up, look into the community to see if a solution has already be figured out.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #717 

All validation checks can be run locally using `blt validate`.

### CODE REVIEW

**Comment by richardbporter** [comment]
I think it would be a good idea to reduce as many warnings as possible.

**Comment by joewhitsitt** [comment]
> I think it would be a good idea to reduce as many warnings as possible.

How many are there? 😰

**Review by richardbporter — COMMENTED** [review]
Any chance @joewhitsitt or @cory-skeers could re-run a migration locally to see if these changes affect it?

Specifically: https://github.com/uiowa/uiowa/pull/824/commits/a486fc1df72e06fd5ef5b7c6f8c41befbac7eba2

**Comment by richardbporter** [comment]
I think we can reduce warnings in a follow up if we want to get this merged and start `drupal-check`-ing all code going forward.

**Comment by joewhitsitt** [comment]
the migrate stuff appears to still work the way I originally tested it

**Comment by joewhitsitt** [comment]
unrelated, but i ran `blt validate` and there were two errors related to uiowa_bootstrap js. i fixed them but don't see them in the git status because of `docroot/themes/custom/*/assets/js` in the .gitignore

i know we talked about re-organizing this stuff since drupal aggregation does essentially the same things as the current gulp task so i don't know if this is an immediate issue or not.

docroot/themes/custom/uiowa_bootstrap/assets/js/bootstrap_popover.behavior.js
docroot/themes/custom/uiowa_bootstrap/assets/js/bootstrap_tooltip.behavior.js

**Comment by richardbporter** [comment]
Hm. I'm not seeing those theme errors for some reason.

**Comment by joewhitsitt** [comment]
Look Ma! Dependency injection!

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
