### PR TITLE
i3559 - User Role Permissions

### LINKED ISSUE #3559: Adjust delete permissions
# Story

As a site owner, I would like to limit delete rights so that content is not accidentally or mistakenly deleted since it cannot be easily recovered.

# Additional Info

Only allow editors to delete content they "own". I think this could be done the same for publishers as well since they do have the ability to archive content but would like to get feedback on the team if this should be done for just editors or both editors and publishers.

We should verify that webmasters have the ability to change author of content.

Dentistry would like to have this by the beginning of July.

# Proposed solution

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #3559 

# How to test

1. Run ‘blt ds —site=sandbox.uiowa.edu’
2. Run ‘drush @sandbox.local uli’
3. Go to https://sandbox.local.drupal.uiowa.edu/admin/people/create and create a ‘test’ user with the webmaster role selected
    1. Change the author of a piece of content and make sure it saves without errors and updates accordingly
4. Go to https://sandbox.local.drupal.uiowa.edu/admin/people/create 
    1. Create another user or change this users perms to ‘Publisher’ 
        1. Go to https://sandbox.local.drupal.uiowa.edu/admin/content and click on the operations dropdown arrow for the content -> shouldn’t see the ‘delete’ option 
        2. Edit a piece of content -> same situation
        3. Repeat with the ‘Editor’ role and make sure you get the same results

I also had to update the role perms for custom sites - I believe I got all that have any split user perms - make sure:
1.  I removed right to delete any custom content for editors/publishers 
2. I granted webmasters the ability to change the ‘authored by’ field for all custom content types as well please

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by dnkemper** [comment]
@cory-skeers Thank you so so much! 🙌

**Comment by cory-skeers** [comment]
Site splits will need permission updates as well (admissions, I think policy.clas, and any others that have different permissions than default).

And along those, if admissions permissions need to be updated separately, should this update be made for areas of study as well? I don't think any active user owns any of the current AoS content since it was migrated in, but it would give the option of a webmaster assigning ownership of them.

**Comment by cory-skeers** [comment]
Tested on a non-split site, and everything works great!

**Comment by dnkemper** [comment]
@cory-skeers that is a solid point, thank you! Okay... should I do this with all custom content types for site splits then? @briand44 have a suggestion on this?

**Comment by dnkemper** [comment]
Okay, believe this is officially good to go!

**Comment by dnkemper** [comment]
@cory-skeers okay NOW I'm officially done after making sure I didn't leave anything out. 2 perms were missing. So close, yet so far haha. Sorry about that!

**Comment by cory-skeers** [comment]
Looks like all site splits are covered, and have tested on a default config site and admissions. Going to give it another look through, but it looks like it should be good to go!

**Comment by dnkemper** [comment]
Thank you so so much, @cory-skeers 🥳

**Review by cory-skeers — APPROVED** [review]
Tested on default/admissions, and reviewed the other site split updates. 💯

**Comment by dnkemper** [comment]
Thank you so much, @cory-skeers 🙌

**Pull request merged**
