### PR TITLE
Feature: Residence hall content type

### LINKED ISSUE #5227: Create content type for Residence Halls
As a Housing site owner, I would like to have a structured content type to store information about residence halls so that information can appear similarly across all residence hall pages.

# Additional Information

Setup content type (https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes) as part of housing site split and create fields:

- [x] Building type - taxonomy or select list - (traditional residence hall or suite-style residence hall)
- [x] Room type - taxonomy or select list - (single, double, triple, quad)
- [x] bathroom type - taxonomy or select list - (community style, single-user, suite-style, private restroom)
- [x] Intro/Body - They need an intro paragraph to describe each residence hall. https://housing.uiowa.edu/residence-halls/burge-hall
- [x] Featured image field for top banner
- [x] Image field - multi - Would like to have a photo gallery of images of the residence hall
- [x] Video field - single - Add YouTube video that tells about the hall
- [x] Ability to show LLC's located in each hall - entity reference?
- [x] Furnishings - taxonomy - rabbit holed? (https://housing.uiowa.edu/residence-halls/burge-hall)
- [x] Amenities - taxonomy - rabbit holed? (https://housing.uiowa.edu/residence-halls/burge-hall)
- [x] Floor plans and 360 views - shows a sample floor plan and 360 views of a typical room (screenshot on epic)
- [x] Meet us - reference multiple people - had inline entity form on D7
- [x] Getting around info - A text area to provide information about proximity to other campus locations.
- [x] Links to bus stops - multiple link field with titles to enter stop names - no integration with Bongo.
- [ ] Map - Concept3D map of residence hall in relation to rest of campus. They would like this displayed higher up the page if possible when we get to the display.
- [x] Bathroom images - multi image field to display bathroom photos in some sort of gallery - could possibly link to a page if we feel that makes the most sense? 
- [x] Rates - They like how rates are handled on this site https://housing.umn.edu/bailey
- [x] Address - Include a section for mailing address for each particular residence hall. Similar to https://housing.umn.edu/bailey
- [x] Neighborhood - (East, West) select list
- [x] Year Built - Date (Year granularity)
- [x] Population (text field on D7)
- [x] Who lives here - taxonomy reference? (screenshot on epic) - Honors students live in all halls - want to make that more visible to visitors.
- [x] Front Desk phone - phone
- [x] Front Desk Hours - text area
- [x] Get Involved Call to action links - These currently have an icon, title and brief desc text
  - [x]   Connect with your community - will link to a page within Housing site
  - [x]    Advocate for Students - Links to arh.org.uiowa.edu - Rewrite text to say: Make a difference by being a resident assistant (RA). Would link out to My Housing section.
  - [x]    Work for Us - Links to studentlifejobs.uiowa.edu
 - [x]   Link to Dining Menu - Will link to dining.uiowa.edu
- [x] Link to place a work order - Include a section to place a work order, will link to housing.uiowa.edu/my-housing
- [x] Section to place information about emergency policies (This will be text only, so an accordion on each res hall page with this information or link out to a basic page could suffice.)

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5227

# How to test

- `ddev blt ds --site=housing.uiowa.edu`
- `ddev drush @housing.local en rabbit_hole`
- `ddev drush @housing.local config:import --source ../config/sites/housing.uiowa.edu --partial`
- `ddev drush @housing.local cim`
- `ddev drush @housing.local cr`
- Review content type according to our standards and tell me what I missed
- Verify that all the fields checked off on https://github.com/uiowa/uiowa/issues/5227 are on the content type
- Mockup for content type is at https://sandbox.prod.drupal.uiowa.edu/catlett-hall which helps explain how these fields **might** be used in the design.

### CODE REVIEW

**Comment by bspeare** [comment]
Having issues with `The "extra_field_block:node:residence_hall:content_moderation_control" was not found` with this content type (https://www.drupal.org/project/drupal/issues/3176461) (https://github.com/uiowa/uiowa/pull/5258#issuecomment-1123012669).  

I'm also getting these reports on `/admin/structure/types/manage/residence_hall/display/default/layout`. 

`Notice: Undefined index: provider in block_theme_suggestions_block() (line 200 of core/modules/block/block.module).`
`Notice: Undefined index: provider in menu_ui_preprocess_block() (line 460 of core/modules/menu_ui/menu_ui.module)`
`Notice: Undefined index: provider in user_preprocess_block() (line 338 of core/modules/user/user.module).`

If anyone can remember a good way to fix this - let me know!  https://github.com/uiowa/uiowa/pull/5258#issuecomment-1123772454 is not working for me.

**Comment by joewhitsitt** [comment]
So far the not found warning hasn't stopped us from doing what we need to do. https://github.com/uiowa/uiowa/issues/1914

I haven't encountered nor do I recall encountering `Undefined index: provider...`.

**Comment by bspeare** [comment]
@joewhitsitt Thanks for chiming in.  The errors seem to come and go.  I just added a new field and now they are gone.  I'll update this issue if they return permanently.

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by bspeare** [comment]
Looks like I need to fix this. 
Screen Shot 2022-05-18 at 3 40 44 PM

**Comment by joewhitsitt** [comment]
- ~~SEO Settings is displaying more buckets than normal (e.g. Schema Person, Schema Article)~~ 0099795. Wonder if we should turn Schema.org Place for this content type though.
- ~~Noticed sticky and authored on are visible to the webmaster~~  - ee952b3 if these don't have a chronological or sticky sort use-case we haven't provided these in the past.
- ~~I think help text is needed for many of the fields. For example, "Bathroom Image(s)" is a text field. I see how it is to be used (https://sandbox.prod.drupal.uiowa.edu/catlett-hall#bathrooms) but that isn't clear on the edit form.~~ e800124
- ~~Speaking of bathroom images, should we just have a multi-link text field for this for MVP? They could create pages with image galleries?~~ 864db8c
- ~~Should we try to limit characters or add custom validation for field_residence_hall_year_built since we can't use a normal date field?~~ 3273296
- ~~Should population be a number/integer field?~~ 13803b6
- I encountered the `Undefined index: provider` and a broken moderation block. I might poke at this. - wtf, this is not consistent...
- ~~Should the CTAs require a link?~~ fa52cf4
- Looks like the emergency policies field type shifted from the issue summary. I like the links but want to make sure more "text" isn't needed with these.

As a webmaster I was able to create a res hall and related taxonomies. As an anonymous visitor, I was not able to reach the related taxonomy terms. There was a field for every item on the issue except for the map field understandably.

**Comment by bspeare** [comment]
>     * Speaking of bathroom images, should we just have a multi-link text field for this for MVP? They could create pages with image galleries?

@joewhitsitt are you thinking a paragraph with a text + link field here?

**Comment by joewhitsitt** [comment]
No sorry, late-afternoon typing. I was thinking a multi-value link field with title and typed it wrong. The mockup has this as title/button so I assumed there wasn't additional content with these.

**Comment by bspeare** [comment]
I could definitely use some help on the Undefined index: provider and a broken moderation block problem.

**Comment by bspeare** [comment]
@joewhitsitt I think the items in https://github.com/uiowa/uiowa/pull/5273#issuecomment-1130565084 should be addressed except for `Undefined index: provider and a broken moderation block problem`.

**Comment by joewhitsitt** [comment]
Taking another look

**Comment by joewhitsitt** [comment]
Emergency policies is only allowing 1 item

**Comment by bspeare** [comment]
> Emergency policies is only allowing 1 item

I'm only looking for one grouping of those fields, should I switch to another method to group those?

To have it look something like:

Screen Shot 2022-05-19 at 10 52 40 AM

**Comment by joewhitsitt** [comment]
If there is only one item per node, not sure I would create a separate paragraph type for this.

**Comment by joewhitsitt** [comment]
Partly because of me, I feel "Bathroom Image(s)" has lost some meaning since it isn't an image field like Media > Image(s) field.

**Comment by bspeare** [comment]
> 

Yes, maybe we change the title of that field to something like "Bathroom gallery link"?

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/drupal/issues/3042418#comment-14098250 - re: undefined index provider. maybe we need to run cron locally before exporting changes to layout builder layouts?

**Comment by joewhitsitt** [comment]
I am wondering if that error has to do with the generateSampleValue that is used to "fill" the layout builder interface as I don't get that error on article/person. Perhaps it is related to remote video, paragraphs type fields

**Comment by bspeare** [comment]
@joewhitsitt I moved the emergency policy into individual fields.  It still might change based on customer feedback on the mockup.


Screen Shot 2022-05-19 at 12 02 19 PM

**Review by joewhitsitt — APPROVED** [review]
As a general content type, this looks good. As we get more feedback from the customers, the fields will take shape and be finalized.

**Comment by bspeare** [comment]
I've updated this content type to match the mockup with these changes:

- Deleted `field.field.node.residence_hall.field_residence_hall_address` - address field
- Deleted `field.field.node.residence_hall.field_residence_hall_dining_link` - link field
- Deleted `field.field.node.residence_hall.field_residence_hall_hours` - long text field
- Deleted `field.field.node.residence_hall.field_residence_hall_phone` - phone field
- Deleted `field.field.node.residence_hall.field_residence_hall_wo_link` - link field

And replaced them with:

- Added `field.field.node.residence_hall.field_residence_hall_bldg_links` - paragraph reference to `housing_cta` paragraph
- Added `field.field.node.residence_hall.field_residence_hall_contact`- paragraph reference to `housing_cta` paragraph

The `housing_cta` paragraph, has a `title`, `image`, `description`, and `link` that will all be styled using the card template.

**Comment by bspeare** [comment]
Can someone review the recent changes of this pr: https://github.com/uiowa/uiowa/pull/5273/commits/209da5545bcb14c46355358cf29e9f50ed513788 and run through the testing steps to make sure this is still working?

**Comment by e-marie-w** [comment]
> Can someone review the recent changes of this pr: [209da55](https://github.com/uiowa/uiowa/commit/209da5545bcb14c46355358cf29e9f50ed513788) and run through the testing steps to make sure this is still working?

I can!

**Comment by e-marie-w** [comment]
Just wanted to note I'm also getting the `Undefined index: provider...` errors. For me it seems to be consistently 5. I filled out the fields and saved frequently, but didn't count the errors until I was finished. I also created a Residence Hall with empty fields and still got 5. 

Possibly a new issue: I also see `This block is broken or missing. You may be missing content or you might need to enable the original module` when trying to view the content. 

All the checked off fields are present for me. I checked the recent changes first and they seemed fine, but I'll double-check now that I understand those fields better.

**Comment by e-marie-w** [comment]
The `This block is broken or missing` ended up being the moderation control block. The [content type creation wiki doc](https://wiki.uiowa.edu/pages/viewpage.action?spaceKey=drupaldev&title=Content+type+creation+notes) mentioned needing to resave the form display. After doing that, the broken block message and the 5 `Undefined index: provider...` errors disappeared for me. That doesn't show up as a file change or config change to export, so I don't know how to save it if needed. Maybe I just had gremlins.

The recent code change looks fine and the content type covers the relevant things from that wiki list. 

There's just one role permission that isn't behaving as expected and is confusing me. On [https://housing.uiowa.ddev.site/admin/people/permissions](https://housing.uiowa.ddev.site/admin/people/permissions) nobody can create new Residence Hall content except admins. But if I masquerade as a webmaster I can still add a new Residence Hall.

**Comment by bspeare** [comment]
Still to do on this:

- Figure out what we want to do for iframe embeds on the floor plans text area
- Figure out how we want to set up the bathroom type and bathroom link section

Screen Shot 2022-05-26 at 11 08 00 AM

**Comment by bspeare** [comment]
After looking at the floor plan in D7, I think we might want to change the floor plans field to a paragraph with these fields. 

- Floor room Type - reference existing room type taxonomy
- Floor Panoramic Image - uses https://github.com/mpetroff/pannellum - still use that here?
- Floor plan image 
- Floor plan description

**Comment by bspeare** [comment]
I've made the updates to the fields and permissions on this.   I'm still getting the `This block is broken or missing. ` for the moderation block and re-saving the form display is not fixing the problem.

**Comment by pyrello** [comment]
> I've made the updates to the fields and permissions on this. I'm still getting the This block is broken or missing. for the moderation block and re-saving the form display is not fixing the problem.

This problem is very annoying. Here is my guess about why it is happening. Because the editorial workflow is a patch file, only the patch and not the actual changes from the patch get imported initially. Hence the additional `drush cim`. Because it doesn't exist at the time when the `core.entity_view_display.node.residence_hall.default` config gets imported, the block is attached to a UUID that doesn't exist.

When I was able to fix this before by re-saving the form display, that involved also being able to drag the content moderation field back into the form display. Then it magically appeared again on the Layout template and could be saved. I have no idea why that worked, but it did and we stopped having this problem.

I cannot find a similar set of actions here to get it to work in this case.

**Comment by pyrello** [comment]
Related? 
- https://www.drupal.org/project/drupal/issues/3176461
- https://www.drupal.org/project/drupal/issues/3056135

**Comment by bspeare** [comment]
@pyrello what do you make of this solution on that issue? https://www.drupal.org/project/drupal/issues/3176461#comment-14423398

**Comment by bspeare** [comment]
It looks like `ddev drush @housing.local cr` fixes the issue.   Are we good with merging this if all we have to do is clear the cache to get the missing moderation block working?

**Comment by pyrello** [comment]
> @pyrello what do you make of this solution on that issue? [#3176461: The "extra_field_block:node:recipe:content_moderation_control" was not found](https://www.drupal.org/project/drupal/issues/3176461#comment-14423398)

I tried to figure out how to implement it, but I think it's too vague to be helpful. The problem that person solved is clearly different than the problem we are having. I'm not sure what file he is adding those dependencies to, but if it was a `core.entity_view_display.node.**` file, they should get added automatically.

**Comment by pyrello** [comment]
> It looks like `ddev drush @housing.local cr` fixes the issue. Are we good with merging this if all we have to do is clear the cache to get the missing moderation block working?

Let's do it. Since this is not a production site yet its low risk. If that doesn't fix it, then we'll have to push a different fix.

**Pull request merged**
