### PR TITLE
updating uids to 3.2.1

### PR DESCRIPTION
**Pull request by GaryRidgway**
Updating UIDS to 3.2.1

# To Test

Pull, run `yarn upgrade @uiowa/uids`, then `blt frontend`, then `drush @sandbox.local cr`

test the visual components of this PR https://github.com/uiowa/uids/pull/479 on this page `https://sandbox.local.drupal.uiowa.edu/about/menu-variants`

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Pulling down to test

**Comment by joewhitsitt** [comment]
Don't know if it is because I just tested https://github.com/uiowa/uiowa/pull/3015 but I am getting this:
```
warning Pattern ["@uiowa/uids@uiowa/uids"] is trying to unpack in the same destination "/home/vagrant/.cache/yarn/v6/npm-@uiowa-uids-3.2.1-f225a600d0df08c13bea0bbc94d43aea629d3b2d/node_modules/@uiowa/uids" as pattern ["@uiowa/uids@uiowa/uids#v3.2.1"]. This could result in non-deterministic behavior, skipping.
```

**Comment by richardbporter** [comment]
I always see that. I don't think it causes a problem.

**Comment by joewhitsitt** [comment]
```warning Error running install script for optional dependency: "/var/www/uiowa/node_modules/gifsicle: Command failed.``` though blt frontend was successful

**Comment by joewhitsitt** [comment]
This is what I see which seems different from the uids PR screenshot where there are no border lines:
Screen Shot 2021-02-04 at 11 36 00 AM

**Comment by joewhitsitt** [comment]
>I always see that. I don't think it causes a problem.

Didn't see the warning or gifsicle error on `main` after `yarn cache clean && rm -rf node_modules && composer install && blt frontend`

**Comment by joewhitsitt** [comment]
testing again now that Rick's PR merged.

No warning from https://github.com/uiowa/uiowa/pull/3024#issuecomment-773477896.
Still see the gifsicle warning and extra output https://github.com/uiowa/uiowa/pull/3024#issuecomment-773478877

I see `=> Found "@uiowa/uids@3.2.1"` but still the same styles as the screenshot above.

**Comment by GaryRidgway** [comment]
This is actually a problem in UIDS where i missed a class on a preview template file. gonna fix that, merge in, and then update this PR

**Comment by GaryRidgway** [comment]
@joewhitsitt this is actually the intended styles for now before we redo the horizontal stacked styles. What you are seeing is correct. it was wrong in the display for uids, which has been fixed.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
