### PR TITLE
Feature: UIDS Base updates

### PR DESCRIPTION
**Pull request by pyrello**
This feature provides enhancements to the UIDS Base theme that was added in a previous update.

* Search box implementation
* Sytem for using primary menu region to handle main navigation depending on style of navigation that is chosen
* Updates uiowa.edu config

### CODE REVIEW

**Comment by richardbporter** [comment]
I think the uiowa.edu site just needs a `drush config:export` to match collegiate install/config changes in f62c4f5.

**Comment by pyrello** [comment]
@richardbporter That doesn't quite make sense to me, though. This is branched off of master where that config doesn't yet exist and won't until #1041 gets merged.

**Comment by richardbporter** [comment]
Yea, thats odd. I can't figure out why that build failed.

**Review by joewhitsitt — APPROVED** [review]
reviewed, not tested

**Pull request merged**
