### PR TITLE
Update frontend dependencies to latest.

### LINKED ISSUE #1183: Update frontend dependencies
https://github.com/uiowa/uiowa/network/alerts

This would also clean up some warnings during frontend compiliation.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #1183.

### CODE REVIEW

**Comment by richardbporter** [comment]
Testing this in develop for deploy check.

**Comment by pyrello** [comment]
@richardbporter How do you recommend testing this?

**Comment by richardbporter** [comment]
I would check it out locally and run `blt frontend` and any additional frontend commands you use regularly. Ex. `yarn workspace uids_base gulp` or something similar.

**Review by pyrello — APPROVED** [review]
As far as I can tell this works. I did pull up the homepage site locally and check to see if there were any console errors and there were none.

**Pull request merged**
