### PR TITLE
Superfish menu bugs

### LINKED ISSUE #3454: superfish 3rd level menus show offscreen
# Problem
The Horizontal navigation style will sometimes show 3rd level menu items off-screen when the text is too long.

Screen Shot 2021-05-05 at 9 58 23 AM

Screen Shot 2021-05-05 at 9 58 08 AM

# Steps to reproduce
Examples for reference are https://africanamericanstudies.uiowa.edu/. Under Graduate Programs > Degrees and Certificates.

https://cinematicarts.uiowa.edu
Under Graduate Programs > Degrees and Certificates

### LINKED ISSUE #4276: When <nolink> is used, nested superfish menu links w/ children overlap the dropdown arrow in tablet and smaller breakpoints
# Problem

If a child of a menu link has children (grandchild of top level menu link?) the dropdown arrow overlaps the text in tablet and smaller breakpoints - only happens when `<nolink>` is used

# Steps to reproduce

Go to africanamericanstudies.uiowa.edu or cinematicarts.uiowa.edu and minimize window to tablet breakpoint and/or smaller
- In africanamericanstudies, expand Graduate Programs menu and view Degrees and Certificates link overlapping arrow 

Example: 
Screen Shot 2021-10-06 at 6 30 22 PM

# Proposed solution

### LINKED ISSUE #4279: Navigation links are overlapping the dropdown caret
# Problem
Navigation links are overlapping the dropdown caret on the mobile navigation with certain screen sizes. Similar, but not the same as the other issue I created about the <nolink> menu items. https://github.com/uiowa/uids/issues/588

Screen Shot 2021-09-30 at 4 20 59 PM

Example site
https://nursing.uiowa.edu/

# Proposed Solution
Add right padding to menuparent links

### PR DESCRIPTION
**Pull request by dnkemper**
# How to test

Closes https://github.com/uiowa/uiowa/issues/3454
Closes #4276
Closes https://github.com/uiowa/uiowa/issues/4279

blt dsa sites ( and test menus at different breakpoints to make sure bugs are fixed. 
Example sites: 

- africanamericanstudies.uiowa.edu
- cinematicarts.uiowa.edu
- nursing.uiowa.edu

make sure updates are imported (drush @site-alias.local cim)
`blt frontend`
` drush @site-alias.local cr` `drush @cinematicarts.local cr` `drush @africanamericanstudies.local cr` `drush @nursing.local cr`

Make sure nested menu links aren't cut off at breakpoints - limited max width of units
Hoping to kill two birds with one stone. There's additionally a superfish menu bug where the drop down arrow overlaps the menu link/text in tablet and mobile views. Prod example: image

### CODE REVIEW

**Comment by bspeare** [comment]
@dnkemper I think we only need this for the horizontal option: https://github.com/uiowa/uiowa/pull/4272/files#diff-70d40f0a2e6722ac1e488a7579e52259484e0be1d5b4e312bb270f7429c42571.     The change is not necessary for the toggle option and the mega option will need to be updated when the work on https://github.com/uiowa/uiowa/issues/3273 begins.

**Comment by dnkemper** [comment]
@bspeare that makes sense. On it! Thank you so much!

**Comment by dnkemper** [comment]
@bspeare done!

**Comment by bspeare** [comment]
Pulling down to test.

**Comment by bspeare** [comment]
Seeing this on nursing.uiowa.edu.   Setting this new smaller fixed maximum width of these menus will mean that https://github.com/uiowa/uiowa/issues/4279 will need to be solved for this issue as well:

Screen Shot 2021-10-08 at 8 58 36 AM

If you can find these existing styles in being set in https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/menus/superfish.scss and adjust them to something like: 

```
ul.sf-menu.sf-horiz-menu li li .nolink, 
ul.sf-menu.sf-horiz-menu li li a, 
ul.sf-menu.sf-horiz-menu li li span {
  padding-right: 2rem;
}

.nav--horizontal .sf-accordion.sf-menu.sf-menu.sf-horiz-menu li li a {
  padding-right: 1.5rem;
}

.block-superfish .menu.sf-accordion > li > .sf-depth-1.menuparent {
  padding-right: .5rem;
}
```

**Review by bspeare — APPROVED** [review]
I have tested this on a number of sites at a number of breakpoints.   Thanks for fixing these bugs!

**Comment by dnkemper** [comment]
@bspeare YAY! Thank you so much for your help!

**Pull request merged**
