### PR TITLE
Guest hawkid support (in uiowa_auth)

### LINKED ISSUE #6101: uiowa_auth - guest hawkids are unable to authenticate
# Problem
Guest hawkids don't typically have a member value which seems to cause our uiowa_auth onUserSync() to choke

https://github.com/uiowa/uiowa_auth/blob/main/src/EventSubscriber/SamlauthSubscriber.php#L106

# Steps to reproduce
```
drupal-watchdog web-33202 Jan 17 21:52:49 web-33202 uiowa[20063]: https://default.prod.drupal.uiowa.edu|1673992369|php|198.211.131.218|https://default.prod.drupal.uiowa.edu/saml/acs|https://idp.uiowa.edu/|0||TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in in_array() (line 106 of /mnt/www/html/uiowa/docroot/modules/uiowa/uiowa_auth/src/EventSubscriber/SamlauthSubscriber.php) #0 /mnt/www/html/uiowa/docroot/modules/uiowa/uiowa_auth/src/EventSubscriber/SamlauthSubscriber.php(106): in_array('CN=Drupal-Devel...', NULL)
drupal-watchdog web-33202 Jan 17 21:52:49 web-33202 uiowa[20063]: https://default.prod.drupal.uiowa.edu|1673992369|php|198.211.131.218|https://default.prod.drupal.uiowa.edu/saml/acs|https://idp.uiowa.edu/|0||Warning: Undefined array key "urn:oid:2.5.4.31" in Drupal\uiowa_auth\EventSubscriber\SamlauthSubscriber->onUserSync() (line 106 of /mnt/www/html/uiowa/docroot/modules/uiowa/uiowa_auth/src/EventSubscriber/SamlauthSubscriber.php) #0 /mnt/www/html/uiowa/docroot/core/includes/bootstrap.inc(347): _drupal_error_handler_real(2, 'Undefined array...', '/mnt/www/html/u...', 106)
drupal-watchdog web-33202 Jan 17 21:52:49 web-33202 uiowa[20063]: https://default.prod.drupal.uiowa.edu|1673992369|samlauth|198.211.131.218|https://default.prod.drupal.uiowa.edu/saml/acs|https://idp.uiowa.edu/|0||Existing user dworrll (61) was newly matched to SAML login attributes; linking user and logging in. request_id="v-48f0945a-96b1-11ed-aa6b-83e1de507c21"
drupal-watchdog web-33202 Jan 17 21:52:49 web-33202 uiowa[20063]: https://default.prod.drupal.uiowa.edu|1673992369|samlauth|198.211.131.218|https://default.prod.drupal.uiowa.edu/saml/acs|https://idp.uiowa.edu/|0||No matching local users found for unique SAML ID dworrll.
```

# Proposed solution
- Create a PR in uiowa_auth to gracefully fallback if `$attributes[$mapping['attr']]` is NULL.
- Create a PR in uiowa that references the uiowa_auth PR and deploy to DEV
- Test authentication and role mapping of guest hawkid, normal hawkid (not web team) and web team hawkid that has not signed in yet to receive admin role.

### PR DESCRIPTION
**Pull request by joewhitsitt**
https://github.com/uiowa/uiowa_auth/pull/8
Resolves https://github.com/uiowa/uiowa/issues/6101

Guest hawkids don't usually have member/group information. Existing functionality assumed it would always return an array. This PR by way of https://github.com/uiowa/uiowa_auth add is_array() checks around multiple points in the code for user sync, login, and linking. This will maintain the checks against current roles and whether other roles should be applied (e.g. Web team being assigned the admin role).

# How to test

- This has been pushed out to DEV for testing on default.dev.drupal.uiowa.edu.
- Note that guest hawkid [dworrll](https://default.dev.drupal.uiowa.edu/user/61) was able to login and has the editor role only which was added on account creation.
- Login as user 1 and remove roles from your hawkid. `ddev drush @default.dev uli /admin/people`
- In an anonymous browser session, login with your hawkid. Web team should get administrator role applied. Users like Michael and Megan should get the webmaster role. Mara (doesn't have an account on default.dev nor role mappings to admin/webmaster) should not be able to login.
- Not sure how it was tested originally, but ideally, if someone loses the necessary group, their auto-assigned role should be revoked. We could draw straws to temporarily drop someone via https://iam.uiowa.edu/access/

# Post Deploy

- Follow up with paklee email/ticket.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
sending out to DEV to intersect with our other problem (Travis)...

**Comment by joewhitsitt** [comment]
waiting till tomorrow to manually deploy to DEV based on https://app.travis-ci.com/github/uiowa/uiowa/builds/259782398

**Comment by joewhitsitt** [comment]
working on a manual deployment to DEV

**Comment by joewhitsitt** [comment]
This did not work. I think it returned the same error.

**Comment by joewhitsitt** [comment]
Waiting on approval/merge of https://github.com/uiowa/uiowa_auth/pull/8 to finalize this PR

**Comment by cory-skeers** [comment]
Taking a looksie.

**Comment by cory-skeers** [comment]
> * Not sure how it was tested originally, but ideally, if someone loses the necessary group, their auto-assigned role should be revoked. We could draw straws to temporarily drop someone via https://iam.uiowa.edu/access/

Do we want to test this part out..? I could volunteer as tribute 😬

**Comment by cory-skeers** [comment]
Thanks @briand44!
Was able to confirm that when logging in after the auto-assigned role was revoked, I no longer maintained the role
image
The reverse also worked: logging in after having roles removed on the site, but having an auto-assigned role, I was given the administrator role.

**Review by cory-skeers — APPROVED** [review]
Last thing could be to check a non-admin user role's addition (@mkyoder or @mjoneill) in order to be thorough, but it worked for my own roles, and I don't see anything in the code that would suggest it could work differently for other roles.

**Comment by joewhitsitt** [comment]
Thanks @cory-skeers and @briand44. Yeah, I think that test is good enough. The same logic is used for webmasters or other AD mappings.

I just tested completely removing my account and getting automatically added/assigned which I think was other potential gap.

Screen Shot 2023-01-24 at 11 01 57 AM

**Pull request merged**
