### PR TITLE
Mirroring recent updates to UIDS

### LINKED ISSUE #1780: Update button @extends in uids_base to use @include instead.
# Problem

Button @extends in UIDS were creating an issue with selector chaining and cascading order within components.   This PR (https://github.com/uiowa/uids/pull/240) updates the button styles to be argument-less mixins to avoid issues. 

# Proposed Solution

Update usage of `@extend %bttn` to `@include bttn` in `uids_base` with a new 2.0.4 UIDS release.

### LINKED ISSUE #1804: As a developer, I can deploy a site that uses the latest UIDS 3.0 release in uids_base
- [x] Create 3.0 Release for UIDS and update `uids_base` to use 3.0 release. 
- [x] Refactor `uids_base` to use new Iowa Bar from UIDS: https://uids.brand.uiowa.edu/components/detail/prototype-iowa-bar--full.html
- [x] Refactor `uids_base` to use newly refactored footer. 
- [x] Verify that new bar works in IE11. 
- [x] https://github.com/uiowa/uiowa/issues/1780 Adjust button extends (in uiowa_paragraphs_background_overrides).
- [x] https://github.com/uiowa/uids/pull/253 Add badge styles
- [x] https://github.com/uiowa/uids/pull/250 Add new Slider to `uids_base`

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #1780 
Resolves #1804 

# How to test

- Verify that `blt frontend` can run without errors.
- Initial testing should be done against the following sites to ensure there are no visual or functional regressions:
  - [ ] uiowa.edu
  - [ ] brand.uiowa.edu
  - [ ] cogscilang.grad.uiowa.edu
  - [ ] icsa.uiowa.edu
  - [ ] policy.clas.uiowa.edu

## Site Header
- Verify that site header markup is similar to: https://uids.brand.uiowa.edu/components/detail/iowa-bar--site_name_below.html.
- Test at all breakpoints. 
- Test on BrowserStack ie11 if you have access. 
- Test IOWA bar stickiness (or lack thereof). Test the scroll functionality down the page, scroll up and test the menu and search options mid-scroll and verify that there are no regressions. 

## Site Header Toggle
- In a private browser, verify that new `iowa-bar.js` is being applied to `.o-canvas__drawer` to set top position based on scroll position in browser.

## Site Footer
- Test that footer and footer logo appear the same without visual regressions (https://github.com/uiowa/uiowa/issues/1811)  
- Test footer with parent organization and without. 

## In-page menus
Verify that the in-page menu on https://uiowa.local.drupal.uiowa.edu/student-life have no visual regressions. Check a mobile breakpoint.

## Button Styles 
- Verify that #1780 has been implemented.  

## Contact form
Check that there are no visual regression on https://uiowa.local.drupal.uiowa.edu/contact

## Visual Regression Fix
- Verify that extra spacing seen in the stat grid on https://uiowa.edu/ is gone (caused by https://github.com/uiowa/uiowa/issues/1810)

## Layout Builder Style Changes
- Check that the background pattern for the events header and the stats section of the home page are in place: https://uiowa.local.drupal.uiowa.edu/
- Inspect the HTML of those areas to confirm that the background is being applied using a `bg--*` class instead of a `uids-*` class.
- Check that the stats blocks have `element--flex-center` alignment class applied to them and that they look like they do in production.

### CODE REVIEW

**Comment by bspeare** [comment]
Checklist of items are listed here https://github.com/uiowa/uiowa/issues/1804.

**Comment by joewhitsitt** [comment]
pulling down for testing on the sites listed above.

**Comment by pyrello** [comment]
Thanks, @joewhitsitt!

**Comment by pyrello** [comment]
I have tested against the 5 sites above and this looks good to me.

Anyone else who is testing this, if you want to get a jump start on the follow-up testing that goes along on this, please see #1901.

**Comment by joewhitsitt** [comment]
I have looked at the test items listed in this PR for brand (switch the header and added parent org) and the homepage with no noticeable issues. I will follow-up with the other sites tomorrow and start looking at #1901 as well.

**Review by joewhitsitt — APPROVED** [review]
Poked around brand, uiowa.edu and policy.clas for the test criteria in this PR.

**Pull request merged**
