### PR TITLE
Article content reference field

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #5575 

# Todo
- [x] stacked cards - taking this opportunity to refactor how classes are implemented for these? https://github.com/uiowa/uiowa/pull/5623#issuecomment-1230811205
- [x] hr split
- [x] iisc https://github.com/uiowa/uiowa/issues/5657
- [x] sppa

# How to test
- Review the code.  Any suggestions to make the machine names better like `card_grid` and `related_manually_referenced_content`?  Is there any extra code that could be removed?
- `blt frontend`
- `ddev blt ds --site=sandbox.uiowa.edu`

## Test the update hook
- Go to https://sandbox.uiowa.ddev.site/admin/config/sitenow/uiowa-articles and verify the "do not display" option is gone from "Display related content" and that this site is set to "Grouped by tag".  Adjust it to display "Manually referenced content" and save. 
- Test on another site that may have had "Do not display" set. 

## Test the functionality
- Go to https://sandbox.uiowa.ddev.site/node/546/edit and find the "Related content" field in the sidebar and select some content to reference.  Read the help text and provide suggestions to help make the text better. 
- Edit or create a new article and use the new "Related Content" field under the "Relationships" tab. 
- A related content section should display a grid of cards at the bottom of the article in the "stacked" card design. 

## Test the splits
- HR - `ddev blt ds --site=hr.uiowa.edu` - it should work on v2 but just look different https://github.com/uiowa/uiowa/pull/5623#issuecomment-1238383764
- IISC - `ddev blt ds --site=iisc.uiowa.edu` it should not work here
- SPPA -`ddev blt ds --site=sppa.uiowa.edu`-  it should work!

### CODE REVIEW

**Comment by bspeare** [comment]
We are setting the card defaults for the teaser view mode at https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.theme#L308-L312.  Can we unset those and provide new defaults for article teasers using this reference field?  Or, do we need a card view mode?

**Comment by joewhitsitt** [comment]
Don't we need to keep that around until v2 goes away? Not sure I understand the ramifications of unsetting those there. Would that be a lot of teaser template updates?

**Comment by joewhitsitt** [comment]
Input overflow
Screen Shot 2022-08-30 at 6 50 56 AM

Grid stacked enclosed with hidden descriptions using existing logic.
Screen Shot 2022-08-30 at 6 51 07 AM

**Comment by joewhitsitt** [comment]
pulling down to look at the update hook and view

**Comment by joewhitsitt** [comment]
Looks like when this was first installed (sitenow_articles_update_9301), it was set to an option that doesn't exist which left things unset for many sites. It now accounts for do_not_display as well as unset.

**Comment by joewhitsitt** [comment]
i'd like to pretend I understand how Views works but I don't. required the relationship, removed the contextual filter and switched the render to content. 🤷 

Update: nevermind. I must have broke something

**Comment by bspeare** [comment]
@joewhitsitt what needs to be updated for splits like (https://github.com/uiowa/uiowa/blob/main/config/sites/hr.uiowa.edu/config_split.config_split.site.yml#L22) or default content?

**Comment by joewhitsitt** [comment]
default_content is probably nothing since we aren't setting a default value.

for the HR split, I think it would be removing the storage base field from the split and adding a complete split item for the field instance located on page. making sure the storage base file is removed from git.

**Comment by bspeare** [comment]
It looks like https://github.com/uiowa/uiowa/blob/9e164473d42499b22e61755361d8279014c28fe7/docroot/themes/custom/uids_base/uids_base.theme#L305-L311 is not working on the `sppa` site.

**Comment by joewhitsitt** [comment]
taking a look at SPPA

**Comment by bspeare** [comment]
This feature does work for V2 sites but has a different visual display - are we good with that?

Screen Shot 2022-09-06 at 11 26 54 AM

**Comment by bspeare** [comment]
I think this should be ready to test.   @joewhitsitt anything else you want to add to the testing instructions?

**Comment by joewhitsitt** [comment]
I think the test instructions are good

**Comment by makurj** [comment]
Pulling down to test.

**Comment by makurj** [comment]
> Any suggestions to make the machine names better like `card_grid` and `related_manually_referenced_content`?

 I kinda like these as they are very clear terms.

**Comment by makurj** [comment]
I'm okay with: 

> Reference similar content. Manage the display of these items at the SiteNow Articles [page](https://sandbox.uiowa.ddev.site/admin/config/sitenow/uiowa-articles).

If needed, we could change "similar" to "related" but as this is under "Related Content", that would be redundant. We could also do "Reference other articles. Manage the display of these items at the SiteNow Articles."

**Comment by makurj** [comment]
To confirm, we are now setting “Display related content” for all sites to "manually referenced"? For ones that were on “Do not display”, this shouldn’t make a difference unless they go into each article and enter some content to reference, correct?

**Comment by briand44** [comment]
>To confirm, we are now setting “Display related content” for all sites to "manually referenced"?

We should be setting "manually referenced" as the default going forward and updating existing sites that have "Do not display" set. Sites that are displaying tags wouldn't be changed.

**Comment by joewhitsitt** [comment]
>Sites that are displaying tags wouldn't be changed.

Correct.

**Comment by makurj** [comment]
For IISC, I see the "Related Content" field in the sidebar on articles but when I enter some text, it's not referencing the article. Is that what is meant by "it should not work here" in the test instructions?

**Comment by briand44** [comment]
https://github.com/uiowa/uiowa/issues/5657

**Comment by makurj** [comment]
Everything checks out.

**Review by makurj — APPROVED** [review]

**Comment by bspeare** [comment]
Does this need the off hours deployment tag?

**Comment by joewhitsitt** [comment]
Created a docs issue https://github.com/uiowa/uiowa/issues/5665

**Comment by pyrello** [comment]
> Does this need the off hours deployment tag?

I reviewed the code from this perspective and I didn't see anything concerning in this regard. It doesn't:
- Introduce new dependencies which are required by code updates
- Update existing dependencies with classes being renamed or moved
- Move existing template files

The config for the view won't exist until after config import happens, but won't be called by anything until the update hook runs. There is maybe the possibility of a very short outage based on this. I think ideally, we would manually import the views config during the update hook so that it is there when the update hook finishes running and sites that did not have related content turned on get switched to using the related content field by default. However, I'm not sure the length of the possible outage necessarily warrants the additional effort.

**Comment by cory-skeers** [comment]
> I think ideally, we would manually import the views config during the update hook so that it is there when the update hook finishes running...

Even if we don't go back and add it here, that's a good point, and this is a good consideration going forward for future update hooks. Similar 'defensive coding' type practice.

**Pull request merged**
