### PR TITLE
Update ctools, introduce exposed filters to list blocks

### LINKED ISSUE #3804: Add exposed filters to views block display
# Story

As a content editor, I want to be able to expose filters on my view blocks.

# Proposed solution

- [x] ~Help get MR at https://www.drupal.org/project/ctools/issues/2657060 to a fully working state.~ MR got merged and is part of the more recent version of `ctools`.
- [ ] Update to most recent version of `ctools` module.
- [x] Refactor code that transform the people type selector based on updates.
- [x] Add patch to account for issue with multiple exposed forms in blocks for the same views display, possibly the one at this issue: https://www.drupal.org/project/drupal/issues/3163299
- [x] Account for pager and offset options showing up in exposed filter form.
- [ ] Refactor code to work with updated version of `ctools` module.
- [ ] Update hook to convert existing configuration to the new format.

<details>
<summary>Original proposed solution</summary>
Modify the `Drupal\layout_builder_custom\Plugin\Display\ListBlock` class in the following ways:
- For each filter that can be set on the block settings form, add a checkbox to the form to allow the user to expose the filter. Name the checkboxes fields `$filter_id . '_expose`.
- Add `'#states'` to each filter field to disable the field if the corresponding checkbox is checked.
- Adjust the logic in the `blockSubmit()` method to check for an instances where the above fields are set to TRUE and set a new option value on the block called `expose_form` to TRUE if any of them are. Here is a quick example I came up with:
  ```
  $expose_form = FALSE;
  $exposed_inputs = $form_state->getValue([
    'override',
    'exposed_filters',
  ]);
  $exposed_filter_values = [];
  foreach ($exposed_inputs as $input) {
    // if input ends with _expose, $expose_form = TRUE;
    // else add to $input to $exposed_filter_values.
  }
  $block->setConfigurationValue('exposed_filter_values', $exposed_filter_values);
  $block->setConfigurationValue('expose_form', $expose_form);
  ```
- In the `preBlockBuild()` method, check the `expose_form` configuration value from the block and set an option on the display handler (`$this->view->display_handler->setOption('expose_form', TRUE)`) if this value is set to TRUE.
- Adjust the `displaysExposed()` method to check the display handler option and return `TRUE` if any filters are exposed.
- An update hook will be need to update all `layout_builder__layout` field instances to add the `expose_form` default value of FALSE to existing block configurations. This is a serialized field and will need to be deserialized to update it, then re-serialized to store it. There are several examples of this in previous update hook. Just ask @cory-skeers if you have any questions :)

**OR**

Alter the SiteNow People module to allow for displaying individual pages for people types as such:
- Change the configuration settings to allow for showing all people (the current option) and checkboxes for each person type to display a similar page.
- Adjust all the settings to be options for each possible person listing.
- Adjust the custom code that handles saving configuration and display the page to handle multiple pages.
</details>

### PR DESCRIPTION
**Pull request by pyrello**
Replaces #4479 and resolves #3804.

# How to test
```
 ddev composer install && ddev blt ds --site sandbox.uiowa.edu && ddev drush @sandbox.local uli people-directory
```
## Article and people list blocks
* View some existing article and people lists block and compare the settings with the production sandbox site to make sure that the update hook worked as expected.
* Place blocks on a page and try changing the following settings, saving the block, saving the layout, and viewing the page.
  * Test setting headline or not
  * Test changing items to display
  * Test changing offset
  * Test setting pager
  * Confirm that the 3 settings above work predictably with one another
  * Test changing sort options
  * Test hiding fields.
  * Test adding a more link, setting a custom path, and setting custom text
  * Test setting filter values
  * Test exposing filters without setting a value
  * Test exposing filters with a value set
  * Test setting multiple filters at the same time
  * Test setting multiple filters to different variations of exposing the filter and not
  * Test that exposed filter and pager for one block do not affect any other views blocks on the same page of either the same type or a different types
  * Confirm that "Items per page" and "Offset" do not show up in exposed filters

### People list block
* When setting the "Person type" filter, it should limit the options display in "Person type status" drop-down to the same option.

## Event list block
```
ddev drush @sandbox.local config-split:activate event -y && ddev drush @sandbox.local cim
```
* Create some local events.
* Run through the above tests.

### CODE REVIEW

**Comment by pyrello** [comment]
Copied over the testing instructions for #4479. Need to review them before this can be marked ready.

**Comment by pyrello** [comment]
Dropping this here because it's useful for testing update hooks when you need to use xdebug:
`ddev drush sql:sync @sandbox.prod @sandbox.local -y && ddev drush @sandbox.local cim -y && ddev drush @sandbox.local cim -y && ddev drush @sandbox.local updb`

**Comment by joewhitsitt** [comment]
Past @pyrello told me to add this here so future Sean doesn't forget: https://github.com/uiowa/uiowa/issues/3804#issuecomment-1351674669

**Comment by pyrello** [comment]
Removing from the project board, but keeping this for future reference.

**Comment by pyrello** [comment]
I fixed the merge conflicts, updated the version of ctools to ^4.0, and did a little refactoring to the update hook to get the existing https://sandbox.uiowa.ddev.site/debug-one-people-list-block working. There is still more to do, but it seems like this is still a usable starting point for working on #3804.

**Comment by joewhitsitt** [comment]
Is this still worth keeping around since https://github.com/uiowa/uiowa/issues/6578 ?

**Comment by pyrello** [comment]
> Is this still worth keeping around since #6578 ?

I've just thought of an old PR that has been around for a long time that could probably now be closed and I got to comment and close it, only to discover that @joewhitsitt got here a day ahead of me.

**Pull request closed without merging**
