### PR TITLE
[Facilities] Alerts on building pages

### LINKED ISSUE #6689: Display Facilities alerts on buildings
# Story

As a site owner for Facilities, I would like to see all active alerts that relate to a building displayed on that building page so that users viewing a building page can be aware of alerts for that building.

# Additional Info

Alert should link to full alert node

Initial mockup https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup

Also dependent upon work done in https://github.com/uiowa/uids/issues/770

# Proposed Solution

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6689. 

# How to test

```
ddev composer install && ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli /building/0374
```
- Code review
- Verify that the alert appears on the Carver building page
- Verify that the alert will disappear if end date is before today
- Verify that alert only appears on reference building page
- Review View settings and check for any settings that might be missing
- The styles will look messed up, further style updates will need to be made in https://github.com/uiowa/uiowa/issues/6790

## Additional cache testing

- Temporarily change the view from `today` to `now` for the date end filter
- Change the alert to expire within a few minutes. In an anonymous browser, load the carver building page and get it to cache.
- After time expires, refresh the anonymous window and see that the alert is still there.
- Run cron, the alert within the anonymous window on refresh should disappear. If not, you may need to wait for a rolling full hour to run cron again to have the alert disappear. Honestly don't know if the state timer is triggered on `blt ds` or is carried from PROD which sets the hour long count.

## Schemadotorg testing

- `ddev composer install` and try syncing known schemadotorg sites (facilities, classrooms, 91st meridian, iswf, sandbox (person)) to see if there are any import errors and to see if json+ld output is still working as expected.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
>Verify that the alert will disappear if end date is before today

Editing/saving the node by changing the date works, but I wonder if we will run into the same issue as https://github.com/uiowa/uiowa/issues/6788

**Comment by joewhitsitt** [comment]
Using this opportunity to evaluate `views_custom_cache_tag` with time:hourly to see if it will help here.

**Comment by joewhitsitt** [comment]
>Using this opportunity to evaluate views_custom_cache_tag with time:hourly to see if it will help here.

I temporarily changed `today` to `now` on the end date filter to make testing more speedy. Adding the cache tag through this module view config and running cron after the alert expires seems to work as expected.

**Comment by joewhitsitt** [comment]
```
        modified:   composer.json
	modified:   composer.lock
	modified:   config/default/config_split.config_split.event.yml
	modified:   config/default/config_split.config_split.sitenow_alerts.yml
	modified:   config/features/event/views.view.events.yml
	modified:   config/features/event/views.view.events_list_block.yml
	modified:   config/features/sitenow_alerts/views.view.alerts_list_block.yml
	modified:   config/sites/facilities.uiowa.edu/views.view.alerts_building_block.yml
	modified:   docroot/modules/custom/uiowa_core/uiowa_core.module
```

@bspeare do you mind if I push this up? Should hopefully resolve https://github.com/uiowa/uiowa/issues/6788 as well.

Adds the module to composer, adds the module to the two feature splits, reconfigures the views to use custom tag and sets it with time:hourly. Adjusted the current cron job to also do a time:daily check based on the referenced blog post, but don't have it configured anywhere.

**Comment by bspeare** [comment]
@joewhitsitt please do!

**Review by joewhitsitt — APPROVED** [review]
I am now biased on this one, but I approve of everything I tested and suggest we get some prod testing with the caching adjustments.

**Comment by joewhitsitt** [comment]
Added additional test instructions if anyone else wants to poke at this.

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
> Verify that the alert will disappear if end date is before today

I can confirm this works if I change the end date. However, after changing it back, the alert does not reappear on the building page.

**Comment by joewhitsitt** [comment]
>However, after changing it back, the alert does not reappear on the building page.

Can you elaborate a bit? Change the date back and saved the alert node? Was this before or after you made the `today` -> `now` change?

**Comment by pyrello** [comment]
> > However, after changing it back, the alert does not reappear on the building page.
> 
> Can you elaborate a bit? Change the date back and saved the alert node? Was this before or after you made the `today` -> `now` change?

I have not changed any views settings. I changed the alert end date to yesterday to test that the alert would disappear from the building page. It did. Then I changed the alert end date to tomorrow to test that it would reappear and it did not.

**Comment by pyrello** [comment]
I also just tested creating a new alert for a building page that I had already viewed. The alert did not show up on the page until after I cleared cache. I suspect that we need to figure out how to add cache tags for alerts the associated building page render array.

**Comment by joewhitsitt** [comment]
Hmm. I'd like to pull this down again, but this seems similar to pharmacy where we had to create a node:person cache tag and add it to a block for things to bubble up based on where it was placed. `pharmacy_core_node_delete`, `pharmacy_core_node_presave` and docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/src/Plugin/Block/PalliativeGradMapBlock.php

**Comment by bspeare** [comment]
Even after turning off the caching on the view, the alert won't show up in Sean's testing scenario.

**Comment by joewhitsitt** [comment]
>This module replaces the hardcoded cache tag with a form that allows developers to set different cache tags based on configuration of the view

Looking deeper into what this module does, it removes the default caching behavior of node_list cache tag. So if we are using this, we need to add entity specific tags to make up for it in addition to our time based ones. I'll push up a change that I think will work.

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/drupal/issues/2145751

This was added after we made our own node type specific ones. Could help us reduce some code (pharmacy, admissions)

**Comment by bspeare** [comment]
Tested this again and the alert is now showing after changing the date to before today, saving, then changing it back to after today and the alert is showing up in the alert list block and node view block.  Do we need any further testing here with events?

**Comment by joewhitsitt** [comment]
>Do we need any further testing here with events?

We could..

I think the time:hourly could be skipped but confirming that changing event dates works for things like events by person content or event series on Admissions.

**Comment by bspeare** [comment]
Trying to fix the `composer.lock` conflict by merging and updating the lock file and getting this error:

```
  Problem 1
    - Root composer.json requires drupal/schemadotorg == dev-1.0.x -> satisfiable by drupal/schemadotorg[dev-1.0.x].
    - drupal/schemadotorg dev-1.0.x requires drupal/core ^10.1 -> found drupal/core[10.1.0-alpha1, ..., 10.1.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by joewhitsitt** [comment]
Ugh, looks like we are using a dev version that just got tweaked to be 10+ only. Might have to go back and pin this to an earlier dev commit until we upgrade to d10.

https://www.drupal.org/project/schemadotorg/releases/1.0.0-alpha5

**Comment by bspeare** [comment]
I'm fine with merging this unless anyone else wants to further test this.

**Comment by joewhitsitt** [comment]
well, i completely borked this with that schemadotorg twist. trying to figure it out before i need to go, but getting a WSOD locally...

update: we either need to try out earlier alpha versions or we need to go back and pin a dev commit before all of the config changes happen. we got bit by not using a stable release in PROD... i can look into this more on monday.

**Comment by joewhitsitt** [comment]
trying to sort this out

**Comment by joewhitsitt** [comment]
>Schemadotorg testing
ddev composer install and try syncing known schemadotorg sites (facilities, classrooms, 91st meridian, iswf, sandbox (person)) to see if there are any import errors and to see if json+ld output is still working as expected.

Yay! Successful build. I am running through this locally.

**Comment by joewhitsitt** [comment]
This worked but I think we need a follow-up task as the module has new things like Address submodule to support event location, etc. and we will need to work to re-map some things.

https://github.com/uiowa/uiowa/issues/6825

**Pull request merged**
