### PR TITLE
Grad migration follow-up

### LINKED ISSUE #2920: Build Grad article redirect migration
# Motivation

The URL scheme for articles changes slightly from the D7 to D8 sites, so a redirect is necessary.

# Proposed solution

The redirect can probably be copied and adapted from one of the SROP content type redirects.

### PR DESCRIPTION
**Pull request by pyrello**
A few changes to allow for more complete migration. This whole thing is being merged mostly so that we can have a relatively complete example to follow for future migrations.

Resolves #2920 

# How to test

File review is sufficient.

### CODE REVIEW

**Comment by pyrello** [comment]
Mentor image field is not downloading, though I am able to see the image when I look at the provided URL, such as https://www.grad.uiowa.edu/sites/gc/files/srop_attached_images/Juan%20Pablo%20Hourcade.jpg. What is printed in the output is the un-urlencoded version: https://www.grad.uiowa.edu/sites/gc/files/srop_attached_images/Juan Pablo Hourcade.jpg. Not sure if that makes a difference.

**Comment by pyrello** [comment]
It looks like most of the mentor image field items are actually getting downloaded correctly. So far, it is actually just the example above that is breaking.

**Comment by pyrello** [comment]
Running the full migration reveals this is only affecting 3 images. I have made note of them and will manually fix them afterwards. On to testing the scholar migration!

**Comment by pyrello** [comment]
I have this all to the point where I am satisfied with the results. I'm going to run these migrations now.

**Review by joewhitsitt — APPROVED** [review]
Based on the test criteria, it looks like everything is spaced correctly... I might not be the right approval on this though.

**Comment by pyrello** [comment]
I'm putting this back into draft and I'm going to use it to handle #2920.

**Comment by pyrello** [comment]
Closes #2920

**Pull request merged**
