### PR TITLE
Restyled RSS link to use a modified button style

### PR DESCRIPTION
**Pull request by quamsta**
Addresses #4695 and #4435

[See "Idea 1" on #4695 ](https://github.com/uiowa/uiowa/issues/4695#issuecomment-1022286910)

Screen Shot 2022-01-28 at 9 32 39 AM

@bspeare -- I had to adjust the button styles a little bit just to keep this button aligned with the content, consequently it loses its outline on hover and its left/right padding. Feel free to modify if needed.

# How to test

- Run `blt frontend`
- Check pages/views where the the feed_icons template is placed, e.g., taxonomy terms, article pages, etc.

### CODE REVIEW

**Comment by pyrello** [comment]
Related: https://www.drupal.org/project/drupal/issues/3261212

**Comment by bspeare** [comment]
Here's the before and after screenshot from Percy for those interested: 

Screen Shot 2022-01-28 at 4 04 08 PM

**Comment by mark-bennett-uiowa** [comment]
I like it! Nice job all.

**Review by bspeare — APPROVED** [review]
Nice changes!  Thanks @quamsta.

**Comment by quamsta** [comment]
Thanks everyone for your help, consideration and for cleaning up the look-and-feel a couple things I left behind, @bspeare. Appreciate it.

**Pull request merged**
