### PR TITLE
[IWP] Media Gallery

### LINKED ISSUE #7794: IWP Media Gallery
# Story

As an IWP site owner, I would like to have a searchable and filterable media gallery so that visitors to our site can easily find our videos, podcasts and documents.

# Additional Info

Current site example https://iwp.uiowa.edu/archives/media-gallery

Current site is not well organized, not promoted well and has a mess of tags.

Need ability to embed YouTube videos, link to external podcasts (https://libsyn.com/) and include some documents (PDFs).

Related to documents:
>The two anthologies linked on this page would be examples: https://iwp.uiowa.edu/book-page/2022-si-session-info
> 
>I don’t think we need to embed them in the page itself (although I am persuadable on that point). I think just linking to the PDFs would be enough.

**Filters**

Ability to search by title/description and possibly year.
Filter by type (video/audio/document)
Filter by Program (Fall Residency, Between the Lines, etc.)
Filter by Country - Can use existing Country taxonomy created for writer bios
Filter by Genre
Filter by Year? - They didn't think they need this filter if search by year was possible but could be nice to have.

**Fields**

Title
Type - single, (Video, Audio, Document)
Media field - allow video embeds, documents?
Body/Description
Link - ability to link to audio podcast on external site or possibly YouTube channel, etc.
Image - Could be used to in gallery display for audio files
Program - Possibly taxonomy (Fall Residency, Between the Lines)
Country - existing vocabulary - allow multiples
Genre - possibly taxonomy
Year? - possibly taxonomy if we want to allow filtering by year. Lots of options here

Probably don't need to link to any taxonomies and probably could rabbit hole (just my assumptions).

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7794 

# How to test

```
ddev blt ds --site=iwp.uiowa.edu && ddev drush @iwp.local uli /admin/structure/taxonomy/manage/writer_bio_countries/add
```
Add some countries
Also add some terms to the Genre taxonomy

Add a few _Resource_ nodes
Add a _Site Custom::Resource List_ block to a _Page_
Test the filters (note: the resources should appear as cards and pull the _Featured image_ as the card image).
The Search filter should search against the title, body, summary, and year (important, as searching against the year is required in order to not create a separate filter for it)

Check the content type creation best practices a la https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/Content%20type%20creation%20notes/Content%20type%20creation%20notes.aspx

Displays are not themed at this point, and will be themed as part of a later slice.

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
> Also add some terms to the Genre taxonomy

Not seeing a Genre vocab:
Screenshot 2024-06-21 at 11 02 10 AM

**Comment by pyrello** [comment]
> > Also add some terms to the Genre taxonomy
> 
> Not seeing a Genre vocab: Screenshot 2024-06-21 at 11 02 10 AM

Sorry. I forgot to check out the branch :|

**Comment by cory-skeers** [comment]
> Sorry. I forgot to check out the branch :|

When starting to check into this, I realized I'd never set up the perms for the taxonomy, so it still led to a good fix!

**Comment by pyrello** [comment]
The `Type` field feels a little clunky. I get why it needs to be there for allowing that type of filtering, but the disconnect from and redundancy of the media entity type feels like a recipe for things going wrong later.

**Review by pyrello — APPROVED** [review]
Not totally sure about the `Type` field but I don't have a better idea of how to accomplish the feature its needed for other than letting the media entity types flow through to views filter. Can potentially be addressed in a future update or we can leave it as it is.

**Pull request merged**
