### PR TITLE
[CCOM] Articles migration

### PR DESCRIPTION
**Pull request by cory-skeers**
# How to test

Sync a CCOM site in DevDesktop

```
ddev blt ds --site=default && ddev drush @default.local config-split:activate ccom_migrate -y && ddev drush @default.local uli /admin/config/sitenow/sitenow-migrate
```

Complete the form following the help text, including the Public Files Path field with the corresponding CCOM listing (such as `sites/medicine.uiowa.edu.pathology/files`)

`ddev drush @default.local ms`
Check that, among others, the `ccom_article` and `ccom_article_redirects` migrations have been registered.

`ddev drush @default.local mim ccom_article`
and, after
`ddev drush @default.local mim ccom_article_redirects`

Note: the `d7_files` migration can be run prior to these, but is not necessary.

I haven't run into a situation where it's needed for the size of migrations here, but you can use the `--limit=X` flag to migrate only `X` number of items at a time.

If a node being migrated had metatag info, you should see a terminal notice like:
image
You can also check the `migrate_message_ccom_article` table for any logs, including metatag info not brought over.

The full field mappings can be found at https://github.com/uiowa/uiowa/issues/6640#issuecomment-1775833696. 

Spot check articles, and look for anything strange or out of place.

### CODE REVIEW

**Comment by bspeare** [comment]
Testing this out.

**Comment by bspeare** [comment]
@cory-skeers what do you recommend for the Base URL if I am trying to migrate pathology?

**Comment by cory-skeers** [comment]
> @cory-skeers what do you recommend for the Base URL if I am trying to migrate pathology?

Base URL https://medicine.uiowa.edu/pathology and public files path sites/medicine.uiowa.edu.pathology/files

**Comment by bspeare** [comment]
Thanks @cory-skeers.  I have it set to that and when I try to run the file migration I get `Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'd7_file'` when there is a total of  895 items listed.

**Comment by cory-skeers** [comment]
> Thanks @cory-skeers. I have it set to that and when I try to run the file migration I get `Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'd7_file'` when there is a total of 895 items listed.

Hrm...I just tried with a fresh sync and it's working for me.

Can you check and see if there's anything in the `migrate_message_d7_file` table in the database?

**Comment by bspeare** [comment]
`migrate_message_d7_file` is empty.   Maybe just a local glitch?

**Comment by cory-skeers** [comment]
> `migrate_message_d7_file` is empty. Maybe just a local glitch?

That's what I'm thinking (hoping). There are some cases where a file might not be brought over, but they should all log a message, and should still have ended up being marked as processed or errored, depending on where in it the problem occurred.

If you're getting the correct count that means the d7 database and the connection to it are all working correctly... 🤷

**Comment by bspeare** [comment]
Screenshot 2023-11-08 at 9 09 03 AM

Noticed this on https://default.uiowa.ddev.site/news/2015/09/richard-g-lynch-md-award-pathology-winners, so I added https://github.com/uiowa/uiowa/pull/7090/commits/02b1d923e19b600217c79f1cf92a36efb08f6cdc.

**Comment by bspeare** [comment]
Noticing https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research-0 (links to https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research) converts to an empty article page: https://default.uiowa.ddev.site/news/2023/10/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-0 and seeing a lot of others like that.

**Comment by cory-skeers** [comment]
> Noticing https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research-0 (links to https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research) converts to an empty article page: https://default.uiowa.ddev.site/news/2023/10/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-0 and seeing a lot of others like that.

Do the migrated ones have a source link filled in correctly? There are some articles that have an external source that do have some copy in the article as well, but if there are a lot of these, we probably want to toggle the 'link directly to source' for them.

**Comment by bspeare** [comment]
Is the page migration supposed to create redirects or no?

**Comment by bspeare** [comment]
@cory-skeers I've checked the first 4 on https://default.uiowa.ddev.site/news/ and they all have empty source links. 

- https://default.uiowa.ddev.site/news/2023/04/mallory-shin-awarded-fall-2023-graduate-college-post-comprehensive-research-0
- https://default.uiowa.ddev.site/news/2023/10/dr-alexander-boyden-receives-one-year-research-grant-national-multiple-sclerosis-0
- https://default.uiowa.ddev.site/news/2023/10/dr-ashutosh-mangalam-receives-new-merit-award-department-veteran-affairs-0
  - https://medicine.uiowa.edu/pathology/content/dr-ashutosh-mangalam-receives-new-merit-award-department-veteran-affairs-0

**Comment by cory-skeers** [comment]
> @cory-skeers I've checked the first 4 on https://default.uiowa.ddev.site/news/ and they all have empty source links.
> 
> * https://default.uiowa.ddev.site/news/2023/04/mallory-shin-awarded-fall-2023-graduate-college-post-comprehensive-research-0
> * https://default.uiowa.ddev.site/news/2023/10/dr-alexander-boyden-receives-one-year-research-grant-national-multiple-sclerosis-0
> * https://default.uiowa.ddev.site/news/2023/10/dr-ashutosh-mangalam-receives-new-merit-award-department-veteran-affairs-0
>   
>   * https://medicine.uiowa.edu/pathology/content/dr-ashutosh-mangalam-receives-new-merit-award-department-veteran-affairs-0

Running it again to take a look

> Is the page migration supposed to create redirects or no?

The `d7_page` migration? It's a bonus from the old `sitenow_migrate` when I was moving stuff over. Not sure if we want to leave it there as potentially useful, but it doesn't have an associated redirect migration.

For the `ccom_articles` migration, `ccom_article_redirects` should create redirects from the old path, but not any other redirects that may have been in place on the old site.

**Comment by bspeare** [comment]
It seems like redirects for the `d7_page` migration would be useful.  Is there a reason to not have redirects in place?

**Comment by cory-skeers** [comment]
> Noticing https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research-0 (links to https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research) converts to an empty article page: https://default.uiowa.ddev.site/news/2023/10/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-0 and seeing a lot of others like that.

I think I misunderstood this the first time I looked at it. Are you getting two articles, one with content and a second empty article page?

There should only be one with content from https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research and nothing from https://medicine.uiowa.edu/pathology/content/nastaran-daneshgar-recipient-2024-spring-graduate-college-post-comprehensive-research-0.

> It seems like redirects for the `d7_page` migration would be useful. Is there a reason to not have redirects in place?

Only focused on articles for this slice, but as long as it's being included as part of the split, I added it in https://github.com/uiowa/uiowa/pull/7090/commits/7aef82fc61a6bfde9010087ff8be34fa8eb5d333

**Comment by bspeare** [comment]
> I think I misunderstood this the first time I looked at it. Are you getting two articles, one with content and a second empty article page?

Yes, this is what is happening.   Is this expected?

**Comment by cory-skeers** [comment]
> > I think I misunderstood this the first time I looked at it. Are you getting two articles, one with content and a second empty article page?
> 
> Yes, this is what is happening. Is this expected?

That is unexpected and confusing, lol.

I ran through all the migrations again, and am not seeing those--only one article per, and with content.

**Comment by bspeare** [comment]
@cory-skeers thanks for confirming.  Maybe it's related to the failing file migration locally and how I ran each migration?   I'm going to stop testing this for now and let someone else jump in and see if they can run the entire migration locally.

**Comment by e-marie-w** [comment]
The d7 file migration works for me, and I am also seeing only one article with content as expected. I have two things:

If I run the `d7_file` migration after the `ccom_article` and `ccom_article_redirects`, I get duplicate media items, vs. when I run the file migration first and then the article ones. Is this expected?

Also, I see work was done to strip the date out of the body field. I found a couple of articles where it is instead in the summary and thus meta. https://default.uiowa.ddev.site/news/2016/11/extra-blood-tubes-useful-or-wasteful-practice, https://default.uiowa.ddev.site/news/2017/04/match-day-2017-results. I'm not sure it's worth the squeeze but I wanted to make it visible.

**Comment by cory-skeers** [comment]
> The d7 file migration works for me, and I am also seeing only one article with content as expected. I have two things:
> 
> If I run the `d7_file` migration after the `ccom_article` and `ccom_article_redirects`, I get duplicate media items, vs. when I run the file migration first and then the article ones. Is this expected?

Yes and no... It's really good to note, and I added a bit on our "update migration docs" card to include it. The files migration is built to bring over ALL files from the original site, so there is no lookup involved. Other migrations are set to do a lookup first to avoid duplicates (whether from the `d7_files` migration, other migrations, or even other pages of the same migration), so they work a little differently.

Ideally, if the files migration is intended to be run, it should always be run first, and if there's a situation where that isn't the case, we'll need to revisit.

> Also, I see work was done to strip the date out of the body field. I found a couple of articles where it is instead in the summary and thus meta. https://default.uiowa.ddev.site/news/2016/11/extra-blood-tubes-useful-or-wasteful-practice, https://default.uiowa.ddev.site/news/2017/04/match-day-2017-results. I'm not sure it's worth the squeeze but I wanted to make it visible.

Nice catch. I'm thinking it's not worth the squeeze as well, since even the initial part in the body was going above and beyond. And with that added bit for the body, the dates should more often than not match now, which would make it redundant but not as bad as if one thing is saying June and the other is saying October.

**Comment by e-marie-w** [comment]
So I decided to test https://medicine.uiowa.edu/surgery/ quick. When I ran the d7_file migration it errored out. I synced default again and tried only running the CCOM article migrations. They ran successfully, but when checking articles the images are missing. If I try to edit the article I see the following where the image should be:
Screenshot 2023-11-13 at 1 26 12 PM

Checking the media tab I can confirm no files were migrated. I'm going to try a different CCOM site to test if it's just this site or something I'm doing wrong.

**Comment by e-marie-w** [comment]
Okay, pediatrics worked fine. In the issue it sounds like we want articles that previously linked directly to source to continue doing that, but I am not seeing that currently. I am going to try surgery one last time.

**Comment by e-marie-w** [comment]
Okay, if I just run the article migrations on surgery everything is fine. I tried the d7 file migration after and it again errored but that is independent of this. For the article migration on pediatrics and surgery I did see a few `[warning] Undefined array key "field_article_gallery_fid" CcomArticle.php:85` but everything appears to have run fine. Also while spot-checking I found one article with a pdf that wasn't appearing in the article, possibly another not worth the squeeze but worth mentioning. 

After clarification on the link directly to source thing I can approve.

**Comment by cory-skeers** [comment]
> Okay, if I just run the article migrations on surgery everything is fine. I tried the d7 file migration after and it again errored but that is independent of this. For the article migration on pediatrics and surgery I did see a few `[warning] Undefined array key "field_article_gallery_fid" CcomArticle.php:85` but everything appears to have run fine. Also while spot-checking I found one article with a pdf that wasn't appearing in the article, possibly another not worth the squeeze but worth mentioning.
> 
> After clarification on the link directly to source thing I can approve.

I pushed up an addition for the link directly source part. I'm going to double check the array key section.

**Comment by cory-skeers** [comment]
> > Okay, if I just run the article migrations on surgery everything is fine. I tried the d7 file migration after and it again errored but that is independent of this. For the article migration on pediatrics and surgery I did see a few `[warning] Undefined array key "field_article_gallery_fid" CcomArticle.php:85` but everything appears to have run fine. Also while spot-checking I found one article with a pdf that wasn't appearing in the article, possibly another not worth the squeeze but worth mentioning.
> > After clarification on the link directly to source thing I can approve.
> 
> I pushed up an addition for the link directly source part. I'm going to double check the array key section.

I checked this out on surgery, and it looks like some of the code I'd written was mistakenly using the full database column name (like `field_article_gallery_fid`) instead of just the value name that the migration tools refer to them as (like simply `fid`). That should be working without warnings now.

**Comment by e-marie-w** [comment]
Latest commits fixed the warning messages for me, and link directly to source articles now correctly do so, great job!

**Review by e-marie-w — APPROVED** [review]
Looked at code and spot checked articles on three different CCOM sites, everything working as expected for the ccom_article and ccom_article_redirects migrations. Awesome job!

**Comment by cory-skeers** [comment]
Thanks @e-marie-w!

**Pull request merged**
