### PR TITLE
Sprint 228

### LINKED ISSUE #7903: Deprovision v3 91st Meridian
It was determined that there is no plan to launch the 91st Meridian website on SiteNow v3 anymore. We have been told we can remove the D10 site.

> - Keep D7 91st around until October 1, 2024, as it will be advertised to 30,000 people in September.

### LINKED ISSUE #8028: CLAS v3 deprovisions
Maggie said the following sites are no longer needed:

https://hr.clas.uiowa.edu/
https://tech.clas.uiowa.edu/
https://finance.clas.uiowa.edu/

CNAMES can be reclaimed

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/7903
Resolves https://github.com/uiowa/uiowa/issues/8028

# How to test

File counters will be thrown off with this one.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
putting these on uiowa07 until we see movement on the uiowa08 ticket with Acquia.

**Comment by joewhitsitt** [comment]
The code that adds custom site config to git failed in https://github.com/uiowa/uiowa/pull/8038/commits/340e94f64ebb6fd18794b767b0ef16324cf4cff1 (not a normal process). Added it manually with https://github.com/uiowa/uiowa/pull/8038/commits/1859acd1e4a90f83d18d7bbbf9e9d6ccdbd9590b and updated the code to fix it going forward here: https://github.com/uiowa/uiowa/pull/8038/commits/c8d53b87e5df6fcac5de2d1300fef22e89746e69

**Comment by joewhitsitt** [comment]
going to add the v3 CLAS deprovisions to this

**Review by pyrello — APPROVED** [review]
As best I can tell, this looks good

**Comment by joewhitsitt** [comment]
Thanks @pyrello

**Pull request merged**
