### PR TITLE
Update Node, Composer and document Yarn workspaces.

### LINKED ISSUE #2611: As a developer, I can use a modern version of Node.
# Story

As a developer I want to use a modern version of Node so that I can benefit from the active development of it.

# Proposed solution

We're currently using Node 10 which is only getting maintenance fixes until April 2021. We should update the version of Node used in CI and DrupalVM to the latest LTS. 

https://nodejs.org/en/about/releases/

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2611 

Taking some learning from debugging my crashes and updating our Node environment to version 14. This also ensures Composer 2 is installed on the VM and documents how to run watch commands on your host. ES6 watch never worked on the VM and SASS was really slow because of polling.

I did not use `lts/*` as the NVM version like we do in uids because its possible CI, the VM and the host could get out of sync. 

### Testing
- `vagrant provision`
- `vagrant ssh`
- `composer --version`
- `node --version`
- `blt frontend`
- Check theme and workspaces built correctly. Visually test theme/workspace assets.
  - uiowa_bootstrap updated to Gulp 4
  - Check HR.
- `yarn workspace uids_base run watch`
  - Change SASS files or something.
- Optional: follow README instructions for running watch commands on your host.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
based on test steps, this worked smoothly. hr looks okay. watch worked

**Comment by joewhitsitt** [comment]
FYI for other testers: not compatible with quick PR switching

**Comment by richardbporter** [comment]
Sorry for not specifying. Labeled with 'config update' as it modifies your VM config and some of that cannot be downgraded when switching branches.

**Comment by pyrello** [comment]
Do you want other testers on this?

**Comment by richardbporter** [comment]
I don't think so. Its probably best if everyone runs `vagrant provision` after this is merged.

**Pull request merged**
