### PR TITLE
adjusted layout breakpoints from sm to md #4653

### PR DESCRIPTION
**Pull request by quamsta**
See #4653, Option A

# How to test

- Run `blt frontend` and see that each column setup in now breaks at the `md` breakpoint instead of `sm`. 
- `blt ds --site=recserv.uiowa.edu`
- Compare mobile emulator views of https://recserv.uiowa.ddev.site/ui-challenge-course against https://recserv.uiowa.edu/ui-challenge-course

This pr also contains an UIDS update that adjusts the `md` breakpoint to the formerly-named `menu` breakpoint of 855px.

### CODE REVIEW

**Comment by cory-skeers** [comment]
I can pull this down to test!

**Comment by cory-skeers** [comment]
Haven't looked into it yet, but visually, it looks like the title/breadcrumb is losing some padding? (Will continue testing, just wanted to get this documented as I came across it.)

image

**Comment by bspeare** [comment]
Nice find @cory-skeers, I'll take a look.

**Comment by cory-skeers** [comment]
Thanks @bspeare! Checked the title/breadcrumb, and the correct spacing is appearing.

I'm noticing some issues with the the 67-33 columns (not sure if it is only these) at the medium breakpoint.

There's an example on the homepage for the sandbox site:
image

**Comment by bspeare** [comment]
Another nice find @cory-skeers!  I'll take a look at that one.

**Comment by bspeare** [comment]
@cory-skeers I updated the breakpoints so that issue should be fixed now.

**Comment by bspeare** [comment]
The bottom of https://sandbox.uiowa.ddev.site/cards-0 is also good for testing these changes.

**Comment by cory-skeers** [comment]
> I updated the breakpoints so that issue should be fixed now.

@bspeare Checking that I'm following this correctly--the intended behavior is to have it collapse to a single column at that breakpoint (990px)?

If so, I think everything is looking good and working correctly!

**Comment by bspeare** [comment]
The `md` breakpoint should be at `855px` with the UIDS update coupled with this.  If you are not seeing it at that pixel value you could run `rm -rf ./node_modules`  `yarn cache clean` and `yarn install` to make sure it is updated.

**Comment by cory-skeers** [comment]
> The `md` breakpoint should be at `855px` with the UIDS update coupled with this. If you are not seeing it at that pixel value you could run `rm -rf ./node_modules` `yarn cache clean` and `yarn install` to make sure it is updated.

That did the trick! Seeing the updated values. Going to do another quick pass through things since I'd missed that originally.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and the updates are looking good 💯

**Comment by bspeare** [comment]
Thank you @cory-skeers!

**Pull request merged**
