### PR TITLE
Provisions 10-23

### PR DESCRIPTION
**Pull request by bzalasky-uiowa**
Sitenow provisions 10-23

- [Initialize biochemstores.medicine.uiowa.edu multisite on uiowa06]
- [Initialize wellstone.medicine.uiowa.edu multisite on uiowa06]
- [Initialize ogps.medicine.uiowa.edu multisite on uiowa06]
- [Initialize flowcytometry.medicine.uiowa.edu multisite on uiowa06]
- [Initialize facultyaffairs.medicine.uiowa.edu multisite on uiowa06]
- [Initialize it.medicine.uiowa.edu multisite on uiowa06]
- [Initialize sercc.medicine.uiowa.edu multisite on uiowa06]
- [Initialize inflammation.medicine.uiowa.edu multisite on uiowa06]
- [Initialize biomed.medicine.uiowa.edu multisite on uiowa06]
- [Initialize craniofacial.medicine.uiowa.edu multisite on uiowa06]
- [Initialize genetherapy.medicine.uiowa.edu multisite on uiowa06]
- [Initialize immunologycenter.medicine.uiowa.edu multisite on uiowa06]
- [Initialize vaccine.medicine.uiowa.edu multisite on uiowa06]
- [Initialize nfrc.medicine.uiowa.edu multisite on uiowa06]

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@bzalasky-uiowa did you use [blt umd](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L223-L242) for this commit? https://github.com/uiowa/uiowa/pull/7029/commits/7e6e59725b2d3d47a20f021bea71483a33130b6e

**Comment by bspeare** [comment]
@joewhitsitt I suggested that he delete those files manually.  I had forgotten `blt umd` was available for that task.  Should he still run that?

**Comment by joewhitsitt** [comment]
`umd` also cleans up the acquia cloud remotes (e.g. databases). i just saw the manual looking commit message and just wanted to make sure it was completely cleaned up.

**Comment by bspeare** [comment]
I believe @bzalasky-uiowa also manually deleted the prod database as well.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
