### PR TITLE
Feature: Sitenow v2 split

### LINKED ISSUE #1807: Move SiteNow V2 Paragraphs-related config to a split
- [x] Move the current Paragraphs-related config to a SiteNow V2 split.
- [x] Replace the base (default) config with pages based on layout builder, similar to config in the collegiate split.
- [x] Update hook (?) to enable the new split on all current SiteNow sites.

### LINKED ISSUE #1926: Should we keep the body field for basic pages?
In the context of #1779, one question that needs to be sorted out is whether the body field should be brought over from the Collegiate split.

My argument would be that yes, you should allow a body field for basic pages that don't need all the trappings of Layout Builder. This would be in addition to other updates that would make it more obvious that creating a more advanced layout requires going to a different page than the edit page.

### LINKED ISSUE #1973: Update entity_usage to work with layout builder and media library
## Problem

Entity usage is not being tracked for layout blocks, etc.

## Proposed Solution

Revisit module configuration to try and reveal usage content referenced by other entities.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #1807. 
Resolves #1926. 
Resolves #1973

This update moves configuration related to the Paragraphs-based layout system into a split called `sitenow_v2`. Additionally, it runs an update hook that removes paragraph instances from sites that have the `collegiate` split enabled and adds the `sitenow_v2` split to all other sites.

A couple things to note:
- I have not moved any of the non-paragraphs configuration to the SiteNow V2 split.
- Paragraphs is not being turned off in the default profile because it will be needed for #1529.  
- I updated the page type to be called just "Page" instead of "Basic page" because I think "Basic page" is confusing in the context of being able to create a complex layout.

# To test

## Install new site
* `blt drupal:install --site=cogscilang.grad.uiowa.edu` or another site locally. You are just temporarily installing over top of an existing site.
* Check that fresh site install does not have `sitenow_v2` split enabled.
* Check that you are able to customize the layout of new and existing pages.

### V2 split on new site
* drush @gradcogscilang.local cim --source ../config/features/sitenow_v2 --partial
* Check that site is consistent with experience of current SiteNow sites.

## Update `collegiate` sites
* `blt ds --site=cogscilang.grad.uiowa.edu` or the `collegiate` site of your choice.
* Check to make sure that existing paragraph types (and therefore instances also) have been removed.

## Update non-`collegiate` sites
* `blt ds --site=brand.uiowa.edu` or the non-`collegiate` site of your choice.
* Check that `sitenow_v2` split is enabled.
* Check that content blocks field still functions as expected.

### CODE REVIEW

**Comment by pyrello** [comment]
This PR makes an assumptions that  we want to remove all paragraphs-related configuration from the default profile.
One potential ramification of this is that if we want to turn on the ability to have paragraphs and LB live side-by-side on some sites, that would have to be handled within the scope of the split or it would require another split to add that functionality to some sites. An alternative to this approach would be to just leave the paragraphs config in the default profile, but to hide or remove the field that exposes them on the page content type, similar to how we are handling it in the collegiate split.

Your feedback is welcome!

**Comment by pyrello** [comment]
@richardbporter or anyone else who looks at this, in the update hook where that moves things around for this PR, I have left in the several approaches that I tried to get this to work (commented out) and added comments to add a little context.

**Comment by richardbporter** [comment]
I think I've got the update hook working but I'm seeing a config diff after syncing the default site:
```
vagrant@local:/var/www/uiowa$ drush config:export --diff
 [notice] Differences of the active config to the export directory:
diff --git a/tmp/drush_tmp_1595258301_5f15b5bdde6ca/core.entity_view_display.node.page.default.yml b/tmp/drush_tmp_1595258302_5f15b5be16296/core.entity_view_display.node.page.default.yml
index ba86b9754..bcc5515ac 100644
--- a/tmp/drush_tmp_1595258301_5f15b5bdde6ca/core.entity_view_display.node.page.default.yml
+++ b/tmp/drush_tmp_1595258302_5f15b5be16296/core.entity_view_display.node.page.default.yml
@@ -201,3 +201,4 @@ hidden:
   field_publish_options: true
   field_tags: true
   field_teaser: true
+  layout_builder__layout: true
```

Does that need to be exported to the split or default config?

I removed the commented out code. Sorry if we need to reimplement any of that.

**Comment by pyrello** [comment]
@richardbporter I went ahead and re-exported that configuration change. It is consistent with the same file inside the collegiate split. Thank you so much for your help on this!

**Comment by pyrello** [comment]
The default template for pages in the PR looks like the standard page layout for current SiteNow sites:
* __Header section__:
  * Background image region: displays the featured image as a background, if it exists.
  * Content region: displays the breadcrumb and page title.
* __Content section__:
  * Left sidebar region: contains the section navigation (if it exists). If it doesn't exist the sidebar region is not rendered.
  * Content region: contains the moderation control, body, and links.

I am wondering if we want to stick to this as the default format?

Also, are there are any other features of SiteNow currently that we want to capture in this split?

**Comment by bspeare** [comment]
@pyrello Do we want to hide some of the layouts available here since it is displaying the default layouts as options to use within layout builder?

Screen Shot 2020-07-20 at 1 51 43 PM

**Comment by bspeare** [comment]
Do we want this set to "Edge to Edge"?  https://github.com/uiowa/uiowa/blob/feature_sitenow_v2_split/config/features/sitenow_v2/core.entity_view_display.node.page.default.yml#L91

Screen Shot 2020-07-20 at 2 05 08 PM

**Comment by pyrello** [comment]
> Do we want to hide some of the layouts available here since it is displaying the default layouts as options to use within layout builder?

I would assume that we want to make available all of the various layouts that we plan to use available. Otherwise, you stuck working with a two column sidebar + content layout, which isn't great.

**Comment by pyrello** [comment]
> Do we want this set to "Edge to Edge"?

I don't think so. Good catch, @bspeare!

**Comment by pyrello** [comment]
@bspeare Actually, I guess we probably want to hide the header layout? I'm not sure. I think it will still exist in the default template, but if it gets removed for any reason, then it won't be able to be added back.

**Comment by bspeare** [comment]
@pyrello Regarding the layouts, I just mean that we should maybe remove the "Header layout" and "Paragraph page" as options to use within a layout since those are meant to be default templates.

**Comment by bspeare** [comment]
We'll need to update https://github.com/uiowa/uiowa/blob/feature_sitenow_v2_split/docroot/themes/custom/uids_base/scss/layouts/page--paragraph.scss with some default spacing for that text area block like we are using for https://github.com/uiowa/uiowa/blob/feature_sitenow_v2_split/docroot/themes/custom/uids_base/scss/layouts/onecol.scss#L8.  Is that something we want to add to this PR?

**Comment by bspeare** [comment]
I ran this on the Brand site and this is the experience without "Edge to edge" set on the main content area in `core.entity_view_display.node.page.default.yml`.    Do we expect each site to adjust the container setting manually or does there need to be a check on pages that are just plain content pages or sidebar pages first?

Screen Shot 2020-07-21 at 9 55 41 AM

**Comment by joewhitsitt** [comment]
i tried this on gis.sites.uiowa.edu. the sitenow_v2 split is enabled but I am seeing layouts functionality as an admin. I thought the sitenow v2 split was supposed to be a legacy cut-off and not a blend of paragraphs/layouts.

I am not sure I understand the update collegiate split sites. I tested on uiowa.edu and the collegiate split is still active. Since their might be changes done in default that a collegiate site might not want to accept, should the process of adopting the default config instead of the collegiate split be a site-by-site process?

- ~~I can do a diff on permissions and update the default for this PR. Webmasters can't see the layout tab.~~
- Of the layout maturity tasks, the ones about restrictions should be done as part of this PR so we don't have an issue with folks creating content they aren't supposed to right off the bat?

If permissions and restrictions are in scope, I will work on that.

**Comment by pyrello** [comment]
@joewhitsitt The update that occurs for collegiate sites is that the paragraph instances that were created as part of the default content are removed, so that when that configuration is removed from the default config, they do not run into an error. 

I have gone through the collegiate config and attempted to remove the items that are no longer relevant because of the changes to default config. At this point, I am leaving the collegiate content type templates in place.

**Comment by pyrello** [comment]
@bspeare I think I remember now why we had that edge-to-edge setting in place and why we want to leave it in place for the SiteNow V2 sites. We did that because the paragraphs layouts have their own control over full width vs containerized options and that was the only way we could accommodate them within a single layout region.

**Comment by pyrello** [comment]
@joewhitsitt I'll have to take a look at gis.sites.uiowa.edu. I'm not sure why layouts would be showing, but maybe I don't have permissions configured correctly. Or the entity_view_display is not correct.

**Comment by joewhitsitt** [comment]
@pyrello did you start this branch before https://github.com/uiowa/uiowa/pull/1910. The restrictions don't seem to be in the config.

**Comment by pyrello** [comment]
I just reverted this: https://github.com/uiowa/uiowa/pull/1932/commits/a4e276edfc20eee892fb7bed39f1375c019669a5

**Comment by joewhitsitt** [comment]
i mean that config/default/core.entity_view_display.node.page.default.yml doesn't have the latest from config/features/collegiate/core.entity_view_display.node.page.default.yml

**Comment by pyrello** [comment]
Good catch, @joewhitsitt! Updated.

**Comment by joewhitsitt** [comment]
thanks, i can fix those conflicts

update: um.. er... i am not seeing the conflicts locally.

**Comment by pyrello** [comment]
Me either. I already tried to and when I merged main, there was no conflicts.

**Comment by bspeare** [comment]
Do we want to introduce https://www.drupal.org/docs/8/modules/layout-builder-restrictions/restricting-blocks-to-specific-layouts-regions to this PR?

**Example restrictions:**

- Hero/Banner - only for use in 1 column layout
- Slider - only for use in 1 column layout
- CTA - available for all layouts
- Text Area - available for all layouts
- Card - only for use in 2, 3, 4 column layouts
- Event - only for use in 2, 3, 4 column layouts
- Statistic - only for use in 2, 3, 4 column layouts (currently used in 1 column sections on uiowa.edu)
- Spacer/Separator - probably should be removed entirely (currently used on uiowa.edu but can be manually removed)
- Vertical Video - only for use on uiowa.edu until it can be improved
- Page Title Hero - should be removed in favor of Featured Image (uiowa.edu would need to be adjusted)?
- Image Gallery - all layouts?

**Comment by joewhitsitt** [comment]
I think I fixed the layout perms for the layout tab on v2 split. need to revisit other v2 sites have site splits.

**Comment by pyrello** [comment]
@joewhitsitt If its that simple, great! I thought I did that, but I think I'm just having trouble keeping track of everything.

**Comment by pyrello** [comment]
Tested against gis.sites.uiowa.edu and that does indeed fix the issue. Thanks for find the easy fix that apparently alluded me :)

**Comment by richardbporter** [comment]
I started looking at #1523 and realized it would be simpler if this PR was merged in sooner rather than later. After reading the Slack discussion, it seems like this could happen as long as we activate the v2 split and import config in the short term for new sites. This can easily be done by adding those Drush commands to the install process, similarly to how the site name is set and requester added.

https://github.com/uiowa/uiowa/blob/75248fa631ca2de9e7ed623ac7ace4a2390e0a7f/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L270-L295

Update:
Adding a split option to the `uiowa:multisite:create` command that would store these as custom config and enable/import them after installation might be a worthwhile addition.

**Comment by joewhitsitt** [comment]
Agree on sooner than later, but I don't want to rush this. I am still testing. Lots of config changing/moving around. About to start looking at v2 custom sites and how their split config is being affected by this.

**Comment by joewhitsitt** [comment]
Regarding https://github.com/uiowa/uiowa/pull/1932#issuecomment-661922578 and https://github.com/uiowa/uiowa/pull/1932#issuecomment-661975017. This appears to still be an issue for the split v2 sites. Changing the container in paragraphs does not change this outer layout wrapper's container.

**Comment by joewhitsitt** [comment]
This fails on policy.clas

**Comment by pyrello** [comment]
Fixed for policy.clas.

**Comment by pyrello** [comment]
It turns out we set the edge-to-edge setting for the whole content section of the page template for SiteNow V2 sites because paragraphs can set full width sections, so we have to account for that. I have restored that functionality.

Another issue that came up with the coronavirus dev site is that SiteNow V2 sites are using a different set of text filters (minimal, filtered, etc.) than collegiate sites. Also, (responsive) image styles. Do we want to go ahead and move over to the collegiate filters and image styles as part of this PR?

**Comment by pyrello** [comment]
One other thing that I had forgotten about until now: Do we want to try to set some conditions to catch current SiteNow V2 that have not had any changes (or minimal changes) to content?

**Comment by pyrello** [comment]
Here is my attempt to summarize where we are at with this PR:
* [x] Remove existing paragraphs in collegiate sites in update hook.
* [x] Add SiteNow V2 split to non-collegiate sites in update hook.
* [x] @richardbporter fixed issue that was preventing update hook from completing.
* [x] Target sites that have had minimal or no changes to default content to be converted to V3 site.
* [x] Default sites will use Page with left sidebar layout by default for now.
* [x] Removed layouts in default from page that we don't want people to use: layout_header, layout_page.
* [x] @bspeare removed layouts in sitenow_v2 that we don't want people to use: layout_header, layout_page.
* [x] Edge-to-edge margin style should be set for layout header and layout page in sitenow_v2 split.
* [x] @joewhitsitt fixed permissions so that 'Layout' tab doesn't show for non-admins in sitenow_v2 sites.
* [x] @bspeare updated class library names, and labels to change 'paragraph-page' to 'page--left-sidebar'.
* [x] Added recent block restriction updates to new page entity_view_displays.
* [x] Restrictions by layout are being handled in #1979. 
* [x] Fixed policy.clas.uiowa.edu split issues.
* [x] Reviewing input formats in #1990. 
* [x] Switch to collegiate (responsive) image styles in #1989. 
* [x] SiteImprove added to v2/v3 (was already on collegiate)
* [x] Entity Usage reconfigured to work with layouts/media library

Feel free to add anything I missed.

**Comment by bspeare** [comment]
Do we need to start a separate issue for the text filters discussion?  For instance, like adjusting what html elements we can add classes to, etc.

**Comment by joewhitsitt** [comment]
I think minimal is actually more restrictive in collegiate which limits spans to only `fa*` classes. So I would be in favor removing minimal from collegiate and matching default across all three (default, v2, collegiate).

As for filtered_html and full_html, I am okay with default (v3) taking on media library/responsive images (i think that is the only diff). For now we need to keep v2 split for those. I still need to check the oEmbed and Remote video parts of Media Library.

**Comment by pyrello** [comment]
@joewhitsitt Do you think we should start a new PR for those or solve it as part of this PR?

**Comment by joewhitsitt** [comment]
I think there is interest in moving forward with this PR so a separate PR sounds fine to me.

I have https://github.com/uiowa/uiowa/issues/865 out there but this might be different if it doesn't include v2 sites.

**Comment by richardbporter** [comment]
Whoops. I need to get d2f745f deployed. Reverted and will move to separate PR.

**Comment by pyrello** [comment]
Looks like the only remaining task is what @richardbporter was working on, to check for minimally changed sites.

**Comment by richardbporter** [comment]
I'm testing fresh installs via `blt drupal:install` and I'm not seeing any default content with or without the v2 split enabled.

**Comment by richardbporter** [comment]
>Target sites that have had minimal or no changes to default content to be converted to V3 site.

I'm not sure how much sense it makes to put time into this now if we're still planning on creating v2 sites requested through the SiteNow request form.

**Comment by richardbporter** [comment]
Sites with viewers, editors, publishers or webmasters that have never logged in. Please remove sites that don't belong here, for example collegiate sites that only have admins accessing the site.

uiowa
- accel.education.uiowa.edu 
- buchholz.lab.uiowa.edu 
- callctr.dentistry.uiowa.edu 
- cd2h.org 
- climatecollective.uiowa.edu 
- cogaresearch.lab.uiowa.edu 
- cognitivecontrol.psychology.uiowa.edu 
- etc.engineering.uiowa.edu 
- health-research-network.sites.uiowa.edu 
- ogallala.research.uiowa.edu 
- themaclab.lab.uiowa.edu 
- uibtaa.centerforconferences.uiowa.edu 

uiowa01
- africanamericanstudies.uiowa.edu 
- americanstudies.uiowa.edu 
- anthropology.uiowa.edu 
- daackhirsch.lab.uiowa.edu 
- fallgiving.sites.uiowa.edu 
- glam.org.uiowa.edu 
- globalhealthstudies.uiowa.edu 
- haa.org.uiowa.edu 
- interdepartmentalstudies.uiowa.edu 
- interdisciplinaryprograms.uiowa.edu 
- internationalstudies.uiowa.edu 
- itpmo.uiowa.edu 
- latinamericanstudies.uiowa.edu 
- latinxstudies.uiowa.edu 
- nativeamericanstudies.uiowa.edu 
- postsecular-novel.sites.uiowa.edu 
- roman.lab.uiowa.edu 
- socialwork.uiowa.edu 

uiowa02
- emfisis.physics.uiowa.edu
- lb-test.uiowa.edu
- perlman.lab.uiowa.edu
- weiss.lab.uiowa.edu
- yahr.lab.uiowa.edu

**Comment by mark-bennett-uiowa** [comment]
@richardbporter what do you mean remove sites that dont belong here? All of "my"sites should be using the collegiate profile at the moment, and arent in the Sitenow collection.

**Comment by cory-skeers** [comment]
Removed the following from the list of sites Rick provided. Content was migrated from D7, and only touched by admin role:

uiowa01
- ~critical-incident-plan.sites.uiowa.edu~
- ~ippl.sites.uiowa.edu~ 
- ~mural-film.sites.uiowa.edu~
- ~sbirt.uiowa.edu~
- ~techforum.uiowa.edu~
- ~wni.sites.uiowa.edu~

@ethanstjohn or @briand44 may know more of them without needing to open each.

**Comment by richardbporter** [comment]
> @richardbporter what do you mean remove sites that dont belong here? All of "my"sites should be using the collegiate profile at the moment, and arent in the Sitenow collection.

The `blt uiowa:multisite:execute` command, which I used to get this list, iterates all sites and not just one profile/split or another. See the drupal-status channel for the exact command. Some of the sites may have had all the content created by an admin which means we probably want to remove them from this list of sites. For example, cogscilang.grad.uiowa.edu.

**Comment by richardbporter** [comment]
Added new split option to UMC command and an update hook for the sitenow request form. Didn't have time to dig into our options regarding default content for newly created sites.

**Comment by mark-bennett-uiowa** [comment]
> > @richardbporter what do you mean remove sites that dont belong here? All of "my"sites should be using the collegiate profile at the moment, and arent in the Sitenow collection.
> 
> The `blt uiowa:multisite:execute` command, which I used to get this list, iterates all sites and not just one profile/split or another. See the drupal-status channel for the exact command. Some of the sites may have had all the content created by an admin which means we probably want to remove them from this list of sites. For example, cogscilang.grad.uiowa.edu.

uiowa01

- africanamericanstudies.uiowa.edu
- americanstudies.uiowa.edu
- anthropology.uiowa.edu
- globalhealthstudies.uiowa.edu
- interdepartmentalstudies.uiowa.edu
- interdisciplinaryprograms.uiowa.edu
- internationalstudies.uiowa.edu
- latinamericanstudies.uiowa.edu
- latinxstudies.uiowa.edu
- nativeamericanstudies.uiowa.edu
- socialwork.uiowa.edu

need to be removed, as they all have admin created content in order to lock pages from accident deletion.

**Comment by pyrello** [comment]
I removed the following sites from the list:
* cogscilang.grad.uiowa.edu
* genetics.grad.uiowa.edu
* iwp.uiowa.edu
* slis.uiowa.edu

**Comment by joewhitsitt** [comment]
For what this PR is scoped to do, it appears to work as advertised. Additionally, for the site-splits I tested they all appear to work as expected with their custom elements maintained. There are follow-up issues related to the default config before new sites should be provisioned. I will document those as part of the layout maturity issues.

I think this should be a scheduled deployment.

**Comment by pyrello** [comment]
Does anyone other than Rick know how to schedule a deployment?

**Comment by pyrello** [comment]
@joewhitsitt Also please note I did create a few follow-up issues: https://github.com/uiowa/uiowa/pull/1932#issuecomment-663071631

**Comment by joewhitsitt** [comment]
> Does anyone other than Rick know how to schedule a deployment?

I have approved his schedule deployments in the past so I am pretty sure I have the permissions to do so. I just need to know the release version and date.

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
