### PR TITLE
Update nvm config to use node version 16

### PR DESCRIPTION
**Pull request by pyrello**
Related to: #6505 

# How to test

```
ddev composer install && ddev nvm install && ddev nvm use && ddev blt frontend
```
Ideally, I'd like to test this on a local machine running Apple Silicon and one that is not.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
should we do uids first? https://github.com/uiowa/uids/blob/4.x/.nvmrc and https://github.com/uiowa/uids/blob/3.x/.nvmrc

**Comment by pyrello** [comment]
> should we do uids first? https://github.com/uiowa/uids/blob/4.x/.nvmrc and https://github.com/uiowa/uids/blob/3.x/.nvmrc

I'm not sure that it matters, since we do not use any of the UIDS workflow that depends on Node/NPM in our SiteNow workflow. For me, `blt frontend` runs without any errors, indicating that this does not cause issues with  the scripts it is necessary for. That being said, if this works, we should update those as well.

**Comment by makurj** [comment]
Pulling down to test on M1.

**Comment by makurj** [comment]
No `blt frontend` issues for me on M1 Pro.

**Comment by joewhitsitt** [comment]
Successful with `node v16.20.0 (npm v8.19.4)` on Intel mac

**Comment by pyrello** [comment]
> No `blt frontend` for me on M1 Pro.

@makurj just double-checking this. Do you mean this worked without issue? Or that you weren't able to run it?

**Comment by makurj** [comment]
> > No `blt frontend` for me on M1 Pro.
> 
> @makurj just double-checking this. Do you mean this worked without issue? Or that you weren't able to run it?

Yes, I meant no issues on M1 Pro. Thanks for checking!

**Review by e-marie-w — APPROVED** [review]
This also works successfully on my M1!

**Pull request merged**
