### PR TITLE
updating carousel accessibility focus styles

### PR DESCRIPTION
**Pull request by GaryRidgway**
This is for #1775, adding better accessibility outlines for carousel controls.

To test: pull down branch, and open any site with a carousel. Then, verify that on focus, the nav buttons at the bottom of the carousel and the arrows have white outlines when focused.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Screen Shot 2020-06-30 at 2 32 22 PM

Looks like the flag happens on the button, not the icon. Can you adjust the styles to be on the `button.slick-arrow`?

**Comment by GaryRidgway** [comment]
yes, ill pull it down right now and make that change

**Comment by GaryRidgway** [comment]
Just finished it up, fixed a few other things as well. Thanks Joe!

**Review by joewhitsitt — APPROVED** [review]
Nioce! Thanks

**Pull request merged**
