### PR TITLE
Paragraphs carousel

### PR DESCRIPTION
**Pull request by GaryRidgway**
Carousel implementation for https://github.com/uiowa/uiowa/issues/1660 and https://github.com/uiowa/uids/issues/123

While I am happy with where this is, I don't think this is done. We probably want to test and check sizing and possibly what we want to do with the edge to edge display.

TO TEST:

load up any site with uids_base as the theme, and create a paragraphs carousel. you should be  able to see a styled carousel made with slick.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Haven't tested this yet, but I don't think this covers uiowa/uids#123 because that is to create the component in uids for use in different situations (paragraphs, blocks, outside-drupal).

**Comment by bspeare** [comment]
@GaryRidgway I'm getting `/themes/custom/uids_base/assets/js/carousel.js` not found.

**Comment by pyrello** [comment]
@GaryRidgway I have started working on #1529 again. I have made an effort to move towards a place where the carousel improvements can be shared between Layout Builder and Paragraphs. If we could make these PR's work together, that would be ideal.

**Comment by GaryRidgway** [comment]
@pyrello I have started on working within the UIDS to make a component for carousels, but it is not pushed up yet. how would you like to start working towards a common ground?

**Comment by joewhitsitt** [comment]
Screen Shot 2020-06-22 at 4 11 28 PM

I am getting a big overflow with section large, align center, full-width column (mac chrome).

**Comment by GaryRidgway** [comment]
looks like container fluid is making the carousel want to expand to extreme sizes, ill look in to this.

**Review by joewhitsitt — APPROVED** [review]
Thanks for your hard work on this and the dealing with the rollercoaster. Just tested locally and I am okay with this assuming we address the colors in #1728 and perform accessibility improvements (visual focus on nav, https://github.com/uiowa/uiowa/issues/1775) at a later date.

**Pull request merged**
