### PR TITLE
update migrate_tools to 6.0.4

### PR DESCRIPTION
**Pull request by joewhitsitt**
Upgrading from 6.0.2

https://www.drupal.org/project/migrate_tools/releases/6.0.4
https://www.drupal.org/project/migrate_tools/releases/6.0.3

Diff https://git.drupalcode.org/project/migrate_tools/-/compare/6.0.2...6.0.4?from_project_id=47830&straight=false

# To Test
```
ddev composer install
```

Quick migration test of drush commands (ms, mim, mr) to ensure things are still working.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Pulling to test

**Comment by joewhitsitt** [comment]
Seeing Cory's commit on the drush_12 reminded me that we have an "active" migration setup with ccom_migrate, so for testing, you can probably follow the instructions here https://github.com/uiowa/uiowa/pull/7090 and pick one of the websites in the Carver College of Medicine app that hasn't been migrated yet.

**Comment by GaryRidgway** [comment]
I am getting a failure for d_7 article for icts

<details><summary>Output here</summary>
<p>

```
 [notice] Processed 138 items (138 created, 0 updated, 0 failed, 0 ignored) - done with 'ccom_article'
  14/138 [==>-------------------------]  10% [error]  Migration failed with source plugin exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;uiowa.migrate_map_d7_file&#039; doesn&#039;t exist: SELECT &quot;fmi&quot;.&quot;entity_id&quot; AS &quot;entity_id&quot;
FROM
&quot;migrate_map_d7_file&quot; &quot;mm&quot;
INNER JOIN &quot;media__field_media_image&quot; &quot;fmi&quot; ON mm.destid1 = fmi.field_media_image_target_id
WHERE &quot;mm&quot;.&quot;sourceid1&quot; = :db_condition_placeholder_0; Array
(
    [:db_condition_placeholder_0] =&gt; 1811
)
 in /var/www/html/docroot/core/modules/mysql/src/Driver/Database/mysql/ExceptionHandler.php line 46 

In MigrateToolsCommands.php line 1092:
                                
  d7_article migration failed.  
                                

Failed to run drush @default.local mim --all: exit status 1

```


</p>
</details>

**Comment by GaryRidgway** [comment]
D7 article worked after all other migrations. Should we weight it to the bottom? 
Otherwise this seems to be working fine (ms, mim, mr all ran as expected, with having to run `d7_article` last)

**Comment by joewhitsitt** [comment]
>Ideally, if the files migration is intended to be run, it should always be run first, and if there's a situation where that isn't the case, we'll need to revisit. https://github.com/uiowa/uiowa/pull/7090

Based on the content from the sites, I am not sure they are always 100% successful and I am not sure making improvements to the migrations is in scope for this issue. migrate_tools provides drush commands/interface to make migrations easier to run. If those are registering/firing as we have historically expected, I'd call testing  this module update a success.

**Review by GaryRidgway — APPROVED** [review]
Approve based on joe's comments

**Comment by pyrello** [comment]
It seems like we are going to need to update the `composer/composer` package in this PR as well. I added it.

**Pull request merged**
