### PR TITLE
Drupal 10 Contrib Low Hanging Fruit

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to #6901

- Update `acquia_purge` to 1.3.0
- Update `administerusersbyrole` to 8.x-3.4
- Update `big_pipe_sessionless` to 2.1.0
- Update `heading` to 1.7.0
- Update `workbench_email` to 2.3.3 (used on brand.uiowa.edu)
- Update `iframe_title_filter` to 2.0.0
- Update `private_content` to 2.0.0
- Update `crop` to 2.3.0
- Update `media_library_theme_reset` to 1.5.0
- Update `menu_link_weight` to 1.0.0-rc1
- Remove `better_normalizers`
- Update `menu_breadcrumb` to 2.0.0-alpha0
- Update `config_ignore` to 3.0.0-beta2

```
ddev composer install
```

# Follow-up

- Remove better_normalizers from composer.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Looks like we have a growing composer.lock conflict. We should resolve before more changes are added to the file.

**Comment by joewhitsitt** [comment]
Keeping the PR small and putting up for review. More of https://github.com/uiowa/uiowa/issues/6901 will be in other PRs/dependabots

**Review by pyrello — APPROVED** [review]
I have tested by pulling locally, running `ddev composer install`, syncing the sandbox site and clicking around while watching logs. Not seeing anything amiss.

**Comment by joewhitsitt** [comment]
I think it is fairly safe to run with this one and ask for forgiveness later. Thanks for the check.

**Pull request merged**
