### PR TITLE
Allow iframes from certain sources in Filtered HTML text format.

### LINKED ISSUE #3393: Consider iFrame Title Filter
## Issue

SiteImprove and other a11y tools have has previously flagged our embeds for not having a "title." Since we don't directly control the iframe markup this has been out of reach.

## Proposed Solution

- [x] Audit our current embed options for title attributes and see if there are SiteImprove issues (local extension).
- [x] Install and configure https://www.drupal.org/project/iframe_title_filter to see if it remedies any of the embeds that are missing title attributes and see if SiteImprove (local extension) no longer flags the embed for this issue.

### LINKED ISSUE #3499: Career Center Video Embeds
# Story

As a content editor for the Career Center, I would like to be able to embed Candid Career videos so that students can have access to career educational videos directly on our site.

# Additional Info
This request if for their SiteNow v3 site that currently exists at https://careers.stage.drupal.uiowa.edu/.

I created a test page with an example of an embedded video using full html at https://careers.dev.drupal.uiowa.edu/test-widget.

Here is a link to the welcome kit and additional info.
https://iowa.sharepoint.com/:w:/r/sites/CSI-Drupal2/Shared%20Documents/Career%20Center/CandidCareer.docx?d=w0d82fd3e6e064b2baff9545a163063d2&csf=1&web=1&e=bDw6cA

# Proposed solution

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3499
resolves #3393

Of the allowed sources, if width/height are included, it checks for aspect ratios we have responsive styling for, otherwise it will display original dimensions but not allow iframe to overflow.

### Setup
```
blt sync --site careers.uiowa.edu
drush @careers.local uli
```

### Stories
As a careers.uiowa.edu site user, I can embed a candid video (as documented through #3499) in a filtered HTML text area.

As a SiteNow platform user, I can embed a Google Map in a filtered HTML text area. (snippet available https://github.com/uiowa/uiowa/issues/3499#issuecomment-884377797)

As a SiteNow platform user, I _can't_ embed other iframes, javascript, etc.

As a SiteNow platform user, I can read about what sources are allowed for iFrames (/filter/tips)

### CODE REVIEW

**Comment by richardbporter** [comment]
There is no integration with CKEditor so you don't get a wrapper to drag and drop an iFrame around. Not great UX compared with media...

**Comment by richardbporter** [comment]
I'm getting the below error after #3846 was merged:
```
The website encountered an unexpected error. Please try again later.

Drupal\Component\Plugin\Exception\PluginException: Plugin (filter_iframe) instance class "Drupal\uiowa_core\Plugin\Filter\FilterIframe" does not exist. in Drupal\Component\Plugin\Factory\DefaultFactory::getPluginClass() (line 97 of core/lib/Drupal/Component/Plugin/Factory/DefaultFactory.php).
```

Anyone else?

**Comment by richardbporter** [comment]
> There is no integration with CKEditor so you don't get a wrapper to drag and drop an iFrame around. Not great UX compared with media...

This is how full HTML embeds work so no difference there.

**Comment by joewhitsitt** [comment]
i think it is your local. allowed google, stripped codepen.
Screen Shot 2021-07-21 at 5 07 43 PM

**Comment by richardbporter** [comment]
Is the filter removing the closing tag now? 728f1bb97f0dd2eda04c458558747bb6b1121f76

**Comment by joewhitsitt** [comment]
So I added markup to each valid iframe and the tests were failing, so I figured it would partial match?!

**Comment by richardbporter** [comment]
I think we'd want to add the new attributes to the test instead: fcdb6b4

This test is brittle though as its all hard-coded right now. With some more refactoring of the filter plugin, it could be improved.

**Comment by richardbporter** [comment]
I think just moving some of the expected attributes as public props/methods on the filter would allow us to grab those and make assertions. We could also add a test for the aspect ratio logic. I can take a look when this is closer to done.

**Comment by joewhitsitt** [comment]
@richardbporter i think I am "done" with the iframe render stuff if you want to look at the tests again.

trying to figure out how to customize the filter/tips more... but got an mvp solution in place.
Screen Shot 2021-07-23 at 2 18 49 PM

**Comment by richardbporter** [comment]
Should we mention in the tips that the embeds have to happen in source mode?

**Comment by richardbporter** [comment]
Unsure of why I'm not seeing those tips...

**Comment by richardbporter** [comment]
I refactored the tests and one is failing right now on the parent div wrapper classes. 

The last data set (`['16x9', 1920, 1080]`) for https://github.com/uiowa/uiowa/pull/3838/files#diff-9770310fad21569102b1383348840b273d93e4635ef7eba29b3aac182a7fe048R89-R112 is testing that a 1920x1080 iframe gets the `16by9` class. It doesn't for some reason.

Also, do we want to ensure that every width/height gets at least the `embed-responsive` class? Is this assumption correct: https://github.com/uiowa/uiowa/pull/3838/files#diff-9770310fad21569102b1383348840b273d93e4635ef7eba29b3aac182a7fe048R100

**Comment by joewhitsitt** [comment]
>do we want to ensure that every width/height gets at least the embed-responsive class?

I don't think we do as the additional aspect ratio class makes or breaks it. I just assumed an easy opt-out would be to have non-traditional dimensions.

>testing that a 1920x1080 iframe gets the 16by9 class. It doesn't for some reason.

I will look into this. I am rounding to a certain decimal point and it might be sneaking past.

>Should we mention in the tips that the embeds have to happen in source mode?
>Unsure of why I'm not seeing those tips...

They are there. Just not where they are useful. I will add the notes about source mode.

**Comment by richardbporter** [comment]
Do you want to add any more test cases? Each row returned from https://github.com/uiowa/uiowa/pull/3838/files#diff-9770310fad21569102b1383348840b273d93e4635ef7eba29b3aac182a7fe048R112 is passed into https://github.com/uiowa/uiowa/pull/3838/files#diff-9770310fad21569102b1383348840b273d93e4635ef7eba29b3aac182a7fe048R98. You can run tests locally with `./vendor/bin/phpunit docroot/modules/custom/uiowa_core/tests/`.

If not, I think I'm done.

**Comment by richardbporter** [comment]
I can't approve this b/c I created it but 👍🏻  from me.

**Review by dnkemper — APPROVED** [review]
nooiice

**Pull request merged**
