### PR TITLE
Hours - Closure support

### LINKED ISSUE #6361: Show closures in UIowa Hours
# Story

As a site owner for Recreational Services, I would like to be able to display closures with details as to specific spaces so that we can represent to our users when a Facility is open but a specific court or other space is closed.

# Additional Info

>Right now our website simply displays closures when no hours are entered.  However, we have the option on the back end to distinguish between open and closed for our activity type so we would love to be able to show closures with details as to specific spaces, etc.

**Joe's comments related to this on Epic**
https://github.com/uiowa/uiowa/issues/4570#issuecomment-1500420781
https://github.com/uiowa/uiowa/issues/4570#issuecomment-1507647501 

# Proposed solution

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #6361 

# To Test

https://recserv.dev.drupal.uiowa.edu/ on the homepage, there is a fitness east block that i modified to show the event details (they plan to use once this is implemented).

After checking this resource for these dates. Check some of the others to confirm they are working as expected. Pick Jan 1 2023 for one of the facilities as it was probably closed.

>April 25 7pm – 9:30pm – FE Closed due to training
>April 26 7pm – 9:30pm – FE Closed for Cleaning
>April 27 2:00pm – 3:00pm – FE Bathrooms Closed for Cleaning  (This one actually overlaps our regular hours which is how we would most likely intend to use it)

https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-fe?start=04/25/2023&end=04/25/2023
https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-fe?start=04/26/2023&end=04/26/2023
https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-fe?start=04/27/2023&end=04/27/2023

Screenshot 2023-04-21 at 11 11 04 AM
Screenshot 2023-04-21 at 11 11 13 AM
Screenshot 2023-04-21 at 11 11 25 AM

### CODE REVIEW

**Comment by e-marie-w** [comment]
It looks like any date in the past will display Closed, has this always been the case?

**Comment by joewhitsitt** [comment]
Yes, I have seen that previous RecServ events at least no longer exist in the feed after they occur. Don't know if RecServ are taking them off or the API just doesn't output them. You can confirm it isn't "our problem" by bringing up the API endpoint.

I think there is also a situation where the API only displays so far in advance. We may want to limit the date picker to upcoming and less than 30 days in another slice

**Review by e-marie-w — APPROVED** [review]
Great work! Upcoming dates with closures correctly display event details. Should we suggest the individual location pages with hours blocks also have Display Title checked to display any closure details like the homepage hours blocks will?

**Comment by joewhitsitt** [comment]
Thanks @e-marie-w 

RecServ is already planning on changing the block config when this becomes available, but I will mention it to them again as I did Law Library this morning.

**Pull request merged**
