### PR TITLE
Feature: Ultrawide responsive image formats

### LINKED ISSUE #1135: Implement Widscreen Ultra responsive image style
In addition to the Widescreen image style, we need a Widescreen Ultra image style to handle a crop that takes up less vertical space for banner images.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #1135

* Adds new media view modes, image styles, responsive image sets, and media view displays to support new Ultrawide image format. 
* Updated the WYSIWYG editor to use new view modes.
* Fixed issue with SVG not showing up in the footer.

Note: The media view modes are added to SiteNow but don't affect anything because they don't do anything on their own. The rest of the config is uiowa.edu-only for now.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
i am going to try again, but my local failed on `core.entity_view_display.media.image.medium__ultrawide`
>Configuration in the database does not match configuration on disk.

**Comment by joewhitsitt** [comment]
Yeah, after sql-drop home.local, trying a `blt ds` it imports all the new config but then continually tries to update the config for core.entity_view_display.media.image.medium__ultrawide

**Comment by pyrello** [comment]
@joewhitsitt Thanks for catching that. I changed the name of a file - to be consistent - but then forgot to change that same name everywhere else it was referenced :|

**Comment by joewhitsitt** [comment]
Now I get:
```
[error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Configuration <em class="placeholder">core.entity_view_display.media.image.medium__ultrawide</em> depends on the <em class="placeholder">core.entity_view_mode.media.medium__ultrawide</em> configuration that will not exist after import.
```

**Comment by pyrello** [comment]
@joewhitsitt I'll take a look. Thanks.

**Comment by pyrello** [comment]
@joewhitsitt This should be fixed now.

**Review by joewhitsitt — APPROVED** [review]
successful import. thanks. i also checked a default sitenow site to make sure ultra_wide wasn't showing yet for wysiwyg content

**Pull request merged**
