### PR TITLE
Admissions AoS requirements

### LINKED ISSUE #2942: Admissions - Add entity reference fields for admissions requirements and application process
# Proposed solution

* [x] Confirm with Scott how he wants to handle entering "Application Process" content.  Do they want to enter as pages similar to "Admission Requirements?"
* [ ] ~~If using a dedicated content type for "Application Process," add the content type. The fields/layout/etc. can be added in a follow-up task. If that is necessary, please create a the follow-up issue.~~
* [x] Remove the Admission Requirements content type.
* [x] Create paragraphs bundle to house the fields
  * Title/label
  * Intro
  * Requirement label
  * Requirement entity reference (page)
  * Process label
  * Process entity reference (page)
* [x] Create three separate paragraphs fields on AoS that allow one item from the bundle above.
* [x] Bring the local admissions requirements field into the same gray section to connect the "four" together.
* [x] Output in card template for follow up work in https://github.com/uiowa/uiowa/issues/2934

<details>
<summary>Original details</summary>
```
- [ ] Add 3 entity reference fields that link to pages, with the following names:
  - Requirements: First year
  - Requirements: Transfer
  - Requirements: International
- [ ] Add 3 entity reference fields that link to whatever content type is determined to be used for "Application Process" content based on previous conversation, with the following names:
  - Application process: First year
  - Application process: Transfer
  - Application process: International
```
</details>

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #2942

## To Test

Pull and go to http://admissions.local.drupal.uiowa.edu/node/761/edit
See the new requirement collections (first year, transfer, international). Fill em out. Try to break it by not adding all of the values.
On render in the same background color as the Admissions Requirements text, see some white card styles with the intro content and some buttons. If references to content weren't provided the button won't show. If a label is not provided a fall back for the button text displays, the buttons themselves should link to the content your referenced.
The card titles themselves should match the field you added them to.
Final styling will be captured in https://github.com/uiowa/uiowa/issues/2934

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling down to test.

**Review by bspeare — APPROVED** [review]
I wasn't able to break this and it appears to function exactly as you described.  Do we want to add help text to explain that  "If references to content weren't provided the button won't show"?

**Comment by joewhitsitt** [comment]
I will add some help text when i go rouge on the stat fragment updates

**Comment by pyrello** [comment]
Future rogue-ing plans.

**Pull request merged**
