### PR TITLE
[ITS] Filter focus fix #3

### LINKED ISSUE #3: Update core patch
The patch we are using to set site configuration values from the install profile no longer applies against 8.5.x. A re-roll of the patch is available at https://www.drupal.org/project/drupal/issues/2849074#comment-12546690.

### LINKED ISSUE #7447: Better exposed filters focus
# Problem
Certain filter combos cause the focus order to mess up, see https://iowaweb.slack.com/archives/C0164FNN1PV/p1709566223488189 for more discussion. 

# Proposed Solution

- Investigate if the ordering of the filters changes what is focused when you submit the filters. Based on that, we could proceed in one of the following ways:
    - If the ordering change works fine enough, neato.
    - Otherwise, potentially look up issues on drupal.org for things that might be tied to this.
    - Worst case scenario, we can always manually change the focus on submit with Javascript.

### PR DESCRIPTION
**Pull request by GaryRidgway**
Resolves https://github.com/uiowa/uiowa/issues/7447

# How to test

```
ddev composer install && ddev blt ds --site=its.uiowa.edu && ddev drush @its.local uli /alerts/status-history
```

1. Check to see if the form works okay after autosubmit is turned off.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
I think this mix of autosubmit and non-autosubmit with this patch is now causing problems. I am sure we have other views like this as well. As a keyboard user I get booted back to the first filter.

I entered a start date that didn't return any results. Cleared it out and tabbed to the end date. It autosubmits with the end date picker displayed but then changes my input focus back to the title filter.

https://github.com/uiowa/uiowa/assets/4663676/14eed5c5-b0eb-4fb2-9bdc-3bc0d74c3bfc

**Comment by joewhitsitt** [comment]
If this patch was just for this view, I'd say move forward but with autosubmit off, but since we have autosubmit almost everywhere now, I can see how this can cause issues. [We already have issues with autosubmit](https://github.com/uiowa/uiowa/issues/6961).

**Comment by bspeare** [comment]
I tested this out and I do like that this change removes the focus from the date picker after a category is selected!   Fixing that is a pretty big improvement for usability. 

There is a quirk, that moves the focus to the building or service field based on a few interactions:
- If a building is selected and at least one category is selected and you use the search field, the focus goes down to the building field.  This can be an issue if you are slow typing out your search terms and it will automatically move you to the building focus (see details below for screen capture). 
- If a building is selected, and you select two categories, the focus goes up to the building field. 
- If a service and building is selected, and you select one category, the focus goes up to the service field. 


<details>

https://github.com/uiowa/uiowa/assets/1036433/6af6bd2c-28f4-4b41-8e5b-e2fda78e5230

</details>

**Comment by GaryRidgway** [comment]
> 
> There is a quirk...
> 

Ugh. This is seriously annoying. There is not any support for those type of fields currently, so in addition to the datefields technically not being supported, any focus that those autocompletes get is a total wash right now too. Perhaps this issue transitions in to a future upgrade for BEF and we just disable autosubmit for now? It feels odd to try and completely refactor and fix all the issues with BEF right now just to solve this one datepicker popup issue when we really didn't scope for more than that.

Thanks for the comments Y'all. I think I will bring this back up to the team in PL.

**Comment by pyrello** [comment]
Pulled to test.

**Review by pyrello — APPROVED** [review]
This isn't the improvement we were hoping for, but it'll do for now. Thanks for your work on this @GaryRidgway!

**Pull request merged**
