### PR TITLE
Yarn upgrade latest

### PR DESCRIPTION
**Pull request by richardbporter**
https://github.com/orgs/uiowa/projects/1#card-77820127

### How to test
blt frontend
Test all workspace output for SASS/JS.
Test for visual regressions in all workspaces.

### CODE REVIEW

**Comment by bspeare** [comment]
Testing

**Comment by bspeare** [comment]
@richardbporter do I need to run any install commands to update anything or does `blt frontend` do it all?

**Comment by richardbporter** [comment]
> @richardbporter do I need to run any install commands to update anything or does `blt frontend` do it all?

It should. `blt frontend` runs `yarn install --production...` which should install things based on the `yarn.lock` file.

**Review by bspeare — APPROVED** [review]
`blt-frontend` worked without errors, `yarn workspace` build commands worked fine too.  I randomly compared the output of `card.css` with what is on production and they are identical.  Did the same for `counselors-map.js` and the files are also identical.  I also looked at UIPress, Admissions, and the home page for any visual regressions and I did not find any.

**Pull request merged**
