### PR TITLE
Dispatch/Facilities Message Logging

### LINKED ISSUE #6855: showing dispatch log
# Story

As a Facilites alert creator, I can see a log of scheduled dispatch emails from my alert node.

# Additional Info

Based on how this functionality is currently setup, we will want to link the log to a message rather than the communication like their existing site does.

Existing site example https://www.facilities.uiowa.edu/node/5816/dispatch

# Proposed Solution

- [ ] Output dispatch log on node tab where scheduling happens
- [ ] Link to Dispatch message
- [ ] Show count in node tab

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #6855

Screenshot 2023-09-20 at 11 20 52 AM

# To Test

```
ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli admin/config/sitenow/sitenow-dispatch
```
Go to [facilities.uiowa.edu](https://www.facilities.uiowa.edu/admin/config/services/facilities-alerts-emails) and get the dispatch API key and enter it here https://facilities.uiowa.ddev.site/admin/config/sitenow/sitenow-dispatch

Create two alerts. Attempt to schedule one of them through the notifications tab.

Note that the unschedule alert does not display a log but the schedule alert does. See that the message id is linked to the modal within the dispatch communication. Also note that the user id gets output as the user name.

Inspect the database table: `facilities_uiowa_edu.sitenow_dispatch_messages_log`

Schedule another dispatch message for the same alert. See that the table sort works as expected and that the tab count is incremented.
Schedule the previously unscheduled alert.

Delete the alert with two scheduled messages and inspect the database table again. The two entries for that entity id should be removed leaving the other log entry for the other alert.

Visit the dispatch interface and unschedule each of the messages you scheduled.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Need to investigate install. Update existing was working as expected.

**Comment by joewhitsitt** [comment]
Switching back to draft. @briand44 explained the left to do on https://github.com/uiowa/uiowa/issues/6855#issuecomment-1727736657

**Comment by joewhitsitt** [comment]
Here is the trouble I am dealing with in trying to style the tab count:
Screenshot 2023-09-20 at 5 00 56 PM
Screenshot 2023-09-20 at 5 00 46 PM

`Notifications  <span class="small badge badge--orange pager__link is-active">' . $count . '</span>'`

Going to leave it as the following for MVP:

Screenshot 2023-09-20 at 5 10 46 PM

**Comment by joewhitsitt** [comment]
Also realized the date sort on the table isn't working. Probably worth storing the date as a unix timestamp which will take some refactoring.

**Comment by joewhitsitt** [comment]
Putting up for review again after changing how the date value is stored in the database and making sure the theme table sorting works.

**Comment by cory-skeers** [comment]
Pulling down to test

**Review by cory-skeers — APPROVED** [review]
Also ran into https://github.com/uiowa/uiowa/pull/6833#pullrequestreview-1625160282 with it complaining about the AlertSubject placeholder, but it otherwise seemed to function, and can be troubleshooted (troubleshot?) as a follow-up.

Otherwise, ran through testing scheduling single or multiple alert communications, and everything in the log and database table has been working great!

**Comment by joewhitsitt** [comment]
Ope! So confident with this PR that you committed the d10 update to this? 😜  https://github.com/uiowa/uiowa/pull/6906/commits/0162e30a899008fbd2b55deaf9f0b9fbec964a3b

**Comment by cory-skeers** [comment]
> Ope! So confident with this PR that you committed the d10 update to this? 😜 [0162e30](https://github.com/uiowa/uiowa/commit/0162e30a899008fbd2b55deaf9f0b9fbec964a3b)

🤦

**Pull request merged**
