### PR TITLE
Updated to D10.0 compatible version of ctools without exposed filters updates

### LINKED ISSUE #5589: Update drupal/ctools to 3.11 and add to our composer.json
# Story

As a developer, I can manage the version of ctools we are using instead of relying on other modules' composer files to update it. Since we rely on ctools/ctools_views for ListBlock, we should maintain better control over this dependency.

# Background

Noticed there have been updates to ctools (https://www.drupal.org/project/ctools/releases/8.x-3.11) but that we are still on 3.7.0 because the way it is pulled in is through other modules' composer files (pathauto, paragraphs).

# Proposed solution

- [ ] Add/update ctools within our composer.json. Test our ListBlock functionality and prepare for later versions of Drupal.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5589

Code changes: https://git.drupalcode.org/project/ctools/-/compare/8.x-3.7...8.x-3.11

# How to test
```
ddev blt ds --site sandbox.uiowa.edu && ddev drush @sandbox.local uli
```
- Test viewing a variety of list blocks
- Test editing existing list blocks
- Test adding new list blocks
- Test removing list blocks
- Test multiple list blocks on a page with different styles
- Test multiple list blocks on a page don't have issues with pagers conflicting

### CODE REVIEW

**Comment by pyrello** [comment]
Looking at the first "Hidden Details" block on https://sandbox.uiowa.ddev.site/articles, no images are showing despite images not being hidden by the block. When the pager is used, the images show up on the second+ page of results or even the first if you page back to it.

**Comment by pyrello** [comment]
The behavior I observed above is in production also, so I guess we need to clarify if the behavior is somehow working as expected or if there was a regression introduced.

**Comment by joewhitsitt** [comment]
On first glance, I think this might be the same issue https://github.com/uiowa/uiowa/issues/6373

**Comment by joewhitsitt** [comment]
Based on https://github.com/uiowa/uiowa/issues/6373#issuecomment-1759923712, I don't think there is an issue with ctools here as it relates to listblock image rendering.

**Comment by pyrello** [comment]
We maybe should create some test pages for these that aren't confusing because they invoke the issue in #6373 or make instances where an article is being linked to another source super obvious.

**Comment by pyrello** [comment]
FYI, I updated the title of https://sandbox.uiowa.ddev.site/news/2023/08/links-directly-source-museum-natural-history-muse-mfa-grad-student-mariceliz-pagan so that I could better understand what was happening at a glance when testing list blocks

**Comment by joewhitsitt** [comment]
https://www.drupal.org/project/ctools/releases/8.x-3.11 

>Note: You must update your conditions before upgrading to Drupal 10. Ensure that node_type is removed from your codebase and configuration: Search your site's configuration for "node_type" in the pathauto and potentially other *.yml files and replace it with 'entity_bundle:node'; Also ensure you are re-exporting your config after running updates, otherwise changes from pathauto or other modules using the updated condition plugin won't get seen in your config.

**Comment by pyrello** [comment]
> https://www.drupal.org/project/ctools/releases/8.x-3.11
> 
> > Note: You must update your conditions before upgrading to Drupal 10. Ensure that node_type is removed from your codebase and configuration: Search your site's configuration for "node_type" in the pathauto and potentially other *.yml files and replace it with 'entity_bundle:node'; Also ensure you are re-exporting your config after running updates, otherwise changes from pathauto or other modules using the updated condition plugin won't get seen in your config.

@joewhitsitt Do you think this is a blocker for this PR? Or just the D10 upgrade?

**Comment by joewhitsitt** [comment]
Not a blocker for the PR, but in reviewing it, I think it broadens what we look at.

**Comment by joewhitsitt** [comment]
Sorry, it looks like I assigned myself to the issue and not the PR. https://github.com/uiowa/uiowa/issues/5589. I was planning on taking a closer look at this.

**Comment by pyrello** [comment]
> Not a blocker for the PR, but in reviewing it, I think it broadens what we look at.

It would be great to find some more documentation about this. The note is pretty cryptic.

**Comment by pyrello** [comment]
I wonder if this is related? https://www.drupal.org/project/ctools/issues/3302732

**Comment by joewhitsitt** [comment]
I just re-saved a pathauto pattern and there was no config diff. In the config I do see a lot `node_type` bits though. pathauto is at 1.11.0 which drops ctools as a dependency. https://www.drupal.org/project/pathauto/releases/8.x-1.11

Apparently, I was all over this in https://github.com/uiowa/uiowa/pull/5527

>pathauto, test new page creation nested in the menu system, updating an existing node alias, and going to /admin/config/sitenow/uiowa-articles and changing the path and then inspecting article content to see that their paths have been updated. update hook, config changes - Update node type conditions from node_type to entity_bundle.

https://github.com/uiowa/uiowa/commit/8f65bf92fcdcfb032d1f5578131490e3592ff693

Not sure why some patterns are still the `node_type`.

The release notes suggested re-running the update hook if necessary. I might try that.

**Comment by joewhitsitt** [comment]
I am seeing it in the db but then it says identical when I try to run an export:

```
a:12:{s:4:"uuid";s:36:"dbec68e5-3dc4-45fb-b0f0-fd2e25e088d5";s:8:"langcode";s:2:"en";s:6:"status";b:1;s:12:"dependencies";a:1:{s:6:"module";a:1:{i:0;s:4:"node";}}s:2:"id";s:7:"article";s:5:"label";s:7:"Article";s:4:"type";s:23:"canonical_entities:node";s:7:"pattern";s:65:"news/[node:created:custom:Y]/[node:created:custom:m]/[node:title]";s:18:"selection_criteria";a:1:{s:36:"e06df5eb-85fe-4c69-8ebc-ff7cb5e10cdc";a:5:{s:2:"id";s:18:"entity_bundle:node";s:6:"negate";b:0;s:4:"uuid";s:36:"e06df5eb-85fe-4c69-8ebc-ff7cb5e10cdc";s:15:"context_mapping";a:1:{s:4:"node";s:4:"node";}s:7:"bundles";a:1:{s:7:"article";s:7:"article";}}}s:15:"selection_logic";s:3:"and";s:6:"weight";i:-5;s:13:"relationships";a:0:{}}
```

Looks like article and person should have it based on logic in `pathauto_update_8108` so I was thinking about manually changing it and going with that for now.

**Review by joewhitsitt — APPROVED** [review]
Sorry to hold this up so long. I think this is fine.

**Comment by pyrello** [comment]
Thanks for testing and digging into everything so thoroughly, @joewhitsitt!

**Pull request merged**
