### PR TITLE
Counselors Listing/Map Updates

### PR DESCRIPTION
**Pull request by GaryRidgway**
This PR is to track progress for #2649

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Review by joewhitsitt — APPROVED** [review]
approving these two changes to go out. more work to close the issue

**Comment by bspeare** [comment]
Scott mentioned in today's meeting a reminder about moving "International Recruitment" to the top of the select list for counselors.   Is it too late to put that work into this pr?

**Comment by cory-skeers** [comment]
@bspeare I added it as an additional checkbox to #2649 as part of the remaining work

**Comment by bspeare** [comment]
@cory-skeers thanks!

**Comment by joewhitsitt** [comment]
The rest of #2649 is happening here: https://github.com/uiowa/uiowa/pull/2717

**Pull request merged**
