### PR TITLE
[ITS] helpdesk emails

### LINKED ISSUE #7417: Email notification to ITS Help Desk about alert creation
# Story

As a member of the ITS Help Desk, I would like to be notified via email when an alert is created that requires review/publishing so that we can promptly review, publish and send any necessary communications about the alert.

# Additional Info

https://github.com/uiowa/uiowa/issues/7417#issuecomment-1984771012

Email to send to `HelpDesk-Notify@uiowa.edu`

Update help text around alert updates for off-hours process

Comment from Joe on https://github.com/uiowa/uiowa/issues/7456#issuecomment-1995021108

> help desk notify needs to be expanded to alert add/edit transitions to "needs review" and help text around alert updates needs to mention off-hours process for alerting helpdesk on-call staff to publish.

# Proposed Solution

```[tasklist]
- [ ] Add workbench_email to ITS site split
- [ ] Configure/export module config to send email to HelpDesk-Notify@uiowa.edu when alerts transition to Needs Review
- [ ] See https://github.com/uiowa/uiowa/issues/7417#issuecomment-1984771012 for email body content
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7417

# How to test

```
ddev blt ds --site=its.uiowa.edu && ddev drush @its.local uli /node/add/alert
```
- Code review
- Run `ddev launch -m` which will bring up the local email client. 
- Add alert and set "needs review" as status
- Check mailpit and see that an alert email is there
- Test email link in body and review email subject, from address, body

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Added permissions for the new workflow and registered the workflow with the content type's form.

**Review by joewhitsitt — APPROVED** [review]
Thanks for working through the bumps with this one.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
