### PR TITLE
Site provisions 3-15

### PR DESCRIPTION
**Pull request by e-marie-w**
Site provisions for afr.fo.uiowa.edu and fa.fo.uiowa.edu on uiowa as it is the only one with SSL cert for *.fo.uiowa.edu.

### CODE REVIEW

**Review by joewhitsitt — APPROVED** [review]
oh happy day!

**Comment by briand44** [comment]
Site provisions 4-15? Is it April already?

**Comment by e-marie-w** [comment]
> Site provisions 4-15? Is it April already?

Ohhhh that's why that date looked so wrong, shoot. I double-checked the day but not the month.

Also thanks for the approval before I even got to requesting it @joewhitsitt!

**Comment by joewhitsitt** [comment]
sorry, got so excited and didn't see you were actively working on requesting approval. thought it switched from draft to review last night

**Pull request merged**
