### PR TITLE
Removing 175 footer logo

### LINKED ISSUE #5581: As a visitor to uiowa.edu, I can view the Iowa logo that no longer celebrates the 175th anniversary
# Proposed solution

Undo or update the files that were created in https://github.com/uiowa/uiowa/pull/4263 to display the Iowa logo.

### PR DESCRIPTION
**Pull request by e-marie-w**
Fixes #5581 

# How to test
- Sync down a site/sites of your choice
- Check update hook runs with no problems
- Check the logo in the footer is now just UIOWA, instead of UIOWA 175 Years, and that clicking the logo will bring you to uiowa.edu
- See that rest of footer elements remain unchanged

### CODE REVIEW

**Comment by bspeare** [comment]
@joewhitsitt how should we handle this logo update considering this fix that you had made previously?

https://github.com/uiowa/uiowa/pull/4400

**Comment by joewhitsitt** [comment]
It should be fine again. The link and the alt text are the same. Before the header was going to the homepage and the footer to 175th while they both had the same alt text.

Might get point off for redundant link going forward, but not the same issue.

**Comment by bspeare** [comment]
Testing.

**Review by bspeare — APPROVED** [review]
Looks good!  Do we need to move this back to draft to wait for a schedule deployment?

**Comment by e-marie-w** [comment]
Moved to draft until next scheduled deployment.

**Pull request merged**
