### PR TITLE
Site customizations for 91st Meridian

### LINKED ISSUE #5595: 91st Meridian - Add translator field to writing content type
# Story

As a 91st Meridian content editor I want a translator field on the writing content type so that I can display the translator of a piece of writing content.

This is picking up from #5414 and will be a follow-up to #5601.

# Proposed solution

- [x] Add a text area field called "Translator" to the article content type. This will be split configuration for the site split.

### LINKED ISSUE #5601: 91st Meridian - Create writing collection container + writing content type
# Motivation

91st Meridian is a periodical literary magazine. As such, it is organized into issues, with [each issue](https://iwp.uiowa.edu/91st/vol1-num1) containing [multiple individual pieces of writing](https://iwp.uiowa.edu/91st/vol1-num1/too-little-seen). In the current version, there are two content types: 91st Meridian Content and 91st Meridian Issue Homepage. I believe this idea of having an entity represent the collection and a different entity to represent the individual pieces of writing is a good way to organize it.

After taking a look at iowareview.org, I think that represents a good path forward for this work.

# Proposed solution

- [x] Add a Periodical/Journal feature split
- [x] Add an Issue content type:
  - [x] Volume
  - [x] Issue Number
  - [x] Season/Year
  - [x] Issue Release Date
  - [x] Table of Contents - _Use body field?_
  - [x] Cover Image (`field_image`)
  - [ ] Description/Teaser
  - [x] Editor's Note
  - [x] Masthead
  - [x] Contributors' Notes
- [x] Add an Issue article content type
  - [x] Issue - ER field (cardinality = 1) that can reference the Issue content type
  - [x] Body
  - [x] Author (text or ER?)
  - [x] Author Bio
  - [ ] Genre
- [ ] Both content types will need a custom path alias pattern
- [ ] Check https://wiki.uiowa.edu/display/drupaldev/Content+type+creation+notes to see other steps that may not be documented here for new content types

<details>
<summary>Original proposed solution</summary>
This is currently based on the investigation at https://github.com/uiowa/uiowa/issues/3868#issuecomment-1222440670

- Add a Periodical (?) feature split
- Enable Entity Hierarchy + submodules
- Add a issue/collection content type
- Add a writing/article content type
- Add all new config to the feature split and export config
</details>

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5601 
Resolves #5595

# To do

- [x] Construct Publication Issue title using volume number, issue number, and season/year (similar to how title is constructed for Person content types
- [x] Fix publication articles showing up on /news page
- [x]  Update article display to match default theming already in place for articles

# How to test
```
ddev blt frontend && ddev blt ds --site 91stmeridian.iwp.uiowa.edu && ddev drush @iwp91stmeridian.local en sitenow_periodical && ddev drush @iwp91stmeridian.local config-split:activate periodical -y && ddev drush @iwp91stmeridian.local cim -y && ddev drush @iwp91stmeridian.local config:import --source ../config/sites/91stmeridian.iwp.uiowa.edu --partial -y && ddev drush @iwp91stmeridian.local cim -y && ddev drush @iwp91stmeridian.local cr && ddev drush @iwp91stmeridian.local uli node/add/publication_issue
```

- `blt frontend`
- `ddev blt ds --site 91stmeridian.iwp.uiowa.edu`
- `ddev drush @iwp91stmeridian.local en sitenow_periodical`
- `ddev drush @iwp91stmeridian.local config-split:activate periodical -y`
- `ddev drush @iwp91stmeridian.local cim`
- Enable site split : `ddev drush @iwp91stmeridian.local config:import --source ../config/sites/91stmeridian.iwp.uiowa.edu --partial && ddev drush @iwp91stmeridian.local cim`
- `ddev drush @iwp91stmeridian.local cr` to get moderation block working. 
- `ddev drush @iwp91stmeridian.local uli node/add/publication_issue`
- Try adding Publication Issues.
- Try adding Articles. Check that filling in the Issue field changes the URL path on save, while leaving the field empty results in our default news/... path.
- Check usual things like user roles and content moderation block working, you could also validate the schema for article and publication issue. 
- Code review also appreciated

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Want to mention this before it is forgotten. We need to update this logic somehow so that paths for periodical articles don't get overwritten by the default set on this form: https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_articles/src/Form/SettingsForm.php#L420

**Comment by joewhitsitt** [comment]
@e-marie-w showed me that https://github.com/uiowa/uiowa/pull/5596#issuecomment-1318843731 appears to be a non issue due to the way the periodical article path is altered.

**Comment by bspeare** [comment]
Testing this out now.

**Comment by bspeare** [comment]
I was running into issues with the moderation block until I found this suggestion: https://github.com/uiowa/uiowa/pull/5273#issuecomment-1140044666.   I'll add it to the wiki page.

**Comment by bspeare** [comment]
Are articles that are used for publications supposed to show up on the `/news` page?

**Comment by e-marie-w** [comment]
> I was running into issues with the moderation block until I found this suggestion: [#5273 (comment)](https://github.com/uiowa/uiowa/pull/5273#issuecomment-1140044666). I'll add it to the wiki page.

Interesting. Glad the cache rebuild worked! I usually run one after `cim` from force of habit but I didn't think it was required. I guess it is.

> Are articles that are used for publications supposed to show up on the /news page?

Huh I did not think of that. Going to move this back to draft while I try to fix that and also update the publication issue title so that it's constructed from the volume, issue number, and season.

**Comment by bspeare** [comment]
How to do we want to handle the article/publication display?  

It currently looks like:

Screen Shot 2022-11-18 at 11 26 23 AM

And should look something like:

Screen Shot 2022-11-18 at 11 26 16 AM

**Comment by bspeare** [comment]
Schema validation looks good. 

Screen Shot 2022-11-18 at 11 38 47 AM

**Comment by pyrello** [comment]
> How to do we want to handle the article/publication display?

In your screenshot, should "Publication" be "Issue"? Do we want to display a link like that in the content? Or should this be something that is handled via the breadcrumb?

**Comment by bspeare** [comment]
@pyrello good point about the label.  Breadcrumb could be a good way to avoid adding more fields to the page?  What would you like to do?

**Comment by joewhitsitt** [comment]
@e-marie-w did you have any code started for the install/uninstall views page adjustments?

**Comment by e-marie-w** [comment]
@joewhitsitt Nope go for it!

**Comment by e-marie-w** [comment]
Now that the article fields have the same styling, I'm wondering about the issue content type. Should the issue fields have the article styling, or something else? Or can we leave them as-is for now? The original PR mentioned theming not being in scope, not sure if field styling counts or not.

**Comment by bspeare** [comment]
@e-marie-w I think the field styling can wait.

**Comment by pyrello** [comment]
I'm going to test this.

**Comment by pyrello** [comment]
Added a copy-able one-liner for testing :)

**Comment by e-marie-w** [comment]
Season/year field is now the title field. I did have to resync the site for it to work.

**Comment by pyrello** [comment]
I can't approve this, since I created it to begin with. But I approve of the changes. Nice work, @e-marie-w!

**Review by cory-skeers — APPROVED** [review]
Approving based on @pyrello 's testing

**Pull request merged**
