### PR TITLE
Admissions - AoS Search Filtering View

### LINKED ISSUE #3203: As an prospective student, I can use a set of filters to sort through the Areas of Study and see detailed results
# Story

As an Admissions website user, I can use a set of filters to sort through the Areas of Study and see Majors and Subprograms listed in the results. 

# Additional Info
https://iowa-my.sharepoint.com/:w:/g/personal/sfiddelk_uiowa_edu/EUCW5mYgGHVHklicgfev3e8BGLGl34GtPMN2-U6xfsWeAA?e=UPhayh

A core patch is needed if entity reference (node) filtering is used: https://www.drupal.org/project/drupal/issues/2429699

# Proposed solution

Using https://admissions.uiowa.edu/academics/undergraduate-areas-of-study as a model, update the search filter on http://admissions.local.drupal.uiowa.edu/areas-of-study and http://admissions.local.drupal.uiowa.edu/ to include the ability to sort by:

- Academic Group
- College
- Program Type (Major, Minor, Certificate, Preprofessional Program, Online/Offcampus Program)

Screen Shot 2021-03-08 at 11 48 18 AM

Update the listing on http://admissions.local.drupal.uiowa.edu/areas-of-study to include Majors and Subprograms like it is listed on https://admissions.uiowa.edu/academics/undergraduate-areas-of-study. 
- Include Majors
- Include Subprograms

Screen Shot 2021-03-08 at 11 47 57 AM

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/3203

## To Test

- pull and sync admissions
- give at least one existing area of study a pretty title. remember it.
- go to http://admissions.local.drupal.uiowa.edu/areas-of-study
- search should filter on contains area of study title or pretty title. remember your pretty title?
- academic group, college, program type should act like normal views filters if the content exist.
- degree/type column should render similar to "BA, BS, Minor, Certificate, Online Option" if the content exists, otherwise the string reflects that and their are no trailing commas.
- i am sure i am forgetting something, but it is probably covered by this awesome PR.

### CODE REVIEW

**Comment by pyrello** [comment]
I'm going to test what is here so far and maybe take a stab at the title switcheroo thing.

**Comment by pyrello** [comment]
Pulling down to test.

**Review by pyrello — APPROVED** [review]
This deserves more in-depth testing, but I'm satisfied that it works so far. Once we complete
#2501, we'll have a lot more live data that we can use to test and identify issues for follow-up work.

**Comment by pyrello** [comment]
I should also mention 2 other things:
* I think we are going to need to work on the design a bit. When I added a college, the "Search" button was pushed to a new line, making the whole box very big.
* I think we should consider adding a reset button. The form is somewhat hard to use without it.

**Comment by bspeare** [comment]
With the search style updates in https://github.com/uiowa/uiowa/issues/3247, the bar will look more like this screenshot below:

Screen Shot 2021-03-19 at 9 02 45 AM

**Comment by pyrello** [comment]
Probably need something other than '-Any-' as a placeholder for those last two boxes. The colleges field takes up a lot of space.
Screen Shot 2021-03-19 at 9 06 36 AM

**Comment by bspeare** [comment]
A few design notes:

- Can we break the filters into two lines and have it auto-submit to remove the search?
- Can we use something like https://www.drupal.org/project/better_exposed_filters to make the filter more dynamic?

**Comment by joewhitsitt** [comment]
I will start a follow-up issue and put it in parking lot

**Pull request merged**
