### PR TITLE
[INRC] Grant theming

### LINKED ISSUE #7846: theme/mockup grants
Current filter page - https://inrc.law.uiowa.edu/iowa-grants-guide
Current node - https://inrc.law.uiowa.edu/grants/iowa-foundation-agricultural-advancement

- theme node teaser and full node
- theming on filter page
- do we want a mockup?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7846

# How to test

```
ddev blt frontend && ddev blt ds --site=inrc.law.uiowa.edu && ddev drush @lawinrc.local uli /grants/iowa-foundation-agricultural-advancement
```
- Code review
- Stress test the layout with maximum and minimum amount of content
- Double check aria is working on application info accordion

There is a code change here that adjusts the work from https://github.com/uiowa/uiowa/pull/7766.  Re-test those instructions and also test the badge/icons on https://housing.uiowa.edu/residence-halls/burge locally and confirm that they are no longer offset.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
pulling to test

**Comment by GaryRidgway** [comment]
I entered a big number in to the `grant size` field and got a WSOD. Specifically I entered the number `1111111111111`, which I was allowed to put in just by typing, and that is what errored it.

<details><summary>The full trace can be found here</summary>

```
The website encountered an unexpected error. Try again later.

Drupal\Core\Entity\EntityStorageException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'field_grant_sizes_value' at row 3: INSERT INTO "node__field_grant_sizes" ("entity_id", "revision_id", "bundle", "delta", "langcode", "field_grant_sizes_value") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5), (:db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11), (:db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15, :db_insert_placeholder_16, :db_insert_placeholder_17); Array ( [:db_insert_placeholder_0] => 126 [:db_insert_placeholder_1] => 281 [:db_insert_placeholder_2] => grant [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => 250 [:db_insert_placeholder_6] => 126 [:db_insert_placeholder_7] => 281 [:db_insert_placeholder_8] => grant [:db_insert_placeholder_9] => 1 [:db_insert_placeholder_10] => en [:db_insert_placeholder_11] => 10000 [:db_insert_placeholder_12] => 126 [:db_insert_placeholder_13] => 281 [:db_insert_placeholder_14] => grant [:db_insert_placeholder_15] => 2 [:db_insert_placeholder_16] => en [:db_insert_placeholder_17] => 1111111111111 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 817 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
Drupal\Core\Database\StatementWrapperIterator->execute(Array, Array) (Line: 44)
Drupal\mysql\Driver\Database\mysql\Insert->execute() (Line: 1400)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->saveToDedicatedTables(Object, 1, Array) (Line: 971)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->doSaveFieldItems(Object) (Line: 718)
Drupal\Core\Entity\ContentEntityStorageBase->doSave('126', Object) (Line: 486)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 806)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object) (Line: 354)
Drupal\Core\Entity\EntityBase->save() (Line: 270)
Drupal\node\NodeForm->save(Array, Object)
call_user_func_array(Array, Array) (Line: 129)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 67)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('node_grant_edit_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object) (Line: 39)
Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

</details> 

I will continue reviewing around this for now

**Comment by GaryRidgway** [comment]
Thinking on the dropdown some more, if the information around it gets too long, it feels a little odd for it to be in the middle of the page,
<details><summary>like so</summary>

</details> 
Should this be moved above or below this area? I'd love to hear other opinions.

Additionally, as the person who originally styled the accordion dropdowns, it pains me that I apparently didn't center the text vertically in them.

**Comment by bspeare** [comment]
@GaryRidgway Thanks for the feedback.  I found that if it is higher up it looks too distracting and if it is lower it is not as visible.

**Comment by bspeare** [comment]
> I entered a big number in to the `grant size` field and got a WSOD. Specifically I entered the number `1111111111111`, which I was allowed to put in just by typing, and that is what errored it.

Thanks, I set a limit to 9 digits and that seems to stop the WSOD.

**Review by GaryRidgway — APPROVED** [review]
With the new changes, I am very happy to APPROVE

**Comment by bspeare** [comment]
Thanks @GaryRidgway!

**Pull request merged**
