### PR TITLE
Feature: card grid fixes

### LINKED ISSUE #3140: Padding on Events grid
The block grid option revealed a style bug related to background padding that causes the cards to mis-align across.

## Steps to reproduce

- Single column, events block (white bg), display as grid (3col)

Screen Shot 2021-02-25 at 12 11 10 PM

### LINKED ISSUE #3145: List grid styles disappear within Page w/ left sidebar layout with an adjacent empty column
# Problem
If have an empty column within a two column layout while using the list grid styles, the grid appears within the layout preview but not when the page is saved because the empty column markup does not render on save. 

# Steps to reproduce

Place a list grid into a Page w/ left sidebar layout.   

**Layout preview:**

Screen Shot 2021-02-26 at 8 50 35 AM

**On save:**

Screen Shot 2021-02-26 at 8 50 47 AM

# Proposed solution
- Update Page w/ left sidebar template to render the grid when saved.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3140 and resolves https://github.com/uiowa/uiowa/issues/3145.

# How to test
`yarn workspace uids_base gulp --development`

1. Using the events block using the grid option on a `v3` site, change the card styles to "stacked" with "hide images" and verify that the top padding even among each card. 
2. Using the events block using the grid/masonry option on a `v2` site, hide the images and verify that the top padding is equal among all the cards. 
3. Place a list grid into a `Page w/ left sidebar` layout with no content in the left sidebar.  Save the page and verify that the grid will appear.   
4. Place a list grid into a `Page w/ left sidebar` layout with a left sidebar menu.  Hide the sidebar from rendering on the node edit screen and verify that the list grid still appears in a grid.

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling down to test.

**Comment by pyrello** [comment]
Screen Shot 2021-03-01 at 12 38 58 PM

I think that, if there is no image, that the card body shouldn't have padding on the top.

**Comment by pyrello** [comment]
Screen Shot 2021-03-01 at 12 55 12 PM

It doesn't look like all the columns aren't rendering the same way. The first column's contents are actually overflowing its boundaries.

**Comment by bspeare** [comment]
> Screen Shot 2021-03-01 at 12 55 12 PM
> 
> It doesn't look like all the columns aren't rendering the same way. The first column's contents are actually overflowing its boundaries.

@pyrello What events filter are you using there?

**Comment by bspeare** [comment]
> Screen Shot 2021-03-01 at 12 38 58 PM
> 
> I think that, if there is no image, that the card body shouldn't have padding on the top.

@pyrello I think we would want to make the adjustment in UIDS first.

**Comment by pyrello** [comment]
> What events filter are you using there?

Department: Graduate College.

I tested 1, 3, and 4 and they appear to work as advertised, although I posted some additional things I noticed.

**Comment by pyrello** [comment]
> I think we would want to make the adjustment in UIDS first.

I'm fine if that update doesn't make it in here. Just pointing that seems like the desired effect.

**Comment by pyrello** [comment]
@bspeare I'm testing this again and encountering some weird behavior. I'm not sure if it is something about my local environment, but when I sync the default site and attempt to drag the events block into a one column section, it cannot be dragged. The other elements are able to be dragged still. Are you seeing this behavior also?

**Comment by bspeare** [comment]
@pyrello Yup, I think that's a separate issue.

**Review by pyrello — APPROVED** [review]
As best I can tell, this is working as intended.

**Comment by pyrello** [comment]
It is actually draggable, but not where the event card sits.

**Pull request merged**
