### PR TITLE
Initial platform email setup.

### LINKED ISSUE #3498: As a site owner, I want generated emails sent reliably without risk of being filtered.
## Issue

There is very little we can do as developers to deal with emails that come from our websites. Our websites are increasingly using webform to create workflows for their organizations and expect email delivery to just work.

>The Cloud Platform email servers are a shared resource, so you can’t send mass emails (such as marketing messages or newsletters). This service is provided as a courtesy and has no uptime or service level agreements associated with it.

There is also a disconnect between emails coming from Acquia and how Office365 processes them causing developers to converse both with Acquia and ITS Email when issues arise.

## Proposed Solution

- [x] Reach out to the ITS Email Team about being our "third-party" mail service provider and discuss steps on making it happen. https://docs.acquia.com/cloud-platform/manage/email/3rdparty/
- [x] Deploy to standard/custom of 701-3 on 01/24
- [x] Dentistry - either use reply_to and change their site mail b/c its a subdomain right now or just implement a much lighter hook_mail_alter to set all from addresses to the noreply address
- [x] icgov
- [x] grad
- [x] clas

### PR DESCRIPTION
**Pull request by richardbporter**
Related to #3498 

### Testing
- Go to https://default.dev.drupal.uiowa.edu/admin/config/development/reroute_email and temporarily disable email rerouting.
- Go to https://default.dev.drupal.uiowa.edu/email-test and submit the form with different variations:
  - From a uiowa.edu address with a from name provided.
  - From a uiowa.edu address with no from name provided.
  - From a non-uiowa.edu address with a from name provided.
  - From a non-uiowa.edu address with no from name provided.
  - To multiple email addresses.
- Check your inbox for the messages and inspect them.
- Reply to the messages and inspect the reply-to address.
- Test brand dev according to https://github.com/uiowa/uiowa/pull/4619#issuecomment-1006822212
- Test D7: https://org-iowareadingresearch.dev.drupal.uiowa.edu/contact-us

Feel free to reconfigure the dev webform to test other email functionality - cc, bcc, etc. Note that multiple from addresses do not currently work, even with legacy email in prod.

### CODE REVIEW

**Comment by richardbporter** [comment]
@joewhitsitt can you help write and/or test email functionality for the brand website in the dev environment?

**Comment by joewhitsitt** [comment]
I should probably write this down somewhere:

- There is a workflow based email that is sent out when a lockup is approved to the user that created it
- There is a daily email that goes to the site-email address that pulls together all needs review lockups

## To Test

- Disable reroute
- Change site email to something else
- Create a lockup with your account, submit it for review.
- Your lockup should trigger the daily review digest, so trigger the drush command (brand_core:lockup-digest) that sends the email to approvers (site email)
- Approve your lockup and provide a message. This should send another email to you the lockup creator with a formatted email.

**Comment by richardbporter** [comment]
Brand isn't working on dev. Getting an error like `unknown shorthand flag: 'b' in -bs`. However, changing the SwiftMailer transport mode to `t` seems to work. I exported that config change in 52d71b1 but it also exported some permission changes that I don't quite understand because I did a fresh sync from prod. Looking for help on reviewing those.

**Comment by richardbporter** [comment]
Haven't merged 52d71b1 into develop yet.

**Comment by joewhitsitt** [comment]
The brand permissions _should_ not need to be here. v2 should already be removing these:
https://github.com/uiowa/uiowa/blob/main/config/features/sitenow_v2/config_split.patch.user.role.webmaster.yml
https://github.com/uiowa/uiowa/blob/main/config/features/sitenow_v2/config_split.patch.user.role.editor.yml

**Comment by richardbporter** [comment]
> The brand permissions _should_ not need to be here. v2 should already be removing these: https://github.com/uiowa/uiowa/blob/main/config/features/sitenow_v2/config_split.patch.user.role.webmaster.yml https://github.com/uiowa/uiowa/blob/main/config/features/sitenow_v2/config_split.patch.user.role.editor.yml

So those are just changes that should not be committed? I wasn't sure if CS2 fixed that part of our workflow or not.

**Comment by joewhitsitt** [comment]
Going to look to @pyrello on this to be sure, but it doesn't seem to be cascading as I would expect it to

**Comment by pyrello** [comment]
> Going to look to @pyrello on this to be sure, but it doesn't seem to be cascading as I would expect it to

Yeah, this doesn't look right. Without knowing what commands were run, hard to say if this is a bug with CS2 or not.

**Comment by pyrello** [comment]
It looks like the brand site split is missing the `stackable: true` property, which would potentially be the cause of this issue.

**Comment by joewhitsitt** [comment]
@richardbporter can you add that stackable true as part of this PR?

**Comment by joewhitsitt** [comment]
Sondra has been pretty responsive in the past if you want to check whether emails have been working or if we need to see if the digest emails fire when this goes live

**Comment by richardbporter** [comment]
I think this ready for initial review for D9. In the meantime, I will start backporting to D7.

**Comment by bspeare** [comment]
I can test this.

**Comment by bspeare** [comment]
Looks like I don't have access to this for testing:

Screen Shot 2022-01-07 at 10 41 23 AM

**Comment by richardbporter** [comment]
> Looks like I don't have access to this for testing:

Looks like that isn't a permission I can grant. I've removed those steps from the PR testing steps for now.

**Comment by richardbporter** [comment]
I've set this up on uiowa702 dev for https://org-iowareadingresearch.dev.drupal.uiowa.edu/contact-us. I changed the form to email our shared inbox instead of the person that was configured.

**Comment by bspeare** [comment]
Is the expected message for all the emails supposed to be "Thanks for your message" instead of the content of the message field?

Screen Shot 2022-01-10 at 8 56 21 AM

**Comment by richardbporter** [comment]
> Is the expected message for all the emails supposed to be "Thanks for your message" instead of the content of the message field?
> 
> Screen Shot 2022-01-10 at 8 56 21 AM

Yea I set the email body to custom text in the webform email handler.

**Comment by bspeare** [comment]
Is the "From name" supposed to show up anywhere?

**Comment by bspeare** [comment]
- [x] Tested https://default.dev.drupal.uiowa.edu/email-test and it worked with all the test cases.   I didn't see the "From name" used if that is an issue. 
- [x] Tested Test brand dev according to #4619 and all steps worked. 
- [x] Tested D7: https://org-iowareadingresearch.dev.drupal.uiowa.edu/contact-us and it sent an email to its-web@uiowa.edu 

I'm happy to approve this if the work on this is done.

**Comment by richardbporter** [comment]
> Is the "From name" supposed to show up anywhere?

Sorry, I hadn't configured the D9 webform to use the From Name properly. It is now. If a From Name is not provided for non-uiowa.edu domains, our code should set it to the site name.

**Review by bspeare — APPROVED** [review]
All of the testing criteria worked for me.

**Comment by richardbporter** [comment]
> All of the testing criteria worked for me.

Thanks! I don't think there is more work here but I haven't heard back on that header yet. I guess I'll mark this blocked until we know that no more changes are needed on our end.

**Pull request merged**
