### PR TITLE
Iowa Now People Migration

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/5821

# Notes

There are ~4 temp person nodes that are created to deal with the OSC contact referencing. Most likely these are referenced entities that no longer exist in the source db. This causes some pretty scary looking errors on the command line, but there should only be a few and it should finish.

# Todo

- ~~Output redirects created~~ Removed in favor of the "sit and wait 404s" method
- Run in DEV for review
- ~~Look into warning: `Undefined array key "date_limiter" BaseNodeSource.php:124`~~ - _@cory-skeers fixed it!_
- ~~Re-wire staff/experts tids~~
- ~~Investigate breaking up job titles by delimiter `;` into multi value position field.~~  - _@cory-skeers fixed it!_

# How to test

- Sync now.uiowa.edu locally in dev desktop from uiowa703 (db name is now_uiowa_edu)
- git checkout now_migrate_person && git pull
- ddev blt ds --site=now.uiowa.edu
- ddev drush @now.local en now_migrate -y && ddev drush @now.local uli /admin/config/sitenow/sitenow-migrate
- Complete the form following the help text
- ddev drush @now.local ms
- ddev drush @now.local mim --all

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Trying to separate positions based on `;` but the following is failing for all:

```yml
  field_person_position:
    plugin: explode
    source: field_person_job_title
    delimiter: ;
```

**Comment by cory-skeers** [comment]
> Trying to separate positions based on `;` but the following is failing for all:
> 
> ```yaml
>   field_person_position:
>     plugin: explode
>     source: field_person_job_title
>     delimiter: ;
> ```

Got this part working. Running it, I did end up with 63 failures, though...not sure if that was there before or if I broke something.

**Comment by joewhitsitt** [comment]
>I did end up with 63 failures, though.

Before it was completely successful 177 or whatever. I meant to change the delimiter to semicolon + space. With 63 failures it seems like it might be failing on the ones that don't have a semicolon or entities without the field filled out?

**Comment by cory-skeers** [comment]
Original site has `cristóbal-mckinney` as an alias, but it's `cristobal-mckinney` in the auto-generated alias post-migration. Doing a quick scan through the database, I _think_ this is the only original alias that had an accent and would be different for this reason, so it may be worth skipping the alias migration. Not 100% sure it's the only one, though--depends how good my eyes did at spotting accents.

**Comment by joewhitsitt** [comment]
that is the one i spotted too

**Comment by cory-skeers** [comment]
> > I did end up with 63 failures, though.
> 
> Before it was completely successful 177 or whatever. I meant to change the delimiter to semicolon + space. With 63 failures it seems like it might be failing on the ones that don't have a semicolon or entities without the field filled out?

Hrm...It doesn't look like there are any empty values for the field, and there are 49 entries w/semicolon and 128 w/out. I'll do some more pokin'.

**Comment by cory-skeers** [comment]
Still not sure what was going on with the errors. I tried doing the same thing in prepareRow and it gets the job done without the errors.

**Comment by joewhitsitt** [comment]
Thanks for helping with this @cory-skeers. Unless you notice anything else, I am thinking we should remove the redirects bit and run this is DEV for customer review.

Perhaps we should create a separate task to make the redirects comparison. Until redirect expiration is a thing, anything to keep that table small would be helpful.

**Comment by cory-skeers** [comment]
> Thanks for helping with this @cory-skeers. Unless you notice anything else, I am thinking we should remove the redirects bit and run this is DEV for customer review.
> 
> Perhaps we should create a separate task to make the redirects comparison. Until redirect expiration is a thing, anything to keep that table small would be helpful.

That sounds good to me. Not noticing anything else outside the couple error-ed people, but it's a small enough number to be able to manually clean up. Similar with redirects--I think it's better to just remove it, and if we need to re-look into how that process works for future migrations that have more of a sure need for migration, that'd be a better time.

**Review by pyrello — APPROVED** [review]
Reviewed code updates and approving based on successful run in dev and customer feedback.

**Comment by joewhitsitt** [comment]
Putting this up for technical review so it can merge into main and clear the way from further Now migrations. More customer feedback can be collected and implemented before the migration is run in PROD.

**Pull request merged**
