### PR TITLE
Create uiowa:multisite:transfer command.

### LINKED ISSUE #4180: Create a process for moving sites between servers
Created from https://github.com/uiowa/uiowa/issues/4153#issuecomment-923452000.

Here is a theoretical idea for how this could work:
1. Release a code update to create a temporary drush alias file for the site at the new server using the `.prod.drupal`. This will be necessary for syncing the database and files later.
2. Set up the `.prod.drupal` domain on the new application.
3. Create the database(s) for the site on the new application.
4. Run the site install command on the new server.
5. Sync the database and files from the current site to the new site.
6. Move domain from the current application to the new application.
7. Release a code update which updates the site's permanent drush alias file to point to the new server.
8. _*Optional:_ If there is any reason why you need to continue to access the old version of the site, you may need to update the temporary drush alias file to point to the old server.
9. Whenever you are done, release a code update to remove the temp drush alias file.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #4180 

### Test uiowa:multisite:create still works.
- `blt umc foo.com --no-db --no-commit`
- Discard changes.

### Test uiowa:multisite:transfer in test mode.
- Open https://sitesgis.stage.drupal.uiowa.edu in an incognito window or another browser. Check this periodically during the process to see what an anonymous user would see.
- In another browser, go to https://sitesgis.stage.drupal.uiowa.edu/admin/reports/status/php and look under the Environment section. The user should be uiowa indicating its on the uiowa application.
- Check out this branch locally.
- Run `vagrant ssh`.
- Run `blt uiowa:multisite:transfer --test-mode`.
- Select gis.sites.uiowa.edu. Transfer to uiowa02. Confirm.
- Read the command output and ensure it makes sense. Suggest any changes. Ensure the command completes with no error output. Select `yes` when asked to delete the old database and files - the database is not deleted in test mode, only files.
- When the command is complete, run `drush @uiowa.test ssh 'ls -l | grep gis.sites.uiowa.edu' --cd /mnt/gfs/uiowa.test/sites/` and ensure there is no output, i.e. the old files directory was deleted.
- Go to https://sitesgis.stage.drupal.uiowa.edu and log in - note there may be a delay if the AC domain task has not completed. Its also possible the IDP consumed the metadata while this domain was removed. Check the PHP admin report again and it should indicate uiowa02. Check the files overview - there should no broken images. Check that not all users are blocked.
  - Optional: SSH into uiowa02.test and check files exist. 
- Run `git status` and check to make sure there are no changed files. Run `git show` which shows the last commit. It should only have file changes in `drush/sites/sitesgis.site.yml`. Inspect the changes.
- Review the command code.

At this point the site is still live on uiowa and should probably be transferred in prod or transferred back in test mode so its not in a wonky state.

### Test uiowa:multisite:transfer in prod mode.
- Pair/mob on transferrinig gis.sites.uiowa.edu in production when ready.

### CODE REVIEW

**Comment by richardbporter** [comment]
@joewhitsitt I kinda volunteered gis.sites.uiowa.edu to be the test case here. 🙏🏻

**Comment by joewhitsitt** [comment]
i'd be willing to pair/mob through this with you @richardbporter

**Comment by pyrello** [comment]
Ditto.

**Comment by richardbporter** [comment]
Trying something on this quick.

**Comment by richardbporter** [comment]
I was wrong about the domain operations. We can kick those off immediately and they can run simultaneously. The varnish clear didn't even error for me. I thought that might if the domain operation wasn't completed but it seemed to work.

**Review by pyrello — APPROVED** [review]
Tested via running on prod.

**Review by joewhitsitt — APPROVED** [review]
i am the proud owner of a site on uiowa02

**Pull request merged**
