### PR TITLE
Classrooms - Room Schedule Pager

### LINKED ISSUE #6476: Classrooms room schedule display pager?
# Story

As a classrooms website owner, I would like our room schedule to be paginated or scrollable so that when there are many items it doesn't push the rest of the content down the page.

# Additional info

Example https://classrooms.prod.drupal.uiowa.edu/ucc-1100

# Proposed solution

- pager or scroll

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/6476

_Note: "Mini" pager is a views thing. Not sure it is available for something like this._

# Options to decide:

- how many to show per page
- how many page buttons to show in between first/last buttons

Screenshot 2023-06-12 at 3 03 13 PM

# To Test

```
ddev blt ds --site=classrooms.uiowa.edu && ddev drush @classrooms.local uli ucc-1100
```
- Confirm pager is loading and showing the correct events.
- Try find hole in caching strategy

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>## Options to decide:
>- how many to show per page
>- how many page buttons to show in between first/last buttons

At EoD, folks didn't have objections to the current settings (display 3 events, 3 pager buttons)

**Comment by e-marie-w** [comment]
Pulling down to test

**Review by e-marie-w — APPROVED** [review]
Pager looks and works great. I agree the current settings for 3 events, 3 buttons are good. I also tested in a private window as anonymous user and didn't run into any issues. And, I looked at a couple of pages with no events or only two events to check the pager wasn't showing up in those cases.

**Comment by joewhitsitt** [comment]
Thanks @e-marie-w

**Pull request merged**
