### PR TITLE
i2556 mentor view

### LINKED ISSUE #2556: Add a view to display Grad College SROP available mentors
# Story

As a [SROP Scholar](https://www.grad.uiowa.edu/ogi/srop/past-scholars) I want view a list of mentors so that I can learn about available opportunities to work with them.

Example: https://www.grad.uiowa.edu/ogi/srop/available-mentors

# Proposed solution

- [x] Build a view that lists Mentor content items split into groups by Department.
- [x] Add the view to the grad.uiowa.edu split and export new items there.

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #2556 

# How to test

1. `blt ds —site=grad.uiowa.edu`
2. `blt frontend`
3. Navigate to http://grad.local.drupal.uiowa.edu/dei/srop/mentors and make sure there’s a teaser view of mentors grouped by their department

### CODE REVIEW

**Comment by pyrello** [comment]
The look of this page can be similar to the scholar listing pages, using a styled teaser rather than a table.

**Comment by dnkemper** [comment]
@pyrello Awesome! I was going to reach out to you after standup to clarify how you were wanting me to go about this. Thank you so much!

**Comment by bspeare** [comment]
Not sure what you are planning here, but do want to keep this within the realm of the teasers built for admissions?

Student profiles (missing teaser image for some reason):

Screen Shot 2021-01-20 at 10 38 17 AM

Counselors:

Screen Shot 2021-01-20 at 10 40 32 AM

**Comment by pyrello** [comment]
I was thinking the latter, although I hadn't seen the former before today and I'm kind of into it.

**Comment by pyrello** [comment]
Pulling down to test.

**Review by pyrello — APPROVED** [review]
There is some weirdness with the display of the images on the mentor page, but I'll follow up with an issue to address that.

**Comment by dnkemper** [comment]
@pyrello Thank you!

**Pull request merged**
