### PR TITLE
Vagrant provision python fix

### PR DESCRIPTION
**Pull request by ethanstjohn**
This issue caused my local dev environment to be unable to run "vagrant up", "vagrant provision" with this error listed in the picture. This fix is listed here.
https://github.com/geerlingguy/drupal-vm/issues/530#issuecomment-207848649

Screen Shot 2020-07-21 at 12 56 47 PM

### CODE REVIEW

**Comment by richardbporter** [comment]
I'm trying to test this but `vagrant up` is hanging on the `Download Solr` step. Not sure if it is related.

**Comment by ethanstjohn** [comment]
> I'm trying to test this but `vagrant up` is hanging on the `Download Solr` step. Not sure if it is related.

Is it still hanging up on it?

**Review by richardbporter — APPROVED** [review]
Finally finished. Tested stop/start as well as a fresh `vagrant up` after a `vagrant destroy`. Not sure why ran into this problem but it doesn't seem to cause any issues for me.

**Comment by richardbporter** [comment]
I don't think this will be necessary anymore after https://github.com/uiowa/uiowa/pull/2124

**Pull request merged**
