### PR TITLE
[IWP] Migrate writer bio

### LINKED ISSUE #7699: migrate writers bio content
# Story

As an IWP site owner, I would like our writers bio content to be migrated from the current site to the new site so we do not have to manually recreate all that content.

# Additional Info

They thought there was more value in getting these migrated sooner than later and worth the cost of any duplicate updates.

They want to migrate all writer bio content

They want us to create redirects from old paths to new paths as part of the migration.

**Mappings - v3 - v1**

- [x] Title - title
- [x] Writer Image - field_image_attach - current allows unlimited, v3 only allows 1.
  - alt
  - title
- [x] Photo Credit - field_writer_photo_credit
- [x] Session - field_writer_session_status - migrating select list into taxonomy - create term as part of migration - current allows unlimited v3 only allows 1
- [x] Countries - taxonomy_vocabulary_1 - create terms as part of migration - current is hierarchical - no need to keep hierarchy - just migrate deepest terms - can have multiple
- [x] Language - field_writer_lang - migrating select list into taxonomy - create terms as part of migration - can have multiple
- [x] Summary - body summary - not sure if they used this currently but is available
- [x] Body - body
- [x] Family Name - field_writer_family_name
- [x] Given Name - field_writer_given_name
- [x] Writing Sample - field_writer_sample - 1
- [x] Writing Sample Original Language - field_writing_sample_in_original - 1
- [x] Media - field_writer_yt_link - map link to link and set the text to "[name] On the Map Interview"

```[tasklist]
### Proposed Solution
- [x] Create migration locally and test
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7699

# How to test

```
ddev blt ds --site=iwp.uiowa.edu && ddev drush @iwp.local en iwp_migrate -y && ddev drush @iwp.local uli admin/config/sitenow/sitenow-migrate
```

- Configure SiteNow Migrate following instructions for DevDesktop. 
  - Database: `iwp`.
  - User: `root`
  - Host: `host.docker.internal`
  - Port: `33067`
  - Base URL: `https://iwp.uiowa.edu`
- Check the migration status: `ddev drush @iwp.local ms`
- Run all migrations `ddev drush @iwp.local mim --all  `  
- or
- Import the countries: `ddev drush @iwp.local mim iwp_countries`
- Import the writer bios: `ddev drush @iwp.local mim iwp_bio`
- Import the redirects: `ddev drush @iwp.local mim iwp_bio_redirects`
- Rollback `ddev drush @iwp.local mr --all`

Go to https://iwp.uiowa.ddev.site/residency/participants to view all. 
Check against live site to make sure that redirects, alt text, files, etc have all been correctly migrated.

### CODE REVIEW

**Comment by e-marie-w** [comment]
Screenshot 2024-05-28 at 2 29 35 PM

I ran the migrations individually and got these results. I rolled back and tried running them all at once, same result. I thought maybe the two extra imports were related to content already existing on the site. I rolled back, deleted the three existing writer bios, ran all migrations again. Same results every time. 

The redirect error shows up at around 70%, reads `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'NqOJ8Yo8Od83gmGeylhP0Hn_VBTUMiXNIL7Mi97ssI4' for key 'hash'`. End message is `iwp_bio_redirects Migration - 1 failed` but there are 13 unprocessed according to the table. 

I'm going to poke at this but also wanted to make it visible.

**Comment by e-marie-w** [comment]
I forgot how media works with migrations. Sometimes the linked files don't work because v3 names files differently than v1 - like the writing samples on https://iwp.uiowa.ddev.site/writers/2023-resident/nektaria-anastasiadou vs https://iwp.uiowa.edu/writers/nektaria-anastasiadou. Does that fix itself when the site goes live?

**Comment by joewhitsitt** [comment]
> I forgot how media works with migrations. Sometimes the linked files don't work because v3 names files differently than v1 - like the writing samples on https://iwp.uiowa.ddev.site/writers/2023-resident/nektaria-anastasiadou vs https://iwp.uiowa.edu/writers/nektaria-anastasiadou. Does that fix itself when the site goes live?

I don't have it pulled down, but if the media is migrated over, the references on the node should link to them just fine align with whatever domain it is hosted at. The path, not the filename changes. If the body content is migrated over without creating media entities for links in the content, that is where the trouble starts with the need for broken link reports, etc.

**Comment by e-marie-w** [comment]
I spoke too soon in EoD, deleting the existing bios and files did not fix the media issue for that one page. I tested several more and the only other one exhibiting that behavior is the other bio that exists on prod at this time. 

So, maybe we make a note to double-check and manually update those files if needed?

**Review by e-marie-w — APPROVED** [review]
Migration is working as expected!

**Pull request merged**
