### PR TITLE
Set all featured images to stack for mobile

### LINKED ISSUE #5507: As a SiteNow editor, I can see the page title and featured image "stacked" for mobile
# Story

As a Iowa Now editor, I can see the page title and featured image "stacked" for mobile so that the page title and featured image have better visibility. 

Currently, article titles get a bit lengthy on mobile.   

Screen Shot 2022-08-01 at 11 15 43 AM

# Proposed solution

Screen Shot 2022-08-01 at 11 34 00 AM

Implement the `banner--stacked` class for https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/layouts/layout--onecol--background.html.twig. 
- https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/layouts/onecol--background.scss

Revisit styles using the `page-title` class:

- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/components/banner.scss
- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/components/typography/headings.scss

Revisit breadcrumb colors:
- https://github.com/uiowa/uiowa/blob/09ed2ad1c947325ccd3184dcf1a4565a1296baa7/docroot/themes/custom/uids_base/scss/layouts/onecol--background.scss#L44-L50

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/5507. 

This effects all pages using the featured image:
- `blt frontend`

Test user story _As a SiteNow editor, I can see the page title and featured image "stacked" for mobile_

**Test the featured image on the page and article content types:** 
- On mobile the image should be stacked above the the breadcrumbs and page title.
- On desktop the breadcrumbs/page title should be sitting on top of the image. 

**Sync and test the sites below:**

- 2plus2 -  https://admissions.uiowa.ddev.site/academics/2plus2/marketing-kirkwood-community-college
- Area of study - https://admissions.uiowa.ddev.site/academics/english-and-creative-writing
- Event series - https://admissions.uiowa.ddev.site/next-step-iowa-admitted-student-days
- Student profiles - https://admissions.uiowa.ddev.site/student-profiles/anna-watts
- Topic Collection - https://mentalhealth.uiowa.ddev.site/help
- Residence Hall - https://housing.uiowa.ddev.site/residence-halls/currier
- Randomly test any other sites using `layout_header` https://github.com/uiowa/uiowa/search?p=3&q=layout_header

### CODE REVIEW

**Comment by cory-skeers** [comment]
I'm wondering about the mobile experience on pages that have a small featured image when the image itself might be quite a bit taller.

https://user-images.githubusercontent.com/49074566/200403638-67d39a37-d2b5-4a93-ad01-22dcb117f53c.mov

Any time there's stacking instead of an overlay I'd expect the page's content to be pushed down some, but in this example it felt like the content started considerably further down the page in relation to the non-mobile view.

Not sure there's much to do here, but wanted to point it out in case there was some wizardry that could be added.

**Comment by bspeare** [comment]
@cory-skeers good point.  Let me take a look at that.

**Comment by cory-skeers** [comment]
Tested on a v2 (hawkeyemarchingband), and the title still has the overlay treatment despite properly being stacked:

image

**Comment by bspeare** [comment]
@cory-skeers I added a solution for small banners like the 2plus2.   I think medium and large banners scale down to similar mobile heights/aspect ratios so I'm not sure if those would be worth pursuing here.   Could you demo this in the mid-sprint demo for me tomorrow?

**Comment by cory-skeers** [comment]
> @cory-skeers I added a solution for small banners like the 2plus2. I think medium and large banners scale down to similar mobile heights/aspect ratios so I'm not sure if those would be worth pursuing here. Could you demo this in the mid-sprint demo for me tomorrow?

Sounds good, and can do. Thanks!

**Comment by bspeare** [comment]
@cory-skeers weird, that one is showing up for me like this:

Screen Shot 2022-11-07 at 3 06 50 PM

Maybe try a fresh `blt frontend`?

**Comment by cory-skeers** [comment]
> @cory-skeers weird, that one is showing up for me like this:
> ...
> Maybe try a fresh `blt frontend`?

That fixed it! Not sure why I had an issue with that site and not others, but I'm glad it was just me.

**Comment by cory-skeers** [comment]
Testing all looks great, and I think the adjustment for small featured images fits what I would expect/hope for with this kind of functionality, and agree that it's not necessary for medium/large versions.

Going to hold off approving until midsprint for team feedback and visibility, but otherwise I think this is good to go.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and this is working great!

Midsprint demoed for visibility/feedback, and looks good to go.

**Pull request merged**
