### PR TITLE
Preparations for Drupal 9

### PR DESCRIPTION
**Pull request by pyrello**
Working to accomplish the steps from "Before upgrading" in these instructions: https://support.acquia.com/hc/en-us/articles/360045796154-Upgrading-from-BLT-11-to-BLT-12
* Upgraded to `drupal/core:^8.9.7`.
* Ran `composer update`.
* Used BLT's recipe to migrate to using `drupal/core-composer-scaffold` instead of `drupal-composer/drupal-scaffold`. This also has the effect of moving to `drupal/core-recommended` instead of `drupal/core`.
* ~Fixed a bunch of new phpcs errors related to arrays needing to be broken up over more than one line when the total line length was greater than 80 characters.~ - Fixed in #2216 

# To test
Review the list of changes below (specifically for paragraphs and webform) and test against sites accordingly. **_If possible, please post comments below about what you have tested or plan to test and what site(s) you are testing/have tested against._**

# Composer updates
Both with the switch to `drupal/core-recommended` and running `composer update` there are a lot of updated dependencies besides what is shown in `composer.json`. `drupal/core-recommended` locks Drupal's dependencies to specific versions, so a lot of those packages are actually downgraded in this update. There are also the following contrib updates:
* drupal/block_content_permissions: 8.x-1.9 => 8.x-1.10
* drupal/config_filter: 8.x-1.5 => 8.x-1.6
* drupal/config_split: 8.x-1.4 => 8.x-1.5
* drupal/date_recur: 8.x-2.0 => 8.x-2.2
* drupal/embed: 8.x-1.3 => 8.x-1.4
* drupal/features: 8.x-3.8 => 8.x-3.11
* drupal/google_tag: 8.x-1.3 => 8.x-1.4
* drupal/honeypot: 2.0.0 => 2.0.1
* drupal/inline_entity_form: 8.x-1.0-rc6 => 8.x-1.0-rc7
* drupal/lazy: 8.x-3.4 => 8.x-3.5
* drupal/linkit: 8.x-5.0-beta10 => 8.x-5.0-beta11
* drupal/masquerade: 8.x-2.0-beta3 => 8.x-2.0-beta4
* drupal/memcache: 8.x-2.0 => 8.x-2.1
* drupal/menu_admin_per_menu: 8.x-1.1 => 8.x-1.3
* drupal/menu_breadcrumb: 8.x-1.13 => 8.x-1.14
* drupal/mimemail: 8.x-1.0-alpha2 => 8.x-1.0-alpha3
* drupal/override_node_options: 8.x-2.4 => 8.x-2.5
* drupal/paragraphs: 8.x-1.11 => 8.x-1.12
* drupal/schema_metatag: 8.x-1.6 => 8.x-1.7
* drupal/search_api: 8.x-1.16 => 8.x-1.17
* drupal/search_api_autocomplete: 8.x-1.3 => 8.x-1.4
* drupal/views_ical: 8.x-1.0-alpha4 => 8.x-1.0-alpha5
* drupal/webform: 8.x-5.13 => 8.x-5.20 **Includes database updates**
* drupal/workbench_email: 8.x-1.6 => 8.x-1.7

### CODE REVIEW

**Comment by pyrello** [comment]
Opened #2216 to break this up a bit, so there are not so many changes to keep track of in one PR.

**Comment by pyrello** [comment]
This is currently blocked by #2160, which requires multiple PRs to happen, so it cannot be done in this PR.

**Comment by joewhitsitt** [comment]
pulling down for review

**Comment by joewhitsitt** [comment]
gosh darn, that is quite the jump... drupal/webform: 8.x-5.13 => 8.x-5.20 :drupal_cry:

**Comment by joewhitsitt** [comment]
so, i might have done it wrong, but i don't think there were any exports for v2 or collegiate and the exports otherwise seem limited in scope to files that don't exist in other splits. going to continue testing. little worried about node_revision_delete as I just closed a bump PR related to it...

I will remove core.entity_form_display.block_content.uiowa_collection.default, core.entity_form_display.block_content.uiowa_slider.default since they seem to cause failures

**Comment by joewhitsitt** [comment]
Gosh. Okay, sorry for messing up the PR with bad commits. Here are my notes thus far:

Most modules were a simple bump, but I spent time testing:

- inline_entity_form as it relates to article author
- lazy
  - Looks like we lost our lazy fade-in effect:
https://www.drupal.org/project/lazy/issues/3171723
- linkit
  - thought there was unwanted behavior with opening links in new windows default, but it is caused by linkit_media_library. ultimately, my "fix" kept the value from being saved. removed.
- menu_breadcrumb as it relates to Article noodle
- mimemail as it relates to brand lockup digest
- workbench_email as it relates to brand lockup approval
- paragraphs as it relates to v2

I plan on testing node_revision_delete again and webform still.

**Comment by pyrello** [comment]
@joewhitsitt Just to clarify, do you consider the behavior with linkit to be a regression?

**Comment by joewhitsitt** [comment]
Not ideal IMO, but not a regression:  https://git.drupalcode.org/project/linkit_media_library/-/blob/1.0.x/src/LinkitMediaLibraryEditorOpener.php#L78

**Comment by pyrello** [comment]
So far, I have tested against coronavirus.uiowa.edu and spot checked some layout builder and paragraph blocks functionality.

**Comment by joewhitsitt** [comment]
I suggest we don't update node_revision_delete for the same reason I stopped the update earlier. We should probably hardcode rc2 release so it doesn't try to update again. https://github.com/uiowa/uiowa/pull/2281

Steps to reproduce:
- Logged in, go to https://brand.local.drupal.uiowa.edu/node/926/edit. Make a small revision. Save as draft. There will be 11 revisions (max of 10) https://brand.local.drupal.uiowa.edu/node/926/revisions
- Run cron.

In version rc2, the oldest revision is deleted as expected. in rc3, it is not.

Since there was an update hook and config change, this downgrade will break existing synced sites in this branch.

**Comment by pyrello** [comment]
To clarify, there does seem to be a regression - or new unexpected functionality - that causes the oldest revision not to be deleted when the newest revision is a draft.

I tested this against a dev site (which is still using the rc2 version of node_revision_delete) and after running cron there were always only 10 revisions regardless of the status of the node.

**Comment by joewhitsitt** [comment]
Though I am a bit concerned there have been 250 commits between webform versions, I am not noticing any thing sticking out as odd/broken. We are already two release behind with this PR... https://www.drupal.org/project/webform/releases/8.x-5.22

**Comment by joewhitsitt** [comment]
I am okay with moving forward with node_revision_delete rc3 after testing more with @pyrello

**Review by joewhitsitt — APPROVED** [review]
No obvious broken things. I think we got the config in a good spot. Drupal 9 here we come!

**Comment by richardbporter** [comment]
I'm seeing untracked files locally after `composer install`:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        docroot/.gitignore
        docroot/modules/.gitignore
        docroot/profiles/.gitignore
        docroot/sites/.gitignore
        docroot/sites/default/default.services.yml
        docroot/themes/.gitignore

```

**Comment by pyrello** [comment]
When we jump to D9, I think we'll bump up to webform version `6.x` (notice no `8.x-`)

**Comment by pyrello** [comment]
@richardbporter I believe that the new scaffold tool adds additional files that weren't being added before. I'm not sure if we should add them or not.

**Comment by richardbporter** [comment]
Looks like they just ignore the readme so it is not deployed in a build artifact, I'm guessing. I think we should commit those and then remove the .gitkeep next to each one.

**Comment by pyrello** [comment]
Sounds good to me.

**Comment by richardbporter** [comment]
I _think_ we want this. :)

**Comment by richardbporter** [comment]
Sorry for jumping in late. After tests pass 👍 .

I added the default services file since we remove that from "standard" new sites but it'd be nice to have tracked. That way developers can copy it to a multisite if needed.

**Comment by pyrello** [comment]
Thanks for wrapping things up, @richardbporter! Thanks for testing, @joewhitsitt!

**Pull request merged**
