### PR TITLE
[Facilities] Alert updates

### PR DESCRIPTION
**Pull request by bspeare**
Relates to https://github.com/uiowa/uiowa/issues/6880. 

Templates:
- Branded Template: `UI 1 row x 1 col + 1 row x 2 cols` https://apps.its.uiowa.edu/dispatch/communications/1238605612
- Template with conditionals that don't seem to be working: https://apps.its.uiowa.edu/dispatch/templates/1238199082
  - Test out at https://facilities.prod.drupal.uiowa.edu/node/3501/dispatch and adding your email address to https://apps.its.uiowa.edu/dispatch/communications/1238605612

# How to test

## Test on facilities

```
ddev blt ds --site=facilities.uiowa.edu && ddev drush @facilities.local uli 
```

- Confirm that the title is not displaying on the alert node edit form only in Facilities split
- Confirm that the category field is required only in Facilities split
- Confirm https://apps.its.uiowa.edu/dispatch/templates/1238199082 is using conditionals for all fields and that project number appears at the bottom of the email. 
- Confirm that project number has been added to the bottom of the branded email template https://apps.its.uiowa.edu/dispatch/communications/1238605612. 

## Test on default

```
ddev blt ds --site=default && ddev drush @default.local config-split:activate sitenow_alerts -y && ddev drush @default.local uli node/add/alert
```

- Confirm that title is still displaying on node edit form for alert
- Confirm that category field is not required

### CODE REVIEW

**Comment by bspeare** [comment]
This is ready for review.  The latest on the email templates is posted here https://github.com/uiowa/uiowa/issues/6880#issuecomment-1735608404.

**Comment by bspeare** [comment]
Dispatch responded with this suggestion if someone wants to try it out in https://apps.its.uiowa.edu/dispatch/templates/1238199082:

```
<!--- <@placeholder name='alertOne' type='text' help='Alert One' /> --->
<!--- <@placeholder name='alertTwo' type='text' help='Alert Two' /> --->

<#if placeholder_alertOne??>
<p>AlertOne: ${placeholder_alertOne}</p>
</#if>

<#if placeholder_alertTwo??>
<p>AlertTwo: ${placeholder_alertTwo}</p>
</#if>

```

**Comment by joewhitsitt** [comment]
I updated the existing template wired up to the communication with the conditionals above. I don't see the branded version still available to update. Not sure what was done previously for that.

Here is the output or lack there of for the basic html template. Seems to work as expected:

Screenshot 2023-09-27 at 1 22 48 PM

**Comment by joewhitsitt** [comment]
>This is ready for review.

Going to review the rest of this PR.

**Comment by joewhitsitt** [comment]
Oops. I messed it up:

Screenshot 2023-09-27 at 3 41 27 PM

Capturing the contents of that template and switching back to what was there previously..
<details>

```txt
<!--- <@placeholder name='AlertCategory' type='richtext' help='Alert Category' /> --->
<!--- <@placeholder name='AlertDate' type='richtext' help='Alert Date' /> --->
<!--- <@placeholder name='AlertBuilding' type='richtext' help='Alert Building'/> --->
<!--- <@placeholder name='AlertBuildingsLocations' type='richtext' help='Alert Location' /> --->
<!--- <@placeholder name='AlertTrafficControl' type='richtext' help='Alert Traffic' /> --->
<!--- <@placeholder name='AlertTrafficControlPlan' type='richtext' help='Alert Traffic Plan' /> --->
<!--- <@placeholder name='AlertAccessibleRoute' type='richtext' help='Alert Accessible Route' /> --->
<!--- <@placeholder name='AlertAlternateRoute' type='richtext' help='Alert Accessible Route Alt' /> --->
<!--- <@placeholder name='AlertAffectedBusRoutes' type='richtext' help='Alert Affected Bus Routes' /> --->
<!--- <@placeholder name='Body' type='richtext' help='Alert Body' /> --->
<!--- <@placeholder name='AlertProjectNumber' type='richtext' help='Alert Project Number' /> --->

<p>The following Access & Construction Alert has been issued from Facilities Management at the University of Iowa. Construction activity may impact road, sidewalk, parking lot, elevator or building entrance access. Please review the alert below for specific details. Contact Facilities Management at 319-335-5500 if you require additional information.</p>

<h2><@placeholder name="AlertSubject" type="richtext"/></h2>

<#if placeholder_AlertCategory??>
<h3>Closure category</h3>
<div>${placeholder_AlertCategory}</div>
</#if>

<#if placeholder_AlertDate??>
<h3>Date</h3>
<div>${placeholder_AlertDate}</div>
</#if>

<#if placeholder_AlertBuilding??>
<h3>Building</h3>
<div>${placeholder_AlertBuilding}</div>
</#if>

<#if placeholder_AlertBuildingsLocations??>
<h3>Location</h3>
<div>${placeholder_AlertBuildingsLocations}</div>
</#if>

<#if placeholder_AlertTrafficControl??>
<h3>Traffic control</h3>
<div>${placeholder_AlertTrafficControl}</div>
</#if>

<#if placeholder_AlertTrafficControlPlan??>
<h3>Traffic control plan</h3>
<div>${placeholder_AlertTrafficControlPlan}</div>
</#if>

<#if placeholder_AlertAccessibleRoute??>
<h3>Accessible route</h3>
<div>${placeholder_AlertAccessibleRoute}</div>
</#if>

<#if placeholder_AlertAlternateRoute??>
<h3>Alternative route</h3>
<div>${placeholder_AlertAlternateRoute}</div>
</#if>

<#if placeholder_AlertAffectedBusRoutes??>
<h3>Affected bus routes</h3>
<div>${placeholder_AlertAffectedBusRoutes}</div>
</#if>

<#if placeholder_Body??>
<h3>Reason and details for closure:</h3>
<div>${placeholder_Body}</div>
</#if>

<#if placeholder_AlertProjectNumber??>
<h3>Project number</h3>
<div>${placeholder_AlertProjectNumber}</div>
</#if>

<p>You can view <a href="https://facilities.uiowa.edu/alerts/">a list</a> or <a href="https://maps.facilities.uiowa.edu/closures/">an interactive map</a> of current UI Access & Construction alerts on the Facilities Management website. If you do not wish to continue receiving these automatic e-mail notices and are not a Building Coordinator, please #unsubscriptionlink#.</p>
```

**Comment by joewhitsitt** [comment]
>Check to see if this is consistent with how we are outputting on an alert node

Not the same order as the node. Going to take a pass at adjusting that.

At EoD I explained how conditionals are still not working (template outside this PR) and it was decided to bring the discoveries of https://github.com/uiowa/uiowa/issues/6880#issuecomment-1738019229 (spell checking) to the customer for further discussion before any solution is implemented.

Everything else looks good.

**Comment by joewhitsitt** [comment]
Updated template to sort of match the node template

Screenshot 2023-09-27 at 4 33 21 PM

<details>

```
<p>The following Access & Construction Alert has been issued from Facilities Management at the University of Iowa. Construction activity may impact road, sidewalk, parking lot, elevator or building entrance access. Please review the alert below for specific details. Contact Facilities Management at 319-335-5500 if you require additional information.</p>

<h2><@placeholder name="AlertSubject" type="richtext"/></h2>

<#if AlertDate??>
<h3>Date</h3>
<p><@placeholder name="AlertDate" type="richtext"/></p>
</#if>

<#if AlertBuilding??>
<h3>Building</h3>
<p><@placeholder name="AlertBuilding" type="richtext"/></p>
</#if>

<#if AlertBuildingsLocations??>
<h3>Location</h3>
<p><@placeholder name="AlertBuildingsLocations" type="richtext"/></p>
</#if>

<#if AlertAffectedBusRoutes??>
<h3>Affected bus routes</h3>
<p><@placeholder name="AlertAffectedBusRoutes" type="richtext"/></p>
</#if>

<#if Body??>
<h3>Reason and details for closure:</h3>
<div><@placeholder name="Body" type="richtext"/></div>
</#if>

<#if placeholder_AlertAccessibleRoute??>
<h3>Accessible route</h3>
<p><@placeholder name="AlertAccessibleRoute" type="richtext"/></p>
</#if>

<#if AlertAlternateRoute??>
<h3>Alternative route</h3>
<p><@placeholder name="AlertAlternateRoute" type="richtext"/></p>
</#if>

<#if AlertTrafficControl??>
<h3>Traffic control</h3>
<p><@placeholder name="AlertTrafficControl" type="richtext"/></p>
</#if>

<#if AlertTrafficControlPlan??>
<h3>Traffic control plan</h3>
<p><@placeholder name="AlertTrafficControlPlan" type="richtext"/></p>
</#if>

<#if AlertCategory??>
<h3>Closure category</h3>
<p><@placeholder name="AlertCategory" type="richtext"/></p>
</#if>

<#if AlertProjectNumber??>
<h3>Project number</h3>
<p><@placeholder name="AlertProjectNumber" type="richtext"/></p>
</#if>


<p>You can view <a href="https://facilities.uiowa.edu/alerts/">a list</a> or <a href="https://maps.facilities.uiowa.edu/closures/">an interactive map</a> of current UI Access & Construction alerts on the Facilities Management website. If you do not wish to continue receiving these automatic e-mail notices and are not a Building Coordinator, please #unsubscriptionlink#.</p>
```

**Review by joewhitsitt — APPROVED** [review]
PR looks good.

**Pull request merged**
