### PR TITLE
Improve recipes:multisite:init and document.

### PR DESCRIPTION
**Pull request by richardbporter**
This should allow developers to create new multisites and install locally. 

Check this branch out locally and run through the instructions in the readme. Feel free to make improvements!

### CODE REVIEW

**Comment by richardbporter** [comment]
I think two more things would be helpful here:

1. Add some docs on creating databases and domains in AC.
2. Change the localhost database names to match those in AC, i.e. an underscored site directory (URI).

The second will require people to rename their existing local databases and then regenerate each site's local.settings.php files.

**Comment by richardbporter** [comment]
I've made those changes. Apologies if that messes up your local setup but I think its for the best to be consistent.

**Comment by joewhitsitt** [comment]
Added a bit about upping php resources as my 128M default memory exhausted during site install.

**Comment by joewhitsitt** [comment]
Otherwise, this appears to have worked as expected. See my result here: https://github.com/uiowa/uiowa/tree/add-gis-sites

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
