### PR TITLE
Feature: Starting work on new event template

### PR DESCRIPTION
**Pull request by bspeare**

### CODE REVIEW

**Comment by richardbporter** [comment]
When I tried this initially I attached the **event** component in the block preprocess and then deleted the **events** component from uids_base. 

https://github.com/uiowa/uiowa/blob/58eb0e7ba9cf2e25d4d4c061ba6c18793c56526c/docroot/modules/custom/sitenow_events/sitenow_events.module#L17-L21

I don't know if that simplifies things or not. Let me know if there is anything specific I can help with here.

**Comment by bspeare** [comment]
It looks like there are a few fixes that need to be made to the border styling when background colors are applied to the container. 

The layout specific `` border is overriding the styles set in the UIDS component:

Screen Shot 2020-10-02 at 10 38 30 AM

Here's a recap of how the border colors are set or should be set in UIDS:

Screen Shot 2020-10-02 at 10 39 26 AM
Screen Shot 2020-10-02 at 10 39 35 AM
Screen Shot 2020-10-02 at 10 39 45 AM
Screen Shot 2020-10-02 at 10 41 22 AM
Screen Shot 2020-10-02 at 10 42 42 AM

The brain pattern variants need to be set in the UIDS component still: https://github.com/uiowa/uids/blob/main/src/components/event/event.scss#L92-L107

**Review by bspeare — COMMENTED** [review]
Since the styles with the event component are now shared should we move this css from `events.scss` to `event.scss`?

**Comment by bspeare** [comment]
Also, if we are adjusting the background style variants in UIDS, we should make this adjustment to how the date is styled: https://github.com/uiowa/uids/issues/309#issuecomment-702803959

**Comment by bspeare** [comment]
@GaryRidgway Was there a style option to align the images to the right?

**Comment by bspeare** [comment]
Is it worth creating a follow-up issue for the `event` component to add a description field and the ability to change the image alignment to match the functionality available here?

**Comment by bspeare** [comment]
I can confirm that this does affect v2 sites and will need additional work before this is merged.

**Comment by bspeare** [comment]
@GaryRidgway It looks like all the v2 styles need to be run through the color contrast kitchen sink background test.

**Comment by GaryRidgway** [comment]
I am going to start working on the V2 BG color styles

**Comment by joewhitsitt** [comment]
pulling down for review/testing

**Review by joewhitsitt — APPROVED** [review]
Overall looking good. Nothing is "broken" but a few thoughts:

- location/virtual icon padding seems off in v2 and v3.
- Probably a separate issue to address for a lot of content blocks/paragraphs, but the 768 mobile breakpoint for v2 and v3 single column is pretty intense, while events in a 4 column v3 seem a bit squished. Again, nothing is broken.
- I feel like the v3 image right image should be on top of the event in mobile instead of underneath.
Screen Shot 2020-10-09 at 10 21 09 AM
Screen Shot 2020-10-09 at 10 23 49 AM
Screen Shot 2020-10-09 at 10 28 43 AM

**Comment by pyrello** [comment]
I pushed an update that is just correcting some formatting issues that I noticed when reviewing the twig and scss files. It should not affect display or functionality.

**Comment by bspeare** [comment]
I fixed these two items:

     location/virtual icon padding seems off in v2 and v3.
     I feel like the v3 image right image should be on top of the event in mobile instead of underneath.

**Pull request merged**
