### PR TITLE
Feature: Collegiate collections permissions fix

### LINKED ISSUE #2271: Allow webmasters to edit collection items after they have been created
# Problem

Webmasters are unable to edit Collections once they have been created.  Masquerade as a Webmaster on https://admissions.prod.drupal.uiowa.edu/how-apply/transfer-admissions and try to edit the accordions. 

Screen Shot 2020-09-30 at 4 32 06 PM

# Proposed Solution

Adjust Collegiate Split so that Webmasters can edit collections?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/2271

### CODE REVIEW

**Comment by joewhitsitt** [comment]
You want to remove permissions for Slider on collegiate?

**Comment by bspeare** [comment]
Nope, let me fix that.

**Comment by joewhitsitt** [comment]
i think you have gone too far the other direction now. probably should add the create and delete perms for collections as well.

**Comment by joewhitsitt** [comment]
See v3 default: https://github.com/uiowa/uiowa/blob/main/config/default/user.role.webmaster.yml#L105, https://github.com/uiowa/uiowa/blob/main/config/default/user.role.webmaster.yml#L130

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
