### PR TITLE
[Pharmacy] Added alumni view 

### LINKED ISSUE #6832: Pharmacy alumni directory
# Story

As a College of Pharmacy website owner, I would like to have an alumni directory with the ability to filter by name, state and research area so that students can find and connect with alumni.

# Additional Information

They currently have a Palliative Care directory and would like to keep that how it is https://pharmacy.uiowa.edu/pharmd/dual_cert/palliative/certificate_graduates.

They currently use Academic profiles for their person directory so all people currently added to their website are technically alumni.

They do not need the map like the Palliative care directory.

They basically want our built in person directory (https://sandbox.prod.drupal.uiowa.edu/people) with the ability to filter by state.

State is currently a field available on Pharmacy person content type.

They currently have overridden the label for "Research Areas" to "Practice Areas" but they may want to change that label again.

# Proposed Solution

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6832

# How to test
```
ddev blt ds --site=pharmacy.uiowa.edu && ddev drush @pharmacy.local uli /alumni/alumni-directory
```

- Confirm that you can filter by name, state, and practice area

### CODE REVIEW

**Comment by bspeare** [comment]
This is ready for review, but not a priority for the last day of this sprint.

**Comment by e-marie-w** [comment]
View looks great! Name, practice area, and state filters work as expected. (name=title in the testing instructions, right?) 

I know a lot of our custom views have a reset button appear after applying a filter, is that something we want to add to this view too? I kept trying to click out of habit. 😂

**Comment by bspeare** [comment]
Good suggestion @e-marie-w!  I have added the reset option into the view.

**Review by e-marie-w — APPROVED** [review]
Looks and works great!! Thanks for adding the reset button.

**Comment by bspeare** [comment]
Thanks @e-marie-w, I think I might move this back to draft to check with @briand44 if the `/alumni/alumni-directory` path will work for pharmacy.

**Comment by briand44** [comment]
I reached out to Barb to get clarity on the path. CC'd Ben.

**Comment by bspeare** [comment]
Barb approved the path.  This can be merged when the build passes.

**Pull request merged**
