### PR TITLE
Feature: SPPA opportunity resource migrations

### LINKED ISSUE #3722: SPPA - Build opportunity resource migration
Create migrations into opportunity resource content type for:
* Employers 
* Consulting firms

Create a redirect migration for each content type.

Example of files related to content migration built recently:
* Article migration config file: https://github.com/uiowa/uiowa/blob/main/docroot/sites/international.uiowa.edu/modules/international_migrate/config/split/migrate_plus.migration.international_articles.yml
* Article migration class file: https://github.com/uiowa/uiowa/blob/8928d27c2d55fb2f23474f94032852c35f32a597/docroot/sites/international.uiowa.edu/modules/international_migrate/src/Plugin/migrate/source/Articles.php
* Article redirection migration config file: https://github.com/uiowa/uiowa/blob/8928d27c2d55fb2f23474f94032852c35f32a597/docroot/sites/international.uiowa.edu/modules/international_migrate/config/split/migrate_plus.migration.international_article_redirects.yml

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3722. 

## To Test

- Sync D7 sppa (urban) site within grad application using Dev Desktop.
- Run the following and configure/save SiteNow Migrate
```
blt sync --site sppa.uiowa.edu && 
drush @sppa.local en sppa_migrate --yes && 
drush @sppa.local uli /admin/config/system/sitenow-migrate
```
```
database = urban
user = root
host = 10.0.2.2
port = 33067
base url = https://sppa.uiowa.edu
```
- `drush @sppa.local cr && drush @sppa.local migrate:status`
- You should see potential employers and consulting firms migrations
`drush @sppa.local migrate:import --all`
- Test that redirects are working: https://sppa.local.drupal.uiowa.edu//content/ad-marble-and-company, https://sppa.local.drupal.uiowa.edu/potential-employer/university-of-virginia-batten-school-of-leadership-and-public-policy

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare It occurred to me that the class files may not be necessary in this case. They would only be necessary if we are going to do some specific processing beyond what can be indicated in the migration config files.

**Comment by bspeare** [comment]
I think these migrations are working.   I'm getting two separate errors on the consulting firm migration that still need to be fixed:

- `No static mapping found for 'array( 'value' => 'District Of Columbia', )' and no default value provided for destination 'field_opportunity_locations'.`
- `Array index missing, extraction failed.`

**Comment by pyrello** [comment]
I added some additional fields based on feedback from the site owner. I also added constant values for degree for the two content type migrations since the field isn't currently present on them.

I also think I fixed the first error in comment above.

**Comment by richardbporter** [comment]
I was able to run one of the redirect migrations successfully after 66a42f7.

**Comment by pyrello** [comment]
I'm noticing that, after this change, the number of items changed for articles and potential employers. That makes me think that the query change is excluding results that don't have an alias, which is not what we want.

**Comment by pyrello** [comment]
I think this is working now.

**Comment by bspeare** [comment]
I also tested this out and had no trouble running the migrations.

**Review by pyrello — APPROVED** [review]
Approving based on my testing and the testing of @bspeare

**Pull request merged**
