### PR TITLE
Admissions - Events - View

### LINKED ISSUE #3173: Admissions - Extend local event content type feature split
Split from https://github.com/uiowa/uiowa/issues/2396
Follow-up to #3170

# Story

As a site owner of Admissions, I can use extended features off of the local event content type feature split

# Proposed solution

### Content Type

- [x] Virtual Event designation? Could the logic just look for Virtual Event link?
- [x] Virtual Featured event? Could this just be "Sticky"?
- [ ] ~~Counselors - Reference an admissions person with type "counselor".~~ https://github.com/uiowa/uiowa/issues/2487
- [x] Full Calendar based view page tab display split from views.view.events - filter on event category

### LINKED ISSUE #3773: Admissions Upcoming Events view page
Split from https://github.com/uiowa/uiowa/issues/3171 as an Admissions specific piece.

## Proposed Solution

- [x] View page of upcoming events teasers using the event feature split that is captured in the admissions split
  - /events for now

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/3773
Resolves https://github.com/uiowa/uiowa/issues/3173

Small slice to continue moving towards local event content on the admissions.uiowa.edu website. In addition to the view for #3773, this adds the calendar display from #3173, and prevents event locations from saving with just a country (default) filled. Styling is basic until https://github.com/uiowa/uiowa/issues/2727 can be addressed.

## Story

As a webmaster of admissions.uiowa.edu, I can create event instance content and have them display in a list as well as on a calendar.

Screen Shot 2021-07-13 at 3 38 47 PM

## To Test

- `git checkout i3773-admissions-events-view && git pull`
- `composer install && blt frontend && blt ds --site=admissions.uiowa.edu`
- `drush @admissions.local cim`
- `drush @admissions.local cr`
- https://admissions.local.drupal.uiowa.edu/events

### CODE REVIEW

**Comment by cory-skeers** [comment]
Pulling down to test

**Comment by cory-skeers** [comment]
If you change the start date after selecting all day, the end date field disappears from the form. The workaround is to set the start date, then mark all day and edit the end date. Guessing it's an error with the smart date field and not our form. (Also don't think it's part of this PR--can open as a new issue if there's not an immediate fix that can be rolled in.)

image

**Comment by joewhitsitt** [comment]
I don't have the branch checked out so I am curious, does this prevent save? Is there an actually an error with this, or just a bug/ux issue?

**Comment by cory-skeers** [comment]
@joewhitsitt It doesn't prevent save--the end date just gets set to the start date (so only a single date can be chosen without the workaround, and not multiple dates). Just a UX bug as far as I've seen.

With that, the views themselves are looking great. I can wait to give approval so this doesn't accidentally get merged prior to admissions review, but it has my 👍

**Comment by joewhitsitt** [comment]
As it relates to https://github.com/uiowa/uiowa/issues/3173, event categories need to be a filter on the calendar.

**Comment by joewhitsitt** [comment]
Added category filtering and fixed seo settings for admissions based on this morning's meeting. Enabled the event feature split in PROD and imported.

**Comment by joewhitsitt** [comment]
@cory-skeers now that this has been reviewed by Admissions can I get a formal approval on this?

**Review by cory-skeers — APPROVED** [review]
👍

**Pull request merged**
