### PR TITLE
Replace &#13; char in obermann article teasers.

### PR DESCRIPTION
**Pull request by richardbporter**
### Testing

```
blt sync --site obermann.uiowa.edu
```

Compare article teasers on https://obermann.local.drupal.uiowa.edu/news/2019/10 with https://obermann.prod.drupal.uiowa.edu/news/2019/10.

### CODE REVIEW

**Comment by richardbporter** [comment]
I don't know if this an issue on #3977 @cory-skeers but maybe https://github.com/uiowa/uiowa/blob/75a7280bb83bab89ddddfbbc3eebe4f86231618b/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/BaseNodeSource.php#L221 is not replacing carriage returns?

**Comment by cory-skeers** [comment]
> I don't know if this an issue on #3977 @cory-skeers but maybe
> 
> https://github.com/uiowa/uiowa/blob/75a7280bb83bab89ddddfbbc3eebe4f86231618b/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/BaseNodeSource.php#L221
> 
> is not replacing carriage returns?

I'll take a look!

**Review by cory-skeers — APPROVED** [review]
Can approve as an update for Obermann. I checked against the education migration and didn't see the same behavior, but I also checked the D7 obermann database and there wasn't anything out of the ordinary there that I think would've caused it.

I think we can push this out and do some followup investigation rolling back the obermann migration locally.

**Comment by richardbporter** [comment]
Ok thanks. Just wanted to quickly make this visible in case it was affecting education.

**Pull request merged**
