### PR TITLE
HR database updates.

### PR DESCRIPTION
**Pull request by richardbporter**
To test, check out this branch and run `blt dsa` to sync from test. This will destroy active config!

Haven't quite figured out the config split update yet.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
i am sure i am doing something wrong, but `lando blt dsa` is causing a lot of red errors in my terminal and finally ends with `Command `drupal:sync:db ` exited with code 1`

Update: `blt dsa` seemed to go farther but I am getting:
```Output:                                                                      
  ================                                                             
  Creating database sitenow. Any existing database will be dropped!            
                                                                               
                                                                               
  Error Output:                                                                
  ================                                                             
                                                                               
  In SqlCommands.php line 101:                                       
                                                                       
                                                                       
    Unable to create database. Rerun with --debug to see any error me  
  ssage.
```

**Comment by richardbporter** [comment]
It doesn't work yet but I wanted to push the code up in a draft PR.

**Comment by richardbporter** [comment]
The build will fail but `blt dsa` should work now.

**Comment by richardbporter** [comment]
@joewhitsitt I think I figured out the CI issue. If you're happy with `blt dsa`, I think this can be merged.

**Pull request merged**
