### PR TITLE
update siteimprove from 2.0.1 to 2.0.2

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/6644

# Background
https://github.com/uiowa/uiowa/issues/6644#issuecomment-2302127543

# How to test

Review changelog https://git.drupalcode.org/project/siteimprove/-/compare/2.0.1...2.0.2?from_project_id=48082&straight=false
- Because this is environment based, actual testing of the functionality needs to happen in PROD where these domains are hooked up with the SiteImprove service.
- To test config import, etc., pick a site and change which environment split is imported on sync by adjusting the site's local.settings.php file:
```
$config['config_split.config_split.local']['status'] = FALSE;
$config['config_split.config_split.prod']['status'] = TRUE;
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
It wanted to export node/taxonomy stuff but since this is for the whole platform, i removed it as other sites have unique features. by omitting i think the module assumes to enable for all.

```
enabled_content_types:
  article: '0'
  page: '0'
  person: '0'
enabled_taxonomies:
  research_areas: '0'
  tags: '0'
```

**Comment by joewhitsitt** [comment]
Inspecting the code, the enabled content types and taxonomies relates to the prepublish functionality which is turned off. same with the api key info that was removed in [ed63513](https://github.com/uiowa/uiowa/pull/7999/commits/ed6351316e7b1065ed4ce61178048533b204edaf)

**Review by pyrello — APPROVED** [review]
Reviewed, not tested.

**Comment by joewhitsitt** [comment]
@pyrello when this passes, should i merge as we discussed in DM? i want to respect what you said here: https://iowaweb.slack.com/archives/C0164FNN1PV/p1724254311682429

**Comment by joewhitsitt** [comment]
retriggered build after failed security check connection

**Pull request merged**
