### PR TITLE
Memory limit increase for menu pages

### LINKED ISSUE #6176: Large menu page not loading/changes not saving
Response from Acquia:
  https://support-acquia.force.com/s/article/360004542293-Conditionally-increasing-memory-limits
  https://docs.acquia.com/cloud-platform/manage/php/#php-mem

Refer to: 
https://github.com/uiowa/uiowa/issues/1996
https://github.com/uiowa/uiowa/issues/1996#issuecomment-1424305613
https://github.com/uiowa/uiowa/issues/1996#issuecomment-1424415304

### PR DESCRIPTION
**Pull request by makurj**
Resolves https://github.com/uiowa/uiowa/issues/6176

# How to test

1. Follow this to set DDEV `memory_limit` to 128: https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-php-configuration-phpini
2. `blt ds --site=engineering.uiowa.edu`
3. Masquerade as a webmaster on Engineering.
4. Go to https://engineering.uiowa.ddev.site/admin/structure/menu/manage/main
5. Make changes to the menu and see if you can save it.
6. Did the changes stick?
7. Follow the same steps on a few other sites with large menus: Tippie is one.

### CODE REVIEW

**Comment by e-marie-w** [comment]
I'm not sure I'm testing this accurately. I created the custom php.ini file but forgot to run `ddev restart`, and it still worked fine. Then I pulled down main to compare something different, resynced the site, and it still worked fine. It seems like the problem is only in prod (I double-checked, that still doesn't work). And I was masquerading as webmaster, and tried editor and publisher as well (those also aren't working on prod but do locally whether on this branch or main).

Should we try testing this in dev or stage instead? Or maybe first see if someone else also sees this behavior?

**Comment by makurj** [comment]
Did you set the memory limit to 128 in DDEV's php.ini before `ddev restart`? Once you do that, you can comment out the code in global.settings.php, then test. The Engineering menu would not work as a webmaster. Then uncomment out the code and try again.

**Comment by e-marie-w** [comment]
Is there a label to put with the 128? Site sync failed and I kept getting errors related to be unable to set the memory.

**Comment by makurj** [comment]
Did you see this above? https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#custom-php-configuration-phpini Instead of `max_execution_time`, you use `memory_limit` and `128M`. Let me know if you want to huddle.

**Comment by e-marie-w** [comment]
Ah I was missing the M, thank you!

**Comment by makurj** [comment]
Glad it's working :) Thanks for testing!

**Comment by e-marie-w** [comment]
Nevermind that didn't fix it, I still can't sync the site.

**Comment by e-marie-w** [comment]
It works! Syncing the site just produces the following error messages:

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/docroot/core/lib/Drupal/Core/Cache/MemoryBackend.php on line 106
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/docroot/core/lib/Drupal/Core/Cache/MemoryBackend.php on line 106

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/html/vendor/symfony/http-foundation/Response.php on line 804
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/html/vendor/symfony/http-foundation/Response.php on line 804
 [Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 255  Time 7.081s
 [error]  Failed to import configuration!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `drupal:config:import --site='engineering.uiowa.edu'` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `drupal:update --site='engineering.uiowa.edu'` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
Failed to run blt ds --site=engineering.uiowa.edu: exit status 1
```

**Review by e-marie-w — APPROVED** [review]
Turns out the sync errors are related to my local, so I'm approving as it works as intended. Awesome job!

**Pull request merged**
