### PR TITLE
UIowa.edu search/menu changes

### LINKED ISSUE #4716: As a prospective student, I can use uiowa.edu with the horizontal or mega navigation
# Story

As a student, I can use uiowa.edu with the horizontal or mega navigation so that I can have easier access to the main navigation

# Problem

We built a lot of custom functionality into uiowa.edu based on the fixed header with toggle menu.   If we want to shift to a new navigation style, we will need to make a number of updates.

Screen Shot 2022-01-28 at 11 22 57 AM
Screen Shot 2022-01-28 at 11 23 04 AM

# Proposed solution
- Remove `uids_base_externalquicklinks`
- Update permissions on uiowa.edu to remove ability to add/edit external quicklinks
- Adjust search toggle to display within the header
- Create an "Athletics" page on uiowa.edu similar to https://illinois.edu/athletics/index.html. 
- Adjust menu to `Horizontal` option and display "Alumni & Friends" and "Health Care" positioned to the right with external link icons and gray color:
- Full screenshots below https://github.com/uiowa/uiowa/issues/4716#issuecomment-1211081749

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/4716. 

# Remaining tasks 
- [x] Browserstack testing, especially safari mobile menu toggle. 
- [x] Attach UIDS main hash once approved
- [ ] Figure out best way to deploy these changes

# How to test

`blt frontend`
`ddev blt sync --site uiowa.edu --define drush.aliases.remote=home.dev`
- Test user story "As a prospective student, I can use horizontal navigation on uiowa.edu while still having access to the links that were available in the toggle navigation"
- `ddev blt ds --site=uiowa.edu`
- Test browser breakpoints - menu should collapse at 980px and under.

## Once approved
- Attach UIDS Release from merged https://github.com/uiowa/uids/pull/784. 

## Once deployed in a release

1. "About Iowa" changes to "About" and "News, Events, Media Resources" moves under "About"
2. "Athletics", "Alumni and Friends", and "Health Care" links to need to be added to the end of the main nav
3. Menu setting on uiowa.edu needs to be set to horizontal `admin/appearance/settings/uids_base`

### CODE REVIEW

**Comment by bspeare** [comment]
I'm going to to some browserstack testing this afternoon on this.   There are a few issues with Safari that need to be resolved.

**Comment by bspeare** [comment]
This is ready for review, just keeping in draft mode so that it doesn't get merged in.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
I think I can approve once the UIDS version is updated, but also had a few thoughts/questions.

Can config/default/block.block.uids_base_externalquicklinks.yml be fully removed in this PR or in a follow-up issue? It isn't being used anywhere else correct?

Was the plain .css file created to avoid a separate yarn workspace build? If so, would moving it into uids_base make sense to get the minify benefit?

**Comment by bspeare** [comment]
@joewhitsitt Yes, the plain css file was to avoid adding an extra yarn workspace.   It looks like it is being compressed in https://home.dev.drupal.uiowa.edu/sites/uiowa.edu/files/css/css_y5XpY1KUYdA5XohRETKoZLgjxQVLaanGMqIPs4XiUBA.css - were you thinking something beyond that?

If we remove `config/default/block.block.uids_base_externalquicklinks.yml` in this pr, would it cause a WSOD on deployment?

**Comment by joewhitsitt** [comment]
>were you thinking something beyond that?

I forgot that drupal does that. Nevermind.

>would it cause a WSOD on deployment?

Well, since the homepage is first in the run list, it would just be a moment, but yes, you are probably right. I did not test it.

**Comment by bspeare** [comment]
The UIDS changes are now attached, so this can be approved and merged in whenever we are ready to deploy this change.

**Comment by joewhitsitt** [comment]
Checking this one more time

**Review by joewhitsitt — APPROVED** [review]
Recent changes check out. Thanks for keeping up with this @bspeare

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
