### PR TITLE
Lando - An Experiment

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/3641

## Notes

- lando ships with docker (dmg) but is out of date. one pro is that a dmg is easier for onboarding.
- I can't get nvm installed on the appserver container. Commented out NVM usage in blt.yml for now.
- SSH operations require entering passphrase for SSH key if one is set.

## Setup
Download the latest Lando DMG for your Mac: ARM64 for M1, x64 for Intel. https://github.com/lando/lando/releases. Run the installer. If you installed Docker with ddev, there might be a way to skip installing it again with Lando. If it gets reinstalled with an older version, you can upgrade Docker for Mac later.

Check out this branch locally. Then:
- `lando start`
- `lando ssh`
- `blt bis`
- `blt frontend`
- `blt sync`
- `drush @default.local uli`

### CODE REVIEW

**Comment by richardbporter** [comment]
I'll try this out next week. This looks interesting: https://support.acquia.com/hc/en-us/articles/360060054874-Switch-from-DrupalVM-to-Lando-with-BLT-11-x

**Comment by richardbporter** [comment]
I get this weird popup when starting lando:
Screen Shot 2021-12-01 at 10 21 10 AM

 Also currently getting access denied for drupal9 MySQL user after trying this again. Thought it was working initially...

**Comment by richardbporter** [comment]
@e-marie-w this should be working now if you had time to try it out. I updated PR description. I'm just curious if M1 works.

**Comment by e-marie-w** [comment]
lando start gives me: 
`Unhandled rejection Error: Could not automatically start the Docker Daemon. Please manually start it to continue.
    at /snapshot/cli/lib/daemon.js
From previous event:
    at LandoDaemon.up (/snapshot/cli/lib/daemon.js)
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.list (/snapshot/cli/lib/engine.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.init (/snapshot/cli/lib/app.js)
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47`

one of the docker docs said  `dockerd` would manually start it but that just gave me `command not found`

**Comment by joewhitsitt** [comment]
@e-marie-w is your docker app running? did you ddev poweroff as well?

**Comment by e-marie-w** [comment]
I did `ddev stop`...do I need to do poweroff too? After updating docker `lando rebuild` ran fine.

**Comment by joewhitsitt** [comment]
Not sure the extent of the difference is but I was recommending `vagrant halt` to test ddev which frees up ports and such. it is my understanding that `ddev poweroff` is the same port freeing up type command if you wanted to test something else like lando.

**Comment by richardbporter** [comment]
Sorry to hear of your troubles. I'm struggling with a couple unrelated things as well. 

I took a few notes on ddev/lando at https://github.com/uiowa/uiowa/issues/3641#issuecomment-983850807. Given the struggles here, I would propose closing this PR in favor of #4458 and diving deeper into ddev.

**Comment by e-marie-w** [comment]
Lando does work on the m1! `blt frontend` throws some errors like ddev did at first but they seem just as fixable. Lando does seem slower, though, so my vote is for ddev.

**Pull request closed without merging**
