### PR TITLE
Feature: Sprint 10 work

### LINKED ISSUE #1158: Refactor theme settings in uids_base for sticky option
# The Problem

- The "sticky" option should only be available if the toggle navigation is selected in the theme settings. 
- The header type variable needs to be moved into body classes instead of in header_classes so that the main content area can be targeted when the header is sticky.

# Proposed solution

- Make the "sticky" option only appear if "toggle navigation" is selected. 
- Refactor header_classes to appear in body class
- UIDS will need to be updated to reflect class updates https://github.com/uiowa/uids/blob/master/components/03%20-%20global/header/_header.scss, https://github.com/uiowa/uids/blob/master/components/03%20-%20global/search-toggle/_search-toggle.scss

### LINKED ISSUE #1178: Regression: Admin toolbar overlapping tab logo when displayed veritically
Screen Shot 2020-03-12 at 11 47 32 AM

This is new behavior, since we had the header working with the toolbar menu previously.

### PR DESCRIPTION
**Pull request by bspeare**
In this PR:

- Admin toolbar overlapping tab logo when displayed veritically (Resolves #1178)
- Card Image style changed to Large Widescreen
- Sticky header class padding changed to the body instead of main tag (Resolves #1158)
- Added vertical video block component that allows video file, caption track, and preview image to be uploaded into block
- Updated libraries and header template to use header sticky js only if it is enabled in theme settings (this will work only after uids version is bumped up to 1.5.1) (Resolves #1158)
- Events block component 

# How to test

**Vertical Video block**

Edit the home page "layout" and add a "Vertical Video" block to the page.  Upload an mp4, txt file, and preview image and save layout. 

**Event Block**

Edit the home page "layout" and add an "Event" block to the page.  Fill out the fields and save the layout. 

**Sticky header**

In the theme settings, uncheck the "sticky" checkbox and verify that the header is no longer sticky on page scroll. 

**Card Image style**

Verify that the cards on the home page are using widescreen images instead of square

### CODE REVIEW

**Review by richardbporter — APPROVED** [review]
Ran a `blt sync --site uiowa.edu` and `blt frontend`. No issues.

Verified that #1178 is fixed. Not exactly sure how to test the others though.

**Comment by richardbporter** [comment]
Not sure if this related but I'm seeing duplicate breadcrumbs on interior pages:
image

**Comment by bspeare** [comment]
@richardbporter Thanks.  Those breadcrumbs still need to be manually removed from each page.

**Comment by bspeare** [comment]
@richardbporter I also added some "how to test" notes above if you would like to kick the tires further.

**Comment by richardbporter** [comment]
Thanks. 👍 

Dig the widescreen styles.

**Review by pyrello — APPROVED** [review]
This looks good. Nice work!

**Pull request merged**
