### PR TITLE
Feature AoS Search Block removal

### LINKED ISSUE #4082: Replace AoS Search Block on Admissions with uiowa_core SearchBlock
## Issue

We made a search block in uiowa_core that does what the aos search block does on admissions. admissions is the only site using the AoS search block. Let's reduce that to one.

## Proposed solution

- [x]  Update content type description to stop referencing view page and instead mention the "Areas of Study" block.
- [x]   Now that the uiowa_core search block is available. remove the current block from admissions homepage (prod), add the uiowa_core block and configure to point to the same /areas-of-study destination.
- [x]  Find usage on the site. I think there is one tucked away somewhere. We have past update hook code that can look for instances.
- [x]  Delete area_of_study_search block content type from split
- [x]  Update permissions to not include areas_of_study_category? Taxonomy vocabulary doesn't exist?
- [ ]  Sync changes (db) to stage/dev so we don't have missing block errors.
- [x]  Remove block from areas of study module

### LINKED ISSUE #4123: Admissions area of study teasers card display are a little broken
# Problem
It looks like the addition of the teaser template for the Areas of Study disrupted the cards on https://github.com/uiowa/uiowa/blob/84f376dffba781b1142635cbfb6cdd0f982ab7a1/docroot/modules/custom/uiowa_area_of_study/templates/node--area-of-study--teaser.html.twig. 

Screen Shot 2021-09-14 at 4 27 45 PM

# Steps to reproduce
Go to https://admissions.uiowa.edu/academics/biz-econ-mgmt and compare against https://web.archive.org/web/20210812002345/https://admissions.uiowa.edu/academics/biz-econ-mgmt

Screen Shot 2021-09-14 at 4 32 28 PM

# Proposed solution
Update admissions to use the correct card template and styles.

### PR DESCRIPTION
**Pull request by e-marie-w**
Resolves https://github.com/uiowa/uiowa/issues/4082
Resolves https://github.com/uiowa/uiowa/issues/4123

# How to test

`blt ds --site=default`

- Enable areas of study split and `drush @default.local cim`
- Check that content type description mentions area of study block and not page
- Check that `areas_of_study_category` doesn't exist for the content type since we removed permisisons to access this taxonomy

`blt ds --site=admissions.uiowa.edu`

- Verify that new search block is in place on home page and that update hook runs for admissions home page removing any reference to previous search block within revisions
- Verify that old area of study search block has been removed from the areas of study module

### CODE REVIEW

**Comment by pyrello** [comment]
Are the permission deletions in this commit intentional? https://github.com/uiowa/uiowa/pull/4139/commits/2729822bd0139f2b8e2c12065eb79f00ae00c99b

**Comment by bspeare** [comment]
> Are the permission deletions in this commit intentional? [2729822](https://github.com/uiowa/uiowa/commit/2729822bd0139f2b8e2c12065eb79f00ae00c99b)

Yes, @joewhitsitt  spotted that non-existent category during demo.

**Comment by bspeare** [comment]
This is ready for review.  Once approved, we might want to test if this update hook runs correctly on stage before deploying to prod.

**Comment by joewhitsitt** [comment]
Can the module be removed from Admissions in this PR to resolve https://github.com/uiowa/uiowa/issues/4123 as well or does that need to be a follow-up?

i can test this after lunch

**Comment by bspeare** [comment]
@joewhitsitt I think it would be worth getting it turned off in this pr.   What needs to be done to turn that off?

**Comment by joewhitsitt** [comment]
i think it would be just removing it from the admissions complete split. i have this local. i can do that and test.

**Review by joewhitsitt — APPROVED** [review]
Looks good. Tested default, education, admissions. 9 block records found/removed. Removed the unused module from Admissions which also resolves https://github.com/uiowa/uiowa/issues/4123
Screen Shot 2021-09-20 at 1 05 57 PM

**Pull request merged**
