### PR TITLE
[D10] Custom module compatibility updates

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #6856 

# To Do

- [x] uiowa_profiles
- [x] docroot/sites
- [x] docroot/themes/custom/uids_base/assets/js/carousel.js

# How to test

```
ddev composer install
```

## Module info updates
Check for `core_version_requirement:` listings in any modules' `.info.yml` in our custom or site modules that does not include `^10`. They should all include the 10 compatibility.

## Explicit access checks
https://www.drupal.org/node/3201242
Code review should be all that's necessary. Entity queries that didn't specify their access check defaulted to `TRUE`. The only changes here are including an `->accessCheck(TRUE)`, which does not affect behavior.

## drupal-off-canvas updates
https://www.drupal.org/node/3305664
Edit a section/block in layout builder, and compare the off-canvas tray with prod. There should be no changes in style.

## javascript updates
https://www.drupal.org/node/3158256
https://www.drupal.org/node/3104677

Check the following still function (some it may be helpful to test in dev):

- sitenow_events: `single-event.js`: Behavior for handling events with repeated dates
- uiowa_alerts: `uiowa_alerts.es6`: Fetches and attaches hawk alerts
- uiowa_search: `cse.js`: Attaches the search results behavior for the site-wide search
- uids_base: `video-cooke.js` Reads from and sets a cookie to control the video autoplay
... and many more..
- uiowa_profiles: wasn't sure how to do core/once on a document each? so i grabbed what I thought would work. https://github.com/uiowa/uiowa/pull/6892/commits/92f839389474fe51448b9c984026e6c389ab19fc

## PHPCS updates

Also included a lot of phpcs warning cleanups.
```
ddev phpcs
```
Witness the lack (or close to) of warnings!

For full testing, can test the dependency injection updates:

- Replicate a node, and check the revision created time of the newly created node, and see that the time is accurate
- Check the Events config on a site without the Events feature split, and see that the Site Events config doesn't show up. Enable the split (`ddev drush @site.local config-split:activate event`) and see that the options now appear.
- Sync an intranet site or enable the intranet split on another site. Check that anonymous users don't have access
- Run the P2LB cleanup command and check that messages are still logged and orphan paragraphs are cleaned up

### CODE REVIEW

**Comment by cory-skeers** [comment]
I think this is ready for review/testing.

Hawk alerts JS is a bit trickier to test with, if this PR is around long enough:
> Campus Safety will test the Hawk Alert emergency notification system at approximately 12:00 p.m. (noon) on Friday, Sept. 22, 2023 as required by federal law.

Otherwise, this is helpful for testing (update w/test site if not default):
```
ddev drush @default.local cset uiowa_alerts.settings hawk_alert.source 'https://emergency.stage.drupal.uiowa.edu/api/active.json'
```

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Does https://www.drupal.org/node/3305664 mean we need to update docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss as well? Not sure why the initial scan didn't pick that up.

**Comment by cory-skeers** [comment]
> Does https://www.drupal.org/node/3305664 mean we need to update docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss as well? Not sure why the initial scan didn't pick that up.

Shoot. Yeah, that should be updated, and any other bits that may have been missed.

**Comment by bspeare** [comment]
@joewhitsitt Yes, and we might want to look to see if we can remove a number of the layout builder patches in `composer.json` as well.

**Comment by bspeare** [comment]
Does the `jquery.once` stuff in https://github.com/uiowa/uiowa/blob/custom-module-compatibility/docroot/modules/custom/layout_builder_custom/layout_builder_custom.libraries.yml need to be adjusted?

**Comment by joewhitsitt** [comment]
~~sitenow~~, ~~uiowa_graph~~, ~~uiowa_hours~~ and uids_base all have core/jquery.once calls still.

**Comment by joewhitsitt** [comment]
That `ddev phpcs` would be perfect except for https://github.com/uiowa/uiowa/blob/custom-module-compatibility/docroot/sites/its.uiowa.edu/modules/its_core/its_core.module#L198

@GaryRidgway is that needed?

**Comment by joewhitsitt** [comment]
@cory-skeers are you working on the remaining jquery.once or would you like help?

**Comment by cory-skeers** [comment]
> @cory-skeers are you working on the remaining jquery.once or would you like help?

If you're available to help, that'd be great! I'm getting some stuff set up for demo currently, and would otherwise jump back on this post-demo.

**Comment by joewhitsitt** [comment]
>we might want to look to see if we can remove a number of the layout builder patches in composer.json as well.

I think this will be easier to spot when we actually try to update composer to d10. I've added a note to the IS about patches to https://github.com/uiowa/uiowa/issues/6537

**Comment by joewhitsitt** [comment]
Easier said than done. Trying to update uiowa_hours, not as simple as I thought. Will come back to it when I can.

**Comment by joewhitsitt** [comment]
My understanding is that there is some backwards compatibility here. Trying to change libraries first for everything on the page and then seeing if I can get the new once format to work.

**Comment by joewhitsitt** [comment]
Should also note that this makes the info files for the modules are reduced to being backwards compatible to 9.2 (once), 9 (cookie)

**Comment by joewhitsitt** [comment]
working on sitenow.profile js ✅ 
now layout_builder_custom ✅

**Comment by joewhitsitt** [comment]
As an anonymous user, I don't think the video cookie is working. Will take a closer look tomorrow along with changes for the other js files in uids_base

**Comment by cory-skeers** [comment]
> As an anonymous user, I don't think the video cookie is working. Will take a closer look tomorrow along with changes for the other js files in uids_base

I found one bit that needed to be fixed in the video cookie js that might have been the culprit, causing the bulk of the function to not get called.

**Comment by joewhitsitt** [comment]
still not sure what is going on with it. i threw in an `alert('cookie-video');` after the `once()` and not getting it when clearing cookies, cache for an anonymous user in chrome.

running `ddev yarn workspace uids_base build && ddev drush @sandbox.local cr` in-between changes

**Comment by joewhitsitt** [comment]
ugh. docroot/sites...

**Comment by joewhitsitt** [comment]
is `COVID Data` block still being used or was it replaced by the text area js and uiowa_graph? https://coronavirus.uiowa.edu/covid-19-numbers

**Comment by joewhitsitt** [comment]
btw, the hawk-alert js changes seemed to work locally.

**Comment by joewhitsitt** [comment]
Realizing our sitenow webform code hasn't been working probably since we transitioned it to v3..

**Comment by joewhitsitt** [comment]
I think this can be reviewed again. I went from reviewer on this to guilty of mistakes so another set of eyes would be appreciated. I tested all the ones I adjusted. not sure i found the coronavirus one in use anywhere though. the one that makes me nervous is the meta info adjustments to uiowa_profiles. i recall there being a "just in time" issue with this and google crawlers. hope this is fast enough. https://github.com/uiowa/uiowa/pull/6892/commits/92f839389474fe51448b9c984026e6c389ab19fc

**Comment by e-marie-w** [comment]
Tested so far:
Module info updates - every core_version_requirement result included ^10, I checked in:
- /modules/custom
- /profiles/custom/sitenow
- /sites
- /themes/custom/uids_base

drupal-off-canvas updates - no differences to tray when comparing local to prod, I tested a few sections and the card, events, articles, and people blocks. 
phpcs updates - ran command, see only 2 warnings (very exciting!). I plan to also run through the full testing instructions.

**Comment by joewhitsitt** [comment]
>is COVID Data block still being used or was it replaced by the text area js and uiowa_graph? https://coronavirus.uiowa.edu/covid-19-numbers

>not sure i found the coronavirus one in use anywhere though. the one that makes me nervous is the meta info adjustments to uiowa_profiles. i recall there being a "just in time" issue with this and google crawlers. hope this is fast enough. https://github.com/uiowa/uiowa/commit/92f839389474fe51448b9c984026e6c389ab19fc

@GaryRidgway are you familiar with both coronavirus and the profiles meta?

**Comment by GaryRidgway** [comment]
> @GaryRidgway are you familiar with both coronavirus and the profiles meta?

The I don't think the Covid data block is being used anymore, and I think the config is buggy for it so it can probably be removed if you couldnt find it anywhere anymore.

I will take a peek at the other code

**Comment by joewhitsitt** [comment]
Created https://github.com/uiowa/uiowa/issues/6929 as a follow-up to clean up the Coronavirus website of unused functionality.

**Comment by joewhitsitt** [comment]
Updated uiowa_auth again as part of this. This time with dependencies. To test, as yourself, not uli, log in to education.dev.drupal.uiowa.edu using the hawkid form as https://github.com/uiowa/uiowa/pull/6928 is in develop

**Comment by joewhitsitt** [comment]
Thanks @GaryRidgway from whatever understanding i have of this JS, that change seems to work. I say we go with it and see if it is still fast enough for web crawlers in PROD.

**Comment by e-marie-w** [comment]
Switched to testing javascript updates. Tested and working:
video-cookie.js 
recserve hours blocks
admissions counselor map
hr faqs
pharmacy graduates map

I also tested the banner, card, and quote form options, they are working correctly. So is the article preserve links functionality.

I also tested the LB off-canvas resizing cookie but I'm having some issues with it. Do I have to save the block/page for the size to keep?

**Comment by e-marie-w** [comment]
> Updated uiowa_auth again as part of this. This time with dependencies. To test, as yourself, not uli, log in to education.dev.drupal.uiowa.edu using the hawkid form as #6928 is in develop

This works! I was able to successfully login using my hawkid.

**Comment by joewhitsitt** [comment]
>I also tested the LB off-canvas resizing cookie but I'm having some issues with it. Do I have to save the block/page for the size to keep?

It should register your sizing and if you close and reopen the block it should persist...

Update: I say that but get mixed results in PROD, so I don't know for sure...

**Comment by e-marie-w** [comment]
> > I also tested the LB off-canvas resizing cookie but I'm having some issues with it. Do I have to save the block/page for the size to keep?
> 
> It should register your sizing and if you close and reopen the block it should persist...
> 
> Update: I say that but get mixed results in PROD, so I don't know for sure...

I am also getting mixed results in PROD so I don't think this should hold up the PR.

**Review by e-marie-w — APPROVED** [review]
I tested various javascript updates, all functioned as expected. I also accidentally repeated testing of some of the other updates and they also worked as expected/had the necessary code changes.

**Comment by joewhitsitt** [comment]
Thanks for taking a look @e-marie-w and @GaryRidgway.

**Pull request merged**
