### PR TITLE
[Dependency updates] Uninstall block_content_template module

### LINKED ISSUE #7041: Remove uiowa/block_content_template repo

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7041. 
Relates to https://github.com/uiowa/uiowa/issues/7711. 

We previously used `block_content_template` module to solve the issue when a block was placed outside of the layout builder and didn't pick up our block templates where we have implemented UIDS components. This PR uninstalls that module and refactors the `content_templates` block templates to work as inline block templates. 

# How to test
- Code review

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /accordion
```
## Collections block
- Confirm you can edit block in layout
- Confirm you can edit accordion block and switch between descriptive list. 
- Confirm `id` variable is rendering on accordion like `<div class="accordion" role="tablist" aria-multiselectable="true" id="accordion-9361">` 
- Confirm multiselect/single select functionality is working and false or true is displaying on wrapper`<div class="accordion" role="tablist" aria-multiselectable="false" id="accordion-776">`
## Featured content
- Confirm you can edit block in layout
- Edit featured content block and confirm that list and grid options work as expected https://sandbox.uiowa.ddev.site/featured-content-0.
## Events block
- Confirm you can edit block in layout
- Edit events block page and confirm that events are spaced apart and grid/list settings work: https://sandbox.uiowa.ddev.site/debug-one-uiowa-events-block
## block-content--uiowa-collection--tab.html.twig
- This has been removed because we don't offer the tab in the uiowa collections block.  We can always add it back if we want to offer tabs in https://github.com/uiowa/uiowa/issues/5011. 
## CTA
- Add CTA to pre-footer (https://sandbox.uiowa.ddev.site/admin/config/sitenow/region-settings) and confirm that it picks up block CTA template

## Update hook
- Confirm that it clears the caches.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
Thanks for diving into this. I had no idea by the original issue what this was all about. I didn't even know we were handling these differently. Everything checks out per the instructions.

**Comment by bspeare** [comment]
Thanks @joewhitsitt! Moving this to draft until we can merge it for a scheduled deployment.

**Comment by pyrello** [comment]
Are we waiting on something specific to schedule this?

**Comment by bspeare** [comment]
@pyrello no, should we just merge and make sure we schedule a release for tomorrow?

**Pull request merged**
