### PR TITLE
Feature scholarship weights

### LINKED ISSUE #2436: Add weight module
# Story

## Display
Alternate sorting options in view displays
As a site visitor, 
I want to view a list of scholarships which has been pre-sorted
so that I can quickly and easily find the scholarships that are most important to me.
## Backend UI
Weight module to set priority content
As a site owner
I need to be able to organize my scholarship content individually
so that I can prioritize the end user’s experience and emphasize (or deemphasize) certain scholarships, which are not sortable in this manner based on data within the system.

# Proposed Solution

Add the weight module to all content types and update view displays (the exception being people draggableviews) to consider weight as part of the sort criteria.

If a service-wide solution is not in-scope, this has been requested specifically for Admissions' Scholarship content type/view block.

https://www.drupal.org/project/weight

<details><summary>Original Issue</summary>
<p>

Admissions currently has their scholarships weighted so that certain ones always display at the bottom of view displays and others are always at the top. Though sticky could be setup for the scholarship content type, it only solves part of the desired behavior.

> We need to be able to weight the scholarships for the order they show on the individual pages/views. There are certain scholarships that always need to be at the bottom of the list (less important) and certain ones we want listed first. 

This would also improve person sorting globally across the site..

</p>
</details>

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2436; followup issues may need to be added for:
 - As an Admissions site owner, I can order scholarships content in relation to each other (e.g. see weights for other content, drag and drop, or other option) so that prioritizing scholarships is faster and has less room for human error.
 - As a site owner, I can weight content which appears in list views in ways other than automatic sorting, so that I can prioritize displays for criteria which is not based on data within the system.

# How to test

`git pull`
`composer install`
Sync admissions, run the update hook if working off a previously synced version
Add a Scholarships block to a page, note the default ordering (alphabetical by title)
Update weights for various scholarships (both positive and negative need testing)
Check Scholarships block, see that the ordering is correctly updating

Check that sites not on the admissions split are unaffected.

### CODE REVIEW

**Comment by richardbporter** [comment]
@cory-skeers Did you run Composer commands on your host or the VM? What version do you have on each? `composer --version`

**Comment by cory-skeers** [comment]
@richardbporter Typically on the host, which is now on version 2.0.4.

v1.10.5 in the VM. Gonna try again with that version.

**Comment by richardbporter** [comment]
Ok yea - I think Composer commands should be run in the VM for discrepancies such as this or PHP versions, etc. We may want to get to #2489 sooner rather than later to avoid confusion. It could hit people's VMs if they destroy/create or reprovision. I'm not really sure.

**Comment by richardbporter** [comment]
Of course I am unable to require drupal/weight due to memory issues which is something Composer 2 solves. :)

**Comment by joewhitsitt** [comment]
`php -d memory_limit=-1 /usr/local/bin/composer...`

**Comment by richardbporter** [comment]
I've got weight added locally without updating anything else. Let me know if you want me to push that up.

**Comment by cory-skeers** [comment]
@richardbporter That would be great! I made some changes to the update hook as well to create the storage/pull in the config prior to attempting to update the existing field weights.

If you want to push that up, this should be good for testing.

**Comment by richardbporter** [comment]
I'm seeing a broken/missing handler on the view. Probably an config import order-of-operations thing. 

image

**Comment by richardbporter** [comment]
Or I'm doing it wrong. :)

**Comment by cory-skeers** [comment]
Hrm. Looks like it's something in how the update hook is pulling things in that's getting things mixed up. Taking a look.

**Comment by GaryRidgway** [comment]
I actually just tested this  as well, and I am getting the broken handler message as well

**Comment by richardbporter** [comment]
A manual sync and then cim gets the field and view working together. I'm not sure what its choking on in the update hook yet.

**Comment by richardbporter** [comment]
This will be a non-issue soon. Just need to upgrade stuff. https://www.drupal.org/project/drupal/issues/2901418

**Comment by richardbporter** [comment]
Update hook aside, this works as expected. I'm not having any luck with it. I suppose this could go out first then with a follow-up update to set initial weights to 0. Thoughts?

**Comment by cory-skeers** [comment]
@richardbporter I'm leaning that way too. The update hook that doesn't deal with config could be included later, with a quick check to set the weight to 0 only if it's still null, if it gets edited between this and the update hook going out.

**Comment by richardbporter** [comment]
Yea that sounds like a plan.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
