### PR TITLE
Update drupal core 10.3.9

### PR DESCRIPTION
**Pull request by joewhitsitt**
- No database updates
- https://git.drupalcode.org/project/drupal/-/compare/10.3.6...10.3.9

```
  - Upgrading behat/mink (v1.11.0 => v1.12.0)
  - Upgrading composer/ca-bundle (1.5.2 => 1.5.3)
  - Upgrading composer/composer (2.8.1 => 2.8.3)
  - Upgrading composer/pcre (3.3.1 => 3.3.2)
  - Upgrading doctrine/persistence (3.3.3 => 3.4.0)
  - Upgrading drupal/core (10.3.6 => 10.3.9)
  - Upgrading drupal/core-composer-scaffold (10.3.6 => 10.3.9)
  - Upgrading drupal/core-dev (10.3.6 => 10.3.9)
  - Upgrading drupal/core-recommended (10.3.6 => 10.3.9)
  - Upgrading google/protobuf (v3.25.5 => v4.28.3)
  - Upgrading myclabs/deep-copy (1.12.0 => 1.12.1)
  - Upgrading open-telemetry/api (1.1.0 => 1.1.1)
  - Upgrading open-telemetry/gen-otlp-protobuf (1.2.0 => 1.2.1)
  - Upgrading open-telemetry/sdk (1.1.0 => 1.1.2)
  - Upgrading phpdocumentor/reflection-docblock (5.4.1 => 5.6.0)
  - Upgrading phpdocumentor/type-resolver (1.8.2 => 1.10.0)
  - Upgrading phpspec/prophecy (v1.19.0 => v1.20.0)
  - Upgrading phpspec/prophecy-phpunit (v2.2.0 => v2.3.0)
  - Upgrading phpstan/phpstan (1.12.6 => 1.12.11)
  - Upgrading phpstan/phpstan-phpunit (1.4.0 => 1.4.1)
  - Upgrading squizlabs/php_codesniffer (3.10.3 => 3.11.1)
  - Upgrading symfony/console (v6.4.13 => v6.4.15)
  - Upgrading symfony/dependency-injection (v6.4.13 => v6.4.15)
  - Upgrading symfony/error-handler (v6.4.13 => v6.4.14)
  - Upgrading symfony/http-kernel (v6.4.13 => v6.4.15)
  - Upgrading symfony/lock (v6.4.8 => v6.4.13)
  - Upgrading symfony/phpunit-bridge (v6.4.11 => v6.4.13)
  - Upgrading symfony/process (v6.4.14 => v6.4.15)
  - Upgrading symfony/serializer (v6.4.13 => v6.4.15)
  - Upgrading symfony/string (v6.4.13 => v6.4.15)
  - Upgrading symfony/validator (v6.4.13 => v6.4.15)
  - Upgrading symfony/var-dumper (v6.4.13 => v6.4.15)
```

# How to test

I personally synced Admissions and re-installed Default. Logged in and tried some basic content tasks.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Might have an issue related to the WYSIWYG. checking against PROD.

Update: Nope. It is an issue in PROD too. Oh goodie. Made an issue: https://github.com/uiowa/uiowa/issues/8276

**Comment by pyrello** [comment]
Hopefully this will fix the errors we have been seeing: https://git.drupalcode.org/project/drupal/-/compare/10.3.6...10.3.9#35160a7149cdca4988c8775508662e5cd7758511_88_87

```
Uncaught exception 'Error' with message 'Undefined constant "DRUPAL_TEST_IN_CHILD_SITE"' in /mnt/www/html/uiowa/docroot/core/includes/errors.inc:87
```

**Review by pyrello — APPROVED** [review]
I didn't test this exhaustively but spot checked a variety of functionality.

**Comment by pyrello** [comment]
I saw an issue with not being able to replicate the default site homepage and got an error. It was also an issue in `main` so not a blocker here.

**Pull request merged**
