### PR TITLE
bigmenu feature for whitmanweb

### LINKED ISSUE #7266: WhitmanWeb site has a very large menu and the “technical difficulties”
# Problem
The WhitmanWeb site has a very large menu and the “technical difficulties” screen popping up when navigating to the page or trying to make a change has become more frequent recently.

# Steps to reproduce
Go to https://whitmanweb.iwp.uiowa.edu/admin/structure/menu/manage/main. 

# Proposed solution
Revisit https://github.com/uiowa/uiowa/pull/6178/files?

### PR DESCRIPTION
**Pull request by bspeare**
# How to test

Resolves https://github.com/uiowa/uiowa/issues/7266. 

```
 ddev composer install && ddev blt ds --site=whitmanweb.iwp.uiowa.edu &&  ddev drush @iwpwhitmanweb.local config-split:activate bigmenu -y && ddev drush  @iwpwhitmanweb.local uli /admin/structure/menu/manage/main
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Should this be a feature split instead?

**Comment by bspeare** [comment]
@joewhitsitt either one works for me - are you thinking it should?

**Comment by joewhitsitt** [comment]
With the possibility of more sites needing this (engineering, tippie, cnm), I'd vote for a feature that can be toggled on in PROD with less of a footprint (similar to advanced_webform)

**Comment by bspeare** [comment]
Sounds good.  I'll move this back to draft to adjust.

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
ignored the config status and moved the settings to the complete split as it originates with this feature. if a site or other feature overrides the setting that would be capable of a partial split.

**Comment by joewhitsitt** [comment]
changes aside, i was able to successfully interact with the menu without running out of resources.

**Comment by bspeare** [comment]
Thanks @joewhitsitt!

**Pull request merged**
