### PR TITLE
update webform, export config diff

### PR DESCRIPTION
**Pull request by joewhitsitt**
This just bumps ckeditor (previous security release) which is tracked separately in webform. I ran a config export (default, tippie) just in case there were new diffs. Most of the config is just moving around.

### CODE REVIEW

**Review by dnkemper — APPROVED** [review]

**Comment by richardbporter** [comment]
The config moving seems opposite of #3954

**Comment by richardbporter** [comment]
What version are we on/going to?

**Comment by dnkemper** [comment]
6.0.5?

**Comment by joewhitsitt** [comment]
6.0.2 -> 6.0.5

**Comment by joewhitsitt** [comment]
>The config moving seems opposite of #3954

I think the order seems opposite (quirky config 🤷) , but it maintains the html markup tweaks, adds another markup tweak and adds `support_disabled`

**Comment by richardbporter** [comment]
> > The config moving seems opposite of #3954
> 
> I think the order seems opposite, but it maintains the html markup tweaks, adds another markup tweak and adds `support_disabled`

yea. 👍🏻

**Comment by joewhitsitt** [comment]
Thanks both!

**Pull request merged**
