### PR TITLE
[INRC] Grants

### LINKED ISSUE #7821: Grants content type
# Story

As a site owner for LAWINRC, I would like to be able store information about grants so that we can produce The Iowa Grants Guide so organizations can search for funders with a connection to Iowa.

# Additional Info

Their existing functionality has been working well for them and they would like us to develop this feature very similar to their existing functionality.

They want us to eventually migrate the ~700 funders from their current site.

https://inrc.law.uiowa.edu/iowa-grants-guide

currently uses a path at `grants/[node:title]` - let's continue to use this path.

# Fields

**General Information**
- Grantor Name - title field
- Filter Friendly Name - required - additional text field same as Grantor Name but without "the," "a," etc. This makes filtering grants easier for the end user.
- Employer Identification Number (EIN) - text field
- Contact Name - text field
- Contact Title - text field
- Address - Postal Address/Location - currently has country, address 1, address 2, city, state, zip
- Phone - phone
- Fax - phone
- Email - email

**Grant Information**
- Grant Classification - term reference - unlimited - currently checkboxes
- Purpose/Mission - body/summary - not sure if using summary but currently outputting body as part of teaser display
- Restrictions - long text
- Grant sizes - integer - unlimited - required - prefixed with `$`
- Total Grants - integer - single - prefixed with `$`
- Trustees - long text
- Sample Grants - long text
- Website - link - single - optional title
- NTEE Classification - taxonomy - unlimited - select list
- Areas of interest - taxonomy - unlimited - select list
- Type of Grant - taxonomy - unlimited - select list
- PDF Version - media - single - document - pdf
**Location Info**
- Counties* - taxonomy - unlimited - using entity reference view so search/select all capabilities
- Cities* - taxonomy - unlimited - using entity reference view so search/select all capabilities
**Application Info**
- Application Info - long text
- Application Deadline - date - single - year, month, day granularity

**Financial Information**
  - Total Assets - integer - single - prefix with `$`
  - Date of latest financial data - date - single - year, month, day granularity

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7821

# How to test

```
ddev blt ds --site=inrc.law.uiowa.edu && ddev drush @lawinrc.local config:import --source ../config/sites/inrc.law.uiowa.edu --partial -y && ddev drush @lawinrc.local cim -y && ddev drush @lawinrc.local uli
```
Check the Counties and Cities taxonomies--they should be populated with values.
Add a few terms to each of the other site-specific vocabs.
Create a Grant
Compare the fields/options with what is detailed in #7821 
Check against our content type best practices and guidelines: https://docs.prod.drupal.uiowa.edu/development-workflow/content-type-best-practices

### CODE REVIEW

**Comment by joewhitsitt** [comment]
>if anyone is itching for work, I started a PR and it should have everything except a little bit of work on setting up the related taxonomies

not seeing the fields pushed up, so to avoid duplicating work/causing conflicts i feel like we may want to let this sit till tomorrow.

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
might demand a source for this county and city info so i don't need to check each one ;)

**Comment by cory-skeers** [comment]
> might demand a source for this county and city info so i don't need to check each one ;)

You don't know the 99 counties by heart?!

I pulled them from the terms in the d7 database and exported as a csv. So 🤞 they are accurate.

**Comment by joewhitsitt** [comment]
left to do:
- menu settings is currently available to webmasters. remove main menu from node type.
- content type specific metatags (removing schema article, etc.) - similar to https://github.com/uiowa/uiowa/pull/7606/commits/21293e6cd7c55eb869015e0afd2116c0dad31a9d
- determine if we need a select all/none for cities/counties going forward

Screenshot 2024-06-26 at 3 57 06 PM
 
next notes:  
- date of last financial field allowed month/year sans day which might be an issue with migration since the new field requires a day.
- missing title on full node - theming slice.

**Comment by cory-skeers** [comment]
> > might demand a source for this county and city info so i don't need to check each one ;)
> 
> You don't know the 99 counties by heart?!
> 
> I pulled them from the terms in the d7 database and exported as a csv. So 🤞 they are accurate.

This was kinda bugging me, so I pulled the latest I could find from census.gov. Counties unsurprisingly remained the same, but we have 2 more cities included now!

**Comment by joewhitsitt** [comment]
>This was kinda bugging me, so I pulled the latest I could find from census.gov. Counties unsurprisingly remained the same, but we have 2 more cities included now!

Still hoping that UH will eventually be absorbed by Iowa City. Someone told me it is the only municipality in the US that is fully encompassed by only one other municipality. I haven't been able to prove them wrong.

**Comment by cory-skeers** [comment]
> left to do:
> 
> * menu settings is currently available to webmasters. remove main menu from node type.
> * content type specific metatags (removing schema article, etc.) - similar to [21293e6](https://github.com/uiowa/uiowa/commit/21293e6cd7c55eb869015e0afd2116c0dad31a9d)
> * determine if we need a select all/none for cities/counties going forward
> next notes:
> 
> * date of last financial field allowed month/year sans day which might be an issue with migration since the new field requires a day.
> * missing title on full node - theming slice.

Of these, I have removed the menu from the content type, updated the metatags, and added a header to the display to include the title (leaving further edits for the theming slice).

For further discussion I think:
 * Select all/none option for the cities/counties select lists
 * Date of last financial field requiring a day where current site does not (and how that relates to migration in the future)

**Comment by briand44** [comment]
>date of last financial field allowed month/year sans day which might be an issue with migration since the new field requires a day.

I think this was my mistake when I drafted the issue. We probably just want month/year granularity. Sorry. Good catch Joe!

**Comment by joewhitsitt** [comment]
>We probably just want month/year granularity

That is the tricky part. I don't think core or smart_date allow for it anymore.

Tricky but not impossible. No longer site builder friendly: https://debugacademy.com/article/how-to-partial-date-in-drupal

**Review by joewhitsitt — APPROVED** [review]
Solid base to continue with

**Pull request merged**
