### PR TITLE
[INRC] NPO migration

### LINKED ISSUE #7974: setup nonprofit organization migration
# Story

As a LAW INRC website owner, we would like to have our nonprofit organizations migrated from our current site to our new site so we do not have to manually move all that content.

# Additional Info

Migrate all published nonprofit organizations (~ 800)

Even though patterns are the same, we still want to implement redirects since the stripping of characters may not be consistent from D7->D10

**Mappings - v3 -> v1**

- Organization Name - title
- EIN - field_np_employer_id
- Contact Name - field_np_contact_name
- Contact Title - field_np_contact_title
- Address - field_inrc_address - Address/Postal Address - country, address 1, address 2, city, state, zip
- Phone - field_inrc_telephone_number - telephone number
- Email - field_inrc_email - email - required
- NTEE Numbers - field_np_ntee - text field
- Website - field_inrc_website - link - single - title and url
- Image - field_image - single
- Category - field_np_category - term reference - unlimited - migration should create terms
- Denomination - field_np_denomination
- Assets - field_np_assets - integer
- Income - field_np_income - integer
- Revenue - field_np_revenue - integer
- Notes - field_npo_notes - text area - filtered html
- Board resolution date - field_np_board_res_date - date - single - year, month, day granularity
- Last training date - field_np_last_training_date - date - single - year, month, day granularity
- Training attendees - field_np_training_attendees - text area - filtered html
- Training location - field_np_training_location - text field - single
- Documents - field_np_documents - 10
- Expiration Date - field_expiration_date - date - single - year, month, day granularity

We had issues with phone and fax on grants. Anything special we want to do with these here?

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7974 

# How to test

Sync the d7 site locally in DevDesktop (on uiowa703). Pulling files locally is not necessary (and codebase is not necessary either, unless you want to load the site).

Now to SNV3!

```
ddev blt ds --site=inrc.law.uiowa.edu && ddev drush @lawinrc.local en inrc_migrate -y && ddev drush @lawinrc.local uli admin/config/sitenow/sitenow-migrate
```

Complete the migration setup page

- **Database name**: inrc_law_uiowa_edu
- **Database user**: root
- **Database user password**: _leave blank_
- **Database host**: host.docker.internal
- **Database host port**: 33067
- **Base URL**: https://inrc.law.uiowa.edu
- **Public files path**: _leave blank_

You can run all the migrations with
```
ddev drush @lawinrc.local mim --all
```

or individual just the nonprofit related ones with
```
ddev drush @lawinrc.local mim inrc_nonprofit && ddev drush @lawinrc.local mim inrc_nonprofit_redirects
```

Compare nonprofits from the existing site (https://inrc.law.uiowa.edu/register-accountability) to those that have been migrated (https://lawinrc.uiowa.ddev.site/register-accountability) (including that the paths from the existing site resolve to the corresponding grant on the new)

Also check that the nonprofit orgs block (included on https://lawinrc.uiowa.ddev.site/register-accountability) sorts alphabetically.

### CODE REVIEW

**Comment by cory-skeers** [comment]
Email field isn't migrating over properly, and it looks like it wasn't working for the Grants migration either. Looking into fixing it for both.

**Comment by cory-skeers** [comment]
> cory-skeers requested a review from bspeare now

@bspeare you can feel free to review it, but requesting you specifically was unintentional 😆

**Comment by GaryRidgway** [comment]
pulling to review

**Comment by GaryRidgway** [comment]
Did all of the steps required and it looks good to me! Nicely done Cory.

**Review by GaryRidgway — APPROVED** [review]

**Pull request merged**
