### PR TITLE
Added map field to residence halls content type.

### LINKED ISSUE #5476: Ability to add a static map to residence halls
Add a media field to the residence halls content type that allows only static map media type and render it. Discovery into display settings might be necessary.

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #5476 

# How to test

- `ddev blt ds --site housing.uiowa.edu`
- `ddev drush @housing.local uli node/466/edit`
- Add a map to Daum Hall using https://maps.uiowa.edu/?id=1890#!m/591094 and save the node
- Confirm that map placement shows up and looks correct, according to the mockup: https://sandbox.prod.drupal.uiowa.edu/catlett-hall

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling this down to test.

**Comment by bspeare** [comment]
Works great!  It does go a bit crazy and crash the node edit form if you try to add more than one. 

Screen Shot 2022-07-21 at 4 26 06 PM

**Comment by pyrello** [comment]
> Works great! It does go a bit crazy and crash the node edit form if you try to add more than one.
> 
> Screen Shot 2022-07-21 at 4 26 06 PM

I'm really surprised that it even allows you to add more than one.

**Review by bspeare — APPROVED** [review]
Works as expected!

**Comment by joewhitsitt** [comment]
did we just merge a "It does go a bit crazy and crash the node edit form if you try to add more than one."? should we look into this in a follow-up issue?

**Comment by pyrello** [comment]
> did we just merge a "It does go a bit crazy and crash the node edit form if you try to add more than one."? should we look into this in a follow-up issue?

I was not able to replicate the issue.

**Pull request merged**
