### PR TITLE
Feature: Added margin fixes for layouts 

### LINKED ISSUE #3445: Layout builder columns do not correctly render if adjacent columns are empty
# Problem
Layout builder columns do not correctly render if adjacent columns are empty

# Steps to reproduce
As reported by @bewoldt, you can view the issue at https://stanleymuseum.prod.drupal.uiowa.edu/giving.

<details>
Screen Shot 2021-05-03 at 3 58 59 PM
Screen Shot 2021-05-03 at 4 01 55 PM
Screen Shot 2021-05-03 at 4 02 12 PM
</details>

# Proposed solution
- Work with the initial work started in https://github.com/uiowa/uiowa/compare/feature_layout_gaps.
- Test on different browsers
- Test on IE

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3445. 

# How to test
`blt ds --site=sandbox.uiowa.edu`
`yarn workspace uids_base build`

- Go to https://sandbox.local.drupal.uiowa.edu/cards-0 and compare against https://sandbox.prod.drupal.uiowa.edu/cards-0. 
- Try to adjust the column layouts for https://sandbox.local.drupal.uiowa.edu/cards-0 by switching the layout percentage and notice if anything breaks.

### CODE REVIEW

**Comment by makurj** [comment]
I can test this.

**Review by mark-bennett-uiowa — APPROVED** [review]
This seems to fix the spacing issues. Approved for what it fixes. Two consecutive columns with different % settings, combined with a empty column, the layout may look funky but the cards and columns arent getting widened improperly.

**Comment by makurj** [comment]
It looks like there is extra white space on cards with no images. See Card 4 in the screenshot below. Testing in BrowserStack on an iPad.
image

CTA in a 3-column layout is aligning right even though no alignment is set:
image

Changing the percentage for 2 and 3-column sections did not cause any issues.

**Comment by makurj** [comment]
Added a 4-column section and inserted cards in 1st and 3rd column. There's no space in between them.

image

**Comment by mark-bennett-uiowa** [comment]
@makurj that has been an "issue" and I think it has to do with transparent vs white backgrounds.

**Comment by makurj** [comment]
Good to know. Thanks @mark-bennett-uiowa

**Comment by bspeare** [comment]
Converting back to draft to fix a few on the bugs noted above.

**Comment by mark-bennett-uiowa** [comment]
> Added a 4-column section and inserted cards in 1st and 3rd column. There's no space in between them.
> 
> image

@makurj This may be due to the styling of the section, and it may have the Remove default column spacing setting enabled. I was curious about this too, until I found it.

**Comment by bspeare** [comment]
> It looks like there is extra white space on cards with no images. See Card 4 in the screenshot below. Testing in BrowserStack on an iPad.
> image
> 


Looks like this spacing issue is due to the extra margin we are adding only to the left/right aligned card.  So that is why this grid has extra margin of a few of the items.

**Comment by makurj** [comment]
Looks great on iPad Pro 12. On iPad 9, 3-column cards are stacking irrespective of the percentage. Looks good.

**Comment by mark-bennett-uiowa** [comment]
@bspeare Looks good to me as well. Great work on this, thanks bud!

**Pull request merged**
