### PR TITLE
Update drush to `drush_12`

### LINKED ISSUE #6981: Upgrade to Drush 12
Supposedly there is an EOL of November 2023...

https://www.drush.org/12.x/install/#drupal-compatibility

https://github.com/drush-ops/drush/releases/tag/12.0.0

### PR DESCRIPTION
**Pull request by GaryRidgway**
This updates drush to drush 12

# How to test

1. pull this branch
2. test p2lb on hawkeyemarchingband
3. sync some sites with `blt dsa` / `blt ds`
4. Check back on the notes from the issue to see if there is anything else to do.

I am trying to not overtest as Sean was worried about in his comment on the issue, so please let me know if there should be more done to change anything important to test

### CODE REVIEW

**Comment by GaryRidgway** [comment]
The P2LB command is now executing with the `&$context` change, but now I am getting a lot of errors about paragraphs not being deleted, which leads me to believe that maybe its not executing correctly?

<details><summary>Full output here:</summary>
<p>

```
+------------+-------------------------------------------------------------------+-----------+
| Collection | Config                                                            | Operation |
+------------+-------------------------------------------------------------------+-----------+
|            | core.extension                                                    | Update    |
|            | node.type.page                                                    | Update    |
|            | core.entity_view_display.node.page.token                          | Update    |
|            | core.entity_view_display.node.page.teaser                         | Update    |
|            | core.entity_view_display.node.page.default                        | Update    |
|            | core.entity_view_display.node.page.banner                         | Update    |
|            | views.view.content                                                | Update    |
|            | views.view.media_library                                          | Update    |
|            | user.role.webmaster                                               | Update    |
|            | user.role.editor                                                  | Update    |
|            | core.entity_form_display.node.page.default                        | Update    |
|            | views.view.content_v3_converter                                   | Delete    |
|            | core.entity_form_display.paragraph.featured_content.default       | Delete    |
|            | core.entity_form_display.paragraph.webform.default                | Delete    |
|            | core.entity_view_display.paragraph.webform.default                | Delete    |
|            | core.entity_view_display.paragraph.webform.preview                | Delete    |
|            | field.field.paragraph.webform.field_webform                       | Delete    |
|            | field.storage.paragraph.field_webform                             | Delete    |
|            | core.entity_view_display.media.image.edgy                         | Delete    |
|            | core.entity_view_display.media.image.image_large                  | Delete    |
|            | core.entity_view_display.media.image.image_medium                 | Delete    |
|            | core.entity_view_display.media.image.image_small                  | Delete    |
|            | core.entity_view_display.media.image.sitenow_16_9                 | Delete    |
|            | responsive_image.styles.sitenow_16_9                              | Delete    |
|            | responsive_image.styles.ui_edgy_no_crop                           | Delete    |
|            | core.entity_form_display.paragraph.accordion_item.default         | Delete    |
|            | core.entity_form_display.paragraph.card.default                   | Delete    |
|            | core.entity_form_display.paragraph.carousel_image.default         | Delete    |
|            | core.entity_form_display.paragraph.text.default                   | Delete    |
|            | core.entity_view_display.paragraph.accordion_item.default         | Delete    |
|            | core.entity_view_display.paragraph.card.default                   | Delete    |
|            | core.entity_view_display.paragraph.carousel_image.default         | Delete    |
|            | core.entity_view_display.paragraph.text.default                   | Delete    |
|            | core.entity_view_display.paragraph.accordion_item.preview         | Delete    |
|            | field.field.paragraph.accordion_item.field_accordion_item_body    | Delete    |
|            | core.entity_view_display.paragraph.card.preview                   | Delete    |
|            | field.field.paragraph.card.field_card_body                        | Delete    |
|            | core.entity_view_display.paragraph.carousel_image.preview         | Delete    |
|            | field.field.paragraph.carousel_image.field_carousel_image_caption | Delete    |
|            | core.entity_view_display.paragraph.text.preview                   | Delete    |
|            | field.field.paragraph.text.field_text_body                        | Delete    |
|            | field.storage.paragraph.field_accordion_item_body                 | Delete    |
|            | field.storage.paragraph.field_card_body                           | Delete    |
|            | field.storage.paragraph.field_carousel_image_caption              | Delete    |
|            | field.storage.paragraph.field_text_body                           | Delete    |
|            | core.entity_form_display.paragraph.articles.default               | Delete    |
|            | core.entity_view_display.paragraph.articles.default               | Delete    |
|            | core.entity_view_display.paragraph.articles.preview               | Delete    |
|            | field.field.paragraph.articles.field_reference                    | Delete    |
|            | core.entity_form_display.paragraph.people.default                 | Delete    |
|            | core.entity_view_display.paragraph.people.default                 | Delete    |
|            | core.entity_view_display.paragraph.people.preview                 | Delete    |
|            | field.field.paragraph.people.field_reference                      | Delete    |
|            | field.storage.paragraph.field_reference                           | Delete    |
|            | system.action.sitenow_p2lb_revert                                 | Delete    |
|            | system.action.sitenow_p2lb_convert                                | Delete    |
|            | core.entity_form_display.paragraph.section.default                | Delete    |
|            | core.entity_view_display.paragraph.section.default                | Delete    |
|            | core.entity_view_display.paragraph.section.preview                | Delete    |
|            | field.field.paragraph.section.field_section_content_block         | Delete    |
|            | field.storage.paragraph.field_section_content_block               | Delete    |
|            | core.entity_form_display.paragraph.events.default                 | Delete    |
|            | core.entity_view_display.paragraph.events.default                 | Delete    |
|            | core.entity_view_display.paragraph.events.preview                 | Delete    |
|            | field.field.paragraph.events.field_events_audiences               | Delete    |
|            | field.field.paragraph.events.field_events_department              | Delete    |
|            | field.field.paragraph.events.field_events_event_types             | Delete    |
|            | field.field.paragraph.events.field_events_gen_interests           | Delete    |
|            | field.field.paragraph.events.field_events_keywords                | Delete    |
|            | field.field.paragraph.events.field_events_more                    | Delete    |
|            | field.field.paragraph.events.field_events_more_path               | Delete    |
|            | field.field.paragraph.events.field_events_results                 | Delete    |
|            | field.storage.paragraph.field_events_audiences                    | Delete    |
|            | field.storage.paragraph.field_events_department                   | Delete    |
|            | field.storage.paragraph.field_events_event_types                  | Delete    |
|            | field.storage.paragraph.field_events_gen_interests                | Delete    |
|            | field.storage.paragraph.field_events_keywords                     | Delete    |
|            | field.storage.paragraph.field_events_more                         | Delete    |
|            | field.storage.paragraph.field_events_more_path                    | Delete    |
|            | field.storage.paragraph.field_events_results                      | Delete    |
|            | core.entity_view_display.paragraph.featured_content.default       | Delete    |
|            | core.entity_view_display.paragraph.featured_content.preview       | Delete    |
|            | field.field.paragraph.featured_content.field_featured_content     | Delete    |
|            | paragraphs.settings                                               | Delete    |
|            | field.field.paragraph.webform.field_uip_classes                   | Delete    |
|            | field.field.paragraph.webform.field_uip_colwidth                  | Delete    |
|            | field.field.paragraph.webform.field_uip_display_title             | Delete    |
|            | field.field.paragraph.webform.field_uip_id                        | Delete    |
|            | field.field.paragraph.webform.field_uip_title                     | Delete    |
|            | paragraphs.paragraphs_type.webform                                | Delete    |
|            | field.field.paragraph.text.field_uip_classes                      | Delete    |
|            | field.field.paragraph.text.field_uip_colwidth                     | Delete    |
|            | field.field.paragraph.text.field_uip_id                           | Delete    |
|            | paragraphs.paragraphs_type.text                                   | Delete    |
|            | field.field.node.page.field_page_content_block                    | Delete    |
|            | field.field.paragraph.section.field_section_alignitems            | Delete    |
|            | field.field.paragraph.section.field_section_container             | Delete    |
|            | field.field.paragraph.section.field_section_image                 | Delete    |
|            | field.field.paragraph.section.field_section_justifycontent        | Delete    |
|            | field.field.paragraph.section.field_section_title                 | Delete    |
|            | field.field.paragraph.section.field_uip_classes                   | Delete    |
|            | field.field.paragraph.section.field_uip_id                        | Delete    |
|            | paragraphs.paragraphs_type.section                                | Delete    |
|            | field.field.paragraph.people.field_people_more                    | Delete    |
|            | field.field.paragraph.people.field_people_more_path               | Delete    |
|            | field.field.paragraph.people.field_people_sort                    | Delete    |
|            | field.field.paragraph.people.field_uip_classes                    | Delete    |
|            | field.field.paragraph.people.field_uip_colwidth                   | Delete    |
|            | field.field.paragraph.people.field_uip_display_title              | Delete    |
|            | field.field.paragraph.people.field_uip_id                         | Delete    |
|            | field.field.paragraph.people.field_uip_items                      | Delete    |
|            | field.field.paragraph.people.field_uip_pager                      | Delete    |
|            | field.field.paragraph.people.field_uip_title                      | Delete    |
|            | paragraphs.paragraphs_type.people                                 | Delete    |
|            | core.entity_form_display.paragraph.image_gallery.default          | Delete    |
|            | core.entity_view_display.paragraph.image_gallery.default          | Delete    |
|            | core.entity_view_display.paragraph.image_gallery.preview          | Delete    |
|            | field.field.paragraph.image_gallery.field_image                   | Delete    |
|            | field.field.paragraph.image_gallery.field_uip_classes             | Delete    |
|            | field.field.paragraph.image_gallery.field_uip_colwidth            | Delete    |
|            | field.field.paragraph.image_gallery.field_uip_display_title       | Delete    |
|            | field.field.paragraph.image_gallery.field_uip_id                  | Delete    |
|            | field.field.paragraph.image_gallery.field_uip_title               | Delete    |
|            | paragraphs.paragraphs_type.image_gallery                          | Delete    |
|            | field.field.paragraph.featured_content.field_uip_classes          | Delete    |
|            | field.field.paragraph.featured_content.field_uip_colwidth         | Delete    |
|            | field.field.paragraph.featured_content.field_uip_display_title    | Delete    |
|            | field.field.paragraph.featured_content.field_uip_id               | Delete    |
|            | field.field.paragraph.featured_content.field_uip_title            | Delete    |
|            | paragraphs.paragraphs_type.featured_content                       | Delete    |
|            | field.field.paragraph.events.field_events_past                    | Delete    |
|            | field.field.paragraph.events.field_uip_classes                    | Delete    |
|            | field.field.paragraph.events.field_uip_colwidth                   | Delete    |
|            | field.field.paragraph.events.field_uip_display_title              | Delete    |
|            | field.field.paragraph.events.field_uip_id                         | Delete    |
|            | field.field.paragraph.events.field_uip_title                      | Delete    |
|            | paragraphs.paragraphs_type.events                                 | Delete    |
|            | core.entity_form_display.paragraph.carousel.default               | Delete    |
|            | core.entity_view_display.paragraph.carousel.default               | Delete    |
|            | core.entity_view_display.paragraph.carousel.preview               | Delete    |
|            | field.field.paragraph.carousel.field_carousel_item                | Delete    |
|            | field.field.paragraph.carousel_image.field_carousel_image_image   | Delete    |
|            | field.field.paragraph.carousel_image.field_uip_classes            | Delete    |
|            | field.field.paragraph.carousel_image.field_uip_id                 | Delete    |
|            | paragraphs.paragraphs_type.carousel_image                         | Delete    |
|            | field.field.paragraph.carousel.field_uip_classes                  | Delete    |
|            | field.field.paragraph.carousel.field_uip_colwidth                 | Delete    |
|            | field.field.paragraph.carousel.field_uip_display_title            | Delete    |
|            | field.field.paragraph.carousel.field_uip_id                       | Delete    |
|            | field.field.paragraph.carousel.field_uip_title                    | Delete    |
|            | paragraphs.paragraphs_type.carousel                               | Delete    |
|            | field.field.paragraph.card.field_card_image                       | Delete    |
|            | field.field.paragraph.card.field_card_link                        | Delete    |
|            | field.field.paragraph.card.field_card_subtitle                    | Delete    |
|            | field.field.paragraph.card.field_card_title                       | Delete    |
|            | field.field.paragraph.card.field_uip_classes                      | Delete    |
|            | field.field.paragraph.card.field_uip_colwidth                     | Delete    |
|            | field.field.paragraph.card.field_uip_id                           | Delete    |
|            | paragraphs.paragraphs_type.card                                   | Delete    |
|            | core.entity_form_display.paragraph.blockquote.default             | Delete    |
|            | core.entity_view_display.paragraph.blockquote.default             | Delete    |
|            | core.entity_view_display.paragraph.blockquote.preview             | Delete    |
|            | field.field.paragraph.blockquote.field_blockquote_cite            | Delete    |
|            | field.field.paragraph.blockquote.field_blockquote_content         | Delete    |
|            | field.field.paragraph.blockquote.field_blockquote_footer          | Delete    |
|            | field.field.paragraph.blockquote.field_uip_classes                | Delete    |
|            | field.field.paragraph.blockquote.field_uip_colwidth               | Delete    |
|            | field.field.paragraph.blockquote.field_uip_id                     | Delete    |
|            | paragraphs.paragraphs_type.blockquote                             | Delete    |
|            | field.field.paragraph.articles.field_articles_more                | Delete    |
|            | field.field.paragraph.articles.field_articles_more_path           | Delete    |
|            | field.field.paragraph.articles.field_uip_classes                  | Delete    |
|            | field.field.paragraph.articles.field_uip_colwidth                 | Delete    |
|            | field.field.paragraph.articles.field_uip_display_title            | Delete    |
|            | field.field.paragraph.articles.field_uip_id                       | Delete    |
|            | field.field.paragraph.articles.field_uip_items                    | Delete    |
|            | field.field.paragraph.articles.field_uip_pager                    | Delete    |
|            | field.field.paragraph.articles.field_uip_title                    | Delete    |
|            | paragraphs.paragraphs_type.articles                               | Delete    |
|            | core.entity_form_display.paragraph.accordion.default              | Delete    |
|            | core.entity_view_display.paragraph.accordion.default              | Delete    |
|            | core.entity_view_display.paragraph.accordion.preview              | Delete    |
|            | field.field.paragraph.accordion.field_accordion_item              | Delete    |
|            | field.field.paragraph.accordion_item.field_accordion_item_title   | Delete    |
|            | field.field.paragraph.accordion_item.field_uip_id                 | Delete    |
|            | paragraphs.paragraphs_type.accordion_item                         | Delete    |
|            | field.field.paragraph.accordion.field_uip_classes                 | Delete    |
|            | field.field.paragraph.accordion.field_uip_colwidth                | Delete    |
|            | field.field.paragraph.accordion.field_uip_display_title           | Delete    |
|            | field.field.paragraph.accordion.field_uip_id                      | Delete    |
|            | field.field.paragraph.accordion.field_uip_title                   | Delete    |
|            | paragraphs.paragraphs_type.accordion                              | Delete    |
|            | core.entity_view_mode.paragraph.token                             | Delete    |
|            | field.storage.node.field_page_content_block                       | Delete    |
|            | field.storage.paragraph.field_accordion_item                      | Delete    |
|            | field.storage.paragraph.field_accordion_item_title                | Delete    |
|            | field.storage.paragraph.field_articles_more                       | Delete    |
|            | field.storage.paragraph.field_articles_more_path                  | Delete    |
|            | field.storage.paragraph.field_blockquote_cite                     | Delete    |
|            | field.storage.paragraph.field_blockquote_content                  | Delete    |
|            | field.storage.paragraph.field_blockquote_footer                   | Delete    |
|            | field.storage.paragraph.field_card_image                          | Delete    |
|            | field.storage.paragraph.field_card_link                           | Delete    |
|            | field.storage.paragraph.field_card_subtitle                       | Delete    |
|            | field.storage.paragraph.field_card_title                          | Delete    |
|            | field.storage.paragraph.field_carousel_image_image                | Delete    |
|            | field.storage.paragraph.field_carousel_item                       | Delete    |
|            | field.storage.paragraph.field_events_past                         | Delete    |
|            | field.storage.paragraph.field_featured_content                    | Delete    |
|            | field.storage.paragraph.field_image                               | Delete    |
|            | field.storage.paragraph.field_people_more                         | Delete    |
|            | field.storage.paragraph.field_people_more_path                    | Delete    |
|            | field.storage.paragraph.field_people_sort                         | Delete    |
|            | field.storage.paragraph.field_section_alignitems                  | Delete    |
|            | field.storage.paragraph.field_section_container                   | Delete    |
|            | field.storage.paragraph.field_section_image                       | Delete    |
|            | field.storage.paragraph.field_section_justifycontent              | Delete    |
|            | field.storage.paragraph.field_section_title                       | Delete    |
|            | field.storage.paragraph.field_uip_classes                         | Delete    |
|            | field.storage.paragraph.field_uip_colwidth                        | Delete    |
|            | field.storage.paragraph.field_uip_display_title                   | Delete    |
|            | field.storage.paragraph.field_uip_id                              | Delete    |
|            | field.storage.paragraph.field_uip_items                           | Delete    |
|            | field.storage.paragraph.field_uip_pager                           | Delete    |
|            | field.storage.paragraph.field_uip_title                           | Delete    |
|            | field.field.node.page.field_v3_conversion_revision_id             | Delete    |
|            | field.storage.node.field_v3_conversion_revision_id                | Delete    |
|            | metatag.metatag_defaults.node__page                               | Delete    |
|            | core.entity_view_mode.media.edgy                                  | Delete    |
|            | core.entity_view_mode.media.image_large                           | Delete    |
|            | core.entity_view_mode.media.image_medium                          | Delete    |
|            | core.entity_view_mode.media.image_small                           | Delete    |
|            | core.entity_view_mode.media.sitenow_16_9                          | Delete    |
|            | image.style.ui_edgy_no_crop_xl                                    | Delete    |
|            | image.style.ui_edgy_no_crop_sm                                    | Delete    |
|            | image.style.ui_edgy_no_crop_md                                    | Delete    |
|            | image.style.ui_edgy_no_crop_lg                                    | Delete    |
|            | image.style.sitenow_16_9_xlarge                                   | Delete    |
|            | image.style.sitenow_16_9_small                                    | Delete    |
|            | image.style.sitenow_16_9_medium                                   | Delete    |
|            | image.style.sitenow_16_9_large                                    | Delete    |
+------------+-------------------------------------------------------------------+-----------+

 Import the listed configuration changes? (yes/no) [yes]:
 > >  [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Webform</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Text</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Section</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Image Gallery</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Featured Content</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Carousel Image</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Carousel</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Card</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Blockquote</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Articles</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Accordion Item</em>. These entities need to be deleted before importing.
> Entities exist of type <em class="placeholder">Paragraph</em> and <em class="placeholder">Paragraph type</em> <em class="placeholder">Accordion</em>. These entities need to be deleted before importing. in Drupal\Core\Config\ConfigImporter->validate() (line 814 of /var/www/html/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php). 
> 
> In ConfigImportCommands.php line 290:
>                                                                                   
>   The import failed due to the following reasons:                                 
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Webform</em>. These en  
>   tities need to be deleted before importing.                                     
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Text</em>. These entit  
>   ies need to be deleted before importing.                                        
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Section</em>. These en  
>   tities need to be deleted before importing.                                     
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Image Gallery</em>. Th  
>   ese entities need to be deleted before importing.                               
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Featured Content</em>.  
>    These entities need to be deleted before importing.                            
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Carousel Image</em>. T  
>   hese entities need to be deleted before importing.                              
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Carousel</em>. These e  
>   ntities need to be deleted before importing.                                    
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Card</em>. These entit  
>   ies need to be deleted before importing.                                        
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Blockquote</em>. These  
>    entities need to be deleted before importing.                                  
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Articles</em>. These e  
>   ntities need to be deleted before importing.                                    
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Accordion Item</em>. T  
>   hese entities need to be deleted before importing.                              
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Accordion</em>. These   
>   entities need to be deleted before importing.                                   
>                                                                                   
> 
> In ConfigImporter.php line 814:
>                                                                                   
>   There were errors validating the config synchronization.                        
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Webform</em>. These en  
>   tities need to be deleted before importing.                                     
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Text</em>. These entit  
>   ies need to be deleted before importing.                                        
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Section</em>. These en  
>   tities need to be deleted before importing.                                     
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Image Gallery</em>. Th  
>   ese entities need to be deleted before importing.                               
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Featured Content</em>.  
>    These entities need to be deleted before importing.                            
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Carousel Image</em>. T  
>   hese entities need to be deleted before importing.                              
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Carousel</em>. These e  
>   ntities need to be deleted before importing.                                    
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Card</em>. These entit  
>   ies need to be deleted before importing.                                        
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Blockquote</em>. These  
>    entities need to be deleted before importing.                                  
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Articles</em>. These e  
>   ntities need to be deleted before importing.                                    
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Accordion Item</em>. T  
>   hese entities need to be deleted before importing.                              
>   Entities exist of type <em class="placeholder">Paragraph</em> and <em class="p  
>   laceholder">Paragraph type</em> <em class="placeholder">Accordion</em>. These   
>   entities need to be deleted before importing.    
```

</p>
</details> 

UPDATE: I hadnt published the converted nodes, so I got errors, the conversion is working completely fine!

**Comment by bspeare** [comment]
Testing this out.

**Comment by bspeare** [comment]
Noticing the log messages like https://github.com/uiowa/uiowa/blob/main/docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php#L87 for `ddev drush @facilities.local facilities_core:projects_import` and `ddev drush @facilities.local facilities_core:buildings_import` are no longer appearing.   Do we fix (https://github.com/uiowa/uiowa/blob/main/docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php) here or in future issues?

**Comment by GaryRidgway** [comment]
> Noticing the log messages like https://github.com/uiowa/uiowa/blob/main/docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php#L87 for `ddev drush @facilities.local facilities_core:projects_import` and `ddev drush @facilities.local facilities_core:buildings_import` are no longer appearing. Do we fix (https://github.com/uiowa/uiowa/blob/main/docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php) here or in future issues?


 thanks for the catch! I think that probably makes sense to fix here if it is affecting a few different outputs from commands. Thoughts from anyone else?

**Comment by GaryRidgway** [comment]
A potential option is to use something like `print` or `echo` instead of those logger options to output simple messages. Is there any issue with this?

**Comment by GaryRidgway** [comment]
Looks like P2LB is [implementing logger](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_p2lb/src/Commands/P2LbCommands.php#L13) differently than Facilities is. I think we should replan this issue if we want to add in implementations of logger to mimic those that are working for those that are not.

**Comment by pyrello** [comment]
> A potential option is to use something like `print` or `echo` instead of those logger options to output simple messages. Is there any issue with this?

If there is no other way to get it to work, then this might be a good temporary option. However, I think the downside to this is that we are not invoking the classes that expected to be involved with logging for Drush, and so we may be missing some step by going the route. We won't necessarily know what we are missing, but it could become important at some point and we'd have to remember that we are using the non-standard implementation. 

> Looks like P2LB is [implementing logger](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_p2lb/src/Commands/P2LbCommands.php#L13) differently than Facilities is. I think we should replan this issue if we want to add in implementations of logger to mimic those that are working for those that are not.

If there are a lot of implementations that are in the mold of the non-working Facilities logging, then I would agree with planning a new issue to fix those. If the Facilities commands logging implementation is an outlier, J think we should just fix it now as I believe the overhead to re-plan will be more work than fixing the implementations in a single file.

**Comment by GaryRidgway** [comment]
> > A potential option is to use something like `print` or `echo` instead of those logger options to output simple messages. Is there any issue with this?
> 
> If there is no other way to get it to work, then this might be a good temporary option. However, I think the downside to this is that we are not invoking the classes that expected to be involved with logging for Drush, and so we may be missing some step by going the route. We won't necessarily know what we are missing, but it could become important at some point and we'd have to remember that we are using the non-standard implementation.
> 
> > Looks like P2LB is [implementing logger](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/sitenow_p2lb/src/Commands/P2LbCommands.php#L13) differently than Facilities is. I think we should replan this issue if we want to add in implementations of logger to mimic those that are working for those that are not.
> 
> If there are a lot of implementations that are in the mold of the non-working Facilities logging, then I would agree with planning a new issue to fix those. If the Facilities commands logging implementation is an outlier, J think we should just fix it now as I believe the overhead to re-plan will be more work than fixing the implementations in a single file.

In reference to the issues with Facilities, @bspeare has noted that it is more than just facilities, classrooms has this issue as well, and that means there are probably more. 

@joewhitsitt has proposed that we push this forward and accept that the logger isn't working for some things right now and plan fixing that as a different slice. I think that is a fair way to proceed as well, but am open to anything.

EDIT: I talked to Sean about proposing to see if I can find a path forward to solve the issue this afternoon. If I cannot, then we can re-slice.

**Comment by joewhitsitt** [comment]
Tried a few blt commands while working support since the acquia-blt upgrade is part of this PR. Confirmed that `blt ugd` and `blt ugc` work as expected.

**Comment by joewhitsitt** [comment]
It looks like our previous version output to the terminal but also to the syslog (enable dblog) making it visible to [Splunk](https://splunk.its.uiowa.edu/en-US/app/search/search?q=search%20index%3Duiowa-acquia%20%22That%20is%20neat.%22&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-30d%40d&latest=now&sid=1707330236.70779_EDED3979-0BD0-4DD8-A05C-4F129EBB094A). Just something to think about when switching this out https://github.com/uiowa/uiowa/pull/7310/commits/a05ce8c3b50181ea79764c743061deefea66b214

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and things are working well. Followup issue has already been made for the dblogging, so I think this is good to go!

**Pull request merged**
