### PR TITLE
[Hotfix] Added registration link back into iswf layout

### PR DESCRIPTION
**Pull request by bspeare**
```
ddev blt ds --site=iowasummerwritingfestival.uiowa.edu && ddev drush @iowasummerwritingfestival.local uli event/521/developing-memoir
```

Verify that custom gold register button appears.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Review by joewhitsitt — APPROVED** [review]
This looks good. Tested works. Scratching my head trying to understand how this happened. The new github file explorer doesn't seem to reveal where this got removed

https://github.com/uiowa/uiowa/commits/main/config/sites/iowasummerwritingfestival.uiowa.edu/core.entity_view_display.node.event.default.yml

**Comment by joewhitsitt** [comment]
This seems to show a big shuffle. https://github.com/uiowa/uiowa/commit/784292957efa3a2bfe981eb3a07c00d3174db008#diff-a640eb67a41d56cc16a547241730bf0fda8d5205f411ea53d3e3157d033f6bad

Do we need to check for anything else?

**Comment by bspeare** [comment]
@joewhitsitt Yes, I found the issue and I'm fixing it in the attendance pr here https://github.com/uiowa/uiowa/pull/6486/commits/d7a652bb6d0cf1e4649bba7c8f64ea4bedee9e0f.  The code was outside the layout region that it needed to be under.

**Pull request merged**
