### PR TITLE
[Bug] Contextual edit links fix

### LINKED ISSUE #7777: Block edit controls are unusable if the block is smaller than the height of the block
# Problem
As reported by Jean, block edit controls are unusable if the block is smaller than the height of the block

# Steps to reproduce

https://github.com/uiowa/uiowa/assets/1036433/65986caf-deec-4937-a0bd-4b0a42bbaa9a

# Proposed solution
- Adjust admin styles for text area blocks to set a larger minimum height.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7777

Solves a regression introduced in https://github.com/uiowa/uiowa/pull/7618.   In this fix, we target the vertical video wrapper only for container queries so that we aren't broadly targeting the text area block.   I've also increased the height of the card block if only a title is set on the card with the borderless property.   When we introduced Container queries we lost the ability to absolutely position, which is why targeting the text area block for container queries for vertical video sizing created this issue with the contextual links. 

# How to test

```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /contextual-link-test
```
- Confirm that you can edit the text and card blocks on the testing page. 
- Confirm vertical video floated right in text area is still set at max-width 50% through container query on /vertical-video and compare to https://sandbox.prod.drupal.uiowa.edu/vertical-video

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
Noticing some padding and wasn't sure if it is expected or not. Technically this meets the testing instructions.

Screenshot 2024-06-07 at 10 23 51 AM
Screenshot 2024-06-07 at 10 25 43 AM

**Comment by bspeare** [comment]
@joewhitsitt let me fix that.

**Comment by bspeare** [comment]
Moving back to draft to fix vertical video alignment withing WYSIWYG.

**Comment by bspeare** [comment]
This is ready for review again.

**Review by joewhitsitt — APPROVED** [review]
oh dear, that css `:has` is a game changer! 

confirmed baseline support https://caniuse.com/css-has

>For example, a:has(img) selects all <a> elements that contain an `` child.

the example alone just makes me salivate!

**Pull request merged**
