### PR TITLE
[IWP] Writer bio

### LINKED ISSUE #7549: Writers Bio content type and site split
# Story

As an IWP site owner, I would like a writers bio content type so that we can showcase writers and their sample works of those that attend a Fall residency or other auxiliary programs.

# Additional Info

**Current links**
https://iwp.uiowa.edu/residency/participants
https://iwp.uiowa.edu/residency/participants-by-region
https://iwp.uiowa.edu/residency/participants-by-year

Epic https://github.com/uiowa/uiowa/issues/7358

content type creation notes - https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/Content%20type%20creation%20notes/Content%20type%20creation%20notes.aspx

url pattern - writers/[session]/[title]

**Fields**
- [x] Title - name
- [x] Photo - 1 - not required
- [x] Photo credit - text - Rare but needed - example https://iwp.uiowa.edu/writers/ghayat-almadhoun
- [x] *Session/Status - taxonomy - years/sessions - no need to go to term page if taxonomy - single
- [x] *Countries - taxonomy - want ability to manage these and not have a default country list - permission to create/edit/remove - need to show countries as they were prior to a name change - can be flat hierarchy - multi valued 
- [x] family name - need this for sorting but doesn't get output and can't be used to create title because some cultures have family name first.
- [x] given name - need this for sorting but doesn't get output and can't be used to create title
- [x] *Languages - taxonomy - multiple - no need to go to a term page
- [x] Bio - Filtered html
- [x] Writing sample - file upload - single
- [x] Writing sample - original language - file upload - single

On the map interview - they would like this to be a multi-valued link field with a title. Existing data would be migrated with the title text "On the map interview". This may change based on an upcoming conversation around media galleries.

# Proposed Solution

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7549

# How to test

```
ddev blt ds --site=iwp.uiowa.edu && ddev drush @iwp.local config:import --source ../config/sites/iwp.uiowa.edu --partial -y && ddev drush @iwp.local cim -y && ddev drush @iwp.local en devel_generate && ddev drush @iwp.local devel-generate:content 40 --bundles writer_bio && ddev drush @iwp.local uli /
```
1. Add a session year `1996`
2. Add a writer bio entry: https://iwp.uiowa.ddev.site/node/add/writer_bio
3. Confirm countries and languages are multiselect
4. Confirm writing sample files render with 'Writing Sample Original Language' and `Writing Sample`
5. Confirm taxonomy is rabbit holed for anonymous users
6. Review content type creation checkboxes below in details

<details>

- [x] Node type
- [x] Fields (can any existing base fields be used? field_image (featured image), body, field_teaser)
- [x] Use body field with summary enabled
- [x] Default display
        - We have been defaulting to using layout builder to set these up. At a bare minimum, it is recommended that there is a separate header (title, breadcrumbs) and content sections to handle spacing correctly. Currently there is a hack to establish the layout in config but then copy/paste/cim an existing layout display that contains a header section for consistency.
- [x] Teaser display
- [x] Form display
- [x] Disable promote to front page unless your custom content type needs it.
- [x] Sticky if you plan on using it.
- [x] Revisions should be max of 10
- [x] Preview settings (don't require)
- [x] Sitemap enabled
- [x] Path alias pattern
- [x] Allowed in main menu?
- [x] Metatags (add the existing field field_meta_tags to the content type, configure a separate metatag bucket)
- [ ] Schema.org Blueprints (map new and existing fields to a schema.org type and properties)
- [x] Should it be allowed to be referenced in the Featured Content block? (if so, field.field.block_content.featured_content.field_featured_content_item will need a partial split)
- [x] Moderation workflow - copy the settings from our standard content types
        - For moderation control to be added to a Layout Builder content template without causing errors, the form display for the content type needs to be re-saved (for some reason). After that, the moderation control block should be able to be placed without issue.
        - After syncing the site, cim and cr in order to get the moderation workflow block to work.
- [x] Role permissions
- [x] Consider using _sitenow_node_form_defaults() - This puts certain shared fields in the sidebar.

</details>

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test after grooming

**Comment by joewhitsitt** [comment]
Noticing a couple things:

- metatag.settings needs to be partial split to only include certain SEO buckets. For example we don't want site verification, Schema:Article showing to editors on this content type.
- The node image seems to set to widescreen instead of square causing a really blown up image.

**Comment by bspeare** [comment]
@joewhitsitt Thanks for catching those, does [21293e6](https://github.com/uiowa/uiowa/pull/7606/commits/21293e6cd7c55eb869015e0afd2116c0dad31a9d) resolve the metatag issues?

**Review by joewhitsitt — APPROVED** [review]
Yes it does, thanks for the quick changes. Let's get this in front of them for review.

**Pull request merged**
