### PR TITLE
Initialize byrne.lab.uiowa.edu multisite on uiowa

### PR DESCRIPTION
**Pull request by e-marie-w**
Provisioned bryne.lab.uiowa.edu on uiowa because 01 had more SANs and 02 more DBs so I went with middle option.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
future reference, *.lab and our other pre-approved patterns don't count against SANs

**Review by dnkemper — APPROVED** [review]

**Comment by e-marie-w** [comment]
Ahh good to know, thanks @joewhitsitt! And thanks @dnkemper for approving!

**Comment by dnkemper** [comment]
@e-marie-w @joewhitsitt I learned something new today as well! Should we add that to provision message? Looks like everyone has been provisioning sites in uiowa/uiowa01 vs uiowa02 or am I misunderstanding?

**Comment by dnkemper** [comment]
OH DUH. Was thinking about databases. JK

**Comment by joewhitsitt** [comment]
@dnkemper When the results come up, it will say that *.lab is already covered on all three in the terminal table because of the wildcard. it won't add to the SAN count. that is why dbs/sans count don't match.

**Pull request merged**
