### PR TITLE
[Facilities] Artist person type, artist artwork view, buliding artwork view, and artwork search block

### LINKED ISSUE #7113: Facilities Artist content
# Story

As a Facilities site editor, I would like to be able to create artist content so that site visitors can see information about artists and their artwork.

# Additional Info

Artist pages should show artist info along with teasers of their artwork.
They'll need the ability to filter artwork by artist when we build the gallery.
If we build a content type for this we will need to update the reference on the artwork content type as that currently is a reference to the person content type.

Examples of artist pages
https://www.facilities.uiowa.edu/art-on-campus/artist/lynn-basa
https://www.facilities.uiowa.edu/charles-ray

**Current Fields**
- Title - generated from first and last name
- First Name - required - text
- Middle - text - no longer needed
- Last - required - text
- Nationality - text
- Birth Year - integer
- Death Year - integer
- Bio - filtered html
- Website - title and url

# Proposed Solution

- Create a split for the person content type for Facilities
- Facilities split should have a new person type for "Artist"
- Facilities split should contain artist specific fields
    - Nationality
    - Birth Year
    - Death Year
    - Website
- Show/hide appropriate fields based on person type
- Output artist specific fields on Facilities person nodes
- #6660

### LINKED ISSUE #7144: Gallery view of artwork with filters
# Story

As a Facilities site owner, I would like a searchable and filterable gallery view of artwork so that users can easily browse and find particular pieces of art.

# Additional Info

https://www.facilities.uiowa.edu/campus-spaces/art-campus/art-campus-gallery

- Single search box that allows searching/filtering by artwork title, artist, artwork description.
- Filters
    - status
    - building
    - artist
    - medium
- Output grid of artwork teasers with paging

# Proposed Solution

- [ ] block view of artwork teasers displayed in grid (using previous teaser grid work)
- [ ] search filter that searches artwork title, artist name, artwork description
- [ ] filters for status, building, artist and medium (single value select lists, top stacked)

### LINKED ISSUE #7150: display artwork on artist pages and building pages
# Stories

As a Facilities site owner, I would like visitors to an artist page (person) to be able to view artwork by that particular artist.

As a Facilities site owner, I would like visitors to building pages to be able to view artwork that is located in that particular building.

# Additional Info

https://www.facilities.uiowa.edu/david-naso

https://www.facilities.uiowa.edu/building/0134

- Output artwork teasers

# Proposed Solution

- [ ] output grid of artwork teasers on artist (people) page
- [ ] output grid of artwork teasers on building page
- [ ] verify no caching issues when a new piece of artwork is added

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7113
Resolves https://github.com/uiowa/uiowa/issues/7144
Resolves https://github.com/uiowa/uiowa/issues/7150

# How to test

```
ddev blt ds --site=facilities.uiowa.edu  && ddev drush @facilities.local uli /node/3636/edit
```

- Edit /node/3636/edit and select `Artist` and confirm that new fields appear.   Save and confirm that new fields appear above the biography. 
- Confirm "Artwork" block appears on the person node page with teaser cards in a three column grid.
- Go to https://facilities.uiowa.ddev.site/building/0189 and confirm that artwork teasers are displayed on only that page. 
- Add a new "Page" and confirm that the "Artwork: Search block" Shows up in "Site Custom".   Add the block and test out the search functionality.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
- I remembered that unchecking the person type retains the values of the allowed_fields. Knowing there is previous work out there like this, this is just a mental note to self for someday to possibly approve upon.
- Should we disable the "items to display" view block option since we want it to be a grid of 8?
- Something is funky with regard to the filters. If I type in `basa` i only get one result. if i reset that and select the artist, i get all back. if I just type a `b` i get two back (created two more). I am going to poke a bit at this.
- I don't love the name `Artwork: Search block` as I expected just a search block that was wired up to send me to a view page based on previous work. How about `Artwork list`?

**Comment by bspeare** [comment]
I did not do the work here outlined on https://github.com/uiowa/uiowa/issues/6660.  This work seems like we should groom separately and plan for a separate sprint.

**Comment by joewhitsitt** [comment]
Had to change the Content: Artist to Content: Title with a relationship to the content referenced by the Artist field for the combined filter to work on the correct content.

**Review by joewhitsitt — APPROVED** [review]
Looking good. Love how much of these three issues is now handled in config. The base styling is really paying off!

**Pull request merged**
