### PR TITLE
D10 compatible releases

### PR DESCRIPTION
**Pull request by bspeare**
- Updated `better_exposed_filters` to `6.0.3` which updated `jquery_ui`, `jquery_ui_datepicker` `jquery_ui_slider`
- Updated `entity_print` to `8.x-2.13`
- Updated `field_delimiter` to `2.0.dev`
- Updated `fragments` to `2.1.0-rc1`
- Updated `google_analytics` to `4.0.2`
- Updated `layout_builder_shortcuts` to `1.0.2` - SAH
- Updated `lazy` to `3.12.0`
- Updated `node_view_permissions` to `8.x-1.6`
- Updated `override_node_options` to `2.7.0`
- Updated `paragraphs` to `8.x-1.16`
- Updated `responsive_table_filter` to `2.0.1`
- Updated `robotstxt` to `8.x-1.5`
- Updated `superfish` to `1.6`
- Updated `theme_permission` to `dev-2.0.x#c924836` and added patch for D10 compatibility - SAH
- Updated `tvi` to `2.0.0-alpha2`

## How to test
```
ddev composer install
```
- Sync sandbox site to test fragments in the region config page.

### Entity print
```
ddev blt ds --site=admissions.uiowa.edu && ddev drush @admissions.local uli /areas-of-study/print-links
```
- Test pdf generation at the print-links page
- Test mail code: adjust mail code on [node](https://admissions.uiowa.ddev.site/node/2696/edit) and then go to https://admissions.uiowa.ddev.site/print/pdf/node/2696 and "Save As" and the file name should match the mail code field. 

### TVI
```
ddev blt ds --site=admissions.uiowa.edu && ddev drush @admissions.local uli /admin/structure/taxonomy/manage/academic_groups
```

### CODE REVIEW

**Comment by pyrello** [comment]
Fixing conflicts.

**Comment by e-marie-w** [comment]
Getting following error when trying to sync sites:

> Failed to log error: AssertionError: The file specified by the given app root, relative path and file name (/var/www/html/docroot/modules/contrib/components/components.info.yml) do not exist. in assert() (line 68 of /var/www/html/docroot/core/lib/Drupal/Core/Extension/Extension.php). #0 /var/www/html/docroot/core/lib/Drupal/Core/Extension/Extension.php(68): assert(false, 'The file specif...')

Update: restoring the Components module just leads to new different error:

>  [error]  ArgumentCountError: Too few arguments to function Drupal\devel\DevelDumperManager::__construct(), 3 passed in /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 and exactly 4 expected in Drupal\devel\DevelDumperManager->__construct() (line 65 of /var/www/html/docroot/modules/contrib/devel/src/DevelDumperManager.php) #0 /var/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drupal\devel\DevelDumperManager->__construct(Object(Drupal\Core\Config\ConfigFactory), Object(Drupal\Core\Session\AccountProxy), Object(Drupal\devel\DevelDumperPluginManager))

I'm going to try cleaning up my local and possibly restarting in case it's just me. 

Update 2: It was me, local `sql-drop` fixed it.

**Comment by e-marie-w** [comment]
I found a small difference with local vs prod pdf generation for Admissions: Dashes are now being added when `&nbsp;` is used. In the Accounting pdf, you can see this at the end of each paragraph under Careers and Outcomes. It also happens within sentences, such as the start of the second paragraph under Student Opportunities (`Business students at Iowa are-very involved...`). 

Mail code is working as expected on site.

**Comment by pyrello** [comment]
> Getting following error when trying to sync sites

I'm able to sync without issues, so I'm going to assume this was gremlins related to `components` being uninstalled in yesterday's deployment and removed in this PR and caching at some layer.

**Comment by pyrello** [comment]
I'm seeing the issue that @e-marie-w indicated in https://github.com/uiowa/uiowa/pull/6952#issuecomment-1745325834. Unless someone has a specific idea about how to fix this, I think we should split the `entity_print` module update into a separate PR so that it doesn't slow down the process of merging this.

**Comment by pyrello** [comment]
> I'm seeing the issue that @e-marie-w indicated in https://github.com/uiowa/uiowa/pull/6952#issuecomment-1745325834. Unless someone has a specific idea about how to fix this, I think we should split the entity_print module update into a separate PR so that it doesn't slow down the process of merging this.

It looks like this can be worked around by just replacing the `&nbsp;` with an actual space. Since these are printed by someone at Admissions, they could spot check and fix any issues before printing them.

Do we want to prioritize figuring out the underlying issue?

**Comment by bspeare** [comment]
I have a fix coming for `&nbsp;`, we can just strip that out in the template ~or preprocess~.

**Comment by e-marie-w** [comment]
The fix worked! I can approve once it's marked as ready for review, TVI and fragments both worked as expected. Code changes made sense too, nothing looked out of place.

**Comment by pyrello** [comment]
> I have a fix coming for `&nbsp;`, we can just strip that out in the template ~or preprocess~.

I'd call this more of a workaround than a fix, personally. It looks like this is a known upstream issue: https://github.com/dompdf/dompdf/issues/2292

**Review by e-marie-w — APPROVED** [review]

**Comment by bspeare** [comment]
Nice find @pyrello.  Everything with the pdf is a workaround.

**Comment by GaryRidgway** [comment]
is this workaround okay for now or should we wait?

**Comment by pyrello** [comment]
> is this workaround okay for now or should we wait?

This is fine for now.

**Pull request merged**
