### PR TITLE
Updates to vwu migration

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #2792 

# How to test
Need a local copy of writinguniversity.org in Dev Desktop.
Pull the `vwu` multisite from the Graduate College Acquia Cloud docroot.
Leave the DD Apache/MySQL stack running.

`git checkout writinguniversity-migrate` and `git pull`
`blt ds --site=writinguniversity.org`
`drush @org-writinguniversity.local en writinguniversity_migrate`
`drush @org-writinguniversity.local mim d7_writinguniversity_blog`

Watch that no `array_flip()` warnings appear in the log.

Checkout out the database, and that there no Missing Image tokens were added during migration.
`drush @org-writinguniversity.local sqlc`
`select sourceid1, destid1 from migrate_map_d7_writinguniversity_blog where destid1 in (select entity_id from node__body where body_value like "%<!--Miss%");` will give you the source and destination node IDs for any nodes that have a missing image as result of the migration (or empty set if all went well).

# Note

This PR contains the module/config to run the migration for #2792, but the actual migration and pushing db/files up will need to be run separately, and will still be pending following merge.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
```
drush @org-writinguniversity.local mim d7_writinguniversity_blog
  16/544 [>---------------------------]   2% [warning] A non-numeric value encountered PelIfd.php:611
 504/544 [=========================>--]  92% [error]  Invalid marker found at offset 0: 0x89 
 [notice] Processed 542 items (542 created, 0 updated, 0 failed, 0 ignored) - done with 'd7_writinguniversity_blog'
```
no array flip but it didn't finish like before

**Comment by cory-skeers** [comment]
Looking into the 542/544 discrepancy...

**Comment by cory-skeers** [comment]
542/544 discrepancy looks to have been multiple URL aliases associated with a node(s). Moved it into a separate method in the `BaseNodeSource` where it can pull multiple without issue.

Both the PelIfd and invalid marker warning/error should be able to be safely ignored as potentially nice-to-haves file cleanup in the future, but as not preventing migrations from taking place or causing any data loss.

**Comment by joewhitsitt** [comment]
running the migration again locally

```
drush @org-writinguniversity.local mim d7_writinguniversity_blog
  16/542 [>---------------------------]   2% [warning] A non-numeric value encountered PelIfd.php:611
 504/542 [==========================>-]  92% [error]  Invalid marker found at offset 0: 0x89 
 [notice] Processed 542 items (542 created, 0 updated, 0 failed, 0 ignored) - done with 'd7_writinguniversity_blog'
```

**Review by joewhitsitt — APPROVED** [review]
couldn't get the sqlc to work so i just checked all body values in node via sequel pro.

**Pull request merged**
