### PR TITLE
Started rabbit hole work

### LINKED ISSUE #4446: AoS Feature - Consider Rabbit Hole node redirect for unauthenticated when linked directly to source (pre-save).
https://iowaweb.slack.com/archives/C0164FNN1PV/p1636558112346600

## Proposed Solution

- [x] Enable rabbit hole node (already a composer dependency. HR is using for taxonomy) and configure for AoS content type with display node set as default with per node override set. Make sure all of this is captured in the AoS split.
- [x] On pre-save, if source link and direct to source are set, change the rabbit hole setting to redirect and set the url to the source link. Establish module specific to the split to handle this.
- [x] Make sure these rabbit hole settings are hidden to webmasters and below.
- [x] Update config on sites that use AoS split if necessary (education, desmoines?)

### PR DESCRIPTION
**Pull request by dnkemper**
Closes #4446 
# How to test

1. blt ds --site=sandbox.uiowa.edu
2. enable area of study split
3. drush @sandbox.local cim
4. drush @sandbox.local cr
5. add an area of study - add a primary source link. If check 'link directly to source' the rabbit hole settings should change - redirect radio should be selected. If uncheck it, the 'display page' rabbit hole radio should be selected

# Stories

- As a site visitor I am redirected when a more suitable destination is configured.
- As an editor/webmaster I can set a primary source link (internal or external) and set link directly to source to have visitors redirected from the view page or by navigating directly to the node.
- As an editor/webmaster I can still edit the area of study node and not be redirected. I also see a message that visitors are being redirect.

### CODE REVIEW

**Comment by dnkemper** [comment]
Going to take a look at this again. Trying to find the best way to programmatically check a radio button.

**Comment by joewhitsitt** [comment]
taking a look

**Comment by dnkemper** [comment]
thank you, @joewhitsitt!

**Comment by joewhitsitt** [comment]
i tested on education which has the split already enabled. i think this is reviewable

**Comment by joewhitsitt** [comment]
Overnight thoughts: Teaser logic could probably be removed since node has rabbit redirect. Drupal messenger status message on node display to "bypass" permission users saying visitors are being redirected.

**Comment by dnkemper** [comment]
> Overnight thoughts: Teaser logic could probably be removed since node has rabbit redirect. Drupal messenger status message on node display to "bypass" permission users saying visitors are being redirected.

errrr.... okay so I'm trying to decipher this... teaser logic to be removed = in the template file, correct? Then what exactly needs to be done for the second sentence? Sawwy. ~Slightly~ Incredibly confused

**Comment by joewhitsitt** [comment]
Sorry, i was out and typed this comment on my way out of town.

`\Drupal::messenger()->addWarning(t('message goes here'));` in a preprocess node of the AoS full/default node view mode because editors will see the page without being redirect and might wonder why it is different. they don't see the rabbit hole settings on the form.

**Comment by joewhitsitt** [comment]
going to add the message on the full node to this

**Comment by bspeare** [comment]
Testing this

**Comment by bspeare** [comment]
@joewhitsitt is this message only meant to be seen by admins?

Screen Shot 2022-02-11 at 3 54 37 PM

**Comment by joewhitsitt** [comment]
It is supposed to be seen only by those not being redirected (anonymous visitors). Did I miss an access check. If source link and direct link is set, anonymous visitors should be redirected an not see that.

**Comment by bspeare** [comment]
I masqueraded as editor and webmaster and both redirected me to the source link when I tried viewing the page.

**Comment by joewhitsitt** [comment]
ah it looks like the `rabbit hole bypass...` permission weren't added to this pr.. i will convert back to draft and fix that.

**Comment by joewhitsitt** [comment]
Added some stories to describe the ideal behavior between visitors and site editors

**Review by bspeare — APPROVED** [review]
The permissions update and the testing instructions worked.  I imagine things could get pretty confusing if someone adds a redirect by mistake but I imagine that is an edge case.

Screen Shot 2022-02-11 at 4 30 34 PM

Displaying the Rabbit Hole settings might help explain things further or potentially confuse. 


Screen Shot 2022-02-11 at 4 32 12 PM

**Comment by bspeare** [comment]
@joewhitsitt Did we intend to display the Rabbit hole settings on the edit page or is that help text just there for admins?

**Comment by joewhitsitt** [comment]
>I imagine things could get pretty confusing if someone adds a redirect by mistake but I imagine that is an edge case.

I hope it stays an edge case. Untested but my hope is that one redirect will take first and that rabbit hole/core already account for infinite redirect loops.

Webmasters and below shouldn't see the rabbit hole functionality so the disabled fieldset is just for Admins.

**Comment by joewhitsitt** [comment]
Wondering if we should notify Education and Distance about this change.

@mjoneill thoughts? If I recall this Area of Study redirect request originally came through you: https://github.com/uiowa/uiowa/issues/4446

**Comment by mjoneill** [comment]
> Wondering if we should notify Education and Distance about this change.
> 
> @mjoneill thoughts? If I recall this Area of Study redirect request originally came through you: #4446

Nice.  Probably would be good to reach out.  Before we do, can I get a brief demo on Mon (after daily scrum)?

**Comment by joewhitsitt** [comment]
Working on an update hook to re-save specific AoS nodes so this takes effect right away.

**Comment by joewhitsitt** [comment]
Would be good to get someone to look at this again.

Make sure the update hook runs and that existing AoS nodes are redirected right away. (e.g. education https://education.uiowa.ddev.site/areas-of-study/certificate-college-teaching should be directed to https://education.uiowa.ddev.site/areas-study/continuing-education/certificates-and-endorsements/certificate-college-teaching)

**Comment by bspeare** [comment]
I can check this again.

**Comment by bspeare** [comment]
Tested on education and the update hook runs and the rabbit hole functionality is working.

**Comment by joewhitsitt** [comment]
Thanks for the third look @bspeare !

**Comment by joewhitsitt** [comment]
Email sent to affected customers.

**Comment by dnkemper** [comment]
Nice work, @Whitsitt, Joe ***@***.***>
________________________________
From: Joe Whitsitt ***@***.***>
Sent: Monday, February 14, 2022 2:05:13 PM
To: uiowa/uiowa ***@***.***>
Cc: Wisnousky, Danielle N ***@***.***>; Review requested ***@***.***>
Subject: [External] Re: [uiowa/uiowa] Started rabbit hole work (PR #4742)


Merged #4742<https://github.com/uiowa/uiowa/pull/4742> into main.

**Pull request merged**
