### PR TITLE
[Bug fix] Added fix for off-canvas alerts

### LINKED ISSUE #6979: Unreadable error
# Problem
when getting an error in the off canvas menu for layout builder, the new alerts do not display correctly, and make the error messages unreadable.

<details><summary>Details</summary>

</details> 

# Steps to reproduce
1. Enter something incorrectly in a field in an off canvas menu.
2. Try to submit content changes to the block.
3. O B S E R V E

# Proposed solution
Add some styles to the alerts for the off canvas stuff.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6979

# How to test
```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli /
```
1. Edit the slider and remove the headline from each slider and try to save the block
2. Confirm that alert message is readable and looks like the screenshots below

Screenshot 2023-10-09 at 9 56 32 AM
Screenshot 2023-10-09 at 9 56 23 AM

### CODE REVIEW

**Comment by pyrello** [comment]
Given how little space there is, I'm wondering if we should make the fields with an error a comma-separated list instead of separate lines?

**Comment by bspeare** [comment]
@pyrello that's a good suggestion.  It now looks like this:

Screenshot 2023-10-09 at 10 48 48 AM



However, I'm not sure much can be done with this type of error - is there?

Screenshot 2023-10-09 at 10 54 14 AM

**Comment by pyrello** [comment]
> However, I'm not sure much can be done with this type of error - is there?

I'm not totally clear on what's going on with that error message. Is it two separate error messages?

**Comment by bspeare** [comment]
Yes, I think that's two error messages.

**Comment by joewhitsitt** [comment]
Taking a look at this

**Comment by joewhitsitt** [comment]
I was able to scope the styles a bit, but if there is a null headline plus more than one other issues, then the items aren't linked and don't get the comma.
Screenshot 2023-10-10 at 12 34 49 PM
Screenshot 2023-10-10 at 12 33 28 PM
Screenshot 2023-10-10 at 12 33 56 PM

**Comment by joewhitsitt** [comment]
As a reviewer with the PR scoped to just solve the contrast bug, this looks good. If someone signs off on my tweak, I think we can merge this.

https://github.com/uiowa/uiowa/pull/6980/commits/7941111812cf97ef123b06e557eb9db8ce77d3fd

**Review by joewhitsitt — APPROVED** [review]

**Comment by joewhitsitt** [comment]
At EoD, we wondered if https://github.com/uiowa/uiowa/commit/7941111812cf97ef123b06e557eb9db8ce77d3fd#comments was a blocker

**Pull request merged**
