### PR TITLE
Graduate Admissions Migrate

### LINKED ISSUE #4638: Migrate Grad Admissions AOS and related content
see also moves from content type to taxonomy. links within need to redirect

We'll want to remove any testing content prior to running migration(s).

- [x] Manually migrate Estimated Costs
  - [x] Set up redirects from the old cost estimate paths to the new
- [x] Programmatically migrate colleges taxonomy
- [x] Programmatically migrate Degree types taxonomy
- [x] Programmatically migrate Areas of Study taxonomy
- [x] Programmatically migrate Areas of Study content (sans "See also" and "Sub title" field)
- [x] Dry run with broken links report sent to customer for corrections map
- [x] Broken links map migration
- [x] Run in DEV for technical and customer review

## Broken Links Report
[gradadmissions-broken-links.txt](https://github.com/uiowa/uiowa/files/7945458/gradadmissions-broken-links.txt)

## Estimated Costs Map
<details>
<summary>

_php_
...

</summary>
<description>

```php
  $map = [
    // source_nid => target_nid,
    // MAc. mac-program-estimated-costs.
    121 => 211,
    // MD. md-program-estimated-costs.
    112 => 246,
    // JD. jd-program-estimated-costs.
    415 => 256,
    // SJD. sjd-program-estimated-costs.
    111 => 266,
    // LLM. llm-program-estimated-costs.
    421 => 276,
    // MSL. master-studies-law-msl-program-estimated-costs.
    583 => 286,
    // PharmD. pharmd-program-estimated-costs.
    116 => 296,
    // DNP. doctor-nursing-practice-dnp-program-estimated-costs.
    113 => 306,
    // DPT. dpt-program-estimated-costs.
    131 => 316,
    // MPH. master-public-health-program-estimated-costs.
    118 => 326,
    // Public health (not MPH). graduate-programs-public-health-estimated-costs.
    103 => 336,
    // Sustainable Water Development. sustainable-water-development-certificate-estimated-costs.
    931 => 346,
    // Oral Science Program. oral-science-program-estimated-costs.
    115 => 356,
    // Applied Math & Computational Sciences. applied-math-computational-sciences-estimated-costs.
    105 => 366,
    // LIS. library-information-science-estimated-costs.
    109 => 376,
    // Second Language Acquisition. second-language-acquisition-estimated-costs.
    119 => 386,
    // Grad Programs in Pharmacy. graduate-programs-pharmacy-estimated-costs.
    117 => 396,
    // Informatics. informatics-estimated-costs.
    412 => 406,
    // Dental Public Health. dental-public-health-estimated-costs.
    106 => 416,
    // Urban & Regional Planning. urban-regional-planning-estimated-costs.
    120 => 426,
    // Endodontics. certificate-program-endodontics-estimated-costs.
    132 => 436,
    // DDS. doctor-dental-surgery-dds-program-estimated-costs.
    107 => 446,
    // Speech Pathology & Audiology. speech-pathology-and-audiology-ma-or-aud-estimated-costs.
    417 => 456,
    // Health Administration. health-administration-program-estimated-costs.
    108 => 466,
    // Business (PhD). phd-programs-business-estimated-costs.
    96 => 476,
    // Education. education-estimated-costs.
    101 => 486,
    // Liberal Arts & Sciences. graduate-programs-liberal-arts-sciences-costs.
    99 => 496,
    // Engineering. engineering-estimated-costs.
    102 => 506,
    // Nursing (PhD). phd-program-nursing-estimated-costs.
    133 => 516,
    // Nursing (MSN). msn-cnl-program-estimated-costs.
    114 => 526,
    // Medicine (non-MD). ms-phd-mme-mca-and-mpa-programs-medicine-estimated-costs.
    100 => 536,
    // Business (MBA). full-time-mba-program-estimated-costs.
    110 => 546,
  ];
```

</description>
</details>

### LINKED ISSUE #4740: Update Featured Image for Grad Admissions AoS
Admissions requested we update the default featured image for Areas of Study. The request was to use the same image that the undergrad admissions site is using.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves https://github.com/uiowa/uiowa/issues/4638
Resolves #4740 

## To Test
get admissions_grad in the Grad docroot pulled and resolving in DevDesktop
blt ds --site grad.admissions.uiowa.edu
drush @admissionsgrad.local en grad_admissions_migrate
drush @admissionsgrad.local uli admin/config/sitenow/sitenow-migrate
Enter details for migration using DevDesktop settings indicated in help text. Database name is 'admissions_grad'.
**delete existing [AoS content](https://admissionsgrad.uiowa.ddev.site/admin/content?type=area_of_study), [Aos taxonomy](https://admissionsgrad.uiowa.ddev.site/admin/structure/taxonomy/manage/grad_areas_of_study/overview), [Colleges taxonomy](https://admissionsgrad.uiowa.ddev.site/admin/structure/taxonomy/manage/colleges/overview), [Degree types taxonomy](https://admissionsgrad.uiowa.ddev.site/admin/structure/taxonomy/manage/degree_types/overview) data**
drush @admissionsgrad.local ms to see migration information
drush @admissionsgrad.local mim --all to run all migrations

- there will be broken links output as part of this. we are waiting for a map of replacements from Admissions.
- check pieces of content for alignment and accuracy
- colleges taxonomy should combine description and program info from the old site.
- estimated costs should map up to replacement domestic version
- department and catalog links should be combined into related links

### CODE REVIEW

**Comment by joewhitsitt** [comment]
This is ready for technical review until we have replacements for the broken links.

**Comment by richardbporter** [comment]
Looking good. I'll take a closer look once the map is in place.

**Comment by GaryRidgway** [comment]
I am going to try and review this

**Comment by joewhitsitt** [comment]
This is now in DEV for spot checking https://admissionsgrad.dev.drupal.uiowa.edu/areas-of-study

**Review by richardbporter — APPROVED** [review]
I'm not seeing anything amiss here. Did we plan to kick it over to the client for final approval? I re-ran just the AoS migration to get the images: https://admissionsgrad.dev.drupal.uiowa.edu/academics/acting-mfa-theatre-arts

**Comment by briand44** [comment]
>Did we plan to kick it over to the client for final approval?
 
@joewhitsitt ran this in dev during the admissions meeting and let them know it was there for their review. Thanks for adding the image in!

**Pull request merged**
