### PR TITLE
Update UIDS and implement component changes to fix card/banner contextual link issue.

### LINKED ISSUE #2277: Anchor links in linked cards/banners go to the card/banner link instead of anchor
## Problem

While testing the banner refactor https://github.com/uiowa/uiowa/pull/2075, I noticed that an anchor link in one of these linked clickable component ultimately send the user to the card/banner link, not the anchor.

## Proposed Solution

Adjust `card.js` to allow anchor links in Excerpt area.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #2277

# How to test

```
rm -rf ./node_modules
yarn cache clean
yarn install
yarn workspace uids_base gulp --development
```
Test on 

- https://sandbox.prod.drupal.uiowa.edu/cards
- https://sandbox.prod.drupal.uiowa.edu/banners-and-buttons
- Verify that `click-container` appears on wrapping div of `card` and `banners`.
- If `card` and `banners` have one link, verify that link class of `click-target` appears on heading `<a>`.
- Verify that you can edit card media when logged in and on card page. 
- Verify that pause and link work on https://sandbox.local.drupal.uiowa.edu/ banner video loop.

### CODE REVIEW

**Comment by richardbporter** [comment]
Is this ready for review/approval?

**Comment by bspeare** [comment]
@richardbporter I think so, just added some more detailed instructions.

**Comment by richardbporter** [comment]
We'll need to change the uids hash to a release before merging, right?

**Comment by bspeare** [comment]
@richardbporter no, we are working off the hash lately.

**Review by richardbporter — APPROVED** [review]

**Comment by richardbporter** [comment]
Does this resolve https://github.com/uiowa/uiowa/issues/2277?

**Comment by richardbporter** [comment]
> Does this resolve #2277?

Seems like it does based on my testing.

**Comment by pyrello** [comment]
@richardbporter It should, since we are not trapping any clicks on `<a>` elements and letting the default behavior flow.

**Pull request merged**
