### PR TITLE
Narrow article feature 

### LINKED ISSUE #6128: Implement a narrow article feature for the law journal sites
# Story

As a Law Journal website owner, I would like to see our articles in a narrow container to increase readability for users.

# Additional Info

- The slice of turning on the narrow container for Law Journals and possibly Writing University should implement a feature split since there are multiple sites. (ilr.law.uiowa.edu, jgrj.law.uiowa.edu, writinguniversity.org)
- Include header area in scope of this based on mockups in https://github.com/uiowa/uiowa/issues/2784#issuecomment-1371369369.
- Need to account for css differences in this feature, possibly preprocess similar to other examples.
- We'll likely want to turn this on in a non-production environment and get approval before turning this on in prod.
- If we learn this is way too big once we get into it, lets discuss.

Epic https://github.com/uiowa/uiowa/issues/2784 

# Proposed solution

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6128. 

# How to test 
```
ddev blt frontend && ddev blt ds --site=ilr.law.uiowa.edu && ddev drush @lawilr.local config-split:activate articles_narrow -y && ddev drush @lawilr.local uli
```

`ddev blt frontend`
`ddev blt ds --site=ilr.law.uiowa.edu`
`ddev drush @lawilr.local config-split:activate articles_narrow`
`ddev drush @lawilr.local uli`

- Code review
  - Test show/hide functionality of image block and broken links block.  I had to rewrite that code to get it to work with an additional layout.
- User story "As a Law Journal website owner, I would like to see our articles in a narrow container to increase readability for users."
- Verify that law articles are rendering with 67/33 sidebar.  All meta info should be in sidebar (screenshots below in details).
- Sync the sandbox site and verify that articles remain the same. 
- Test articles list, featured content list, /news list and verify that I didn't mess up the styling there. 
- Test mobile/desktop all breakpoints.

<details>

Screenshot 2023-02-13 at 9 16 46 AM
Screenshot 2023-02-13 at 9 16 04 AM

</details>

### CODE REVIEW

**Comment by makurj** [comment]
Not a biggie...Would we want to decrease the spacing between the meta data for smaller viewports? It seems like they are taking up too much screen real estate:

image

**Comment by bspeare** [comment]
@makurj That's a good point but we would probably want to create a follow-up issue to address that because it is related to https://github.com/uiowa/uiowa/issues/4917 or https://github.com/uiowa/uiowa/issues/4906.

**Comment by makurj** [comment]
Also, noticed that at smaller breakpoints, some text is overflowing for the 3-column grid which, I'm guessing, will be addressed by https://github.com/uiowa/uiowa/issues/4678

image

**Comment by bspeare** [comment]
@makurj Is that an existing page?  What setup are you using there?

**Comment by makurj** [comment]
> @makurj Is that an existing page? What setup are you using there?

Nope, created a new one to place the articles list block on. One column section with normal container and:
image

Also added some images to articles to test.

**Comment by bspeare** [comment]
@makurj Yes, that is most likely not related to this pr.  But probably worth creating a bug issue for and linking it to that other issue.

**Comment by makurj** [comment]
For reference: https://github.com/uiowa/uiowa/issues/6182

**Comment by makurj** [comment]
> @makurj That's a good point but we would probably want to create a follow-up issue to address that because it is related to #4917 or #4906.

https://github.com/uiowa/uiowa/issues/6183

**Comment by cory-skeers** [comment]
Did a code review on this, and things are looking good! I like the new helper function for unsetting blocks. 

Once I get my local back to normal, I wanted to pull it down and check things out too, but otherwise with that and the follow-up issues, I think this is probably ready to go.

**Review by cory-skeers — APPROVED** [review]
Reviewed and tested, and looks great!

**Comment by bspeare** [comment]
I added the subhead field to this layout if someone wants to pull this down and verify that the field is working or review the latest commit.

**Comment by makurj** [comment]
Pulling down to test subhead.

**Comment by makurj** [comment]
Looking good on both new and existing articles (if entered):

image

**Comment by makurj** [comment]
Looking good on both new and existing articles (if entered):

image
image

**Comment by makurj** [comment]
Sandbox:
image

**Comment by bspeare** [comment]
Thanks @makurj and @cory-skeers!

**Pull request merged**
