### PR TITLE
Feature: Obermann articles migration

### LINKED ISSUE #3697: Migrate obermann articles
> For instance, our current website has lots of news articles (using the “article” content type). We’d love if those could be moved over to SiteNow as individual articles. I know we’d have to manually tag them if we wanted to filter and display them, but the more important thing is that they all get moved over, so that they’re accessible and searchable on the new site. Each of our current article nodes use the Title field, the featured image, the body, and one or more “Featured Program” tags, along with the date of publication. The SiteNow article content type has those same fields—so maybe all of that content could be moved over (except for maybe the tagged programs)?

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/3697. 

### Setup
Sync obermann.uiowa.edu D7 site in DevDesktop.

Sync obermann.uiowa.edu D9 site.
```
blt sync --site obermann.uiowa.edu &&
drush @obermann.local en obermann_migrate --yes &&
drush @obermann.local uli /admin/config/system/sitenow-migrate
```

Fill out form for DD.

`drush @obermann.local ms`
`drush @obermann.local mim --all`

### Stories
- As an obermann.uiowa.edu site owner, I can see articles created before 9/9/2020 in the new site and none created after that except the ones I created manually.
- As an obermann.uiowa.edu site owner, I can see those migrated articles have references to tags with the same name as a featured program if such a reference existed on the D7 site.
- As an obermann.uiowa.edu site owner, I can be provided a list of broken links in migrated articles so that I can fix them.
- As an obermann.uiowa.edu site visitor, I can get redirected to the new location of a migrated article in case I have it bookmarked.

### CODE REVIEW

**Comment by richardbporter** [comment]
I think 4d6e6ca fixes the date issue and gets `drush @obermann.local mim --all` working.

I think I have the terms mapping based on a name lookup using the source database. We should identify some source articles that are tagged and verify the destination has the same tags. That assumes the tag exists in the new site and not many do.

I renamed the split as part of this - that may bork you local environment. Sorry. :)

There are some log messages available with verbose logging on: `drush @obermann.local mim --all -v`.

**Comment by richardbporter** [comment]
Seeing lots of these warnings in the migration:
```
[warning] Query failed for program lookup: 18
[warning] Query failed for program lookup: 402
[warning] Query failed for program lookup: 560
[warning] Query failed for program lookup: 530
```

Seems like these nodes don't exist in the source. Examples:
https://obermann.uiowa.edu/node/18
https://obermann.uiowa.edu/node/402
https://obermann.uiowa.edu/node/560
https://obermann.uiowa.edu/node/530

I'm assuming these are broken references in the D7 site.

**Comment by richardbporter** [comment]
Assuming those non-existent references can just be skipped, I think I'm done with this. We just need to outline setup and testing/stories.

**Comment by richardbporter** [comment]
I wrote up some testing instructions and stories. Just noticed this from #3912: 

>provide list of articles with internal links that will likely be broken

I did not see any log messages related to this. Maybe that isn't working?

**Comment by richardbporter** [comment]
Yea - seeing some hrefs like `/programs/working-groups` which will be broken but we're not catching those.

**Comment by cory-skeers** [comment]
> I did not see any log messages related to this. Maybe that isn't working?

Check it now--some of that got moved into a function of the linkReplaceTrait so it can be called from the completion of a migration instead of reporting throughout.

**Comment by richardbporter** [comment]
Nice! Yea I forgot how that worked. I was looking at our internal link replace code... 🤦🏻

**Comment by richardbporter** [comment]
```
[notice] Possible broken links found in node 3523: A conference report
 [notice] Possible broken links found in node 3570:  2017 “Data Science for the Social Good” camp,check out Rebelsky’s article in the ,Grinnell Herald-Register
 [notice] Processed 237 items (237 created, 0 updated, 0 failed, 0 ignored) - done with 'obermann_articles'
 [notice] Possible broken links found in node 3523: A conference report
 [notice] Possible broken links found in node 3570:  2017 “Data Science for the Social Good” camp,check out Rebelsky’s article in the ,Grinnell Herald-Register
 [notice] Possible broken links found in node 3523: A conference report
 [notice] Possible broken links found in node 3570:  2017 “Data Science for the Social Good” camp,check out Rebelsky’s article in the ,Grinnell Herald-Register
```

**Comment by richardbporter** [comment]
Something isn't right:

image

**Comment by joewhitsitt** [comment]
did you migrate devel generate?

**Comment by richardbporter** [comment]
These are not present after importing obermann_articles. They appear after importing obermann_articles_redirects.

I noticed the counts are different between the two migrations. We added a query condition to exclude articles created after 2020 that the new sitenow_alias_redirect source isn't taking into account. I think we're getting too many redirects imported. No clue why its creating this bogus content...

**Comment by richardbporter** [comment]
f9e85dd seems to fix this but I'm not sure why those nodes were created in the first place. Maybe the redirect destination doesn't exist and it's being auto-generated somehow?

Regardless, I think we want to use our custom source plugin instead of the generic redirect source to account for our reduced source data.

**Comment by richardbporter** [comment]
The bogus nodes all have August dates but I'm not seeing a corresponding redirect destination. Some of the URL aliases look odd too: 

image

I check the source DB and these nodes don't exist. They get a random name each time after rolling back and re-importing. I think this PR can move forward without fixing this issue but I'd be wary of using sitenow_alias_redirect for other migrations.

**Comment by richardbporter** [comment]
Getting memory failures processing media but re-running seems to work.

**Review by richardbporter — APPROVED** [review]
All the stories seem to check out. 👍🏻

**Pull request merged**
