### PR TITLE
Create sitenow update to cc all and change engineering media title/alt fields.

### LINKED ISSUE #3870: Engineering media metadata
# Story

As a content editor for engineering.uiowa.edu, I would like my previously migrated media content to have its D7 metadata and/or other unique metadata so that I can easily find my content, and have accessible alt text readily available for site visitors.

# Proposed solution

Check that affected media is easily findable in the D8 database by either null values in title/alt or default values ("title" and "alt"). Find a way to update these entries using the D7 database (likely by matching filenames), or at least update the titles to something reasonable like filename minus extension.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3870

I'm not sure how to connect to the D7 database to make this better. If someone has an idea of how to do that, I think this could be closed in favor of that approach as it'd probably have better alt/title fields.

While syncing this site, I got a fatal error related to #3745 so I included a cc all in the update hook.

### Setup
```
blt sync --site engineering.uiowa.edu
```

### Stories
- As an engineering site content creator, I can browse and search media by name.
- As an engineering site content creator, I can embed images with decent alt text.

### CODE REVIEW

**Review by dnkemper — APPROVED** [review]
Can't think of an alternative way at the moment... works as should though and will approve it - understand if you want someone else to look at this though

**Comment by richardbporter** [comment]
Thanks. I'd be looking at @cory-skeers as that someone else. ;)

**Comment by cory-skeers** [comment]
> Thanks. I'd be looking at @cory-skeers as that someone else. ;)

I'll take a look!

**Comment by cory-skeers** [comment]
At least at first pass trying to track down original file data, the small handful of example images I used didn't have any alt or title information on the D7 site. With that and that there are at least some that migrated with full title/alt, I'm inclined to think this was a lack of info in the original site combined with a failure of failsafe to give unique media titles. 

I'd still like to look a little further to check that that hunch is correct, but if it is, this is likely the best we can offer and would match what the D7 site had in place.

**Comment by cory-skeers** [comment]
I went through some more examples, and still haven't found a situation where there was a title and/or alt that was missed, where there's anything more we could do than what's in this PR.

So we should still look at #3865, but for engineering I think this is the best approach.

**Pull request merged**
