### PR TITLE
Added position:relative to form-textarea-wrapper class

### LINKED ISSUE #7300: CKEditor buttons hiding Add Block button
# Problem
Sometimes when I'm editing a block and scroll down, the editor fields will appear and block the button to Add Block.

Browser: Firefox

https://github.com/uiowa/uiowa/assets/731952/483108a7-2848-497e-9ddb-160186d37861

### PR DESCRIPTION
**Pull request by quamsta**
Resolves: https://github.com/uiowa/uiowa/issues/7300

Edit: Somehow my branch name that I created when I forked the repo didn't come through, sorry about that.

# How to test

1. Clone this branch
2. Build frontend assets
3. Note that Text Area block's CKEditor toolbar doesn't "stick" to the bottom of the Off-Canvas Panel any longer.

### CODE REVIEW

**Comment by bspeare** [comment]
Tested this and it works, but I have a question here https://github.com/uiowa/uiowa/issues/7300#issuecomment-1984397110.

**Review by joewhitsitt — APPROVED** [review]
I don't feel comfortable creating a d.o issue I am having troubles reproducing consistently. This seems like a small-footprint fix to an irritating problem. It is commented so that we can revisit if there is an upstream fix/change.

**Comment by joewhitsitt** [comment]
For visibility, this PR was "stuck" with travis. Temporarily removed protections to merge.

**Comment by quamsta** [comment]
Thanks @joewhitsitt ! I tried to recreate the issue on simplytest in a bunch of different combinations of text fields and other cases and couldn't reproduce it at all. It's strange.

**Pull request merged**
