### PR TITLE
[Bug] UIowa Hours fix

### LINKED ISSUE #7194: recserv hours not showing on homepage
Got a report hours were not showing on https://recserv.uiowa.edu. They added a message to direct users to their hours page where they were showing correctly https://recserv.uiowa.edu/hours. 

I disabled js aggregation as a temporary workaround and hours started showing again on the homepage.

Creating this to address the problem so we that we can turn on js aggregation again in the future.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/7194. 

# How to test

1. Change line 63 of local.settings.php for recserv.uiowa.edu to `$config['system.performance']['js']['preprocess'] = TRUE;`
2. Confirm logged-in home page hours block and https://recserv.uiowa.ddev.site/hours works
2. Confirm anonymous https://recserv.uiowa.ddev.site/hours and front page home page hours block works

```
ddev blt ds --site=recserv.uiowa.edu && ddev drush @recserv.local uli /
```

### CODE REVIEW

**Comment by briand44** [comment]
@bspeare can we confirm https://recserv.uiowa.edu/hours works as well while testing this? There weren't issues previously with this page but since it is same/similar functionality, it would probably be good to verify this page continues to function properly as well.

**Comment by bspeare** [comment]
@briand44 added it to the testing steps!

**Comment by pyrello** [comment]
Did we get rid of JS for the stat component?

**Comment by bspeare** [comment]
@pyrello Apparently there never was JS for that component.  The file certainly could be removed in UIDS if someone wants to do that.

**Comment by pyrello** [comment]
Pulling to test

**Review by pyrello — APPROVED** [review]
Looks good.

**Pull request merged**
