### PR TITLE
update media_thumbnails_video

### PR DESCRIPTION
**Pull request by joewhitsitt**
Relates to https://github.com/uiowa/uiowa/issues/6381
If you upload a video for a banner, does it create a still image for paused by default banners?

Just some PHP and Drupal compatibility fixes. One of which we were pinned at.
https://git.drupalcode.org/project/media_thumbnails_video/-/compare/8.x-1.0-alpha2...2.0.0?from_project_id=62163&straight=false

# To Test

- `ddev composer install`
- Sync a v3 site. Add a banner to layout. For the media upload/select a video file. Set autoplay to false.
- On render an image from the first second should display.

Test video (right-click save-as..)
https://github.com/uiowa/uiowa/assets/4663676/e6382cd6-9f8e-444b-a664-c8c027b38f9c

### CODE REVIEW

**Comment by bspeare** [comment]
What's the best way to test this?  Or can you not test it locally?

**Comment by joewhitsitt** [comment]
Sorry, updated test instructions. Yes this should be available to test locally.

**Comment by pyrello** [comment]
Fixing conflicts on this.

**Comment by pyrello** [comment]
Testing since I have it setup locally.

**Comment by pyrello** [comment]
I'm noticing a regression where, when I click on the Video vertical tab, it doesn't switch the panel that's showing. I'm going to check if this is happening in the main branch.

**Comment by joewhitsitt** [comment]
>when I click on the Video vertical tab

You mean the media library? Is that related to this module's functionality?

**Comment by pyrello** [comment]
> You mean the media library? Is that related to this module's functionality?

The regression appears to be happening in `main` so appears to be unrelated.

**Comment by pyrello** [comment]
> On render an image from the first second should display.

This isn't happening for me:

Screenshot 2023-06-14 at 10 13 07 AM

Testing on https://sandbox.uiowa.ddev.site/banners-imagesvideos-w-black-and-white-gradients. Not sure if there is a `stage_file_proxy` issue at play here or not. I would think not, since the video is being uploaded locally.

**Comment by bspeare** [comment]
@pyrello is the black video thumbnail image showing up as the poster image on the `video` tag?  That's what I had when I tested this out.

**Comment by pyrello** [comment]
I'm seeing `poster="https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/media-icons/generic/video.png"`. The PNG its pointing at does not appear to exist.

**Comment by pyrello** [comment]
@joewhitsitt Can you provide a screenshot of the expected behavior?

**Comment by joewhitsitt** [comment]
shoot. sorry. i can pull down after the oniowa meeting

**Comment by joewhitsitt** [comment]
Yep. This isn't working as expected. Not sure because I thought it worked when I put this together.

Expected behavior in PROD:
Screenshot 2023-06-14 at 11 23 24 AM
Screenshot 2023-06-14 at 11 23 03 AM
Screenshot 2023-06-14 at 11 23 14 AM


Actual behavior on LOCAL:

Screenshot 2023-06-14 at 11 25 06 AM
Screenshot 2023-06-14 at 11 24 47 AM
Screenshot 2023-06-14 at 11 24 56 AM

**Comment by joewhitsitt** [comment]
Anyone care if I send this out to DEV for testing? It might have to do with the availability and path of ffmpeg and ffprobe

**Comment by bspeare** [comment]
Nope, I think this is just a local issue.

**Comment by joewhitsitt** [comment]
It worked on DEV with similar behavior as PROD:

Blank on upload. Thumbnail on insert. Placeholder for LB preview.

Screenshot 2023-06-14 at 12 14 24 PM

**Review by bspeare — APPROVED** [review]
Tested on https://sandbox.dev.drupal.uiowa.edu/banner-videos and it works as Joe described.

**Pull request merged**
