### PR TITLE
[Commencement] event importer fixes

### PR DESCRIPTION
**Pull request by e-marie-w**
Sort of relates to #7822 

# How to test

- ~~Code review - is this the best way to do this? I tried doing this a different way (see commit number 4) but couldn't get that way to work correctly.~~
- `ddev blt ds --site=commencement.uiowa.edu && ddev drush @commencement.local uli`
- Note how events like https://commencement.uiowa.ddev.site/ceremony/spring-2025/college-liberal-arts-and-sciences-9-am-commencement-ceremony have everything in one paragraph and no links, vs. how it is on the [events calendar](https://events.uiowa.edu/70820)
- `ddev drush @commencement.local import-events`
- Spot check a few different events. Paragraph breaks and links should now appear correctly in the details field.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling to test

**Comment by joewhitsitt** [comment]
>is this the best way to do this

Looks like this is how facilities' building combined hours was done. Future work could be done to process different field types beyond value only.

**Comment by joewhitsitt** [comment]
>Commencement event content sync completed. 0 events were created, 58 updated, 0 deleted, 0 skipped. That is neat.

Concerned there is always updated nodes. Looks like the same thing on `main` though so unrelated to this change. Has this been mentioned before?

Update: The room number field is always updated when record is "" and entity is NULL.

**Comment by e-marie-w** [comment]
> > Commencement event content sync completed. 0 events were created, 58 updated, 0 deleted, 0 skipped. That is neat.
> 
> Concerned there is always updated nodes. Looks like the same thing on `main` though so unrelated to this change. Has this been mentioned before?

That also worries me. I feel like this issue came up recently but I can't recall if it was about commencement or another site. Either way, I can poke at this some and see if there's an easy fix.

**Comment by joewhitsitt** [comment]
Pushed a fix for body always being updated = true. The room number probably needs to be processed similarly and not included in the field map. Either that or the EntityItemProcessorBase needs to be updated to handle that blank/null non-value.

https://github.com/uiowa/uiowa/blob/3ced9f3cb2b92db0f9b4d7aa16fd876e28f43711/docroot/modules/custom/uiowa_core/src/EntityItemProcessorBase.php#L52

**Comment by joewhitsitt** [comment]
@e-marie-w was this ready for review again or are you still tweaking it?

**Comment by e-marie-w** [comment]
> @e-marie-w was this ready for review again or are you still tweaking it?

It's ready for review again!

**Comment by joewhitsitt** [comment]
Works fine as-is, but a with a little nitpicking, this will simplify the comparison. We don't care that it `!is_null()`, only that it exists and isn't the value we want to later work with.

```php
if (property_exists($record, 'room_number') && $record->room_number === '') {
    $record->room_number = NULL;
}
```

As for Percy, hopefully just a momentary hiccup:

```
[percy] asset-discovery - Articles - 44.639s
[percy] Encountered an error taking snapshot: Articles
[percy] Error: Timed out waiting for network requests to idle.
[percy] asset-discovery - Article - 45.643s
[percy] Encountered an error taking snapshot: Article
[percy] Error: Timed out waiting for network requests to idle.
```

**Review by joewhitsitt — APPROVED** [review]

**Comment by e-marie-w** [comment]
> Works fine as-is, but a with a little nitpicking, this will simplify the comparison. We don't care that it `!is_null()`, only that it exists and isn't the value we want to later work with.
> 

Oh that is way better, thank you! Change committed.

**Pull request merged**
