### PR TITLE
[Bug] Wysiwyg fonts / colors fix

### LINKED ISSUE #6282: Buttons and other styles within CKEditor are not displaying correctly
# Problem
Buttons style using the Primary and Secondary styles are not showing up correctly within the editor window. The live site looks correct.

image

# Proposed solution

Audit the styles that are added to the wysiwyg, and which are not.

Additional styles can be pulled into ckeditor through https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/uids_base.info.yml,
or included through https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/sitenow/sitenow_wysiwyg.scss

For styles that might need tweaks to work correctly within the wysiwyg, alterations can be added to `sitenow_wysiwyg.scss` with minimal impact outside of this.

https://github.com/uiowa/uiowa/pull/1712/files#diff-3e2f505910782c55036ebbe9cabac6fb649ee875a4588beeed62d0c70f533057

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6282. 

# How to test
```
ddev blt frontend && ddev blt ds --site=sandbox.uiowa.edu && ddev drush @sandbox.local uli kitchen-sink
```

Compare wysiwyg preview on https://sandbox.prod.drupal.uiowa.edu/kitchen-sink to local.  Verify that you can now see all headings a fonts and tables styled in the wysiwyg. 

Bonus testing: 
- V2 
```
ddev blt ds --site=brand.uiowa.edu && ddev drush @brand.local uli applying-brand/web
```
- Off-brand (still black and gold)
```
ddev blt ds --site=wirrc.org && ddev drush @org-wirrc.local uli degree-and-certificate-offerings
```
- Serif font 
```
ddev blt ds --site=writinguniversity.org && ddev drush @org-writinguniversity.local uli teaching-research
```

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
Just realized this was ready but not requested. Based on testing, I will approve if that changes. Thanks for figuring it out!

**Comment by bspeare** [comment]
Thanks @joewhitsitt, it is ready for review.

**Review by joewhitsitt — APPROVED** [review]
Thanks! Sorry for jumping the gun.

**Pull request merged**
