### PR TITLE
update stage_file_proxy to 3.1.3

### PR DESCRIPTION
**Pull request by joewhitsitt**
# How to test

- Check that your local.settings.php file for the website is not trying to mimic another environment like PROD. `
$config['config_split.config_split.local']['status'] = FALSE;` (We want that to be TRUE if it exists at all and not overridden by another line like `config_split.config_split.prod`
- Sync sandbox.uiowa.edu but delete the contents of the site's files directory locally.
- If you haven't previously, update the local.settings.php file for the website with the internal production or live URL of the website (e.g. `$config['stage_file_proxy.settings']['origin'] = 'https://sandbox.prod.drupal.uiowa.edu/';`)
- Database updates should run without error and config should import locally as expected.
- Navigate pages and see media display
- If hot linking is enabled, media should display and the files directory should remain fairly empty.
- If hot linking is disabled, media should be downloaded to the files directory as expected.

admin/config/system/stage_file_proxy

### CODE REVIEW

**Comment by joewhitsitt** [comment]
Noticed some quirky behavior when testing https://github.com/uiowa/uiowa/pull/8182#issuecomment-2444854189. Let's update the module and rule that out.

**Comment by bspeare** [comment]
Do I need to enable `stage_file_proxy` to test this or should it be automatically on?

**Comment by joewhitsitt** [comment]
It should be enabled by default in the local environment. Whether or not the site is configured to use it, might be the sticking point.

docroot/sites/sandbox.uiowa.edu/settings/local.settings.php

$config['stage_file_proxy.settings']['origin'] = 'https://sandbox.prod.drupal.uiowa.edu';

**Comment by bspeare** [comment]
Thanks.  For some reason it is not enabled. I'll have to do some further investigation as to why it is not being turned on.

**Comment by joewhitsitt** [comment]
Did you switch sandbox to use a different env split?

**Comment by cory-skeers** [comment]
Checked this out, and my local env is using stage file proxy by default, and is working as expected (with hotlink enabled).

**Comment by bspeare** [comment]
Can we merge this? I'm getting this error on 2.1: https://www.drupal.org/project/stage_file_proxy/issues/3450243.

**Comment by joewhitsitt** [comment]
I was waiting for formal approval

**Review by bspeare — APPROVED** [review]
Fixes the issue with https://www.drupal.org/project/stage_file_proxy/issues/3450243.

**Comment by bspeare** [comment]
Also having this issue now with `3.1.3` in testing: https://www.drupal.org/project/stage_file_proxy/issues/3457368.

**Comment by bspeare** [comment]
@joewhitsitt mind if I merge this?

**Pull request merged**
