### PR TITLE
Add webp derivative to all responsive image styles.

### PR DESCRIPTION
**Pull request by richardbporter**
This seems like a quick win. A set-it-and-forget solution to add a WebP image style to all responsive image formats. It should fallback in browsers (Safari) where it is not supported. I'm not finding a similar module for jpeg2000.

Test
- Sync a site locally so config is imported.
- Check for webp derivative in responsive image picture elements.
- Profit.

### CODE REVIEW

**Comment by richardbporter** [comment]
https://www.cnet.com/news/apple-ios-macos-tests-googles-webp-graphics-to-speed-up-web/

**Comment by joewhitsitt** [comment]
> July 19, 2016

Is Apple, Mozilla still mulling it over?

**Comment by richardbporter** [comment]
No clue. That was linked off caniuse.

**Review by pyrello — APPROVED** [review]
This seems to work as advertised.

**Review by joewhitsitt — APPROVED** [review]
ditto

**Pull request merged**
