### PR TITLE
uiowa.edu - import redirects and match redirects

### LINKED ISSUE #1249: [Story] As a site visitor I can be redirected from old paths to where the content exists now.
- [x] Get current uiowa.edu redirects/match redirects and communicate freeze/double post of redirects going forward
- [x] See if match redirects work in D8
- [x] Use similar HR redirect update hook to import

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #1249

## To Test
- Pull uiowa.edu locally with a dsa
- Confirm that the redirect module is successfully patched
- Confirm that update hook importing redirects fires and completes.
- Login to the website to confirm the redirects table has been populated (several pages)
- Try a regular redirect and a match redirect (something/*)

### CODE REVIEW

**Comment by richardbporter** [comment]
Could redirecting in htaccess make this any easier?

**Review by pyrello — APPROVED** [review]
I have reviewed the code. I'm not sure about the best way to test. Just pull it down and make sure that all the new redirects are present?

**Comment by joewhitsitt** [comment]
@pyrello , sorry I thought I had filled out the test steps for this one. I have updated the PR description if you are interested.

**Review by pyrello — APPROVED** [review]
Tested!

**Pull request merged**
