### PR TITLE
Move moderation control, remove links field

### PR DESCRIPTION
**Pull request by cory-skeers**
Relates to #2078. Initial work moving some things around.

Removes links block, and separates moderation control block from main content. 
Places moderation control in its own section currently above the header, and locks the section/block from editing.

## Testing
Sync a site, update config.
Check that main content sections contain the body field and/or sidebar menu (no links field, no moderation control).
Check that the moderation control appears and works properly (visible when viewing non-published pages).
_Needs to be checked across the various splits_
hr.uiowa.edu, policy.clas.uiowa.edu, and coronavirus.uiowa.edu have site-specific splits.
- hr.uiowa.edu: No changes should be made
- policy.clas.uiowa.edu and coronavirus.uiowa.edu should have the newly moved moderation control, removed links placeholder, and no additional changes/regressions.

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
This looks great to me so far @cory-skeers, nice work! The blocks have been moved properly and links have been removed. 
Screen Shot 2020-08-28 at 2 51 11 PM

**Comment by cory-skeers** [comment]
Thanks @mark-bennett-uiowa!

Opening for review as an incremental change, can be further addressed in #2078.

**Review by joewhitsitt — APPROVED** [review]
Checked in v3, collegiate as webmaster for lb preview, node preview, and render.

v2 it is still in the content region

**Comment by cory-skeers** [comment]
Updated the SNV2 split to also move moderation control and remove links field to keep them in line. Would appreciate a double-check on that split in particular.

**Comment by joewhitsitt** [comment]
I just realized that the file in question is split different on hr, coronavirus, policy.clas. Do we want to extend these changes to those as well? Probably a good idea right? Consistent to theme against.

**Comment by cory-skeers** [comment]
Gah! Yes, I think we should update those as well. Glad you caught that.

**Comment by pyrello** [comment]
Pulling this down for review

**Comment by cory-skeers** [comment]
Converting to draft until additional config splits are pushed up and tested.

**Comment by cory-skeers** [comment]
@joewhitsitt For the HR split, looks like the page display isn't using the layout currently--I'm guessing it's best to just not touch HR for now, and when they come into the fold set up the page layout to match whatever is current w/the rest of the sites at that point?

**Comment by joewhitsitt** [comment]
Yeah, leave HR alone if it still works. I keep forgetting that HR is pretty sectioned off from the v2 split.

**Comment by cory-skeers** [comment]
Updated config splits for policy.clas.uiowa.edu and coronavirus.uiowa.edu, that could use another pair of eyes before merging.

**Review by joewhitsitt — APPROVED** [review]
In reviewing corona and policy, I got a taste of overridden templates that don't have the region anymore. Worked for new content.

Not sure if this is just one-step in a larger process, but I'd be interested following up this PR to limit what developers can place back in that region since it is named specifically for moderation.

**Comment by cory-skeers** [comment]
There was some small discussion in #2078 regarding the default template that I think could be developed out more, and would be a good place to address further updates. For now, I think it's enough to move it and remove the links field

**Pull request merged**
