### PR TITLE
Bump drupalvm to 6.0.3.

### LINKED ISSUE #2979: Ansible + PIP issue - Bump drupal-vm when its next release is out (6.0.3?)
Hi, I'm sure dependabot will let you know about the next release of drupal-vm, so this is just a reminder/info. I was rebuilding my VM yesterday due to a separate issue and I ran across a recent problem with Ansible described here:

https://github.com/geerlingguy/drupal-vm/issues/2138

Ansible was unable to be downloaded + installed and vagrant up failed due to PIP 2 being used to fetch a script only compatible with PIP 3.  I had to temporarily change drupal-vm's composer constraint to dev-master before updating it via composer and running vagrant up. 

The drupal-vm maintainer hasn't actually merged the fix into a release yet, but this may block anyone trying to reclone or rebuild a VM right now.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2979 

I did not shut down my VM before upgrading which caused me to somehow lose it. I had to destroy and then delete a duplicate VM in the VirtualBox interface. Hopefully, halting the VM before upgrading will just work for people. Looking for testers on that. :)

### Testing
- vagrant halt
- composer install
- vagrant up --provision
- vagrant ssh
- composer --version

Newly-created VMs still get hirak/prestissimo installed globally despite it being removed from drupal-vm config. I tried removing it in our post-provision scripts but it just hangs with no debug output.

### CODE REVIEW

**Comment by richardbporter** [comment]
@quamsta Curious if this solves your issue.

**Comment by dnkemper** [comment]
I guess I can be the brave soul that tests this out 😅

**Review by dnkemper — APPROVED** [review]
Halting the vm worked! Nice work!

**Comment by quamsta** [comment]
@richardbporter Yep, this fixed it. Was able to provision without issue now -- this fixes https://github.com/uiowa/uiowa/issues/2979

Thanks!!

**Pull request merged**
