### PR TITLE
Allow headline styles in WYSIWYG

### LINKED ISSUE #2532: As a content editor, I can set Zilla headings and Zilla underline styles in the WYSIWYG toolbar rather than in HTML source
# Story

As a content editor, I can set Zilla headings and Zilla underline styles in the WYSIWYG toolbar rather than in HTML source 

Previous solution:

<details>
As a content editor, I can adjust font styling in WYSIWYG toolbar rather than in HTML source.

Could we get font styles or options to set font to the following options:

- [ ] Smaller text
- [ ] Headline text in Serif font
- [ ] Headline text in Serif font with underline
- [x] uids-component--light-intro
- [x] uids-component--bold-intro
- [ ] more?

Currently we have to edit the HTML in source to get the headline font to change.

Screen Shot 2020-11-12 at 4 48 49 PM
</details>

# Proposed solution

- Add styling options to WYSIWYG for the Zilla serif and Zilla serif underline heading styles. 
- https://github.com/uiowa/uiowa/issues/2532#issuecomment-1040864388

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #2532 

# How to test

`git checkout allow-headline-styles-wysiwyg && git pull`
`blt ds --site=sandbox.uiowa.edu` or another site
Try editing some text fields, and set some fancy new heading styles (available in filtered and full html formats)

### CODE REVIEW

**Comment by cory-skeers** [comment]
Want to double check the config updates--might have gotten some extra stuff in the export.

**Comment by cory-skeers** [comment]
I believe this is ready for review.

@bspeare, the two class combos I added for serif with/out underline were:
`headline.headline--serif`
`headline.headline--serif.headline--underline`
Wondering if this looks right to you?

**Comment by bspeare** [comment]
@cory-skeers those look like the classes we want!

**Comment by mark-bennett-uiowa** [comment]
pulling for testing.

**Comment by mark-bennett-uiowa** [comment]
This looks really good @cory-skeers thank you. I tested this on some existed headings, and they recognize the styling without prompting:
Screen Shot 2022-04-15 at 3 19 11 PM
I also tested reverting this styling by selecting Normal text under the Paragraph formatting dropdown. Tested this with all headline sizing as well.

Do we need to have all the options for H2 Serif, H2 Serif Underline, etc. or can we simply have a Heading Serif and Heading Serif Underline style? Also, can we move these up underneath the Intro Bold and Intro Light styling options?

**Review by mark-bennett-uiowa — APPROVED** [review]
Pulled, tested, and reviewed. Looks good with comments above.

**Comment by bspeare** [comment]
Percy noticing these styles have had their classes removed:

Screen Shot 2022-04-15 at 3 45 47 PM
Screen Shot 2022-04-15 at 3 46 05 PM

**Comment by cory-skeers** [comment]
> Do we need to have all the options for H2 Serif, H2 Serif Underline, etc. or can we simply have a Heading Serif and Heading Serif Underline style? Also, can we move these up underneath the Intro Bold and Intro Light styling options?

We can change the ordering! Unfortunately if we want to allow styling for different heading levels, they all have to be listed out separately because of how ckeditor handles block styles. Looks like that will be changing for ckeditor 5 though...

**Comment by cory-skeers** [comment]
> Percy noticing these styles have had their classes removed:

Hrm...Not seeing those regressions locally, but can poke around.

**Comment by bspeare** [comment]
@cory-skeers maybe because we changed it from `<p class>` to  `<p class=" uids-component--bold-intro uids-component--light-intro">` ?

**Comment by cory-skeers** [comment]
> @cory-skeers maybe because we changed it from `<p class>` to `<p class=" uids-component--bold-intro uids-component--light-intro">` ?

Hrm...maybe! I wouldn't think that should effect things there, but it's possible, and either way, wasn't an intentional change. Gonna update and see if it likes it better.

**Comment by cory-skeers** [comment]
Updated the ordering, and also got rid of the allowed html changes, because they didn't need to be changed anyway.

Fingers crossed it'll fix the Percy issue!

**Comment by mark-bennett-uiowa** [comment]
Pulled for testing. This worked great. I pulled down ISA and sandbox and tested both. I did not see the issue from above on sandbox. However, sandbox is using old classes:
Screen Shot 2022-04-15 at 5 06 25 PM
Screen Shot 2022-04-15 at 5 06 16 PM
So, the textarea in the LB block is not picking up the new styles:
Screen Shot 2022-04-15 at 5 09 15 PM

**Pull request merged**
