### PR TITLE
Specify dependency on uids_base instead of uids for Yarn workspaces.

### LINKED ISSUE #3014: Incorrect version of uids installed under certain conditions
# Problem
The version specified in the yarn.lock file of uiowa/uids is ignored under certain conditions. This seems to happen when a new release is available due to the odd version constraint in the uiowa_apr workspace.

# Steps to reproduce
- `git fetch`
- `git checkout 3.3.25`
- `rm -rf node_modules`
- `cat yarn.lock | grep -C 5 '@uiowa/uids'`
  -  Note that uiowa/uids is locked at 3.1.10.
- `blt frontend`
- `yarn why @uiowa/uids`
  - See latest version is installed: `=> Found "@uiowa/uids@3.2.0"`

# Proposed solution
Change the uiowa_apr workspace to depend on uids_base instead and use uids_base to strictly manage the uids version going forward.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #3014 

# How to test

Follow the steps in #3014 to replicate the issue, assuming you don't mind nuking node_modules. Then do it again but make a manual change to the uiowa_apr/package.json file beforehand: replace the dependency on uiowa/uids with what it is changed to in this PR: "uids_base": "^1.0.0".

Then when you run the commands in #3014 you should see `=> Found "@uiowa/uids@3.1.10"` instead.

Other changes
- Update README docs on workspaces.
- Change APR SASS imports to use uids_base.
- Output uiowa/uids version after running `blt frontend`.
  - https://travis-ci.com/github/uiowa/uiowa/builds/215969158#L3643

### CODE REVIEW

**Comment by richardbporter** [comment]
I verified that APR styles still work.

**Comment by richardbporter** [comment]
This does not change the process of updating uids.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by richardbporter** [comment]
Ugh. My testing instructions are not great. I just simplified them. Sorry.

**Comment by GaryRidgway** [comment]
pulling to test as well

**Review by joewhitsitt — APPROVED** [review]
Horrible instructions, but got `=> Found "@uiowa/uids@3.2.0"` in the end...

Update: just realized I was supposed to see `you should see => Found "@uiowa/uids@3.1.10" instead.`

**Comment by richardbporter** [comment]
> Horrible instructions, but got `=> Found "@uiowa/uids@3.2.0"` in the end...

Now I realize why I wrote the instructions the way I did. I locked uids at 3.2.0 in this PR since we need it. To illustrate the problem though, I wrote the instructions to show that on main, the change in uiowa_apr/package.json prevented uids from updating to the latest release.

**Comment by richardbporter** [comment]
It works: https://travis-ci.com/github/uiowa/uiowa/builds/216092098#L3664

**Pull request merged**
