### PR TITLE
Update admissions counselor territory options

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves final checkboxes of #2649.

# How to test

- `blt ds --site=admissions.uiowa.edu`
- Go to http://admissions.local.drupal.uiowa.edu/counselors
- Check that "International Recruitment" option appears at the top (below " - Any - ")
- Check that only "International Recruitment", states, and DC are included in the list (American Samoa, Guam, Northern Mariana Islands, Puerto Rico, United States Minor Outlying Islands, and Virgin Islands, U.S. have been removed)
- Check that a counselor person type has the same above options for their territory

### CODE REVIEW

**Comment by joewhitsitt** [comment]
WOW! seriously?! Fast work @cory-skeers. Can we move this to admissions_core.install and remove the if at the beginning?

I will test here shortly.

**Comment by cory-skeers** [comment]
Good call! Forgot there was a separate admissions module. Got it moved over and removed the initial check.

Had a nice base to work off of--guessing there are some spots that could be cleaned up that are leftovers from the previous update, but functionally it should be good to run and test!

**Comment by GaryRidgway** [comment]
You are a madman Cory. A very skilled madman, but a madman none the less.

**Review by joewhitsitt — APPROVED** [review]
Worked for me! Thanks

**Pull request merged**
