### PR TITLE
Use loggerChannelTrait again

### LINKED ISSUE #7597: Watchdog logging lost again for Facilities API
# Problem

[A drush update and recent changes to the Facilities API](https://github.com/uiowa/uiowa/pull/7449) seem to have caused watchdog logging of the commands to stop being passed on to Splunk:
No new logs since 4/10: https://splunk.its.uiowa.edu/en-US/app/search/search?q=search%20index%3Duiowa-acquia%20%22That%20is%20neat.%22&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=%40mon&latest=now&sid=1713196218.42446_EDED3979-0BD0-4DD8-A05C-4F129EBB094A

### PR DESCRIPTION
**Pull request by cory-skeers**
Resolves #7597 

# How to test

The following sitenow and site drush commands have been updated:

- Uiowa Core: `uiowa_core:toggle-gtag`, `uiowa_core:custom_role_mappings`
- Sitenow p2lb: `sitenow_p2lb:cleanup`
- its.uiowa.edu: `its_core:alerts-digest`
- brand.uiowa.edu: `brand_core:lockup-digest`
- classrooms.uiowa.edu: `classrooms_core:buildings`, `classrooms_core:rooms_import`
- facilities.uiowa.edu: `facilities_core:buildings_import`, `facilities_core:projects_import`

For each, test that on a fresh site sync 

1. the command functions and you see terminal output
2. Enable dblog and re-run the command, and check that
   1. you see terminal output 
   2. watchdog has caught the log (eg `ddev drush @site.local watchdog-show --count=10` you see a line item for what you just ran, or at /admin/reports/dblog)
3. Clear cache on the site you're working with, re-run again, and check that 
   1. you see terminal output
   2. watchdog has caught the log

If the command ran properly in step 1, for steps 2 and 3 you only need to let it run far enough to get output and/or logging (for instance, facilities building import, you can cancel after the initial "starting" message)

### CODE REVIEW

**Comment by bspeare** [comment]
Pulling to test.

**Comment by bspeare** [comment]
Here are the results of my testing.  I'm getting errors on  Brand and on sites with p2lb enabled.


### Brand
- `ddev drush @brand.local brand_core:lockup-digest`  
- `Error: Call to undefined method Drupal\brand_core\Commands\BrandCoreCommands::t() in /var/www/html/docroot/sites/brand.uiowa.edu/modules/brand_core/src/Commands/BrandCoreCommands.php on line 84 #0 [internal function]: Drupal\brand_core\Commands\BrandCoreCommands->lockupDigest(Array)` 

### toggle-gtag
`ddev blt ds --site=default`
`ddev drush @default.local uiowa_core:toggle-gtag`

Before dblog enabled:
- ` [notice] Site-specific Google Tag Manager Enabled`

After dblog enabled:
- No terminal output
- Dblog message: `Site-specific Google Tag Manager Disabled`

After clearing cache:
- Both messages appear as expected. 


### custom_role_mappings
`ddev drush @default.local  uiowa_core:custom_role_mappings`

Before dblog enabled:
- No terminal output

After dblog enabled:
- No terminal output
- No dblog

### p2lb
- `ddev blt ds --site=latinxcouncil.uiowa.edu`, ` ddev blt ds --site=law.uiowa.edu `
- `TypeError: Drupal\sitenow_p2lb\Commands\P2LbCommands::__construct(): Argument #2 ($entityTypeManager) must be of type Drupal\Core\Entity\EntityTypeManagerInterface, Drupal\Core\Logger\LoggerChannel given in Drupal\sitenow_p2lb\Commands\P2LbCommands->__construct() (line 53 of /var/www/html/docroot/modules/custom/sitenow_p2lb/src/Commands/P2LbCommands.php).`

### Buildings import
- `ddev drush @facilities.local facilities_core:buildings_import`

Before dblog enabled:
- Terminal message: `Starting the facilities building content sync from drush. This may take a little time if the information isn't cached. Facilities building content sync completed. 0 buildings were created, 223 updated, 0 deleted, 168 skipped. That is neat. Duration: 339.54 seconds [notice] Message: The node was added to the Node Revision Delete queue.`

After dblog enabled: 
- Terminal message: `Duration: 340.56 seconds. [notice] Message: The node was added to the Node Revision Delete queue.`
- Dblog message: `Facilities building content sync completed. 0 buildings were created, 223 updated, 0 deleted, 168 skipped. That is neat.`

After clearing cache:
- Both messages appear as expected. 

### Projects import
- `ddev drush @facilities.local facilities_core:projects_import`

Before dblog enabled:
- ` [notice] Starting the facilities projects sync from drush. This may take a little time if the information isn't cached. Facilities projects content sync completed. 0 projects were created, 1 updated, 0 deleted, 209 skipped. That is neat.
Duration: 120.38 seconds [notice] Message: The node was added to the Node Revision Delete queue.`


After dblog enabled: 
- Terminal message: `Duration: 96.30 seconds [notice] Message: The node was added to the Node Revision Delete queue.`
- Dblog message: `Facilities projects content sync completed. 0 projects were created, 1 updated, 0 deleted, 209 skipped. That is neat.`

After clearing cache:
- Both messages appear as expected. 


### ITS Alerts digest
- `ddev drush @its.local its_core:alerts-digest `

Before dblog enabled:
- Terminal message: ` [notice] Alerts Digest sent`

After dblog enabled: 
- No terminal message
- Dblog message: `Alerts Digest sent`

After clearing cache:
- Both messages appear as expected. 


### Classrooms buildings
- `ddev drush @classrooms.local classrooms_core:buildings`

Before dblog enabled:
- Terminal message: ` [notice] Bummer. No new buildings were created. Maybe next time.
Duration:  1.10 seconds`

After dblog enabled: 
- Terminal message: `Duration:  0.00 seconds`
- Dblog message: `Bummer. No new buildings were created. Maybe next time.`

After clearing cache:
- Both messages appear as expected. 

### Classrooms rooms
- `ddev drush @classrooms.local classrooms_core:rooms_import`

Before dblog enabled:
```
>  [notice] Running Batch "1"
>  [notice] Running Batch "2"
>  [notice] Running Batch "3"
>  [notice] Running Batch "4"
>  [notice] Running Batch "5"
>  [notice] Running Batch "6"
>  [notice] Running Batch "7"
>  [notice] Running Batch "8"
>  [notice] Running Batch "9"
>  [notice] Running Batch "10"
>  [notice] Running Batch "11"
>  [notice] Running Batch "12"
>  [notice] Running Batch "13"
>  [notice] Running Batch "14"
>  [notice] Running Batch "15"
>  [notice] Running Batch "16"
>  [notice] Running Batch "17"
>  [notice] Running Batch "18"
>  [notice] Running Batch "19"
>  [notice] Running Batch "20"
>  [notice] Running Batch "21"
>  [notice] Message: 0 results updated. That is neat.
> 
```

After dblog enabled:
- Terminal: same as above
- Dblog: `Rooms import update batch operations ended.`

**Comment by cory-skeers** [comment]
I believe brand and p2lb commands should be working now.

**Comment by bspeare** [comment]
Brand and p2lb are working now.   @cory-skeers are the rest of the results from https://github.com/uiowa/uiowa/pull/7889#issuecomment-2218233645 expected?

**Comment by cory-skeers** [comment]
> Brand and p2lb are working now. @cory-skeers are the rest of the results from [#7889 (comment)](https://github.com/uiowa/uiowa/pull/7889#issuecomment-2218233645) expected?

Thanks for testing and the thorough documenting! Yes, that all looks to match what should be expected after the update.

The extra cache clear should only be needed to get terminal outputs working again, so I don't think we need to do anything extra there with rolling things out, thankfully.

**Review by bspeare — APPROVED** [review]
Nice work! Thanks for reviewing my notes :)

**Pull request merged**
