### PR TITLE
[P2LB] Turn off V2 and P2LB

### LINKED ISSUE #6814: Figure out how to remove P2LB and V2 from a site after its owners have signed off on the conversion
# Proposed solution

```[tasklist]
### Tasks
- [x] Create `sitenow_p2lb` uninstall hook that can be triggered by `drush pm:uninstall sitenow_p2lb`
- [x] Remove protected revision field content
- [x] Remove every revision for page up to and including the protected revision
- [x] Investigate whether `sitenow_v2` entry in sites blt file is used anywhere in automated commands or other code
- [x] If not, update all site's blt files manually to remove the `sitenow_v2` entry
- [x] Turn off P2LB split
- [x] Turn off V2 split
- [x] Identify any other things that need to be addressed
```

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/6814

# How to test
```
ddev blt sync --site staff-council.uiowa.edu && ddev drush @staff-council.local config-split:activate p2lb -y && ddev drush @staff-council.local uli admin/content/sitenow-converter
```

```
ddev blt sync --site faculty-senate.uiowa.edu && ddev drush @faculty-senate.local config-split:activate p2lb -y && ddev drush @faculty-senate.local uli admin/content/sitenow-converter
```

1. Convert all pages
2. Check some card link conversions related to the change here https://github.com/uiowa/uiowa/pull/6830/commits/9be1262564ebffc0bc1c7c30aeafebfe956a0bf5
3. Publish latest revisions `/admin/content?title=&type=page&status=All&field_tags_target_id=`
4. Cleanup

```
ddev drush @staff-council.local sitenow_p2lb:cleanup
```

```
ddev drush @faculty-senate.local sitenow_p2lb:cleanup
```

- Observe that paragraph types are gone (except for the v3 ones)
- Running a `cim` after the drush command should note no changes/diff.
- Inspecting the database before and after there should be ~94 less tables and upon closer inspection, things like `node__field_page_content_block` and `paragraph__field_section_content_block` should not be there.
- Browser console should say v3.

Try testing on another website (NOT gis.sites.uiowa.edu, that site has some gremlins). Also keep in mind #6859, so like for brand, deleting the other revisions newer than the protected revision needs to happen before the drush command is triggered or the config import at the end will error out.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
@bspeare did you encounter this when working on this PR?

```
diff --git a/tmp/drush_tmp_1693929635_64f750a3713e4/core.entity_form_display.node.page.default.yml b/tmp/drush_tmp_1693929636_64f750a40f662/core.entity_form_display.node.page.default.yml
index 90307f8..fd7edda 100644
--- a/tmp/drush_tmp_1693929635_64f750a3713e4/core.entity_form_display.node.page.default.yml
+++ b/tmp/drush_tmp_1693929636_64f750a40f662/core.entity_form_display.node.page.default.yml
@@ -148,11 +148,6 @@ content:
     settings:
       display_label: true
     third_party_settings: {  }
-  simple_sitemap:
-    weight: 10
-    region: content
-    settings: {  }
-    third_party_settings: {  }
   status:
     type: boolean_checkbox
     weight: 12
```

**Comment by bspeare** [comment]
@joewhitsitt I did after trying to resync it recently.  I'm not sure where it came from.

**Comment by joewhitsitt** [comment]
Okay. I think it might be that v2 didn't get updated when we updated the sitemap module.

**Comment by joewhitsitt** [comment]
>Remove protected revision field content

So I've changed some code in https://github.com/uiowa/uiowa/pull/6830/commits/9096d07833e4cb15cfab7463b44b4091664f198b.

It uses the same stuff as [node_revision_delete](https://git.drupalcode.org/project/node_revision_delete/-/blob/8.x-1.x/src/NodeRevisionDeleteBatch.php?ref_type=heads#L53). My understanding is that it deletes what we want. But I am going to monitor the database through this process.

Supposedly this was address to clean up node_field_revision stuff: https://www.drupal.org/project/drupal/issues/2753971

There is some possible issue with referenced files https://www.drupal.org/node/1239558

Some of this might be cleaned up with deleting orphaned paragraphs content.

**Comment by joewhitsitt** [comment]
Looks like to really clean things up, `/admin/config/system/delete-orphans` or `drush err:purge paragraph` has to be run approximately three times after to handle the layers of nesting. The first run will delete the sections (because the page host revision was deleted). Then accordions will be deleted because the section host was deleted. Then accordion items will be deleted because the accordion host is deleted...

**Comment by joewhitsitt** [comment]
Tried this on brand and I am running into a processing error related to card links and `mailto:`

`The internal path component 'mailto:fm-building-signage@uiowa.edu' is invalid. Its path component must have a leading slash, e.g. internal:/foo.`

Drupal\Core\Url::fromUri('internal:mailto:fm-building-signage@uiowa.edu') (Line: 571)

**Comment by joewhitsitt** [comment]
I _think_ I fixed https://github.com/uiowa/uiowa/pull/6830#issuecomment-1708787819 except for one node on brand where the link was straight up `brand.uiowa.edu` which is invalid (node/3776). It was a draft page so I fixed the URL in prod

**Comment by joewhitsitt** [comment]
Do we want to delete all revisions except for the "current" one? I've run into an issue on brand where things get messy and there are v2 revisions newer than the protected revision. This results in the orphan purger not cleaning things up because the current code only deletes the protected revision and anything that is "less than"

Screenshot 2023-09-06 at 2 46 11 PM

**Comment by joewhitsitt** [comment]
Current combination is running multiple times because disabling the split, uninstalls the module while the uninstall is already firing.. Trying to resolve.

**Comment by joewhitsitt** [comment]
Sean said something about this being done on deployment through an update hook, so I think this is how it would look:

```php
use Drush\Drush;

/**
 * Cleanup v2/P2LB.
 */
function mysite_update_9001() {
  $alias = Drush::aliasManager()->getSelf();
  $cleanup = Drush::processManager()->drush($alias, 'sitenow_p2lb:cleanup');
  $cleanup->run($cleanup->showRealtime());
  $cleanup->getOutput();
}
```

**Comment by pyrello** [comment]
Pulling to test

**Comment by pyrello** [comment]
Didn't actually have time to test. Un-assigned myself.

**Comment by GaryRidgway** [comment]
Pulling to test

<details><summary>Getting an error on conversion.</summary>
<p>

```
Warning: Undefined array key 0 in Drupal\sitenow_p2lb\P2LbConverter->processSection() (line 156 of modules/custom/sitenow_p2lb/src/P2LbConverter.php).
Drupal\sitenow_p2lb\P2LbConverter->processSection('421') (Line: 68)
Drupal\sitenow_p2lb\P2LbConverter->processSections() (Line: 50)
Drupal\sitenow_p2lb\P2LbConverter->convert() (Line: 39)
Drupal\sitenow_p2lb\Plugin\Action\ConvertParagraphsToLayoutBuilder->execute(Object) (Line: 22)
Drupal\Core\Action\ActionBase->executeMultiple(Array) (Line: 129)
Drupal\system\Entity\Action->execute(Array) (Line: 415)
Drupal\views\Plugin\views\field\BulkForm->viewsFormSubmit(Array, Object) (Line: 183)
Drupal\views\Form\ViewsFormMainForm->submitForm(Array, Object) (Line: 190)
Drupal\views\Form\ViewsForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('views_form_content_v3_converter_moderated_content', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 224)
Drupal\Core\Form\FormBuilder->getForm(Object, Object, Array) (Line: 2257)
Drupal\views\Plugin\views\display\DisplayPluginBase->elementPreRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 788)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 374)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 446)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 243)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Warning: Undefined array key 0 in Drupal\sitenow_p2lb\P2LbConverter->processSection() (line 156 of modules/custom/sitenow_p2lb/src/P2LbConverter.php).
Drupal\sitenow_p2lb\P2LbConverter->processSection('436') (Line: 68)
Drupal\sitenow_p2lb\P2LbConverter->processSections() (Line: 50)
Drupal\sitenow_p2lb\P2LbConverter->convert() (Line: 39)
Drupal\sitenow_p2lb\Plugin\Action\ConvertParagraphsToLayoutBuilder->execute(Object) (Line: 22)
Drupal\Core\Action\ActionBase->executeMultiple(Array) (Line: 129)
Drupal\system\Entity\Action->execute(Array) (Line: 415)
Drupal\views\Plugin\views\field\BulkForm->viewsFormSubmit(Array, Object) (Line: 183)
Drupal\views\Form\ViewsFormMainForm->submitForm(Array, Object) (Line: 190)
Drupal\views\Form\ViewsForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('views_form_content_v3_converter_moderated_content', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 224)
Drupal\Core\Form\FormBuilder->getForm(Object, Object, Array) (Line: 2257)
Drupal\views\Plugin\views\display\DisplayPluginBase->elementPreRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 788)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 374)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 446)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 243)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)  
```

</p>
</details> 

Doing some debugging right now, I'll come back here with any findings.

**Comment by GaryRidgway** [comment]
I think this functions as outlined now, though I am wondering if anyone else should test now that I have added new code?

I will re-test the two stated sites as well.

**Comment by joewhitsitt** [comment]
>wondering if anyone else should test now that I have added new code

If you outline some general instructions (how to reproduce on main, how to see the fix with this branch) and the type of content that would trip this up to check on other sites, i'd be willing to try it on a couple sites.

**Comment by GaryRidgway** [comment]
> If you outline some general instructions (how to reproduce on main, how to see the fix with this branch) and the type of content that would trip this up to check on other sites, i'd be willing to try it on a couple sites.

Sure, no problem.
This:
https://github.com/uiowa/uiowa/blob/951f5038ce6f1950e156bca78caf606a16a581a9/docroot/modules/custom/sitenow_p2lb/src/P2LbConverter.php#L155-L158
Was changed to this:
https://github.com/uiowa/uiowa/blob/c1eaa12652a50b6639821fdb6428e327e5ef747d/docroot/modules/custom/sitenow_p2lb/src/P2LbConverter.php#L155-L160

Where `$w2d` is this:

https://github.com/uiowa/uiowa/blob/c1eaa12652a50b6639821fdb6428e327e5ef747d/docroot/modules/custom/sitenow_p2lb/src/P2LbConverter.php#L143-L149

So if a column layout had `0` or `flex` layout, it would not index, and error out, as neither `0` nor `flex` were indexes in the associative array. So, testing with some flex layouts might be nice or layouts with 0 columns? not sure if many of those exist though, but i guess they did on HMB so who knows.

**Comment by joewhitsitt** [comment]
Going to test Alan's commit

**Comment by joewhitsitt** [comment]
Off of `main`, confirmed the error with an empty section (no inner paragraphs). Though it spit out errors, it still created the section in layout builder with the expected settings. There was no issue with a section with a single "flex/fluid" paragraph. Switching to `turn_off_p2lb_and_v2`, there was no conversion error. ✅

**Review by GaryRidgway — APPROVED** [review]
Based on Joe's comment, this seems approvable.

**Pull request merged**
