### PR TITLE
Move grad split config to grad split dir.

### PR DESCRIPTION
**Pull request by richardbporter**
#2373 exported the grad site split config into the default config and activated it. We should be able to move it to the grad split directory. I'm having trouble exporting things correctly locally.

### Testing
`blt dsa`

### CODE REVIEW

**Comment by richardbporter** [comment]
Actually, this might be it. Looks all the config was in the split except the split config itself.

**Comment by richardbporter** [comment]
Running `blt dsa` locally to see...

**Comment by richardbporter** [comment]
Nope. We need to disable the split first, then import config. Working on that.

**Comment by joewhitsitt** [comment]
pulling down real quick to test update hook on random site

**Review by joewhitsitt — APPROVED** [review]
removed book from the site i tested

**Comment by joewhitsitt** [comment]
does uiowa need to finish before this one goes out?

**Comment by richardbporter** [comment]
Probably

**Comment by richardbporter** [comment]
The irony here is that we'll probably end up enabling book for everyone.

**Comment by richardbporter** [comment]
But the split config needs to move anyway.

**Pull request merged**
