### PR TITLE
Feature: uids_base section backgrounds and featured images

### PR DESCRIPTION
**Pull request by bspeare**
Work for #1501.

# How to Test 
`blt frontend`

- Add a section background image and verify that it is working with other paragraphs
Screen Shot 2020-05-08 at 2 55 09 PM

- Add a page featured image for a basic and verify that it is rendering as a hero component (http://localhost:3000/components/detail/hero-block--left)

- Verify that with featured image removed, the page title and breadcrumbs display as normal and there is no hero component markup in the html. 

Screen Shot 2020-05-08 at 3 02 17 PM

- Add an article featured image and caption and verify that it is rendering as a hero component. Verify that caption is visible on hover. 

Screen Shot 2020-05-08 at 1 38 39 PM

- Add a page title hero component via layout builder with an image that contains a global caption and verify that caption appears on hover. 

Screen Shot 2020-05-08 at 1 37 48 PM

- Verify that a very long page title will wrap within the hero component

Screen Shot 2020-05-08 at 1 38 43 PM

# Other misc tests

- Verify that tour z-index updates are working https://brand.local.drupal.uiowa.edu/?tour (It looks like tour z-index needs to be set around  `z-index: 600;` to get above admin toolbar. 

Screen Shot 2020-05-08 at 1 39 32 PM

- Verify that Colorbox captions on https://brand.local.drupal.uiowa.edu/showcase appear within the colorbox container without overflowing.  You might need to add an image and caption to test this. 

Screen Shot 2020-05-08 at 1 47 47 PM

- Embed a small image into the card body on https://brand.local.drupal.uiowa.edu/templates/email-signatures and verify that it is not stretched full-width of the container. 

Screen Shot 2020-05-08 at 2 54 18 PM

- Verify that search and menu buttons are aligned when using the tertiary header with toggle menu and that there is no logo tab overlap when search is expanded during sticky scroll. 

Screen Shot 2020-05-08 at 2 58 12 PM

Screen Shot 2020-05-08 at 2 57 42 PM

Screen Shot 2020-05-08 at 2 58 05 PM

### CODE REVIEW

**Comment by bspeare** [comment]
@joewhitsitt How do you want to handle adjusting these images https://github.com/uiowa/uiowa/pull/1539/files#diff-5188d9d53ba02d59f0aec9aadf1e2cdcR69 ?

**Comment by joewhitsitt** [comment]
i can bring this down and test in uiowa_bootstrap, but this should be an easier transition than https://github.com/uiowa/uiowa/pull/1530.

**Review by joewhitsitt — APPROVED** [review]
A few notes, not blockers.

Looks like the breadcrumb overflows the image until the breakpoint kicks in:

Screen Shot 2020-05-08 at 4 29 52 PM

For me the `.joyride-tip-guide` needs a z-index of 502 to get over the admin bar, superfish dropdowns, font awesome icons and the uiowa header.

Regardless, awesome work!

**Comment by bspeare** [comment]
@joewhitsitt Could you take another look at the changes to uiowa_bootstrap that we made yesterday?

**Review by pyrello — APPROVED** [review]
Tested on brand.local.drupal.uiowa.edu and sitenowdemo.local.drupal.uiowa.edu. Very nice work!

**Comment by joewhitsitt** [comment]
I see an issue with the global caption and uiowa_bootstrap. Give me a bit and I can push a fix for this.

**Comment by joewhitsitt** [comment]
"approved" again

**Pull request merged**
