### PR TITLE
Split related content

### PR DESCRIPTION
**Pull request by joewhitsitt**
#219

### CODE REVIEW

**Comment by joewhitsitt** [comment]
This removes related content (entity reference sidebar view block) from the "service" and makes it custom for HR. Would love another eye on this before merge. It doesn't seem to cause issue on sites that were using it (callctr.dentistry) and hr seems to still work (node/713)

**Comment by richardbporter** [comment]
I'm confused - this was already removed from the sync directory for shared sites. It still exists in the HR config and seems to be working on HR right now.

**Comment by richardbporter** [comment]
Ah, I see. The field still exists for all sites.

**Comment by richardbporter** [comment]
Sync worked. No config discrepancies. I think this is fine so that folks do not continue to use the shared field since it does not work. However, splitting basic page for HR is probably not a good idea long term and we'll want to get #220 implemented soon.

**Review by richardbporter — APPROVED** [review]

**Pull request merged**
