### PR TITLE
Rename all site splits to `site` and move to `config/sites` directory.

### LINKED ISSUE #2359: Standardize multisite config split machine names
### Problem
We cannot execute Drush/BLT commands targeting all multisite config splits because the machine names are all different. We (I) documented that multisite splits should be named the same as the URI. In hindsight, having them all be the same would be useful.

Ideally, we would be able to do something like this:
`blt uiowa:multisite:execute 'config-split:export site'`

### Proposed Solution
- [x] #4095
- [x] #4096
- [x] Update multisite split machine names to be "site". 
  - [x] Move site splits to subdirectory under config/sites/
  - [x] Update docs.

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #2359 

### Testing
1. Inspect file changes tab. Although many files were changed, most were just renames to a new directory.
2. Add the following to `blt/local.blt.yml`:
```
  - admissions.uiowa.edu
  - brand.uiowa.edu
  - coronavirus.uiowa.edu
  - genetics.grad.uiowa.edu
  - grad.uiowa.edu
  - hr.uiowa.edu
  - icsa.uiowa.edu
  - ighn.international.uiowa.edu
  - immuno.grad.uiowa.edu
  - iowasuperfund.uiowa.edu
  - pharmacy.uiowa.edu
  - policy.clas.uiowa.edu
  - presidentialsearch.uiowa.edu
  - sitenow.uiowa.edu
  - sppa.uiowa.edu
  - tippie.uiowa.edu
  - transportation.uiowa.edu
  - uiowa.edu
```

3. Run `blt dsa` and closely examine the output for each site. There should be no changes outside of the usual local environment split **besides** the deletion of the previous site split. For example, admissions lists the following:
```
...
 [notice] Synchronized extensions: install config_inspector.
 [notice] Synchronized extensions: install reroute_email.
 [notice] Synchronized extensions: install update.
 [notice] Synchronized extensions: install views_ui.
 [notice] Synchronized extensions: install devel.
 [notice] Synchronized extensions: install stage_file_proxy.
 [notice] Synchronized extensions: uninstall acquia_purge.
 [notice] Synchronized extensions: uninstall siteimprove.
 [notice] Synchronized configuration: delete config_split.config_split.admissions.
 [notice] Synchronized configuration: create system.menu.devel.
 [notice] Synchronized configuration: create tour.tour.views-ui.
...
```

Look out for any modules that get uninstalled and reinstalled which would indicate a gap where both splits are inactive. 

Additionally, visit all these sites in your browser, log in and look for any visual regressions.

4. Unless you have untracked changes in the config directory from other work, you can run `git clean -fd config` because `dsa` results in the recreation of the old config directories. I think this happens because the old split is still active during the update and it recreates the directory.  I tried specifically disabling the old splits but that didn't work. This shouldn't happen once this is deployed to prod. 
5. Run `blt ume 'config-split:export site'` to test exporting all site splits.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
testing so https://github.com/uiowa/uiowa/pull/4111 can move forward with admissions split config.

**Comment by joewhitsitt** [comment]
So far all of the sites synced have deleted the site split except for coronavirus.uiowa.edu. Not sure what is different about that one.
Screen Shot 2021-09-13 at 3 46 28 PM
Screen Shot 2021-09-13 at 3 46 37 PM

**Comment by richardbporter** [comment]
Nice catch. It appears the coronavirus.uiowa.edu split is already named `site` so that one is just being moved to another directory.

**Comment by joewhitsitt** [comment]
Just fyi. Ran step 5 with default in my multisites file:

```
Executing on default...

In ConfigSplitCliService.php line 438:
                                                                               
  The following split is not available: config_split.config_split.site 
```

**Review by joewhitsitt — APPROVED** [review]
Looks good to me. Re-reveals config issues with hr, presidentialsearch and sppa.

Fingers crossed that the recreation of site config directories doesn't make travis or acquia mad.

**Comment by richardbporter** [comment]
> Just fyi. Ran step 5 with default in my multisites file:
> 
> ```
> Executing on default...
> 
> In ConfigSplitCliService.php line 438:
>                                                                                
>   The following split is not available: config_split.config_split.site 
> ```

Yea that is to be expected but it should keep processing sites and not just error out.

**Comment by richardbporter** [comment]
> Looks good to me. Re-reveals config issues with hr, presidentialsearch and sppa.
> 
> Fingers crossed that the recreation of site config directories doesn't make travis or acquia mad.

Yea 🤞🏻. I was going to merge into develop but the HR conflict was, not great.

**Pull request merged**
